### ISSUE TITLE
Mons role fails to generate configuration file (ceph.conf)

### ISSUE THREAD

**Issue by aric49** [ceph/ceph-ansible#1002]
I am attempting to run the ceph-mon role to deploy into Docker containers.  I created a bridge interface on my hosts "br-ceph" and I am attempting run the playbooks against these hosts.  Below is the contents of my group_vars/mon:

```
##########
# DOCKER #
##########

mon_containerized_deployment: true
#mon_containerized_deployment_with_kv: true
# This is currently in ceph-common defaults because it is shared with ceph-nfs
ceph_mon_docker_interface: br-ceph
ceph_mon_docker_subnet: 192.168.1.0/24
ceph_mon_docker_username: ceph
ceph_mon_docker_imagename: daemon
ceph_mon_docker_image_tag: latest
ceph_mon_extra_envs: "MON_NAME={{ ansible_hostname }}" # comma separated variables
#ceph_docker_on_openstack: false
#mon_docker_privileged: false
#mon_docker_net_host: true
```

Below is the error I get when I run the ceph-mon role:

```
TASK [ceph-mon : generate ceph configuration file] *****************************
fatal: [192.168.1.88]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute u'ansible_br-ceph'"}
        to retry, use: --limit @/home/aric/Community/github/comdev/docker-homebrew-ceph/ceph-ansible/site.retry
```

I also tried passing in:   br_ceph (since Ansible facts reports the name of the interface as:  "ansible_br_ceph".   I also tried passing in hardware physical interfaces:  eth0, eth1, etc.   I get the same error message for any interface I pass in. 

Please let me know if you require any further information. 

Thank you for your time.

**Comment by leseb** [comment]
Just to be clear, even with simple interfaces like `eth0` you're getting this error?

**Comment by aric49** [comment]
Yes, correct.   I experimented with all interfaces available with all the hosts I am deploying to:  eth0, eth1, and eth2.   It appears that I can only get the role to run successfully when I specify the interface as:  docker0, which doesn't do any good since we need the containers to be able to talk over the physical network interfaces. Currently I am running Ansible 2.2.0, but I also saw this as well with Ansible 2.1.0

**Comment by aric49** [comment]
I should also add as well we are deploying on Ubuntu 16.04 bare metal hosts with the latest patches.   We are also installing Docker based on these Ansible roles as well.

**Comment by font** [comment]
Are you using server or desktop version of Ubuntu on your hosts? Note that the interface names are different in newer versions e.g. `enpXs0` for server and `enoX` for desktop. You can check with the `ifconfig` or `ip addr` command, or see what the `ansible_interfaces` list variable says about the hosts when collecting Ansible facts.

**Comment by aric49** [comment]
I am running the server version of 16.04.   We are deploying onto four baremetal hosts -- 2 have their primary interfaces defined as `enpXs0`, and the other 2 have `eth0 `as their primary address (These servers were upgraded from 14.04 server).  These interfaces show up when I run the setup module and check the facts.  However, no matter which interface name I pass into the `group_vars/mon`  file, it gives me the same error for all hosts, for example:

```
TASK [ceph-mon : generate ceph configuration file] *****************************
fatal: [192.168.1.100]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute u'ansible_eth0'"}
        to retry, use: --limit @/home/aric/Community/github/comdev/docker-homebrew-ceph/ceph-ansible/site.retry

```

It seems very strange since I can see that these interfaces exist in the ansible facts.  Could it be that the interfaces are not exactly the same on all four hosts I am seeing this issue?

**Comment by leseb** [comment]
If interfaces are not the same on all the host, you would have to set the variables explicitly in your inventory file, something like this:

```
[mons]
ceph-mon-01 ceph_mon_docker_interface=eth0
ceph-mon-01 ceph_mon_docker_interface=enp0s8
```

Please try this out.
