### ISSUE TITLE
suggestion | ceph_conf_override to support client.rgw.X section

### ISSUE THREAD

**Issue by OrFriedmann** [ceph/ceph-ansible#1010]
Hi,
Is it possible to support the sections of each rgw?

Thank you

**Comment by leseb** [comment]
I don't think so, I think I've already tried and it doesn't work.

**Comment by leseb** [comment]
But I'll see how we can improve this.

**Comment by leseb** [comment]
Wait it actually works thanks to @cloudnull, I'm going to submit a PR that will introduce "profiles" in ceph-ansible, starting with keystone v3
