### ISSUE TITLE
'dict object' has no attribute u'ansible_<the network link name with a hyphen>'

### ISSUE THREAD

**Issue by wind0204** [ceph/ceph-ansible#1038]
I guess I have to say that it's an old issue: https://github.com/ceph/ceph-ansible/issues/993 (nvm, it's turned out irrelevant)

I had changed the network link name for ceph public network from eth1/enp?s? to ceph-pub-0 on all the nodes and ran the ansible-playbook
then the errors occurred.

> TASK [ceph.ceph-common : generate ceph configuration file] *********************
> fatal: [0-h0]: FAILED! => {"failed": true, "msg": "'dict object' has no attribute u'ansible_ceph-pub-0'"}
> fatal: [peta-s-227]: FAILED! => {"failed": true, "msg": "'dict object' has no attribute u'ansible_ceph-pub-0'"}
> $ ip addr
> 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
>     link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
>     inet 127.0.0.1/8 scope host lo
>        valid_lft forever preferred_lft forever
>     inet6 ::1/128 scope host 
>        valid_lft forever preferred_lft forever
> 2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq master br0 state UP group default qlen 1000
>     link/ether f4:ce:46:b9:0b:34 brd ff:ff:ff:ff:ff:ff
> 3: ceph-pub-0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
>     link/ether f4:ce:46:b9:0b:36 brd ff:ff:ff:ff:ff:ff
>     inet 192.168.255.254/27 brd 192.168.255.255 scope global ceph-pub-0
>        valid_lft forever preferred_lft forever
>     inet6 fe80::f6ce:46ff:feb9:b36/64 scope link 
>        valid_lft forever preferred_lft forever
> 4: br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
>     link/ether f4:ce:46:b9:0b:34 brd ff:ff:ff:ff:ff:ff
>     inet 116.193.90.131/27 brd 116.193.90.159 scope global br0
>        valid_lft forever preferred_lft forever
>     inet6 fe80::f6ce:46ff:feb9:b34/64 scope link 
>        valid_lft forever preferred_lft forever
> 5: one-65-0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master br0 state UNKNOWN group default qlen 1000
>     link/ether fe:00:74:c1:5a:84 brd ff:ff:ff:ff:ff:ff
>     inet6 fe80::fc00:74ff:fec1:5a84/64 scope link 
>        valid_lft forever preferred_lft forever

# tried the original network link name for the central ansible node:

> $ sed 's/ceph-pub-0/eth1/' < ~/ceph-ansible/group_vars/all > ~/ceph-ansible/group_vars/all
> $ ansible-playbook ~/ceph-ansible/site.yml
> TASK [ceph.ceph-common : generate ceph configuration file] *********************
> fatal: [0-h0]: FAILED! => {"failed": true, "msg": "'dict object' has no attribute 'ipv4'"}
> fatal: [peta-s-227]: FAILED! => {"failed": true, "msg": "'dict object' has no attribute 'ipv4'"}

# tried monitor_address instead of monitor_interface.

> $ vim ~/ceph-ansible/group_vars/all #change from monitor_interface to monitor_address: 192.168.255.227 (it was the ip address for a monitor node)
> $ ansible-playbook ~/ceph-ansible/site.yml
> TASK [ceph.ceph-common : generate ceph configuration file] *********************
> fatal: [peta-s-227]: FAILED! => {"failed": true, "msg": "'dict object' has no attribute u'ansible_interface'"}
> fatal: [0-h0]: FAILED! => {"failed": true, "msg": "'dict object' has no attribute u'ansible_interface'"}

What should I do now?
Any help would be much appreciated!

Best Wishes
From Korea

**Comment by wind0204** [comment]
I hope this would be helpful

doeals0@0-h0:~/ceph-ansible$ cat ~/ceph-ansible/group_vars/osds.txt 

> ---
> dummy:
> 
> devices:
>   - /dev/cciss/c0d1
>   - /dev/cciss/c0d3
>   - /dev/cciss/c0d5
> 
> raw_multi_journal: true
> raw_journal_devices:
>   - /dev/cciss/c0d2
>   - /dev/cciss/c0d4
>   - /dev/cciss/c0d6
> 

doeals0@0-h0:~/ceph-ansible$ cat ~/ceph-ansible/group_vars/all.txt 

> ---
> dummy:
> 
>   ceph_origin: 'upstream'
> 
> ceph_stable: true
> 
> monitor_interface: ceph-pub-0
> journal_size: 2560 # OSD journal size in MB
> public_network: 192.168.255.224/27
> 
> ceph_conf_overrides:
>   osd:
>     osd mkfs type: xfs
> 
>

**Comment by OrFriedmann** [comment]
what is the output of `ansible mons -m setup` ?

**Comment by wind0204** [comment]
@OrFriedmann :)
$ ansible mons -m setup
peta-s-227 | SUCCESS => {
    "ansible_facts": {
        "ansible_all_ipv4_addresses": [
            "192.168.255.227"
        ], 
        "ansible_all_ipv6_addresses": [
            "fe80::221:5aff:feaa:b9b6"
        ], 
        "ansible_architecture": "x86_64", 
        "ansible_bios_date": "05/02/2011", 
        "ansible_bios_version": "P58", 
        "ansible_ceph_pub_0": {
            "active": true, 
            "device": "ceph-pub-0", 
            "ipv4": {
                "address": "192.168.255.227", 
                "broadcast": "192.168.255.255", 
                "netmask": "255.255.255.224", 
                "network": "192.168.255.224"
            }, 
            "ipv6": [
                {
                    "address": "fe80::221:5aff:feaa:b9b6", 
                    "prefix": "64", 
                    "scope": "link"
                }
            ], 
            "macaddress": "00:21:5a:aa:b9:b6", 
            "module": "bnx2", 
            "mtu": 1500, 
            "pciid": "0000:03:00.0", 
            "promisc": false, 
            "type": "ether"
        }, 
        "ansible_cmdline": {
            "BOOT_IMAGE": "/boot/vmlinuz-4.7.0-0.bpo.1-amd64", 
            "quiet": true, 
            "ro": true, 
            "root": "UUID=a07e3346-3b81-44e1-88cd-16afaaa8030f"
        }, 
        "ansible_date_time": {
            "date": "2016-10-19", 
            "day": "19", 
            "epoch": "1476859642", 
            "hour": "15", 
            "iso8601": "2016-10-19T06:47:22Z", 
            "iso8601_basic": "20161019T154722259451", 
            "iso8601_basic_short": "20161019T154722", 
            "iso8601_micro": "2016-10-19T06:47:22.259589Z", 
            "minute": "47", 
            "month": "10", 
            "second": "22", 
            "time": "15:47:22", 
            "tz": "KST", 
            "tz_offset": "+0900", 
            "weekday": "Wednesday", 
            "weekday_number": "3", 
            "weeknumber": "42", 
            "year": "2016"
        }, 
        "ansible_default_ipv4": {
            "address": "192.168.255.227", 
            "alias": "ceph-pub-0", 
            "broadcast": "192.168.255.255", 
            "gateway": "192.168.255.254", 
            "interface": "ceph-pub-0", 
            "macaddress": "00:21:5a:aa:b9:b6", 
            "mtu": 1500, 
            "netmask": "255.255.255.224", 
            "network": "192.168.255.224", 
            "type": "ether"
        }, 
        "ansible_default_ipv6": {}, 
        "ansible_devices": {
            "cciss!c0d0": {
                "holders": [], 
                "host": "RAID bus controller: Hewlett-Packard Company Smart Array Controller (rev 03)", 
                "model": "LOGICAL VOLUME", 
                "partitions": {}, 
                "removable": "0", 
                "rotational": "1", 
                "scheduler_mode": "cfq", 
                "sectors": "143305920", 
                "sectorsize": "512", 
                "size": "68.33 GB", 
                "support_discard": "0", 
                "vendor": "HP"
            }, 
            "cciss!c0d1": {
                "holders": [], 
                "host": "RAID bus controller: Hewlett-Packard Company Smart Array Controller (rev 03)", 
                "model": "LOGICAL VOLUME", 
                "partitions": {}, 
                "removable": "0", 
                "rotational": "1", 
                "scheduler_mode": "cfq", 
                "sectors": "143305920", 
                "sectorsize": "512", 
                "size": "68.33 GB", 
                "support_discard": "0", 
                "vendor": "HP"
            }, 
            "cciss!c0d2": {
                "holders": [], 
                "host": "RAID bus controller: Hewlett-Packard Company Smart Array Controller (rev 03)", 
                "model": "LOGICAL VOLUME", 
                "partitions": {}, 
                "removable": "0", 
                "rotational": "1", 
                "scheduler_mode": "cfq", 
                "sectors": "585871964", 
                "sectorsize": "512", 
                "size": "279.37 GB", 
                "support_discard": "0", 
                "vendor": "HP"
            }, 
            "sr0": {
                "holders": [], 
                "host": "IDE interface: Intel Corporation 631xESB/632xESB IDE Controller (rev 09)", 
                "model": "DW-224E-V", 
                "partitions": {}, 
                "removable": "1", 
                "rotational": "1", 
                "scheduler_mode": "cfq", 
                "sectors": "2097151", 
                "sectorsize": "512", 
                "size": "1024.00 MB", 
                "support_discard": "0", 
                "vendor": "TEAC"
            }
        }, 
        "ansible_distribution": "Debian", 
        "ansible_distribution_major_version": "8", 
        "ansible_distribution_release": "jessie", 
        "ansible_distribution_version": "8.6", 
        "ansible_dns": {
            "nameservers": [
                "164.124.101.2", 
                "210.220.163.82", 
                "168.126.63.1"
            ]
        }, 
        "ansible_domain": "", 
        "ansible_env": {
            "HOME": "/home/ansibled", 
            "LANG": "en_US.UTF-8", 
            "LC_ALL": "en_US.UTF-8", 
            "LC_MESSAGES": "en_US.UTF-8", 
            "LOGNAME": "ansibled", 
            "MAIL": "/var/mail/ansibled", 
            "PATH": "/usr/local/bin:/usr/bin:/bin:/usr/games", 
            "PWD": "/home/ansibled", 
            "SHELL": "/bin/sh", 
            "SSH_CLIENT": "116.193.90.131 54858 22", 
            "SSH_CONNECTION": "116.193.90.131 54858 192.168.255.227 22", 
            "SSH_TTY": "/dev/pts/1", 
            "TERM": "screen-256color", 
            "USER": "ansibled"
        }, 
        "ansible_eth1": {
            "active": false, 
            "device": "eth1", 
            "macaddress": "00:21:5a:aa:b9:bc", 
            "module": "bnx2", 
            "mtu": 1500, 
            "pciid": "0000:05:00.0", 
            "promisc": false, 
            "type": "ether"
        }, 
        "ansible_fips": false, 
        "ansible_form_factor": "Rack Mount Chassis", 
        "ansible_fqdn": "peta-s-227", 
        "ansible_hostname": "peta-s-227", 
        "ansible_interfaces": [
            "lo", 
            "eth1", 
            "ceph-pub-0"
        ], 
        "ansible_kernel": "4.7.0-0.bpo.1-amd64", 
        "ansible_lo": {
            "active": true, 
            "device": "lo", 
            "ipv4": {
                "address": "127.0.0.1", 
                "broadcast": "host", 
                "netmask": "255.0.0.0", 
                "network": "127.0.0.0"
            }, 
            "ipv6": [
                {
                    "address": "::1", 
                    "prefix": "128", 
                    "scope": "host"
                }
            ], 
            "mtu": 65536, 
            "promisc": false, 
            "type": "loopback"
        }, 
        "ansible_lsb": {
            "codename": "jessie", 
            "description": "Debian GNU/Linux 8.6 (jessie)", 
            "id": "Debian", 
            "major_release": "8", 
            "release": "8.6"
        }, 
        "ansible_machine": "x86_64", 
        "ansible_machine_id": "4fc3acca1ef04b888ac5210602e66ee1", 
        "ansible_memfree_mb": 11346, 
        "ansible_memory_mb": {
            "nocache": {
                "free": 11837, 
                "used": 180
            }, 
            "real": {
                "free": 11346, 
                "total": 12017, 
                "used": 671
            }, 
            "swap": {
                "cached": 0, 
                "free": 5858, 
                "total": 5858, 
                "used": 0
            }
        }, 
        "ansible_memtotal_mb": 12017, 
        "ansible_mounts": [
            {
                "device": "/dev/cciss/c0d0p2", 
                "fstype": "ext4", 
                "mount": "/", 
                "options": "rw,relatime,errors=remount-ro,data=ordered", 
                "size_available": 60427100160, 
                "size_total": 66038091776, 
                "uuid": ""
            }
        ], 
        "ansible_nodename": "peta-s-227", 
        "ansible_os_family": "Debian", 
        "ansible_pkg_mgr": "apt", 
        "ansible_processor": [
            "GenuineIntel", 
            "Intel(R) Xeon(R) CPU           E5440  @ 2.83GHz", 
            "GenuineIntel", 
            "Intel(R) Xeon(R) CPU           E5440  @ 2.83GHz", 
            "GenuineIntel", 
            "Intel(R) Xeon(R) CPU           E5440  @ 2.83GHz", 
            "GenuineIntel", 
            "Intel(R) Xeon(R) CPU           E5440  @ 2.83GHz", 
            "GenuineIntel", 
            "Intel(R) Xeon(R) CPU           E5440  @ 2.83GHz", 
            "GenuineIntel", 
            "Intel(R) Xeon(R) CPU           E5440  @ 2.83GHz", 
            "GenuineIntel", 
            "Intel(R) Xeon(R) CPU           E5440  @ 2.83GHz", 
            "GenuineIntel", 
            "Intel(R) Xeon(R) CPU           E5440  @ 2.83GHz"
        ], 
        "ansible_processor_cores": 4, 
        "ansible_processor_count": 2, 
        "ansible_processor_threads_per_core": 1, 
        "ansible_processor_vcpus": 8, 
        "ansible_product_name": "ProLiant DL360 G5", 
        "ansible_product_serial": "NA", 
        "ansible_product_uuid": "NA", 
        "ansible_product_version": "NA", 
        "ansible_python_version": "2.7.9", 
        "ansible_selinux": false, 
        "ansible_service_mgr": "systemd", 
        "ansible_ssh_host_key_dsa_public": "AAAAB3NzaC1kc3MAAACBAMq0dtwabzwreZo07kuYBGjqUeFbqIMHxSWixx3/6BpQAwhrdkvAtUHEYZnmd8KP/TBAMaUfmaqTm4rOwWuDZqPTdalK+LDCDHlUTzViBzQECH6DPaaOWls75KpJfQQVEA6S2zcBVsR5FyZEZ+pRKk71J/K0RxNOnOuRX6VrhfghAAAAFQCsBDik8cYvTwy9X54gAQwTQEyYkwAAAIBHQkFTCzkJFMX5eCKSoApTjdM34JDySM7OxahPcDe//rrkHmfAYKJ+hJdclfxieF44GKvSLoz8+iS2jYGvPzKoV0tZg1CzGoYJ3VMuODqUmIsl5iZGY+vRJEu12wHICl9XI+6FjVl3pX7tqo+sDKGPpzyKg8B7ud6NjxTBSd38pQAAAIBaQBbSDknHO/7dOZhdKyU47CnpZ2AMAtUdCYj9+bTdWP1/yHpN7H6xRzQy6C4mKctXYc/4F2ZJJuet+CBSoi0MLKoomsgl87Ffs5CEJA7fqlEY0AVrUrAADoTye5AL2Vgm5R/7z8lejk/kJ8WhSplXlw/4flvY6pqR6MrpTOH8cg==", 
        "ansible_ssh_host_key_ecdsa_public": "AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBNIF/NimHcWVoM97F9B19zu1RwT9U96axUKcsxhKCzEwRw+lejdOJXADE1Ai2H55ekqhw6PuPctTPwZhRknPl9g=", 
        "ansible_ssh_host_key_ed25519_public": "AAAAC3NzaC1lZDI1NTE5AAAAIIgQb2jkkuMCOPTrZPkL5kEwwizmWPvUtTeGxpdjHAKz", 
        "ansible_ssh_host_key_rsa_public": "AAAAB3NzaC1yc2EAAAADAQABAAABAQC6sv5Cu1SSVliis9xx2WgCBIynMnVSZo5NR0Y/AT0eYSD0j3lSmxWUjHjwmcqXqqBxE/d8V74du4fZaWyVIq1BMpN125fleFL7JbLtUMWzEtMOxIIKLG3HM3Mz6pUfDac+T4QgWJdNITxKrRkWDDICFEFz0KQkxiFc+CtQGOjWpQnRwtHz7QOaMCQG0VHynKFtQwMYewHb+/zuKSMjpy46NwMZl8c/yuxnIBjrlB7lz9+q54rREJBuUFHrcFz5+YCfiYTHxwkwg+JWgLTiI5DLMlKuMPfLaH05CyLAX8m1IQ7Q5LWMl2Pgi4nHaqwQWmmFWG3aHdJtDCBney/KZdX1", 
        "ansible_swapfree_mb": 5858, 
        "ansible_swaptotal_mb": 5858, 
        "ansible_system": "Linux", 
        "ansible_system_vendor": "HP", 
        "ansible_uptime_seconds": 84544, 
        "ansible_user_dir": "/home/ansibled", 
        "ansible_user_gecos": "", 
        "ansible_user_gid": 1002, 
        "ansible_user_id": "ansibled", 
        "ansible_user_shell": "/bin/sh", 
        "ansible_user_uid": 1002, 
        "ansible_userspace_architecture": "x86_64", 
        "ansible_userspace_bits": "64", 
        "ansible_virtualization_role": "host", 
        "ansible_virtualization_type": "kvm", 
        "module_setup": true
    }, 
    "changed": false
}
0-h0 | SUCCESS => {
    "ansible_facts": {
        "ansible_all_ipv4_addresses": [
            "116.193.90.131", 
            "192.168.255.254"
        ], 
        "ansible_all_ipv6_addresses": [
            "fe80::f6ce:46ff:feb9:b34", 
            "fe80::f6ce:46ff:feb9:b36"
        ], 
        "ansible_architecture": "x86_64", 
        "ansible_bios_date": "01/22/2015", 
        "ansible_bios_version": "P64", 
        "ansible_br0": {
            "active": true, 
            "device": "br0", 
            "id": "8000.f4ce46b90b34", 
            "interfaces": [
                "eth0"
            ], 
            "ipv4": {
                "address": "116.193.90.131", 
                "broadcast": "116.193.90.159", 
                "netmask": "255.255.255.224", 
                "network": "116.193.90.128"
            }, 
            "ipv6": [
                {
                    "address": "fe80::f6ce:46ff:feb9:b34", 
                    "prefix": "64", 
                    "scope": "link"
                }
            ], 
            "macaddress": "f4:ce:46:b9:0b:34", 
            "mtu": 1500, 
            "promisc": false, 
            "stp": false, 
            "type": "bridge"
        }, 
        "ansible_ceph_pub_0": {
            "active": true, 
            "device": "ceph-pub-0", 
            "ipv4": {
                "address": "192.168.255.254", 
                "broadcast": "192.168.255.255", 
                "netmask": "255.255.255.224", 
                "network": "192.168.255.224"
            }, 
            "ipv6": [
                {
                    "address": "fe80::f6ce:46ff:feb9:b36", 
                    "prefix": "64", 
                    "scope": "link"
                }
            ], 
            "macaddress": "f4:ce:46:b9:0b:36", 
            "module": "bnx2", 
            "mtu": 1500, 
            "pciid": "0000:02:00.1", 
            "promisc": false, 
            "type": "ether"
        }, 
        "ansible_cmdline": {
            "BOOT_IMAGE": "/vmlinuz-4.7.0-0.bpo.1-amd64", 
            "cgroup_enable": "memory", 
            "quiet": true, 
            "ro": true, 
            "root": "/dev/mapper/0--h0--vg-root", 
            "swapaccount": "1"
        }, 
        "ansible_date_time": {
            "date": "2016-10-19", 
            "day": "19", 
            "epoch": "1476859642", 
            "hour": "15", 
            "iso8601": "2016-10-19T06:47:22Z", 
            "iso8601_basic": "20161019T154722300081", 
            "iso8601_basic_short": "20161019T154722", 
            "iso8601_micro": "2016-10-19T06:47:22.300208Z", 
            "minute": "47", 
            "month": "10", 
            "second": "22", 
            "time": "15:47:22", 
            "tz": "KST", 
            "tz_offset": "+0900", 
            "weekday": "Wednesday", 
            "weekday_number": "3", 
            "weeknumber": "42", 
            "year": "2016"
        }, 
        "ansible_default_ipv4": {
            "address": "116.193.90.131", 
            "alias": "br0", 
            "broadcast": "116.193.90.159", 
            "gateway": "116.193.90.129", 
            "interface": "br0", 
            "macaddress": "f4:ce:46:b9:0b:34", 
            "mtu": 1500, 
            "netmask": "255.255.255.224", 
            "network": "116.193.90.128", 
            "type": "bridge"
        }, 
        "ansible_default_ipv6": {}, 
        "ansible_devices": {
            "sda": {
                "holders": [], 
                "host": "RAID bus controller: Hewlett-Packard Company Smart Array G6 controllers (rev 01)", 
                "model": "LOGICAL VOLUME", 
                "partitions": {
                    "sda1": {
                        "sectors": "497664", 
                        "sectorsize": 512, 
                        "size": "243.00 MB", 
                        "start": "2048"
                    }, 
                    "sda2": {
                        "sectors": "2", 
                        "sectorsize": 512, 
                        "size": "1.00 KB", 
                        "start": "501758"
                    }, 
                    "sda5": {
                        "sectors": "142802944", 
                        "sectorsize": 512, 
                        "size": "68.09 GB", 
                        "start": "501760"
                    }
                }, 
                "removable": "0", 
                "rotational": "1", 
                "scheduler_mode": "cfq", 
                "sectors": "143305920", 
                "sectorsize": "512", 
                "size": "68.33 GB", 
                "support_discard": "0", 
                "vendor": "HP"
            }, 
            "sdb": {
                "holders": [], 
                "host": "RAID bus controller: Hewlett-Packard Company Smart Array G6 controllers (rev 01)", 
                "model": "LOGICAL VOLUME", 
                "partitions": {
                    "sdb1": {
                        "sectors": "134217728", 
                        "sectorsize": 512, 
                        "size": "64.00 GB", 
                        "start": "2048"
                    }, 
                    "sdb2": {
                        "sectors": "152457311", 
                        "sectorsize": 512, 
                        "size": "72.70 GB", 
                        "start": "134219776"
                    }
                }, 
                "removable": "0", 
                "rotational": "1", 
                "scheduler_mode": "cfq", 
                "sectors": "286677120", 
                "sectorsize": "512", 
                "size": "136.70 GB", 
                "support_discard": "0", 
                "vendor": "HP"
            }, 
            "sdc": {
                "holders": [
                    "vg--one--0-lv--one"
                ], 
                "host": "RAID bus controller: Hewlett-Packard Company Smart Array G6 controllers (rev 01)", 
                "model": "LOGICAL VOLUME", 
                "partitions": {}, 
                "removable": "0", 
                "rotational": "1", 
                "scheduler_mode": "cfq", 
                "sectors": "143305920", 
                "sectorsize": "512", 
                "size": "68.33 GB", 
                "support_discard": "0", 
                "vendor": "HP"
            }
        }, 
        "ansible_distribution": "Debian", 
        "ansible_distribution_major_version": "8", 
        "ansible_distribution_release": "jessie", 
        "ansible_distribution_version": "8.6", 
        "ansible_dns": {
            "nameservers": [
                "164.124.101.2", 
                "210.220.163.82", 
                "8.8.8.8"
            ]
        }, 
        "ansible_domain": "", 
        "ansible_env": {
            "HOME": "/home/ansibled", 
            "LANG": "en_US.UTF-8", 
            "LC_ALL": "en_US.UTF-8", 
            "LC_MESSAGES": "en_US.UTF-8", 
            "LOGNAME": "ansibled", 
            "MAIL": "/var/mail/ansibled", 
            "PATH": "/usr/local/bin:/usr/bin:/bin:/usr/games", 
            "PWD": "/home/ansibled", 
            "SHELL": "/bin/sh", 
            "SSH_CLIENT": "116.193.90.131 38318 22", 
            "SSH_CONNECTION": "116.193.90.131 38318 116.193.90.131 22", 
            "SSH_TTY": "/dev/pts/9", 
            "TERM": "screen-256color", 
            "USER": "ansibled", 
            "XDG_RUNTIME_DIR": "/run/user/9871", 
            "XDG_SESSION_ID": "3062"
        }, 
        "ansible_eth0": {
            "active": true, 
            "device": "eth0", 
            "macaddress": "f4:ce:46:b9:0b:34", 
            "module": "bnx2", 
            "mtu": 1500, 
            "pciid": "0000:02:00.0", 
            "promisc": true, 
            "type": "ether"
        }, 
        "ansible_fips": false, 
        "ansible_form_factor": "Rack Mount Chassis", 
        "ansible_fqdn": "0-h0", 
        "ansible_hostname": "0-h0", 
        "ansible_interfaces": [
            "eth0", 
            "lo", 
            "br0", 
            "ceph-pub-0"
        ], 
        "ansible_kernel": "4.7.0-0.bpo.1-amd64", 
        "ansible_lo": {
            "active": true, 
            "device": "lo", 
            "ipv4": {
                "address": "127.0.0.1", 
                "broadcast": "host", 
                "netmask": "255.0.0.0", 
                "network": "127.0.0.0"
            }, 
            "ipv6": [
                {
                    "address": "::1", 
                    "prefix": "128", 
                    "scope": "host"
                }
            ], 
            "mtu": 65536, 
            "promisc": false, 
            "type": "loopback"
        }, 
        "ansible_lsb": {
            "codename": "jessie", 
            "description": "Debian GNU/Linux 8.6 (jessie)", 
            "id": "Debian", 
            "major_release": "8", 
            "release": "8.6"
        }, 
        "ansible_machine": "x86_64", 
        "ansible_machine_id": "b89478e02e31421cbab6fc82dfe0da6e", 
        "ansible_memfree_mb": 12176, 
        "ansible_memory_mb": {
            "nocache": {
                "free": 13268, 
                "used": 753
            }, 
            "real": {
                "free": 12176, 
                "total": 14021, 
                "used": 1845
            }, 
            "swap": {
                "cached": 0, 
                "free": 2871, 
                "total": 2871, 
                "used": 0
            }
        }, 
        "ansible_memtotal_mb": 14021, 
        "ansible_mounts": [
            {
                "device": "/dev/dm-0", 
                "fstype": "ext4", 
                "mount": "/", 
                "options": "rw,relatime,errors=remount-ro,data=ordered", 
                "size_available": 61442740224, 
                "size_total": 68863770624, 
                "uuid": ""
            }, 
            {
                "device": "/dev/sda1", 
                "fstype": "ext2", 
                "mount": "/boot", 
                "options": "rw,relatime,block_validity,barrier,user_xattr,acl", 
                "size_available": 172999680, 
                "size_total": 246755328, 
                "uuid": ""
            }, 
            {
                "device": "/dev/mapper/vg--one--0-lv--one", 
                "fstype": "ext4", 
                "mount": "/var/lib/one", 
                "options": "rw,relatime,block_validity,delalloc,barrier,user_xattr,acl", 
                "size_available": 15506403328, 
                "size_total": 149049409536, 
                "uuid": ""
            }
        ], 
        "ansible_nodename": "0-h0", 
        "ansible_os_family": "Debian", 
        "ansible_pkg_mgr": "apt", 
        "ansible_processor": [
            "GenuineIntel", 
            "Intel(R) Xeon(R) CPU           E5506  @ 2.13GHz", 
            "GenuineIntel", 
            "Intel(R) Xeon(R) CPU           E5506  @ 2.13GHz", 
            "GenuineIntel", 
            "Intel(R) Xeon(R) CPU           E5506  @ 2.13GHz", 
            "GenuineIntel", 
            "Intel(R) Xeon(R) CPU           E5506  @ 2.13GHz", 
            "GenuineIntel", 
            "Intel(R) Xeon(R) CPU           E5506  @ 2.13GHz", 
            "GenuineIntel", 
            "Intel(R) Xeon(R) CPU           E5506  @ 2.13GHz", 
            "GenuineIntel", 
            "Intel(R) Xeon(R) CPU           E5506  @ 2.13GHz", 
            "GenuineIntel", 
            "Intel(R) Xeon(R) CPU           E5506  @ 2.13GHz"
        ], 
        "ansible_processor_cores": 4, 
        "ansible_processor_count": 2, 
        "ansible_processor_threads_per_core": 1, 
        "ansible_processor_vcpus": 8, 
        "ansible_product_name": "ProLiant DL360 G6", 
        "ansible_product_serial": "NA", 
        "ansible_product_uuid": "NA", 
        "ansible_product_version": "NA", 
        "ansible_python_version": "2.7.9", 
        "ansible_selinux": false, 
        "ansible_service_mgr": "systemd", 
        "ansible_ssh_host_key_dsa_public": "AAAAB3NzaC1kc3MAAACBAKN6YU+yFj6lB6QNqwniqUxfP0/XrfjxPdJkrtQO3Af8MWkN3AzNufHzynlx1zCW2YOlLIeFmiu8Qf871YnsrDg9oO/Yzdytk29G1cy8sV0C8O1dXJYRV64M4HKCeBCMOC56Vh+QO5JcC/v3baPxgN7UwOqvL08mSBgN6BqVWmCVAAAAFQCuI1YwCAU/fsCo/PNsfeu7vT/SJQAAAIB+lHKnOIJtc608anvwPERoUPGqvkHy9oT6o62oWRVugx7HZcRak87QsWe4DAwr78Qk92x82I0+9vdx+MS8rZmiKr+VW2gJ8QLIsgkMXG5nyyEusaluWbp9f3wSYFA1zWRIAJMqcL9TnO8msS/yLDxXg8oJTh6kC94Bpigx+Msh2QAAAIEAoGjM41GLVFujwPVrFj4IFH82hb89KB79o5WIWA29/kSmFyuXF2/JJ/Gq501cBH/w5//0dQfIfdAp0vfuRWfp/QoDGdBvRDbOtHhzBfWhwAl6eVwK8KzjUHp5LOW8gK8AWrogz5ub2/NHI9Gx5zCr0rd3tQHuS4zN5SjiUsCPc6k=", 
        "ansible_ssh_host_key_ecdsa_public": "AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBMB0U6IjGm94sbhR6Hu/vVzvKEemHbC3S1dN23czdDKkPrCHDtLvwVrQklUrd3swL4AieepPJgfBvP0Oob/6xxQ=", 
        "ansible_ssh_host_key_ed25519_public": "AAAAC3NzaC1lZDI1NTE5AAAAIJviLotrlaI8+kfz4x6Iv0ewS81J+UHh1h4fI2E4hUdw", 
        "ansible_ssh_host_key_rsa_public": "AAAAB3NzaC1yc2EAAAADAQABAAABAQDEkghzaCDS3Gf/nz4fYBMgqGMidkSdMWntwhk0HSv7StksVD2oGUJCNk+M9ETDg5x8p0wxRDBCne4x1nPS8QeOsYMZOI6wWTmx93pH/XbLV0Qk7hHkXHETYdwfdyL/306JaWZ837KOBavR5XzfdH+T+sxYbQBCbliDrHF93lHzeFkdgfWEpJeFi5l+m9eRqDwOj556049QRbHxxX/PMc7wmHt+ZlLAg1SuS0scvWmTaSXJ9SREyijtiMhGJwobMY4V+BoqtwDOz/aNXUgB7q+Zu1HJMzAV8B1XvNnZthjdraHoHx+raN8R+7u/OJHPBfBMr7yV69b2yLKttWwoCfi1", 
        "ansible_swapfree_mb": 2871, 
        "ansible_swaptotal_mb": 2871, 
        "ansible_system": "Linux", 
        "ansible_system_vendor": "HP", 
        "ansible_uptime_seconds": 84218, 
        "ansible_user_dir": "/home/ansibled", 
        "ansible_user_gecos": "", 
        "ansible_user_gid": 9871, 
        "ansible_user_id": "ansibled", 
        "ansible_user_shell": "/bin/sh", 
        "ansible_user_uid": 9871, 
        "ansible_userspace_architecture": "x86_64", 
        "ansible_userspace_bits": "64", 
        "ansible_virtualization_role": "host", 
        "ansible_virtualization_type": "kvm", 
        "module_setup": true
    }, 
    "changed": false
}

**Comment by wind0204** [comment]
@OrFriedmann you got it! it had u'ansible_ceph_pub_0' instead of u'ansible_ceph-pub-0' :) I'm almost new at python and any computer science thing so I couldn't do the job; but I guess we should make the network_interface@ceph-ansible/group_vars/all stripped. ('-' -> '_')

**Comment by leseb** [comment]
@wind0204 closing this since it seems to be solved.

**Comment by wind0204** [comment]
@OrFriedmann Do you think it's really solved like @leseb said?

**Comment by OrFriedmann** [comment]
I saw this error for several times, it happens when someone write wrong interface so it looks like it is the same thing.

**Comment by wind0204** [comment]
@OrFriedmann I didn't write it wrong though, you see; ceph-pub-0 in ip addr and group_var/all

**Comment by leseb** [comment]
ceph-ansible will only use what Ansible sees, I know it might be confusing to have an interface named `ansible_ceph-pub-0` on the host and this being reported as `ansible_ceph_pub_0` but that's the way things are.

In ceph-ansible we are just using the interface name that you are setting and we don't check if it exists, it's a check you have to run by yourself by using the setup module, just like you did.

Now, is it still an issue for you after setting `ansible_ceph_pub_0`?
Thanks!

**Comment by wind0204** [comment]
@leseb 
it is. I guess could just replace the genuine 'ceph-pub-0' with a makeshift string like 'ceph_pub_0' in the file named group_vars/all though; you want me to just use the makeshift replacement?

**Comment by wind0204** [comment]
see; it's got a property with the original name of the network link, which is named "device"; and I guess it's a good point to start resolving the issue. I wish I was well experienced in python, ansible and other software stuff so I could contribute to ceph-ansible.

```
"ansible_ceph_pub_0": {
            "active": true, 
            "device": "ceph-pub-0", 
            "ipv4": {
                "address": "192.168.255.227", 
                "broadcast": "192.168.255.255", 
                "netmask": "255.255.255.224", 
                "network": "192.168.255.224"
            }, 
            "ipv6": [
                {
                    "address": "fe80::221:5aff:feaa:b9b6", 
                    "prefix": "64", 
                    "scope": "link"
                }
            ], 
            "macaddress": "00:21:5a:aa:b9:b6", 
            "module": "bnx2", 
            "mtu": 1500, 
            "pciid": "0000:03:00.0", 
            "promisc": false, 
            "type": "ether"
        }, 
```

**Comment by wind0204** [comment]
please check out my pull request.

**Comment by leseb** [comment]
Fixed in https://github.com/ceph/ceph-ansible/pull/1045
