### ISSUE TITLE
CentOS extras repository fails.

### ISSUE THREAD

**Issue by whatevsz** [ceph/ceph-ansible#1041]
### Problem

Commit https://github.com/ceph/ceph-ansible/commit/9de16e4d94bd01875520be6c140836af9515ca62 enabled configuration of the "extras" repo on CentOS.

However, this fails with the following message:

```
Parameter 'baseurl' or 'mirrorlist' is required.
```

As it says, the ansible [yum_repository module](https://docs.ansible.com/ansible/yum_repository_module.html) needs either `baseurl` or `mirrorlist`, which is missing in the task.

Of course this could be added easily, but I'm not sure how to ensure that we do not break existing setups by specifying a hardcoded URL. I guess we should make this configurable?

I would create a pull request when we agree on a way to proceed.
### Tested with

```
ansible 2.1.1.0
ceph-ansible f7680b99b216a85d3874ab2e741f0fecea63af61
```
### Workaround

The new code can be disabled by skipping tag `with_pkg`

_Update_: This does not work because `tags` is not formed as a list.

**Comment by verdurin** [comment]
Thanks for reporting this and sorry for the inconvenience. 

I went by the module documentation for `yum_repository`, which at least in the versions I'm using doesn't list those parameters as mandatory. Hmmph.

Looks like https://github.com/ansible/ansible-modules-extras/pull/2820 would be a way of achieving what I originally intended.

In the absence of that, I'm happy to revert the original method and use `init_file`, unless and until the `yum_repo_enabler` module is accepted.

**Comment by verdurin** [comment]
I've tried to address this in https://github.com/ceph/ceph-ansible/pull/1042

**Comment by whatevsz** [comment]
Thank you for the fast response!

A bit odd that the ansible maintainer doesn't want to implement this funcionality in `yum_repository` ...

I will test your pull request this evening. An alternative to using `ini_file` could also be shelling out to `yum-config-manager --enable <repo>`, this would save us from having to hard core the repo file path in the task.

Another thing I stumbled apon: Shouldn't
```
   tags:
      with_pkg
```
be
```
   tags:
      - with_pkg
```
?

**Comment by verdurin** [comment]
Bah - yes, it should. Will fix that tonight.

**Comment by alfredodeza** [comment]
#1042 doesn't address this. The issue is introduced in 9de16e4d

Please check the CI build output when submitting PRs. The error appears in all the runs

**Comment by leseb** [comment]
Fixed
