### ISSUE TITLE
yum_repository is not a legal parameter in an Ansible task or handler

### ISSUE THREAD

**Issue by vasukulkarni** [ceph/ceph-ansible#1056]
Ansible version is 1.9.4
using the latest ceph-ansible upstream repo
extra vars set to pickup upstream ceph build:

(venv)ubuntu@mira046:~/ceph-ansible$ ansible-playbook -v --extra-vars '{"ceph_dev_branch": "master", "ceph_conf_overrides": {"global": {"osd default pool size": 2, "osd pool default pg num": 128, "osd pool default pgp num": 128}}, "ceph_test": true, "ceph_dev_key": "https://download.ceph.com/keys/autobuild.asc", "journal_collocation": true, "ceph_origin": "upstream", "ceph_dev": true, "osd_auto_discovery": true, "journal_size": 1024}' -i inven.yml site.yml
ERROR: yum_repository is not a legal parameter in an Ansible task or handler

If you need the system access, let me know, will keep it in same state.

inventory:
[clients]
mira027.front.sepia.ceph.com monitor_interface='eth0' public_network='172.21.0.0/20'

[mons]
mira027.front.sepia.ceph.com monitor_interface='eth0' public_network='172.21.0.0/20'
mira046.front.sepia.ceph.com monitor_interface='eth0' public_network='172.21.0.0/20'

[osds]
mira027.front.sepia.ceph.com monitor_interface='eth0' public_network='172.21.0.0/20'
mira046.front.sepia.ceph.com monitor_interface='eth0' public_network='172.21.0.0/20'

**Comment by vasukulkarni** [comment]
thanks to @tmuthamizhan who has been try to get good run

**Comment by andrewschoen** [comment]
This is because the ``yum_repository`` module was added in ansible version 2.1 and won't work if you're running ansible==1.9.4.

What version of ceph-ansible are you using again?

**Comment by tmuthamizhan** [comment]
ansible 1.9.4 is what we are using

**Comment by vasukulkarni** [comment]
@andrewschoen this just uses latest master clone

**Comment by vasukulkarni** [comment]
is the minimum supported version now has to be at 2.1 now? if you master repo

**Comment by andrewschoen** [comment]
@vasukulkarni yeah, I believe the current state of master does require 2.1

**Comment by vasukulkarni** [comment]
@andrewschoen thanks, works with 2.1
