### ISSUE TITLE
rgw: error is logged when binding civetweb to an ip

### ISSUE THREAD

**Issue by Chrislevi** [ceph/ceph-ansible#1062]
- roles/ceph-common/templates/ceph.conf.j2 (line 101)
Seems like when inserting an ip with the port in this line "rgw frontends = civetweb port={{ radosgw_civetweb_bind_ip }}:{{ radosgw_civetweb_port }}" it logs an error.

According to this guide it should be only port.
http://docs.ceph.com/docs/master/start/quick-rgw/

Error:
"radosgw[539165]: error parsing int: 1.2.3.4:1234 The option value '1.2.3.4:1234' seems to be invalid"

Found this bug, yet I assume it hasnt been dealt with.
http://tracker.ceph.com/issues/16581

Any regards on how this could affect RadosGW? 

Thanks,
Chris

**Comment by leseb** [comment]
We know it's some sort of a harmless bug for now.
In the end, rgw listens on the right IP, did you encounter any issue with your rgw?

**Comment by Chrislevi** [comment]
Actually, im encountering an issue with configuring rgw to work with keystone v3 api. seems like every config I've tried through the whole web is failing so I thought this might have been my problem. apparently not though can I email you for assistance since its not really about this issue and I dont want to spam this issue.

**Comment by leseb** [comment]
If you want to configure OpenStack Keystone v3 with rgw you can have a look at this function: https://github.com/openstack/devstack-plugin-ceph/blob/master/devstack/lib/ceph#L494-L528

For more config options see this current PR: https://github.com/ceph/ceph-ansible/pull/1018/files

Let me know if that works, we can continue the discussion here :)
