### ISSUE TITLE
Multiple OSDs per disk

### ISSUE THREAD

**Issue by cdwertmann** [ceph/ceph-ansible#1064]
This is a feature request:

Several Ceph experts at the recent Openstack summit recommended to use more than one OSD per NVMe/SSD drive to achieve the best performance. Flash storage can handle parallel access exceptionally well, therefore splitting a SSD drive into two OSD partitions (plus journal partition) and four OSD partitions per NVMe drive were recommended.

Could we have a ceph-ansible option to select how many OSD partitions per disk are created? Ansible can then split the available storage by that number and automatically create the respective partitions.

Thank you!

**Comment by leseb** [comment]
The easiest way to do this and to avoid disruptive changes is to create a new playbook to do the partition of the device. Then one we have all the partitions we ask ceph-ansible to re-use them and create the OSDs.

**Comment by guits** [comment]
Closed due to inactivity, feel free to re-open if needed. Thanks!
