### ISSUE TITLE
Rolling upgrade playbook should allow you to overwrite upgrade_ceph_packages

### ISSUE THREAD

**Issue by fiskn** [ceph/ceph-ansible#1071]
If you normally don't want your package manager to update Ceph packages when calling the ceph roles, then you would set variable upgrade_ceph_packages to False. However, unless I am misunderstanding things, this would stop the rolling upgrade playbook from working.

Should the rolling playbook allow you to override this variable? If so I will generate a PR.

**Comment by leseb** [comment]
What's the use case? Are you doing some image based upgrades or something and don't use any package manager?
Sounds reasonable to me anyway, please send a PR :)

**Comment by fiskn** [comment]
I might have misunderstood how this works, but if upgrade_ceph_packages is set to true, won't everytime you call the ceph-common role it will try and upgrade ceph packages, if there is a new point release available? In which case you might want to keep this variable set to false. But then the rolling upgrade playbook won't do anything?

**Comment by leseb** [comment]
Correct if this is set to true, every time you run `rolling_update.yml` it will call `ceph-common` and if there is any update on the package repo then Ceph will get updated.
Since this is a rolling upgrade playbook we want to have this set to True.

**Comment by fiskn** [comment]
Right, but ceph-common is a dependency of the other roles. So if I had another playbook which calls ceph-osd for example to either install a new disk or maybe update config options, would that not mean that if upgrade_ceph_packages is set to true, it would try and upgrade the packages as well. This would not be the desired outcome and so you would want the group_vars/all upgrade_ceph_packages set to False and only override in rolling_update.yml.

**Comment by leseb** [comment]
By default and when not called from `rolling_update.yml`, the value of `upgrade_ceph_packages` is false, see: https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-common/defaults/main.yml#L34. Only  `rolling_update.yml` turns it to true.

**Comment by fiskn** [comment]
Sorry, I think I am misunderstanding something. I understand that default behaviour is false but where in rolling_update.yml does upgrade_ceph_packages get set to true?

**Comment by leseb** [comment]
WTF, oh man I removed it in this commit: https://github.com/ceph/ceph-ansible/commit/f49bf2832c9c150ba3c487d75ae96daed97049b6

So it hasn't been updating anything since then...

**Comment by fiskn** [comment]
Ah right, thought I missing something obvious. Glad we have got to the bottom of it.

**Comment by leseb** [comment]
It was just me being so convinced but then came the `git grep` and I realized my terrible mistake.
THANKS for spotting this one.
