### ISSUE TITLE
shrink-mon: add a warning if there is only one mon

### ISSUE THREAD

**Issue by leseb** [ceph/ceph-ansible#1083]

**Comment by guits** [comment]
Hi leseb,

from what I understood, you would want a warning that prompt you if you are about to shrink the only one mon present in the cluster.

It would be great to do a conditional `vars_prompt` but this is something not allowed in ansible.

I think a task displaying a simple warning is not enough.

**Comment by leseb** [comment]
You're right, let's go with the "fail" solution if only one mon is found.
Thanks maggle!
