### ISSUE TITLE
rolling-update.yml needs monitor_interface defined in group_vars file

### ISSUE THREAD

**Issue by vasukulkarni** [ceph/ceph-ansible#1094]
i have hosts file that has monitor interface defined, 
[mons]
node1 monitor_interface=ens3

this works with regular install, but if i use the rolling-update playbook it fails and needs the var to be defined in group_vars

TASK: [ceph-common | make sure monitor_interface or monitor_address is configured] *** 
failed: [mon-node] => {"failed": true}
msg: monitor_interface or monitor_address must be configured. Interface for the monitor to listen on or IP address of that interface

FATAL: all hosts have already failed -- aborting

**Comment by leseb** [comment]
Solved by #1093

**Comment by vasukulkarni** [comment]
@leseb I think this is different, @andrewschoen do you know if this is fixed in master?

**Comment by andrewschoen** [comment]
@vasukulkarni I think it is different, but I also see that in the hosts file you pasted in the description your mon is ``node1``, where the ansible output shows ``mon-node``. Did you have ``monitor_interace`` or ``monitor_address`` defined for ``mon-node``?

**Comment by vasukulkarni** [comment]
@andrewschoen thanks, you can ignore the node name, it was lengthy name and i just wanted to give a short name here for the issue.

**Comment by leseb** [comment]
@vasukulkarni sorry I though #1093 did fix it since it imported all the variables.

**Comment by andrewschoen** [comment]
@vasukulkarni ok, but are you sure you have everything defined correctly? I can't see how ``ansible-playbook -i /path/to/hosts site.yml`` would be any different than ``ansible-playbook -i /path/to/hosts rolling_update.yml`` in regards to using vars defined in your inventory.

**Comment by vasukulkarni** [comment]
@leseb np, @andrewschoen yep, it was just my typo here, i have the same confusion as well how the site works with same hosts but not upgrade, i can give you the setup if you want.
