### ISSUE TITLE
Playbook doesn't work with ansible 2.2.0.0-1ppa~xenial

### ISSUE THREAD

**Issue by MedourMehdi** [ceph/ceph-ansible#1095]
Hi

You have to force the ansible version in install-ansible.sh

A lot of errors occures with v 2.2.0, so apt-get install ansible=2.0.0.2-2 fixed my issues

**Comment by leseb** [comment]
Work is here, this will be merged this week https://github.com/ceph/ceph-ansible/pull/1068
Thanks!
