### ISSUE TITLE
New Pool

### ISSUE THREAD

**Issue by rlljorge** [ceph/ceph-ansible#1108]
Hi,

I have a cluster running with disks SATA and journals using SSDs. Now I need a new pool using only SSD disks.
If I add up 3 new SSD ( 1 per host ), Can I create a new pool using this SSD only ?

**Comment by leseb** [comment]
Yes you can. Follow this: http://www.sebastien-han.fr/blog/2014/08/25/ceph-mix-sata-and-ssd-within-the-same-box/
