### ISSUE TITLE
Correct procedure for replacing disk with raw multi journal

### ISSUE THREAD

**Issue by fiskn** [ceph/ceph-ansible#1116]
Example config:
devices:
  - /dev/sda
  - /dev/sdb
  - /dev/sdc
raw_journal_devices:
   - /dev/nvme0n1
   - /dev/nvme0n1
   - /dev/nvme0n1

Say I need to replace disk sdb, how do I make ansible/ceph-disk reuse the 2nd nvme partition? From what I can see in ceph-disk (https://github.com/ceph/ceph/blob/master/src/ceph-disk/ceph_disk/main.py#L1539), it will try and find the 1st free space on the device and create a partition. In the case of a disk replacement the disk will be empty but the journal partition will still exist and so will create a new partition at the end of the device.

I see a couple of ways to accomplish this:
1. Delete the journal partition so ceph-disk see's this as free space and will attempt to create new partition in it, but does this cause problems with (https://github.com/ceph/ceph/blob/master/src/ceph-disk/ceph_disk/main.py#L2065)?

2. Create a separate disk replacement playbook with variables overridden, something like
devices:
  - /dev/sdb
raw_journal_devices:
   - /dev/nvme0n1p2

3. I have 400G NVME and only 4G partitions, why do I care, just let it keep creating new journal partitions :-)

Any views?

**Comment by leseb** [comment]
I think the easiest way for now I just like you described is to delete the journal partition.
The second method won't work because we need a full device, you cannot give the specific partition AFAIK.

And yes, even with a 100GB SSD you would have room for a couple of dead OSDs too. So with 400GB you should be good.

**Comment by fiskn** [comment]
Ok, thanks. I will proceed with option 1 for now.

**Comment by k0ste** [comment]
I test first method and it works fine.

```shell
ceph-disk deactivate --cluster ceph --deactivate-by-id 18 --mark-out
ceph-disk destroy --cluster ceph --destroy-by-id 18 --zap
```

Then you can easy find partiotion number via `ceph-disk list` and delete this number via `fdisk` or `parted`.

After this run `infrastructure-playbooks/osd-configure.yml`.
