### ISSUE TITLE
Let radosgw listen on localhost ?

### ISSUE THREAD

**Issue by mistur** [ceph/ceph-ansible#1126]
Hello,

I'd like to force radosgw to listen on localhost instead of the nic interface 

On my previous cluster in infernalis, by default, radosgw daemon was listening on localhost but not anymore on my jewel cluster.

is that something I can set in the config ?

Thx

Yoann

**Comment by leseb** [comment]
https://github.com/ceph/ceph-ansible/blob/master/group_vars/all.yml.sample#L288

`radosgw_civetweb_bind_ip: 127.0.0.1`
