### ISSUE TITLE
ERROR: package is not a legal parameter in an Ansible task or handler

### ISSUE THREAD

**Issue by rlljorge** [ceph/ceph-ansible#1136]
I updated my git repo and tried re-execute site.yum because I going add new servers in cluster in two weeks,

root@deploy:/opt/ceph-ansible# git pull
Already up-to-date.
root@deploy:/opt/ceph-ansible# ansible-playbook site.yml
ERROR: package is not a legal parameter in an Ansible task or handler

root@deploy:/opt/ceph-ansible# ansible-playbook --version
ansible-playbook 1.9.4
  configured module search path = None
root@deploy:/opt/ceph-ansible#

I need do something ?

**Comment by leseb** [comment]
Please switch to the ansible-1.9 branch

**Comment by leseb** [comment]
Or update to at least Ansible 2.0

**Comment by rlljorge** [comment]
TASK: [ceph-osd | start and add that the osd service(s) to the init sequence (for or after infernalis)] ***
failed: [osd01] => (item=1) => {"changed": false, "failed": true, "item": "1"}
msg: Job for ceph-osd@1.service failed because a timeout was exceeded. See "systemctl status ceph-osd@1.service" and "journalctl -xe" for details.

failed: [osd01] => (item=5) => {"changed": false, "failed": true, "item": "5"}
msg: Job for ceph-osd@5.service failed because a timeout was exceeded. See "systemctl status ceph-osd@5.service" and "journalctl -xe" for details.

failed: [osd03] => (item=2) => {"changed": false, "failed": true, "item": "2"}
msg: Job for ceph-osd@2.service failed because a timeout was exceeded. See "systemctl status ceph-osd@2.service" and "journalctl -xe" for details.

failed: [osd02] => (item=0) => {"changed": false, "failed": true, "item": "0"}
msg: Job for ceph-osd@0.service failed because a timeout was exceeded. See "systemctl status ceph-osd@0.service" and "journalctl -xe" for details.

failed: [osd02] => (item=3) => {"changed": false, "failed": true, "item": "3"}
msg: Job for ceph-osd@3.service failed because a timeout was exceeded. See "systemctl status ceph-osd@3.service" and "journalctl -xe" for details.

failed: [osd01] => (item=8) => {"changed": false, "failed": true, "item": "8"}
msg: Job for ceph-osd@8.service failed because a timeout was exceeded. See "systemctl status ceph-osd@8.service" and "journalctl -xe" for details.

failed: [osd03] => (item=4) => {"changed": false, "failed": true, "item": "4"}
msg: Job for ceph-osd@4.service failed because a timeout was exceeded. See "systemctl status ceph-osd@4.service" and "journalctl -xe" for details.

failed: [osd02] => (item=6) => {"changed": false, "failed": true, "item": "6"}
msg: Job for ceph-osd@6.service failed because a timeout was exceeded. See "systemctl status ceph-osd@6.service" and "journalctl -xe" for details.

failed: [osd03] => (item=7) => {"changed": false, "failed": true, "item": "7"}
msg: Job for ceph-osd@7.service failed because a timeout was exceeded. See "systemctl status ceph-osd@7.service" and "journalctl -xe" for details.
