### ISSUE TITLE
'sudo' required to run ceph after client is setup

### ISSUE THREAD

**Issue by vasukulkarni** [ceph/ceph-ansible#1143]
After a client is setup using ceph-client role,  following are the permission on the keyring

ubuntu@mira022:~/cephtest/mnt.0/client.0/tmp$ ls -lt /etc/ceph/
total 12
-rw------- 1 ceph ceph 129 Dec  2 01:09 ceph.client.admin.keyring
-rw-r--r-- 1 ceph ceph 689 Dec  2 01:09 ceph.conf
-rw-r--r-- 1 root root  92 Dec  1 22:00 rbdmap

since the keyring is owned by ceph and the 'ceph' binary is owner by 'root', without 'sudo' ceph will not be able to read the keyring

ceph -s
2016-12-02 01:42:27.657726 7fd63d4e0700 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.b

Do we have to fix any ownership change for the binary or the file? I believe 'normal' user should be able to use ceph cli and capablities decide what  the user can do?

**Comment by leseb** [comment]
We have to keep `rw` for the admin key because whoever calls Ceph using this key can do pretty bad damage to the cluster.
This behaviour is expected and won't probably be fixed. I hope you understand the concern :).
I'm closing this as a won't fix.

**Comment by vasukulkarni** [comment]
sure agree, I think what we did in teuthology runs for clients was we made it easy for workunits to run :), I believe this is the correct behaviour for admin keyring file. Thanks
