### ISSUE TITLE
'pool_default_pg_num' is undefined for 'client' role

### ISSUE THREAD

**Issue by eduardegorov** [ceph/ceph-ansible#1145]
ceph-ansible: 0f3ae4c
ansible: 2.2.0.0

If `client` role is assigned to a host with default group vars, this error pops up:
```
TASK [ceph-client : create pools] **********************************************
task path: /root/tfs/OpenStack2Configs/roles/ceph-client/tasks/create_users_keys.yml:2^[[0m
fatal: [n1]: FAILED! => {"failed": true, "msg": "[{u'name': u'test', u'pgs': u'{{ pool_default_pg_
num }}'}, {u'name': u'test2', u'pgs': u'{{ pool_default_pg_num }}'}]: 'pool_default_pg_num' is undefined"}
fatal: [n2]: FAILED! => {"failed": true, "msg": "[{u'name': u'test', u'pgs': u'{{ pool_default_pg_
num }}'}, {u'name': u'test2', u'pgs': u'{{ pool_default_pg_num }}'}]: 'pool_default_pg_num' is undefined"}
fatal: [n3]: FAILED! => {"failed": true, "msg": "[{u'name': u'test', u'pgs': u'{{ pool_default_pg_
num }}'}, {u'name': u'test2', u'pgs': u'{{ pool_default_pg_num }}'}]: 'pool_default_pg_num' is undefined"}
fatal: [n4]: FAILED! => {"failed": true, "msg": "[{u'name': u'test', u'pgs': u'{{ pool_default_pg_
num }}'}, {u'name': u'test2', u'pgs': u'{{ pool_default_pg_num }}'}]: 'pool_default_pg_num' is undefined"}
```

`pool_default_pg_num` is defined in `mon` role variables only. For my case, this can be workarounded by:
```diff
diff --git a/roles/ceph-client/tasks/main.yml b/roles/ceph-client/tasks/main.yml
index c2b363f..32f5743 100644
--- a/roles/ceph-client/tasks/main.yml
+++ b/roles/ceph-client/tasks/main.yml
@@ -2,3 +2,4 @@
 - include: pre_requisite.yml
 - include: create_users_keys.yml
   when: user_config
+  static: False
```

But, of course, the main issue is not solved and might annoy newcomers if they would try to add test pools as well. Should we move this `pool_default_pg_num` to all.yml or calculate pgs for test/test2 pools using http://ceph.com/pgcalc/ formula in order to avoid HEALTH_WARN messages (since these pools are not for production purposes anyway)?

**Comment by leseb** [comment]
This is actually a bit annoying to manage this value now since we removed a lot from the template.
We need to change this logic and use something like this condition: `  when: ceph_conf_overrides.global.osd_pool_default_pg_num is defined`. I'll work on a patch today.

**Comment by leseb** [comment]
@eduardegorov please have a look at https://github.com/ceph/ceph-ansible/pull/1146 and test :)

**Comment by keepwatch** [comment]
ceph-ansible: 6043b53
ansible: 2.2.0.0

I initially had the same issue as @eduardegorov - after testing pull request #1146, I'm getting two new errors, both apparently because I have a default all.yml:
`# ceph_conf_overrides: {}`

### First Issue
```
TASK [ceph-mon : set_fact] *****************************************************
fatal: [mon0]: FAILED! => {"failed": true, "msg": "The conditional check 'ceph_conf_overrides.global.osd_pool_default_pg_num is not defined' failed. The error was: error while evaluating conditional (ceph_conf_overrides.global.osd_pool_default_pg_num is not defined): 'dict object' has no attribute 'global'\n\nThe error appears to have been in '/etc/vagrant/ceph-ansible/roles/ceph-mon/tasks/ceph_keys.yml': line 34, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- set_fact:\n  ^ here\n"}
```
Line 38 in roles/ceph-mon/tasks/ceph_keys.yml was: 
`- ceph_conf_overrides.global.osd_pool_default_pg_num is not defined`
Changing line 38 to the below let me bypass the problem:
`- ceph_conf_overrides.global is not defined or ceph_conf_overrides.global.osd_pool_default_pg_num is not defined`

### Second Issue
```
TASK [ceph-client : create pools] **********************************************
fatal: [client0]: FAILED! => {"failed": true, "msg": "[{u'name': u'test', u'pgs': u'{{ ceph_conf_overrides.global.osd_pool_default_pg_num }}'}, {u'name': u'test2', u'pgs': u'{{ ceph_conf_overrides.global.osd_pool_default_pg_num }}'}]: 'dict object' has no attribute 'global'"}
```

I can't figure out why roles/ceph-client/tasks/create_users_keys.yml runs when ceph_conf_overrides.global.osd_pool_default_pg_num is not defined (seems contrary to the **when** check in roles/ceph-client/tasks/main.yml). 

However, when defining ceph_conf_overrides.global.osd_pool_default_pg_num in group_vars/all, this PR runs without errors:
```
ceph_conf_overrides:
  global:
    osd_pool_default_pg_num: 8
```

**Comment by leseb** [comment]
@keepwatch yes I was overconfident with #1149, I need to rework this.

**Comment by verdurin** [comment]
I'm still seeing the first issue, even with the commit in #1146, when running `master`.

**Comment by leseb** [comment]
@verdurin use master and declare `ceph_conf_overrides.global.osd_pool_default_pg_num`, everything should work.
