### ISSUE TITLE
ceph fsid regenerate on a existing cluster if fetch dir is empty 

### ISSUE THREAD

**Issue by mistur** [ceph/ceph-ansible#1148]
Hello,

Applying the playbook on a fresh ceph-ansible clone (ie fetch directory is empty) on an existing cluster with the config stores in cluster-<clustername> regenerate a new ceph fsid instead of getting the one of the cluster. 

so the fsid in /etc/ceph/<clustername>.conf is not the one of the cluster

**Comment by font** [comment]
You can manually disable the fsid generation in your `group_vars/all.yml` by setting `generate_fsid: false` and setting the existing `fsid` as shown here https://github.com/ceph/ceph-ansible/blob/80c018b575b92e47ad732f70685dae1f887b4aec/group_vars/all.yml.sample#L199-L206.

**Comment by mistur** [comment]
I try this but got an error when I have applied the playbook with this parameter :

fsid: "<real fsid of my clster"
generate_fsid: false

maybe I souldn't specify the fsid and comment the line instead.

but I think it could be good to protect from creating a new fsid if one already exist.

**Comment by leseb** [comment]
@mistur what was the error?

**Comment by mistur** [comment]
here the error

```
fatal: [iccluster002.iccluster.epfl.ch]: FAILED! => {"failed": true, "msg": "{{ cluster_uuid.stdout }}: 'dict object' has no attribute 'stdout'"}
fatal: [iccluster010.iccluster.epfl.ch]: FAILED! => {"failed": true, "msg": "{{ cluster_uuid.stdout }}: 'dict object' has no attribute 'stdout'"}
fatal: [iccluster018.iccluster.epfl.ch]: FAILED! => {"failed": true, "msg": "{{ cluster_uuid.stdout }}: 'dict object' has no attribute 'stdout'"}
```

here the change :

```--- a/cluster-cephprod/group_vars/all	2016-12-05 14:57:16.481611727 +0100
+++ b/cluster-cephprod/group_vars/all	2016-12-06 15:29:28.329141647 +0100
@@ -196,8 +196,8 @@
 # generated, you may find it useful to disable fsid generation to
 # avoid cluttering up your ansible repo. If you set `generate_fsid` to
 # false, you *must* generate `fsid` in another way.
-fsid: "{{ cluster_uuid.stdout }}"
-generate_fsid: true
+fsid: "f9dfd27f-c704-4d53-9aa0-4a23d655c7c4"
+generate_fsid: false
 
 cephx: true
 max_open_files: 131072
```
