### ISSUE TITLE
Document what is `conf_with_kv` for instance in `mon_containerized_default_ceph_conf_with_kv`

### ISSUE THREAD

**Issue by harobed** [ceph/ceph-ansible#1151]
Document what is `conf_with_kv` for instance in `mon_containerized_default_ceph_conf_with_kv`.

* https://github.com/ceph/ceph-ansible/blob/master/group_vars/all.docker.yml.sample#L14
* https://github.com/ceph/ceph-ansible/blob/master/group_vars/all.docker.yml.sample#L15
* https://github.com/ceph/ceph-ansible/blob/master/group_vars/all.docker.yml.sample#L31
* https://github.com/ceph/ceph-ansible/blob/master/group_vars/all.docker.yml.sample#L50
* https://github.com/ceph/ceph-ansible/blob/master/group_vars/all.docker.yml.sample#L62
* https://github.com/ceph/ceph-ansible/blob/master/group_vars/all.docker.yml.sample#L87
* https://github.com/ceph/ceph-ansible/blob/master/group_vars/all.docker.yml.sample#L99

Best regards,
Stéphane

**Comment by leseb** [comment]
Containerized deployment with kv means using a key/value store to store ceoh.conf options, monmap, key files on etcd or consul. The benefit is that we don't need to copy files over nodes (e.g: monmap) but we can fetch them from that persistent store.

**Comment by harobed** [comment]
@leseb what do you think about document it?

**Comment by leseb** [comment]
@harobed I know at some point we need to re-organize the doc...

**Comment by harobed** [comment]
I can create pull request then and help you to improve the documentation.

**Comment by leseb** [comment]
Would be nice, thanks @harobed
