### ISSUE TITLE
Suggestion: add more documentation about `ceph-osd` mandatory variables

### ISSUE THREAD

**Issue by harobed** [ceph/ceph-ansible#1156]
Suggestion: add more documentation about `ceph-osd` [mandatory variables](https://github.com/ceph/ceph-ansible/tree/master/roles/ceph-osd#mandatory-variables)

Documentation about:

* `journal_collocation`
* `raw_multi_journal`
* `osd_directory`

Best regards,
Stéphane

**Comment by harobed** [comment]
It's documented here:

* journal_collocation: https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-osd/defaults/main.yml#L95
* raw_multi_journal: https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-osd/defaults/main.yml#L112
* osd_directory: https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-osd/defaults/main.yml#L132

Suggestion: add this link in [README.md](https://github.com/ceph/ceph-ansible/tree/master/roles/ceph-osd#mandatory-variables)

**Comment by leseb** [comment]
@harobed thanks for reporting this, would you mind gathering all of your doc requests in a new issue so I can address all of them at once?
Thanks!

**Comment by harobed** [comment]
Or can I add a "doc" issue tag?

**Comment by leseb** [comment]
Yes you can.

**Comment by harobed** [comment]
> Yes you can.

I'm not allowed to do that, can you grant me?

**Comment by leseb** [comment]
I'll do it once you get your PR. :)
