### ISSUE TITLE
readline isn't configured or installed in ceph cli

### ISSUE THREAD

**Issue by harobed** [ceph/ceph-ansible#1159]
`readline` isn't configured or installed in `ceph` cli, example:

```
ceph> help ^H^H^H^[[A^[[A^[[B^H
```

I can't use `delete`, `up key`…

**Comment by leseb** [comment]
I think this is more a Ceph packaging issue than a ceph-ansible problem.

**Comment by harobed** [comment]
Ok but I didn't see « issues » tab here https://github.com/ceph/ceph :(

**Comment by leseb** [comment]
Oh right, you have to use the ceph tracker. http://tracker.ceph.com/issues

**Comment by harobed** [comment]
This is this issue in upstream: http://tracker.ceph.com/issues/18168
