### ISSUE TITLE
Ganesha Installation as part of CephFS

### ISSUE THREAD

**Issue by acomisario** [ceph/ceph-ansible#1188]
We were looking that the ansible-ceph app, deploys Ganesha when CephFS is deployed.

We wanted to ask you about the "production state" of that solution to work with the Manila API since we thought that if the "ansible-ceph" does it (deploying ganesha), there must be a reason to it.

Can you give us an insight about that ?
thanks for your time.

**Comment by leseb** [comment]
We currently don't support CephFS and Ganesha in ceph-ansible. There is actually not much to do, you just need to get an Ansible ganesha role, deploy a gateway and connect it to Ceph.
