### ISSUE TITLE
Civetweb IP:Port Issue

### ISSUE THREAD

**Issue by clwells** [ceph/ceph-ansible#1197]
I can't find docs on this so I may be wrong.  Am having an issue when setting both the bind_ip and port for civetweb on the RGW machines.

Here's my error:

```
Dec 16 03:41:06 radosgw: error parsing int: 10.136.33.109:7480: The option value '10.136.33.109:7480' seems to be invalid
```

Here's my Ceph config entry:

```
rgw frontends = civetweb port=10.136.30.231:7480 num_threads=50
```

Looks like port= is looking for just the port and not the IP:port combo.

**Comment by clwells** [comment]
Followup here - The ceph.conf j2 script also seems to output the same IP for each RGW in the bunch for civetweb.  The issue looks like it's here:

https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-common/templates/ceph.conf.j2#L114

Regardless of the hostvars the IP for civetweb is always output as the ```radosgw_civetweb_bind_ip``` var.

Am happy to PR changes if you guys verify these are issues.

**Comment by leseb** [comment]
It's a known issue, but normally if you look at your radosgw, the process is started and listening on the right IP/interface. This radosgw log is a bit misleading but it doesn't describe a failure, this is fix in a newer version of Ceph. Can you confirm that?

**Comment by clwells** [comment]
Yep - you're right, sorry for false-alarming.
