### ISSUE TITLE
How to disable cephx only in ceph.conf?

### ISSUE THREAD

**Issue by zealoussnow** [ceph/ceph-ansible#1201]
I want to disable cephx in my cluster, but I found "cephx: true" in role ceph-common, ceph-mon and ceph-osd. If I want to disable cephx, which file should I modify? Or If I only modify in cepy-commmon, what will happens？

**Comment by zhsj** [comment]
You should set the variable in `group_vars/all.yml`. Don't modify files in `roles`.

**Comment by leseb** [comment]
+1 for @zhsj commentn just set `cephx: false` in `group_vars/all.yml`.

**Comment by zealoussnow** [comment]
OK, I will try it again.  Thank you.
