### ISSUE TITLE
Suggest: add config parameter to configure "ceph osd crush tunables {PROFILE}"

### ISSUE THREAD

**Issue by harobed** [ceph/ceph-ansible#1205]
Suggest: add config parameter to configure "ceph osd crush tunables {PROFILE}"

**Comment by harobed** [comment]
Documentation is here: http://docs.ceph.com/docs/master/rados/operations/crush-map/#tuning-crush

**Comment by leseb** [comment]
This is an operation procedure, I don't see why it should be included in the playbook.
