### ISSUE TITLE
adding a new node with different disks amounts and device names

### ISSUE THREAD

**Issue by acomisario** [ceph/ceph-ansible#1206]
Hi, suppose i have a 5 nodes cluster deployed and declared group_vars/osd like this:

devices:
  - /dev/sdc
  - /dev/sdd
  - /dev/sde
  - /dev/sdf
  - /dev/sdg
  - /dev/sdh
raw_multi_journal: true
raw_journal_devices:
  - /dev/sdb
  - /dev/sdb
  - /dev/sdb
  - /dev/sdb
  - /dev/sdb
  - /dev/sdb

and the hosts file like this:

[mons]
rack01-nde103
rack01-nde104
rack01-nde105

[osds]
rack01-nde101
rack01-nde102
rack01-nde103
rack01-nde104
rack01-nde105

but now i want to add to the cluster two more servers  (nde106 & nde107) that has lots of more disks, what would be the correct order to do it after modifyng the devices section ?

i was thinking about adding those two new nodes to the osd section and after that run the deploy like this:

```
ansible-playbook site.yml -l nde106,nde107
```
would that **add** the new servers into the already running cluster ?
if not, how should i proceed ?

**Comment by leseb** [comment]
If nde106 and 107 have more disks than the other servers you can do this in your `hosts` file:

```
rack01-nde106 devices=['/dev/sdb', '/dev/sdc' ...] raw_journal_devices=['/dev/sdd', '/dev/sdd']
rack01-nde107 devices=['/dev/sdb', '/dev/sdc' ...] raw_journal_devices=['/dev/sdd', '/dev/sdd']
```

**Comment by acomisario** [comment]
and what happens if i want this new nodes to use journal collocation ? can i not name the raw jornals but expect nothing to happen on the already deployed nodes ? (with raw journal devices)

**Comment by leseb** [comment]
I've never tried that but on the new node you can set `journal_collocation: true` and `raw_multi_journal: false`.

**Comment by acomisario** [comment]
thanks so much ! it works

**Comment by nitinkamble** [comment]
This is purely an ansible question. and ansible documentation has answer: http://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html
