### ISSUE TITLE
remove infernalis support

### ISSUE THREAD

**Issue by ktdreyer** [ceph/ceph-ansible#1216]
Infernalis has been EOL upstream for a long time. We should remove support for it to simplify the conditionals.

**Comment by leseb** [comment]
yay!
I'm traveling next week so I'll give a try if nothing happens when I come back.

**Comment by ktdreyer** [comment]
Thanks! (and Firefly can go as well)

**Comment by leseb** [comment]
@ktdreyer What about Hammer though?

**Comment by ktdreyer** [comment]
We don't test Hammer, so I think it should go

**Comment by leseb** [comment]
We don't test it but there are likely users using it... However we need to keep moving, people are encouraged to move to Jewel anyway. I'll simply the code and our next release will drop the support of anything before Jewel.

**Comment by guits** [comment]
still WIP, need to double check few things.

**Comment by fiatala** [comment]
Sorry if this is the incorrect place to ask, but are the Red Hat Infernalis checks backwards? For example, Infernalis and Jewel are intentionally skipped during "install ceph." This is my first time using ceph-ansible, so I may be missing something. 

https://github.com/guits/ceph-ansible/blob/master/roles/ceph-common/tasks/installs/install_on_redhat.yml#L57
