### ISSUE TITLE
OSD 0 cannot write to its log file

### ISSUE THREAD

**Issue by smatzek** [ceph/ceph-ansible#1223]
Ceph-ansible deployments leave a /var/log/ceph-osd-0.log file on every OSD node with permissions of root/root.  This means that the real ceph OSD with ID 0 cannot write to its own log file because the daemon is running as 'ceph' and the file is owned by 'root':

~$ sudo ls -l /var/log/ceph
total 15320
-rw------- 1 ceph ceph    6240 Jan 10 08:00 ceph.audit.log
-rw------- 1 ceph ceph 6689776 Jan 11 14:50 ceph.log
-rw-r--r-- 1 ceph ceph 8753329 Jan 11 14:50 ceph-mon.mhost5.log
-rw-r--r-- 1 root root     810 Jan 10 08:00 ceph-osd.0.log
-rw-r--r-- 1 ceph ceph  210278 Jan 11 14:40 ceph-osd.1.log

I've tracked the file creation down to the call to "ceph-disk prepare".  The 'ceph-disk' tool in turn calls these commands:
/usr/bin/ceph-osd --check-allows-journal -i 0 --cluster ceph
/usr/bin/ceph-osd --check-wants-journal -i 0 --cluster ceph
/usr/bin/ceph-osd --check-needs-journal -i 0 --cluster ceph

Ceph-disk has the '0' hard coded.   This causes the log file to be created with owner root and since we are calling ceph-disk prepare on every OSD node this causes the file to be created on every OSD node.

Note, when I reproduce this with a simple playbook to call just this command with become: true the file is owned by root but has group 'ceph'.  It doesn't fully explain how the files from ceph-ansible deploy end up with root/root.

So yes, this issue is outside of ceph-ansible but I am opening the bug to have the discussion about whether these commands should be run as user 'ceph' by ceph-ansible or if we should put a 'workaround' in ceph-ansible to remove the *-osd.0.log files or change owner/group to ceph/ceph.

**Comment by smatzek** [comment]
Update:  The ceph-disk prepare code does make the ceph-osd-0.log file and the perms are root/root.  In my original tests I was testing this in a cluster where no monitors were up. When the monitor is up and ceph-disk prepare can run to successful completion the file is left with root / root.


I did some more investigation into this to see if we could/should have ceph-ansible run ceph-disk prepare as the 'ceph' user.  This won't work ceph-disk fails with an error like this:
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 581, in get_dev_size
    fd = os.open(dev, os.O_RDONLY)
OSError: [Errno 13] Permission denied: '/dev/vdc'

Because user 'ceph' does not have read permission on the device.  So we must run it as root.

At this point the only workaround we could do in ceph-ansible is to do a chown/chgrp on the file after disk prepare and before OSD activate or remove the file between disk prepare and disk activate.

**Comment by leseb** [comment]
@smatzek or we could chown the device to the ceph user and run ceph-disk with the ceph user?

**Comment by smatzek** [comment]
That may work.  I did more investigation after the last update and neglected to update before the weekend.  I've found that it's likely a simple fix in ceph-disk and opened a bug for that:
http://tracker.ceph.com/issues/18538

Once I get the fix for that merged the ceph-ansible question will be what, if anything, we want to do for a workaround in levels that don't have the fix.

**Comment by leseb** [comment]
Right, ceph-disk should apply the right permission on the device and fix its hardcoded parts. In the meantime, I think it's acceptable to apply the right permission of the block device. Do you mind testing this out?

Thanks!

**Comment by smatzek** [comment]
The fix for http://tracker.ceph.com/issues/18538 is merged in ceph master (luminous) and is targeted for backport to jewel and kraken.

The fix for this bug isn't pretty.  You have to change the permissions on the osd.0.log and then kill -1 signal the daemon to close its FD and reopen.

Given the above, we won't workaround this in ceph-ansible and it will auto-correct once the fixes make it into minor versions of the affected releases.
