### ISSUE TITLE
docker mon setup uses short hostname for monitors

### ISSUE THREAD

**Issue by ibotty** [ceph/ceph-ansible#1241]
It uses `ansible_hostname` which makes a host like a.a.example.com become host a monitor `mon-a`. A host a.b.example.com will now also host `mon-a`. I _think_ using `ansible_fqdn` is correct, while a little verbose. Of course that won't be backwards-compatible.

Ideas?

**Comment by leseb** [comment]
We can change the template by exposing `MON_NAME` to it and default it to $(hostname), then you can change this variable later. Let me quickly do that.

**Comment by leseb** [comment]
@ibotty https://github.com/ceph/ceph-ansible/pull/1244

**Comment by leseb** [comment]
@ibotty please do your changes here: https://github.com/ceph/ceph-ansible/blob/625ee0952e34036f85dc959a8710d973e59c8df4/roles/ceph-mon/defaults/main.yml#L79

**Comment by ibotty** [comment]
Thank you!

**Comment by ibotty** [comment]
Well, finally got to it again. Just setting MON_NAME is unfortunately by far not enough.

There are the following issues (which I hacked around) because `{{ansible_hostname}}` is hardcoded in quiet a few places. I can prepare a pull request that abstracts the MON_NAME (and MDS_NAME, etc.)

 * There are the `mon_use_fqdn` and `mds_use_fqdn` variables to be set,
 * `roles/ceph-mon/tasks/docker/main.yml` uses the wrong monitor socket,
 * the mon docker containers are named `{{ansible_hostname}}`. I would certainly prefer it to be `ceph-mon-$MON_NAME`, more seriously: so are the ceph-mds- and the ceph-rbd-mirror containers! When testing (or colocating for "hyperconverged storage" ;-)) multiple ceph services on one node that leads to madness!

What's your take on it? I patched most things locally for now, but would like to make it better! Should I file separate issues for the docker container naming inconsistency?

**Comment by leseb** [comment]
Alright, yes I wouldn't say no to a PR that fixes the MON_NAME all over the places.
As for naming the container `ceph-mon-$MON_NAME`, I'm fine with this as well. It's just the name of the container :). I think it's fine keeping this issue for reference. Just make sure you have separate commits for everything and we should be good.

Thanks @ibotty
