### ISSUE TITLE
ceph-disk activate for partition failing... but not

### ISSUE THREAD

**Issue by ashak** [ceph/ceph-ansible#1242]
Hi,

I've recently been trying out ceph-ansible. But I don't end up with any osd's on my hosts.

My untrained eye believes the problem is happening within:
TASK [ceph-osd : activate osd(s) when device is a partition]
Each of my hosts report the same, which looks to me like ceph-disk activate /dev/sda3 is actually failing, but the task seems to pass?

`ok: [10.0.1.1] => (item=[{'_ansible_parsed': True, u'cmd': u"readlink -f /dev/sda3 | egrep '/dev/([hsv]d[a-z]{1,2}|cciss/c[0-9]d[0-9]p|nvme[0-9]n[0-9]p)[0-9]{1,2}$'", u'end': u'2017-01-20 10:48:07.970056', '_ansible_no_log': False, u'stdout': u'/dev/sda3', '_ansible_item_result': True, u'rc': 0, 'item': u'/dev/sda3', u'delta': u'0:00:00.005338', u'stderr': u'', u'changed': False, 'invocation': {'module_name': u'command', u'module_args': {u'warn': True, u'executable': None, u'_uses_shell': True, u'_raw_params': u"readlink -f /dev/sda3 | egrep '/dev/([hsv]d[a-z]{1,2}|cciss/c[0-9]d[0-9]p|nvme[0-9]n[0-9]p)[0-9]{1,2}$'", u'removes': None, u'creates': None, u'chdir': None}}, 'stdout_lines': [u'/dev/sda3'], 'failed_when_result': False, u'start': u'2017-01-20 10:48:07.964718', u'warnings': [], 'failed': False}, u'/dev/sda3']) => {"changed": false, "cmd": ["ceph-disk", "activate", "/dev/sda3"], "delta": "0:00:00.127561", "end": "2017-01-20 10:48:09.293854", "failed": false, "failed_when_result": false, "item": [{"_ansible_item_result": true, "_ansible_no_log": false, "_ansible_parsed": true, "changed": false, "cmd": "readlink -f /dev/sda3 | egrep '/dev/([hsv]d[a-z]{1,2}|cciss/c[0-9]d[0-9]p|nvme[0-9]n[0-9]p)[0-9]{1,2}$'", "delta": "0:00:00.005338", "end": "2017-01-20 10:48:07.970056", "failed": false, "failed_when_result": false, "invocation": {"module_args": {"_raw_params": "readlink -f /dev/sda3 | egrep '/dev/([hsv]d[a-z]{1,2}|cciss/c[0-9]d[0-9]p|nvme[0-9]n[0-9]p)[0-9]{1,2}$'", "_uses_shell": true, "chdir": null, "creates": null, "executable": null, "removes": null, "warn": true}, "module_name": "command"}, "item": "/dev/sda3", "rc": 0, "start": "2017-01-20 10:48:07.964718", "stderr": "", "stdout": "/dev/sda3", "stdout_lines": ["/dev/sda3"], "warnings": []}, "/dev/sda3"], "rc": 1, "start": "2017-01-20 10:48:09.166293", "stderr": "Traceback (most recent call last):\n  File \"/usr/sbin/ceph-disk\", line 9, in <module>\n    load_entry_point('ceph-disk==1.0.0', 'console_scripts', 'ceph-disk')()\n  File \"/usr/lib/python2.7/dist-packages/ceph_disk/main.py\", line 5009, in run\n    main(sys.argv[1:])\n  File \"/usr/lib/python2.7/dist-packages/ceph_disk/main.py\", line 4962, in main\n    main_catch(args.func, args)\n  File \"/usr/lib/python2.7/dist-packages/ceph_disk/main.py\", line 4993, in main_catch\n    msg=e,\n  File \"/usr/lib/python2.7/dist-packages/ceph_disk/main.py\", line 270, in __str__\n    return ': '.join([doc] + [_bytes2str(a) for a in self.args])\nTypeError: sequence item 2: expected string or Unicode, CalledProcessError found", "stdout": "", "stdout_lines": [], "warnings": []}`

If I run the command manually on the host I get the same response:

```
root@host1:~# ceph-disk activate /dev/sda3
Traceback (most recent call last):
  File "/usr/sbin/ceph-disk", line 9, in <module>
    load_entry_point('ceph-disk==1.0.0', 'console_scripts', 'ceph-disk')()
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 5009, in run
    main(sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 4962, in main
    main_catch(args.func, args)
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 4993, in main_catch
    msg=e,
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 270, in __str__
    return ': '.join([doc] + [_bytes2str(a) for a in self.args])
TypeError: sequence item 2: expected string or Unicode, CalledProcessError found
```

My group_vars/all.yml file (with all comments and empty lines removed) contains:
```
---
dummy:
ceph_origin: 'upstream' # or 'distro' or 'local'
ceph_stable: true # use ceph stable branch
ceph_stable_key: https://download.ceph.com/keys/release.asc
ceph_stable_release: jewel # ceph stable release
ceph_stable_repo: "http://download.ceph.com/debian-{{ ceph_stable_release }}"
monitor_interface: eth0
journal_size: 5120 # OSD journal size in MB
public_network: 10.0.1.0/24

```

vars/osds.yml (with all comments and empty lines removed) contains:
```
---
dummy:
devices:
  - /dev/sda3
journal_collocation: true
```

my hosts file contains:
```
[mons]
10.0.1.1
10.0.1.2
10.0.1.3

[osds]
10.0.1.1
10.0.1.2
10.0.1.3

[mdss]

[rgws]
```

I'm running ansible 2.2.0.0 installed from the debian apt repo (2.2.0.0-4).

I don't think i'm doing anything too dumb or out of the ordinary?

**Comment by leseb** [comment]
Hum looks like a ceph-disk bug at this point. How big is the partition?

**Comment by ashak** [comment]
967GB according to parted.

**Comment by leseb** [comment]
Is it the entire space of the device or are you using a portion of that disk for the OSD? If not, I'll suggest using the entire block device for now.
Let me see if I can reproduce this.

**Comment by ashak** [comment]
They are 1TB drives, GPT, there's two other partitions. From memory one is 512MB EFI, the other is 32GB root partition. I can confirm if it's important.

**Comment by leseb** [comment]
No worries partitions should be supported, so we need to investigate. Can you also register an issue on tracker.ceph.com? Thanks!

**Comment by ashak** [comment]
Issue registered as requested, sorry it took so long:

http://tracker.ceph.com/issues/18694

**Comment by leseb** [comment]
@ashak would you mind trying Leonid suggestion and get the latest version of ceph-disk? (just the main.py just be enough) then test again? Thanks!

**Comment by ashak** [comment]
I've been trying today. But the playbook is now failing at an earlier step. It's currently failing to start the monitors on my hosts. I'll have to debug that first. I'll report back once I manage to get back to this stage and try out the updated file.

**Comment by leseb** [comment]
@ashak alright thanks

**Comment by ashak** [comment]
I took that file and overwrote the same file on my system installed by the debian package using:
wget https://github.com/ceph/ceph/raw/master/src/ceph-disk/ceph_disk/main.py -O /usr/lib/python2.7/dist-packages/ceph_disk/main.py

I then ran the play again (I didn't purge because that would have removed the package and the hacked in place file), but it now fails in a different place

TASK [ceph-mon : get default value for osd_pool_default_pg_num] ***
ok: [10.0.1.1] => {"changed": false, "cmd": "ceph --cluster ceph daemon mon.vm1 config get osd_pool_default_pg_num | grep -Po '(?<=\"osd_pool_default_pg_num\": \")[^\"]*'", "delta": "0:00:00.045653", "end": "2017-02-06 15:11:06.244949", "failed": false, "failed_when_result": false, "rc": 0, "start": "2017-02-06 15:11:06.199296", "stderr": "", "stdout": "8", "stdout_lines": ["8"], "warnings": []}

TASK [ceph-mon : set_fact] ***
skipping: [10.0.1.1] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
skipping: [10.0.1.2] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
skipping: [10.0.1.3] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}

TASK [ceph-mon : set_fact] ***
fatal: [10.0.1.2]: FAILED! => {"failed": true, "msg": "The conditional check 'ceph_conf_overrides.global.osd_pool_default_pg_num is not defined' failed. The error was: error while evaluating conditional (ceph_conf_overrides.global.osd_pool_default_pg_num is not defined): 'dict object' has no attribute 'global'\n\nThe error appears to have been in '/home/garyr/code/ceph-ansible/roles/ceph-mon/tasks/ceph_keys.yml': line 71, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- set_fact:\n  ^ here\n"}
... same error repeated for the other two hosts ...

**Comment by leseb** [comment]
@ashak are you running master?

**Comment by ashak** [comment]
@leseb Yes, updated this morning before I started messing for the day.

**Comment by ashak** [comment]
This current issue, where should global be defined in ceph_conf_overrides?

To try to proceed, I made this change:
diff --git a/roles/ceph-mon/tasks/ceph_keys.yml b/roles/ceph-mon/tasks/ceph_keys.yml
index f58c8b7..545f2ed 100644
--- a/roles/ceph-mon/tasks/ceph_keys.yml
+++ b/roles/ceph-mon/tasks/ceph_keys.yml
@@ -73,11 +73,11 @@
   when:
     - pool_default_pg_num is not defined
     - default_pool_default_pg_num.rc == 0
-    - ceph_conf_overrides.global.osd_pool_default_pg_num is not defined
+    - not global_in_ceph_conf_overrides or ceph_conf_overrides.global.osd_pool_default_pg_num is not defined

But then it failed on the next task, so I did the same sort of thing:
 - set_fact:
     osd_pool_default_pg_num: "{{ ceph_conf_overrides.global.osd_pool_default_pg_num }}"
-  when: ceph_conf_overrides.global.osd_pool_default_pg_num is defined
+  when: global_in_ceph_conf_overrides and ceph_conf_overrides.global.osd_pool_default_pg_num is defined

It got further but failed at 
TASK [ceph-mon : destroy and recreate rbd pool if osd_pool_default_pg_num is not honoured]
With the same sort of error.

This is why I wonder where global should be defined in ceph_conf_overrides, because as far as I can tell the few places in the sample group vars etc. that it's defined don't seem to be anything that I should be defining right now.
