### ISSUE TITLE
Multiple RGW Ceph.conf Issue

### ISSUE THREAD

**Issue by clwells** [ceph/ceph-ansible#1258]
Am running multiple RGWs on a single cluster and noticed that the civetweb line for each RGW on each node is identical.  It boils down to this definition:

https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-common/defaults/main.yml#L288

Which gets embedded in:

https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-common/defaults/main.yml#L293

And then it's passed along to:

https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-common/templates/ceph.conf.j2#L117

Since the original reference above is based on the current RGW's IP that IP gets used for all RGWs within the ceph.conf.  This doesn't cause any issue since the non-local INI blocks are just ignored. That said it's still sad.  Would a PR for this be welcome or is it seen as not a huge deal?

**Comment by leseb** [comment]
Oh right, each ceph.conf should get the right IP for each gw, so yes PR is welcome.
I just don't understand this isn't an issue, I mean if they all share the same IP in their config they shouldn't be able to listen to that IP. But I have the feeling, I'm missing something...

**Comment by clwells** [comment]
It's not an issue now because each RGW server looks only at its stanza in the ceph.conf.  So while the other stanzas may be wrong each individual RGW is looking at a correct version (for itself) of the stanza.

And roger - will PR something when I can.

**Comment by leseb** [comment]
@clwells thanks!

**Comment by mcv21** [comment]
One approach would be to leave the IP address out entirely (it's not needed there you can just say `rgw frontends = "civetweb port=443s"` )
