### ISSUE TITLE
Typo on wiki 

### ISSUE THREAD

**Issue by tshefi** [ceph/ceph-ansible#1263]
On https://github.com/ceph/ceph-ansible/wiki
Typo or forgot to update, source files are not x.sample but rather x.yml.sample
Three lines below should be updated:
$ cp group_vars/all.sample group_vars/all   
$ cp group_vars/mons.sample group_vars/mons  
$ cp group_vars/osds.sample group_vars/osds

**Comment by leseb** [comment]
Fixed thanks!
