### ISSUE TITLE
Handler change breaks /etc/ansible/roles installs

### ISSUE THREAD

**Issue by Logan2211** [ceph/ceph-ansible#1265]
Recently began seeing this failure: http://logs.openstack.org/95/427695/1/check/gate-openstack-ansible-openstack-ansible-ceph-ubuntu-xenial-nv/3ef9dee/console.html#_2017-02-01_14_00_10_173468

It looks like the change 40a2df5bbf13685c83ddc0b784b97e8a76414006 breaks role installations in /etc/ansible/roles by assuming that the role resides in ``{{ playbook_dir }}``

**Comment by andrewschoen** [comment]
@Logan2211 I had suspected that would cause issues. Let's see how the CI likes #1266

**Comment by andrewschoen** [comment]
fixed with #1266
