### ISSUE TITLE
Deprecated warnings with ansible 2.2 

### ISSUE THREAD

**Issue by vasukulkarni** [ceph/ceph-ansible#1270]
I see following deprecated warnings with 2.2 run

there are 2 or 3 var's complaining about deprecated warnings

https://paste.fedoraproject.org/542574/78177148/raw/

**Comment by leseb** [comment]
Thanks @vasukulkarni I'll look into that. We keep `always_run` for now so 2.1 users can still use the module. The unicode stuff is part of the override module.

**Comment by Kallio** [comment]
full ceph-ansible "stack" contains quite many always_run checks. 
```
grep -ri  always_run ceph-ansible |wc -l
     106

```
Since 2.4 is already latest stable  core version (docs.ansbile.com won't even show documentation for pre 2.3 versions) I think that seek'n' replace would be the "thing"  soon.

**Comment by guits** [comment]
@Kallio There is a PR opened regarding this (#1966)

**Comment by guits** [comment]
Actually just outdated by #2037
