### ISSUE TITLE
Attempt to install ceph-fs-common on kraken removes all other Ceph packages

### ISSUE THREAD

**Issue by fiskn** [ceph/ceph-ansible#1273]
I've just noticed that after the initial deployment with ansible, if i run the site.yml again it uninstalls all the Ceph packages because it tries to install ceph-fs-common package. This package no longer exists in the Ubuntu Kraken release as it has been merged into ceph-common and so as its a different version it removes the other packages. I believe this package needs to be removed from the list of packages to install, or maybe only excluded if version =Kraken+

```
Apt history.log after running site.yml for 2nd time:
Start-Date: 2017-02-01  21:58:09
Commandline: /usr/bin/apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold install ceph-fs-common -t xenial
Requested-By: vagrant (1000)
Install: ceph-fs-common:amd64 (10.2.5-1xenial)
Remove: ceph-common:amd64 (11.2.0-1xenial), ceph-mds:amd64 (11.2.0-1xenial), ceph-mgr:amd64 (11.2.0-1xenial), ceph-mon:amd64 (11.2.0-1xenial), ceph-osd:amd64 (11.2.0-1xenial), ceph-base:amd64 (11.2.0-1xenial), ceph:amd64 (11.2.0-1xenial)
End-Date: 2017-02-01  21:58:12
```

**Comment by leseb** [comment]
@fiskn feel free to remove it from the list of `debian_ceph_packages`, here https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-common/defaults/main.yml#L74

**Comment by fiskn** [comment]
@leseb I did that to fix my problem, but I was wondering what the correct approach would be to stop this happening to anyone else using kraken in the future, without altering the current behaviour for jewel and below?

**Comment by leseb** [comment]
@fiskn at the moment we haven't switched to kraken yet, I'd hate duplicating code simply to add the support of a specific version. So perhaps the only thing we would do is document this.
