### ISSUE TITLE
Trusty support broken

### ISSUE THREAD

**Issue by Logan2211** [ceph/ceph-ansible#1275]
It seems that 76ddcbc2719d316b7746f2d4567521b9fbfcc568 not only removed support for pre-Jewel ceph releases, but also removes all support for upstart based OS's, so trusty builds now fail with problems like:

```
23:39:08 TASK [ceph-mon : start the monitor service] ************************************
23:39:08 fatal: [aio1_ceph-mon_container-59b7eeaa]: FAILED! => {"changed": false, "failed": true, "msg": "no service or tool found for: ceph-mon@aio1-ceph-mon-container-59b7eeaa"}
```

**Comment by leseb** [comment]
Correct we also removed the support for non-systemd distros.
Although this should have failed earlier with https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-common/tasks/checks/check_system.yml#L38

Oh wait is it a containerized deployment?

**Comment by Logan2211** [comment]
Bare metal in this case.

I don't see that task in my previous test but maybe the git repo common was pulled from was more stale than -mon. Probably nothing to be concerned about but I did just restart the build to see if it fails there with the updated -common.

Thanks for the info.. I figured it was worth raising the issue since the commit message made no mention of this so it was unclear whether it is a regression or intentional removal.

**Comment by leseb** [comment]
Thanks for the followup @Logan2211 and sorry for breaking your CI so often lately...
