### ISSUE TITLE
ceph mon's no longer start up on first ansible run

### ISSUE THREAD

**Issue by ashak** [ceph/ceph-ansible#1277]
I've been failing around trying to solve my previous issue and my servers get to the stage where the playbooks try to 'start the monitor service' and this fails reliably every time on my servers.

I tried starting them manually (using systemctl start ceph-mon@host1.service), but to no avail.

However if I manually try the command that systemctl status ceph-mon@host1.service suggests to me it tried to run, my monitor starts.

To shorten the pain i've felt over the last few hours trying to debug this, it turns out that the systemd config for the ceph monitors doesn't actually allow me to start the monitors up for 30 mins after a failure.

Once I realised that and editted /lib/systemd/system/ceph-mon@.service, reducing the StartLimitInterval setting to something much less than 30 mins, I can start the monitors using systemctl start without issue.

Now I am confused.... how on earth do I work out why the playbook cannot start my monitors on its first run? If I literally run them and let it fail, then edit the systemd file mentioned above reducing StartLimitInterval to 1, run systemctl daemon-reload, then start the monitors by hand myself, they start without issue.

Is this an issue with the ansible code or ceph itself?

I didn't have this problem 2-3 weeks ago, the monitors would start without issue on the first run of the playbook.

My system is a fully up to date Debian Jessie machine.

**Comment by leseb** [comment]
Do you have systemd logs? Ceph-mon logs? Just so we can understand the reason why the monitor didn't start.

**Comment by ashak** [comment]
That's what i've spent the best part of the last few hours trying to come up with. But I don't seem to get any actual useful logging in any of the log files.

The ceph mon logs just say this:
2017-02-03 15:55:13.532279 7fca0c21b600  0 set uid:gid to 64045:64045 (ceph:ceph)
2017-02-03 15:55:13.532287 7fca0c21b600  0 ceph version 10.2.5 (c461ee19ecbc0c5c330aca20f7392c9a00730367), process ceph-mon, pid 34833
2017-02-03 15:55:13.911303 7f7af63bf600  0 set uid:gid to 64045:64045 (ceph:ceph)
2017-02-03 15:55:13.911316 7f7af63bf600  0 ceph version 10.2.5 (c461ee19ecbc0c5c330aca20f7392c9a00730367), process ceph-mon, pid 34899
2017-02-03 15:55:14.108655 7f9e128e0600  0 set uid:gid to 64045:64045 (ceph:ceph)
2017-02-03 15:55:14.108669 7f9e128e0600  0 ceph version 10.2.5 (c461ee19ecbc0c5c330aca20f7392c9a00730367), process ceph-mon, pid 34965
2017-02-03 15:55:14.450215 7f46b8fe1600  0 set uid:gid to 64045:64045 (ceph:ceph)
2017-02-03 15:55:14.450221 7f46b8fe1600  0 ceph version 10.2.5 (c461ee19ecbc0c5c330aca20f7392c9a00730367), process ceph-mon, pid 34994
2017-02-03 15:55:14.699871 7f3ae7aab600  0 set uid:gid to 64045:64045 (ceph:ceph)
2017-02-03 15:55:14.699879 7f3ae7aab600  0 ceph version 10.2.5 (c461ee19ecbc0c5c330aca20f7392c9a00730367), process ceph-mon, pid 35011
2017-02-03 15:55:14.948805 7f37b209c600  0 set uid:gid to 64045:64045 (ceph:ceph)
2017-02-03 15:55:14.948812 7f37b209c600  0 ceph version 10.2.5 (c461ee19ecbc0c5c330aca20f7392c9a00730367), process ceph-mon, pid 35023
2017-02-03 15:55:30.511419 7f2b12efe600  0 set uid:gid to 64045:64045 (ceph:ceph)
2017-02-03 15:55:30.885159 7f2b12efe600  1 leveldb: Delete type=3 #1

I tried to work out how to make them give me something more useful, but mostly failed and then I realised that the systemd stuff I mentioned above.

Syslog says:
Feb  3 15:55:30 vm1 ansible-command: Invoked with creates=/var/lib/ceph/mon/ceph-vm1/keyring executable=None _uses_shell=False _raw_params=ceph-mon --cluster ceph --setuser ceph --setgroup ceph --mkfs -i vm1 --fsid 74dd3dec-4242-4810-8742-f4f6eec7a972 --keyring /var/lib/ceph/tmp/keyring.mon.vm1 removes=None warn=True chdir=None
Feb  3 15:55:31 vm1 ansible-systemd: Invoked with no_block=False name= enabled=True daemon_reload=False state=started user=False masked=None
Feb  3 15:55:31 vm1 systemd[1]: Starting Ceph cluster monitor daemon...
Feb  3 15:55:31 vm1 systemd[1]: ceph-mon@vm1.service start request repeated too quickly, refusing to start.
Feb  3 15:55:31 vm1 systemd[1]: Failed to start Ceph cluster monitor daemon.

jounalctl -x tells me:
Feb 03 15:55:31 vm1 ansible-systemd[35730]: Invoked with no_block=False name= enabled=True daemon_reload=False state=started user=False masked=None
Feb 03 15:55:31 vm1 systemd[1]: Starting Ceph cluster monitor daemon...
-- Subject: Unit ceph-mon@vm1.service has begun with start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit ceph-mon@vm1.service has begun starting up.
Feb 03 15:55:31 vm1 systemd[1]: ceph-mon@vm1.service start request repeated too quickly, refusing to start.
Feb 03 15:55:31 vm1 systemd[1]: Failed to start Ceph cluster monitor daemon.
-- Subject: Unit ceph-mon@vm1.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit ceph-mon@vm1.service has failed.
-- 
-- The result is failed.

I have no clue how to get better systemd logging, suggestions?

**Comment by leseb** [comment]
As far as I see, the mon logs say that the mon is up or was? So every time you bootstrap an initial mon, it fails, then later you can start it without apparent good reason and it works, right?

**Comment by ashak** [comment]
I'm not sure I agree with the first part of what you're saying, but I'm not very experienced with ceph.

The mon logs to me look like it tried to start 6 times in succession. After which I ended up with no mon process running. 
systemctl (i've not touched the system since) says:
● ceph-mon@vm1.service - Ceph cluster monitor daemon
   Loaded: loaded (/lib/systemd/system/ceph-mon@.service; enabled)
   Active: failed (Result: start-limit) since Fri 2017-02-03 15:55:15 GMT; 55min ago
  Process: 35023 ExecStart=/usr/bin/ceph-mon -f --cluster ${CLUSTER} --id %i --setuser ceph --setgroup ceph (code=exited, status=1/FAILURE)
 Main PID: 35023 (code=exited, status=1/FAILURE)

Which tallies up with the timings of all but the last two entries in the mon logs.

The last two entries in the mon logs do tally up with the journalctl -x and syslog outputs though. Both of which suggest the mon failed to start.

I ended up with no mon process.

The latter part of what you say is correct though.
If I wait beyond the amount of time set in  /lib/systemd/system/ceph-mon@.service for the StartLimitInterval (default seems to be 30mins). And I try to start, the mon starts fine.

If I manually hack the StartLimitInterval setting in /lib/systemd/system/ceph-mon@.service to be 1 and perform systemctl daemon-reload, then try to start the mon immediately it also starts.

I have not been able to work out why it doesn't start when ansible tries to start it. But then can be started almost immediately afterwards with the above hack.

**Comment by leseb** [comment]
@ashak can you start from scratch, run `purge-cluster.yml`, then comment out these lines: https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-mon/tasks/main.yml#L5-L6 the playbook should fail after this, which is normal. Then try to run the monitor with systemd. See the result.

If this doesn't work, repeat the same operation and try to run the monitor manually from the command line and see if this works.

**Comment by ashak** [comment]
Running purge-cluster.yml failed on my hosts at:
TASK [include_vars] ***
fatal: [10.0.1.2]: FAILED! => {"ansible_facts": {}, "changed": false, "failed": true, "message": "Unable to find 'roles/ceph-common/defaults/main.yml' in expected paths."}

roles/ceph-common/defaults/main.yml definitely exists in my copy of the ceph-ansible git repo?!

I finished cleaning stuff up myself manually as much as possible with:
apt-get autoremove --purge ceph ceph-common; rm -r /etc/ceph /var/lib/ceph /etc/default/ceph

Then I commented out the suggested lines and ran the playbook again as requested.

It doesn't fail (at least it hadn't after a number of minutes). It sat at TASK [ceph-mon : collect admin and bootstrap keys (for or after kraken release)]  taking forever... Which I see is the first task after the commented out task.

I left ansible waiting and tried to start ceph using systemctl ceph-mon@vm1.service 

The results are as before. It doesn't start. None of the logs contain anything different to the logs in the second post on this thread. I'm sure there must be something I can do to obtain more verbose logging somewhere, but i've not managed to work that out yet. Suggestions welcome.

I purged again (with the same problem as before. Cleaned up manually, as before. And tried the second suggestion.

As with the first test, It sat at the same task waiting again.

I tried to start the mon manually from the command line which worked fine.

Interestingly, whilst waiting for it to get to the same place as before, I also kept looking at the status of ceph-mon@vm1.service on one of my hosts. Interestingly, after ceph was installed, but before ansible had got anywhere near to trying to start the mon, the status output changed to
root@vm1:~# systemctl status ceph-mon@vm1.service
● ceph-mon@vm1.service - Ceph cluster monitor daemon
   Loaded: loaded (/lib/systemd/system/ceph-mon@.service; enabled)
   Active: failed (Result: start-limit) since Mon 2017-02-06 14:14:16 GMT; 10s ago
  Process: 59963 ExecStart=/usr/bin/ceph-mon -f --cluster ${CLUSTER} --id %i --setuser ceph --setgroup ceph (code=exited, status=1/FAILURE)
 Main PID: 59963 (code=exited, status=1/FAILURE)

Suggesting to me that after install something is already trying to start my mon's and that's failing. This would definitely explain why ansible itself is then unable to start them due to the 30 min restart limit in the systemd config for mon services.

Perhaps this has to do with me being unable to purge everything properly?

I'd rebuild my test hosts entirely and try it out with a clean slate (at least until I could get purge-cluster.yml working correctly), but I can't do that with these hosts until i'm onsite, which is now 11 days time.

**Comment by leseb** [comment]
To run the purge playbook, first copy it to the root of the repo then run it.
The waiting for keys is expected, at this point you should kill ansible and try to run the monitor manually with systemd.

**Comment by ashak** [comment]
Purge works much better now!

Will report back on running the tests again shortly.

**Comment by ashak** [comment]
OK,

Purging the cluster appears to solve my problem.

With the two lines commented out I can start the mons correctly.

I then put them back in and tried again, my mons start up properly.

Clearly I had something still lying around and my attempt at purging all the things wasn't good enough.

Apologies for wasting time with this. Back to the original issue
