### ISSUE TITLE
Issue #1242 'fix' isn't really a fix for the same problem in all the other places

### ISSUE THREAD

**Issue by ashak** [ceph/ceph-ansible#1294]
The fix that closed issue #1242, I don't think it covered all the places where this fix would be relevant.

I was suggesting that I had the problem with:
ceph_conf_overrides.global.osd_pool_default_pg_num is defined
breaking when ceph_conf_overrides.global is not defined.

The first change I mentioned in the previous issue that i'd applied locally to try to move past the problem seems to be what's been implemented by the fix that's been put in place. However, with that fix in place,  the code breaks 4 lines later on line 80 with a very similar problem (which is what I mention in the second code change i'd made locally).

If I fix that problem it then breaks with a very similar problem again in roles/ceph-mon/tasks/rbd_pool_pgs.yml with task:
TASK [ceph-mon : destroy and recreate rbd pool if osd_pool_default_pg_num is not honoured]

If the fix is valid, then it would seem to me that there's numerous other places where a similar fix would need to be applied.

Either that or some suggestion somewhere on where ceph_conf_overrides.global should actually be defined because the documentation that i've followed so far doesn't appear to suggest I should have been doing that for any reason. It's possible i've missed it if there is some though.

**Comment by leseb** [comment]
@guits is looking into this :)

**Comment by guits** [comment]
@ashak could you test the PR #1301 ?

**Comment by ashak** [comment]
I created a PR for your branch containing one further place that needed the check to make it work for me.
