### ISSUE TITLE
harmonize docker systemd unit file location

### ISSUE THREAD

**Issue by ibotty** [ceph/ceph-ansible#1296]
They are stored in /etc/systemd/system or /var/lib/ceph. Which one, do you prefer? I would write a patch.

**Comment by leseb** [comment]
@ibotty where do you see systemd files on `/var/lib/ceph/`? AFAIR we only store the docker systemd unit files in `/etc/systemd/system`.

**Comment by ibotty** [comment]
ceph-ansible$ git grep /var/lib/ceph/ceph-
roles/ceph-mds/tasks/docker/start_docker_mds.yml:    dest: /var/lib/ceph/ceph-mds@.service
roles/ceph-mds/tasks/docker/start_docker_mds.yml:    src: /var/lib/ceph/ceph-mds@.service
roles/ceph-rgw/tasks/docker/start_docker_rgw.yml:    dest: /var/lib/ceph/ceph-rgw@.service
roles/ceph-rgw/tasks/docker/start_docker_rgw.yml:    src: /var/lib/ceph/ceph-rgw@.service

**Comment by leseb** [comment]
@ibotty I never paid attention to that, so please submit a PR to have everything in `/etc/systemd/system` just like mon and osd.
