### ISSUE TITLE
ceph-ansible/restart-mon.yml' does not exist

### ISSUE THREAD

**Issue by zhjunqin** [ceph/ceph-ansible#1309]
Hi,

When I follow https://github.com/ceph/ceph-ansible/wiki to Deploy without Vagrant, I find following problem.

RUNNING HANDLER [ceph.ceph-common : restart ceph mons] *************************
fatal: [CephAnMon]: FAILED! => {"failed": true, "reason": "ERROR! the file_name '/home/user/ceph/ceph-ansible/restart-mon.yml' does not exist, or is not readable"}

RUNNING HANDLER [ceph.ceph-common : restart ceph osds] *************************

RUNNING HANDLER [ceph.ceph-common : restart ceph mdss] *************************

RUNNING HANDLER [ceph.ceph-common : restart ceph rgws] *************************

RUNNING HANDLER [ceph.ceph-common : restart ceph nfss] *************************

Then I checked repository, I found the restart-mon.yml located in ceph-ansible/roles/ceph-common/handlers/. 
So, am I supposed to copy those restart-*.yml files to the directory where I run ansible-playbook site.yml, that is /home/user/ceph/ceph-ansible/?
Or did I do anything wrong about the execution directory?
Thanks.

**Comment by leseb** [comment]
Hello,
What's your ansible version?

**Comment by zhjunqin** [comment]
Thanks for reply, I'm using the master branch of ceph-ansible.

**Comment by leseb** [comment]
And the Ansible version itself? `ansible --version`

**Comment by chyka** [comment]
I'm running into this issue as well, on ansible 2.0.0.2

**Comment by leseb** [comment]
This is fixed by: https://github.com/ceph/ceph-ansible/pull/1412
