### ISSUE TITLE
TASK [ceph-mon : create ceph filesystem] fails if file system already exists

### ISSUE THREAD

**Issue by batrick** [ceph/ceph-ansible#1314]
````
fatal: [ceph-mon-1]: FAILED! => {
    "changed": false,
    "cmd": [
        "ceph",
        "--cluster",
        "ceph",
        "fs",
        "new",
        "cephfs",
        "cephfs_metadata",
        "cephfs_data"
    ],
    "delta": "0:00:00.225630",
    "end": "2017-02-16 20:24:49.375255",
    "failed": true,
    "invocation": {
        "module_args": {
            "_raw_params": "ceph --cluster ceph fs new cephfs cephfs_metadata cephfs_data",
            "_uses_shell": false,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "warn": true
        },
        "module_name": "command"
    },
    "rc": 22,
    "start": "2017-02-16 20:24:49.149625",
    "stderr": "Error EINVAL: pool 'cephfs_metadata' already contains some objects. Use an empty pool instead.",
    "stdout": "",
    "stdout_lines": [],
    "warnings": []
}
````

Also, this command and the pool creation need only be executed on a single monitor?

**Comment by leseb** [comment]
@batrick yes on a single monitor and we should check if the pool already exists. Can you make a PR for this?

**Comment by batrick** [comment]
@leseb I have made an issue for `fs new` failing when it should silently succeed: http://tracker.ceph.com/issues/18964

In any case, I would think that the right thing to do is check if that file system already exists with `ceph fs ls` before blindly trying.

As for making a PR, I'm not really sure what the ansible incantations are to get it to work and don't really have time right now to learn (sorry!).

**Comment by leseb** [comment]
@batrick no worries, @guits can you look into this please? Thanks!

**Comment by guits** [comment]
@leseb yes i'll take care of this :)

**Comment by leseb** [comment]
@guits thanks!

**Comment by guits** [comment]
@batrick just to be sure, what version of ceph are you using?

**Comment by batrick** [comment]
https://github.com/ceph/ceph-ci/tree/wip-multimds-tests
