### ISSUE TITLE
"disable transparent hugepage" task actually do nothing

### ISSUE THREAD

**Issue by nikitych** [ceph/ceph-ansible#1319]
To configure kernel the [task is using](https://github.com/ceph/ceph-ansible/blob/3023d0339ccbedf88d0b57264a91e039369e60dd/roles/ceph-common/tasks/misc/system_tuning.yml#L8) "[command](http://docs.ansible.com/ansible/command_module.html)" module which is not respect operator ">". So this task just print to "stdout": "never > /sys/kernel/mm/transparent_hugepage/enabled"

To really change kernel config you have to use module "[shell](http://docs.ansible.com/ansible/shell_module.html#shell)"

**Comment by leseb** [comment]
Thanks!
