### ISSUE TITLE
create openstack pools and keys even for containerized deployments

### ISSUE THREAD

**Issue by leseb** [ceph/ceph-ansible#1321]

**Comment by leseb** [comment]
@guits wanna have a look?
Basically, we need to do this: https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-mon/tasks/ceph_keys.yml#L106

And add it here: https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-mon/tasks/main.yml#L26

So we can create pools and keys even when we do containerized deployment.

**Comment by guits** [comment]
@leseb okey, i'll have a look at this

**Comment by leseb** [comment]
@guits Thanks!
