### ISSUE TITLE
One or more undefined variables: 'host' is undefined

### ISSUE THREAD

**Issue by rlljorge** [ceph/ceph-ansible#1337]
I have a cluster in production and I would like test some change and upgrades.
I trying create a test environment. I created 3 vm's to simulate my production environment and I copied the original ceph-ansible files from the production to the test.

When I try deploy this new environment, I recive the follow error:

TASK: [ceph.ceph-common | generate ceph configuration file] ******************* 
<osd01> ESTABLISH CONNECTION FOR USER: root
<osd01> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/root/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 osd01 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1488421504.83-157560430475868 && echo $HOME/.ansible/tmp/ansible-tmp-1488421504.83-157560430475868'
<osd02> ESTABLISH CONNECTION FOR USER: root
<osd02> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/root/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 osd02 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1488421504.83-16166007620527 && echo $HOME/.ansible/tmp/ansible-tmp-1488421504.83-16166007620527'
<osd03> ESTABLISH CONNECTION FOR USER: root
<osd03> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/root/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 osd03 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1488421504.84-200607805499601 && echo $HOME/.ansible/tmp/ansible-tmp-1488421504.84-200607805499601'
fatal: [osd03] => One or more undefined variables: 'host' is undefined
fatal: [osd02] => One or more undefined variables: 'host' is undefined
fatal: [osd01] => One or more undefined variables: 'host' is undefined

FATAL: all hosts have already failed -- aborting

root@deploy:/opt/ceph-ansible# git describe --tags
v1.0.5-323-gc127df7
root@deploy:/opt/ceph-ansible# ansible --version
ansible 1.9.4
  configured module search path = None

root@deploy:/opt/ceph-ansible# ansible -m ping all
osd01 | success >> {
    "changed": false, 
    "ping": "pong"
}

osd02 | success >> {
    "changed": false, 
    "ping": "pong"
}

osd03 | success >> {
    "changed": false, 
    "ping": "pong"
}

This is works in production, the only change in config files was:

group_vars/all
from: monitor_interface: bond0 to monitor_interface: enp0s8

**Comment by leseb** [comment]
We do not support Ansible 1.9.4, we support 2.2.1.0. Please test with that.

**Comment by rlljorge** [comment]
Thank you for your answer, but I created the virtual environment just for the test the ansible  and the ceph-ansible upgrade.
I would like test this before apply in production.

Any ideias ?

**Comment by leseb** [comment]
Can't you get the right ansible version in your virtualenv?

**Comment by rlljorge** [comment]
Ok! Here are:

root@deploy01:/opt/ceph-ansible# ansible --version
ansible 2.2.1.0
  config file = /opt/ceph-ansible/ansible.cfg
  configured module search path = Default w/o overrides
root@deploy01:/opt/ceph-ansible#  git describe --tags
v1.0.5-323-gc127df7
root@deploy01:/opt/ceph-ansible# 

TASK [ceph.ceph-common : define vm.min_free_kbytes] ****************************
ok: [server01]
ok: [server02]
ok: [server03]

TASK [ceph.ceph-common : apply operating system tuning] ************************
fatal: [server01]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'ansible.vars.unsafe_proxy.AnsibleUnsafeText object' has no attribute 'name'\n\nThe error appears to have been in '/opt/ceph-ansible/roles/ceph.ceph-common/tasks/misc/system_tuning.yml': line 30, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: apply operating system tuning\n  ^ here\n"}
fatal: [server02]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'ansible.vars.unsafe_proxy.AnsibleUnsafeText object' has no attribute 'name'\n\nThe error appears to have been in '/opt/ceph-ansible/roles/ceph.ceph-common/tasks/misc/system_tuning.yml': line 30, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: apply operating system tuning\n  ^ here\n"}
fatal: [server03]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'ansible.vars.unsafe_proxy.AnsibleUnsafeText object' has no attribute 'name'\n\nThe error appears to have been in '/opt/ceph-ansible/roles/ceph.ceph-common/tasks/misc/system_tuning.yml': line 30, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: apply operating system tuning\n  ^ here\n"}
	to retry, use: --limit @/opt/ceph-ansible/site.retry

PLAY RECAP *********************************************************************
server01                   : ok=5    changed=0    unreachable=0    failed=1   
server02                   : ok=5    changed=0    unreachable=0    failed=1   
server03                   : ok=5    changed=0    unreachable=0    failed=1

**Comment by leseb** [comment]
Please use this branch: https://github.com/ceph/ceph-ansible/tree/stable-2.1 or master. You run an old version of ceph-ansible.
