### ISSUE TITLE
Containerized deployment only supports journal colocation

### ISSUE THREAD

**Issue by fitschn** [ceph/ceph-ansible#1341]
Hi,

the current docker deployment doesn't support different OSD scenarios. It ignores the variables and puts the journal on the osd disk. It's not possible to use a separate SSD Disk as journal device.

I couldn't find any documentation for this behavior. Is this already planned for the future?

**Comment by leseb** [comment]
Not true, we support:

* journal colocation 
* dedicated device for journal
* dmcrypt

Please see: https://github.com/ceph/ceph-ansible/blob/master/group_vars/osds.yml.sample#L189-L210

**Comment by fitschn** [comment]
Ah OK! Sorry! I assumed that you check the variable journal_collocation for the docker deployment as well. I've overlooked the additional vars.

**Comment by leseb** [comment]
No worries :)
