### ISSUE TITLE
MON doesn't join cluster after restart

### ISSUE THREAD

**Issue by fitschn** [ceph/ceph-ansible#1342]
Hi,

my scenario: I have three server. On each server i have one MON daemon deployed. For the deployment i use the containerized scenario, so every mon service runs in its own docker container.

The expected behavior is, that the mon daemon rejoins the existing cluster.

The actual behavior: If I restart one server, the docker container with the mon daemon tries to spawn but exits with the following error message:

```
mon does not exist in monmap, will attempt to join an existing cluster
...
e1129 not in monmap and have been in a quorum before; must have been removed
e1129 commit suicide!
```

I didn't changed anything during the mon reboot.

**Comment by fitschn** [comment]
It seems to me that the file `/etc/ceph/monmap` is the problem. It contains only the first mon on all three nodes. If I override this file with the current monmap, after all mon daemons are startet, a mon restart is no problem anymore.

So maybe we have to deploy a final monmap on all nodes, after the actually mon deployment.

**Comment by leseb** [comment]
Did you run the deployment with `serial: 1`? Did you use this file? https://github.com/ceph/ceph-ansible/blob/master/site-docker.yml.sample

**Comment by fitschn** [comment]
Yes to both of your questions :)

**Comment by leseb** [comment]
Normally this works with an initial monmap built with a single node :/

**Comment by leseb** [comment]
Fixed in recent versions.
