### ISSUE TITLE
[RFE] Add debugging option

### ISSUE THREAD

**Issue by b-ranto** [ceph/ceph-ansible#1343]
Hi,

it would be really great if we could tell ansible to turn on debugging during installation/deployment. I'm specifically interested in enabling debugging for calamari (*) but a global option that would enable debugging for all the projects would be nice as well.

To enable debugging in calamari, you just need to modify /etc/calamari/calamari.conf and edit two debugging related variables (from WARN to DEBUG):
- log_level in cthulhu section
- log_level in calamari section

**Comment by leseb** [comment]
Isn't `-vvvv` enough as flag when you run `ansible-playbook`?

**Comment by b-ranto** [comment]
@leseb that will just improve logging verbosity for ansible itself.

Maybe I was not clear enough. What I am interested in, here, is the ability to set the debugging level for projects like ceph or (specifically in my case) calamari. In calamari, this is achieved by modifying the `/etc/calamari/calamari.conf` file. This file defines the log levels for calamari-lite daemon which goes into the /var/log/calamari/ directory. I will give implementing this myself a shot.

**Comment by b-ranto** [comment]
The idea here being that we could get the debugging output for calamari/ceph logs directly from customers (or qa) when they are deploying the clusters just by asking them to turn the debugging on in a yaml file.

**Comment by b-ranto** [comment]
@leseb This implements the debugging option (well, for calamari):

https://github.com/ceph/ceph-ansible/pull/1356
