### ISSUE TITLE
[RFE] Allow the use of chacra for package installation

### ISSUE THREAD

**Issue by b-ranto** [ceph/ceph-ansible#1344]
Currently, there are several installation methods but afaik, we still can't use the upstream chacra (I was playing with a downstream version so this might have been stripped out or maybe, I missed something).

This might allow the installation of any package that we build upstream. This could be an option that would take a list of projects and it would enable the proper repos (if found). Another option could specify what packages should be installed/updated/force-installed.

This would really ease up upstream debugging since we would not have to set up these repositories manually.

There is also an API for chacra (called shaman) that can help you do the appropriate queries and find the appropriate repositories.

**Comment by guits** [comment]
Closed due to inactivity, feel free to re-open if needed. Thanks!
