### ISSUE TITLE
radosgw / RGW need configurable options like ssl_certificate

### ISSUE THREAD

**Issue by mcv21** [ceph/ceph-ansible#1348]
Hi,

I want to have in my ceph.conf config like this:
`rgw frontends = "civetweb port=443s ssl_certificate=/etc/ceph/cog.pem"`

There isn't currently a good way to add the ssl_certificate line (you can abuse some of the existing config parameters); could we have a radosgw_further_options variable or somesuch, please?

[I'm using your stable-2.1 branch]

Thanks.

**Comment by leseb** [comment]
This will be available in the next stable release. We should release stable-2.2 in a couple of weeks. Thanks for your patience.
