### ISSUE TITLE
rgw role doesn't have ceph keyring

### ISSUE THREAD

**Issue by vasukulkarni** [ceph/ceph-ansible#1351]
since the radosgw admin exists only on the rgw node it makes sense to have the admin keyring on rgw role, currently i dont see what the workflow is for running the admin commands

**Comment by leseb** [comment]
You have an option to copy the admin key on the RGW nodes, just set `copy_admin_key: true`.
Then run your radosgw-admin commands.

**Comment by vasukulkarni** [comment]
@leseb shouldn't this be by default? I would say the other way around should be default eg: copy_admin_key: false , without admin keyring there would be no way to use the admin cli.

**Comment by leseb** [comment]
@vasukulkarni you're right, although I think `radosgw-admin` should be part of `ceph-common`, so this command could be executed from a monitor node or a client node.
I don't think the rgw nodes should have the admin key available.

**Comment by vasukulkarni** [comment]
Yes i agree, I think it should be part of ceph-common and one can use any monitor node for admin operations. I believe this will be a devops ticket then.

**Comment by ktdreyer** [comment]
Before we change the packaging, can you try copy the `/usr/bin/radosgw-admin` binary to a node without the `ceph-radosgw` package installed, and ensure that it works properly? (and no missing libs with `ldd /usr/bin/radosgw-admin`). I just want to be sure it's isolated and can move to ceph-common without dragging in more of what we ship in `ceph-radosgw`

**Comment by vasukulkarni** [comment]
It seems to work,  I dont have ceph-radosgw but I do have ceph-common/ceph-osd, I will raise a devops ticket anyway

[cephuser@ceph-jenkins-build-run63-node8-rgw ~]$ ldd /usr/bin/radosgw-admin 
	linux-vdso.so.1 =>  (0x00007ffd6eb8d000)
	librgw.so.2 => /lib64/librgw.so.2 (0x00007f9c0c5df000)
	librados.so.2 => /lib64/librados.so.2 (0x00007f9c02e5e000)
	libboost_system-mt.so.1.53.0 => /lib64/libboost_system-mt.so.1.53.0 (0x00007f9c02c59000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f9c02a3d000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f9c02735000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f9c0251e000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f9c0215d000)
	libssl3.so => /lib64/libssl3.so (0x00007f9c01f1a000)
	libsmime3.so => /lib64/libsmime3.so (0x00007f9c01cf2000)
	libnss3.so => /lib64/libnss3.so (0x00007f9c019cc000)
	libnssutil3.so => /lib64/libnssutil3.so (0x00007f9c017a0000)
	libplds4.so => /lib64/libplds4.so (0x00007f9c0159b000)
	libplc4.so => /lib64/libplc4.so (0x00007f9c01396000)
	libnspr4.so => /lib64/libnspr4.so (0x00007f9c01158000)
	libcurl.so.4 => /lib64/libcurl.so.4 (0x00007f9c00eee000)
	libexpat.so.1 => /lib64/libexpat.so.1 (0x00007f9c00cc4000)
	libfcgi.so.0 => /lib64/libfcgi.so.0 (0x00007f9c00ab9000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f9c0089e000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f9c0069a000)
	libboost_thread-mt.so.1.53.0 => /lib64/libboost_thread-mt.so.1.53.0 (0x00007f9c00483000)
	libboost_random-mt.so.1.53.0 => /lib64/libboost_random-mt.so.1.53.0 (0x00007f9c0027e000)
	libblkid.so.1 => /lib64/libblkid.so.1 (0x00007f9c00040000)
	libuuid.so.1 => /lib64/libuuid.so.1 (0x00007f9bffe3b000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f9bffc32000)
	libboost_iostreams-mt.so.1.53.0 => /lib64/libboost_iostreams-mt.so.1.53.0 (0x00007f9bffa18000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f9bff716000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f9c164c8000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f9bff4ff000)
	libidn.so.11 => /lib64/libidn.so.11 (0x00007f9bff2cb000)
	libssh2.so.1 => /lib64/libssh2.so.1 (0x00007f9bff0a1000)
	libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007f9bfee53000)
	libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007f9bfeb6b000)
	libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007f9bfe939000)
	libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007f9bfe735000)
	liblber-2.4.so.2 => /lib64/liblber-2.4.so.2 (0x00007f9bfe525000)
	libldap-2.4.so.2 => /lib64/libldap-2.4.so.2 (0x00007f9bfe2d2000)
	libnsl.so.1 => /lib64/libnsl.so.1 (0x00007f9bfe0b9000)
	libbz2.so.1 => /lib64/libbz2.so.1 (0x00007f9bfdea8000)
	libssl.so.10 => /lib64/libssl.so.10 (0x00007f9bfdc3a000)
	libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00007f9bfd84f000)
	libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007f9bfd640000)
	libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007f9bfd43c000)
	libsasl2.so.3 => /lib64/libsasl2.so.3 (0x00007f9bfd21e000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f9bfcff7000)
	libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007f9bfcdbf000)
	libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f9bfcb5e000)
	libfreebl3.so => /lib64/libfreebl3.so (0x00007f9bfc95b000)

**Comment by vasukulkarni** [comment]
Filed for devops, http://tracker.ceph.com/issues/19577 , Closing
