### ISSUE TITLE
Just grabbing the first ip address from the NIC link makes the monclient authentication fail

### ISSUE THREAD

**Issue by wind0204** [ceph/ceph-ansible#1352]
Hi, I'm trying to deploy a tiny ceph cluster with only 1 mon. but I've found out it's stuck at some point of keyring deployment. and dug into it and found some...

> TASK [ceph-mon : collect admin and bootstrap keys (for or after kraken release)] ***
> [DEPRECATION WARNING]: always_run is deprecated. Use check_mode = no instead..
> This feature will be removed in version 2.4. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
> ok: [peta-0000-01] => {"changed": false, "cmd": ["ceph-create-keys", "--cluster", "ceph", "-i", "peta-0000-01"], "delta": "0:05:00.259558", "end": "2017-03-08 11:49:11.365664", "failed": false, "failed_when_result": false, "rc": 1, "start": "2017-03-08 11:44:11.106106", "stderr": "INFO:ceph-create-keys:Talking to monitor...\n2017-03-08 11:49:11.3353637f29158d0700  0 monclient(hunting): authenticate timed out after 300\n2017-03-08 11:49:11.335405 7f29158d0700  0 librados: mon. authentication error (110) Connection timed out\nError connecting to cluster: TimedOut\nINFO:ceph-create-keys:Cannot get or create admin key, permission denied", "stdout": "", "stdout_lines": [], "warnings": []}
> 
> *#* and then it fails 300 seconds after doing the next TASK [ceph-mon : wait for ceph.client.admin.keyring exists]

I guess it's because the ceph-mgr failing starting due to a failure at the last line of 4 ExecStartPre lines in ..systemd/system/ceph-mgr@.service: ExecStartPre=/usr/bin/ceph -i /var/lib/ceph/mgr/${CLUSTER}-%i/keyring auth add mgr.%i mon 'allow *' --keyring=/var/lib/ceph/mon/${CLUSTER}-%i/keyring --name=mon.
( ceph-mgr tries to start after the TASK [ceph-mon : start the monitor service] )

> root@peta-0000-01:~\# systemctl status ceph-mgr@*
> ● ceph-mgr@peta-0000-01.service - Ceph cluster manager daemon
>    Loaded: loaded (/lib/systemd/system/ceph-mgr@.service; disabled; vendor preset: enabled)
>    Active: activating (start-pre) since Wed 2017-03-08 16:18:18 KST; 3s ago
>   Process: 8118 ExecStartPre=/bin/sh -c exec chown -R ceph.ceph /var/lib/ceph/mgr/${CLUSTER}-%i (code=exited, status=0/SUCCESS)
>   Process: 8076 ExecStartPre=/bin/sh -c [ -f /var/lib/ceph/mgr/${CLUSTER}-%i/keyring ] || /usr/bin/ceph-authtool --create-keyring --gen-key --name=mgr.%i /var
>   Process: 8024 ExecStartPre=/bin/sh -c exec mkdir -p /var/lib/ceph/mgr/${CLUSTER}-%i (code=exited, status=0/SUCCESS)
>   Control: 8130 (ceph)
>    CGroup: /system.slice/system-ceph\x2dmgr.slice/ceph-mgr@peta-0000-01.service
>            └─control
>              └─8130 /usr/bin/python2.7 /usr/bin/ceph -i /var/lib/ceph/mgr/ceph-peta-0000-01/keyring auth add mgr.peta-0000-01 mon allow * --keyring=/var/lib/ceph/mon/ceph-peta-0000-01
> 
> root@peta-0000-01:~#  /usr/bin/ceph -i /var/lib/ceph/mgr/ceph-peta-0000-01/keyring auth add mgr.%i mon 'allow *' --keyring=/var/lib/ceph/mon/ceph-peta-0000-01
> /keyring --name=mon.                                                                                                                                          
> 2017-03-08 15:47:12.227178 7fbf414f7700  0 monclient(hunting): authenticate timed out after 300
> 2017-03-08 15:47:12.227207 7fbf414f7700  0 librados: mon. authentication error (110) Connection timed out
> Error connecting to cluster: TimedOut

anyone have an idea how to fix it?

**Comment by wind0204** [comment]
I just figured out how to fix it which is change 'mon host' to an ip address within 'cluster network' or 'public network'. I don't understand why it makes the monclient unable to connect and authenticate in the first place though.

Mine had been set to a public IP address for the internet starting with 116.193.. and I've replaced it with 192.168.255.253.

> # ip addr
> 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
>     link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
>     inet 127.0.0.1/8 scope host lo
>        valid_lft forever preferred_lft forever
>     inet6 ::1/128 scope host 
>        valid_lft forever preferred_lft forever
> ...
> 6: ceph-pub-0-1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq master ceph-pub-0 state UP group default qlen 1000
>     link/ether a0:36:9f:9c:8e:14 brd ff:ff:ff:ff:ff:ff
>     inet6 fe80::a236:9fff:fe9c:8e14/64 scope link 
>        valid_lft forever preferred_lft forever
> 9: ceph-pub-0: <BROADCAST,MULTICAST,PROMISC,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
>     link/ether a0:36:9f:9c:8e:14 brd ff:ff:ff:ff:ff:ff
>     inet 116.193.???.??/27 brd 116.193.90.159 scope global ceph-pub-0
>        valid_lft forever preferred_lft forever
>     inet 10.0.0.61/27 brd 10.0.0.63 scope global ceph-pub-0
>        valid_lft forever preferred_lft forever
>     inet 192.168.0.61/27 brd 10.0.0.63 scope global ceph-pub-0
>        valid_lft forever preferred_lft forever
>     inet 192.168.255.253/27 brd 192.168.255.255 scope global ceph-pub-0
>        valid_lft forever preferred_lft forever
>     inet6 fe80::a236:9fff:fe9c:8e14/64 scope link 
>        valid_lft forever preferred_lft forever

So, should I edit this line of ceph.conf.j2?
`mon host = {% for host in groups[mon_group_name] %}{{ hostvars[host]['ansible_all_ipv4_addresses'] | ipaddr(monitor_address_block) | first }}{% if not loop.last %},{% endif %}{% endfor %}`

**Comment by wind0204** [comment]
well, I just stopped using monitor_interface in ceph.conf.j2 and replaced it with monitor_address_block, but the jinja2 code should be fixed some day; I'd be love to submit my code but I'm too busy these days in a small team (actually I'm the only one in a one man tech team

**Comment by leseb** [comment]
#1594 will fix that
