### ISSUE TITLE
Should not over-write fetch/ceph_cluster_uuid.conf

### ISSUE THREAD

**Issue by mcv21** [ceph/ceph-ansible#1353]
Hi,

I'm on stable-2.1 branch.

I ran ceph-ansible with -C [check mode] and it failed; one of the failed tasks was "is ceph running already?" (false failure - I tried running the command by hand and that worked). 

If this fails, then "generate cluster fsid" will generate a new uuid, and over-write an existing ceph_cluster_uuid.conf file. That means ceph-ansible will try and change the fsid of the cluster.

It should not do this. Sorry, my analysis above may be wrong, but ceph-ansible did definitely change the cluster fsid :-/

**Comment by leseb** [comment]
This is expected since `is ceph running already?` rc was `!=0`. I thought using `always_run: yes` would make Ansible happy.

**Comment by mcv21** [comment]
Mmm. I confess I'm not entirely sure what went wrong (and am a bit reluctant to repro since I don't have a test-cluster to play with) :-/

**Comment by leseb** [comment]
Once you'll deploy a cluster without using "check mode" this should be fine, so I'm tempted to close this, what do you think?

**Comment by mcv21** [comment]
Check mode is the sort of thing I want to do against my cluster - e.g. "once we come to update to v 2.2 of ceph-ansible, what changes to our config will happen?"

**Comment by leseb** [comment]
Oh I see, that makes sense, although I'm not sure how to fix this...

**Comment by guits** [comment]
Closed due to inactivity, feel free to re-open if needed. Thanks!
