### ISSUE TITLE
Setting ntp_service_enabled = False still installs ntp

### ISSUE THREAD

**Issue by gaudenz** [ceph/ceph-ansible#1354]
Even if the variable to not enabled the NTP service is set, the playbooks still install ntp through the XXX_package_dependencies variables. This makes it impossible to use a different NTP implementation (like openntpd or chrony) without also overriding the XXX_package_dependencies variable.

IMO installing the ntp package should be in it's own task and only be done when ntp_service_enabled is set to to True. I expect that in most environments where you manage all your hosts with Ansible you already have some kind of base playbook which takes care of installing and configuring an NTP daemon.

**Comment by leseb** [comment]
@guits can you look into this please?
