### ISSUE TITLE
tag-build-master-kraken-centos-7 image is not up-to-date

### ISSUE THREAD

**Issue by ibotty** [ceph/ceph-ansible#1357]
It does not include scenarios/osd_common.sh.

**Comment by leseb** [comment]
Now it should be sorry about that?

**Comment by ibotty** [comment]
Sorry, I don't understand. Can you elaborate?

**Comment by leseb** [comment]
Sorry for the confusion, I pushed a new version a couple of days ago so the image on the Docker Hub should have the fix now :).
