### ISSUE TITLE
cluster client configuration

### ISSUE THREAD

**Issue by cornelius-keller** [ceph/ceph-ansible#136]
Hi all,

can anyone provide some documentation on how to setup a client for this cluster?
I try to tests some rbd use cases like creating mounting and cloning rbd images with a local cluster sat up with vagrant.

I tried copying the monitor configuration from mon1:/etc/ceph/\* to my hostmachine:/etc/ceph/*

doing so ceph health outputs:

```
root@jck2:~# ceph health
HEALTH_OK
```

ceph -w

```
root@jck2:~# ceph -w
    cluster 4a158d27-f750-41d5-9e7f-26ce4c9d2d45
     health HEALTH_OK
     monmap e1: 3 mons at {ceph-mon0=192.168.42.10:6789/0,ceph-mon1=192.168.42.11:6789/0,ceph-mon2=192.168.42.12:6789/0}, election epoch 6, quorum 0,1,2 ceph-mon0,ceph-mon1,ceph-mon2
     osdmap e14: 6 osds: 6 up, 6 in
      pgmap v24: 192 pgs, 3 pools, 0 bytes data, 0 objects
            207 MB used, 65126 MB / 65333 MB avail
                 192 active+clean

2014-11-10 12:59:34.364045 mon.0 [INF] pgmap v24: 192 pgs: 192 active+clean; 0 bytes data, 207 MB used, 65126 MB / 65333 MB avail
```

ceph osd tree:

```
root@jck2:~# ceph osd tree
# id    weight  type name   up/down reweight
-1  0.05997 root default
-2  0.01999     host ceph-osd0
0   0.009995            osd.0   up  1   
3   0.009995            osd.3   up  1   
-3  0.01999     host ceph-osd1
2   0.009995            osd.2   up  1   
4   0.009995            osd.4   up  1   
-4  0.01999     host ceph-osd2
1   0.009995            osd.1   up  1   
5   0.009995            osd.5   up  1   

```

creating of rbd images works!

```
root@jck2:~# rbd create --image-format 2 --size 512 test --id admin
root@jck2:~# rbd ls
test
```

However if I try to map and mount an image i get the following error:

```
root@jck2:~# rbd map test --id admin
rbd: add failed: (95) Operation not supported
```

Can anyone tell me why map fails? If someone provides me with some hints on setting up the client I am willing to contribute to ceph-ansible by writing a playbook that configures clients and document the setup for other users.

Thanks in advance
- Cornelius

**Comment by rootfs** [comment]
For CentOS7 (kernel 3.10), this is still issue. For now I use the following patch
```diff
diff --git a/roles/ceph-common/defaults/main.yml b/roles/ceph-common/defaults/main.yml
index c34a3ce..5411cb1 100644
--- a/roles/ceph-common/defaults/main.yml
+++ b/roles/ceph-common/defaults/main.yml
@@ -105,8 +105,8 @@ ceph_dev_redhat_distro: centos7
 #
 fsid: "{{ cluster_uuid.stdout }}"
 cephx: true
-cephx_require_signatures: true # Kernel RBD does NOT support signatures for Kernels < 3.18!
-cephx_cluster_require_signatures: true
+cephx_require_signatures: false # Kernel RBD does NOT support signatures for Kernels < 3.18!
+cephx_cluster_require_signatures: false
 cephx_service_require_signatures: false
 max_open_files: 131072
 disable_in_memory_logs: true # set this to false while enabling the options below
```

**Comment by leseb** [comment]
@rootfs you should probably override this variable from group_vars/all instead.
So your change won't be tracked in git :)
I was wondering if I shouldn't put this to 'false' by default anyway... Feel free to PR the change and I'll merge it. ;)

**Comment by rootfs** [comment]
awesome, will ping you later

**Comment by leseb** [comment]
@rootfs sure :)

**Comment by rokka-n** [comment]
Have you guys had a chance validate client basic operations on centos7.1 with cephx enabled?
I still seeing the same problem, although OS has newer kernel that supposedly works with cephx.
I'd like to make it work properly.

```
[vagrant@ceph-mon0 ~]$ uname -a
Linux ceph-mon0 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
[vagrant@ceph-mon0 ~]$ sudo rbd create --image-format 2 --size 512 test2 --id admin
[vagrant@ceph-mon0 ~]$ sudo rbd map  test2
rbd: sysfs write failed
rbd: map failed: (95) Operation not supported
```

Aditional question, how to restart services on centos nodes? 
systemctl can't work with them. For example on mon0:
```
[vagrant@ceph-mon0 ~]$ sudo systemctl list-unit-files | grep ceph
ceph-create-keys@.service                   static
ceph-disk@.service                          static
ceph-mds@.service                           disabled
ceph-mon@.service                           enabled
ceph-osd@.service                           disabled
ceph-radosgw@.service                       disabled
ceph.target                                 disabled
```

**Comment by leseb** [comment]
@rokka-n

For a monitor: systemctl restart ceph-mon@<hostname>.service
For an OSD: systemctl restart ceph-osd@<id>.service

**Comment by subhashchand** [comment]
$ rbd create rbd/test --size 2G --image-feature layering
$rbd info rbd/test
$ rbd map rbd/test 
rbd: sysfs write failed
In some cases useful info is found in syslog - try "dmesg | tail" or so.
rbd: map failed: (13) Permission denied

**Comment by subhashchand** [comment]
now i am facing this issue. i have applied upper mention suggestions but unfortunately not success.

**Comment by subhashchand** [comment]
Want to  setup CEPH cluster integration with OpenNebula 5.2. but we faced some issues on that, after creating CEPH cluster when try to integrating with opennebula frontend node then its not getting up and not showing disk uasble space.

[cephuser@storage1 ~]$ ceph -s
    cluster dd8ea244-d2e4-4948-b3b8-ec2ddedeff80
     health HEALTH_OK
     monmap e1: 3 mons at {storage1=XX:XX:XX:137:6789/0,storage2=XX.XX.XX.138:6789/0,storage3=XX.XX.XX.139:6789/0}
            election epoch 70, quorum 0,1,2 storage1,storage2,storage3
     osdmap e204: 3 osds: 3 up, 3 in
            flags sortbitwise,require_jewel_osds
      pgmap v312560: 2112 pgs, 3 pools, 14641 kB data, 24 objects
            19914 MB used, 11104 GB / 11123 GB avail
                2112 active+clean


[oneadmin@node1 ~]$ cat cephds.conf
NAME = "cephds"
DS_MAD = ceph
TM_MAD = ceph
DISK_TYPE = RBD
POOL_NAME   = data
CEPH_HOST   = storage1-storage2-storage3
CEPH_USER   = oneadmin
CEPH_SECRET = "AQCU1GxYHmbkBxAA6TlD6q+PyMTL+/a+AB+2bg==2dsf"
BRIDGE_LIST = storage1   

Plz suggest us.

**Comment by subhashchand** [comment]
![datastore](https://cloud.githubusercontent.com/assets/10760179/21849833/d7eeb8ba-d82d-11e6-9131-8011a5996131.PNG)

**Comment by leseb** [comment]
@subhashchand what are the features enabled on that test image?

Can you run an `rbd info <pool>/<image>`?
