### ISSUE TITLE
docker pid = 1 running sshd

### ISSUE THREAD

**Issue by gator1** [ceph/ceph-ansible#1360]
Trying with docker, my mon-node1 is running sshd 
[root@6d7c4ff37de7 ~]# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0  82476  6184 ?        Ss   00:53   0:00 /usr/sbin/sshd -D

this makes the PID = 1 running sshd. 

I guess this makes the setup think
"ansible_service_mgr": "sshd",

so that it failed if systemd is not present. The system is centos 7 (the daemon image of ceph-docker). 

Is there a way to override the ansible_service_mgr = "systemd"? 
Tried to to add into all.yml
ceph_conf_overrides:
   mons:
     ansible_service_mgr: systemd

it doesn't help. Any suggestions?

TASK [ceph.ceph-common : fail if systemd is not present] ***********************
fatal: [mon-node1]: FAILED! => {"changed": false, "failed": true, "msg": "Systemd must be present"}
fatal: [mon-node2]: FAILED! => {"changed": false, "failed": true, "msg": "Systemd must be present"}
fatal: [mon-node3]: FAILED! => {"changed": false, "failed": true, "msg": "Systemd must be present"}

**Comment by leseb** [comment]
Not sure what you're trying to achieve but putting sshd inside a container is not recommended and nor is running ansible inside a container...

**Comment by gator1** [comment]
I thought I could use ansible to install ceph on containers. If not please let me know and I will close this.

**Comment by leseb** [comment]
@gator1 yes you can, start with vagrant for this. Set docker https://github.com/ceph/ceph-ansible/blob/master/vagrant_variables.yml.sample#L4 to true and then run `vagrant up`.
