### ISSUE TITLE
What do you think to create stable branch by version?

### ISSUE THREAD

**Issue by harobed** [ceph/ceph-ansible#1361]
Hi,

what do you think to create stable branch by version?

Best regards,
Stéphane

**Comment by harobed** [comment]
I see that http://lists.ceph.com/pipermail/ceph-ansible-ceph.com/2017-January/000025.html

**Comment by leseb** [comment]
This is not part of our current strategy I'm afraid. We release ceph-ansible version every ~3 months. Each stable version will be able to support the current LTS and potentially another release.
For example, we currently support and test Jewel, the current LTS but soon we will have stable-2.2 with both Jewel and Kraken support.
