### ISSUE TITLE
What do you think to use Ansible Tags on various component (mon, osd…)?

### ISSUE THREAD

**Issue by harobed** [ceph/ceph-ansible#1362]
Hi,

what do you think to use Ansible Tags on various component (mon, osd…)?

Example, now I have some error on OSD, I would like execute only OSD Ansible tasks.

Best regards,
Stéphane

**Comment by leseb** [comment]
Hum why don't you use `--limit` or comment host in your inventory file?

**Comment by srhb** [comment]
@leseb 
Wouldn't that break every ceph.conf on the osds since now there's no known monitor addresses? Or do you always hardcode this?

**Comment by leseb** [comment]
@srhb you're right, this will indeed break the play. Our roles are kinda inter-dependant from common --> mon --> any other Ceph daemon.
Anyway, the playbook is idempotent so it's safe to run monitors then OSDs, you can also play with you inventory file if you don't want to go through all your OSDs.
