### ISSUE TITLE
Is it possible to configure rbd-mirror peering to a remote cluster

### ISSUE THREAD

**Issue by TejasC88** [ceph/ceph-ansible#1390]
Using the rbd-mirror role, we can get the rbd-mirror daemon running on both the clusters.
Can we get the task to configure the mirror peer also?
I see that this is defined here:
 https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-rbd-mirror/tasks/configure_mirroring.yml

Specifically using these variables:
ceph_rbd_mirror_configure: true
ceph_rbd_mirror_pool: "data1"

**Comment by leseb** [comment]
This might happen at some point.

**Comment by leseb** [comment]
@gauravsitlani nop, the code remains the same and does not do much.

**Comment by gauravsitlani** [comment]
@leseb thanks!
