### ISSUE TITLE
ceph monitor service do not auto start when reboot

### ISSUE THREAD

**Issue by WingkaiHo** [ceph/ceph-ansible#1392]
Use ceph-ansbile install kraken, when reboot machine, the monitor service do not auto start

**Comment by WingkaiHo** [comment]
Can I add the add task int ceph-mon/tasks/start_monitor.yml like this

- name: enable the ceph-mon.target service
  service:
    name: ceph-mon.target
    enabled: yes
  changed_when: false

**Comment by leseb** [comment]
Did you add the lines mentioned to fix this?

**Comment by WingkaiHo** [comment]
Yes.  Because by default

$ systemctl is-enabled ceph-mon.target
disable

I found ceph-mon.target do not set enable, the monitor service do not auto start when machine reboot. So it used add the lines mentioned to fix this
