### ISSUE TITLE
[kraken] ubuntu 16.04 and ceph-fs-common conflicts

### ISSUE THREAD

**Issue by vasukulkarni** [ceph/ceph-ansible#1400]
During ceph-ansible runs on kraken with xenial its failing due to conflicts https://paste.fedoraproject.org/paste/PmhPRvLcta36C0JMt0d2t15M1UNdIGYhyRLivL9gydE=/raw

Full run here:
http://qa-proxy.ceph.com/teuthology/teuthology-2017-03-28_05:15:09-ceph-ansible-kraken-distro-basic-vps/955256/teuthology.log

**Comment by vasukulkarni** [comment]
I think this is due to ceph-common that ships with xenial by default which is at 10.2.6 and probably we will have to uninstall any ceph-packages from ubuntu for it to proceed?

**Comment by leseb** [comment]
Are you trying to deploy Kraken?

**Comment by leseb** [comment]
We are not shipping Kraken yet, hopefully, soon. We need to work on the CI first.

**Comment by leseb** [comment]
This is actually easy to fix, just remove `ceph-fs-common` from the package list here: https://github.com/ceph/ceph-ansible/blob/master/group_vars/all.yml.sample#L82

Don't forget to uncomment the line for the variable `debian_ceph_packages`
