### ISSUE TITLE
Provisioning fails to find 'restart-mon.yml'

### ISSUE THREAD

**Issue by shaycohen** [ceph/ceph-ansible#1413]
RUNNING HANDLER [ceph.ceph-common : restart ceph mons] *************************
fatal: [mon2]: FAILED! => {"failed": true, "reason": "ERROR! the file_name '/home/shay/vagrant/ceph-ansible/restart-mon.yml' does not exist, or is not readable"}

Modified locally the paths under "roles/ceph-common/handlers/main.yml" to "./roles/ceph-common/handlers/" instead of "./"

**Comment by leseb** [comment]
Closed by https://github.com/ceph/ceph-ansible/pull/1412
