### ISSUE TITLE
Bluestore override values not used when creating disks 

### ISSUE THREAD

**Issue by piwi3910** [ceph/ceph-ansible#1423]
when specifying overrides needed for bluestore not all of them are used when creating disks.

bluestore block size: 5368709120 works correctly and a 5GB partition is created
and when not specifying the whole disk is used -> correct
however:
bluestore block db size: 34359738368
bluestore block wal size: 1073741824
or whatever value is being used is not used when setting up the disk and always a 100MB partition is created even if we set the db and wall size bigger

```
#         Start          End    Size  Type            Name
 1         2048       206847    100M  unknown         ceph data
 2       206848   1756889054  837.7G  unknown         ceph block
```

**Comment by leseb** [comment]
Hum could this be a ceph-disk bug?
This is the command we use to prepare a device:

`ceph-disk prepare --bluestore --cluster <cluster name> <device>`

Can you try manually? And add `-v` to the prepare command.
Normally ceph-disk is doing a lookup of the ceph.conf to find these options.

Thanks!

**Comment by guits** [comment]
Closed due to inactivity, feel free to re-open if needed. Thanks!
