### ISSUE TITLE
ceph-ansible hangs when the command 'ceph --cluster ceph osd pool stats rbd' hangs

### ISSUE THREAD

**Issue by vasukulkarni** [ceph/ceph-ansible#1440]
When the above command hangs for any reason, cpeh-ansible is stuck waiting forever, Instead it should timeout and throw the fatal warning.

**Comment by vasukulkarni** [comment]
Assigning to Andrew since he knows the background.

**Comment by vasukulkarni** [comment]
the last output i see that hangs forever is

**Comment by alfredodeza** [comment]
We should identify all the places where this could timeout (a lot of the Ceph CLI commands can hang) and do the same

**Comment by andrewschoen** [comment]
It seems to me we have a couple options to add a timeout to our ceph commands.

1) use an approach with ``until`` like we do here https://github.com/ceph/ceph-ansible/blob/master/infrastructure-playbooks/rolling_update.yml#L146-L149

2) use ``async`` and ``poll`` http://docs.ansible.com/ansible/playbooks_async.html

Does anybody have a preference? Also, what's a good timeout default for these ceph commands?

**Comment by andrewschoen** [comment]
For context, this is the upstream ceph bug related to the ceph command making ceph-ansible hang. http://tracker.ceph.com/issues/19600

**Comment by alfredodeza** [comment]
None of these commands should take longer than 5 minutes (exaggerating here).  I don't feel authoritative enough to pursue a blanket solution like that one. @dmick do you know of anything or any environment that could take longer than 5 minutes?

**Comment by leseb** [comment]
Although `until` is more Ansible and possibly more elegant too, the `timeout` command is part of `coreutils` on RedHat/Debian based systems so widely available.
That could be a simpler solution.
