### ISSUE TITLE
ceph-mon task currently chmods all the files of /etc/ceph/*.keyring

### ISSUE THREAD

**Issue by wind0204** [ceph/ceph-ansible#1445]
I mean, do ceph-mons really have to chmod all the files of /etc/ceph/*.keyring?

13:37:55 Nicho1as | Hi, ceph-ansible playbook's ceph-mon role chmods all the files of /etc/ceph/*.keyring but I have to keep /etc/ceph/ceph.client.libvirt.keyring as 0640 not 0600... what would you guys suggest as a preferable solution? I mean do ceph-mons really have to chmod all the files of /etc/ceph/*.keyring?
13:38:29          | it's written in ceph-ansible/roles/ceph-mon/tasks/ceph_keys.yml
13:38:56          | leseb: I'd like to hear your opinion..
16:27:27          | for the time being I just put a task right after that which chmods the file I need to keep 0640..
16:34:29      --> | *****04 (~*****04@s******.******.***) has joined #ceph-ansible
16:44:40      --> | ******ne-***** (~******ne@1**.***.**.**) has joined #ceph-ansible
16:55:54    leseb | Nicho1as can you open an issue for this please? on github :) we will address that
16:56:27 Nicho1as | Sure, I will after dinner
16:57:13          | Oh, I could do it right now ... just copying the irc log :-q hehe

**Comment by guits** [comment]
PR #1471 was closed due to inactivity,  closing this issue as well.
Feel free to re-open.
