### ISSUE TITLE
Can ansible blow up if monitor_interface is set but that interface doesn't exist on a host?

### ISSUE THREAD

**Issue by ashak** [ceph/ceph-ansible#1462]
I've been switching some hosts between Debian and Centos and back for some testing.

Whenever I switch, I always forget that I need to change monitor_interface from eth0 to em1 and back again.

The ansible run breaks in a way that doesn't make it obvious what the problem is. I get as far as the monitors being started and then it waits for ceph.client.admin,keyring to exist, but it never does because my monitors never achieve quorum as they don't know how to find each other. If I look at ceph.conf it contains:
mon host = ,,

Which I realise is why they can't find each other, I looked at the template, which made me search for monitor_interface in group_vars and then I realise i've forgotten to update it again.

I'm sure if I do this enough times I will eventually remember, but it would be nice if it just told me :)

**Comment by leseb** [comment]
You can assign variable per host so in your inventory file you can do:

```
[mons]
mon0 monitor_interface=eth0
mon1 monitor_interface=eth1
mon3 monitor_interface=em1
```
