### ISSUE TITLE
bluestore config requires two redundant (?) options

### ISSUE THREAD

**Issue by batrick** [ceph/ceph-ansible#1475]
So I was trying out bluestore with batrick/ceph-linode which had a few configuration problems I found confusing. I tried enabling the bluestore var:

https://github.com/ceph/ceph-ansible/blob/5192e3cd6de592b8d1aced6b0c377ef547742386/group_vars/osds.yml.sample#L147

but apparently you also need to set:

https://github.com/ceph/ceph-ansible/blob/5192e3cd6de592b8d1aced6b0c377ef547742386/group_vars/all.yml.sample#L275

to "bluestore". It would be nice if setting it in one place worked.

Also, journal_collocation needs to be unset to use bluestore which I find unnecessarily restrictive since journal_collocation is automatic (?) with bluestore. Is it really necessary to unset that?

Finally, after setting up a cluster I found that ceph-ansible choked on activating the OSDs. I had to do the following to get it running:

````
ansible -m shell -a 'printf "[global]\nenable experimental unrecoverable data corrupting features = bluestore\n" >> /etc/ceph/ceph.conf' osds
ansible -m shell -a 'ceph-disk activate /dev/sdc1' osds
````

**Comment by bengland2** [comment]
+1 on Patrick's comment.  It would be great to have option to use **raw_multi_journal** with **bluestore**, putting the WAL on the SSD instead.    **raw_multi_journal** (whether you use SSD acceleration of HDDs) and **osd_auto_discovery** (whether you specify devices) could be independent of data format (whether you use bluestore or filestore).

**Comment by bengland2** [comment]
to get it to work just now, I had to do this in group_vars/osds:

osd_objectstore: bluestore
bluestore: true
journal_collocation: false
raw_multi_journal: false

But it did bring up the OSDs without anything extra from me.  Now to get Ceph to use the SSD as the WAL.

**Comment by leseb** [comment]
@bengland2 yeah, it's a known limitation we are planning on fixing soon. Soon you will be able to specify a drive for DB and WAL.

**Comment by leseb** [comment]
Oh and yes, with the last RC no need to set experimental flags.
And yes, `osd_objectstore` and  `bluestore` are definitely redundant.

**Comment by leseb** [comment]
Actually there is an easy fix for the redundancy thing.

**Comment by leseb** [comment]
@bengland2 I don't think these 2 options are needed:

```
journal_collocation: false
raw_multi_journal: false
```
