### ISSUE TITLE
ceph-docker-common vars not added to group_vars/all.yml

### ISSUE THREAD

**Issue by andrewschoen** [ceph/ceph-ansible#1493]
When you run ``bash generate_group_vars_sample.sh`` the contents of ``roles/ceph-docker-common/defaults/main.yml`` should be added to ``group_vars/all.yml.sample``.

I attempted a quick fix, but my approach overwrote all of ``group_vars/all.yml.sample`` with the values from ``ceph-docker-common``. The correct thing I think should be to have ``group_vars/all.yml.sample`` include config options from both ``ceph-docker-common`` and ``ceph-common``.

**Comment by leseb** [comment]
what about https://github.com/ceph/ceph-ansible/blob/master/group_vars/docker-commons.yml.sample?

**Comment by andrewschoen** [comment]
@leseb ``docker-commons.yml`` does not match up with any of our groups, so it won't be used by ansible. This is why ``ceph-common`` must put it's vars in ``all.yml``.

See: http://docs.ansible.com/ansible/intro_inventory.html#splitting-out-host-and-group-specific-data

**Comment by leseb** [comment]
Fixed.
