### ISSUE TITLE
purge-cluster.yml fails due to bug in ansible service module?

### ISSUE THREAD

**Issue by bengland2** [ceph/ceph-ansible#1520]
infrastructure-playbooks/purge-cluster.yml task below fails when Ceph is not installed:

      - name: stop ceph mdss with systemd
        service:
          name: ceph-mds@{{ ansible_hostname }}
          state: stopped
          enabled: no
        when: ansible_service_mgr == 'systemd'

The error is:

    TASK [stop ceph mdss with systemd] *********************************************
    fatal: [ip-172-31-27-179]: FAILED! => {"changed": false, "failed": true, "msg":  
     "Could not find the requested service ceph-mds@ip-172-31-27-179: cannot disable" }

versions:
ansible-2.2.1.0-1.el7.noarch
ceph-ansible-2.1.9-1.el7scon.noarch

To me this seems like a bug in the Ansible service module - if the service cannot be found, it should be safe to assume that the service is not running, right?    So in the Ansible tradition of idempotency, the service module should return success.  The service *is* disabled in the sense that it will not start when the system boots, since it is not present on the system.  This allows for purge-cluster to run successfully on a system where ceph is not present.  Do people agree with this?

But reality rears its ugly head -- if we can't get ansible to fix this (and they won't right away), then we have to start testing to see if the service is installed and add a when clause to above task to check before asking the service module to disable it, right?  :-(  

Why do I keep worrying about purge-cluster.yml?  After all, ansible playbooks are supposed to be idempotent.  I'm thinking about day-2 operations.  What if you want to shrink a cluster or change the nodes that a cluster lives on?  Then you'll need a playbook similar to this one right?  Also for testing purposes it's nice to be able to strip ceph off a cluster before running ceph-ansible, without redeploying the entire set of nodes.   

Perhaps with containerized Ceph services this problem goes away, trying that now...

**Comment by leseb** [comment]
Why would run `purge-cluster.yml` on a node where Ceph is not installed?

**Comment by bengland2** [comment]
as part of another script that puts ceph onto a cluster  and wants to make sure that all disks are wiped and any leftover ceph pieces are gone.  For example, previous ceph cluster may not have had an MDS.

**Comment by guits** [comment]
My thought is that even if what you describe here was a real ansible issue, I'm not sure we should manage it at the ceph-ansible level.

**Comment by guits** [comment]
This playbook is not supposed to fit this usecase.
Closing this issue
