### ISSUE TITLE
'test if rbd exists' is hanging

### ISSUE THREAD

**Issue by andrewschoen** [ceph/ceph-ansible#1547]
The following task is hanging and keeping CI slaves locked up for days in some instances:

https://github.com/ceph/ceph-ansible/blame/master/roles/ceph-mon/tasks/ceph_keys.yml#L61

See: https://jenkins.ceph.com/job/ceph-ansible-prs-kraken-ansible2.2-update_cluster/249/console

or: https://jenkins.ceph.com/job/ceph-ansible-prs-kraken-ansible2.2-update_cluster/288/console

**Comment by leseb** [comment]
To clarify, the task doesn't hang, it passes.
However the task `check rbd pool usage` is failing because: 

`The conditional check 'rbd_pool_exist.rc == 0' failed. The error was: error while evaluating conditional (rbd_pool_exist.rc == 0): 'dict object' has no attribute 'rc'`

**Comment by andrewschoen** [comment]
@leseb That's not what I observed. If you look further up the log you'll see this, specifically the ``MODULE FAILURE`` and ``Aborted by Andrew Schoen`` line:

```
TASK [ceph-mon : test if rbd exists] *******************************************
task path: /home/jenkins-build/build/workspace/ceph-ansible-prs-kraken-ansible2.2-update_cluster/roles/ceph-mon/tasks/ceph_keys.yml:59
ok: [mon0] => {
    "changed": false, 
    "failed": false, 
    "failed_when_result": false, 
    "module_stderr": "", 
    "module_stdout": ""
}

MSG:

MODULE FAILURE

TASK [ceph-mon : include] ******************************************************
task path: /home/jenkins-build/build/workspace/ceph-ansible-prs-kraken-ansible2.2-update_cluster/roles/ceph-mon/tasks/ceph_keys.yml:65
Build was aborted
Aborted by Andrew Schoen
[PostBuildScript] - Execution post build scripts.
```

When checking jenkins I noticed some of the PR jobs had went "red", meaning they had been running for quite some time. Most of them over 6 hours. However, when I aborted the job the task below it ran anyway. Perhaps because of the ``failed_when: false`` on the task.

**Comment by leseb** [comment]
Ok, my bad.

**Comment by andrewschoen** [comment]
@leseb here's another example of the CI hanging on that task, I'll leave the job running so you can inspect it if you'd like.

https://jenkins.ceph.com/job/ceph-ansible-prs-kraken-ansible2.2-update_cluster/339/console

**Comment by bengland2** [comment]
I just tried installing Luminous upstream stable build on RHEL7.3, and saw the same task hang.  The rbd pool is created, but when I do the command "ceph osd pool stats rbd" it hangs.  Clearly it shouldn't do this, but if you just want to see whether the rbd pool was created, we could do "ceph osd pool ls | grep rbd", for example.

**Comment by leseb** [comment]
@andrewschoen we just do a `ceph --cluster {{ cluster }} osd pool get rbd size`, yes we could go with the `ls | grep` approach, however, this means using the `shell` module.

**Comment by DDamianEam** [comment]
Hello,
I would like to confirm the issue:
Ceph-ansible: branch=Master
Ceph: Jewel
OS: CentOS 7 (minimal, 3.10.0-693.el7.x86_64)
Ansible: 2.3.1 (on LUbuntu 16.04 LTS)
repo: epel-release + centos-release-ceph-jewel
