### ISSUE TITLE
remove *_containerized_deployment variables?

### ISSUE THREAD

**Issue by leseb** [ceph/ceph-ansible#1556]
These variables are causing issues while using infrastructure playbooks, especially when we use `delegate_to`. Variables will appear undefined.

Originally I made different variables so each daemon can be treated separately. This offers us the ability to mix containerized and non-containerized deployment for certain daemon. How valid is this scenario? Is it realistic? I'll tend to think that if people want to go containers then they should go all out.

Now, I wonder if we should have a single common variable to just containerize all the daemons and that's all. That will greatly simplify the code. Something like `containerized_deployment` could be used in `ceph-docker-common`, then added into `group_vars.all.yml.sample`.

@GregMeno @ktdreyer @guits @andrewschoen @alfredodeza thoughts?

**Comment by guits** [comment]
I agree with @leseb. I'm not sure but I even think these variables might cause some confusion. I don't think the use case of having a mix of containerized and non-containerized daemons is really relevant but maybe @GregMeno @ktdreyer @andrewschoen @alfredodeza have a different opinion on that.
Also, removing these variables might help to refactor the code a bit more.

**Comment by andrewschoen** [comment]
I think this is a good idea, ``containerized_deployment`` in ``ceph-docker-common`` would work as well. Going this route we don't close the possibility of doing mixed deployments either. The user could set ``containerized_deployment: true`` in either group_vars, host_vars or their inventory to control which daemons (or individual hosts) use containers.

**Comment by guits** [comment]
see #1469

**Comment by guits** [comment]
done in #1469
