### ISSUE TITLE
Duplicate OSD sections in ceph.conf

### ISSUE THREAD

**Issue by gaudenz** [ceph/ceph-ansible#1571]
If the ceph-osd role is rerun one ends up with duplicate sections for each osd in ceph.conf.

AFAICS this is what happens:
1. ceph-common is run as a dependency of ceph-osd and writes a ceph.conf file which already includes the osd sections as the /etc/ceph/ceph.d/osd.conf file already exists from the previous run.
2. ceph-osd copies this file into /etc/ceph/ceph.d/ceph.conf
3. ceph-osd again assebles the ceph.conf file which now contains duplicate sections.

I guess the correct solution is to remove step two from ceph-osd and to rely on the fact that ceph-osd has a role dependency on ceph-common and thus step 1 is always run.

**Comment by leseb** [comment]
Hum we don't really test this functionality in the CI since it's a very limited use case.
Can you show me the options you enabled and the result?

Thanks!

**Comment by gaudenz** [comment]
I don't understand your question. What do you mean by options? Ansible variables? This is a bit difficult as we have a quite complex inventory and I'm using the individual roles but I'm quite sure this is not relevant. Just run any playbook which includes the ceph-osd role twice and you will see what happens. I'm quite sure this is not dependent on any variables.

What do you mean by limited use case? I don't think rerunning the same playbook (maybe because you changed something or added some OSDs or just to ensure the settings are still correct) is something unusual. IMO this should be supported and result in the same configuration as for the first run (when no variables changed).

Or to rephrase what I wrote above in my analysis, think about this: Before the second run, /etc/ceph/ceph.d/osd.conf already exists (it was created on the first run and not removed). Then the assemble module used in ceph-common integrates it's content into /etc/ceph/ceph.conf. So the OSD sections are now already in ceph.conf before the ceph-osd role runs it's tasks. Then  ceph-osd copies ceph.conf to /etc/ceph/ceph.d/ceph.conf and uses the assemble module again to add osd.conf once again to it. Voilà.

**Comment by guits** [comment]
@gaudenz I can't reproduce your issue, which branch of ceph-ansible are you running and which version of ansible ?

**Comment by guits** [comment]
@gaudenz are you still encountering this issue? any update?

**Comment by nexecook** [comment]
@guits @leseb  it is still indeed a problem, i inherited a (pretty complex) playbook using this role and from what i can tell; if `crush_location` is set to `true` and define a crush location for a host and run the playbook multiple times you should get multiple osd sections redefining the crush location. If that isn't the case i can try to come up with a minimal reproducible playbook

**Comment by leseb** [comment]
The code that was causing this is gone in stable-3.1. Do you mind giving it another try?
Thanks.
