### ISSUE TITLE
Deprecation warning: alaways_run is deprecated. Use check_mode = no instead.

### ISSUE THREAD

**Issue by zealoussnow** [ceph/ceph-ansible#1574]
When I deploy a new ceph cluster, I got the following message:

```yml
TASK [ceph-mon : collect admin and bootstrap keys] *******************************************************************************************************************************
[DEPRECATION WARNING]: always_run is deprecated. Use check_mode = no instead..
This feature will be removed in version 2.4. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
ok: [kvm-host1]
```

Shoud I remove always_run and add check_mode = no or set deprecation_warnings=False in ansible.cfg?

**Comment by leseb** [comment]
That's not an issue for now. We are keeping `always_run` for backward compatibility. Once we move to 2.4 we will use `check_mode` instead. No rush here, but if you find this annoying feel free to set deprecation_warnings=False in ansible.cfg.

**Comment by zealoussnow** [comment]
@leseb OK, Thank you
