### ISSUE TITLE
Disable the ability to deploy with custom cluster names

### ISSUE THREAD

**Issue by alfredodeza** [ceph/ceph-ansible#1593]
In the June 6th CDM we agreed to start a transition for no longer supporting custom cluster names.

This is a difficult transition from Ceph itself (the cluster name gets parsed everywhere), so the initial step is for deployment tools to disallow that customization.

https://bugzilla.redhat.com/show_bug.cgi?id=1459861

**Comment by guits** [comment]
Closed due to inactivity, feel free to re-open if needed. Thanks!
