### ISSUE TITLE
re-run site.yml after replace disk

### ISSUE THREAD

**Issue by OrFriedmann** [ceph/ceph-ansible#1605]
After replace osd because of failed disk, and delete the journal partition , re-run of the site.yml creates a new partition in the ssd at the end of the ssd and not in place of where the journal was before(the playbook not creates the new partition where it was before deleted).

Any ideas?

Thank you

**Comment by leseb** [comment]
This is normal, ceph-disk will look at the last offset available. It will not search for the exact space in between. Actually, it's not ceph-disk it's sgdisk that is doing this.

Basically if you have:
A - B - C as journal partitions. The OSD using the journal partition B dies, next time you rebootstrap that OSD a new D partition will be created for its journal.
