### ISSUE TITLE
possibility of stale /var/run/ceph check during initial deployment 

### ISSUE THREAD

**Issue by vasukulkarni** [ceph/ceph-ansible#1608]
Andrew pointed out me a code that should not be run during initial deployment

https://github.com/ceph/ceph-ansible/blob/stable-2.2/roles/ceph-common/tasks/checks/check_socket.yml#L4

I mostly had a stale /var/run/ceph left and it caused the above condition to pass, It would be nice to actually run a tell command using admin socket or add some more checks to avoid stale asok checks.

**Comment by leseb** [comment]
Hum so you're suggestion is:

* look for any socket
* if find test it
* if fails then do no restart
* if works trigger a restart

?

**Comment by vasukulkarni** [comment]
@leseb  that is correct, it could also test one of the ceph binaries in addition to asok + test the asok for whether to restart or not

**Comment by leseb** [comment]
This could be integrated in a follow up of https://github.com/ceph/ceph-ansible/pull/1727

**Comment by guits** [comment]
Closed due to inactivity, feel free to re-open if needed. Thanks!
