### ISSUE TITLE
Can ceph-ansible set up the container host with container files in a directory dedicated to the container and not native to the host?

### ISSUE THREAD

**Issue by fultonj** [ceph/ceph-ansible#1618]
An example of $subject is config files. TripleO deploys a containerized OpenStack by generating the configuration files needed by a container in `/var/lib/config-data/$svc/` and then bind mounting that volume to `/etc/$svc` when it starts the container. For [example](https://github.com/openstack/tripleo-heat-templates/blob/af3828437e4ec92a738023afd29f12225161866e/docker/services/nova-compute.yaml#L100), the nova-compute service's `/etc/nova` exists as `/etc/nova` in the container but on the container host it's `/var/lib/config-data/nova_libvirt/etc/nova/`. 

ceph-ansible is different in that it generates `/etc/ceph` on both the container host and the container. Is it worth following the same pattern as TripleO in ceph-ansible? 

At the moment TripleO containers and ceph-ansible containers coexist on the same host without issues, but following the same [architecture](https://docs.openstack.org/developer/tripleo-docs/containers_deployment/architecture.html) would make a converged system more consistent.

**Comment by fultonj** [comment]
FYI: Some recent discussion on this in https://review.openstack.org/#/c/471527/7/docker/services/manila-share.yaml@97 in case you wish to comment.

**Comment by leseb** [comment]
This was closed by https://github.com/ceph/ceph-ansible/pull/1624
