### ISSUE TITLE
Support for a CRUSH location string in config file

### ISSUE THREAD

**Issue by mwheckmann** [ceph/ceph-ansible#162]
It would be great if we could support setting a custom CRUSH location string in the config file for larger non-standard setups.

Just a placeholder for future work.

**Comment by leseb** [comment]
What do you mean? Something like:

[osd.X]
osd crush location = "root=location"

**Comment by mwheckmann** [comment]
Yes, exactly. An example would be: 

osd crush location = "root=default pod=b1 host={{ ansible_hostname }}"

Ideally, the right hand side of the '=' would be in a configurable variable.

Default would be "root=default host={{ ansible_hostname }}" (this is the Ceph default).

**Comment by leseb** [comment]
Ok I see, since it's an OSD section, it might be really tricky.
We don't support OSD section at the moment, and will be difficult to support it.
I've been thinking of using the assemble module for that. I'll have a look again.

**Comment by leseb** [comment]
Ok I have a really tricky prototype for you. I'm gonna push a branch soon.
