### ISSUE TITLE
Needs playbook to do a rolling migration from FileStore to BlueStore

### ISSUE THREAD

**Issue by fghaas** [ceph/ceph-ansible#1623]
It would be great if this repo had a playbook to automate migration, post-Luminous, from FileStore to BlueStore. Here's what that would entail:

Such a playbook would
- touch OSDs only; there is nothing that needs to change about other components,
- run with `serial: 1` by default,
- stop an OSD,
- zap an OSD store (`ceph-disk zap`), and then reapply the `ceph-osd` role after setting `bluestore: true` (and `osd_objectstore: bluestore`, unless #1475 is addressed/fixed)
- restart the OSD,
- wait for all PGs to go clean again (similar to the way `rolling_update.yml` already does — but the BlueStore conversion wouldn't be able to do this as one of the `post_tasks`),
- only then proceed to the next OSD.

It's obvious that this process would likely run for days or weeks in large clusters, which is why it's all the more helpful to be fully automated.

Optionally, it should probably be configurable to also mark the OSD `out` and wait for PGs to go clean *before* zapping, so that full data redundancy is always maintained (at the expense of much longer processing times).

**Comment by leseb** [comment]
http://docs.ceph.com/docs/master/rados/operations/bluestore-migration/

**Comment by mcv21** [comment]
We have a shell script that we use to do this - it does OSDs a machine at a time, and waits for the cluster to be `HEALTH_OK` again before moving on to the next host...

**Comment by guits** [comment]
Closed due to inactivity, feel free to re-open if needed. Thanks!
