### ISSUE TITLE
missing mgr_vms variable in vagrant_variables.yml.openstack?

### ISSUE THREAD

**Issue by hwasp** [ceph/ceph-ansible#1628]
Hello,

I am trying to run ceph-ansible in an OpenStack environment but after following the steps in the Readme I got an error:

Vagrantfile:183:in `block in <top (required)>': undefined method `-' for nil:NilClass (NoMethodError)

I noticed that the loop in line 183 refers to a variable that is not defined in vagrant_variables.yml (originally copied from vagrant_variables.yml.openstack): mgr_vms

If I add mgr_vms = 1 for example I get rid of the error (and I get another one related to the vagrant_box, but don't know if this is related)

I just wanted to know if  mgr_vms should be present or not.

PD: Also I noticed that the  group_vars/all.docker.yml.sample (as stated in the Readme) is not in the repo, so I used group_vars/all.yml.samble instead)

Thanks!

**Comment by leseb** [comment]
Yes  `mgr_vms` could be part of `vagrant_variables.yml.openstack`, feel free to send a PR for this.
You need to use  `group_vars/all.yml.samble` for Docker deployments too.

Thanks!
