### ISSUE TITLE
Infrastructure playbooks break all assumptions on variable precedence

### ISSUE THREAD

**Issue by fghaas** [ceph/ceph-ansible#1634]
[Variable precedence in Ansible 2.x is clearly defined and documented](http://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable). The `take-over-existing-cluster.yml` playbooks does not play by these rules.

In Ansible 2.x, role defaults always have the very lowest priority. Group variables defined in `group_vars` files relative to the inventory override them, and are in turn overridden by host variables defined in `host_vars` files relative to the inventory. All of the above are overridden by host variables defined in `group_vars` and `host_vars` files relative to the playbook directory. And finally, all of *that* is overridden by any variables defined directly in the playbooks. It also allows you to keep sensitive variables in a [vault](http://docs.ansible.com/ansible/playbooks_vault.html), as explained as a [best practice](http://docs.ansible.com/ansible/playbooks_best_practices.html#variables-and-vaults) in the Ansible documentation. 

That means that it's be quite common in a default Ansible configuration to keep the inventory in `/etc/ansible/hosts`, and group and host variables in `/etc/ansible/group_vars` and (if necessary) `/etc/ansible/host_vars`. This also enables users to keep their local `ceph-ansible` checkout clean, and keep the `ceph-ansible` _configuration_ in a separate repo.

However, **all these assumptions completely break down** in the playbooks in the `infrastructure-playbooks` directory. 

As an example, look at `take-over-existing-cluster.yml`, specifically the following lines:

```yaml
- hosts: mons
  become: True
  vars_files:
    - roles/ceph-common/defaults/main.yml
    - group_vars/all.yml
  roles:
    - ceph-fetch-keys
```

and

```yaml
- hosts: all
  become: true

  tasks:
    - include_vars: roles/ceph-common/defaults/main.yml
    - include_vars: group_vars/all.yml
```

Here, **role defaults** are suddenly being promoted to playbook variables, which override any inventory variables at that time, and then _those_ are overridden with a `group_vars` file — but only one, which is completely nonsensical. What if I want to define some group variables for my `mons` group? What if I need to override `monitor_interface` for just one of my mons?

There are several approaches to tackle this that I can think of, but the following appears to me like the most promising:

- Create a role named `ceph-defaults`.
- Have it *only* include a `defaults/main.yml` file containing all the defaults. No tasks, no handlers, no files, no templates.
- Never use this role directly.
- Have `ceph-common` depend on `ceph-defaults`, removing all of `ceph-common`'s own defaults.
- Have `ceph-fetch-keys` depend on `ceph-defaults` as well. This removes the need for the `vars_files` declaration in `take-over-existing-cluster.yml`.
- Create another role named `ceph-config`, which also depends from `ceph-defaults`.
- Apply that role in `take-over-existing-cluster.yml`, removing the need for the `include_vars` declaration.

**Comment by fghaas** [comment]
Updated title and description to reflect that not only `take-over-existing-cluster.yml` is affected, but most playbooks in `infrastructure_playbooks` (as those all use `include_vars` in terrible ways).

**Comment by leseb** [comment]
Usually, we recommend copying the playbook from infrastructure-playbooks at the root of the Ansible repo so we can inherit from `group_vars`. Isn't this a simpler solution?

**Comment by fghaas** [comment]
Eh, what? No, copying doesn't change or fix anything. You're still including role defaults from within the playbook, which override whatever is in `group_vars`. And then you're *also* including a `group_vars` file in the playbook, which overrides `host_vars`.

**Comment by guits** [comment]
Closed due to inactivity, feel free to re-open if needed. Thanks!
