### ISSUE TITLE
take-over-existing-cluster.yml isn't actually suitable for taking over an existing cluster

### ISSUE THREAD

**Issue by fghaas** [ceph/ceph-ansible#1638]
The `take-over-existing-cluster.yml` playbook includes comments that say:

```yaml
# The procedure is as follows:
#
# 1. Install Ansible and add your monitors and osds hosts in it. For more detailed information you can read the [Ceph Ansible Wiki](https://github.com/ceph/ceph-ansible/wiki)
# 2. Set  `generate_fsid: false` in `group_vars`
# 3. Get your current cluster fsid with `ceph fsid` and set `fsid` accordingly in `group_vars`
# 4. Run the playbook called: `take-over-existing-cluster.yml` like this `ansible-playbook take-over-existing-cluster.yml`.
# 5. Eventually run Ceph Ansible to validate everything by doing: `ansible-playbook site.yml`.
```

Following this will almost certainly mean the cluster will break, or at least behave very unexpectedly. The "documentation" doesn't at all mention that `take-over-existing-cluster.yml` will completely clobber over the Ceph configuration, and not at all incorporate any of the existing cluster configuration. `ceph-deploy` at least has an `--overwrite-conf` switch; `take-over-existing-cluster.yml` badly needs an equivalent: fail when trying to deploy `ceph.conf` if one already exists with different content, unless a specific variable is set.

A much better option still would be to also have another playbook that connects to a Ceph node, reads `ceph.conf`, and then generates `ceph_conf_overrides` YAML that can then be included in `group_vars` files.

**Comment by guits** [comment]
Closed due to inactivity, feel free to re-open if needed. Thanks!
