### ISSUE TITLE
Update of ansible-galaxy roles

### ISSUE THREAD

**Issue by dmesser** [ceph/ceph-ansible#1640]
Hi,

it seems that the ansible-galaxy roles have not been updated for some time. As of today it's not possible to install luminous with ceph-ansible because the ceph-mgr role is missing in galaxy and the code available there pre-kraken.

**Comment by fghaas** [comment]
Related: #1637.

**Comment by leseb** [comment]
@dmesser Sorry about that, I'm currently fixing that. The roles are getting updated.
