### ISSUE TITLE
[RFE] Allow for customization of the cephx secret key for the MDS service

### ISSUE THREAD

**Issue by fultonj** [ceph/ceph-ansible#1642]
This request is similar to #1630 except it is for the cephx secret key for the MDS service. 

The TripleO [integration](https://specs.openstack.org/openstack/tripleo-specs/specs/pike/tripleo-ceph-ansible-integration.html) uses a pattern where OpenStack clients are configured by puppet and use a secret key that is passed to them. For example, this pattern exists for [Manilla](https://github.com/openstack/tripleo-heat-templates/blob/master/puppet/services/manila-backend-cephfs.yaml#L57-L64) and if we support being able to pass the MDS Key from [Heat](https://github.com/openstack/tripleo-heat-templates/blob/master/puppet/services/ceph-mds.yaml#L29-L33) to ceph-ansible, then the TripleO client configuration code does not need to be re-written and we are able to maintain backwards compatibility with TripleO.

**Comment by fultonj** [comment]
@gfidente @colonwq @vkmc

**Comment by colonwq** [comment]
@fultonj I think this feature is needed for RGW. Should I submit a RFE for this too?

**Comment by batrick** [comment]
See also: https://review.openstack.org/#/c/479426/

**Comment by guits** [comment]
Closed due to inactivity, feel free to re-open if needed. Thanks!
