### ISSUE TITLE
support standby mds deployment

### ISSUE THREAD

**Issue by garyyang85** [ceph/ceph-ansible#1658]
I found this "
Important
You must deploy at least one metadata server to use CephFS. There is experimental support for running multiple metadata servers. Do not run multiple active metadata servers in production. "

Because it is not recommended to  run multiple active mds,  Do we have a plan to support standby mds deployment?   Thanks.

**Comment by leseb** [comment]
Multi MDS is supported as of Luminous.

**Comment by gvfnix** [comment]
I deployed 3-node MDSs with "jewel" stable release. All MDSs are run as active, neither of them has --hot-standby key. Did I do something wrong?

*inventory.ini*  looks like this:
```[testk8s]
testk8s1 vmid=116 
testk8s2 vmid=117
testk8s3 vmid=118

[testk8s:vars]
ansible_python_interpreter = "/usr/bin/python2.7"

[clients]
[mons]
[osds]
[mdss]


[mons:children]
testk8s

[osds:children]
testk8s

[clients:children]
testk8s

[mdss:children]
testk8s
```
_group_vars/all.yml_ looks like this:
```ceph_origin: repository
ceph_repository: community
ceph_stable_release: jewel
public_network: 10.105.6.0/23
cluster_network: 10.19.10.112/29
monitor_interface: ens18
fsid: "8a5d5628-3224-45c5-ad04-cc3fe3cc0dbe"
journal_size: 1024
```
