### ISSUE TITLE
ceph_release not always correct when using custom repo

### ISSUE THREAD

**Issue by r0ss3** [ceph/ceph-ansible#1659]
I ran into this issue when using bluestore combined with custom repo:

```
TASK [ceph-osd : check if bluestore is supported by the selected ceph version] **************************************************************************************************************************************************************
task path: /home/user1/bccl-tda/roles/ceph-osd/tasks/check_mandatory_vars.yml:69
 [WARNING]: when statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: ceph_release_num.{{ ceph_release }} < ceph_release_num.luminous

fatal: [osdserver1.intern.local]: FAILED! => {
    "changed": false,
    "failed": true,
    "msg": "bluestore is not supported by the selected Ceph version, use Luminous or above."
}
```

The custom_repo I use is luminous, but when custom_repo is used, the ceph_release defaults to stable.  It would be nice if there is a way to set ceph_release when using custom repo in group_vars/all.yml.

**Comment by guits** [comment]
@r0ss3 can you provide the full playbook run log and your group_vars/* ?

**Comment by andrewschoen** [comment]
@r0ss3 can you try setting ``ceph_stable_release: luminous`` in your ``group_vars/all.yml``? I think setting that will then make ``ceph_release`` what you'd expect it to be.

**Comment by r0ss3** [comment]
That is correct, I added ceph_stable_release under the "stable" section as well as the custom repo under the "custom" section and it works as expected.
