### ISSUE TITLE
OSD prepare fails on incurrect arguments for ceph-disk

### ISSUE THREAD

**Issue by gfidente** [ceph/ceph-ansible#1665]
Recent versions (after commit 7ef908a) fail on the OSD disk prepare step with:

`ceph-disk: error: unrecognized arguments: --block.wal --block.wal-uuid 1a85662b-3580-4a86-9fc0-867e8e753c11 --block.db /dev/vdb --block.db-uuid 59f48fa5-364d-467d-8340-d1af4395eb64 /dev/vdb`

**Comment by gfidente** [comment]
@guits should this be fixed by https://github.com/ceph/ceph-ansible/pull/1656 ?

**Comment by guits** [comment]
@gfidente yes, it should but not tested yet as I'm waiting for the new docker images to be available (still building right now).

**Comment by guits** [comment]
fixed by #1656
