### ISSUE TITLE
OSD number is not in order among hosts

### ISSUE THREAD

**Issue by zhouyuan** [ceph/ceph-ansible#1668]
Hi ceph-ansible developers,

I'm trying to use ceph-ansible to deploy my 5 nodes cluster, everything works fine except I find OSD number is not in order, here's my cluser info:

> -1 29.09576 root default
-2  5.81915     host osd2
 0  1.45479         osd.0       up  1.00000          1.00000
 2  1.45479         osd.2       up  1.00000          1.00000
 4  1.45479         osd.4       up  1.00000          1.00000
 6  1.45479         osd.6       up  1.00000          1.00000
-3  5.81915     host osd4
 1  1.45479         osd.1       up  1.00000          1.00000
 3  1.45479         osd.3       up  1.00000          1.00000
 5  1.45479         osd.5       up  1.00000          1.00000
 7  1.45479         osd.7       up  1.00000          1.00000
-4  5.81915     host osd1
 8  1.45479         osd.8       up  1.00000          1.00000
12  1.45479         osd.12      up  1.00000          1.00000
15  1.45479         osd.15      up  1.00000          1.00000
19  1.45479         osd.19      up  1.00000          1.00000
-5  5.81915     host osd3
10  1.45479         osd.10      up  1.00000          1.00000
13  1.45479         osd.13      up  1.00000          1.00000
16  1.45479         osd.16      up  1.00000          1.00000
18  1.45479         osd.18      up  1.00000          1.00000
-6  5.81915     host osd5
 9  1.45479         osd.9       up  1.00000          1.00000
11  1.45479         osd.11      up  1.00000          1.00000
14  1.45479         osd.14      up  1.00000          1.00000
17  1.45479         osd.17      up  1.00000          1.00000

I'm expecting some ordered deploy, like osd{0..3} are on host osd1, and osd{4..7} are on host osd2, etc.,

This is my first time to use this tool, is that doable via some special config?

Thanks, -yuan

**Comment by keepwatch** [comment]
Did you follow the [FAQ directions](https://github.com/ceph/ceph-ansible#faq) and use `serial`? 

> Simply add `serial: 1` after the `osd` section `- hosts: osds` in your `site.yml` file.

**Comment by guits** [comment]
I'm not sure you want to serialize the deployment of your OSDs. Imagine the time it would consume for a cluster with a large number of OSD. Actually, I don't see where is the issue here, IMO, in a cloud mindset, you shouldn't care about where reside your osd (but maybe I'm missing something?)

**Comment by zhouyuan** [comment]
@keepwatch Thanks a lot! I missed that before.
@guits I see your point and agreed here. My current setup was a testing env, so a fixed order can help me to do some quick debug. 

thanks, -yuan
