### ISSUE TITLE
ceph_release_num.ceph_release when clause causing warnings

### ISSUE THREAD

**Issue by bengland2** [ceph/ceph-ansible#1669]
When I use bluestore in ceph-ansible, I see warnings about when statements.   I'm running ansible RPM ansible-2.3.1.0-1.el7.noarch .   [This article](https://stackoverflow.com/questions/42673045/ansible-when-statements-should-not-include-jinja2-templating-delimiters) is providing a hint on how to fix it.
For example:

    TASK [ceph-osd : check if bluestore is supported by the selected ceph version] ***
     [WARNING]: when statements should not include jinja2 templating delimiters
    such as {{ }} or {% %}. Found: ceph_release_num.{{ ceph_release }} <
    ceph_release_num.luminous
    skipping: [ip-172-31-38-188]

**Comment by guits** [comment]
related BZ : 
https://bugzilla.redhat.com/show_bug.cgi?id=1454688

**Comment by leseb** [comment]
Thanks Ben, closing this since it's tracked in BZ.
