### ISSUE TITLE
Support clients configuration with external Ceph clusters

### ISSUE THREAD

**Issue by gfidente** [ceph/ceph-ansible#1670]
It is important for the integration in TripleO that we allow for configuration of the clients without configuring other roles.

In this scenario the list of mons and the fsid will be given by the user as input and, together with keys:, should make it possible to configure a client without requiring access to the mons role.

**Comment by leseb** [comment]
Fixed in https://github.com/ceph/ceph-ansible/commit/0032640b7e6b0ab08e3eb19be1bd1751c548a151

**Comment by ktdreyer** [comment]
That commit is not yet in master

**Comment by GregMeno** [comment]
@leseb Would you please tell me if you plan to include this in the 2.3 release?

**Comment by leseb** [comment]
This should be fixed by #1727
