### ISSUE TITLE
purge cluster: also cleanup /etc/systemd/system/ceph-osd.target

### ISSUE THREAD

**Issue by vasukulkarni** [ceph/ceph-ansible#1672]
some of the systemd files /etc/systemd/ceph* maybe left behind even after uninstall, Its better to remove them with force for proper purge-cluster.

**Comment by guits** [comment]
@vasukulkarni I tried to reproduce, after a purge-cluster i don't have this behavior. I have no systemd unit file left regarding ceph. Can you give me more context about your environment?

**Comment by vasukulkarni** [comment]
@guits check this here: http://tracker.ceph.com/issues/15333,  you can try with jewel bulid, try with some radosbench + start/restart systemd and then uninstall, It is intermittent, so the case to recreate is not very clear.

**Comment by laggeduout** [comment]
I tried to replicate this and found the below got left behind.
```
/etc/systemd/system/ceph-mon.target.wants 
/etc/systemd/system/ceph-mgr.target.wants
```
The OS used is below:

```
# cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)
```

**Comment by guits** [comment]
@vasukulkarni I think if a file is created by the package itself it should also remove it at uninstalling.
