### ISSUE TITLE
filestore support broke

### ISSUE THREAD

**Issue by bengland2** [ceph/ceph-ansible#1678]
Today Barry Marson and I were trying to install Ceph filestore with ceph-ansible and it wasn't creating OSD filesystems correctly.   We were using Ceph [Luminous from download.ceph.com](http://download.ceph.com/rpm-luminous/el7/x86_64/).  We tracked this down to the fact that we had to add the "--filestore" option to ceph-disk command used for the osd_objectstore: filestore case in [this line of code](https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-osd/tasks/scenarios/raw_multi_journal.yml#L11).  Did the default for ceph-disk change to --bluestore recently?  If so, note this probably has to change wherever ceph-disk is run (i.e. multiple scenarios) to create a filestore OSD.

**Comment by liewegas** [comment]
Yeah, ceph-disk in luminous defaults to bluestore.  In ceph-deploy we 
added a --filestore option (to complement --bluestore) to force a 
particular choice, but by default it's bluestore.  I think ceph-ansible 
should be the same (i.e., default to bluestore unless a specific backend 
is specified).

**Comment by bengland2** [comment]
Yes, that's fine with me if ceph-disk defaults to bluestore, but my only concern was that ceph-ansible should still allow you to select filestore if you request it.

**Comment by guits** [comment]
@bengland2 a PR #1676 has been submitted for that issue

**Comment by bengland2** [comment]
thank you for the awesomely quick response.

**Comment by leseb** [comment]
follow up here: https://github.com/ceph/ceph-ansible/pull/1704
