### ISSUE TITLE
When using docker, the deployment should fail if one or more of the disks in devices: can't be activated

### ISSUE THREAD

**Issue by gfidente** [ceph/ceph-ansible#1686]
I believe the expectations are that the playbook should fail if any of the disks listed in devices: can't be activated ... this happens when disks are reused for a new cluster with a different fsid

**Comment by GregMeno** [comment]
@gfidente this doesn't strike me a a bug. Consider you want to setup a Ceph cluster containing OSDs 0-9 and 3 and 7 fail for some reason. At the end of the playbook you'd still have a usable cluster albeit with 2 fewer OSDs than you had spec'd

**Comment by gfidente** [comment]
I agree this is a matter of managing user expectations and not exactly a bug but, as discussed for puppet-ceph as well (which also initially didn't exit), if the user passes a list of devices it expects that list of devices to be used and fail if it can't.

This might be different when a globbing / regexp is given.

**Comment by fultonj** [comment]
In puppet ceph it was judged to be a bug because we would be deceiving the user. They may think they have more OSDs then they do. We thought it was better to make them change what they're asking for from the system so that they know because they wrote the updated change. Perhaps a warning is a good comprise? "OK, you have a working ceph cluster but only X of Y OSDs are enabled". From there the user could rely on idempotence after they address the the environmental issue (e.g. they had run sgdisk -Z -g on the disk first). We could also only do that when osd_auto_discovery is not used.

**Comment by leseb** [comment]
I don't think this is ceph-ansible's job to fail if one of the devices doesn't turn into an OSD.
If we are given a disk with an old content there is not much we can do. If a disk is given we expect that this disk was zapped prior to run the deployment. As a best effort if we detect a wrong label for a disk we zap it to re-create label and partition tables.
I believe this validation should come from another tool, a post-deployment validation tool.

As an intermediate solution, I can add a message that shown something like:

"N devices were given and your cluster has N OSD up and in".

Show a message when N matches and a warning when they differ.

How does that sound?

**Comment by leseb** [comment]
https://github.com/ceph/ceph-ansible/pull/1714

**Comment by jprovaznik** [comment]
> If  we are given a disk with an old content there is not much we can do. If a disk is given we expect that this disk was zapped prior to run the deployment.

IMO if ceph-ansible expects the disk to be zapped (which I think is logical), then I would expect that ceph-ansible fails if this expectation is not fulfilled. So as a user I would prefer ceph-ansbile to fail in such case. I'm afraid that showing a message if OSD num doesn't match is not sufficient in openstack deployments where ceph-ansible output is not "visible-enough" to user and can be easily overlooked. Just my $.02.

**Comment by guits** [comment]
Closed due to inactivity, feel free to re-open if needed. Thanks!
