### ISSUE TITLE
ceph-fetch-keys missing dependency on ceph-common

### ISSUE THREAD

**Issue by mcv21** [ceph/ceph-ansible#1698]
Hi,

A number of the infrastructure playbooks include the ceph-fetch-keys role; this role, however, will fail (complaining about missing `cluster_uuid.stdout`) in the common case where fsid is set to `"{{ cluster_uuid.stdout }}"`; it needs to depend upon the `ceph-common` role, where that variable is set (having extracted the fsid from the running cluster via the "is ceph running already?" task).

I'll open a PR shortly with the (pretty simple) patch, but it seemed worth opening an issue separately, in case I'm missing something obvious.

Example playbook to repro:
```yaml
---
- hosts: mons
  become: True
  roles:
     - ceph-fetch-keys
```

Output from running this:
mv3@deskpro108655:~/software/ceph-ansible$ ansible-playbook --ask-vault-pass -i inventory.py infrastructure-playbooks/keysbug.yml 
Vault password: 

PLAY [mons] ********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [sto-1-1]
ok: [sto-3-1]
ok: [sto-2-1]

TASK [ceph-fetch-keys : find ceph keys] ****************************************
[DEPRECATION WARNING]: always_run is deprecated. Use check_mode = no instead..

This feature will be removed in version 2.4. Deprecation warnings can be 
disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: always_run is deprecated. Use check_mode = no instead..

This feature will be removed in version 2.4. Deprecation warnings can be 
disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: always_run is deprecated. Use check_mode = no instead..

This feature will be removed in version 2.4. Deprecation warnings can be 
disabled by setting deprecation_warnings=False in ansible.cfg.
ok: [sto-1-1]
ok: [sto-3-1]
ok: [sto-2-1]

TASK [ceph-fetch-keys : set keys permissions] **********************************
changed: [sto-1-1] => (item=/etc/ceph/ceph.client.admin.keyring)
changed: [sto-1-1] => (item=/etc/ceph/ceph.client.irods-test.keyring)
changed: [sto-1-1] => (item=/etc/ceph/ceph.client.openstack-delta2.keyring)
changed: [sto-1-1] => (item=/etc/ceph/ceph.client.openstack-delta.keyring)
changed: [sto-1-1] => (item=/etc/ceph/ceph.client.openstack-demo.keyring)
changed: [sto-1-1] => (item=/etc/ceph/ceph.client.openstack-epsilon.keyring)
changed: [sto-1-1] => (item=/etc/ceph/ceph.client.openstack.keyring)
changed: [sto-1-1] => (item=/etc/ceph/ceph.openstack.client.keyring)
changed: [sto-2-1] => (item=/etc/ceph/ceph.client.admin.keyring)
changed: [sto-2-1] => (item=/etc/ceph/ceph.client.irods-test.keyring)
changed: [sto-2-1] => (item=/etc/ceph/ceph.client.openstack-delta2.keyring)
changed: [sto-2-1] => (item=/etc/ceph/ceph.client.openstack-delta.keyring)
changed: [sto-2-1] => (item=/etc/ceph/ceph.client.openstack-demo.keyring)
changed: [sto-2-1] => (item=/etc/ceph/ceph.client.openstack-epsilon.keyring)
changed: [sto-2-1] => (item=/etc/ceph/ceph.client.openstack.keyring)
changed: [sto-2-1] => (item=/etc/ceph/ceph.openstack.client.keyring)
changed: [sto-3-1] => (item=/etc/ceph/ceph.client.admin.keyring)
changed: [sto-3-1] => (item=/etc/ceph/ceph.client.irods-test.keyring)
changed: [sto-3-1] => (item=/etc/ceph/ceph.client.openstack-delta2.keyring)
changed: [sto-3-1] => (item=/etc/ceph/ceph.client.openstack-delta.keyring)
changed: [sto-3-1] => (item=/etc/ceph/ceph.client.openstack-demo.keyring)
changed: [sto-3-1] => (item=/etc/ceph/ceph.client.openstack-epsilon.keyring)
changed: [sto-3-1] => (item=/etc/ceph/ceph.client.openstack.keyring)
changed: [sto-3-1] => (item=/etc/ceph/ceph.openstack.client.keyring)

TASK [ceph-fetch-keys : copy keys to the ansible server] ***********************
fatal: [sto-1-1]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: {{ cluster_uuid.stdout }}: 'cluster_uuid' is undefined\n\nThe error appears to have been in '/nfs/users/nfs_m/mv3/software/ceph-ansible/roles/ceph-fetch-keys/tasks/main.yml': line 17, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: copy keys to the ansible server\n  ^ here\n"}

NO MORE HOSTS LEFT *************************************************************
        to retry, use: --limit @/nfs/users/nfs_m/mv3/software/ceph-ansible/infrastructure-playbooks/keysbug.retry

PLAY RECAP *********************************************************************
sto-1-1                    : ok=3    changed=1    unreachable=0    failed=1   
sto-2-1                    : ok=3    changed=1    unreachable=0    failed=0   
sto-3-1                    : ok=3    changed=1    unreachable=0    failed=0

**Comment by guits** [comment]
Closed due to inactivity, feel free to re-open if needed. Thanks!
