### ISSUE TITLE
deploy with "containerized_deployment: true" broken on ubuntu 16.04

### ISSUE THREAD

**Issue by fxpester** [ceph/ceph-ansible#1700]
**problem description**
Deploy is ok without "containerized_deployment: true", if I add it deploy ends with error " Make sure your Ceph monitors are up and running in quorum"

in logs: **error: NSS AES final round failed**
so I guess error in keyring synchronization.

**environment**:
ubuntu 16.04
3x baremetal node deploy

all.yaml:
ceph_origin: upstream
ceph_stable: true
ceph_conf_overrides:
  client:
    rbd default features: 3
monitor_interface: ens3
public_network: $1
containerized_deployment: true

osds.yaml:
devices:
  - $2
journal_collocation: True

**Comment by guits** [comment]
@fxpester could you provide the full log?

**Comment by fxpester** [comment]
I`m still experimenting, this is same error but on stable-2.2 branch
@guits http://paste.openstack.org/show/616165/

**Comment by fxpester** [comment]
as I understand mon's keyrings should be same across all hosts, but in my case they are different - http://paste.openstack.org/show/616168/

**Comment by guits** [comment]
@fxpester the log you provided is truncated

**Comment by fxpester** [comment]
@guits this is full log https://pastebin.com/8w4KWTVw

**Comment by guits** [comment]
@fxpester could you provide also your host inventory file content?

**Comment by fxpester** [comment]
default site.yml

hosts:
```
cat /etc/ansible/hosts
[mons]
1.1.1.7
1.1.1.6
1.1.1.5
[osds]
1.1.1.5
1.1.1.6
1.1.1.7
[rgws]
1.1.1.5
1.1.1.6
1.1.1.7
[clients]
1.1.1.5
1.1.1.7
1.1.1.6
```

**Comment by guits** [comment]
@fxpester I think you are running the playbook with site.yml instead of site-docker.yml

**Comment by fxpester** [comment]
thx! we luck documentation about this moment

**Comment by guits** [comment]
If you look well, for the monitors deployment part of the log :
```
TASK [ceph-mon : pull ceph/daemon image] ************************************************************************************************************************************************************
ok: [1.1.1.6]
ok: [1.1.1.5]
ok: [1.1.1.7]
```

with containerized deployment you should have monitors deployed in a serialized way.

**Comment by guits** [comment]
ok, closing issue.
feel free to reopen if needed.
