### ISSUE TITLE
ansible ssh access broken since vagrant 1.7

### ISSUE THREAD

**Issue by cultcom** [ceph/ceph-ansible#172]
As far as I could figure out vagrant changed it's default behaviour since release 1.7.0 and replaces the insecure ssh_key with an individual key for each host.

Thus the deployment of the configured ansible playbook is run with the private_key of the last deployed host (osd2) and fails to connect to all the other hosts.

see here as well: https://github.com/mitchellh/vagrant/issues/5048

**Comment by leseb** [comment]
Arf I'm still using vagrant 1.5.1 so I didn't notice.
