### ISSUE TITLE
Ability to manage config key

### ISSUE THREAD

**Issue by Fbrachere** [ceph/ceph-ansible#1722]
ceph-mgr uses [config-key](http://docs.ceph.com/docs/master/man/8/ceph/#config-key) to store parameters for plugins like [zabbix](http://docs.ceph.com/docs/master/mgr/zabbix/#configuration) or [dashboard](http://docs.ceph.com/docs/master/mgr/dashboard/#configuration).
It would be nice if ceph-ansible could update those parameters.

**Comment by leseb** [comment]
Correct, this shouldn't be too difficult to do, however, it's not our top priority right now.
Thanks!

**Comment by Fbrachere** [comment]
I would like implement this feature.
I already did the modules part (PR  #2053).
What is the best way to do this ?
* Let the user specify a key/value couple without restriction 
or
* have variable for each modules like dashboard_server_port=172.0.0.1 and manage the config key for the user ?

**Comment by leseb** [comment]
I think having a variable dict to store k/v is a viable approach. Then we have a task to apply the changed.
Looking forward to seeing your PR :).

Thanks!

**Comment by guits** [comment]
Closed due to inactivity, feel free to re-open if needed. Thanks!
