### ISSUE TITLE
"vagrant provision" errors out with "The device pointed by OSD_DEVICE (/dev/sdc) doesn't exist !""

### ISSUE THREAD

**Issue by dgedia** [ceph/ceph-ansible#1728]
```
failed: [osd0] (item=[u'/dev/sdc', {'_ansible_parsed': True, u'cmd': u"lsblk -o PARTLABEL /dev/sdc | grep -sq 'ceph'", u'end': u'2017-07-28 22:30:42.199039', '_ansible_no_log': False, u'stdout': u'', '_ansible_item_result': True, u'rc': 1, 'item': u'/dev/sdc', u'delta': u'0:00:00.004360', u'stderr': u'lsblk: /dev/sdc: not a block device', u'changed': True, 'invocation': {'module_name': u'command', u'module_args': {u'warn': True, u'executable': None, u'_uses_shell': True, u'_raw_params': u"lsblk -o PARTLABEL /dev/sdc | grep -sq 'ceph'", u'removes': None, u'creates': None, u'chdir': None}}, 'stdout_lines': [], 'failed_when_result': False, u'start': u'2017-07-28 22:30:42.194679', u'warnings': [], 'failed': False}]) => {
    "changed": true,
    "cmd": "docker run --net=host --pid=host --privileged=true --name=\"ceph-osd-prepare-ceph-mon1-devdevsdc\" -v /etc/ceph:/etc/ceph -v /var/lib/ceph/:/var/lib/ceph/ -v /dev:/dev -v /etc/localtime:/etc/localtime:ro -e \"OSD_DEVICE=/dev/sdc\" -e \"OSD_JOURNAL_UUID=$(python -c \"import uuid; print uuid.uuid5(uuid.NAMESPACE_DNS, 'cd0a3c8721ac05fdb3b30cf35950f92f/dev/sdc')\")\" -e CEPH_DAEMON=OSD_CEPH_DISK_PREPARE -e CLUSTER=ceph -e OSD_JOURNAL_SIZE=100 -e OSD_FORCE_ZAP=1 \"docker.io/ceph/daemon:latest\"",
    "delta": "0:00:00.389031",
    "end": "2017-07-28 22:30:44.175371",
    "failed": true,
    "invocation": {
        "module_args": {
            "_raw_params": "docker run --net=host --pid=host --privileged=true --name=\"ceph-osd-prepare-ceph-mon1-devdevsdc\" -v /etc/ceph:/etc/ceph -v /var/lib/ceph/:/var/lib/ceph/ -v /dev:/dev -v /etc/localtime:/etc/localtime:ro -e \"OSD_DEVICE=/dev/sdc\" -e \"OSD_JOURNAL_UUID=$(python -c \"import uuid; print uuid.uuid5(uuid.NAMESPACE_DNS, 'cd0a3c8721ac05fdb3b30cf35950f92f/dev/sdc')\")\" -e CEPH_DAEMON=OSD_CEPH_DISK_PREPARE -e CLUSTER=ceph -e OSD_JOURNAL_SIZE=100 -e OSD_FORCE_ZAP=1 \"docker.io/ceph/daemon:latest\"",
            "_uses_shell": true,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "warn": true
        },
        "module_name": "command"
    },
    "item": [
        "/dev/sdc",
        {
            "_ansible_item_result": true,
            "_ansible_no_log": false,
            "_ansible_parsed": true,
            "changed": true,
            "cmd": "lsblk -o PARTLABEL /dev/sdc | grep -sq 'ceph'",
            "delta": "0:00:00.004360",
            "end": "2017-07-28 22:30:42.199039",
            "failed": false,
            "failed_when_result": false,
            "invocation": {
                "module_args": {
                    "_raw_params": "lsblk -o PARTLABEL /dev/sdc | grep -sq 'ceph'",
                    "_uses_shell": true,
                    "chdir": null,
                    "creates": null,
                    "executable": null,
                    "removes": null,
                    "warn": true
                },
                "module_name": "command"
            },
            "item": "/dev/sdc",
            "rc": 1,
            "start": "2017-07-28 22:30:42.194679",
            "stderr": "lsblk: /dev/sdc: not a block device",
            "stdout": "",
            "stdout_lines": [],
            "warnings": []
        }
    ],
    "rc": 1,
    "start": "2017-07-28 22:30:43.786340",
    "stderr": "",
    "stdout": "ownership of '/var/run/ceph/' retained as ceph:ceph\nownership of '/var/lib/ceph/bootstrap-mds/ceph.keyring' retained as ceph:ceph\nownership of '/var/lib/ceph/bootstrap-mds' retained as ceph:ceph\nownership of '/var/lib/ceph/bootstrap-osd/ceph.keyring' retained as ceph:ceph\nownership of '/var/lib/ceph/bootstrap-osd' retained as ceph:ceph\nownership of '/var/lib/ceph/bootstrap-rgw/ceph.keyring' retained as ceph:ceph\nownership of '/var/lib/ceph/bootstrap-rgw' retained as ceph:ceph\nownership of '/var/lib/ceph/mds/ceph-mds-ceph-mon1' retained as ceph:ceph\nownership of '/var/lib/ceph/mds' retained as ceph:ceph\nownership of '/var/lib/ceph/mgr/ceph-ceph-mon1' retained as ceph:ceph\nownership of '/var/lib/ceph/mgr' retained as ceph:ceph\nownership of '/var/lib/ceph/mon/ceph-ceph-mon1/store.db/CURRENT' retained as ceph:ceph\nownership of '/var/lib/ceph/mon/ceph-ceph-mon1/store.db/LOCK' retained as ceph:ceph\nownership of '/var/lib/ceph/mon/ceph-ceph-mon1/store.db/000006.log' retained as ceph:ceph\nownership of '/var/lib/ceph/mon/ceph-ceph-mon1/store.db/000005.ldb' retained as ceph:ceph\nownership of '/var/lib/ceph/mon/ceph-ceph-mon1/store.db/MANIFEST-000004' retained as ceph:ceph\nownership of '/var/lib/ceph/mon/ceph-ceph-mon1/store.db' retained as ceph:ceph\nownership of '/var/lib/ceph/mon/ceph-ceph-mon1/kv_backend' retained as ceph:ceph\nownership of '/var/lib/ceph/mon/ceph-ceph-mon1/keyring' retained as ceph:ceph\nownership of '/var/lib/ceph/mon/ceph-ceph-mon1' retained as ceph:ceph\nownership of '/var/lib/ceph/mon' retained as ceph:ceph\nownership of '/var/lib/ceph/osd' retained as ceph:ceph\nownership of '/var/lib/ceph/radosgw/ceph-mon1' retained as ceph:ceph\nownership of '/var/lib/ceph/radosgw' retained as ceph:ceph\nownership of '/var/lib/ceph/tmp' retained as ceph:ceph\n2017-07-28 22:30:44  /entrypoint.sh: static: does not generate config\n2017-07-28 22:30:44  /entrypoint.sh: ERROR- The device pointed by OSD_DEVICE (/dev/sdc) doesn't exist !",
    "stdout_lines": [
        "ownership of '/var/run/ceph/' retained as ceph:ceph",
        "ownership of '/var/lib/ceph/bootstrap-mds/ceph.keyring' retained as ceph:ceph",
        "ownership of '/var/lib/ceph/bootstrap-mds' retained as ceph:ceph",
        "ownership of '/var/lib/ceph/bootstrap-osd/ceph.keyring' retained as ceph:ceph",
        "ownership of '/var/lib/ceph/bootstrap-osd' retained as ceph:ceph",
        "ownership of '/var/lib/ceph/bootstrap-rgw/ceph.keyring' retained as ceph:ceph",
        "ownership of '/var/lib/ceph/bootstrap-rgw' retained as ceph:ceph",
        "ownership of '/var/lib/ceph/mds/ceph-mds-ceph-mon1' retained as ceph:ceph",
        "ownership of '/var/lib/ceph/mds' retained as ceph:ceph",
        "ownership of '/var/lib/ceph/mgr/ceph-ceph-mon1' retained as ceph:ceph",
        "ownership of '/var/lib/ceph/mgr' retained as ceph:ceph",
        "ownership of '/var/lib/ceph/mon/ceph-ceph-mon1/store.db/CURRENT' retained as ceph:ceph",
        "ownership of '/var/lib/ceph/mon/ceph-ceph-mon1/store.db/LOCK' retained as ceph:ceph",
        "ownership of '/var/lib/ceph/mon/ceph-ceph-mon1/store.db/000006.log' retained as ceph:ceph",
        "ownership of '/var/lib/ceph/mon/ceph-ceph-mon1/store.db/000005.ldb' retained as ceph:ceph",
        "ownership of '/var/lib/ceph/mon/ceph-ceph-mon1/store.db/MANIFEST-000004' retained as ceph:ceph",
        "ownership of '/var/lib/ceph/mon/ceph-ceph-mon1/store.db' retained as ceph:ceph",
        "ownership of '/var/lib/ceph/mon/ceph-ceph-mon1/kv_backend' retained as ceph:ceph",
        "ownership of '/var/lib/ceph/mon/ceph-ceph-mon1/keyring' retained as ceph:ceph",
        "ownership of '/var/lib/ceph/mon/ceph-ceph-mon1' retained as ceph:ceph",
        "ownership of '/var/lib/ceph/mon' retained as ceph:ceph",
        "ownership of '/var/lib/ceph/osd' retained as ceph:ceph",
        "ownership of '/var/lib/ceph/radosgw/ceph-mon1' retained as ceph:ceph",
        "ownership of '/var/lib/ceph/radosgw' retained as ceph:ceph",
        "ownership of '/var/lib/ceph/tmp' retained as ceph:ceph",
        "2017-07-28 22:30:44  /entrypoint.sh: static: does not generate config",
        "2017-07-28 22:30:44  /entrypoint.sh: ERROR- The device pointed by OSD_DEVICE (/dev/sdc) doesn't exist !"
    ],
    "warnings": []
}
        to retry, use: --limit @/root/ceph-ansible/site-docker.retry
```

**Comment by leseb** [comment]
Does the device exist? Could it be `vdc` instead?

**Comment by dgedia** [comment]
The current output on osd0 does show that /dev/sdb exist as show by "sudo fdisk -l" command:
vagrant@ceph-osd0:~$ sudo fdisk -l
Disk /dev/sda: 40 GiB, 42949672960 bytes, 83886080 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x3c9154bb

Device     Boot   Start      End  Sectors  Size Id Type
/dev/sda1  *       2048   999423   997376  487M 83 Linux
/dev/sda2       1001470 83884031 82882562 39.5G  5 Extended
/dev/sda5       1001472 83884031 82882560 39.5G 8e Linux LVM


Disk /dev/sdc: 10.8 GiB, 11534336000 bytes, 22528000 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/sdb: 10.8 GiB, 11534336000 bytes, 22528000 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/mapper/vagrant--vg-root: 38.5 GiB, 41360031744 bytes, 80781312 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/mapper/vagrant--vg-swap_1: 1 GiB, 1073741824 bytes, 2097152 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
vagrant@ceph-osd0:~$

**Comment by dgedia** [comment]
Scrolling up the output of "vagrant provision" a little bit also shows me the same error for /dev/sdb as below:

failed: [osd0] (item=['/dev/sdb', {'_ansible_parsed': True, u'cmd': u"lsblk -o PARTLABEL /dev/sdb | grep -sq 'ceph'", u'end': u'2017-07-31 18:00:04.004167', '_ansible_no_log': False, u'stdout': u'', '_ansible_item_result': True, u'rc': 1, 'item': u'/dev/sdb', u'delta': u'0:00:00.004310', u'stderr': u'lsblk: /dev/sdb: not a block device', u'changed': True, 'invocation': {'module_name': u'command', u'module_args': {u'warn': True, u'executable': None, u'_uses_shell': True, u'_raw_params': u"lsblk -o PARTLABEL /dev/sdb | grep -sq 'ceph'", u'removes': None, u'creates': None, u'chdir': None}}, 'stdout_lines': [], 'failed_when_result': False, u'start': u'2017-07-31 18:00:03.999857', u'warnings': [], 'failed': False}]) => {
    "changed": true,
    "cmd": "docker run --net=host --pid=host --privileged=true --name=\"ceph-osd-prepare-ceph-mon1-devdevsdb\" -v /etc/ceph:/etc/ceph -v /var/lib/ceph/:/var/lib/ceph/ -v /dev:/dev -v /etc/localtime:/etc/localtime:ro -e \"OSD_DEVICE=/dev/sdb\" -e \"OSD_JOURNAL_UUID=$(python -c \"import uuid; print uuid.uuid5(uuid.NAMESPACE_DNS, 'cd0a3c8721ac05fdb3b30cf35950f92f/dev/sdb')\")\" -e CEPH_DAEMON=OSD_CEPH_DISK_PREPARE -e CLUSTER=ceph -e OSD_JOURNAL_SIZE=100 -e OSD_FORCE_ZAP=1 \"docker.io/ceph/daemon:latest\"",
    "delta": "0:00:00.684612",
    "end": "2017-07-31 18:00:05.798460",
    "failed": true,
    "invocation": {
        "module_args": {
            "_raw_params": "docker run --net=host --pid=host --privileged=true --name=\"ceph-osd-prepare-ceph-mon1-devdevsdb\" -v /etc/ceph:/etc/ceph -v /var/lib/ceph/:/var/lib/ceph/ -v /dev:/dev -v /etc/localtime:/etc/localtime:ro -e \"OSD_DEVICE=/dev/sdb\" -e \"OSD_JOURNAL_UUID=$(python -c \"import uuid; print uuid.uuid5(uuid.NAMESPACE_DNS, 'cd0a3c8721ac05fdb3b30cf35950f92f/dev/sdb')\")\" -e CEPH_DAEMON=OSD_CEPH_DISK_PREPARE -e CLUSTER=ceph -e OSD_JOURNAL_SIZE=100 -e OSD_FORCE_ZAP=1 \"docker.io/ceph/daemon:latest\"",
            "_uses_shell": true,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "warn": true
        },
        "module_name": "command"
    },
    "item": [
        "/dev/sdb",
        {
            "_ansible_item_result": true,
            "_ansible_no_log": false,
            "_ansible_parsed": true,
            "changed": true,
            "cmd": "lsblk -o PARTLABEL /dev/sdb | grep -sq 'ceph'",
            "delta": "0:00:00.004310",
            "end": "2017-07-31 18:00:04.004167",
            "failed": false,
            "failed_when_result": false,
            "invocation": {
                "module_args": {
                    "_raw_params": "lsblk -o PARTLABEL /dev/sdb | grep -sq 'ceph'",
                    "_uses_shell": true,
                    "chdir": null,
                    "creates": null,
                    "executable": null,
                    "removes": null,
                    "warn": true
                },
                "module_name": "command"
            },
            "item": "/dev/sdb",
            "rc": 1,
            "start": "2017-07-31 18:00:03.999857",
            "stderr": "lsblk: /dev/sdb: not a block device",
            "stdout": "",
            "stdout_lines": [],
            "warnings": []
        }
    ],
    "rc": 1,
    "start": "2017-07-31 18:00:05.113848",
    "stderr": "",
    "stdout": "ownership of '/var/run/ceph/' retained as ceph:ceph\nchanged ownership of '/var/lib/ceph/bootstrap-mds/ceph.keyring' from root:root to ceph:ceph\nownership of '/var/lib/ceph/bootstrap-mds' retained as ceph:ceph\nchanged ownership of '/var/lib/ceph/bootstrap-osd/ceph.keyring' from root:root to ceph:ceph\nownership of '/var/lib/ceph/bootstrap-osd' retained as ceph:ceph\nchanged ownership of '/var/lib/ceph/bootstrap-rgw/ceph.keyring' from root:root to ceph:ceph\nownership of '/var/lib/ceph/bootstrap-rgw' retained as ceph:ceph\nownership of '/var/lib/ceph/mds/ceph-mds-ceph-mon1' retained as ceph:ceph\nownership of '/var/lib/ceph/mds' retained as ceph:ceph\nownership of '/var/lib/ceph/mgr/ceph-ceph-mon1' retained as ceph:ceph\nownership of '/var/lib/ceph/mgr' retained as ceph:ceph\nownership of '/var/lib/ceph/mon/ceph-ceph-mon1/store.db/CURRENT' retained as ceph:ceph\nownership of '/var/lib/ceph/mon/ceph-ceph-mon1/store.db/LOCK' retained as ceph:ceph\nownership of '/var/lib/ceph/mon/ceph-ceph-mon1/store.db/000006.log' retained as ceph:ceph\nownership of '/var/lib/ceph/mon/ceph-ceph-mon1/store.db/000005.ldb' retained as ceph:ceph\nownership of '/var/lib/ceph/mon/ceph-ceph-mon1/store.db/MANIFEST-000004' retained as ceph:ceph\nownership of '/var/lib/ceph/mon/ceph-ceph-mon1/store.db' retained as ceph:ceph\nownership of '/var/lib/ceph/mon/ceph-ceph-mon1/kv_backend' retained as ceph:ceph\nownership of '/var/lib/ceph/mon/ceph-ceph-mon1/keyring' retained as ceph:ceph\nownership of '/var/lib/ceph/mon/ceph-ceph-mon1' retained as ceph:ceph\nownership of '/var/lib/ceph/mon' retained as ceph:ceph\nownership of '/var/lib/ceph/osd' retained as ceph:ceph\nownership of '/var/lib/ceph/radosgw/ceph-mon1' retained as ceph:ceph\nownership of '/var/lib/ceph/radosgw' retained as ceph:ceph\nownership of '/var/lib/ceph/tmp' retained as ceph:ceph\n2017-07-31 18:00:05  /entrypoint.sh: static: does not generate config\n2017-07-31 18:00:05  /entrypoint.sh: ERROR- The device pointed by OSD_DEVICE (/dev/sdb) doesn't exist !",
    "stdout_lines": [
        "ownership of '/var/run/ceph/' retained as ceph:ceph",
        "changed ownership of '/var/lib/ceph/bootstrap-mds/ceph.keyring' from root:root to ceph:ceph",
        "ownership of '/var/lib/ceph/bootstrap-mds' retained as ceph:ceph",
        "changed ownership of '/var/lib/ceph/bootstrap-osd/ceph.keyring' from root:root to ceph:ceph",
        "ownership of '/var/lib/ceph/bootstrap-osd' retained as ceph:ceph",
        "changed ownership of '/var/lib/ceph/bootstrap-rgw/ceph.keyring' from root:root to ceph:ceph",
        "ownership of '/var/lib/ceph/bootstrap-rgw' retained as ceph:ceph",
        "ownership of '/var/lib/ceph/mds/ceph-mds-ceph-mon1' retained as ceph:ceph",
        "ownership of '/var/lib/ceph/mds' retained as ceph:ceph",
        "ownership of '/var/lib/ceph/mgr/ceph-ceph-mon1' retained as ceph:ceph",
        "ownership of '/var/lib/ceph/mgr' retained as ceph:ceph",
        "ownership of '/var/lib/ceph/mon/ceph-ceph-mon1/store.db/CURRENT' retained as ceph:ceph",
        "ownership of '/var/lib/ceph/mon/ceph-ceph-mon1/store.db/LOCK' retained as ceph:ceph",
        "ownership of '/var/lib/ceph/mon/ceph-ceph-mon1/store.db/000006.log' retained as ceph:ceph",
        "ownership of '/var/lib/ceph/mon/ceph-ceph-mon1/store.db/000005.ldb' retained as ceph:ceph",
        "ownership of '/var/lib/ceph/mon/ceph-ceph-mon1/store.db/MANIFEST-000004' retained as ceph:ceph",
        "ownership of '/var/lib/ceph/mon/ceph-ceph-mon1/store.db' retained as ceph:ceph",
        "ownership of '/var/lib/ceph/mon/ceph-ceph-mon1/kv_backend' retained as ceph:ceph",
        "ownership of '/var/lib/ceph/mon/ceph-ceph-mon1/keyring' retained as ceph:ceph",
        "ownership of '/var/lib/ceph/mon/ceph-ceph-mon1' retained as ceph:ceph",
        "ownership of '/var/lib/ceph/mon' retained as ceph:ceph",
        "ownership of '/var/lib/ceph/osd' retained as ceph:ceph",
        "ownership of '/var/lib/ceph/radosgw/ceph-mon1' retained as ceph:ceph",
        "ownership of '/var/lib/ceph/radosgw' retained as ceph:ceph",
        "ownership of '/var/lib/ceph/tmp' retained as ceph:ceph",
        "2017-07-31 18:00:05  /entrypoint.sh: static: does not generate config",
        "2017-07-31 18:00:05  /entrypoint.sh: ERROR- The device pointed by OSD_DEVICE (/dev/sdb) doesn't exist !"
    ],
    "warnings": []
}

**Comment by guits** [comment]
Closed due to inactivity, feel free to re-open if needed. Thanks!
