### ISSUE TITLE
with containerized Ceph, only 1 SSD journal allowed

### ISSUE THREAD

**Issue by bengland2** [ceph/ceph-ansible#1729]
[Here is the comment](https://github.com/ceph/ceph-ansible/blob/master/group_vars/osds.yml.sample#L140) in the code, is this correct?  This comment says you can only configure a single SSD journal device when using containers to run Ceph OSDs.  If so, this is a show stopper for systems with over 12-16 drives/server, depending on the read/write mix.  Even NVM SSDs have trouble keeping up with more than that number of HDDs.

**Comment by leseb** [comment]
This is correct Ben, I have a PR for this here: https://github.com/ceph/ceph-ansible/pull/1724

**Comment by bengland2** [comment]
PR does not yet pass CI tests.  I think problem is out-of-scope item.1 reference (comment left in PR) but I need to reproduce on my own AWS cluster first, have some ideas on how to fix.
