### ISSUE TITLE
ceph-ansible: failure in ceph-mon playbook

### ISSUE THREAD

**Issue by tmuthamizhan** [ceph/ceph-ansible#1737]
ceph branch: jewel

ceph-ansible fails at "generate monitor initial keyring" in ceph-mon playbook with the following error "The conditional check 'not containerized_deployment' failed. The error was: error while evaluating conditional (not containerized_deployment): 'containerized_deployment' is undefined"

latest logs can be found at - http://qa-proxy.ceph.com/teuthology/teuthology-2017-08-02_04:15:01-ceph-ansible-jewel-distro-basic-vps/1471779/teuthology.log

**Comment by leseb** [comment]
What's the content of `cephlab.yml`? I suspect you need to update it to reflect our recent changes with the introduction of the `ceph-defaults` role, see: https://github.com/ceph/ceph-ansible/blob/master/site.yml.sample

**Comment by tmuthamizhan** [comment]
@leseb, can you please merge the fix so we can proceed with testing?

**Comment by guits** [comment]
@tmuthamizhan, unless I missed something, I think there is a misunderstanding here? There is no fix to push, you just need to include the `ceph-defaults` role in your `cephlab.yml`, indeed, we merged some days ago in master some commits which introduced a new role `ceph-defaults` that needs to be called before playing `ceph-common`, this role handles all default variables and sets all many facts that which are all consumed by `ceph-common`.

**Comment by tmuthamizhan** [comment]
@guits, where can i find cephlab.yml?
I believe this is a ceph-ansible change and thought you may simply add the new role ceph-defaults before ceph-common.

please correct me if am wrong

**Comment by andrewschoen** [comment]
@tmuthamizhan you need to explicitly define ``ceph-defaults`` and ``ceph-common`` roles now. It looks like teuthology does that here https://github.com/ceph/teuthology/blob/master/teuthology/task/ceph_ansible.py#L32

Our ``site.yml.sample`` playbook also does this now: https://github.com/ceph/ceph-ansible/blob/master/site.yml.sample#L44

**Comment by tmuthamizhan** [comment]
@andrewschoen , thank you! it works fine and am stuck with a new issue - https://github.com/ceph/ceph-ansible/issues/1752
