### ISSUE TITLE
bluestore database size on SSD

### ISSUE THREAD

**Issue by bengland2** [ceph/ceph-ansible#1744]
I took advantage of the new bluestore functionality in ceph-ansible to use SSD journal + SSD database with HDD data and it works,  I think this is really important functionality, but the database partition is very small, and I'm not convinced it is big enough to handle normal workloads.  For example, I ran a test to create 10 omaps, each with 1 million 16-byte keys, and I got a bluefs failure to allocate.  Once this happens, there is no clear recovery path.    For ceph-ansible, I would think it was important to be able to control the size of the /dev/nvmeXn1p* partitions to allocate more space for the database, right?  This won't really resolve what happens when you run out of space in the DB but could prevent it for more common cases.  Am I missing something - is there already a way to do this?  How does it determine database partition size?

**Comment by leseb** [comment]
Isn't this a bluestore parameter that you need to set using `ceph_conf_overrides`?
Once you get the value you want `ceph-disk` will pick it up.

This doesn't look like an issue to me.

**Comment by bengland2** [comment]
from your suggestion I found ceph.conf **bluestore block db size** parameter, will try and post whether that worked, thx!

**Comment by bengland2** [comment]
you were correct, closing this.
