### ISSUE TITLE
what branch to use to deploy a stable cluster ?

### ISSUE THREAD

**Issue by acomisario** [ceph/ceph-ansible#1751]
Sorry for this question, but i see so many branches, that i need to ask this.
what branch should i use ? master ? always ?

best.

**Comment by dvusboy** [comment]
Same boat here. I think there are `stable-*` with the version number referring to `ceph-ansible` releases. I don't know about the `ansible-*`. If I'm stuck with Ansible 1.9, can I use the branch `ansible-1.9`? Is it getting backported bug-fixes?

Many thanks for the great work though.

**Comment by xahare** [comment]
some notes on the different branches would be great! and, maybe a faq entry.

having tried a few, seems for jewel, stable-2.2 is good. for luminus, tag v2.3.0rc5 works.

master also worked, but had to change a couple osd variables. id like to know how stable master is supposed to be. most of the combinations i tried failed in various ways. most tests were with ubuntu xenial and ansible 2.3.1.0.

**Comment by fghaas** [comment]
_cough_ #1732

**Comment by xahare** [comment]
i dont remmeber the error, but luminous didnt work for me on 2.2 either. now im using 3.0rcX on a test luminous cluster and its doing well. a recent commit made it clear thats the branch they want to work on.

**Comment by leseb** [comment]
You have to use `stable-*` branches. We only support Ansible starting from 2.2, the latest tag 3.0rc series test on Ansible 2.3.1. We will continue to do so. The next major release (incoming) will likely only support Ansible starting from 2.3.1.

Thanks and sorry for the confusion, we will try to clarify all of that in the README soon.

**Comment by fghaas** [comment]
@leseb I suggest you keep this issue open, then close it with the commit that actually updates the `README`.

**Comment by leseb** [comment]
@fghaas sounds good to me.
