### ISSUE TITLE
serialize configuration changes?

### ISSUE THREAD

**Issue by xahare** [ceph/ceph-ansible#1754]
tried making configuration changes with ceph_conf_overrrides and re running the playbook. all three nodes tried to restart osds at the same time. 

is there an easy way to serialize this? should it be in the playbook?

running v2.3.0rc5 luminous on xenial in kvm.

**Comment by guits** [comment]
@xahare can you provide:
- your full playbook log (pastebin or whatever you want)
- your `group_vars/*` data?
- ansible version?

**Comment by xahare** [comment]
https://gist.github.com/xahare/06530d3722733e39324396342bc29605

ansible version 2.3.1.0

the first time, ceph_conf_overrides were commented out. the log posted is the run after that section was uncommented.

**Comment by guits** [comment]
@xahare the log you provided is not complete :
```
RUNNING HANDLER [ceph.ceph-common : restart ceph osds daemon(s)] *****************
^C [ERROR]: User interrupted execution
```

**Comment by xahare** [comment]
it hung there for a while, so i sshed into one of the nodes, and "ceph -s" said all the osds were up so i interrupted it. just ran the play again and it worked, but this time the new changes were in place. changed "osd pool default size" to 2, ran it again, and now its hung again at "restart ceph osd daemons" ill leave it going and update if/when it does anything.

**Comment by xahare** [comment]
the play finished, heres the error. theres a full log at the gist, https://gist.github.com/xahare/06530d3722733e39324396342bc29605#file-ceph-not-serial-log-full

fatal: [ceph3]: FAILED! => {"changed": true, "cmd": ["/tmp/restart_osd_daemon.sh"], "delta": "0:20:14.338538", "end": "2017-08-09 02:12:31.615223", "failed": true, "rc": 1, "start": "2017-08-09 01:52:17.276685", "stderr": "", "stderr_lines": [], "stdout": "Error while running 'ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring --cluster ceph -s', PGs were not reported as active+clean\nIt is possible that the cluster has less OSDs than the replica configuration\nWill refuse to continue\n  cluster:\n    id:     3d184655-691c-4bb3-a608-a083ee1bb24c\n    health: HEALTH_OK\n \n  services:\n    mon: 3 daemons, quorum ceph1,ceph2,ceph3\n    mgr: ceph1(active), standbys: ceph2, ceph3\n    osd: 3 osds: 3 up, 3 in\n \n  data:\n    pools:   0 pools, 0 pgs\n    objects: 0 objects, 0 bytes\n    usage:   3197 MB used, 146 GB / 149 GB avail\n    pgs:     \n ", "stdout_lines": ["Error while running 'ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring --cluster ceph -s', PGs were not reported as active+clean", "It is possible that the cluster has less OSDs than the replica configuration", "Will refuse to continue", "  cluster:", "    id:     3d184655-691c-4bb3-a608-a083ee1bb24c", "    health: HEALTH_OK", " ", "  services:", "    mon: 3 daemons, quorum ceph1,ceph2,ceph3", "    mgr: ceph1(active), standbys: ceph2, ceph3", "    osd: 3 osds: 3 up, 3 in", " ", "  data:", "    pools:   0 pools, 0 pgs", "    objects: 0 objects, 0 bytes", "    usage:   3197 MB used, 146 GB / 149 GB avail", "    pgs:     ", " "]}

**Comment by guits** [comment]
@xahare 
the `restart_osd_daemon.sh` can take a moment to finish depending on the values of `handler_health_osd_check_retries` and `handler_health_osd_check_delay` and how many osds you have.
The message is pretty clear here, the check didn't pass because your pg state is not OK.

Can you show me your `site.yml` file?

When I see: `pools: 0 pools, 0 pgs`, I suspect you didn't deploy an mgr node.

**Comment by xahare** [comment]
https://gist.github.com/xahare/06530d3722733e39324396342bc29605#file-site-yml
https://gist.github.com/xahare/06530d3722733e39324396342bc29605#file-hosts

**Comment by guits** [comment]
@xahare The problem here is that you interrupted the first deployment, so mgr node didn't get deployed, therefore, you are not in a 'clean' state. Without an mgr node deployed, the PG state won't be OK.

Could you try run again the playbook? I didn't try to reproduce your issue but I think it shouldn't trigger the handlers this time so you will get your mgr node deployed.

Let me know

**Comment by xahare** [comment]
the first time, a manager node should have been created. the play ran fine the first time through, just not the second after changing a value.

i tried making a pool, changing a ceph_conf_override, and running the playbook again. the handler was called, and everything worked. is it possible that a pool is needed for the health check?

**Comment by guits** [comment]
@xahare a pool should have been created here :
https://gist.github.com/xahare/06530d3722733e39324396342bc29605#file-ceph-not-serial-log-full-L1331
but in your case, the task has been skipped.

**Comment by guits** [comment]
@xahare task has been skipped probably because of these conditions :
https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-mon/tasks/ceph_keys.yml#L91-L92

**Comment by guits** [comment]
It should work if you change :
```
ceph_conf_overrides:
  osd:
    osd pool default size: 3
    osd pool default min size: 1
    osd pool default pg num: 250
    osd pool default pgp num: 250
    mon osd min down reporters: 1
```
to
```
ceph_conf_overrides:
  global:
    osd pool default size: 3
    osd pool default min size: 1
    osd pool default pg num: 250
    osd pool default pgp num: 250
    mon osd min down reporters: 1
```

Can you give it a try? Meantime I'm thinking about a patch because not sure this is really relevant to force users to have `osd pool default pg num` set in `global` section just because of this.

(@andrewschoen any opinion on that?)

**Comment by xahare** [comment]
tried global. as before, first time, the cluster came up, but no pools were created. having trouble with copy paste across VMs (qubes), ill update this when the log is up.

**Comment by guits** [comment]
@xahare actually if you change :

```
ceph_conf_overrides:
  global:
    osd pool default size: 3
    osd pool default min size: 1
    osd pool default pg num: 250
    osd pool default pgp num: 250
    mon osd min down reporters: 1
```
to:
```
ceph_conf_overrides:
  global:
    osd_pool_default_size: 3
    osd_pool_default_min_size: 1
    osd_pool_default_pg_num: 250
    osd_pool_default_pgp_num: 250
    mon_osd_min_down_reporters: 1
```

it should work

**Comment by xahare** [comment]
Yes, that created the pool. changed ceph-ansible version to v3.0.0rc3

the readme uses spaces between words in the variable names and has a note saying not to use underscores. should the docs be updated?

**Comment by guits** [comment]
@xahare as mentioned in the README, we shouldn't use underscores in `ceph_conf_overrides`.

I will make a patch for that check causing the rbd pool not created instead. thanks for having reported this issue.
