### ISSUE TITLE
Don't wait for user confirmation when migrating a cluster to containers

### ISSUE THREAD

**Issue by gfidente** [ceph/ceph-ansible#1758]
Would it be possible to not wait for user confirmation in the switch to containers playbook?

This would be useful when consuming the playbook in TripleO

**Comment by guits** [comment]
I think we could get rid of [this](https://github.com/ceph/ceph-ansible/blob/master/infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml#L11-L15) and just change [this](https://github.com/ceph/ceph-ansible/blob/master/infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml#L26) :

like this:
`when: ireallymeanit != 'yes'`
to 
`when: ireallymeanit is not defined and ireallymeanit != 'yes'`

@andrewschoen any thoughts?

**Comment by andrewschoen** [comment]
You can get around this by passing ``--extra-vars "ireallymeanit=yes"`` to your ``ansible-playbook`` command.

We do this for our CI testing of ``purge-cluster.yml`` and ``rolling_update.yml``. e.g https://github.com/ceph/ceph-ansible/blob/master/tox.ini#L15

**Comment by guits** [comment]
thx @andrewschoen, I was not aware of that. Looks there is no issue with that then.
