### ISSUE TITLE
Mode seems wrong on .mon. and .admin. keyrings on non-operating node

### ISSUE THREAD

**Issue by gfidente** [ceph/ceph-ansible#1760]
The .mon. and .admin. keyrings seem to have the wrong permissions set (644). Only the node which creates the keyrings uses 0600.

**Comment by gfidente** [comment]
It looks like the wrong permissions are set for the nodes hosting the ceph-osd role.

**Comment by fultonj** [comment]
Does this happen even if you set the mode permission to 600? Are we saying this is a side effect of the recent change? 

https://github.com/ceph/ceph-ansible/commit/7d429410901601a0b29d2be079aaf2bcc7c2bb94#diff-5b690092507379934c15b222efe0ec05

**Comment by leseb** [comment]
@fultonj looks like it to me. @gfidente, please make sure you change the dict with the right mode.
@gfidente can we close this?

**Comment by gfidente** [comment]
@leseb no this is precisely the issue I am reporting; we can specify a mode for the keys: and openstack_keys: structures and that works fine; it is not possible to specify a mode for the .mon. and the .admin. keyrings instead, which are appropriately defaulted to 0600 in the task but, that is only applied on the node where the keys are created, additional monitors where the key is copied don't seem to preserve the mode

**Comment by leseb** [comment]
@gfidente right, I believe `umask` is applied when copying the keys on the other hosts. Let me check that.

**Comment by leseb** [comment]
I suspect this tasks is the issue: https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-docker-common/tasks/fetch_configs.yml#L38-L49
