### ISSUE TITLE
site.yml.sample should be the main site.yml instead of sample file

### ISSUE THREAD

**Issue by vasukulkarni** [ceph/ceph-ansible#1763]
Since site.yml.sample actually has various roles that are run in proper order for all hosts we shouldn't let user create their own during a new deployment, the file should be renamed 'site.yml' and should be used as is like other infrastructure playbooks (eg: purge-cluster)

**Comment by andrewschoen** [comment]
Actually, it's expected for a user to change ``site.yml.sample`` to fit the needs of their own cluster. However, we've tried to design it so it works for most common use cases.

**Comment by leseb** [comment]
Closing this with @andrewschoen's answer.
