### ISSUE TITLE
"Unable to find any IP address in networks" while running ceph/daemon mon using docker in Mac

### ISSUE THREAD

**Issue by njalnapure** [ceph/ceph-ansible#1765]
Hi,

I am trying to run ceph/daemon monitor for last couple of days but it is keep failing for "unable to find any IP address in networks: 192.168.1.0/24"

My IP is 192.168.1.248 and CIDR is 192.168.1.0/24

```
Nileshs-MBP:daemon nileshjalnapure$  docker run -d --net=host \
> -e MON_IP=192.168.1.248 \
> -e CEPH_PUBLIC_NETWORK=192.168.1.0/24 \
> ceph/daemon mon
b0a163d85f0bdf044e9f50e49b471152ee7cf288d177a605da759f4625245750

Nileshs-MBP:daemon nileshjalnapure$ docker ps -a
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS                     PORTS               NAMES
b0a163d85f0b        ceph/daemon         "/entrypoint.sh mon"   4 seconds ago       Exited (1) 2 seconds ago                       hungry_joliot

Nileshs-MBP:daemon nileshjalnapure$ docker logs b0a163d85f0b
ownership of '/var/run/ceph/' retained as ceph:ceph
ownership of '/var/lib/ceph/mon' retained as ceph:ceph
changed ownership of '/var/lib/ceph/mon/ceph-moby' from root:root to ceph:ceph
ownership of '/var/lib/ceph/mds' retained as ceph:ceph
changed ownership of '/var/lib/ceph/mds/ceph-mds-moby' from root:root to ceph:ceph
ownership of '/var/lib/ceph/bootstrap-rbd' retained as ceph:ceph
ownership of '/var/lib/ceph/osd' retained as ceph:ceph
ownership of '/var/lib/ceph/mgr' retained as ceph:ceph
changed ownership of '/var/lib/ceph/mgr/ceph-moby' from root:root to ceph:ceph
ownership of '/var/lib/ceph/bootstrap-mgr' retained as ceph:ceph
ownership of '/var/lib/ceph/bootstrap-osd' retained as ceph:ceph
ownership of '/var/lib/ceph/bootstrap-mds' retained as ceph:ceph
ownership of '/var/lib/ceph/tmp' retained as ceph:ceph
ownership of '/var/lib/ceph/radosgw' retained as ceph:ceph
changed ownership of '/var/lib/ceph/radosgw/moby' from root:root to ceph:ceph
ownership of '/var/lib/ceph/bootstrap-rgw' retained as ceph:ceph
creating /etc/ceph/ceph.client.admin.keyring
creating /etc/ceph/ceph.mon.keyring
creating /var/lib/ceph/bootstrap-osd/ceph.keyring
creating /var/lib/ceph/bootstrap-mds/ceph.keyring
creating /var/lib/ceph/bootstrap-rgw/ceph.keyring
changed ownership of '/etc/ceph/ceph.mon.keyring' from root:root to ceph:ceph
changed ownership of '/var/lib/ceph/bootstrap-osd/ceph.keyring' from root:root to ceph:ceph
changed ownership of '/var/lib/ceph/bootstrap-mds/ceph.keyring' from root:root to ceph:ceph
changed ownership of '/var/lib/ceph/bootstrap-rgw/ceph.keyring' from root:root to ceph:ceph
monmaptool: monmap file /etc/ceph/monmap-ceph
monmaptool: set fsid to 00edd98d-1d09-401e-a400-24c024ca9bba
monmaptool: writing epoch 0 to /etc/ceph/monmap-ceph (1 monitors)
changed ownership of '/etc/ceph/monmap-ceph' from root:root to ceph:ceph
importing contents of /var/lib/ceph/bootstrap-osd/ceph.keyring into /etc/ceph/ceph.mon.keyring
importing contents of /var/lib/ceph/bootstrap-mds/ceph.keyring into /etc/ceph/ceph.mon.keyring
importing contents of /var/lib/ceph/bootstrap-rgw/ceph.keyring into /etc/ceph/ceph.mon.keyring
importing contents of /etc/ceph/ceph.client.admin.keyring into /etc/ceph/ceph.mon.keyring
2017-08-16 19:37:42.007802 7f3304b19f00 -1 unable to find any IP address in networks: 192.168.1.0/24


```
Please help urgently..

Nilesh

**Comment by r0ss3** [comment]
I'm not a docker for mac user so I'm not sure, but I believe docker for mac runs a linux VM in the background, the containers are not running on your mac itself.  So 192.168.1.248 might not be the IP you need here.

**Comment by leseb** [comment]
@r0ss3 +1, @njalnapure check the subnet of the container or simply use `NETWORK_AUTO_DETECT=1` instead.

**Comment by njalnapure** [comment]
I am checking on this. I will get back to you on this.

**Comment by njalnapure** [comment]
Hi,

Below is my ifconfig output.

Nileshs-MacBook-Pro:daemon nileshjalnapure$ ifconfig
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	options=1203<RXCSUM,TXCSUM,TXSTATUS,SW_TIMESTAMP>
	inet 127.0.0.1 netmask 0xff000000
	inet6 ::1 prefixlen 128
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1
	nd6 options=201<PERFORMNUD,DAD>
gif0: flags=8010<POINTOPOINT,MULTICAST> mtu 1280
stf0: flags=0<> mtu 1280
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether 78:4f:43:7d:06:cc
	inet6 fe80::8ff:1605:5418:3b2b%en0 prefixlen 64 secured scopeid 0x5
	inet 192.168.1.248 netmask 0xffffff00 broadcast 192.168.1.255
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
en1: flags=963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX> mtu 1500
	options=60<TSO4,TSO6>
	ether d2:00:bc:8a:0e:00
	media: autoselect <full-duplex>
	status: inactive
en3: flags=963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX> mtu 1500
	options=60<TSO4,TSO6>
	ether d2:00:bc:8a:0e:01
	media: autoselect <full-duplex>
	status: inactive
en2: flags=963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX> mtu 1500
	options=60<TSO4,TSO6>
	ether d2:00:bc:8a:0e:04
	media: autoselect <full-duplex>
	status: inactive
en4: flags=963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX> mtu 1500
	options=60<TSO4,TSO6>
	ether d2:00:bc:8a:0e:05
	media: autoselect <full-duplex>
	status: inactive
bridge0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=63<RXCSUM,TXCSUM,TSO4,TSO6>
	ether d2:00:bc:8a:0e:00
	Configuration:
		id 0:0:0:0:0:0 priority 0 hellotime 0 fwddelay 0
		maxage 0 holdcnt 0 proto stp maxaddr 100 timeout 1200
		root id 0:0:0:0:0:0 priority 0 ifcost 0 port 0
		ipfilter disabled flags 0x2
	member: en1 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 6 priority 0 path cost 0
	member: en2 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 8 priority 0 path cost 0
	member: en4 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 9 priority 0 path cost 0
	member: en3 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 7 priority 0 path cost 0
	nd6 options=201<PERFORMNUD,DAD>
	media: <unknown type>
	status: inactive
p2p0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 2304
	ether 0a:4f:43:7d:06:cc
	media: autoselect
	status: inactive
awdl0: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1484
	ether 22:30:ad:22:d9:03
	inet6 fe80::2030:adff:fe22:d903%awdl0 prefixlen 64 scopeid 0xc
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
utun0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 2000
	inet6 fe80::6caf:83e7:317a:dea0%utun0 prefixlen 64 scopeid 0xd
	nd6 options=201<PERFORMNUD,DAD>
utun1: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1380
	inet6 fe80::1ee5:775:1b36:d850%utun1 prefixlen 64 scopeid 0xe
	nd6 options=201<PERFORMNUD,DAD>
utun2: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1380
	inet6 fe80::4c4b:1f19:862f:98ea%utun2 prefixlen 64 scopeid 0xf
	nd6 options=201<PERFORMNUD,DAD>
utun3: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1380
	inet6 fe80::95b1:73f5:d15b:ae61%utun3 prefixlen 64 scopeid 0x11
	nd6 options=201<PERFORMNUD,DAD>
utun4: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1380
	inet6 fe80::1366:669:3009:2e0b%utun4 prefixlen 64 scopeid 0x12
	nd6 options=201<PERFORMNUD,DAD>
utun5: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1380
	inet6 fe80::bb3:89ae:7f5b:2436%utun5 prefixlen 64 scopeid 0x13
	nd6 options=201<PERFORMNUD,DAD>
utun6: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1380
	inet6 fe80::df0:9764:8a8c:9aca%utun6 prefixlen 64 scopeid 0x14
	nd6 options=201<PERFORMNUD,DAD>
utun7: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1380
	inet6 fe80::b9da:1352:3542:b558%utun7 prefixlen 64 scopeid 0x15
	nd6 options=201<PERFORMNUD,DAD>
utun8: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1380
	inet6 fe80::83b4:1708:f7a8:9f35%utun8 prefixlen 64 scopeid 0x16
	nd6 options=201<PERFORMNUD,DAD>
utun9: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1380
	inet6 fe80::bf67:cee0:5919:90a%utun9 prefixlen 64 scopeid 0x17
	nd6 options=201<PERFORMNUD,DAD>
utun10: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1380
	inet6 fe80::351f:84b4:ecdd:1063%utun10 prefixlen 64 scopeid 0x18
	nd6 options=201<PERFORMNUD,DAD>
utun11: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1380
	inet6 fe80::8e96:ac18:382e:5812%utun11 prefixlen 64 scopeid 0x19
	nd6 options=201<PERFORMNUD,DAD>
utun12: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1380
	inet6 fe80::eb39:9d30:6382:a99f%utun12 prefixlen 64 scopeid 0x1a
	nd6 options=201<PERFORMNUD,DAD>
en5: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether ac:de:48:00:11:22
	inet6 fe80::aede:48ff:fe00:1122%en5 prefixlen 64 scopeid 0x4
	nd6 options=281<PERFORMNUD,INSECURE,DAD>
	media: autoselect
	status: active

Nilesh

**Comment by leseb** [comment]
We need the subnet within the docker container, so the docker bridge to be precise.
