### ISSUE TITLE
validate monitor_address and friends

### ISSUE THREAD

**Issue by fullerdj** [ceph/ceph-ansible#1766]
If the user supplies an incorrect monitor_address or monitor_address_block, ceph-ansible blows up trying to generate ceph.conf with the very unhelpful error message:

"msg": "No first item, sequence was empty."

Check that hostvars[host]['ansible_all_ipvX_addresses'] | ipaddr(monitor_address_block) is not empty before running generate ceph configuration file.

**Comment by guits** [comment]
This is now handled by ceph-validate

**Comment by satishdotpatel** [comment]
Why i am still getting error in luminous deployment?
