### ISSUE TITLE
Luminous : nfs-ganesha-fsal : Depends: glusterfs-common (>= 3.8.8) but it is not going to be installed

### ISSUE THREAD

**Issue by mistur** [ceph/ceph-ansible#1768]
Hello,

I try to install a Luminous cluster on 4 nodes with Ubunt 16.04 and it failed on nfs-ganesha-fsal 

`fatal: [cluster019.cluster]: FAILED! => {`
`    "cache_update_time": 1502971361, `
`    "cache_updated": true, `
`    "changed": false, `
`    "failed": true, `
`    "invocation": {`
`        "module_args": {`
`            "allow_unauthenticated": false, `
`            "autoremove": null, `
`            "cache_valid_time": 0, `
`            "deb": null, `
`            "default_release": null, `
`            "dpkg_options": "force-confdef,force-confold", `
`            "force": false, `
`            "install_recommends": null, `
`            "only_upgrade": false, `
`            "package": [`
`                "nfs-ganesha-fsal"`
`            ], `
`            "pkg": "nfs-ganesha-fsal", `
`            "purge": false, `
`            "state": "present", `
`            "update_cache": true, `
`            "upgrade": null`
`        }`
`    }, `
`    "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'nfs-ganesha-fsal'' failed: E: Unable to correct problems, you have held broken packages.\n", `
`    "rc": 100, `
`    "stderr": "E: Unable to correct problems, you have held broken packages.\n", `
`    "stderr_lines": [`
`        "E: Unable to correct problems, you have held broken packages."`
`    ], `
`    "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nSome packages could not be installed. This may mean that you have\nrequested an impossible situation or if you are using the unstable\ndistribution that some required packages have not yet been created\nor been moved out of Incoming.\nThe following information may help to resolve the situation:\n\nThe following packages have unmet dependencies:\n nfs-ganesha-fsal : Depends: glusterfs-common (>= 3.8.8) but it is not going to be installed\n", `
`    "stdout_lines": [`
`        "Reading package lists...", `
`        "Building dependency tree...", `
`        "Reading state information...", `
`        "Some packages could not be installed. This may mean that you have", `
`        "requested an impossible situation or if you are using the unstable", `
`        "distribution that some required packages have not yet been created", `
`        "or been moved out of Incoming.", `
`        "The following information may help to resolve the situation:", `
`        "", `
`        "The following packages have unmet dependencies:", `
`        " nfs-ganesha-fsal : Depends: glusterfs-common (>= 3.8.8) but it is not going to be installed"`
`    ]
`}`

The version availabe in 16.04 is :

`glusterfs-common/xenial 3.7.6-1ubuntu1 amd64`
`  GlusterFS common libraries and translator modules`

is that a ceph issue or ceph-ansible issue ?

Best regards,

Yoann Moulin

**Comment by mistur** [comment]
full ceph-ansible playbook log : [ceph-ansible.log.zip](https://github.com/ceph/ceph-ansible/files/1231334/ceph-ansible.log.zip)

ceph-ansible config (group_vars/* + inventory) : [cluster-luminous.zip](https://github.com/ceph/ceph-ansible/files/1231312/cluster-luminous.zip)

admin004:~/git/ceph-ansible-luminous# ansible --version
ansible 2.3.2.0
  config file = /root/git/ceph-ansible-luminous/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]

I use the lastest master branch of ceph-ansible 

Yoann

**Comment by xelexin** [comment]
Quick fix to get nfss running is to add in 

> roles/ceph-common/tasks/installs/debian_ceph_repository.yml

item:

>     - ppa:gluster/glusterfs-3.8

**Comment by mistur** [comment]
by fixing this it solved my other issue : https://github.com/ceph/ceph-ansible/issues/1769

Thanks

**Comment by xelexin** [comment]
Good information, I will create pull request :)

**Comment by xelexin** [comment]
@mistur do you have shared these shared libraries:

- /usr/lib/x86_64-linux-gnu/ganesha/libfsalceph.so
- /usr/lib/x86_64-linux-gnu/ganesha/libfsalrgw.so
