### ISSUE TITLE
The switch-to-containers playbook fails when called from TripleO

### ISSUE THREAD

**Issue by gfidente** [ceph/ceph-ansible#1774]
In TripleO we're trying to run two infrastructure playbooks sequentially

1. take-over-existing-cluster.yml (which completes successfully)
2. switch-from-non-containerized-to-containerized-ceph-daemons.yml

The second fails in [get current ceph fsid] with:

fatal: [192.168.24.7]: FAILED! => {"failed": true, "msg": "'mon_host' is undefined"}

Output from execution attached
[switch_failure.txt](https://github.com/ceph/ceph-ansible/files/1234155/switch_failure.txt)

**Comment by gfidente** [comment]
I think this happens because with a single monitor the when condition in [select a running monitor] is never met; it prevents migration of clusters with a single monitor. Is this the intended behavior?

**Comment by gfidente** [comment]
I think we still want to make some changes, working on it in PR #1779

**Comment by gfidente** [comment]
More fixes coming with https://github.com/ceph/ceph-ansible/pull/1788

**Comment by guits** [comment]
Closed due to inactivity, feel free to re-open if needed. Thanks!
