### ISSUE TITLE
rest api keyring and mgr keyring are not created 

### ISSUE THREAD

**Issue by mistur** [ceph/ceph-ansible#1776]
I still try to deploy a Lunimous cluster and now I have an issue with rest api keyring and mgr keyring creation : 

```TASK [ceph-mon : create ceph rest api keyring when mon is not containerized]
********************************************************************************************************************************************************************************************************************************************
task path: /root/git/ceph-ansible-luminous/roles/ceph-mon/tasks/ceph_keys.yml:35
skipping: [cluster007.cluster] => {
        "changed": false, 
        "skip_reason": "Conditional result was False", 
        "skipped": true
}
skipping: [cluster015.cluster] => {
        "changed": false, 
        "skip_reason": "Conditional result was False", 
        "skipped": true
}

TASK [ceph-mon : create ceph mgr keyring(s) when mon is not containerized]
**********************************************************************************************************************************************************************************************************************************************
task path: /root/git/ceph-ansible-luminous/roles/ceph-mon/tasks/ceph_keys.yml:45
skipping: [cluster007.cluster] => (item=cluster007.cluster)  => {
        "changed": false, 
        "item": "cluster007.cluster.", 
        "skip_reason": "Conditional result was False", 
        "skipped": true
}
skipping: [cluster015.cluster] => (item=cluster007.cluster)  => {
        "changed": false, 
        "item": "cluster007.cluster.", 
        "skip_reason": "Conditional result was False", 
        "skipped": true
}
skipping: [cluster007.cluster] => (item=cluster015.cluster)  => {
        "changed": false, 
        "item": "cluster015.cluster.", 
        "skip_reason": "Conditional result was False", 
        "skipped": true
}
skipping: [cluster015.cluster] => (item=cluster015.cluster)  => {
        "changed": false, 
        "item": "cluster015.cluster.", 
        "skip_reason": "Conditional result was False", 
        "skipped": true
}
skipping: [cluster007.cluster] => (item=cluster019.cluster)  => {
        "changed": false, 
        "item": "cluster019.cluster.", 
        "skip_reason": "Conditional result was False", 
        "skipped": true
}
skipping: [cluster015.cluster] => (item=cluster019.cluster)  => {
        "changed": false, 
        "item": "cluster019.cluster.", 
        "skip_reason": "Conditional result was False", 
        "skipped": true
}```

Yoann

**Comment by mistur** [comment]
Config of the cluster : [cluster-luminous-1776.zip](https://github.com/ceph/ceph-ansible/files/1238726/cluster-luminous-1776.zip)

**Comment by mistur** [comment]
playbook log : [luminous-1776.debug.zip](https://github.com/ceph/ceph-ansible/files/1238761/luminous-1776.debug.zip)

**Comment by mistur** [comment]
this problem disappear with the fix on https://github.com/ceph/ceph-ansible/issues/1768

**Comment by girishvnair** [comment]
I am trying to setup openstack ansible. I have 6 blades with a partition /dev/sda5 of 635 Gb each . I want to use ceph with openstack ansible to utilize these storage disks effectively. When I execute openstack-ansible setup-infrastructure.yml , I get fpollowing error :

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AnsibleFileNotFound: Could not find or access '/etc/opetack_deploy/ceph-fetch//c24b571b-894a-4b12-9c8a-774d26549b91/var/lib/ceph/bootstrap-osd/ceph.keyring'
failed: [infra1] (item={u'name': u'/var/lib/ceph/bootstrap-osd/ceph.keyring', u'copy_key': True}) => {"changed": false, "failed": true, "item": {"copy_k": true, "name": "/var/lib/ceph/bootstrap-osd/ceph.keyring"}, "msg": "Could not find or access '/etc/openstack_deploy/ceph-fetch//c24b571b-894a-4b12-9c8774d26549b91/var/lib/ceph/bootstrap-osd/ceph.keyring'"}
skipping: [infra1] => (item={u'name': u'/etc/ceph/ceph.client.admin.keyring', u'copy_key': False})

my user_variables.yml file has :

generate_fsid: false
fsid: c24b571b-894a-4b12-9c8a-774d26549b91
#monitor_address_block: "{{ cidr_networks.container }}"
#public_network: "{{ cidr_networks.container }}"
#cluster_network: "{{ cidr_networks.storage }}"
monitor_address_block: "192.168.250.0/24"
public_network: "192.168.250.0/24"
cluster_network: "192.168.100.0/24"
osd_scenario: collocated
osd_objectstore: bluestore
osd_auto_discovery: true
devices:
- /dev/sda5
journal_size: 10240 # size in MB
openstack_config: true
cinder_ceph_client: cinder
glance_ceph_client: glance
glance_default_store: rbd
glance_rbd_store_pool: images
nova_libvirt_images_rbd_pool: vms

cinder_backends:
RBD:
volume_driver: cinder.volume.drivers.rbd.RBDDriver
rbd_pool: volumes
rbd_ceph_conf: /etc/ceph/ceph.conf
rbd_store_chunk_size: 8
volume_backend_name: rbddriver
rbd_user: "{{ cinder_ceph_client }}"
rbd_secret_uuid: "{{ cinder_ceph_client_uuid }}"
report_discard_supported: true

My openstack_user_config.yml file has:

ceph-osd_hosts:
infra2:
ip: 192.168.250.22
device: "/dev/sda5"
infra4:
ip: 192.168.250.24
device: "/dev/sda5"
infra5:
ip: 192.168.250.25
device: "/dev/sda5"
infra6:
ip: 192.168.250.26
device: "/dev/sda5"

Kindly help please

**Comment by guits** [comment]
Closed due to inactivity, feel free to re-open if needed. Thanks!
