### ISSUE TITLE
Hot-swapping disks confuses ceph-ansible

### ISSUE THREAD

**Issue by mcv21** [ceph/ceph-ansible#1777]
Hi,

We have osds' devices specified via inventory (to be `/dev/sda` through `/dev/sdbh`), and raw journal devices similarly specified for NVME cards, and `raw_multi_journal` set.

This works fine, until we hot-plug a disk (i.e. to replace a failed drive) - the new drive then appears as `/dev/sdbk` and the failed drive doesn't exist in `/dev/` any more, so ceph-ansible then fails on that host
in the 'ceph-osd : fix partitions gpt header or labels of the osd disks' task.

Example barf:

```
failed: [sto-2-2] (item=[{'_ansible_parsed': True, 'stderr_lines': [], '_ansible_item_result': True, u'end': u'2017-07-26 11:36:12.019353', '_ansible_no_log': False, u'stdout': u'', u'cmd': u'parted --script /dev/sdah print > /dev/null 2>&1', u'rc': 1, 'item': [{'_ansible_parsed': True, 'stderr_lines': [], '_ansible_item_result': True, u'end': u'2017-07-26 11:31:47.372346', '_ansible_no_log': False, u'stdout': u'', u'cmd': u"readlink -f /dev/sdah | egrep '/dev/([hsv]d[a-z]{1,2}|cciss/c[0-9]d[0-9]p|nvme[0-9]n[0-9]p)[0-9]{1,2}$'", u'rc': 1, 'item': u'/dev/sdah', u'delta': u'0:00:00.004611', u'stderr': u'', u'changed': False, u'invocation': {u'module_args': {u'warn': True, u'executable': None, u'_uses_shell': True, u'_raw_params': u"readlink -f /dev/sdah | egrep '/dev/([hsv]d[a-z]{1,2}|cciss/c[0-9]d[0-9]p|nvme[0-9]n[0-9]p)[0-9]{1,2}$'", u'removes': None, u'creates': None, u'chdir': None}}, 'stdout_lines': [], 'failed_when_result': False, u'start': u'2017-07-26 11:31:47.367735', 'failed': False}, u'/dev/sdah'], u'delta': u'0:00:00.004145', u'stderr': u'', u'changed': False, u'invocation': {u'module_args': {u'warn': True, u'executable': None, u'_uses_shell': True, u'_raw_params': u'parted --script /dev/sdah print > /dev/null 2>&1', u'removes': None, u'creates': None, u'chdir': None}}, 'stdout_lines': [], 'failed_when_result': False, u'start': u'2017-07-26 11:36:12.015208', 'failed': False}, u'/dev/sdah']) => {"changed": false, "cmd": "sgdisk --zap-all --clear --mbrtogpt -- /dev/sdah || sgdisk --zap-all --clear --mbrtogpt -- /dev/sdah", "delta": "0:00:00.008660", "end": "2017-07-26 13:07:28.664214", "failed": true, "item": [{"_ansible_item_result": true, "_ansible_no_log": false, "_ansible_parsed": true, "changed": false, "cmd": "parted --script /dev/sdah print > /dev/null 2>&1", "delta": "0:00:00.004145", "end": "2017-07-26 11:36:12.019353", "failed": false, "failed_when_result": false, "invocation": {"module_args": {"_raw_params": "parted --script /dev/sdah print > /dev/null 2>&1", "_uses_shell": true, "chdir": null, "creates": null, "executable": null, "removes": null, "warn": true}}, "item": [{"_ansible_item_result": true, "_ansible_no_log": false, "_ansible_parsed": true, "changed": false, "cmd": "readlink -f /dev/sdah | egrep '/dev/([hsv]d[a-z]{1,2}|cciss/c[0-9]d[0-9]p|nvme[0-9]n[0-9]p)[0-9]{1,2}$'", "delta": "0:00:00.004611", "end": "2017-07-26 11:31:47.372346", "failed": false, "failed_when_result": false, "invocation": {"module_args": {"_raw_params": "readlink -f /dev/sdah | egrep '/dev/([hsv]d[a-z]{1,2}|cciss/c[0-9]d[0-9]p|nvme[0-9]n[0-9]p)[0-9]{1,2}$'", "_uses_shell": true, "chdir": null, "creates": null, "executable": null, "removes": null, "warn": true}}, "item": "/dev/sdah", "rc": 1, "start": "2017-07-26 11:31:47.367735", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}, "/dev/sdah"], "rc": 1, "start": "2017-07-26 11:36:12.015208", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}, "/dev/sdah"], "rc": 4, "start": "2017-07-26 13:07:28.655554", "stderr": "Problem opening /dev/sdah for reading! Error is 2.\nThe specified file does not exist!\nProblem opening '' for writing! Program will now terminate.\nWarning! MBR not overwritten! Error is 2!\nCaution! Secondary header was placed beyond the disk's limits! Moving the\nheader, but other problems may occur!\nUnable to open device '' for writing! Errno is 2! Aborting write!\nProblem opening /dev/sdah for reading! Error is 2.\nThe specified file does not exist!\nProblem opening '' for writing! Program will now terminate.\nWarning! MBR not overwritten! Error is 2!\nCaution! Secondary header was placed beyond the disk's limits! Moving the\nheader, but other problems may occur!\nUnable to open device '' for writing! Errno is 2! Aborting write!", "stderr_lines": ["Problem opening /dev/sdah for reading! Error is 2.", "The specified file does not exist!", "Problem opening '' for writing! Program will now terminate.", "Warning! MBR not overwritten! Error is 2!", "Caution! Secondary header was placed beyond the disk's limits! Moving the", "header, but other problems may occur!", "Unable to open device '' for writing! Errno is 2! Aborting write!", "Problem opening /dev/sdah for reading! Error is 2.", "The specified file does not exist!", "Problem opening '' for writing! Program will now terminate.", "Warning! MBR not overwritten! Error is 2!", "Caution! Secondary header was placed beyond the disk's limits! Moving the", "header, but other problems may occur!", "Unable to open device '' for writing! Errno is 2! Aborting write!"], "stdout": "Information: Creating fresh partition table; will override earlier problems!\nInformation: Creating fresh partition table; will override earlier problems!", "stdout_lines": ["Information: Creating fresh partition table; will override earlier problems!", "Information: Creating fresh partition table; will override earlier problems!"]}
```

**Comment by mcv21** [comment]
The output isn't very helpful, but it's basically failing to open `/dev/sdah`, because it doesn't exist.

**Comment by leseb** [comment]
Indeed `Problem opening /dev/sdah for reading! Error is 2.\nThe specified file does not exist!`.
Perhaps we should check that the devices listed in `devices` exist.

@fullerdj, do you mind taking a stab at this one? Thanks!

**Comment by acomisario** [comment]
any news ?

**Comment by guits** [comment]
Closed due to inactivity, feel free to re-open if needed. Thanks!

**Comment by mcv21** [comment]
@guits this is still a live issue, could you re-open, please?

**Comment by guits** [comment]
@mcv21 sure

**Comment by guits** [comment]
@mcv21 could you provide more details ? How can I reproduce this issue in a virtualized environment? Do you mind sharing a typical log (full) of a failing run? Thanks!

**Comment by mcv21** [comment]
If you have a virtualised environment where you can control virtual disks, it should be fairly straightforward:

1. set up with some disks, specify lvm_volumes (with suitable data / db entries), osd_objectstore=bluestore, osd_scenario=lvm
2. run ceph-ansible, observe all is good
3. pick an OSD, stop it, and remove the relevant virtual disk
4. re-run ceph-ansible, get error message like in the initial report

**Comment by mcv21** [comment]
Looking at 3.2 (which is where our current deployment is), you have in roles/ceph-osd/tasks/main.yml
```YAML
- name: read information about the devices
  parted:
    device: "{{ item }}"
    unit: MiB
  register: parted_results
  with_items: "{{ devices }}"
```
(and similar in roles/ceph-validate/tasks/check_devices.yml)
```YAML
- name: validate devices is actually a device
  parted:
    device: "{{ item }}"
    unit: MiB
  register: devices_parted
  with_items: "{{ devices }}"
```

This will fail if any of `{{ devices }}` is absent, roughly:
`failed: [sto-t1-1] (item=/dev/does_not_exist) => {"changed": false, "err": "Error: Could not stat device /dev/does_not_exist - No such file or directory.\n", "item": "/dev/does_not_exist", "msg": "Error while getting device information with parted script: '/sbin/parted -s -m /dev/does_not_exist -- unit 'MiB' print'", "out": "", "rc": 1}`

**Comment by mcv21** [comment]
This issue is still live - please don't close it.

**Comment by mcv21** [comment]
This issue is still live - please don't close it.
[aside: this process is a bit irritating, could there be some way to disable it even for particular issues?]

**Comment by mcv21** [comment]
[still an issue]

**Comment by guits** [comment]
@mcv21 that would be really complex to make ceph-ansible detecting if the name of a device linked to an OSD has changed between 2 runs, the only thing we can do here is to check if devices present in `lvm_volumes` / `devices` / `dedicated_devices` actually exist.

**Comment by mcv21** [comment]
@guits I appreciate it's not a straightforward issue to solve! But it is a real problem for us - our main cluster has 51 nodes, with 60 OSDs each, so the chance of at least one of them having had a disk swapped since the last reboot (and so an odd device name) is pretty high; and at the moment this blocks us running ceph-ansible against our cluster.

Some workarounds that might help:
1. a flag for "don't worry about the state of OSD devices" (which would be able to use in this situation to run ceph-ansible against our cluster)
2. a script to run on the host to ask it what devices its running OSDs on? I'm not sure this is a good idea in the general case, but e.g. `ceph-volume lvm list` does typically know which devices are in play

I don't use ceph-ansible to replace a failed OSD (it's relatively heavyweight and slow for that purpose), though I do for adding entire hosts to the cluster.

**Comment by devfaz** [comment]
@mcv21 i agree this is a bug, but maybe you could workaround this with udev rules to create alias devnames (fe /dev/diskSlot3) and/or trigger a rescan of your hba? Just my 3cents :)

**Comment by BenoitKnecht** [comment]
On most distributions, udev already generates persistent disk names under `/dev/disk/by-path/`.

@mcv21 Wouldn't it solve your issue if you specified your disk paths as `/dev/disk/by-path/...` instead of `/dev/sda`? If a disk fails and you replace it, udev should create a link with the exact same name since it'll be plugged in on the same connector.

**Comment by mcv21** [comment]
by-path links _might_ help, but they're very hardware-dependent in a way that sda et al aren't (e.g. if we get a new storage node with different internals, I imagine the by-path links will be different, since they're quite detailed e.g. pci-0000:01:00.0-sas-exp0x5003048009259fff-phy25-lun-0

**Comment by mcv21** [comment]
[could we disable the auto-stale on this?]

**Comment by srelf-ukcloud** [comment]
We have had this issue in the past, and have got around it by doing the following (YMMV/do it in a test cluster first :D)

Let's assume the scenario as follows

Original Mapping : /dev/sdd

New Mapping : /dev/sdl

Set the new mapping state to delete
  echo 1 > /sys/block/sdl/device/delete

then rescan the scsi bus (we use RH so we can use the following https://access.redhat.com/solutions/1314183)

Sometimes we just have to reboot the server.

**Comment by mcv21** [comment]
Sorry to circle back to @BenoitKnecht 's suggestion of `/dev/disk/by-path` after so much time! I've looked at our deployment, and this won't work for us, either. While all of our OSD nodes are essentially the same hardware, they clearly differ enough for the by-path entries to not be the same, e.g. we see
pci-0000:01:00.0-sas-exp0x5003048009259dff-phy16-lun-0
pci-0000:01:00.0-sas-exp0x5003048001aa47bf-phy16-lun-0
pci-0000:01:00.0-sas-exp0x500304801f71693f-phy16-lun-0
pci-0000:01:00.0-sas-exp0x500304801f71953f-phy16-lun-0
and that was just picking 4 nodes at random.
I'll look at the rescan-scsi-bus.sh tip, though - I've not found it helped in the past, but I didn't know about the -r and -a options.

**Comment by svogt** [comment]
@mcv21 - sorry to jump in, but stumbled accross this issue. We use "/dev/disk/by-id/" and then use one of the entries which contain the serial number of the drive - this for us remained stable accross reboots and hotplugs... (running Ubuntu 18.04)

**Comment by mcv21** [comment]
@svogt that's an interesting idea, but I don't see how that scales very well (are you generating a custom fact per-system which works out what devices to use or something?), and such a link doesn't always exist e.g.:
```
root@sto-1-1:~# smartctl -i /dev/sdd | grep Serial
Serial number:        76J0A05UFWWB
root@sto-1-1:~# ls /dev/disk/by-id | grep -i 76J0A05UFWWB
```
And then on some of our (roughly identical SM 4U) servers, you have `/dev/disk/by-id/ata-*` and on others `/dev/disk/by-id/scsi-*` and some have a mix of both(!); so it's still seemingly pretty variable even on very similar kit.

**Comment by svogt** [comment]
Hm, never had that issue but we have not a huge-scale deployment. We have different enough hardware anyway so we need to maintain a host_var yaml and there we just list the devices. But we need the host-specific yaml for other parts of the initial config as well (like network etc. pp) - YMMV especially if you do not have stable or recognisable /dev/disk/by-id links

Another option would be to explicitly set partlabels etc, so you can use one of the other /dev/disk/by-... But that makes initial provisioning more cumbersome ;)
