### ISSUE TITLE
purge-cluster.yml does not support osd_scenario=lvm

### ISSUE THREAD

**Issue by jharriga** [ceph/ceph-ansible#1787]
I have a ceph cluster deployed with osd_scenario=lvm
I tried running purge-cluster and no go... it needs 'devices' defined.
    fatal: [gprfs041.sbu.lab.eng.bos.redhat.com]: FAILED! => {"failed": true, "msg": "The conditional
    check 'devices|length == 0' failed. The error was: error while evaluating conditional (devices|length
    == 0): 'devices' is undefined\n

Since I am running with osd_scenario=lvm I have not defined that var.

FYI, the vars in 'group_vars/osds' look like this

osd_scenario: lvm
lvm_volumes:
  cached-lv0: /dev/nvme0n1p5
  cached-lv1: /dev/nvme0n1p6
  cached-lv2: /dev/nvme0n1p7
  noncached-lv0: /dev/nvme0n1p8
  noncached-lv1: /dev/nvme0n1p9
  noncached-lv2: /dev/nvme0n1p10

**Comment by andrewschoen** [comment]
Thanks for reporting this. We currently have not build support into ``purge-cluster.yml`` for the ``lvm`` osd scenario. @alfredodeza and I were just discussing a ``ceph-volume lvm zap`` command to assist with this process, but we're not sure when it'll land in ceph. In the meantime I could try to add some tasks to ``purge-cluster.yml`` to handle this outside of ``ceph-volume``.

**Comment by jharriga** [comment]
I am trying to do some performance testing with lvm osd scenario which will require tearing down and rebuilding the cluster with various lvm configurations.
I could really use a  purge ability. Thanks.
