### ISSUE TITLE
ceph-ansible/roles/ceph-mon/tasks/start_monitor.yml: ERROR! no action detected in task.

### ISSUE THREAD

**Issue by ljozsa** [ceph/ceph-ansible#1790]
I'm attempting to run the following playbook

```
#!/bin/ansible-playbook -i inventory
---
- hosts: ceph-nodes
  become: true
  roles:
    - ceph-ansible/roles/ceph-mon
    - ceph-ansible/roles/ceph-osd


But I'm getting error 

$ ansible-playbook -vvv install-ceph.yaml 
Using /home/stack/centralci-openstack-rhos10/external-ceph/ansible.cfg as config file
statically included: /home/stack/centralci-openstack-rhos10/external-ceph/ceph-ansible/roles/ceph-mon/tasks/check_mandatory_vars.yml
statically included: /home/stack/centralci-openstack-rhos10/external-ceph/ceph-ansible/roles/ceph-mon/tasks/deploy_monitors.yml
statically included: /home/stack/centralci-openstack-rhos10/external-ceph/ceph-ansible/roles/ceph-mon/tasks/start_monitor.yml
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/home/stack/centralci-openstack-rhos10/external-ceph/ceph-ansible/roles/ceph-mon/tasks/start_monitor.yml': line 10, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: add ceph-mon systemd service overrides
  ^ here
```

Running with:
ansible 2.3.1.0
ceph-ansible commit b80ba207453b8beb9288e0b328d82e7ebd1b7fde

**Comment by leseb** [comment]
Not sure if it's related but you need to run `ceph-defaults` and `ceph-common` as well.

**Comment by satishdotpatel** [comment]
[root@ostack-osa /opt/openstack-ansible/playbooks]# openstack-ansible ceph-install.yml -l ceph-osd
Variable files: "-e @/etc/openstack_deploy/user_secrets.yml -e @/etc/openstack_deploy/user_variables.yml "
 [WARNING]: Unable to parse /var/opt/openstack-ansible/playbooks/OSA_INVENTORY_PATH/dynamic_inventory.py as an inventory source

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

 [WARNING]: Could not match supplied host pattern, ignoring: ceph-osd

[DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated. Use 'import_tasks' for static inclusions or 'include_tasks' for dynamic inclusions. This feature will be
removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: include is kept for backwards compatibility but usage is discouraged. The module documentation details page may explain more about this rationale.. This
feature will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: The use of 'static' has been deprecated. Use 'import_tasks' for static inclusion, or 'include_tasks' for dynamic inclusion. This feature will be removed in a
 future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/etc/ansible/roles/ceph-ansible/roles/ceph-mon/tasks/deploy_monitors.yml': line 22, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: create monitor initial keyring
  ^ here


The error appears to have been in '/etc/ansible/roles/ceph-ansible/roles/ceph-mon/tasks/deploy_monitors.yml': line 22, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: create monitor initial keyring
  ^ here

exception type: <class 'ansible.errors.AnsibleParserError'>
exception: no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/etc/ansible/roles/ceph-ansible/roles/ceph-mon/tasks/deploy_monitors.yml': line 22, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: create monitor initial keyring
  ^ here


EXIT NOTICE [Playbook execution failure] **************************************
===============================================================================

**Comment by xieziran784** [comment]
I have this problem. I found my  "/ceph-ansible/" not have "/plugins" and "/library". When I add them,the problem  was  solved.
