### ISSUE TITLE
low-priority: purge-cluster.yml and Amazon EC2 vms

### ISSUE THREAD

**Issue by bengland2** [ceph/ceph-ansible#1791]
purge-cluster.yml will not clean up partitions on Amazon EC2 virtual machines, which use block device names /dev/xvd[a-z]*  (Xen virtualization right? KVM uses /dev/vd*).   Amazon AWS may be low priority use-case, but never hurts to support it.  It's pretty easy to do.  For example, insert string **|xvd[a-z]{1,2}** 
in device-name-matching regular expressions and insert string **|xvd[a-z]{1,2}[0-9]{1,2}** in partition-name-matching regular expressions.

This code is getting pretty hard to read, because the regular expressions are repeated, but because of syntax it's hard to put them in variables.

**Comment by leseb** [comment]
Mind sending a PR for this?

**Comment by bengland2** [comment]
this week.

**Comment by leseb** [comment]
Thanks!

**Comment by bengland2** [comment]
pr is [1816](https://github.com/ceph/ceph-ansible/pull/1816)

**Comment by bengland2** [comment]
superceded by PR [1832](https://github.com/ceph/ceph-ansible/pull/1832)

**Comment by leseb** [comment]
I believe this can be closed indeed. Thanks for the following on this @bengland2.
