### ISSUE TITLE
Playbook not allowing using 0.0.0.0 as bind IP for rgw

### ISSUE THREAD

**Issue by OrFriedmann** [ceph/ceph-ansible#1820]
I think that we want to allow users to bind all interfaces of the rgw by using 0.0.0.0 .
We could use dummy as default ip in defaults to check if user inserted value.
I think that ceph-aio-no-vagrant.sh is not working with rgw because of this change
I can send a PR to fix this.

What do you think?

**Comment by leseb** [comment]
Please send a PR, thanks!

**Comment by guits** [comment]
Closed due to inactivity, feel free to re-open if needed. Thanks!
