### ISSUE TITLE
low-priority: don't need OS tuning in ceph tests

### ISSUE THREAD

**Issue by bengland2** [ceph/ceph-ansible#1828]
The kernel tuning in [this test file](https://github.com/ceph/ceph-ansible/blob/21b3fd2819418eb1c598521c511618983c3f966c/tests/functional/centos/7/jrn-col/group_vars/all#L15) should not be needed anymore, if it is then this is a bug in Ceph. 
 Ceph OSD unit files raise kernel.pid-max and async messenger in Luminous reduces socket count so file-max parameter should not be needed either.

**Comment by leseb** [comment]
I'd be happy to merge a PR for this Ben, thanks in advance :).

**Comment by guits** [comment]
Closed due to inactivity, feel free to re-open if needed. Thanks!
