### ISSUE TITLE
unbreak/support old installation variables or make it more clear

### ISSUE THREAD

**Issue by vasukulkarni** [ceph/ceph-ansible#1834]
With the recent merges, the 'master' ceph-ansible branch is broken due to changes to installation variables

I have been using ceph_dev,  ceph_dev_key, ceph_dev_branch and ceph-sha with ceph_origin set to 'upstream' before, That is already 4 variables.  

The recent PR which refactored the installation method actually breaks the current regression runs with uses the above variables. 
http://pulpito.ceph.com/vasu-2017-08-30_17:07:08-ceph-ansible-luminous-distro-basic-vps/

I find the new variables are bit confusing to use along with above variables which are  also set ? , so please consider unbreaking the old method or further simplying the number of variables used.

ceph_origin: repository  ( instead of 'upstream' as before )
ceph_repository: dev

**Comment by vasukulkarni** [comment]
@leseb can we make the below assumption default for upstream, It will be simpler for everyone. 'custom' is very minimal use cases, also I believe ceph_dev_key can take a default value for community. 

default values:
ceph_origin: repository
ceph_repository: community
ceph_dev_key: 'https://download.ceph.com/keys/autobuild.asc'

**Comment by andrewschoen** [comment]
I'd be +1 to adding these defaults:

```
ceph_origin: repository
ceph_repository: community
```

I don't believe ``ceph_dev_key`` is a config option at all though. I know for certain that shaman repos are not signed.

**Comment by vasukulkarni** [comment]
@leseb can we make this default now in all.yml.sample since rhcs is separated out? @yuriw FYI for the issue you asked , we will need these vars set.

**Comment by yuriw** [comment]
@cbodley @theanalyst  FYI ^

**Comment by yuriw** [comment]
@leseb can we get this backported for luminous 12.2.2 ?

**Comment by leseb** [comment]
addressed in https://github.com/ceph/ceph-ansible/pull/2076
