### ISSUE TITLE
Which one is more supported? Ceph-Ansible Docker deployment or Linux packages?

### ISSUE THREAD

**Issue by Asher256** [ceph/ceph-ansible#1857]
Hi,

We already deployed Ceph (version 11) in 6 bare-metal servers with ceph-ansible (branch stable-2.2) using Docker's Ansible playbooks 'site-docker.yml'. The deployment worked very well, thank you.

Questions:
1. Is deploying using 'site.yml' (Linux packages) more or less supported by ceph-ansible's community, compared to 'site-docker.yml' (Docker distribution)? Same support from ceph-ansible's community? What about rolling? Could we miss some features if we choose one or another?

2. What are the pros and cons of deploying 'ceph-ansible' with 'site-docker.yml' (Docker version) instead of 'site.yml' (Ubuntu/other Linux dist. packages)?

Thank you.

Cheers,
Asher256

**Comment by leseb** [comment]
1. Both have the same support and this will continue to be like this for a while.
2. If you go with containers you get some benefits from containers themselves. But at the moment we are still stabilizing the container deployment, so I'll wait for the first stable release of containers. This will happen soon.
