### ISSUE TITLE
add warnings, deprecations, or document them otherwise

### ISSUE THREAD

**Issue by alfredodeza** [ceph/ceph-ansible#1858]
This error keeps coming up from anyone not using Ansible 2.3.1:

    The conditional check 'ansible_distribution == 'Fedora'' failed. The error was: error while evaluating conditional (ansible_distribution == 'Fedora'): 'ansible_distribution' is undefined

There is nothing here that says the Ansible version is wrong. Something needs to clearly state what versions are needed for ceph-ansible to work properly.

**Comment by leseb** [comment]
like this? https://github.com/ceph/ceph-ansible/pull/1862
