### ISSUE TITLE
bump ceph-ansible pkr requirement to 2.3.1?

### ISSUE THREAD

**Issue by leseb** [ceph/ceph-ansible#1896]
@ktdreyer shouldn't we update this? https://github.com/ceph/ceph-ansible/blob/master/ceph-ansible.spec.in#L18
to 2.3.1?

Thanks!

**Comment by ktdreyer** [comment]
I never heard definitively if we require Ansible 2.3.1?

**Comment by leseb** [comment]
Oh yes we do. We don't support otherwise

**Comment by leseb** [comment]
Please send a PR :)
