### ISSUE TITLE
doc: README is incorrect about stable documentation

### ISSUE THREAD

**Issue by fghaas** [ceph/ceph-ansible#1902]
The README says:

```rst
You can view documentation for our ``stable-*`` branches by substituting ``master`` in the link
above for the name of the branch. For example: http://docs.ceph.com/ceph-ansible/stable-2.2/ 
```

... but http://docs.ceph.com/ceph-ansible/stable-2.2/ is a 404.

**Comment by leseb** [comment]
@alfredodeza could you please help with this one? Thanks!

**Comment by fghaas** [comment]
Technically this is already fixed as the 404 is now gone — but I've added #1932 in order to populate the stable docs with @andrewschoen's recent documentation additions (insofar as they are relevant to `stable-2.2`), and added a couple of patches on top of that (those, too, are only relevant to `stable-2.2`).

**Comment by guits** [comment]
Closed due to inactivity, feel free to re-open if needed. Thanks!
