### ISSUE TITLE
stable-2.2: ceph-nfs role is uninstallable on Ubuntu 16.04

### ISSUE THREAD

**Issue by fghaas** [ceph/ceph-ansible#1905]
The `ceph-nfs` role is uninstallable on Ubuntu 16.04. The `nfs-ganesha-fsal` package has a dependency on `glusterfs-common (>= 3.8.8)`, which is not in the default Ubuntu Xenial repositories, nor in any of the other PPAs that the `tasks/installs/debian_ceph_repository.yml` tasks in `ceph-common` enable.

To make `nfs-ganesha-fsal` installable, another PPA is required (`ppa:gluster/glusterfs-3.8`).

**Comment by fghaas** [comment]
Wow. `nfs-ganesha-fsal` installed from that PPA **doesn't even contain** `libfsalceph.so`. Has anyone ever used or tested this?

**Comment by fghaas** [comment]
OK, answering my own question here: the role installed packages from the wrong PPA. In addition, the autogenerated `ganesha.conf` is non-functional. I'll try to fix up a PR for this.

**Comment by leseb** [comment]
Unfortunately, we don't do much testing on Ubuntu, we only have a single scenario for that. However, it's weird since we haven't noticed any issues so far.
Looking forward to seeing your PR.

Thanks!

**Comment by fghaas** [comment]
@leseb PR is #1912.

**Comment by fghaas** [comment]
Fixed in #1912.
