### ISSUE TITLE
master: nfs-ganesha installation broken for jewel, kraken?

### ISSUE THREAD

**Issue by fghaas** [ceph/ceph-ansible#1907]
According to http://docs.ceph.com/ceph-ansible/master/, the `master` branch should support `jewel`, `kraken`, and `luminous` deployments. But it appears to try to install `nfs-ganesha` from http://download.ceph.com/nfs-ganesha/, where `nfs-ganesha` builds are only available for `luminous`.

So this is any one of the following:

- documentation bug, because `master` is in fact *not* meant to be used for deploying anything earlier than `luminous`,
- role bug, because for `jewel` and `kraken` the same approach must be applied as in `stable-2.2` (which means, including the upstream `nfs-ganesha` PPAs),
- upstream packaging bug, because the `nfs-ganesha` builds really ought to exist for all 3 releases.

**Comment by ktdreyer** [comment]
IMHO it is the latter (upstream packaging problem).

We really need nfs-ganesha builds for `jewel` and `luminous` (kraken is EOL and needs to be removed entirely from ceph-ansible).

One challenge is that nfs-ganesha 2.5 requires newer features in librgw than what `jewel` supports. Jewel has `LIBRGW_FILE_VERSION` 1.1.0, and nfs-ganesha 2.5 has `find_package(RGW 1.1.3)`. So we cannot build the 2.5 RGW FSAL with jewel; it has to be 2.4. And there are no 2.4 packages on download.ceph.com.

CephFS does not have this problem (as far as I know!)

Problems like this have made me think that we need to build and distribute ceph + nfs-ganesha via the CentOS Storage SIG and Ceph Launchpad groups so it is easier to identify and consume the matrix of supported versions.

**Comment by ktdreyer** [comment]
That sounds good to me @fghaas . @alimaredia , as the nfs-ganesha maintainer, what do you think?

**Comment by alimaredia** [comment]
@fghaas If you can remove the `nfs_obj_gw` variable entirely, and remove the part of the template in `ganesha.conf.j2`, that would be ideal. If removing `nfs_obj_gw` is too much of a pain, setting it to false with a comment saying to never turn it on works fine to.

**Comment by alimaredia** [comment]
@fghaas now that I think about it, since you're working on a pull request, it might be best to just set `nfs_obj_gw` to false instead of making a lot of changes to the code base.

**Comment by fghaas** [comment]
@alimaredia Turns out that the default for `nfs_obj_gw` already *is* `false`, so nothing to do there.

As for the rest, I've created #1935 — please look into that and let me know which of the patches you'd like to keep, and I'll fix up that branch accordingly so you can merge.

**Comment by fghaas** [comment]
Just a quick summary / status update on this one.

- For `jewel` in `stable-2.2`, `nfs-ganesha` installation now ought to be fine since #1912 has been merged.
- Also for `jewel` in `stable-2.2`, RGW NFS is gone with the merge of #1935.
- `kraken` has not been eliminated from either `master` or `stable-2.2`, but it doesn't look like it's being used in any specific fashion either — there is just no test that fails when `kraken` is selected. (Neither is there one for `hammer` or any other EOL release, mind you.)
- `master` still relies on RPM and .deb packages from https://download.ceph.com/nfs-ganesha/ which are available only on `luminous`, which means that `master` can't be used for installing `nfs-ganesha` for Jewel.

@ktdreyer or @alimaredia, can you please give me some guidance as to how to proceed here?

**Comment by alimaredia** [comment]
@fghaas  for your last bullet, we've decided not to put any jewel packages on download.ceph.com. Master can still install a nfs-ganesha from jewel, it just needs to be a development package from shaman.ceph.com.

In your 3rd bullet can you elaborate more on which references to `kraken` you're talking about?

**Comment by fghaas** [comment]
@alimaredia I'm talking to the `kraken` references in the documentation:

- http://docs.ceph.com/ceph-ansible/master/#releases
- http://docs.ceph.com/ceph-ansible/stable-2.2/#releases

**Comment by guits** [comment]
Closed due to inactivity, feel free to re-open if needed. Thanks!
