### ISSUE TITLE
stable-2.2: ceph-common role creates invalid nfs-ganesha configuration

### ISSUE THREAD

**Issue by fghaas** [ceph/ceph-ansible#1909]
The `ganesha.conf` template, `roles/ceph-common/templates/ganesha.conf.j2`, will not create a working nfs-ganesha configuration.

According to https://github.com/nfs-ganesha/nfs-ganesha/issues/146#issuecomment-287348793, the `NFS_Protocols` and `Transport_Protocols` are wrong. https://github.com/nfs-ganesha/nfs-ganesha/blob/master/src/config_samples/config.txt confirms this.

**Comment by leseb** [comment]
Thanks for reporting this, it looks like master is also suffering from this. I'd be happy to merge a PR for this.
@alimaredia, fyi.

**Comment by fghaas** [comment]
@leseb In `master`, `ganesha.conf.j2` correctly generates `Protocols` and `Transports`.

**Comment by alimaredia** [comment]
@fghaas I highly recommend you use ceph-ansible 3.0 (once it's released) for using nfs-ganesha and Ceph. As you can see from master, I made quite a few changes to the nfs-ganesha related code in ceph-ansible. If you have any issues or questions feel free to ask me.

**Comment by fghaas** [comment]
Yeah but it's not released yet, sorry. I can't use unreleased code for production systems. That's precisely why I'm sending fixes for the stable branch.

**Comment by alimaredia** [comment]
@fghaas Understood, just wanted to let you know for the future. As Sebastian said, if you open up a pull request with the fix I would be glad to merge it.

**Comment by fghaas** [comment]
@alimaredia #1912

**Comment by fghaas** [comment]
Fixed in #1912.
