### ISSUE TITLE
docker task "pull ceph daemon image" needs a timeout and a retry

### ISSUE THREAD

**Issue by fultonj** [ceph/ceph-ansible#1954]
If the "pull ceph daemon image" task [1] gets hung, then the playbook can hang. Sometimes just re-running the docker pull resolve the issue however. Could an Ansible until, retries, and delays be added to this task so that it doesn't hang the playbook? 

[1] https://github.com/ceph/ceph-ansible/blob/c6728ca21d93d88818bfcf0426c4f00e48da3500/roles/ceph-common/tasks/docker/fetch_image.yml#L2-L6

**Comment by fultonj** [comment]
@jtaleric

**Comment by jtaleric** [comment]
I will submit a pr for this : 
```
# Normal case - pull image from registry
- name: "pull {{ ceph_docker_image }} image"
  command: "timeout 300s docker pull {{ ceph_docker_registry}}/{{ ceph_docker_image }}:{{ ceph_docker_image_tag }}"
  changed_when: false
  register: docker_image
  when: ceph_docker_dev_image is undefined or not ceph_docker_dev_image
  until: docker_image.rc == 0
  retries: 3
  delay: 10
```

**Comment by leseb** [comment]
@fultonj @jtaleric any update on this? stable 3.0 is this week and I'd like to have this one in.

**Comment by jtaleric** [comment]
@leseb https://github.com/ceph/ceph-ansible/pull/2071
