### ISSUE TITLE
Busy mon breaks cluster

### ISSUE THREAD

**Issue by logan2211** [ceph/ceph-ansible#1970]
In a CD environment where /etc/ceph-fetch is generated on the fly each run, a busy mon/down mon can really break the cluster due to the connect-timeout specified here: https://github.com/ceph/ceph-ansible/blob/0da6d8e3565867de146e8e5e5a92d5cd250f91b3/roles/ceph-defaults/tasks/facts.yml#L18

If the mon queried cannot respond quickly enough, you will get a rc = 1 and ```RuntimeError: "None": exception "['{"prefix": "get_command_descriptions"}']": exception You cannot perform that operation on a Rados object in state configuring``` output. This means you will now be generating a new mon keyring here https://github.com/ceph/ceph-ansible/blob/0da6d8e3565867de146e8e5e5a92d5cd250f91b3/roles/ceph-common/tasks/main.yml#L89 and it also means you will be generating a new fsid here: https://github.com/ceph/ceph-ansible/blob/0da6d8e3565867de146e8e5e5a92d5cd250f91b3/roles/ceph-defaults/tasks/facts.yml#L72

This could really wreck the cluster. There should probably be a combination of fixes to prevent this situation:
- don't just test cluster existence by `ceph fsid`, use stat, check ceph.conf, or some other way that doesn't require a timeout to check for existing clusters.
- Fail if it looks like a fsid may already exist & generation is enabled to avoid generating a new one.
- Don't depend on generated fsid to run the tasks checking for an existing mon keyring. Currently if it can't detect a fsid, it won't check for existing mon keyring to download.

Generally, better testing could help with this--
build a cluster, rm ceph-fetch directory, stop mon, run playbooks?

**Comment by leseb** [comment]
What about increasing the timeout?

**Comment by leseb** [comment]
Unfortunately, we are really bound to this fetch directory. We have to find a way to live without it at some point.

**Comment by guits** [comment]
Closed due to inactivity, feel free to re-open if needed. Thanks!
