### ISSUE TITLE
How to replace a failed OSD with BlueStore the "ceph-ansible" way

### ISSUE THREAD

**Issue by acomisario** [ceph/ceph-ansible#1972]
Hi, i have a 160 OSD ceph Luminous deploy with Bluestore made with Ceph-Ansible.

the osd.yml is defined as follow.

devices:
  - /dev/sdb
  - /dev/sdc
  - /dev/sdd
  - /dev/sde
  - /dev/sdf
  - /dev/sdg
  - /dev/sdh
  - /dev/sdi
  - /dev/sdj
  - /dev/sdk
  - /dev/sdl
  - /dev/sdm
  - /dev/sdn
  - /dev/sdo
  - /dev/sdp
  - /dev/sdq
  - /dev/sdr
  - /dev/sds
  - /dev/sdt
  - /dev/sdu
  - /dev/sdv
  - /dev/sdw
  - /dev/sdx

dedicated_devices:
  - /dev/sdb
  - /dev/sdc
  - /dev/sdd
  - /dev/sde
  - /dev/sdf
  - /dev/nvme0n1
  - /dev/nvme1n1
  - /dev/nvme0n1
  - /dev/nvme1n1
  - /dev/nvme0n1
  - /dev/nvme1n1
  - /dev/nvme0n1
  - /dev/nvme1n1
  - /dev/nvme0n1
  - /dev/nvme1n1
  - /dev/nvme0n1
  - /dev/nvme1n1
  - /dev/nvme0n1
  - /dev/nvme1n1
  - /dev/nvme0n1
  - /dev/nvme1n1
  - /dev/nvme0n1
  - /dev/nvme1n1

bluestore_wal_devices:
  - /dev/sdb
  - /dev/sdc
  - /dev/sdd
  - /dev/sde
  - /dev/sdf
  - /dev/nvme0n1
  - /dev/nvme1n1
  - /dev/nvme0n1
  - /dev/nvme1n1
  - /dev/nvme0n1
  - /dev/nvme1n1
  - /dev/nvme0n1
  - /dev/nvme1n1
  - /dev/nvme0n1
  - /dev/nvme1n1
  - /dev/nvme0n1
  - /dev/nvme1n1
  - /dev/nvme0n1
  - /dev/nvme1n1
  - /dev/nvme0n1
  - /dev/nvme1n1
  - /dev/nvme0n1
  - /dev/nvme1n1

As you can see, all OSD have block.wal and block.db on nvme (the first ones are SSD, so they have those into their own disks, the rest are SATA and SAS).

Device sdx failed on one of the nodes (OSD # 104)
I was thnking about doing a "ceph crush reweight" until 0% then bringing down the OSD daemon to how-swap it.

After that, who can please tell me what's the best practice to re-add the OSD to the cluster using ceph-ansible again ?

Much apreciate it.

**Comment by acomisario** [comment]
hi guys, any help ?

this is really important for me to know, since i dont want that when starting to do normal maintenance, things wont break by the time i need to add new resources.

best.

**Comment by acomisario** [comment]
Hi, should i do this http://docs.ceph.com/docs/master/rados/operations/add-or-rm-osds/#replacing-an-osd and not worring about later ceph-ansible runs ?

anyone ?

**Comment by leseb** [comment]
@acomisario yes please follow the doc you mentioned and don't worry about ceph-ansible new runs. We could actually build a playbook to replace a disk, I'm just not sure if this is needed due to the fact you only have a single command to type.
I might have a quick prototype for this soon.

**Comment by acomisario** [comment]
@leseb thanks for the reply.

In my case what im using right now on that OSD is this :

root@ndc-cl-osd4:~# ls -lsah /var/lib/ceph/osd/ceph-104
total 64K
   0 drwxr-xr-x  2 ceph ceph  310 Sep 21 10:56 .
4.0K drwxr-xr-x 25 ceph ceph 4.0K Sep 21 10:56 ..
   0 lrwxrwxrwx  1 ceph ceph   58 Sep 21 10:30 block -> /dev/disk/by-partuuid/0ffa3ed7-169f-485c-9170-648ce656e9b1
   0 lrwxrwxrwx  1 ceph ceph   58 Sep 21 10:30 block.db -> /dev/disk/by-partuuid/5873e2cb-3c26-4a7d-8ff1-1bc3e2d62e5a
   0 lrwxrwxrwx  1 ceph ceph   58 Sep 21 10:30 block.wal -> /dev/disk/by-partuuid/aed9e5e4-c798-46b5-8243-e462e74f6485

block.db and block.wal are on two different NVME partitions, witch are nvme1n1p17 and nvme1n1p18 so assuming after hot swaping the device, the drive letter is "sdx" according to the link above what would be the right command to re-use the two NVME partitions for block db and wal ?

I presume that everything else is the same.
best.

**Comment by leseb** [comment]
Hope you got your response somehow sorry for not replying earlier.
I'm closing this.
