### ISSUE TITLE
[ Documentation request ] - Use the playbook without Vagrant

### ISSUE THREAD

**Issue by theonlydoo** [ceph/ceph-ansible#199]
Is it possible to produce a simple "howto" (vars to uncomment, etc.) inside the Wiki ? It might be painful to read all the playbook to push a ceph cluster for the first time.

**Comment by leseb** [comment]
Sure, I know the doc is really basic, sorry about that I'll push something soon.

**Comment by leseb** [comment]
Is it enough to start?

**Comment by leseb** [comment]
Is it enough to start? https://github.com/ceph/ceph-ansible/wiki

**Comment by theonlydoo** [comment]
more than enough, it's perfect to start. 
Thank you very much ! :+1:

**Comment by prithivm** [comment]
The ansible playbook hangs at the following step:

NOTIFIED: [ceph-common | restart ceph mons] ***********************************

I have to stop the run and re-run it everytime. The manual run of the command in the mon node says the binary /usr/bin/ceph-mon not found.

Is this a known issue. Or am i missing something

**Comment by leseb** [comment]
@prithivm please open a different issue, this doesn't sound right.
It looks like Ceph didn't get installed which I hardly doubt about.
