### ISSUE TITLE
Wrong path for osd_fragment.yml

### ISSUE THREAD

**Issue by rrmichel** [ceph/ceph-ansible#1996]
Path should be  ../osd_fragment.yml

https://github.com/ceph/ceph-ansible/blob/163c87af7937acd4401fed6ea15b82b0cb06c0c6/roles/ceph-osd/tasks/docker/main.yml#L3

**Comment by leseb** [comment]
Thanks for reporting this, do you mind sending a PR to fix that? 
Thanks!

**Comment by rrmichel** [comment]
here we are #1997
