### ISSUE TITLE
Option to disable  "Handlers - restarting daemons after a config change" ?

### ISSUE THREAD

**Issue by mistur** [ceph/ceph-ansible#2007]
Is that possible to disable "## Handlers - restarting daemons after a config change" ?

I'm doing some test about config generation and it takes more than 40min to run the playbook because of the restart of the 40 OSDs, which is quite long in my case. 

Thx

Yoann

**Comment by leseb** [comment]
Not possible and I don't think it'll ever be.

**Comment by mistur** [comment]
so doing something like that is not possible ? (it a quick and dirt stuff, can definitely be better)
https://github.com/EPFL-IC/ceph-ansible/commit/ca7b7977ce8737505385d617d7eeba08c59bec41

**Comment by leseb** [comment]
@mistur feel free to submit a PR and we will discuss this further, thanks!

**Comment by guits** [comment]
Closed due to inactivity, feel free to re-open if needed. Thanks!
