### ISSUE TITLE
ceph-ansible needs to allow configuring PG for metadata and data pools

### ISSUE THREAD

**Issue by batrick** [ceph/ceph-ansible#2017]
The metadata pool often uses far fewer PG than the data pool. The `osd_pool_default_pg_num` parameter is inappropriate for this.

**Comment by leseb** [comment]
Ok so I think we should add one variable for the metadata pool only.

**Comment by leseb** [comment]
And btw I'm not if this should be marked as a bug... This is more an improvement to me.

**Comment by batrick** [comment]
TBH, I'm not thrilled by the presence of `osd_pool_default_pg_num `. There is no good default for placement groups -- it's the most challenging admin config option in the whole of Ceph. Deployment which includes setting up pools should require deliberate choice of PG for each pool.

Can we somehow require the user to specify the pools to create and the PGs for each pool? That would need to be done as a prereq for creating the file system (`ceph fs new`).

**Comment by leseb** [comment]
Makes sense, let me work on something on that regard.
Thanks for the input.

**Comment by zmc** [comment]
Any docs mentioning the addition of another mandatory var?

**Comment by leseb** [comment]
@zmc nop :/, looks like we forgot that.
