### ISSUE TITLE
stable-2.2: Botched backport in take-over-existing-cluster.yml

### ISSUE THREAD

**Issue by fghaas** [ceph/ceph-ansible#2033]
In the `stable-2.2` branch, the `take-over-existing-cluster.yml` playbook has apparently been broken since 4639d8923 (a backport of #1330). For `master`, @djgalloway fixed this in 40ed2d7be613caa66faa5ab2ff33a0859e088428, but that fix was evidently never backported.

**Comment by guits** [comment]
Closed due to inactivity, feel free to re-open if needed. Thanks!
