### ISSUE TITLE
Vagrant on VirtualBox: no virtualbox guest modules in ceph/ubuntu-xenial

### ISSUE THREAD

**Issue by wildy** [ceph/ceph-ansible#2049]
Hi.

I decided to spin up a Vagrant environment for testing, and at present it seems like VMs can't start because there are no VirtualBox guest modules available in ceph/ubuntu-xenial box.

'vagrant up' fails with the following output:
```
    client0: /vagrant => /home/ygorshkov/smlabs/ansible/ceph-ansible-lum-migration
Failed to mount folders in Linux guest. This is usually because
the "vboxsf" file system is not available. Please verify that
the guest additions are properly installed in the guest and
can work properly. The command attempted was:

mount -t vboxsf -o uid=`id -u vagrant`,gid=`getent group vagrant | cut -d: -f3` vagrant /vagrant
mount -t vboxsf -o uid=`id -u vagrant`,gid=`id -g vagrant` vagrant /vagrant

The error output from the last command was:

mesg: ttyname failed: Inappropriate ioctl for device
mount: unknown filesystem type 'vboxsf'
```

**Comment by wildy** [comment]
Seems like the `vboxsf` modules doesn't get loaded on boot.

**Comment by guits** [comment]
@wildy what about `vagrant plugin install vagrant-vbguest` ?

**Comment by wildy** [comment]
Works, but I'm curious why the ceph/ubuntu-xenial box doesn't have it installed from apt.
It definitely has the vboxsf module, and I can modprobe it.
