### ISSUE TITLE
VLAN interfaces break ceph.conf template 

### ISSUE THREAD

**Issue by cultcom** [ceph/ceph-ansible#205]
TASK: [ceph-common | Generate Ceph configuration file] ************************ 
fatal: [ceph04] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'dict object' has no attribute 'ansible_bond0.1062'", 'failed': True}
fatal: [ceph04] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'dict object' has no attribute 'ansible_bond0.1062'", 'failed': True}

**Comment by leseb** [comment]
Hum I thought I fixed that a while ago...
Can you try something for me?

Replace this line https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-common/templates/ceph.conf.j2#L80

By:
mon addr = {{ hostvars[host]['ansible_' + monitor_interface].ipv4.address }}

And try again.

**Comment by leseb** [comment]
One more thing, do you the interface when collecting facts?

**Comment by cultcom** [comment]
Do I what when collecting facts?

I changed the template line according to your suggestions but the error keeps comming

**Comment by leseb** [comment]
Arf sorry, I updated my previous comment.

Same error?
Ok I don't have anything to test this right now, I'll update this next week.

**Comment by cultcom** [comment]
yes, the interfaces shows up. The quote of my first message was directly from the "setup" module.

**Comment by leseb** [comment]
Ok waiting for Ansible to fix this then.

**Comment by leseb** [comment]
It doesn't look like you're getting a lot attention on that bug... :-(

**Comment by cultcom** [comment]
no, I guess not.

**Comment by leseb** [comment]
Just used: `monitor_interface: bond1.2108` and it works.
ansible 1.9.1

**Comment by leseb** [comment]
Closing, feel free to re-open.
