### ISSUE TITLE
utilizing wasted space on SSD journal devices

### ISSUE THREAD

**Issue by bengland2** [ceph/ceph-ansible#2077]
Yet another suggestion... just what you need!  ;-) It would be great if Ceph-ansible could add the unused space on SSD journal devices in the form of OSDs with a distinguishable storage class so that storage pools could be created with this space.  An example of this might be OpenStack telemetry "metrics" storage pool, which requires very little space but a lot of IOPS for large deployments.    This would not require creation of crush rules or storage pools -- system admins (such as OpenStack OOO) can easily do that with Luminous after the Ceph cluster is deployed, as long as there is a unique device class for this storage.  ceph-ansible could just create SSD partitions out of the unused space and make them into collocated OSDs.  Ideally this would be done only if the user specified some var in osds.yml that specified the requested partition size.  Does ceph-disk support use of a SSD partition to create an OSD?  ceph-volume?

**Comment by leseb** [comment]
This would mean bringing back the "osd partition" support in ceph-ansible. Not impossible, but requires work.

**Comment by bengland2** [comment]
Not if you used LVM volumes and ceph-volume!

**Comment by bengland2** [comment]
The new ceph-volume lvm batch could be compatible with this, provided that you specify the bluestore_block_db_size parameter in ceph_conf_overrides to be less than the default, which is to use the entire device.  IMHO there will be many cases where a customer does not want to use all of their multi-terabyte SSD space for RocksDB.

**Comment by bengland2** [comment]
now that we seem to be moving to an all-flash world, this is less of a concern.   Haven't heard any complaints lately about it.
