### ISSUE TITLE
RGW : "rgw dns name" directive missing in ceph.conf ?

### ISSUE THREAD

**Issue by mistur** [ceph/ceph-ansible#2085]
I don't fine any reference in the playbook about "rgw dns name" directive, is there another way to do that ? 

even with 
`radosgw_resolve_cname: true # enable for radosgw to resolve DNS CNAME based bucket names` 

I can't access to buckets with ${bucket}.${radosgw_dns_name} fqdn 

Yoann

**Comment by fbarbeira** [comment]
The file 'group_vars/all.yml' has the variable defined:

```
group_vars/all.yml.sample:#radosgw_dns_name: your.subdomain.tld # subdomains used by radosgw. See http://ceph.com/docs/master/radosgw/config/#enabling-subdomain-s3-calls
```

But even if you specify a value in the 'all.yml' file, it's not applied to the final 'ceph.conf' file, you have to do it manually. It looks like a bug because in the template it's not defined.

**Comment by leseb** [comment]
Looks like a leftover to me, we remove it in a pending PR.
If you want to use it, apply `ceph_conf_overrides` to your rgw nodes.

See examples here: https://github.com/ceph/ceph-ansible/blob/master/profiles/
