### ISSUE TITLE
test ceph-ansible with Ansible 2.4

### ISSUE THREAD

**Issue by ktdreyer** [ceph/ceph-ansible#2087]
RHEL 7 Extras has Ansible 2.4.0.0, and CentOS Extras will soon follow after that.

We should have Jenkins validate that 2.4.0.0 works. Looks like tox.ini only tests ansible 2.2 and 2.3 at the moment.

**Comment by leseb** [comment]
Does that mean, stable-3.0 must work with Ansible 2.4.x?

**Comment by ktdreyer** [comment]
Yes
