### ISSUE TITLE
playbook fails if mon_use_fqdn is false, but /etc/hostname is fqdn

### ISSUE THREAD

**Issue by megian** [ceph/ceph-ansible#2089]
The playbook stops, because the status file /var/run/ceph/ceph-mon.<hostname>.asok can not be recognized because it will be created as /var/run/ceph/ceph-mon.<hostname><dns-name>.asok. The playbook should precheck it or us the right variable to check the status file.

**Comment by guits** [comment]
Closed due to inactivity, feel free to re-open if needed. Thanks!
