### ISSUE TITLE
[question] osd on device and journal on a partition

### ISSUE THREAD

**Issue by fentas** [ceph/ceph-ansible#2101]
I have 3 dedicated root servers with 2x3TB devices each. Am I able to use a device (/dev/sdb) as osd and a partition (on /dev/sda) for the journal?
Also, can I deploy mons, rgws and mdss (for cephfs) on each /dev/sda?

Any help (configuration examples) would be appreciated. Thanks.

**Comment by leseb** [comment]
You can use /dev/sdb by collocating data and journal. Using a partition for the journal on /dev/sda (if sda is already occupied if not possible.

mons, rgws and mdss (for cephfs) don't need drives so just declare them in your inventory file.
Also please have a look at the doc: http://docs.ceph.com/ceph-ansible/master/

**Comment by leseb** [comment]
We don't test this scenario in ceph-ansible but I believe it'll work, ceph-disk looks for available space on /dev/sda, if it does it'll create a partition on it.
