### ISSUE TITLE
Best branch way to deploy Ceph Luminous

### ISSUE THREAD

**Issue by Asher256** [ceph/ceph-ansible#2138]
Hi,

What is the most stable branch to deploy Ceph version 'luminous'?
- stable-2.2
- stable-3.0

What's the difference between the branch 2.2 and 3.0?

Thanks in advance.

Asher256

**Comment by guits** [comment]
@Asher256 The last stable branch is 3.0, this branch has obviously more feature and bugfix. If you start deploying ceph you should definitely use stable-3.0.

**Comment by Asher256** [comment]
Thank you for the fast answer. We will use 'stable-3.0' to deploy Ceph luminous.
