### ISSUE TITLE
For non containerized_deployment,  osd_crush_location cannot be set

### ISSUE THREAD

**Issue by mslovy** [ceph/ceph-ansible#2139]
we set those in the inventory like below:

[osds]
cephsata-0-rack2-1 ceph_crush_root=HDD ceph_crush_pod=HDD-Replication-Domain-0 ceph_crush_rack=HDD-RACK-2
cephsata-1-rack3-1 ceph_crush_root=HDD ceph_crush_pod=HDD-Replication-Domain-0 ceph_crush_rack=HDD-RACK-3
cephsata-2-rack4-1 ceph_crush_root=HDD ceph_crush_pod=HDD-Replication-Domain-0 ceph_crush_rack=HDD-RACK-4

and  enable the param:
crush_location: true
osd_crush_location: "\"root={{ ceph_crush_root }} rack={{ ceph_crush_rack }} host={{ ansible_hostname }}\""

however, osd_crush_location is not properly set for each osd. I find the code in master just config osd_crush_location for containerized_deployment, am I miss something or something wrong here, thanks?

**Comment by guits** [comment]
Closed due to inactivity, feel free to re-open if needed. Thanks!
