### ISSUE TITLE
osd_directory option is gone.

### ISSUE THREAD

**Issue by jarkomes** [ceph/ceph-ansible#2162]
Hello,

In the previous versions of Ceph Ansible, we had the option to use a dir as our osd with the following options:
osd_directory: true
osd_directories:
  - /dataosd_directory: true
osd_directories:
  - /data

It looks like this option does not exist anymore in the latest instalment? 3.0.9? Is this intended? Any good workaround available maybe then?

Kr,
Jarkomes

**Comment by alfredodeza** [comment]
@jarkomes what was your use case for using directories? The most common usage we saw was non-device OSDs for testing or trying Ceph out, which is the reason we decided to remove it. The PR that removed it is here https://github.com/ceph/ceph-ansible/pull/1461

Depending on what you were using directories we can try and get a recommendation for you.

**Comment by jarkomes** [comment]
Hello,

We use Ceph with osd_dir on our baremetal kubernetes clusters so we can utilise the space normally lost in the cluster as persistent storage for apps to write crash logs etc (functions which do not need high speed/ high available storage.)

**Comment by alfredodeza** [comment]
The OSD directory was really just meant for testing and never for production use. As of Luminous, the alternative would be to use LVM. It would make it easier to manage volumes and unused space, and you can expand or contract the available space from the group.

The ceph-ansible integration is described here: http://docs.ceph.com/ceph-ansible/master/osds/scenarios.html#lvm

Going to close this as we don't consider an issue.
