### ISSUE TITLE
radosgw socket is wrongly hardcoded 

### ISSUE THREAD

**Issue by gmihaiescu** [ceph/ceph-ansible#217]
The socket name is hardcoded in rgw.conf as "/tmp/radosgw.sock", but with the latest changes the rados gw socket in ceph.conf.j2 is defined as "rgw socket path = /tmp/radosgw-{{ hostvars[host]['ansible_hostname'] }}.sock", so the fastcgi doesn't work because if cannot find the socket.

The socket in "https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-radosgw/templates/rgw.conf" should be defined as below:

FastCgiExternalServer /var/www/s3gw.fcgi -socket /tmp/radosgw-{{ ansible_hostname }}.sock 

Thank you for the playbook, it helps a lot with the initial deployment.

**Comment by leseb** [comment]
Thanks for reporting this :)
I"ll fix  /var/www/s3gw.fcgi at the same time.

Sorry for the inconvenience.
