### ISSUE TITLE
firewalld needs to be disabled on Centos 7.4 and ceph ansible stable 3.0

### ISSUE THREAD

**Issue by Masber** [ceph/ceph-ansible#2192]
ceph cluster ends in ERROR state due to firewalld is blocking OSDs traffic. Several errors like 

> 2017-11-17 10:18:12.101651 7fb658ccb700 -1 osd.0 71 heartbeat_check: no reply from 10.0.32.58:6815 osd.7 ever on either front or back, first ping sent 2017-11-16 19:22:44.900585 (cutoff 2017-11-17 10:17:52.101594)

can be seen in the log files.

as a work around firewalld can be disabled

**Comment by leseb** [comment]
This is not a ceph-ansible issue. At present, this is your own responsibility to configure firewalls. We are targetting 3.1 to configure firewalld if available on the system.

**Comment by eduardegorov** [comment]
@leseb Hi, Sebastien! You might be interested on how we implemented it - please see https://github.com/ceph/ceph-ansible/pull/2196

**Comment by guits** [comment]
Closed due to inactivity, feel free to re-open if needed. Thanks!
