### ISSUE TITLE
Question: Crush location per device

### ISSUE THREAD

**Issue by symptog** [ceph/ceph-ansible#2198]
Hello,

is it possible to define a crush location per device?
I've got hosts with mixed devices (HDD & SSD) and I want to create two rule sets. therefor I need to separate the devices per host.

Or does ceph this automatically per device class?

If there is no such option I will have to write these task by my own using
http://docs.ceph.com/docs/master/rados/operations/crush-map/#device-classes
http://docs.ceph.com/docs/master/rados/operations/crush-map/#modifying-the-crush-map

Does ceph-ansible gathers the osd facts so that I would know which device got which osd num?

Thank you and best regards.

**Comment by eduardegorov** [comment]
Hi @symptog ,

As far as I understand, currently, there is no possibility to define individual crush location per device because 'osd_crush_location' variable is per-host one.
I'm not familiar enough with "device classes" concept but according to the link you provided it seems to be a possible solution for your issue (I assume you are on Luminous or higher).

**Comment by vishalkanaujia** [comment]
@symptog I too had a similar situation of using HDDs and SSDs in Luminous cluster. I did not use device class feature though, and used a solution as follows:

- Create osd group for each type of device you plan to add under `group_var/`, e.g. `group_var/osd_group_ssd, group_var/osd_group_nvme, group_var/osd_group_hdd`. Define the CRUSH, journal config etc under these files.
- In group_var/all.yml, specify a list of osd groups.
```
  osd_group_name:
   - osd_group_ssd
   - osd_group_hdd
   - osd_group_nvme
```
- Under your inventory hosts, specify osds as follows:
```
[osds] 
osd_group_hdd 
osd_group_ssd
osd_group_nvme

[osd_group_hdd]
x.x.x.x
[osd_group_ssd]
y.y.y.y
[osd_group_nvme]
z.z.z.z
```

Hope it helps!

**Comment by leseb** [comment]
@symptog we don't have that kind of support at the moment, we might, I'm just not sure when this will get implemented.

**Comment by symptog** [comment]
Sorry for not replying.
Ceph does a really good job in creating crush maps. It automatically created "virtual" maps for ssd and hdd.

**Comment by leseb** [comment]
@symptog this is now possible btw if you use Luminous.

**Comment by alikhajeh1** [comment]
@leseb can you possibly outline how this can be done with ceph-ansible, or point me to the doc pages I can find this in? I tried @vishalkanaujia's [workaround](https://github.com/ceph/ceph-ansible/issues/2198#issuecomment-350242385) but I ended-up with the same results as [this](https://github.com/ceph/ceph-ansible/issues/2435) (i.e. the SSD root bucket wasn't used at all).

**Comment by leseb** [comment]
@alikhajeh1 I guess this requires https://github.com/ceph/ceph-ansible/pull/2440 for now, but there have been very few activities on this one. Not sure when we will be able to resume.
