### ISSUE TITLE
Can we set "enable extras repo for centos" task to variable?

### ISSUE THREAD

**Issue by k0ste** [ceph/ceph-ansible#2199]
https://github.com/ceph/ceph-ansible/blob/3c6f2854feb9c46ab1e1ccd3ed0fde650b01bcfa/roles/ceph-osd/tasks/pre_requisite.yml#L2-L9

Because I actually don't need this task due self mirrored centos/epel/ceph repos and repos configured via my ansible `yum` role.

I PR if this okay for `ceph-ansible`.
Thanks.

**Comment by guits** [comment]
@k0ste this task is just a leftover and can be simply removed.

see #2202

**Comment by k0ste** [comment]
Nice.
