### ISSUE TITLE
Change in ceph_conf_overrides causes OSD daemons to restart

### ISSUE THREAD

**Issue by spolat-hps** [ceph/ceph-ansible#2205]
We deployed a Ceph cluster using Ceph-ansible, all works fine.

Once the cluster was running we made some changes in the all.yml in the ceph_conf_overrides block and ran the playbook (site.yml) again and see that (all) OSD daemons + MONs are being restarted.

Is this expected behavior? A restart of the daemons + mons could cause interruption and data corruption.

**Comment by guits** [comment]
@spolat-hps what kind of change did you make?

**Comment by spolat-hps** [comment]
@guits 

We added the following to all.yml:

ceph_conf_overrides: 
  mon:
    log_to_syslog: true
    err_to_syslog: true
    clog_to_syslog: true
    mon_cluster_log_to_syslog: true
  osd:
    log_to_syslog: true
    err_to_syslog: true

**Comment by guits** [comment]
@spolat-hps In that case I guess this is expected the osd + mon are restarted. However, they shouldn't be restarted all at the same time, is it what you observed?

**Comment by spolat-hps** [comment]
@guits I am not sure if they are being restarted exactly at the same time. Where can I find the "restart logs" of the mons and OSD deamons?

I was able to find the following:
ceph.log-20171122:2017-11-21 17:03:02.010287 mon.0 10.26.12.91:6789/0 22 : cluster [INF] osd.15 marked itself down
ceph.log-20171122:2017-11-21 17:03:02.025923 mon.0 10.26.12.91:6789/0 23 : cluster [INF] osd.1 marked itself down
ceph.log-20171122:2017-11-21 17:03:02.027461 mon.0 10.26.12.91:6789/0 24 : cluster [INF] osd.11 marked itself down
ceph.log-20171122:2017-11-21 17:03:02.052912 mon.0 10.26.12.91:6789/0 25 : cluster [INF] osd.0 marked itself down

So only 4 OSD deamons were restarted, but they restarted at the same time...

**Comment by guits** [comment]
@spolat-hps could you please provide : 
- content of group_vars/*  (`grep -Ev '(^$|^#)' group_vars/*.yml`)
- inventory host file
- the full playbook run log
- ceph-ansible version used for this deployment and ansible version

**Comment by guits** [comment]
Closed due to inactivity, feel free to re-open if needed. Thanks!
