### ISSUE TITLE
default to ceph-volume

### ISSUE THREAD

**Issue by alfredodeza** [ceph/ceph-ansible#2213]
Once luminous 12.2.2 is released, ceph-disk will be officially deprecated: https://github.com/ceph/ceph/pull/18989

Defaulting to ceph-volume should be the new norm, unless explicitly requested by a user. There are just a few corners were ceph-disk is still a viable option: anything regarding encryption.

Encryption support is coming to ceph-volume at some point, but in the meantime, all other functionality has feature parity.

This might create some usability concerns to ceph-ansible since the mappings for devices for ceph-volume differs from that of ceph-disk scenarios.

**Comment by alfozan** [comment]
warning is still there with the mimic 13 release
_"This tool is now deprecated in favor of ceph-volume.\nIt is recommended to use ceph-volume for OSD deployments"_

**Comment by alfredodeza** [comment]
@alfozan the schedule changed to keep ceph-disk in Luminous without deprecation (the warning was removed) and added on Mimic, ceph-disk is no longer an option in Ceph's master which will end up being Nautilus

**Comment by alfredodeza** [comment]
Closing in favor of https://github.com/ceph/ceph-ansible/issues/2622
