### ISSUE TITLE
Setting ceph_conf_overrides fails with TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by Idix** [ceph/ceph-ansible#2225]
Hi,

After setting ceph_conf_override like this, I get an error while creating ceph.conf file.
```yml
ceph_conf_overrides:
  global:
    osd_pool_default_pg_num: 128
```
Without this setting it works flawlessly. I'm using latest version of ceph-ansible from master and latest version of Ansible.

Here is the stacktrace.
> TASK [ceph-config : generate ceph configuration file: ceph.conf] **************************************************************************************************************************************************
> task path: /home/login/workspace/prov-openstack/ceph-ansible/roles/ceph-config/tasks/main.yml:30
> <ceph-01> ESTABLISH SSH CONNECTION FOR USER: debian
> <ceph-01> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=120s -F ssh/ssh-config -o StrictHostKeyChecking=no -o 'IdentityFile="/home/login/workspace/prov-openstack/ssh/cloud.key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=debian -o ConnectTimeout=10 -o ControlPath=/home/login/.ansible/cp/709e12873e ceph-01 '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
> <ceph-01> (0, b'/home/debian\n', b'')
> <ceph-01> ESTABLISH SSH CONNECTION FOR USER: debian
<ceph-01> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=120s -F ssh/ssh-config -o StrictHostKeyChecking=no -o 'IdentityFile="/home/login/workspace/prov-openstack/ssh/cloud.key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=debian -o ConnectTimeout=10 -o ControlPath=/home/login/.ansible/cp/709e12873e ceph-01 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo > /home/debian/.ansible/tmp/ansible-tmp-1512055922.3672817-183758455777248 `" && echo ansible-tmp-1512055922.3672817-183758455777248="` echo /home/debian/.ansible/tmp/ansible-tmp-1512055922.3672817-183758455777248 `" ) && sleep 0'"'"''
> <ceph-01> (0, b'ansible-tmp-1512055922.3672817-183758455777248=/home/debian/.ansible/tmp/ansible-tmp-1512055922.3672817-183758455777248\n', b'')
> [DEPRECATION WARNING]: ansible.utils.unicode.to_bytes is deprecated.  Use ansible.module_utils._text.to_bytes instead. This feature will be removed in version 2.4. Deprecation warnings can be disabled by
> setting deprecation_warnings=False in ansible.cfg.
> [DEPRECATION WARNING]: ansible.utils.unicode.to_unicode is deprecated.  Use ansible.module_utils._text.to_text instead. This feature will be removed in version 2.4. Deprecation warnings can be disabled by
> setting deprecation_warnings=False in ansible.cfg.
> The full traceback is:
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/dist-packages/ansible/executor/task_executor.py", line 130, in run
>     res = self._execute()
>   File "/usr/local/lib/python3.6/dist-packages/ansible/executor/task_executor.py", line 528, in _execute
>     result = self._handler.run(task_vars=variables)
>   File "/home/login/workspace/prov-openstack/ceph-ansible/plugins/actions/_v2_config_template.py", line 534, in run
>     list_extend=_vars.get('list_extend', True)
>   File "/home/login/workspace/prov-openstack/ceph-ansible/plugins/actions/_v2_config_template.py", line 284, in return_config_overrides_ini
>     config_object = io.BytesIO(str(resultant))
> TypeError: a bytes-like object is required, not 'str'
> fatal: [ceph-01]: FAILED! => {
>     "msg": "Unexpected failure during module execution.",
>     "stdout": ""
> }

Also attached is the full log output.

Ansible and Python version.
> ansible-playbook 2.4.2.0
>   config file = /home/login/workspace/prov-openstack/ansible.cfg
>   configured module search path = ['/home/login/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
>   ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
>   executable location = /usr/local/bin/ansible-playbook
>   python version = 3.6.3 (default, Oct  3 2017, 21:16:13) [GCC 7.2.0]

Thanks.
[full-log.txt](https://github.com/ceph/ceph-ansible/files/1518408/full-log.txt)

**Comment by guits** [comment]
Hi @Idix this is probably due to your python version (more precisely, config_template with python 3.x).

can you try using python 2.7?

**Comment by Idix** [comment]
Hi @guits, using python 2.7 with Ansible did the trick.
I would still consider this a bug.

Cheers,
Idix

**Comment by guits** [comment]
@Idix I'm not sure how much effort it represents to be able to run with python3, I'm not sure this is a top priority at the moment.
Closing this, feel free to reopen if needed
