### ISSUE TITLE
Creates argument prevents bootstrap keys from being generated in luminous and greater releases

### ISSUE THREAD

**Issue by allen13** [ceph/ceph-ansible#2228]
When running the playbook with the luminous release the mons role fails to generate bootstrap keys. Since fetch doesn't have "fail_on_missing: yes" it continues on without failing. It finally fails when it gets the the osd role and can't find the fetch keys.

Removing the creates statement fixes the problem because the {{ cluster }}.client.admin.keyring gets generated in a previous step which means this command will never get run:

args:
    creates: /etc/ceph/{{ cluster }}.client.admin.keyring

https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-mon/tasks/ceph_keys.yml#L2

Apparently the creates arg wins out over always_run: yes and check_mode: no (I tested both)

**Comment by guits** [comment]
@allen13 can you provide a full playbook run log with verbose?

**Comment by vishalkanaujia** [comment]
@allen13 I also faced the same problem and resolved it by commenting `#creates: /etc/ceph/{{ cluster }}.client.admin.keyring`.  This file is first created in `./roles/ceph-mon/tasks/deploy_monitors.yml`. Since the deply_monitor.yml task runs before ceph_keys task, the latter _create_ operation fails.

**Comment by allen13** [comment]
Everything works fine when I comment out the creates argument as well. Is there any reason for keeping it? ceph-create-keys is already idempotent. Running it again doesn't hurt anything.
