### ISSUE TITLE
Scale-out roles to separate repositories

### ISSUE THREAD

**Issue by baccenfutter** [ceph/ceph-ansible#2229]
# Userstory

As a Ceph user who already uses Ansible to manage infrastructure, I want to integrate roles of this playbook as resources into my already existing playbook.

# AC
- [ ] split all roles into separate individual repositories
- [ ] semantically tag all role-repos with a version number
- [ ] create a `requirements.yml` and add all the roles as deps being pulled directly from Github
- [ ] patch `ansible.cfg` to contain `roles_path = ./.imported_roles:roles/
- [ ] extend docs: describe how to use `ansible-galaxy` to sync role deps before execution

**Comment by leseb** [comment]
All the roles are already split into individual repositories (github.com/ceph/ansible-ceph-$role) and available as part of the ansible galaxy.
These repos are already tagged using the last schema from that repo (e.g: v3.0.12).
You can use this outdated requirement file https://github.com/ceph/ceph-ansible/blob/master/example-ansible-role-requirements.yml as an example.

I think you should patch your own `ansible.cfg` as this is not the out preferred method to deploy Ceph.

As for the doc, I'll redirect you to the Ansible galaxy doc on how to use roles from the galaxy: https://docs.ansible.com/ansible/latest/galaxy.html

I'm closing this, feel free to respond if you have any more concerns.
Thanks.
