### ISSUE TITLE
Specifying OSD groups as list fails with AnsibleError: Unexpected templating type error occurred on ..unhashable type: 'list'

### ISSUE THREAD

**Issue by vishalkanaujia** [ceph/ceph-ansible#2234]
The ceph-ansible (latest master with Luminous Bluestore) fails when osd_group_name defined in _group_var/all.yml_ is specified as follows:
```
osd_group_name:
 - osds_group_ssd_collocated
 - osds_group_hdd
 - osds_group_hdd_collocated

```
The playbook fails while generating ceph.conf as follows:
```
TASK [ceph-config : generate ceph configuration file: ceph.conf] ******************************************************************************************************************************************************************************************************
fatal: [10.33.69.28]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleError: Unexpected templating type error occurred on (# {{ ansible_managed }}\n\n[global]\n{% if not cephx %}\nauth cluster required = none\nauth service required = none\nauth client required = none\nauth supported = none\n{% endif %}\n{% if ip_version == 'ipv6'  %}\nms bind ipv6 = true\n{% endif %}\n\nosd crush chooseleaf type = 0\n{% endif %}\n{# NOTE (leseb): the blank lines in-between..............
: unhashable type: 'list'"
```

The IP 10.33.69.28 is of one of the monitors node.

The task is defined in "ceph-ansible/roles/ceph-config/tasks/main.yml" 
```
  - name: "generate ceph configuration file: {{ cluster }}.conf"
    action: config_template
    args:
      src: ceph.conf.j2
      dest: /etc/ceph/ceph.d/{{ cluster }}.conf
      owner: "ceph"
      group: "ceph"
      mode: "0644"
      config_overrides: "{{ ceph_conf_overrides_rendered }}"
      config_type: ini
```
I am suspecting that config_template is trying to access osd_group_name somehow, and is failing to understand it. Could you please help me on fixing this problem?

**Comment by guits** [comment]
@vishalkanaujia `osd_group_name` is not supposed to be an array but a string. This is the osd group name from an ansible inventory host file point of view.

**Comment by varadakari** [comment]
@guits in that case, if we have a cluster, which has to be created like above, how do we mention in the config? Is there a different way? we have some nodes with ssds where we want to have co-located deployment for them and HDD will have a ssd to host rocksdb for bluestore meta.

**Comment by guits** [comment]
@vishalkanaujia in that case you need to specify for each host which osd scenario you want in your inventory host file

**Comment by varadakari** [comment]
@guits thanks for the info. we were trying to group them based on the deployment and trying to mention in the osd group. It would be modular if we can mention them as groups and deploy according to the characteristic of the device.

**Comment by guits** [comment]
@varadakari you can still declare several groups of osds host in your inventory host file and declare them as children of a parent group 'osds':
```
[osds:children]
osds_group_ssd_collocated
osds_group_hdd_collocated
osds_group_hdd

[osds_group_ssd_collocated]
osd1-0
osd1-1
osd1-2

[osds_group_hdd]
osd2-0
osd2-1
osd2-2

[osds_group_hdd_collocated]
osd3-0
osd3-1
osd3-2
```
 and then you would have `group_vars/osds_group_ssd_collocated.yml`, `group_vars/osds_group_hdd.yml` and `group_vars/osds_group_hdd_collocated.yml` with a 'per group' applied configuration. (see: http://docs.ansible.com/ansible/latest/intro_inventory.html#groups-of-groups-and-group-variables)

**Comment by varadakari** [comment]
@guits Thanks a lot. I think this suits well for our usecase. will try this and let you know if it fails.

**Comment by vishalkanaujia** [comment]
@guits the host file changes worked well. thanks you much.
