### ISSUE TITLE
ceph-mon : make sure pg num is set for cephfs pools

### ISSUE THREAD

**Issue by grharry** [ceph/ceph-ansible#2239]
Hello, 

I am trying to collocate journals and data on same disk so I am using the collocation scenario in osds.yml 
and  osd_objectstore: bluestore

However ansible complaints/needs pg_nums 
Any ideas? 

ansible-playbook site.yml 

TASK [ceph-mon : make sure pg num is set for cephfs pools] *********************************************************************************************************************************************************
failed: [ceph1] (item={u'name': u'cephfs_data', u'pgs': u''}) => {"changed": false, "item": {"name": "cephfs_data", "pgs": ""}, "msg": "You must set pg num for your cephfs pools, see the cephfs_pools variable."}
failed: [ceph2] (item={u'name': u'cephfs_data', u'pgs': u''}) => {"changed": false, "item": {"name": "cephfs_data", "pgs": ""}, "msg": "You must set pg num for your cephfs pools, see the cephfs_pools variable."}
failed: [ceph1] (item={u'name': u'cephfs_metadata', u'pgs': u''}) => {"changed": false, "item": {"name": "cephfs_metadata", "pgs": ""}, "msg": "You must set pg num for your cephfs pools, see the cephfs_pools variable."}
failed: [ceph2] (item={u'name': u'cephfs_metadata', u'pgs': u''}) => {"changed": false, "item": {"name": "cephfs_metadata", "pgs": ""}, "msg": "You must set pg num for your cephfs pools, see the cephfs_pools variable."}

PLAY RECAP *********************************************************************************************************************************************************************************************************
ceph-mon1                  : ok=2    changed=0    unreachable=0    failed=0   
ceph1                      : ok=50   changed=3    unreachable=0    failed=1   
ceph2                      : ok=45   changed=1    unreachable=0    failed=1

**Comment by guits** [comment]
@grharry you should have something like this :
```
cephfs_pools:
  - { name: "{{ cephfs_data }}", pgs: "8" }
  - { name: "{{ cephfs_metadata }}", pgs: "8" }
```
declared in `group_vars/mons.yml`

can you paste the output of `grep -Ev '(^$|^#)' group_vars/*` ?

**Comment by grharry** [comment]
roup_vars/all.yml:---
group_vars/all.yml:dummy:
group_vars/all.yml:fetch_directory: fetch/
group_vars/all.yml:ceph_origin: repository
group_vars/all.yml:ceph_repository: community
group_vars/all.yml:ceph_mirror: http://download.ceph.com
group_vars/all.yml:ceph_stable_key: https://download.ceph.com/keys/release.asc
group_vars/all.yml:ceph_stable_release: luminous
group_vars/all.yml:ceph_stable_repo: "{{ ceph_mirror }}/debian-{{ ceph_stable_release }}"
group_vars/all.yml:fsid: "{{ cluster_uuid.stdout }}"
group_vars/all.yml:generate_fsid: true
group_vars/all.yml:monitor_interface: ens18
group_vars/all.yml:ip_version: ipv4
group_vars/all.yml:mon_use_fqdn: false # if set to true, the MON name used will be the fqdn in the ceph.conf
group_vars/all.yml:journal_size: 102400 # OSD journal size in MB
group_vars/all.yml:public_network: 10.10.10.0/24
group_vars/all.yml:cluster_network: "{{ public_network }}"
group_vars/all.yml:osd_objectstore: bluestore
group_vars/all.yml:radosgw_civetweb_port: 8080
group_vars/osds.yml:---
group_vars/osds.yml:dummy:
group_vars/osds.yml:copy_admin_key: true
group_vars/osds.yml:devices: 
group_vars/osds.yml:    - /dev/vdb
group_vars/osds.yml:osd_scenario: collocated
group_vars/rgws.yml:---
group_vars/rgws.yml:dummy:
group_vars/rgws.yml:create_pools:
group_vars/rgws.yml:  defaults.rgw.buckets.data:
group_vars/rgws.yml:    pg_num: 16
group_vars/rgws.yml:  defaults.rgw.buckets.index:
group_vars/rgws.yml:    pg_num: 32
group_vars/rgws.yml:  foo:
group_vars/rgws.yml:    pg_num: 4

**Comment by guits** [comment]
As the message told you, please, set `cephfs_pool` variable properly

**Comment by grharry** [comment]
kudos!
