### ISSUE TITLE
TASK [ceph-osd : activate osd(s) when device is a disk] 

### ISSUE THREAD

**Issue by grharry** [ceph/ceph-ansible#2240]
I am getting this for all disks in my config 

TASK [ceph-osd : activate osd(s) when device is a disk] ************************************************************************************************************************************************************
failed: [ceph2] (item=/dev/vdb) => {"changed": false, "cmd": ["ceph-disk", "activate", "/dev/vdb1"], "delta": "0:00:02.955898", "end": "2017-12-07 18:27:02.194538", "item": "/dev/vdb", "msg": "non-zero return code", "rc": 1, "start": "2017-12-07 18:26:59.238640", "stderr": "/usr/lib/python2.7/dist-packages/ceph_disk/main.py:5653: UserWarning: \n*******************************************************************************\nThis tool is now deprecated in favor of ceph-volume.\nIt is recommended to use ceph-volume for OSD deployments. For details see:\n\n    http://docs.ceph.com/docs/master/ceph-volume/#migrating\n\n*******************************************************************************\n\n  warnings.warn(DEPRECATION_WARNING)\ngot monmap epoch 1\n2017-12-07 18:27:01.754143 7f1c57b42e00 -1 bluestore(/var/lib/ceph/tmp/mnt.SM3DxL/block) _check_or_set_bdev_label bdev /var/lib/ceph/tmp/mnt.SM3DxL/block fsid dd325bd7-32c5-4405-aa07-9d43b7c7a83b does not match our fsid 68b06bec-1fd8-4686-8e3c-01ba5b070a9e\n2017-12-07 18:27:02.019313 7f1c57b42e00 -1 bluestore(/var/lib/ceph/tmp/mnt.SM3DxL) mkfs fsck found fatal error: (5) Input/output error\n2017-12-07 18:27:02.019647 7f1c57b42e00 -1 OSD::mkfs: ObjectStore::mkfs failed with error (5) Input/output error\n2017-12-07 18:27:02.019901 7f1c57b42e00 -1 \u001b[0;31m ** ERROR: error creating empty object store in /var/lib/ceph/tmp/mnt.SM3DxL: (5) Input/output error\u001b[0m\nmount_activate: Failed to activate\nTraceback (most recent call last):\n  File \"/usr/sbin/ceph-disk\", line 9, in <module>\n    load_entry_point('ceph-disk==1.0.0', 'console_scripts', 'ceph-disk')()\n  File \"/usr/lib/python2.7/dist-packages/ceph_disk/main.py\", line 5736, in run\n    main(sys.argv[1:])\n  File \"/usr/lib/python2.7/dist-packages/ceph_disk/main.py\", line 5682, in main\n    main_catch(args.func, args)\n  File \"/usr/lib/python2.7/dist-packages/ceph_disk/main.py\", line 5710, in main_catch\n    func(args)\n  File \"/usr/lib/python2.7/dist-packages/ceph_disk/main.py\", line 3761, in main_activate\n    reactivate=args.reactivate,\n  File \"/usr/lib/python2.7/dist-packages/ceph_disk/main.py\", line 3524, in mount_activate\n    (osd_id, cluster) = activate(path, activate_key_template, init)\n  File \"/usr/lib/python2.7/dist-packages/ceph_disk/main.py\", line 3701, in activate\n    keyring=keyring,\n  File \"/usr/lib/python2.7/dist-packages/ceph_disk/main.py\", line 3153, in mkfs\n    '--setgroup', get_ceph_group(),\n  File \"/usr/lib/python2.7/dist-packages/ceph_disk/main.py\", line 570, in command_check_call\n    return subprocess.check_call(arguments)
....
.....
.....
....

**Comment by guits** [comment]
@grharry can you paste the content of your ceph.conf?

**Comment by grharry** [comment]
# Please do not change this file directly since it is managed by Ansible and will be overwritten

[global]
fsid = b6752541-3d76-44fa-a63e-dada6b636238



mon initial members = ceph1,ceph2
mon host = 10.10.10.155,10.10.10.156

public network = 10.10.10.0/24
cluster network = 10.10.10.0/24

**Comment by grharry** [comment]
hello again, 
my git branch is stable-3.0, 
ansible 2.4.2.0

my ansible-ceph Config is 

group_vars/all.yml:---
group_vars/all.yml:dummy:
group_vars/all.yml:fetch_directory: fetch/
group_vars/all.yml:cluster: ceph
group_vars/all.yml:ceph_origin: repository
group_vars/all.yml:ceph_repository: community
group_vars/all.yml:ceph_mirror: http://download.ceph.com
group_vars/all.yml:ceph_stable_key: https://download.ceph.com/keys/release.asc
group_vars/all.yml:ceph_stable_release: luminous
group_vars/all.yml:ceph_stable_repo: "{{ ceph_mirror }}/debian-{{ ceph_stable_release }}"
group_vars/all.yml:fsid: "{{ cluster_uuid.stdout }}"
group_vars/all.yml:generate_fsid: true
group_vars/all.yml:ceph_conf_key_directory: /etc/ceph
group_vars/all.yml:cephx: true
group_vars/all.yml:monitor_interface: ens18
group_vars/all.yml:monitor_address_block: 10.10.10.0/24
group_vars/all.yml:ip_version: ipv4
group_vars/all.yml:mon_use_fqdn: false # if set to true, the MON name used will be the fqdn in the ceph.conf
group_vars/all.yml:journal_size: 102400 # OSD journal size in MB
group_vars/all.yml:public_network: 10.10.10.0/24
group_vars/all.yml:cluster_network: "{{ public_network }}"
group_vars/all.yml:osd_objectstore: bluestore
group_vars/all.yml:radosgw_civetweb_port: 8080
group_vars/all.yml:radosgw_interface: ens18
group_vars/all.yml:radosgw_address_block: 10.10.10.0/24
group_vars/ceph-fetch-keys.yml:---
group_vars/ceph-fetch-keys.yml:dummy:
group_vars/ceph-fetch-keys.yml:fetch_directory: fetch/
group_vars/ceph-fetch-keys.yml:cluster: ceph
group_vars/mons.yml:---
group_vars/mons.yml:dummy:
group_vars/mons.yml:monitor_secret: "{{ monitor_keyring.stdout }}"
group_vars/mons.yml:admin_secret: 'admin_secret'
group_vars/mons.yml:cephfs_data: cephfs_data
group_vars/mons.yml:cephfs_metadata: cephfs_metadata
group_vars/mons.yml:cephfs: cephfs
group_vars/osds.yml:---
group_vars/osds.yml:dummy:
group_vars/osds.yml:copy_admin_key: true
group_vars/osds.yml:devices: 
group_vars/osds.yml:  - /dev/vdb 
group_vars/osds.yml:osd_scenario: collocated
group_vars/rgws.yml:---
group_vars/rgws.yml:dummy:
group_vars/rgws.yml:create_pools:
group_vars/rgws.yml:  defaults.rgw.buckets.data:
group_vars/rgws.yml:    pg_num: 16
group_vars/rgws.yml:  defaults.rgw.buckets.index:
group_vars/rgws.yml:    pg_num: 32
group_vars/rgws.yml:  dhd:
group_vars/rgws.yml:    pg_num: 4
----------------------------------------------------------------------------------------------------

This Breaks with 

failed: [ceph1] (item=/dev/vdb) => {"changed": false, "cmd": ["ceph-disk", "activate", "/dev/vdb1"], "delta": "0:00:02.111792", "end": "2017-12-08 00:58:43.842788", "item": "/dev/vdb", "msg": "non-zero return code", "rc": 1, "start": "2017-12-08 00:58:41.730996", "stderr": "/usr/lib/python2.7/dist-packages/ceph_disk/main.py:5653: UserWarning: ,
*******************************************************************************,
This tool is now deprecated in favor of ceph-volume.,
It is recommended to use ceph-volume for OSD deployments. For details see:,
,
    http://docs.ceph.com/docs/master/ceph-volume/#migrating,
,
*******************************************************************************,
,
  warnings.warn(DEPRECATION_WARNING),
got monmap epoch 1,
2017-12-08 00:58:43.332369 7fd90320fe00 -1 bluestore(/var/lib/ceph/tmp/mnt.BXHFoq/block) _check_or_set_bdev_label bdev /var/lib/ceph/tmp/mnt.BXHFoq/block fsid caa8757c-2473-45e5-87bf-b5367c66f005 does not match our fsid f18b35b6-10ef-4760-b37d-956c26b97370,
2017-12-08 00:58:43.583475 7fd90320fe00 -1 bluestore(/var/lib/ceph/tmp/mnt.BXHFoq) mkfs fsck found fatal error: (5) Input/output error,
2017-12-08 00:58:43.583796 7fd90320fe00 -1 OSD::mkfs: ObjectStore::mkfs failed with error (5) Input/output error,
2017-12-08 00:58:43.584023 7fd90320fe00 -1 \u001b[0;31m ** ERROR: error creating empty object store in /var/lib/ceph/tmp/mnt.BXHFoq: (5) Input/output error\u001b[0m,
mount_activate: Failed to activate,
Traceback (most recent call last):,
  File \"/usr/sbin/ceph-disk\", line 9, in <module>,
    load_entry_point('ceph-disk==1.0.0', 'console_scripts', 'ceph-disk')(),
  File \"/usr/lib/python2.7/dist-packages/ceph_disk/main.py\", line 5736, in run,
    main(sys.argv[1:]),
  File \"/usr/lib/python2.7/dist-packages/ceph_disk/main.py\", line 5682, in main,
    main_catch(args.func, args),
  File \"/usr/lib/python2.7/dist-packages/ceph_disk/main.py\", line 5710, in main_catch,
    func(args),
  File \"/usr/lib/python2.7/dist-packages/ceph_disk/main.py\", line 3761, in main_activate,
    reactivate=args.reactivate,,
  File \"/usr/lib/python2.7/dist-packages/ceph_disk/main.py\", line 3524, in mount_activate,
    (osd_id, cluster) = activate(path, activate_key_template, init),
  File \"/usr/lib/python2.7/dist-packages/ceph_disk/main.py\", line 3701, in activate,
    keyring=keyring,,
  File \"/usr/lib/python2.7/dist-packages/ceph_disk/main.py\", line 3153, in mkfs,
    '--setgroup', get_ceph_group(),,
  File \"/usr/lib/python2.7/dist-packages/ceph_disk/main.py\", line 570, in command_check_call,
    return subprocess.check_call(arguments),
  File \"/usr/lib/python2.7/subprocess.py\", line 541, in check_call,
    raise CalledProcessError(retcode, cmd),
subprocess.CalledProcessError: Command '['/usr/bin/ceph-osd', '--cluster', 'ceph', '--mkfs', '-i', u'0', '--monmap', '/var/lib/ceph/tmp/mnt.BXHFoq/activate.monmap', '--osd-data', '/var/lib/ceph/tmp/mnt.BXHFoq', '--osd-uuid', u'f18b35b6-10ef-4760-b37d-956c26b97370', '--setuser', 'ceph', '--setgroup', 'ceph']' returned non-zero exit status 1", "stderr_lines": ["/usr/lib/python2.7/dist-packages/ceph_disk/main.py:5653

any Ideas?

**Comment by grharry** [comment]
arghhhhhhhhhhhhhhhh ..... 
Mea culpa! 
102400 is not 100Mbytes !!!!!! 
Please close issue!
