### ISSUE TITLE
Containerized deployment does not properly set up client

### ISSUE THREAD

**Issue by dmesser** [ceph/ceph-ansible#2241]
Consider the following inventory:

```
[mons]
ceph-mon1
ceph-mon2
ceph-mon3

[mgrs]
ceph-mon1
ceph-mon2
ceph-mon3

[osds]
ceph-osd1
ceph-osd2
ceph-osd3
ceph-osd4
ceph-osd5

[rgws]
ceph-osd1
ceph-osd2
ceph-osd3

[clients]
ceph-client
```

The following group_vars/clients.yml

```
---
dummy:
user_config: true
pools:
  - { name: testpool, pgs: "{{ ceph_conf_overrides.global.osd_pool_default_pg_num }}" }
keys:
  - { name: client.test, key: "$(ceph-authtool --gen-print-key)", mon_cap: "allow r", osd_cap: "allow class-read object_prefix rbd_children, allow rwx pool=testpool", mode: "0600", acls: [] }
```

and the following deployment command:

```
ansible-playbook site-docker.yml
```

The installation goes through but the client is actually not really configured. All that happens is that the ceph image is downloaded and the ceph.conf is copied. No keyrings or ceph client libraries, binaries are copied and no pools are created.

**Comment by vishalkanaujia** [comment]
@dmesser could you please share the play file and ansible log for the ceph-client role.

**Comment by dmesser** [comment]
@vishalkanaujia The play file is the stock file shipping from this repo. I have attached the complete log of this run.
[ansible.log](https://github.com/ceph/ceph-ansible/files/1543032/ansible.log)
