### ISSUE TITLE
Ceph user/group missing

### ISSUE THREAD

**Issue by berendt** [ceph/ceph-ansible#2250]
Ceph user & group missing when deploying with Ubuntu/Docker:

```
TASK [ceph-config : create ceph conf directory and assemble directory] *********
failed: [xxx] (item=/etc/ceph/) => {"failed": true, "gid": 64045, "group": "64045", "item": "/etc/ceph/", "mode": "0755", "msg": "chown failed: failed to look up user ceph", "owner": "64045", "path": "/etc/ceph/", "size": 4096, "state": "directory", "uid": 64045}
failed: [xxx] (item=/etc/ceph/ceph.d/) => {"failed": true, "gid": 0, "group": "root", "item": "/etc/ceph/ceph.d/", "mode": "0755", "msg": "chown failed: failed to look up user ceph", "owner": "root", "path": "/etc/ceph/ceph.d/", "size": 4096, "state": "directory", "uid": 0}
```

**Comment by guits** [comment]
@berendt can you paste here the output of :
`grep -Ev '(^$|^#) group_vars/*.yml` ?

your nodes are running on Ubuntu?

**Comment by berendt** [comment]
@guits Running on Ubuntu, yes. With ``containerized_deployment: true`` (Cannot paste the whole configuration.). There is no ``ceph`` user or group by default and no packages will be installed that will create a ``ceph`` user and group. Because of this the role has to ensure the existence of the user and group.

**Comment by guits** [comment]
@berendt you shouldn't hit this error since you are running a containerized deployment. The failing tasks you mentioned here are played only for non containerized deployments.

**Comment by guits** [comment]
@berendt can you link here the command you've used to launch the playbook?

**Comment by berendt** [comment]
Learned a bit more about variable precedence in ansible. Can be closed as invalid.

**Comment by howels** [comment]
Ran into this using the example site-docker.yml.sample file on CentOS Atomic. Install fails as user is not created before the local configuration directory is chown'd to that user. Looks like the commit is not yet included as making the same change to my local files fixes the issue; roles/ceph.ceph-common/tasks/installs/configure_redhat_local_installation.yml is not executed for Docker installs.

**Comment by leseb** [comment]
@howels, as you mentioned ceph-common, does not run on containerized deployment. So it's unclear to me what's your error?

**Comment by MrStupnikov** [comment]
Hi @leseb 

I have run into the same issue while installing containerized CEPH on CentOS machine. Please check error details below:

~~~
TASK [ceph-config : create ceph conf directory] *****************************************************************************
Wednesday 01 August 2018  18:16:40 +0000 (0:00:01.404)       0:03:56.529 ****** 
fatal: [ceph1]: FAILED! => {"changed": false, "gid": 64045, "group": "64045", "mode": "0755", "msg": "chown failed: failed to look up user ceph", "owner": "64045", "path": "/etc/ceph", "secontext": "unconfined_u:object_r:etc_t:s0", "size": 6, "state": "directory", "uid": 64045}
~~~

**Comment by jekohk** [comment]
Running a non-containtainerized environment and hitting this issue. If your `ceph_origin` is set to `repository` the user and group will never be created. Is there a reason the user & group are only created in `local` mode? Both `local` and `repository` require the user and group be present. To me, the role is currently broken.

**Comment by dsavineau** [comment]
In non containerized environment the user/group are created by the ceph packages installation. So if you're using `ceph_origin: repository` the packages will be installed.

```console
# rpm -q --scripts ceph-common
preinstall scriptlet (using /bin/sh):
CEPH_GROUP_ID=167
CEPH_USER_ID=167
/usr/sbin/groupadd ceph -g $CEPH_GROUP_ID -o -r 2>/dev/null || :
/usr/sbin/useradd ceph -u $CEPH_USER_ID -o -r -g ceph -s /sbin/nologin -c "Ceph daemons" -d /var/lib/ceph 2>/dev/null || :
exit 0
```

Also please don't comment on a closed (and old) issue and without sharing logs, inventory and group_vars/* values.

**Comment by jekohk** [comment]
@dsavineau I see, it must be because I had an older version of ceph packages installed which did not create the user & group. 

Apologies for re-opening a closed thread but the solution was never posted here before your reply, and there were others with a similar issue already following this thread.
