### ISSUE TITLE
Use of /dev/disk/by-path for devices not possible

### ISSUE THREAD

**Issue by berendt** [ceph/ceph-ansible#2252]
We tried to use ``/dev/disk/by-path`` for OSD and journal devices. Looks like this is not possible for OSD devices.

```
devices:
    - /dev/disk/by-path/pci-0000:06:00.0-sas-phy6-lun-0
```

1. invalid container names:

```
docker: Error response from daemon: Invalid container name (ceph-osd-xxx-dev-pci-0000:06:00.0-sas-phy6-lun-0), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed.
```

2. wrong ```OSD_DEVICE``` in ```ceph-osd-run.sh```:

In ```roles/ceph-osd/templates/ceph-osd-run.sh.j2``` it is  ```-e OSD_DEVICE=/dev/${1}```. ```${1}``` is the sub name of the generated systemd unit file (```ceph-osd@pci-0000:06:00.0-sas-phy6-lun-0.service``` --> ```-e OSD_DEVICE=/dev/pci-0000:06:00.0-sas-phy6-lun-0```).

Because of this I think ```/dev/disk/by-id``` is also not working.

3. other issue in ```ceph-osd-run.sh```:

```
Dec 12 12:48:08 xxx ceph-osd-run.sh[53523]: invalid argument "/dev/pci-0000:06:00.0-sas-phy6-lun-0" for --device=/dev/pci-0000:86:00.0-sas-phy4-lun-0: bad mode specified: 00.0-sas-phy4-lun-0
```

**Comment by leseb** [comment]
@berendt just to be sure: `/dev/disk/by-path/pci-0000:06:00.0-sas-phy6-lun-0` is a symlink rigth?

**Comment by berendt** [comment]
@leseb Yes. ``pci-0000:06:00.0-sas-phy6-lun-0 -> ../../sdd``

**Comment by leseb** [comment]
Could you please insert: `- debug: msg="{{ devices }}"` here: https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-defaults/tasks/facts.yml#L154

Then run the playbook and send us the result, thanks.

**Comment by guits** [comment]
Closed due to inactivity, feel free to re-open if needed. Thanks!
