### ISSUE TITLE
ceph-default: fuser command is used without verifcation

### ISSUE THREAD

**Issue by sparktown** [ceph/ceph-ansible#2254]
In task file "check_socket_non_container.yml" the command fuser is used several times to check if a socket is used. But there is no verification, that the fuser command is available. If fuser is not available on a host the role removess all ceph-daemons on the host, because the when conditions applys to rc !=0 of the task with the fuser command (which is 127, command fuser not found).

Possible fixes:
a) Ensure package "psmisc" is installed (Ubuntu, don't know the packagename of centos)
b) Instead of daemon_name_socket.rc !=0 use daemon_name_socket.rc == 1 in the when condistions of the remove socket tasks

**Comment by leseb** [comment]
@sparktown you're right using `daemon_name_socket.rc == 1` sounds the right approach. Will send a PR for this.
