### ISSUE TITLE
cannot stat '/var/run/ceph/ceph-mon.abcd.asok': No such file or directory",

### ISSUE THREAD

**Issue by sercanacar** [ceph/ceph-ansible#2276]
Hi,

Not sure what I'm doing wrong, when I run sudo ansible-playbook site-docker.yml, hitting

`
fatal: [abcd.com]: FAILED! => {"attempts": 5, "changed": true, "cmd": ["docker", "exec", "ceph-mon-abcd.com", "stat", "/var/run/ceph/ceph-mon.abcd.com.asok"], "delta": "0:00:00.049798", "end": "2017-12-18 04:31:41.684137", "failed": true, "rc": 1, "start": "2017-12-18 04:31:41.634339", "stderr": "stat: cannot stat '/var/run/ceph/ceph-mon.abcd.com1.asok': No such file or directory", "stderr_lines": ["stat: cannot stat '/var/run/ceph/ceph-mon.abcd.com.asok': No such file or directory"], "stdout": "", "stdout_lines": []}`

But I can see such volume

`/var/lib/docker/btrfs/subvolumes/cbf8b075872875edd770c34c5e4b235c27bba82a998560fe14f8d19c48dac84c/run/ceph/ceph-mon.abcd.asok`

If I look at the container logs

`Dec 18 04:44:39 ca-abcd.com docker: 2017-12-18 04:44:39.234081 7f5b17d6af00  4 rocksdb: [/build/ceph-12.2.1/src/rocksdb/db/db_impl.cc:343] Shutdown complete
Dec 18 04:44:39 ca-abcd.com docker: 2017-12-18 04:44:39.234101 7f5b17d6af00 -1 rocksdb: IO error: lock /var/lib/ceph/mon/ceph-ca-abcd.com/store.db/LOCK: Resource temporarily unavailable
Dec 18 04:44:39 ca-abcd.com docker: 2017-12-18 04:44:39.234107 7f5b17d6af00 -1 error opening mon data directory at '/var/lib/ceph/mon/ceph-abcd.com': (22) Invalid argument
`
Regards

**Comment by leseb** [comment]
`/ceph-mon.abcd.com.asok` versus `ceph-mon.abcd.asok`. Please share your group_vars.

**Comment by sercanacar** [comment]
all.yml 
`---
dummy:
containerized_deployment: true
ceph_stable_release: luminous
monitor_interface: eno1
ip_version: ipv4
mon_use_fqdn: true
public_network: 192.168.1.0/24
osd_objectstore: bluestore
docker: true
`
Don't think I've edited any other file, which again could be the reason...

**Comment by sercanacar** [comment]
Closing. my /etc/hosts was incorrest
