### ISSUE TITLE
 cephx server client.admin:  unexpected key

### ISSUE THREAD

**Issue by sercanacar** [ceph/ceph-ansible#2319]
Hi,

Clearly not ceph-ansible problem but I'm unable to successfully deploy.

`ansible-playbook site-docker.ym`l completes without any failures

However when I check the logs on the monitoring container:

2018-01-12 08:25:13.044677 7fbb040f5700  0 cephx server client.admin:  unexpected key: req.key=696378e9333af335 expected_key=1d4312e8b4917543
2018-01-12 08:25:18.055032 7fbb040f5700  0 cephx server osd.8: couldn't find entity name: osd.8
2018-01-12 08:25:20.413631 7fbb040f5700  0 cephx server osd.5: couldn't find entity name: osd.5
2018-01-12 08:25:22.674355 7fbb040f5700  0 cephx server osd.4: couldn't find entity name: osd.4

I clearly need to cleanup something. I've failed with removing the containers and images. Unfortunately `purge-docker-cluster.yml` isn't working either with failures on
```

"get all the running osds"
FAILED! => {"changed": true, "cmd": "systemctl list-units | grep \"loaded active\" | grep -oE \"ceph-osd@([0-9]{1,2}|[a-z]+).service\"", "delta": "0:00:00.010032", "end": "2018-01-12 08:27:01.489301", "failed": true, "rc": 1, "start": "2018-01-12 08:27:01.479269", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
```

I don't have any running osds atm, stuck in a limbo...

Regards

**Comment by guits** [comment]
@sercanacar could you provide more details ? ceph-ansible/ceph-container versions? full playbook run log?
you said you failed removing the containers and images, what is the the actual status of your nodes ? are the containers still running ?
It looks like you tried to remove everything but failed for some reason. I'm not sure about the state of your cluster then. What kind of environment are you trying to deploy (VM/baremetal..?)
At first glance, with the little bit information you provided, I would say it looks like there is some leftover on the env that prevent you from deploying properly.

**Comment by guits** [comment]
Closed due to inactivity, feel free to re-open if needed. Thanks!
