### ISSUE TITLE
osd_fragments does not work with dmcrypt devices

### ISSUE THREAD

**Issue by czunker** [ceph/ceph-ansible#2320]
ceph-ansible version: v3.1.0rc1
Setup: non-collocated with dmcrypt and no auto discovery

This step in osd_fragments.yml

`
- name: get osd path
  shell: "df | grep {{ item }} | awk '{print $6}' "
  with_items: "{{ devices }}"
  changed_when: false
  failed_when: false
  check_mode: no
  register: osd_path
`

does not work, when the OSDs are encrypted with dmcrypt.
The output of df looks different when the OSDs are encrypted:
`
/dev/sdb5       8.7M   98K  7.9M   2% /var/lib/ceph/osd-lockbox/40727135-93d3-4002-875b-84899a7e32ea
/dev/dm-1       3.7T  110M  3.7T   1% /var/lib/ceph/osd/ceph-6
`
The above task expects a direct mapping like this:
`
/dev/sdb5       8.7M   98K  7.9M   2% /var/lib/ceph/osd/ceph-6
`

**Comment by guits** [comment]
Closed due to inactivity, feel free to re-open if needed. Thanks!
