### ISSUE TITLE
TASK [ceph-osd : create gpt disk label] failed on disk not referenced in the playbook

### ISSUE THREAD

**Issue by mistur** [ceph/ceph-ansible#2335]
Hello,

I ran the playbook today to install a new cluster with 2 disks per server (sdc and sdd) but playbook failed on sdb even no reference is made to this disk in the playbook.

here some logs with all.yml and osds,.yml

[sdb-error.log](https://github.com/ceph/ceph-ansible/files/1644034/sdb-error.log)
[osds.yml.txt](https://github.com/ceph/ceph-ansible/files/1644038/osds.yml.txt)
[all.yml.txt](https://github.com/ceph/ceph-ansible/files/1644039/all.yml.txt)

```
apollo@icadmin004:~/ceph-ansible$ git branch
   master
 * stable-3.0
```

```
apollo@icadmin004:~/ceph-ansible$ ansible --version
ansible 2.4.0.0
  config file = /home/apollo/ceph-ansible/ansible.cfg
  configured module search path = [u'/home/apollo/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

Thanks for you help

Best regards

Yoann

**Comment by andymcc** [comment]
osd_auto_discovery: true

I think you should set that to false.

**Comment by mistur** [comment]
OK Thanks That fixed my issue.

Best regards,

Yoann
