### ISSUE TITLE
purge-cluster wi bluestore: deleting LVM volume doesn't clean it up

### ISSUE THREAD

**Issue by bengland2** [ceph/ceph-ansible#2337]
I was using purge-cluster.yml with a LVM ceph-volume-based config involving multiple OSDs/SSD, and switching between filestore and bluestore for performance testing purposes.    When I tried to switch back from filestore to bluestore, it complained that the OSDs already existed even though I had deleted and recreated the LVM volumes.  Apparently that doesn't actually clean out the signatures on the storage.  So I saw the note about switching to ceph-volume lvm zap when it becomes available, which it is now in Luminous 12.2.2, and did this patch and it worked after I did purge-cluster and site.yml.  Can't do a PR right now, sorry.

```
diff --git a/infrastructure-playbooks/purge-cluster.yml b/infrastructure-playbooks/purge-cluster.yml
index c04c408..ebb4874 100644
--- a/infrastructure-playbooks/purge-cluster.yml
+++ b/infrastructure-playbooks/purge-cluster.yml
@@ -320,23 +320,14 @@
     failed_when: false
     register: ceph_lockbox_partition_to_erase_path
 
-  # this should go away once 'ceph-volume lvm zap' is available
-  - name: remove osd logical volumes
-    command: "lvremove -f {{ item.data_vg }}/{{ item.data }}"
-    with_items: "{{ lvm_volumes }}"
-    when:
-      - osd_scenario == "lvm"
-
-  # this should go away once 'ceph-volume lvm zap' is available
-  - name: remove osd lvm journals
-    command: "lvremove -f {{ item.journal_vg }}/{{ item.journal }}"
+  - name: zap lvm data
+    command: "ceph-volume lvm zap {{ item.data_vg }}/{{ item.data}}"
     with_items: "{{ lvm_volumes }}"
     # journals might be logical volumes, but they could also be
     # devices so fail silently if this doesn't work
     failed_when: false
     when:
       - osd_scenario == "lvm"
-      - item.journal_vg is defined
 
   - name: get ceph block partitions
     shell: |
```

**Comment by leseb** [comment]
This implies we know about `lvm_volumes`. You should try to detect it instead.
Thanks for letting us know anyway :).

**Comment by bengland2** [comment]
**ceph_volume lvm zap** takes care of this as long as  you run it before deleting the LVM volumes.
