### ISSUE TITLE
Possible to use 'non-collocated' scenario + bluestore with ONLY the RocksDB (and not also the WAL)?

### ISSUE THREAD

**Issue by agoree407** [ceph/ceph-ansible#2342]
I wanted to see if it were paossible to use 'non-collocated' scenario with ONLY the RocksDB and not also the WAL?  I.e., have 'dedicated_devices' use only a partition for RocksDB, and not an additional partition for the WAL.  I'm usuing an nvme device for this and from my understanding, I'll have to manually parition the nvme, so that there's a partiton per "normal" device, like so:

osd_scenario: non-collocated
osd_objectstore: bluestore
devices:
  - /dev/sda
  - /dev/sdb
  - /dev/sdc
  - /dev/sdd
dedicated_devices:
  - /dev/nvme0n1p1
  - /dev/nvme0n1p2
  - /dev/nvme0n1p3
  - /dev/nvme0n1p4

Is this the proper way to go about using ceph-ansible for buildout?

**Comment by agoree407** [comment]
I saw that I did not have to manually partition the nvme device, simply allowed ansible to do so by defining it for each dedicated_device, like so:

devices:
    /dev/sda
    /dev/sdb
    /dev/sdc
    /dev/sdd
dedicated_devices:
    /dev/nvme0n1
    /dev/nvme0n1
    /dev/nvme0n1
    /dev/nvme0n1

**Comment by leseb** [comment]
You can do this if you use ceph-volume, for ceph-disk this is not supported and won't likely be.
Thanks.
