### ISSUE TITLE
vgcreate: command not found => lvm2 not installed by the playbook (v3.1.0rc1)

### ISSUE THREAD

**Issue by mistur** [ceph/ceph-ansible#2344]
On a fresh ubuntu minimal install, lvm2 is not installed, the playbook seems to no installed the package by itself, could be good to check and install it if not installed.

testing with ansible v3.1.0rc1

failed: [iccluster169.iccluster.epfl.ch] (item={u'data': u'/dev/sdd'}) => {"changed": true, "cmd": ["ceph-volume", "--cluster", "apollo", "lvm", "create", "--bluestore", "--data", "/dev/sdd"], "delta": "0:00:00.483640", "end": "2018-01-23 13:56:46.463439", "failed": true, "item": {"data": "/dev/sdd"}, "msg": "non-zero return code", "rc": 1, "start": "2018-01-23 13:56:45.979799", "stderr": "Traceback (most recent call last):\n  File \"/usr/sbin/ceph-volume\", line 6, in <module>\n    main.Volume()\n  File \"/usr/lib/python2.7/dist-packages/ceph_volume/main.py\", line 37, in __init__\n    self.main(self.argv)\n  File \"/usr/lib/python2.7/dist-packages/ceph_volume/decorators.py\", line 59, in newfunc\n    return f(*a, **kw)\n  File \"/usr/lib/python2.7/dist-packages/ceph_volume/main.py\", line 144, in main\n    terminal.dispatch(self.mapper, subcommand_args)\n  File \"/usr/lib/python2.7/dist-packages/ceph_volume/terminal.py\", line 131, in dispatch\n    instance.main()\n  File \"/usr/lib/python2.7/dist-packages/ceph_volume/devices/lvm/main.py\", line 38, in main\n    terminal.dispatch(self.mapper, self.argv)\n  File \"/usr/lib/python2.7/dist-packages/ceph_volume/terminal.py\", line 131, in dispatch\n    instance.main()\n  File \"/usr/lib/python2.7/dist-packages/ceph_volume/devices/lvm/create.py\", line 57, in main\n    self.create(args)\n  File \"/usr/lib/python2.7/dist-packages/ceph_volume/decorators.py\", line 16, in is_root\n    return func(*a, **kw)\n  File \"/usr/lib/python2.7/dist-packages/ceph_volume/devices/lvm/create.py\", line 21, in create\n    Prepare([]).prepare(args)\n  File \"/usr/lib/python2.7/dist-packages/ceph_volume/decorators.py\", line 16, in is_root\n    return func(*a, **kw)\n  File \"/usr/lib/python2.7/dist-packages/ceph_volume/devices/lvm/prepare.py\", line 208, in prepare\n    block_lv = self.prepare_device(args.data, 'block', cluster_fsid, osd_fsid)\n  File \"/usr/lib/python2.7/dist-packages/ceph_volume/devices/lvm/prepare.py\", line 150, in prepare_device\n    api.create_vg(vg_name, arg)\n  File \"/usr/lib/python2.7/dist-packages/ceph_volume/api/lvm.py\", line 209, in create_vg\n    name] + list(devices)\n  File \"/usr/lib/python2.7/dist-packages/ceph_volume/process.py\", line 135, in run\n    raise RuntimeError(msg)\nRuntimeError: command returned non-zero exit status: 1", "stderr_lines": ["Traceback (most recent call last):", "  File \"/usr/sbin/ceph-volume\", line 6, in <module>", "    main.Volume()", "  File \"/usr/lib/python2.7/dist-packages/ceph_volume/main.py\", line 37, in __init__", "    self.main(self.argv)", "  File \"/usr/lib/python2.7/dist-packages/ceph_volume/decorators.py\", line 59, in newfunc", "    return f(*a, **kw)", "  File \"/usr/lib/python2.7/dist-packages/ceph_volume/main.py\", line 144, in main", "    terminal.dispatch(self.mapper, subcommand_args)", "  File \"/usr/lib/python2.7/dist-packages/ceph_volume/terminal.py\", line 131, in dispatch", "    instance.main()", "  File \"/usr/lib/python2.7/dist-packages/ceph_volume/devices/lvm/main.py\", line 38, in main", "    terminal.dispatch(self.mapper, self.argv)", "  File \"/usr/lib/python2.7/dist-packages/ceph_volume/terminal.py\", line 131, in dispatch", "    instance.main()", "  File \"/usr/lib/python2.7/dist-packages/ceph_volume/devices/lvm/create.py\", line 57, in main", "    self.create(args)", "  File \"/usr/lib/python2.7/dist-packages/ceph_volume/decorators.py\", line 16, in is_root", "    return func(*a, **kw)", "  File \"/usr/lib/python2.7/dist-packages/ceph_volume/devices/lvm/create.py\", line 21, in create", "    Prepare([]).prepare(args)", "  File \"/usr/lib/python2.7/dist-packages/ceph_volume/decorators.py\", line 16, in is_root", "    return func(*a, **kw)", "  File \"/usr/lib/python2.7/dist-packages/ceph_volume/devices/lvm/prepare.py\", line 208, in prepare", "    block_lv = self.prepare_device(args.data, 'block', cluster_fsid, osd_fsid)", "  File \"/usr/lib/python2.7/dist-packages/ceph_volume/devices/lvm/prepare.py\", line 150, in prepare_device", "    api.create_vg(vg_name, arg)", "  File \"/usr/lib/python2.7/dist-packages/ceph_volume/api/lvm.py\", line 209, in create_vg", "    name] + list(devices)", "  File \"/usr/lib/python2.7/dist-packages/ceph_volume/process.py\", line 135, in run", "    raise RuntimeError(msg)", "RuntimeError: command returned non-zero exit status: 1"], "stdout": " stderr: sudo: vgs: command not found\nRunning command: sudo vgcreate --force --yes ceph-fc76846a-d0f0-4866-ae6d-d442fc885469 /dev/sdd\n stderr: sudo: vgcreate: command not found", "stdout_lines": [" stderr: sudo: vgs: command not found", "Running command: sudo vgcreate --force --yes ceph-fc76846a-d0f0-4866-ae6d-d442fc885469 /dev/sdd", " stderr: sudo: vgcreate: command not found"]}

Best regards,

Yoann

**Comment by alfredodeza** [comment]
This has been fixed in Ceph: https://github.com/ceph/ceph/pull/19529

Not yet released.
