### ISSUE TITLE
ceph user/group is missing

### ISSUE THREAD

**Issue by rrmichel** [ceph/ceph-ansible#2421]
https://github.com/ceph/ceph-ansible/blob/0739f7cc3aeeb0de9ebee80aaa92a56942affa1d/roles/ceph-osd/tasks/docker/main.yml#L3

osd_fragments.yml requires a existing ceph user/group but in a containerized deployment we have no ceph user/group.

**Comment by rrmichel** [comment]
@leseb can some introduce a variable e.g. ceph_user / ceph_group to solve the problem?

**Comment by leseb** [comment]
fragments are going away with https://github.com/ceph/ceph-ansible/pull/2409, this should be merged this week.
