### ISSUE TITLE
When using ceph_dev, nfs_ganesha_dev must also be specified to get ganesha up

### ISSUE THREAD

**Issue by batrick** [ceph/ceph-ansible#2437]
I'm not really sure why this redundant configuration is necessary but it makes bringing up any `nfss` up fail without specifying it:

````
No package matching 'nfs-ganesha-rgw' found available, installed or updated
failed: [nfs-000] (item=nfs-ganesha-rgw) => {
    "changed": false, 
    "item": "nfs-ganesha-rgw", 
    "rc": 126, 
    "results": [
        "No package matching 'nfs-ganesha-rgw' found available, installed or updated"
    ]
}
````

Is this intentional? Why?

Note, this may also affect other builds other than `ceph_dev`.

**Comment by guits** [comment]
@batrick could you provide the full playbook run log ?

**Comment by batrick** [comment]
@guits, I don't have the log anymore but the issue is straightforward. Specifically, here:

https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-nfs/tasks/pre_requisite_non_container.yml#L23

and

https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-nfs/tasks/pre_requisite_non_container.yml#L12

And these defaults:

https://github.com/ceph/ceph-ansible/blob/master/group_vars/all.yml.sample#L164
https://github.com/ceph/ceph-ansible/blob/master/group_vars/all.yml.sample#L237

For example, assuming every setting is default except `ceph_repository = dev`, no repository is setup for the `nfss` group.
