### ISSUE TITLE
Failed when 'TASK: [ceph-common | Check for a Ceph socket]'

### ISSUE THREAD

**Issue by ddxgz** [ceph/ceph-ansible#244]
I've tried several times, it always failed at TASK: [ceph-common | Check for a Ceph socket].
error output:
TASK: [ceph-common | Check for a Ceph socket] ********************************* 
failed: [mon1] => {"changed": true, "cmd": "stat /var/run/ceph/*.asok > /dev/null 2>&1", "delta": "0:00:00.001969", "end": "2015-04-08 03:56:01.522639", "rc": 1, "start": "2015-04-08 03:56:01.520670", "warnings": []}
...ignoring
failed: [osd0] => {"changed": true, "cmd": "stat /var/run/ceph/*.asok > /dev/null 2>&1", "delta": "0:00:00.001964", "end": "2015-04-08 03:56:01.535388", "rc": 1, "start": "2015-04-08 03:56:01.533424", "warnings": []}
...ignoring
failed: [mon2] => {"changed": true, "cmd": "stat /var/run/ceph/*.asok > /dev/null 2>&1", "delta": "0:00:00.001971", "end": "2015-04-08 03:56:01.551236", "rc": 1, "start": "2015-04-08 03:56:01.549265", "warnings": []}
...ignoring
failed: [mon0] => {"changed": true, "cmd": "stat /var/run/ceph/*.asok > /dev/null 2>&1", "delta": "0:00:00.002027", "end": "2015-04-08 03:56:01.657233", "rc": 1, "start": "2015-04-08 03:56:01.655206", "warnings": []}
...ignoring
failed: [osd1] => {"changed": true, "cmd": "stat /var/run/ceph/*.asok > /dev/null 2>&1", "delta": "0:00:00.002610", "end": "2015-04-08 03:56:01.592151", "rc": 1, "start": "2015-04-08 03:56:01.589541", "warnings": []}
...ignoring
failed: [osd2] => {"changed": true, "cmd": "stat /var/run/ceph/*.asok > /dev/null 2>&1", "delta": "0:00:00.001967", "end": "2015-04-08 03:56:01.660520", "rc": 1, "start": "2015-04-08 03:56:01.658553", "warnings": []}
...ignoring

Sometimes not all the nodes failed in this step. 
I did not change anything in the ceph-ansible dir, just vagrant up|provision.
Is there anyone can help me figure out where the problem is?

**Comment by leseb** [comment]
If it's the first time you bootstrap this is normal (since the services are not started there is no socket).
This error ignored anyway, this is not critical.
