### ISSUE TITLE
multi distro ceph cluster 

### ISSUE THREAD

**Issue by grharry** [ceph/ceph-ansible#2441]
Is it possible to add a client host but of a different distro ? 
My Ceph cluster is installed using Ubuntu Xenial on all nodes, I 've tried to add another host as a client running Debian stretch but ansible-ceph breaks with 

`FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'codename'\n\nThe error appears to have been in '/opt/latest-ceph/ceph-ansible/roles/ceph-common/tasks/installs/debian_community_repository.yml': line 7, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: configure debian ceph stable community repository\n  ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'dict object' has no attribute 'codename'"}
`

Harry.

**Comment by guits** [comment]
@grharry which ceph-ansible version are you using ?
Do you run ceph-ansible with the site.yml/site-docker.yml provided in the playbook ?

Could you provide the full playbook run log ?

**Comment by grharry** [comment]
Mea Culpa! 
Thanks!

**Comment by guits** [comment]
@grharry could have been nice to share the solution, perhaps someone could hit the same issue in the future.

**Comment by grharry** [comment]
Ansible was on an Ubuntu Xenial. 
OSDs, mgrs etc on Ubuntu Xenial. 
I just wanted to try a rados client on pre-existing  Debian  and it  broke with the message above. 

All I did was a clean debian install  from scratch.
