### ISSUE TITLE
osd_scenario variable can be dropped

### ISSUE THREAD

**Issue by vasukulkarni** [ceph/ceph-ansible#2447]
If a user declares dedicated_devices, that would mean its a non colocated scenario and there is no need for one to defined as such.

lvm uses lvm_volumes, so having to define scenario as lvm would be extra variable to set for admin.

**Comment by leseb** [comment]
`dedicated_devices` is always declared as an empty array. We could check its length and then drop `osd_scenario`. Let us think about that, thanks for the input @vasukulkarni

**Comment by vasukulkarni** [comment]
thanks @leseb

**Comment by alfredodeza** [comment]
Dropping `osd_scenario` would be a tremendous API regression. The whole colocation/non-colocation thing will end up going away once ceph-ansible transitions away from ceph-disk.

@vasukulkarni this situation is just transitional for now, and it would take a lot to prevent breakage everywhere just to accommodate dropping one variable.

**Comment by leseb** [comment]
@alfredodeza I don't think we have to drop it. We can simply set it on the fly. So the variable remains, but no one has to set it. ceph-ansible will detect it accordingly.

**Comment by guits** [comment]
As of stable-4.0 `osd_scenario` has been dropped
