### ISSUE TITLE
'osd_pool_default_pg_num' is undefined" in a sample deployment

### ISSUE THREAD

**Issue by JanoSicek** [ceph/ceph-ansible#2453]
I am trying to run examples form book "Learning Ceph" and I ran into big problem just trying a sample Ceph deployment in VM using this config:

Vagrant 2.0.3
Ansible 2.4.2.0
On branch stable-3.0

My changes:
site.yml = copy of site.yml.sample
vagrant_variables.yml = has these mods:
  mon_vms: 1
  client_vms: 1
group_vars/all.yml = has these mods:
  ceph_stable: True
  ceph_stable_release: luminous

These are all changes I did and after I execute it I get this error:

```
TASK [ceph-config : generate ceph configuration file: ceph.conf] ***************
[DEPRECATION WARNING]: ansible.utils.unicode.to_bytes is deprecated.  Use 
ansible.module_utils._text.to_bytes instead. This feature will be removed in 
version 2.4. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: ansible.utils.unicode.to_unicode is deprecated.  Use 
ansible.module_utils._text.to_text instead. This feature will be removed in 
version 2.4. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
fatal: [mon0]: FAILED! => {"msg": "{'name': 'vms', 'pg_num': '{{ osd_pool_default_pg_num }}', 'rule_name': ''}: 'osd_pool_default_pg_num' is undefined"}```

**Comment by guits** [comment]
can you paste : 
- the full content of group_vars/*.yml please ? `grep -Ev '(^#|^$)' group_vars/*.yml`
- your inventory host file
- a complete playbook run log if possible.

That would be helpful to help you.

Thanks!

**Comment by JanoSicek** [comment]
1. 
```dummy:
ceph_stable: True # backward compatibility with stable-2.2, will disappear in stable 3.1
ceph_stable_release: luminous```
2.
I dot not have any inventory host file, I use "Vagrant up"

3.
https://pastebin.com/fSyhjNFS

**Comment by thisismsreddy** [comment]
@JanoSicek , You can get around this issue by adding "osd_pool_default_pg_num: 128" to your Vagrantfile (ansible.extra_vars)

```
 ansible.extra_vars = {
      cluster_network: "#{CLUSTER_SUBNET}.0/24",
      journal_size: 100,
      public_network: "#{PUBLIC_SUBNET}.0/24",
      monitor_secret: "AQAPn8tUmPBwCxAAeIfvpDKA1fGvrBeXGdc6xQ==",
      osd_pool_default_pg_num: 128,
  }

```
