### ISSUE TITLE
vars validation

### ISSUE THREAD

**Issue by alfredodeza** [ceph/ceph-ansible#2457]
The current amount of variables in ceph-ansible, in addition to their relationships with one another makes it very complicated to try enforcing constraints with YAML as it is currently done in `check_mandatory_vars.yml`

The mandatory vars file does a good job at identifying a few, but it doesn't ever validate the tremendous amount of other options there are.

For ceph-installer [0] we used a validation engine called Notario [1] that allows to describe schemas for Python dictionaries. Since Ansible exposes these vars as a Python dictionary as well, Notario would be a good fit.

There are a couple of ways that Ansible grants access to the vars. For callback plugins it is a bit obscure:

    self.play._variable_manager._hostvars

But for action plugins it is straightforward if using `**kw` in the run method.

Using an Action plugin will allow ceph-ansible to define a lax or strict mode where variables can generate warnings, or halt execution of the whole play.

To fully take advantage of this approach, the action plugin would need to be created with Notario integration, and the schemas should be put in place. Maybe a good initial approach will be to have the action plugin with a few schemas to demonstrate the execution

[0] http://notario.cafepais.com/
[1] https://github.com/ceph/ceph-installer/blob/master/ceph_installer/schemas.py

**Comment by andrewschoen** [comment]
I like this idea. Should we start by picking an install option and/or osd scenario and writing schemas for those? We could pick a testing scenario and write the schemas needed for that test to validate, maybe https://github.com/ceph/ceph-ansible/tree/master/tests/functional/centos/7/lvm-osds or https://github.com/ceph/ceph-ansible/tree/master/tests/functional/centos/7/cluster

**Comment by guits** [comment]
since ceph-validate has been merged, we can close this issue.
