### ISSUE TITLE
ceph luminous with bluestore add osd failed

### ISSUE THREAD

**Issue by like-inspur** [ceph/ceph-ansible#2480]
I have created a ceph cluster environment, but one disk on one node and all disks on two nodes install failed. Now I want add failed osds to present environment, but ansible install output error like this:
failed: [ceph-58] (item=/dev/sdf) => {"changed": false, "cmd": ["ceph-disk", "activate", "/dev/sdf1"], "delta": "0:00:00.625780", "end": "2018-03-29 10:45:27.801482", "item": "/dev/sdf", "msg": "non-zero return code", "rc": 1, "start": "2018-03-29 10:45:27.175702", "stderr": "/usr/lib/python2.7/site-packages/ceph_disk/main.py:5653: UserWarning: \n*******************************************************************************\nThis tool is now deprecated in favor of ceph-volume.\nIt is recommended to use ceph-volume for OSD deployments. For details see:\n\n    http://docs.ceph.com/docs/master/ceph-volume/#migrating\n\n*******************************************************************************\n\n  warnings.warn(DEPRECATION_WARNING)\ncommand_with_stdin: Error EEXIST: entity osd.0 exists but key does not match\n\nmount_activate: Failed to activate\n'['ceph', '--cluster', 'ceph', '--name', 'client.bootstrap-osd', '--keyring', '/var/lib/ceph/bootstrap-osd/ceph.keyring', '-i', '-', 'osd', 'new', u'865b1295-0d7d-4088-8048-e196c9212049']' failed with status code 17", "stderr_lines": ["/usr/lib/python2.7/site-packages/ceph_disk/main.py:5653: UserWarning: ", "*******************************************************************************", "This tool is now deprecated in favor of ceph-volume.", "It is recommended to use ceph-volume for OSD deployments. For details see:", "", "    http://docs.ceph.com/docs/master/ceph-volume/#migrating", "", "*******************************************************************************", "", "  warnings.warn(DEPRECATION_WARNING)", "command_with_stdin: Error EEXIST: entity osd.0 exists but key does not match", "", "mount_activate: Failed to activate", "'['ceph', '--cluster', 'ceph', '--name', 'client.bootstrap-osd', '--keyring', '/var/lib/ceph/bootstrap-osd/ceph.keyring', '-i', '-', 'osd', 'new', u'865b1295-0d7d-4088-8048-e196c9212049']' failed with status code 17"], "stdout": "", "stdout_lines": []}

**Comment by like-inspur** [comment]
I have wipefs disks and execute ceph-deploy purge and purgedata on failed nodes, but problem still exists. @hunter @gbraad @dang @duritong @verdurin

**Comment by vishalkanaujia** [comment]
The error string `Error EEXIST: entity osd.0 exists but key does not match` means that the old OSD entry still lingers in your cluster. Run `ceph osd tree` and remove all OSDs under `default` root. Re-run ansible.

**Comment by like-inspur** [comment]
@vishalkanaujia  I know this is because the second installation will produce new key that dose not math first installation. Remove all OSDs can work , but how I achieve addition of OSDs after first installation. I think this is a big problem

**Comment by vishalkanaujia** [comment]
The problem here is that your old OSD auth details are with mon. If you remove the OSD entry and its auth keys, you should be able to add old OSDs.
`
$ sudo ceph osd rm osd.27
removed osd.27
$ sudo ceph auth del osd.17
updated
`

**Comment by like-inspur** [comment]
@vishalkanaujia I do this but osd.0 is still down.  And next installation outputs osd.1 error that like osd.0 error. So at last it will produce many osd, but none of these is up.

**Comment by like-inspur** [comment]
[root@icp-71 ~]# ceph osd tree
ID  CLASS WEIGHT   TYPE NAME       STATUS REWEIGHT PRI-AFF 
 -1       84.45911 root default                            
 -9       21.79590     host icp-57                         
  3   hdd  2.72449         osd.3       up  1.00000 1.00000 
  6   hdd  2.72449         osd.6       up  1.00000 1.00000 
 10   hdd  2.72449         osd.10      up  1.00000 1.00000 
 15   hdd  2.72449         osd.15      up  1.00000 1.00000 
 23   hdd  2.72449         osd.23      up  1.00000 1.00000 
 28   hdd  2.72449         osd.28      up  1.00000 1.00000 
 33   hdd  2.72449         osd.33      up  1.00000 1.00000 
 38   hdd  2.72449         osd.38      up  1.00000 1.00000 
 -3       19.07141     host icp-58                         
  7   hdd  2.72449         osd.7       up  1.00000 1.00000 
 12   hdd  2.72449         osd.12      up  1.00000 1.00000 
 16   hdd  2.72449         osd.16      up  1.00000 1.00000 
 21   hdd  2.72449         osd.21      up  1.00000 1.00000 
 26   hdd  2.72449         osd.26      up  1.00000 1.00000 
 32   hdd  2.72449         osd.32      up  1.00000 1.00000 
 37   hdd  2.72449         osd.37      up  1.00000 1.00000 
 -7       21.79590     host icp-60                         
  4   hdd  2.72449         osd.4       up  1.00000 1.00000 
  9   hdd  2.72449         osd.9       up  1.00000 1.00000 
 14   hdd  2.72449         osd.14      up  1.00000 1.00000 
 19   hdd  2.72449         osd.19      up  1.00000 1.00000 
 24   hdd  2.72449         osd.24      up  1.00000 1.00000 
 29   hdd  2.72449         osd.29      up  1.00000 1.00000 
 34   hdd  2.72449         osd.34      up  1.00000 1.00000 
 39   hdd  2.72449         osd.39      up  1.00000 1.00000 
-11       21.79590     host icp-61                         
 40   hdd  2.72449         osd.40      up  1.00000 1.00000 
 41   hdd  2.72449         osd.41      up  1.00000 1.00000 
 42   hdd  2.72449         osd.42      up  1.00000 1.00000 
 43   hdd  2.72449         osd.43      up  1.00000 1.00000 
 44   hdd  2.72449         osd.44      up  1.00000 1.00000 
 45   hdd  2.72449         osd.45      up  1.00000 1.00000 
 46   hdd  2.72449         osd.46      up  1.00000 1.00000 
 47   hdd  2.72449         osd.47      up  1.00000 1.00000 
  0              0 osd.0             down        0 1.00000 
  1              0 osd.1             down        0 1.00000

[root@icp-71 ~]# cat /etc/ceph/ceph.conf 
[mds.icp-72]
host = icp-72

[mds.icp-71]
host = icp-71

[global]
cluster network = 10.1.25.0/24
fsid = 25f46cd5-d6d0-48fc-b288-a6580c58a7ed
mon host = 10.1.25.71,10.1.25.72,10.1.25.73
mon initial members = icp-71,icp-72,icp-73
osd pool default pg num = 32
osd pool default pgp num = 32
public network = 10.1.25.0/24
rbd_default_features = 1

[osd]
enable experimental unrecoverable data corrupting features = bluestore rocksdb

[mds.icp-73]
host = icp-73

**Comment by zamasaki158** [comment]
you can try delete osd auth and add osd again.
ceph auth list
ceph auth del osd.0

**Comment by kobigi** [comment]
+1 ,  good observation 
indeed ceph auth del osd.[osd id]
did the job

**Comment by like-inspur** [comment]
I once did this operation, but doesn't work. Does it need to use newest version?

**Comment by shez1461** [comment]
$ ceph auth list
then 
$ ceph auth del osd.x

worked for me too.

**Comment by mcv21** [comment]
@like-inspur looks like you need to do `ceph osd rm osd.0`

**Comment by manoj-ms** [comment]
I have seen the same issue. However, lsblk shows that partition tables are already created. would deleting Auth and re-running the ansible playbook ( add-osd.yml) will cause issues? or should i manually delete all the partition table and re-run the playbook?

**Comment by liuqinfei** [comment]
> you can try delete osd auth and add osd again.
> ceph auth list
> ceph auth del osd.0
> it worked for me

I just solve by this!
