### ISSUE TITLE
ceph-rgw role and related tasks not performed ?

### ISSUE THREAD

**Issue by ColumGaynor** [ceph/ceph-ansible#2490]
Trying to install ceph-ansible ( branch stable-3.0-good ) with vagrant.
All expected VirtualBox VMs are created including the RGW0 node, but no ansible tasks associated with
role ceph-rgw seem to be executed!

ansible version = 2.3.1.0  (Host OS = Ubuntu 17.10)
Note: In the beginning of ansible.log file lots of "tasks" are statically included based on "roles" found under the roles directory, but oddly the ceph-rgw subdirectory related tasks are not statically included. The result is RGW0 node exists but none of the needed software is deployed there.
Tasks for other ceph roles whose sub-directories are found under the same roles directory work fine!

I am obviously making an error here but would appreciate a tip/idea what my error is.
Any tip would be appreciated as a total newcomer.

Files attached.
1. ansible.log file
[ansible.log](https://github.com/ceph/ceph-ansible/files/1872574/ansible.log)

2. zip file with hopefully needed ceph-ansible configuration files used
[ceph-ansible_selected_zipArchive.zip](https://github.com/ceph/ceph-ansible/files/1872678/ceph-ansible_selected_zipArchive.zip)

-Colum

``

**Comment by ColumGaynor** [comment]
Brief update...  
Seems the assumptions asserted in original text above are erroneous.
The problem appears to be that starting up of the **radosgw** daemon service on node rgw0 fails.
(Short extract from syslog file on rgw0 attached, which demonstrated this clearly.)
[short_extract_from_syslog.txt](https://github.com/ceph/ceph-ansible/files/1876951/short_extract_from_syslog.txt)

Looks similar to issued described earlier in issue: ("Unable to start Rados Gateway" #408) and similar failure messages as are reported in ceph-users mail list thread:
(https://www.mail-archive.com/ceph-users@lists.ceph.com/msg17051.html)

Suspect some issue related to the keyring files generated by ansible on node rgw0, but unsure how to resolve.
Any help / tips would be appreciated.

**Comment by vishalkanaujia** [comment]
Your radosgw daemon did come up, I can see that in logs. Could you please share the contents of `/etc/ceph/ceph.conf` file on the rgw0 host?

**Comment by vishalkanaujia** [comment]
are you still hitting this problem? Could you please update.

**Comment by ColumGaynor** [comment]
Sorry ... I gave up with the environment and took a fresh machine running ubuntu 18.04 and managed to get things working there. So closing it as unsolved mystery.
