### ISSUE TITLE
Initial OSD weight 

### ISSUE THREAD

**Issue by gmihaiescu** [ceph/ceph-ansible#252]
I'm trying to understand where the initial OSD weight is set as I would like to have the new OSDs added to the crush manually with a slowly increasing weight, but for this I would have to disable the automatic addition done by Ansible.

Thank you,
George

**Comment by leseb** [comment]
It's controlled by the following option: osd_crush_update_on_start

Look at roles/ceph-common/defaults/main.yml

**Comment by gmihaiescu** [comment]
Thanks, I saw it but I wasn't sure how it works.
