### ISSUE TITLE
Update Taks/ Playbook

### ISSUE THREAD

**Issue by vanthome** [ceph/ceph-ansible#253]
Any plans to support updating a ceph installation? I think this can be a very complex task juggling many deamons on many machines but it can potentially automated even with zero downtime I guess.

**Comment by leseb** [comment]
This is supported here: https://github.com/ceph/ceph-ansible/blob/master/rolling_update.yml

Please have a look at it. 
Closing this, feel free to reopen :)

**Comment by vanthome** [comment]
Sorry, didn't spot that although I looked trough it :/
