### ISSUE TITLE
fail when [ceph-mon:collect admin and bootstrap keys]

### ISSUE THREAD

**Issue by jinxiao** [ceph/ceph-ansible#2530]
ansible: v2.4.4.0
os: centos-7.4.1708
ceph-ansible: v3.0.30

> [WARNING]: when statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: ceph_release_num.{{ ceph_release }} >= ceph_release_num.luminous
 [WARNING]: when statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: ceph_release_num.{{ ceph_release }} >= ceph_release_num.luminous
 [WARNING]: when statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: ceph_release_num.{{ ceph_release }} >= ceph_release_num.luminous
fatal: [192.168.0.34]: FAILED! => {"changed": false, "cmd": ["ceph-create-keys", "--cluster", "ceph", "-i", "ceph-jx-2", "-t", "30"], "delta": "0:00:36.987453", "end": "2018-04-18 11:51:06.916667", "failed": true, "msg": "non-zero return code", "rc": 1, "start": "2018-04-18 11:50:29.929214", "stderr": "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nceph-mon was not able to join quorum within 0 seconds", "stderr_lines": ["INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "ceph-mon was not able to join quorum within 0 seconds"], "stdout": "", "stdout_lines": []}
fatal: [192.168.0.35]: FAILED! => {"changed": false, "cmd": ["ceph-create-keys", "--cluster", "ceph", "-i", "ceph-jx-3", "-t", "30"], "delta": "0:00:37.074080", "end": "2018-04-18 11:51:07.046113", "failed": true, "msg": "non-zero return code", "rc": 1, "start": "2018-04-18 11:50:29.972033", "stderr": "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nceph-mon was not able to join quorum within 0 seconds", "stderr_lines": ["INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "ceph-mon was not able to join quorum within 0 seconds"], "stdout": "", "stdout_lines": []}
fatal: [192.168.0.32]: FAILED! => {"changed": false, "cmd": ["ceph-create-keys", "--cluster", "ceph", "-i", "ceph-jx-1", "-t", "30"], "delta": "0:00:37.600903", "end": "2018-04-18 11:51:07.604598", "failed": true, "msg": "non-zero return code", "rc": 1, "start": "2018-04-18 11:50:30.003695", "stderr": "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nceph-mon was not able to join quorum within 0 seconds", "stderr_lines": ["INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "ceph-mon was not able to join quorum within 0 seconds"], "stdout": "", "stdout_lines": []}

i tried manually run cmd
it showed
> INFO:ceph-create-keys:ceph-mon admin socket not ready yet.

**Comment by leseb** [comment]
Monitors are not in quorum, please check the monitor service status and the logs.

**Comment by jangras** [comment]
hello Jinxiao, have same issue, did you resolve this? :)

**Comment by guits** [comment]
this can come from multiple reasons, could you share the service status and the logs ?

**Comment by jinxiao** [comment]
i think this is because i have not uncomment the dict 
`ceph_release_num:
#  dumpling: 0.67
#  emperor: 0.72
#  firefly: 0.80
#  giant: 0.87
  hammer: 0.94
  infernalis: 9
  jewel: 10
#  kraken: 11
  luminous: 12
#  mimic: 13
`

**Comment by wtwde** [comment]
@jinxiao  same issue, cloud you tell me how to solve?
