### ISSUE TITLE
ERROR:ceph-osd : manually prepare ceph "filestore" non-containerized osd disk(s) with collocated osd data and journal

### ISSUE THREAD

**Issue by RenWeiGuo0** [ceph/ceph-ansible#2538]
when I **ansible-playbook -vvv site.yml** -i hosts 
Error:TASK [**ceph-osd : manually prepare ceph "filestore" non-containerized osd disk(s) with collocated osd data and journa**l] 
    "start": "2018-04-20 15:14:31.653003", 
    "stderr": "usage: ceph-disk [-h] [-v] [--log-stdout] [--prepend-to-path PATH]\n                 [--statedir PATH] [--sysconfdir PATH] [--setuser USER]\n                 [--setgroup GROUP]\n                 \n                 {prepare,activate,activate-lockbox,activate-block,activate-journal,activate-all,list,suppress-activate,unsuppress-activate,deactivate,destroy,zap,trigger,fix}\n                 ...\nceph-disk: error: unrecognized arguments: --filestore", 
    "stderr_lines": [
        "usage: ceph-disk [-h] [-v] [--log-stdout] [--prepend-to-path PATH]", 
        "                 [--statedir PATH] [--sysconfdir PATH] [--setuser USER]", 
        "                 [--setgroup GROUP]", 
        "                 ", 
        "                 {prepare,activate,activate-lockbox,activate-block,activate-journal,activate-all,list,suppress-activate,unsuppress-activate,deactivate,destroy,zap,trigger,fix}", 
        "                 ...", 
        "**ceph-disk: error: unrecognized arguments: --filestore"**
    ], 
    "stdout": "", 
    "stdout_lines": []
}

I read it /ceph-ansible/ceph-ansible-3.0.0/roles/ceph-osd/tasks/scenarios/collocated.yml,
find  command: "ceph-disk prepare {{ ceph_disk_cli_options }} {{ item.1 }}"
 there is no filestore 
I dont unstand it ?
and I look for webiste http://docs.ceph.com/docs/hammer/man/8/ceph-disk/ and not find filestore .
so why?

**Comment by leseb** [comment]
Your doc links Hammer, are you trying to deploy Hammer?

**Comment by RenWeiGuo0** [comment]
This problem is  solved. I think its cause from **.repo**  My repo is no have L version.

**Comment by leseb** [comment]
Glad you solved your issue.
