### ISSUE TITLE
TASK: [ceph-mon | Create filesystem pools] -- FATAL: all hosts have already failed -- aborting

### ISSUE THREAD

**Issue by dfarrar117** [ceph/ceph-ansible#254]
The playbook seems to be failing at this point for me with a fresh git pull in vagrant (version 1.7.2) on an Ubuntu 14.04 x64 host with Virtualbox 4.3.10. 

Default vagrant box:
vagrant_box: ubuntu/trusty64

TASK: [ceph-mon | Create filesystem pools] ************************************ 
fatal: [mon1] => error while evaluating conditional: not ceph_containerized_deployment and not {{ceph_version.stdout | version_compare('0.84', '<')}} and mds
fatal: [mon2] => error while evaluating conditional: not ceph_containerized_deployment and not {{ceph_version.stdout | version_compare('0.84', '<')}} and mds
fatal: [mon0] => error while evaluating conditional: not ceph_containerized_deployment and not {{ceph_version.stdout | version_compare('0.84', '<')}} and mds

FATAL: all hosts have already failed -- aborting

**Comment by leseb** [comment]
Thanks for reporting, I'll try to reproduce this.

**Comment by leseb** [comment]
I can't reproduce this with Vagrant.
What's your unusable version?

**Comment by dfarrar117** [comment]
I'm using vagrant 1.7.2 with Ubuntu 14.04 as the host.  ceph version 0.94.1 is what was automatically pulled down.  

When I run "ceph -s" I get:
     health HEALTH_ERR
            64 pgs stuck inactive
            64 pgs stuck unclean
            no osds
            clock skew detected on mon.ceph-mon1
Not sure if the clock skew would cause the file system pools to fail?  Let me know if there's any other info that would be helpful.

**Comment by dfarrar117** [comment]
Nevermind, reran and got the same error with no "clock skew" this time.

**Comment by leseb** [comment]
All these errors are not connected, can you send the trace where the playbook fails?
