### ISSUE TITLE
infrastructure-playbooks/shrink-osd.yml leaves behind NVMe partition; scenario non-collocated

### ISSUE THREAD

**Issue by utp887** [ceph/ceph-ansible#2548]
Description of problem:

infrastructure-playbooks/shrink-osd.yml does not clean up NVME partitions w/scenario non-collocated.

Version-Release number of selected component (if applicable):
3.0 latest

How reproducible:
100%

Steps to Reproduce:
1. run shrink-osd.yml on non-collocated osd(NVME journal).
infrastructure-playbooks/shrink-osd.yml leaves behind NVMe partition; scenario non-collocated

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1572933

**Comment by guits** [comment]
@utp887 are you still experiencing issue using stable-3.2 ?
