### ISSUE TITLE
Playbook failing with "[Errno 2] No such file or directory", "rc": 2}

### ISSUE THREAD

**Issue by zieg8301** [ceph/ceph-ansible#2573]
Playbook version: stable-3.1
Ansible version: 2.4.2
Ceph: Luminous 12.2.2
OS: Centos 7.4.1708 (Core) 

Several tasks in the ansible playbook are failing with "[Errno 2] No such file or directory", "rc": 2. In many cases the command being run exists in /usr/sbin, and changing the command to the full path solves the issue.

Example in roles/ceph-osd/tasks/check_gpt.yml: blkid exists in /sbin and parted exists in /usr/sbin.

Full path is not ideal. Wondering if anyone else is running into this or if my env is messed up.

**Comment by guits** [comment]
Your environment must have something wrong.
For instance, our CI runs jobs with Centos 7.4 for a while now.

I remember having met someone who had this issue before, something was wrong with the way his env was provisioned and something in their ~/.bashrc or /etc/profile was messed up.

**Comment by andymcc** [comment]
It sounds like blkid isn't in the path for the user ansible is running as - you could try run "which blkid" as that user, to double check.

**Comment by zieg8301** [comment]
Will take a closer look at .bashrc, and /etc/profile. Thanks for the help.
