### ISSUE TITLE
"Get ceph monitor version" always returns 0 as exit code

### ISSUE THREAD

**Issue by alfredodeza** [ceph/ceph-ansible#258]
Even when it fails.

This happens because it is getting piped into cut:

    [vagrant@node2 ~]$ ceph daemon mon.node2 version | cut -d '"' -f 4 | cut -f 1,2 -d '.'
    admin_socket: exception getting command descriptions: [Errno 2] No such file or directory
    [vagrant@node2 ~]$ echo $?
    0

If the command instead is first called and then registered it would be able to catch the exit code (probably `22`):

    - name: Get Ceph monitor version
      shell: ceph daemon mon."{{ ansible_hostname }}" version | cut -d '"' -f 4 | cut -f 1,2 -d '.'
      register: ceph_monitor_version_raw
      changed_when: False
    
    
    - name: Set ceph version
      # ceph version output should be like
      # ceph version 0.94.1 (e4bfad3a3c51054df7e537a724c8d0bf9be972ff)
      set_fact: ceph_version="{{ ceph_monitor_version_raw.split()[2] }}"

**Comment by alfredodeza** [comment]
My example doesn't quite work. I will provide a PR once I figure this one out.

**Comment by leseb** [comment]
Thanks!

**Comment by leseb** [comment]
Just thought about this, perhaps we can use the `${PIPESTATUS}` variable and register it.
Example:

```bash
[root@ceph-eno5 ~]# ceph daemon mon.node2 version | cut -d '"' -f 4 | cut -f 1,2 -d '.'
admin_socket: exception getting command descriptions: [Errno 2] No such file or directory
[root@ceph-eno5 ~]# echo "The exit status of first command ${PIPESTATUS[0]}, and the second command ${PIPESTATUS[1]}"
The exit status of first command 22, and the second command 0
```

**Comment by leseb** [comment]
Actually something easier might be:

`failed_when: "'No such file or directory' in command_result.stderr"`

**Comment by alfredodeza** [comment]
@leseb thank you sir! that is definitely better/cleaner than doing odd shell piping
