### ISSUE TITLE
RFE: Create VDO volumes for OSDs

### ISSUE THREAD

**Issue by donnydavis** [ceph/ceph-ansible#2580]
This RFE is to ask that ceph-ansible create a vdo volume for each OSD.

**Comment by leseb** [comment]
This is in-progress.

**Comment by donnydavis** [comment]
Has there been any updates to the status of VDO and ceph-ansible?

**Comment by dsavineau** [comment]
Please see https://bugzilla.redhat.com/show_bug.cgi?id=1550278
