### ISSUE TITLE
default to ceph-volume, discourage ceph-disk usage

### ISSUE THREAD

**Issue by alfredodeza** [ceph/ceph-ansible#2622]
The first stable release for Mimic should come at the end of May or early June, although currently ceph-ansible is not defaulting to either one, it appears as if ceph-disk is thoroughly supported/encouraged.

A rework of the options in group_vars for the "osd scenarios" should be done, in such a way that the ceph-volume is the obvious choice and ceph-disk is discouraged. Probably through heavy commenting in both all.yml and osds.yml samples.

The deprecation notice in ceph-disk is enabled for master and Mimic, and ceph-disk is frozen (no new development going on), full removal is expected by the N release.

https://www.spinics.net/lists/ceph-devel/msg41420.html

**Comment by leseb** [comment]
@alfredodeza Do you have a BZ for that? This is tremendous work, so PMs must vote and prioritize this. We really have to start organizing resources to complete this work.

**Comment by alfredodeza** [comment]
There is no BZ for this, do note that ceph-disk is about to get removed from master (See linked email from ceph-devel)

**Comment by leseb** [comment]
https://github.com/ceph/ceph/pull/22343

**Comment by alfredodeza** [comment]
ceph-disk just got fully removed from master

**Comment by leseb** [comment]
@alfredodeza can ceph-volume detect ceph-disk prepared OSDs and report them? Thanks.

**Comment by alfredodeza** [comment]
Yes, that is correct. It has three options to do that:

* If the input is the data partition, it will mount it temporarily to parse contents inside
* if the input is the running OSD, it will just parse the path contents directly
* if the input is the data partition and it is mounted it will check where that is and parse the contents

The `prepare` step in ceph-disk gets the OSD ready up until the point before actually running the OSD. This is sufficient for ceph-volume to manage it.

**Comment by leseb** [comment]
Thanks, I guess I wasn't clear enough, do we have a command like `ceph-volume lvm list` that could list OSDs that were prepared with `ceph-disk`?
Thanks!

**Comment by alfredodeza** [comment]
No, that is not possible. An input is required which can be the path to the running OSD, or the data device.

**Comment by leseb** [comment]
That's too bad, it'd useful to have something like this so when we scan devices we know if they are OSDs prepared with `ceph-disk` and part of the existing cluster. Particularly useful for `choose_disk` and potentially other systems that want to determine if a disk is from Ceph.

Now 2 questions:

1. A question that comes to my mind, if we take over an OSD with the `simple` command, will the OSD be listed with `ceph-volume lvm list`?

2. If 1. is 'no', do you think this is something you might consider implementing?
I can open a tracker for this.

Thanks.

**Comment by alfredodeza** [comment]
they will not be listed with `ceph-volume lvm list` because that command lists OSDs created by `lvm`, ceph-disk is not created by that command so it can't produce a list.

To list OSDs that have been taken over one would just need to look in `/etc/ceph/osd/*.json` (by default). Although the location can be altered, which is why we can't provide a list that will work reliably in all cases

I am not sure why choose_disk would need to know about this. What consumers need is disks that can be used, not if the disk has a partition from ceph-disk?

Maybe a meeting to clarify this is better, since this doesn't seem to involve discouraging ceph-disk usage anymore

**Comment by leseb** [comment]
@alfredodeza invit sent!

**Comment by ErwanAliasr1** [comment]
I tried to warn about this situation in https://github.com/ceph/ceph/pull/22343#pullrequestreview-128765965 
Let's discuss this in the meeting then.

**Comment by k0ste** [comment]
@alfredodeza @leseb when `ceph-ansible` will be switched to `ceph-volume`, community is need to know how-to properly migrate current `ceph-ansible` deployments (some doc or playbook). Thanks.

**Comment by guits** [comment]
ceph-disk has been dropped as of stable-4.0, closing this issue.
