### ISSUE TITLE
contributing guidelines for commit messages

### ISSUE THREAD

**Issue by alfredodeza** [ceph/ceph-ansible#2623]
Seems like the ceph-ansible project is requiring some structure for commit messages (from pr #2621) . For new contributors, there is no such mention in the docs, and although there is a 'dev' section, there is nothing about commit messages needing to comply with certain guidelines.

Github allows repositories to have ["Guidelines" for contributors to follow](https://help.github.com/articles/setting-guidelines-for-repository-contributors/), which might make sense to have in addition for an update on docs. The Ceph and ceph-deploy projects have the guidelines that can be used as a base/example if needed.

This will also help the maintainers as there will be no need to comment what these guidelines are each time.

**Comment by ErwanAliasr1** [comment]
That is supposed to be a classical way of making clean commits to help others. I can suggest we reuse what we wrote for ceph-container. This way it will be explicit.

https://github.com/ceph/ceph-container/blob/master/CONTRIBUTING.md#commit-guidelines

**Comment by leseb** [comment]
@ErwanAliasr1 Sounds good to me.
Although guidelines are important they won't prevent people not following them, in addition, we need a validation from our CI.

**Comment by guits** [comment]
a guidelines has been added, we can close this.
