### ISSUE TITLE
"transparent hugepage" task fails on ansible 2.5.3

### ISSUE THREAD

**Issue by alfredodeza** [ceph/ceph-ansible#2629]
ceph-volume tests tried to run with the top-level `requirements.txt` and started failing (both CentOS7 and Xenial) on ceph-ansible master with:

    TASK [ceph-osd : disable transparent hugepage] *********************************
    task path: /tmp/tox.usPB2V6tvB/centos7-filestore-activate/tmp/ceph-ansible/roles/ceph-osd/tasks/system_tuning.yml:33
    fatal: [osd0]: FAILED! => {
        "changed": false, 
        "checksum": "c2fa1ea2403821dbbc293a7dfc0bc12be139bed4", 
        "exit_status": 1
    }
    
    MSG:
    
    failed to validate
    fatal: [osd1]: FAILED! => {
        "changed": false, 
        "checksum": "c2fa1ea2403821dbbc293a7dfc0bc12be139bed4", 
        "exit_status": 1
    }
    
    MSG:
    
    failed to validate

The same run, with Ansible 2.4 works without issues:

    changed: [osd0] => {
        "changed": true,
        "checksum": "c2fa1ea2403821dbbc293a7dfc0bc12be139bed4",
        "dest": "/etc/tmpfiles.d/ceph_transparent_hugepage.conf",
        "diff": [],
        "failed": false,
        "gid": 0,
        "group": "root",
        "invocation": {
            "module_args": {
                "attributes": null,
                "backup": false,
                "content": null,
                "delimiter": null,
                "dest": "/etc/tmpfiles.d/ceph_transparent_hugepage.conf",
                "directory_mode": null,
                "follow": false,
                "force": true,
                "group": "root",
                "local_follow": null,
                "mode": "0644",
                "original_basename": "tmpfiles_hugepage.j2",
                "owner": "root",
                "regexp": null,
                "remote_src": null,
                "selevel": null,
                "serole": null,
                "setype": null,
                "seuser": null,
                "src": "/home/vagrant/.ansible/tmp/ansible-tmp-1527076495.61-204062911476136/source",
                "unsafe_writes": null,
                "validate": "systemd-tmpfiles --create %s"
            }
        },
        "md5sum": "cbe8f482777cfcb639343245d7cdb81e",
        "mode": "0644",
        "owner": "root",
        "size": 79,
        "src": "/home/vagrant/.ansible/tmp/ansible-tmp-1527076495.61-204062911476136/source",
        "state": "file",
        "uid": 0
    }

**Comment by alfredodeza** [comment]
BZ https://bugzilla.redhat.com/show_bug.cgi?id=1583684

**Comment by guits** [comment]
@alfredodeza This bug doesn't happen anymore in ansible 2.5.5
