### ISSUE TITLE
top-level requirements.txt does not pin dependencies

### ISSUE THREAD

**Issue by alfredodeza** [ceph/ceph-ansible#2631]
The top-level `requirements.txt` does not pin Ansible version, using instead:

    ansible>=2.4.2

At the time of this writing, this will install `2.5.3` which is causing breakage on vanilla deployments for both Xenial and CentOS7. Other projects that install ceph-ansible for testing that want to make use of the dependencies listed for ceph-ansible will break (teuthology, ceph-medic, ceph-volume, etc...) 

I think that the top level requirements.txt should go hand in hand with whatever the branch is willing to support. For example, if the stable-2.5 branch works with ansible 2.2, then it should pin to that version (or a range if that is desired). 

For the *master* branch, it should be probably the latest Ansible version that will be used in the next stable release. In this case, I think that would be Ansible 2.5

Having these dependencies pinned will ease the burden of other projects to just blindly depend on what ceph-ansible can support, regardless of the branch.

It however imposes that burden on the ceph-ansible team, as this would be another thing that needs to get updated continuously to make sure that dependencies are correct as time goes by.

**Comment by ktdreyer** [comment]
For the RH Ceph Storage product, it would be very helpful if the pinned values matched the latest packages that are available in RHEL's repositories. For example `rhel-7-server-ansible-2.4-rpms` has 
ansible-2.4.4.0-1.el7ae.noarch.rpm.

Maybe the ceph-ansible CI system could use ansible RPMs instead of PyPI packages.
