### ISSUE TITLE
[ERROR]: The python-notario library is missing. Please install it to continue.

### ISSUE THREAD

**Issue by necarnot** [ceph/ceph-ansible#2649]
Hello,

Using ceph-ansible upd-to-date github clone and the dev repo, CentOS 7.4, running ansible-playbook site.yml leads me to : 
[ERROR]: The python-notario library is missing. Please install it to continue.

I can not install is manually, because of yum priority protections and personal lack of knowledge.

On the first host for it is witnessed, I see that /etc/yum.repos.d contains : 

ls -la /etc/yum.repos.d/ceph-dev.repo*
-rw-r--r-- 1 root root 588 12 avril 16:25 /etc/yum.repos.d/ceph-dev.repo
-rw-r--r-- 1 root root 588 11 avril 12:34 /etc/yum.repos.d/ceph-dev.repo.101266.2018-04-12@15:27:27~
-rw-r--r-- 1 root root 588 12 avril 15:27 /etc/yum.repos.d/ceph-dev.repo.110475.2018-04-12@16:25:44~
-rw-r--r-- 1 root root 588 30 mars  16:11 /etc/yum.repos.d/ceph-dev.repo.2183.2018-04-10@16:43:15~
-rw-r--r-- 1 root root 588 10 avril 16:43 /etc/yum.repos.d/ceph-dev.repo.31913.2018-04-11@09:36:49~
-rw-r--r-- 1 root root 588 11 avril 09:36 /etc/yum.repos.d/ceph-dev.repo.40742.2018-04-11@12:34:50~

and wondering if this is normal?

In another github issue, I found that python-notario was used by the test framework of ceph (whose name I'm forgetting). Is there a way to bypass this?

Thank you.

**Comment by guits** [comment]
@necarnot you need to install python-notario on the host running ceph-ansible, AFAIK, there is no rpm available in centos repositories, you have to install from `pip install python-notario`

**Comment by necarnot** [comment]
@guits  Thank you Guillaume, that did the trick.
Could we agree to say that the error message is not very helpful :  I was thinking this package was missing on the target hosts, not on the admin host.

**Comment by guits** [comment]
I would agree, if you misunderstood that message, it means it's not absolutely clear for everyone apparently :-)

**Comment by leseb** [comment]
Closing this since the issue has been resolved.

**Comment by leseb** [comment]
@rahulait what's your error?

**Comment by xs233** [comment]
I can't install python-notario.Anyone can help me?

[root@localhost ceph-ansible]# pip install python-notario
Collecting python-notario
  Could not find a version that satisfies the requirement python-notario (from versions: )
No matching distribution found for python-notario

**Comment by leseb** [comment]
@alfredodeza please assist @xs233 thanks.

**Comment by alfredodeza** [comment]
The *system package* is `python-notario`

The *python package* is `notario`

That means that for pip, it should be:

    pip install notario

**Comment by andrewschoen** [comment]
You can also use the requirements.txt file provided by ceph-ansible. This
will also install ansible as well though.
https://github.com/ceph/ceph-ansible/blob/master/requirements.txt

Docs for this installation method are here:
http://docs.ceph.com/ceph-ansible/master/#installation

**Comment by rahulait** [comment]
@leseb I see these errors:

TASK [ceph-defaults : create ceph initial directories] ********************************************************************************
Friday 08 June 2018  09:56:17 -0400 (0:00:00.115)       0:00:08.996 ***********
ok: [192.168.10.10] => (item=/etc/ceph)
ok: [192.168.10.11] => (item=/etc/ceph)
ok: [192.168.10.10] => (item=/var/lib/ceph/)
ok: [192.168.10.11] => (item=/var/lib/ceph/)
ok: [192.168.10.10] => (item=/var/lib/ceph/mon)
ok: [192.168.10.11] => (item=/var/lib/ceph/mon)
ok: [192.168.10.10] => (item=/var/lib/ceph/osd)
ok: [192.168.10.11] => (item=/var/lib/ceph/osd)
ok: [192.168.10.10] => (item=/var/lib/ceph/mds)
ok: [192.168.10.11] => (item=/var/lib/ceph/mds)
ok: [192.168.10.10] => (item=/var/lib/ceph/tmp)
ok: [192.168.10.11] => (item=/var/lib/ceph/tmp)
ok: [192.168.10.11] => (item=/var/lib/ceph/radosgw)
ok: [192.168.10.10] => (item=/var/lib/ceph/radosgw)
ok: [192.168.10.11] => (item=/var/lib/ceph/bootstrap-rgw)
ok: [192.168.10.10] => (item=/var/lib/ceph/bootstrap-rgw)
ok: [192.168.10.11] => (item=/var/lib/ceph/bootstrap-mds)
ok: [192.168.10.10] => (item=/var/lib/ceph/bootstrap-mds)
ok: [192.168.10.11] => (item=/var/lib/ceph/bootstrap-osd)
ok: [192.168.10.10] => (item=/var/lib/ceph/bootstrap-osd)
ok: [192.168.10.11] => (item=/var/lib/ceph/bootstrap-rbd)
ok: [192.168.10.10] => (item=/var/lib/ceph/bootstrap-rbd)
ok: [192.168.10.10] => (item=/var/run/ceph)
ok: [192.168.10.11] => (item=/var/run/ceph)
 [ERROR]: The python-notario library is missing. Please install it to continue.

The python-notario library is missing. Please install it to continue.

On that machine, I do have notario installed:
ubuntu@vm-ceph3:~$ python
Python 2.7.12 (default, Dec  4 2017, 14:50:18)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import notario
>>> notario.__version__
'0.0.13'
>>>

ubuntu@vm-ceph3:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
ubuntu@vm-ceph3:~$

I am using http://cloud-images.ubuntu.com/releases/xenial/release/ubuntu-16.04-server-cloudimg-amd64-disk1.img image for the ceph nodes.

**Comment by andrewschoen** [comment]
On Fri, Jun 8, 2018 at 9:44 AM, Rahul Sharma <notifications@github.com>
wrote:

> @leseb <https://github.com/leseb> I see these errors:
>
> TASK [ceph-defaults : create ceph initial directories]
> ************************************************************
> ********************
> Friday 08 June 2018 09:56:17 -0400 (0:00:00.115) 0:00:08.996 ***********
> ok: [192.168.10.10] => (item=/etc/ceph)
> ok: [192.168.10.11] => (item=/etc/ceph)
> ok: [192.168.10.10] => (item=/var/lib/ceph/)
> ok: [192.168.10.11] => (item=/var/lib/ceph/)
> ok: [192.168.10.10] => (item=/var/lib/ceph/mon)
> ok: [192.168.10.11] => (item=/var/lib/ceph/mon)
> ok: [192.168.10.10] => (item=/var/lib/ceph/osd)
> ok: [192.168.10.11] => (item=/var/lib/ceph/osd)
> ok: [192.168.10.10] => (item=/var/lib/ceph/mds)
> ok: [192.168.10.11] => (item=/var/lib/ceph/mds)
> ok: [192.168.10.10] => (item=/var/lib/ceph/tmp)
> ok: [192.168.10.11] => (item=/var/lib/ceph/tmp)
> ok: [192.168.10.11] => (item=/var/lib/ceph/radosgw)
> ok: [192.168.10.10] => (item=/var/lib/ceph/radosgw)
> ok: [192.168.10.11] => (item=/var/lib/ceph/bootstrap-rgw)
> ok: [192.168.10.10] => (item=/var/lib/ceph/bootstrap-rgw)
> ok: [192.168.10.11] => (item=/var/lib/ceph/bootstrap-mds)
> ok: [192.168.10.10] => (item=/var/lib/ceph/bootstrap-mds)
> ok: [192.168.10.11] => (item=/var/lib/ceph/bootstrap-osd)
> ok: [192.168.10.10] => (item=/var/lib/ceph/bootstrap-osd)
> ok: [192.168.10.11] => (item=/var/lib/ceph/bootstrap-rbd)
> ok: [192.168.10.10] => (item=/var/lib/ceph/bootstrap-rbd)
> ok: [192.168.10.10] => (item=/var/run/ceph)
> ok: [192.168.10.11] => (item=/var/run/ceph)
> [ERROR]: The python-notario library is missing. Please install it to
> continue.
>
> The python-notario library is missing. Please install it to continue.
>
> On that machine, I do have notario installed:
> ubuntu@vm-ceph3:~$ python
> Python 2.7.12 (default, Dec 4 2017, 14:50:18)
> [GCC 5.4.0 20160609] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
>
> import notario
> notario.*version*
> '0.0.13'
>
>
And this is on the node you are running the ceph-ansible playbook from or a
ceph node you are trying to provision? They notario library must be
installed on the node you run ceph-ansible from, not the nodes being
configured. Are you using any python virtual environments that would keep
notario from being accessed here by ceph-ansible on the installer node?
