### ISSUE TITLE
yum repositories failures in CI

### ISSUE THREAD

**Issue by guits** [ceph/ceph-ansible#2666]
For a while, we are seeing too many yum repositories failure in the CI.

#2665 and #2652 have been created in the hope of fixing these failures but this is probably not enough.

This issue aims to track what has been done or is ongoing in order to fix these failures

**Comment by djgalloway** [comment]
http://apt-mirror.front.sepia.ceph.com/epel7/ can be used for epel.  CentOS is still syncing.

**Comment by ktdreyer** [comment]
Have we reported this to the Fedora / EPEL projects?

**Comment by ErwanAliasr1** [comment]
@djgalloway will the resync will be automatic ?
Thanks for the quick response

**Comment by ErwanAliasr1** [comment]
@ktdreyer we are not so sure about the real reason for now but it sounds like some mirrors might have quality issue. I'm not so sure that Fedora/Epel is handling the quality of every mirror. And that is not uncommon to have a local repo for better performance.

**Comment by guits** [comment]
@djgalloway thanks!

**Comment by djgalloway** [comment]
> will the resync will be automatic ?

After this initial sync is finished, I'll have the repos updated daily.

**Comment by guits** [comment]
@djgalloway just curious, how will they be updated?

**Comment by djgalloway** [comment]
Using `reposync` and `createrepo` for epel and a simple rsync for CentOS.

**Comment by ErwanAliasr1** [comment]
@djgalloway it's important that rpms doesn't vanish during the rsync (which might take some time). How do you handle repo's integrity during the update ?

**Comment by djgalloway** [comment]
It's a problem you're going to run into with any repo mirror AFAIK.  The best I can do is add `--delete-after` to the rsync so packages only get deleted all at once at the end of the rsync.

**Comment by ErwanAliasr1** [comment]
That would be much better ! Thx.

**Comment by djgalloway** [comment]
For EPEL, the repo is synced to a local dir then rsynced (locally) to the publicly-accessible directory so that should minimize problems.

The CentOS sync just finished as well: http://apt-mirror.front.sepia.ceph.com/centos/7.5.1804/os/x86_64/

**Comment by guits** [comment]
we didn't see these failures for a while now, looks like we've improved things 👍 

special thanks to @djgalloway @ErwanAliasr1 for your more than quick reactivity, really appreciate!
