### ISSUE TITLE
unable to parse version 'dummy' 

### ISSUE THREAD

**Issue by alfredodeza** [ceph/ceph-ansible#2692]
Similar to issue #2671 that fixed the missing parsing for mimic, we are now seeing the same error:

    The conditional check 'ceph_release_num[ceph_release] >= ceph_release_num.luminous' failed. 
    The error was: error while evaluating conditional 
        (ceph_release_num[ceph_release] >= ceph_release_num.luminous): 'dict object' has no attribute u'dummy'

This is happening because commit db50aec13d1575db0ab7df3a802353a508c55f3f added a conditional for manager ports that wants to compare at the ceph_release *before* ceph-ansible has set the fact for `ceph --version`

This went undetected in the pull request because the only functional test that ran was "luminous 2.4 CentOS 7 cluster" 

It would be nice to see tests that use ceph's master or similar to help prevent issues like this, running on ceph-ansible pull requests

**Comment by alfredodeza** [comment]
The full report on the task is:

    TASK [ceph-common : open manager ports] ****************************************
    task path: /tmp/tox.moPfWD9oeV/centos7-filestore-activate/tmp/ceph-ansible/roles/ceph-common/tasks/misc/configure_firewall_rpm.yml:28
    fatal: [mon0]: FAILED! => {
        "failed": true
    }
    
    MSG:
    
    The conditional check 'ceph_release_num[ceph_release] >= ceph_release_num.luminous' failed. The error was: error while evaluating conditional (ceph_release_num[ceph_release] >= ceph_release_num.luminous): 'dict object' has no attribute u'dummy'
    
    The error appears to have been in '/tmp/tox.moPfWD9oeV/centos7-filestore-activate/tmp/ceph-ansible/roles/ceph-common/tasks/misc/configure_firewall_rpm.yml': line 28, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.
    
    The offending line appears to be:
    
    
    - name: open manager ports
      ^ here


And an example of a failed run can be found in https://jenkins.ceph.com/view/ceph-volume%20master%20nightly/job/ceph-volume-nightly-master-simple-centos7-filestore-activate/112/console

**Comment by guits** [comment]
closed by #2693
