### ISSUE TITLE
Generate ceph.conf locally from ansible host

### ISSUE THREAD

**Issue by haphan** [ceph/ceph-ansible#2697]
We currently fetching keyrings from monitor using `ceph-fetch-keys`, it'd be useful to fetch `ceph.conf` and `ceph.d/*` configuration to ansible server node.

The use case at the moment is that `clients` group is unnecessary and can be easily replaced by a container which mounted a working `ceph.conf`.
@andrewschoen  @leseb

**Comment by leseb** [comment]
The `ceph-fetch-keys` script gets Ceph's keys from the monitors and writes them on the filesystem.
Why should we fetch it when we can generate it?

Are you trying to simplify the client role?

**Comment by haphan** [comment]
@leseb You are right. I think it is better  to generate `ceph.conf` locally. 

My goal is to enable ansible host to manage ceph cluster. Right now we already have the keyring, the only thing missing is `ceph.conf`

**Comment by guits** [comment]
Fixed by #2700
