### ISSUE TITLE
run_once in gather and delegate facts

### ISSUE THREAD

**Issue by TamizharasiS** [ceph/ceph-ansible#2708]
file-name: ceph-ansible/infrastructure-playbooks/rolling_update.yml
task-name: gather and delegate facts

As per the discussion over, fact gathering optimization for scalability #2553
I think we should have run_once: true in the rolling_update.yml fact gathering too.

  - name: gather and delegate facts
      setup:
      delegate_to: "{{ item }}"
      delegate_facts: True
      with_items: "{{ groups['all'] }}"
      when:
        - delegate_facts_host | bool

We should have the run_once set in this task this way. Isn't it?

  - name: gather and delegate facts
      setup:
      delegate_to: "{{ item }}"
      delegate_facts: True
	  run_once: True
      with_items: "{{ groups['all'] }}"
      when:
        - delegate_facts_host | bool

**Comment by guits** [comment]
@TamizharasiS that's correct, thanks for reporting this
