### ISSUE TITLE
re-run of the roles in the rolling_update.yml for each node type

### ISSUE THREAD

**Issue by TamizharasiS** [ceph/ceph-ansible#2709]
file-name: ceph-ansible/infrastructure-playbooks/rolling_update.yml

My concern here is, why do we have to run the roles again for each cluster component during the rolling_update. Shouldn't the rolling update be just a service stop, upgrade ceph packages and then start the service?

In the playbook, rolling_update.yml we have the roles to be run for each node type.
Example:

for ceph-osd

 roles:
    - ceph-defaults
    - { role: ceph-common, when: not containerized_deployment }
    - { role: ceph-docker-common, when: containerized_deployment }
    - ceph-config
    - ceph-osd

for ceph-mon

roles:
    - ceph-defaults
    - { role: ceph-common, when: not containerized_deployment }
    - { role: ceph-docker-common, when: containerized_deployment }
    - ceph-config
    - ceph-mon
	
Similarly for mgrs, rgws, and all other types of hosts.

These roles must have already been run on the specific nodes during the cluster setup.
And a rolling update is performed only on an established and configured cluster, 
isn't re-running the roles redundant and time consuming?
regenerating the config on every node, is it really required even for a minor upgrade?
Probably, it is required incase of a major upgrade??

Also, I have tested the rolling_update.yml on a test cluster to upgrade from
12.2.4 to 12.2.5 (luminous minor version upgrade) with roles removed. ie., a service stop, update packages and a service stop. And it worked perfectly and it was much faster too relatively.

 Please help me understand if am missing something 
Otherwise, we should enhance rolling_update.yml to not do redundant jobs.

**Comment by leseb** [comment]
Although this makes sense, running the entire role for new daemons makes sense, e.g: the ceph-mgr and maybe more in the future. Of course, this could be added as an exception and rework the other pieces.
Running the following might just be enough:

```
roles:
- ceph-defaults
- { role: ceph-common, when: not containerized_deployment }
- { role: ceph-docker-common, when: containerized_deployment }
- ceph-config
```

We have to investigate that, but we have no bandwidth to provide some code at the moment, so PR welcome.
Thanks.

**Comment by TamizharasiS** [comment]
Correct, however adding new daemons happens in a major release upgrade.

adding new things incase of a major release can be split into 2 steps,
1. add new daemons i.e., run only that specific tasks/roles
2. then run rolling_update(without roles) on all nodes.
Or
Probably, we should have a flag to decide if roles has to be run or not for each node type.

But re-run of roles on already configured osds, mons and rgws is actually not required and we can save a lot of time and also avoid running into some other issues.

Will raise a PR for this soon.
Thank you.
