### ISSUE TITLE
Ceph multipath disk issues (partition detection and symlink resolving)

### ISSUE THREAD

**Issue by keeperofdakeys** [ceph/ceph-ansible#2717]
I've recently deployed ceph on a cluster using disks supplied using multipath fibre channel links. I've run into a few issues that I've worked around in my install. If these can be fixed in a generic way, I'd be willing to turn them into a PR.

The way multipathd is configured, each disk appears like this:

> /dev/mapper/36005076400810224b00000000000001a
> /dev/mapper/36005076400810224b000000000000018
> /dev/mapper/36005076400810224b000000000000019

Some issues I've found:

### Partition detection is broken:

The file `roles/ceph-osd/tasks/activate_osds.yml` has detection for when 'p' or '-part' is needed to reference partitions for a device. These rules are totally broken for devices that appear like the above. This is how partitions actually appear on the host:

> /dev/mapper/36005076400810224b00000000000001a1
> /dev/mapper/36005076400810224b00000000000001a2
> /dev/mapper/36005076400810224b000000000000018p2
> /dev/mapper/36005076400810224b000000000000018p1
> /dev/mapper/36005076400810224b000000000000019p1
> /dev/mapper/36005076400810224b000000000000019p2

From what I can gather from searching online, a "p" is only added for partitions if the device ends with a number. I assume the "-part" syntax is only needed within "/dev/disk/by-*" directories.

I've managed to fix the rule by changing the first command in `activate-osds.yml` to this:
>  ceph-disk activate "{{ item }}{%- if item | regex_search('[0-9]$') %}{{ 'p' }}{%- endif %}{%- if 'mpath' in item %}{{ '-part' }}{%- endif %}{{ '1' }}"

### Symlinks being followed breaks the install.

The devices in /dev/mapper are symlinks to device mapper entries. IE:

> [root@host1 /]# stat /dev/mapper/36005076400810224b000000000000018
>   File: ‘/dev/mapper/36005076400810224b000000000000018’ -> ‘../dm-4’
>   Size: 7         	Blocks: 0          IO Block: 4096   symbolic link

Ceph-ansible tries to enumerate these device mapper symlinks, and call ceph-activate on them. To workaround this I modified the `roles/ceph-defaults/tasks/facts.yml` file to simply not append the resolved symlinks. I'm not really sure why this is done, so I'm not sure how to go about fixing this.

**Comment by leseb** [comment]
@keeperofdakeys thanks for the detailed issue.

The first fix sounds good, you can go ahead and submit a PR for this. Thanks.

For the second one, can be more specific, where is this breaking? We resolve the devices name so we can come up with a decent container name that has its device as a name.

**Comment by keeperofdakeys** [comment]
For the symlinks, I think the issue is that usually devices in /dev/mapper are virtual devices symlinked to device mapper entries (LVM LVs, dmcrypt devices, multipath devices, etc). For the purposes of naming, the /dev/mapper entries should be the preferred entry.

Would it be useful to either:
1. Not resolve symlinks that start with "/dev/mapper".
2. Ignore the results of resolving devices when they point to device mapper entries " .. ->  /dev/dm-*".

**Comment by leseb** [comment]
A third option would be to start naming the osd with its osd.id and not its associated device.
