### ISSUE TITLE
Update master/tests/functional/centos/7/ooo-collocation/hosts

### ISSUE THREAD

**Issue by gfidente** [ceph/ceph-ansible#2731]
I reviewed master/tests/functional/centos/7/ooo-collocation/hosts and it seems to have diverged from what is used in OOO

**Comment by gfidente** [comment]
https://github.com/ceph/ceph-ansible/blob/5eacc8f8d8ce20fc187471a79543bbfb02388031/tests/functional/centos/7/ooo-collocation/hosts#L5

we also pass `rgw_keystone_revocation_interval: '0'`

**Comment by gfidente** [comment]
https://github.com/ceph/ceph-ansible/blob/5eacc8f8d8ce20fc187471a79543bbfb02388031/tests/functional/centos/7/ooo-collocation/hosts#L8

we append a new param `ceph_mgr_docker_extra_env: '-e MGR_DASHBOARD=0'`

**Comment by gfidente** [comment]
https://github.com/ceph/ceph-ansible/blob/5eacc8f8d8ce20fc187471a79543bbfb02388031/tests/functional/centos/7/ooo-collocation/hosts#L12

we append a custom cluster name `cluster: mycluster`

**Comment by gfidente** [comment]
https://github.com/ceph/ceph-ansible/blob/5eacc8f8d8ce20fc187471a79543bbfb02388031/tests/functional/centos/7/ooo-collocation/hosts#L35

we do not pass this explicitly

**Comment by gfidente** [comment]
https://github.com/ceph/ceph-ansible/blob/5eacc8f8d8ce20fc187471a79543bbfb02388031/tests/functional/centos/7/ooo-collocation/hosts#L36

we do not pass this explicitly

**Comment by gfidente** [comment]
https://github.com/ceph/ceph-ansible/blob/5eacc8f8d8ce20fc187471a79543bbfb02388031/tests/functional/centos/7/ooo-collocation/hosts#L60

we do not pass this explicitly

**Comment by gfidente** [comment]
https://github.com/ceph/ceph-ansible/blob/5eacc8f8d8ce20fc187471a79543bbfb02388031/tests/functional/centos/7/ooo-collocation/hosts#L61

we do not pass this explicitly

**Comment by gfidente** [comment]
https://github.com/ceph/ceph-ansible/blob/5eacc8f8d8ce20fc187471a79543bbfb02388031/tests/functional/centos/7/ooo-collocation/hosts#L46

these have been changed slightly:

"""
            - {key: AQAN0RdbAAAAABAA3CpSKRVDrENjkOSunEFZ0A==, mgr_cap: 'allow *', mode: '0600', mon_cap: 'allow r', name: client.openstack, osd_cap: "allow class-read object_prefix\nrbd_children, allow rwx pool=volumes, allow rwx pool=backups, allow rwx pool=vms,\nallow rwx pool=images, allow rwx pool=metrics"}
            - {key: AQAN0RdbAAAAABAAtV5Dq28z4H6XxwhaNEaFZg==, mds_cap: 'allow *', mgr_cap: 'allow *', mode: '0600', mon_cap: 'allow r, allow command \"auth del\", allow command \"auth caps\", allow command \"auth get\", allow command \"auth get-or-create\"', name: client.manila, osd_cap: 'allow rw'}
            - {key: AQAN0RdbAAAAABAAH5D3WgMN9Rxw3M8jkpMIfg==, mgr_cap: 'allow *', mode: '0600', mon_cap: 'allow rw', name: client.radosgw, osd_cap: 'allow rwx'}
"""

**Comment by gfidente** [comment]
https://github.com/ceph/ceph-ansible/blob/5eacc8f8d8ce20fc187471a79543bbfb02388031/tests/functional/centos/7/ooo-collocation/hosts#L33

these have been updated, look at the comment for line 46

**Comment by gfidente** [comment]
https://github.com/ceph/ceph-ansible/blob/5eacc8f8d8ce20fc187471a79543bbfb02388031/tests/functional/centos/7/ooo-collocation/hosts#L17

we do not set this explicitly

**Comment by guits** [comment]
fixed by #2732
