### ISSUE TITLE
"No first item, sequence was empty." for config_template plugin

### ISSUE THREAD

**Issue by amarao** [ceph/ceph-ansible#2757]
Hello.

When I debug actual usage for ceph-ansible I often can see a message `fatal: [vm]: FAILED! => {"msg": "No first item, sequence was empty."}` for the task "generate ceph configuration file". Most of the times it's caused by lack of something in inventory variables, but not always. It's really hard to debug, and generic error is just saying 'something is wrong', which is not helpful.

As far as I understand, it caused by an empty reply from a module `plugins/actions/_v2_config_template.py` (or, may be, _v1).

Is it possible to add here more extensive diagnostic? Some kind of trace to pinpoint what's wrong?

**Comment by amarao** [comment]
Hello.
I found and fixed the errors in my inventory.

The problem I report here is that those errors are hard to debug, and some debug output from `config_template` plugin will be really appreciated.

**Comment by guits** [comment]
@amarao if launching the playbook with more verbosity to catch a python traceback isn't enough, it's probably better to open a bug at https://bugs.launchpad.net/openstack-ansible
We are using this plugin from the openstack-ansible project, we basically just resync periodically the content from the file in the upstream repo.
