### ISSUE TITLE
ceph-mgr questions

### ISSUE THREAD

**Issue by ww110052181** [ceph/ceph-ansible#2769]
fatal: [master-01]: FAILED! => {"changed": false, "msg": "Unable to start service ceph-mgr@master-01: Job for ceph-mgr@master-01.service failed because the control process exited with error code.\nSee \"systemctl status ceph-mgr@master-01.service\" and \"journalctl -xe\" for details.\n"}
fatal: [master-02]: FAILED! => {"changed": false, "msg": "Unable to start service ceph-mgr@master-02: Job for ceph-mgr@master-02.service failed because the control process exited with error code.\nSee \"systemctl status ceph-mgr@master-02.service\" and \"journalctl -xe\" for details.\n"}
fatal: [master-03]: FAILED! => {"changed": false, "msg": "Unable to start service ceph-mgr@master-03: Job for ceph-mgr@master-03.service failed because the control process exited with error code.\nSee \"systemctl status ceph-mgr@master-03.service\" and \"journalctl -xe\" for details.\n"}

**Comment by guits** [comment]
could you share a bit more details?
inventory host file ? group_vars/* ? ansible version ? OS ? systemctl status ? /var/log/ceph/*.log ?

i'm not sure how to help here otherwise

**Comment by guits** [comment]
I'm wondering if this might be related to the @czunker's issue in #2768 but without more details it's hard to help.

@ww110052181 please provide `sudo journalctl -x -e -l -u ceph-mgr@master-XX` output

**Comment by ww110052181** [comment]
@guits  thx a lot,close this issue
