### ISSUE TITLE
TASK [ceph-osd : activate osd(s) when device is a disk] 

### ISSUE THREAD

**Issue by ww110052181** [ceph/ceph-ansible#2770]
```
failed: [master-04] (item=/dev/sdb) => {"changed": false, "cmd": ["ceph-disk", "activate", "/dev/sdb1"], "delta": "0:00:00.659952", "end": "2018-06-15 16:23:19.754822", "item": "/dev/sdb", "msg": "non-zero return code", "rc": 1, "start": "2018-06-15 16:23:19.094870", "stderr": "mount_activate: Failed to activate\nceph-disk: Error: ceph osd create failed: Command '/usr/bin/ceph' returned non-zero exit status 13: Error EACCES: access denied", "stderr_lines": ["mount_activate: Failed to activate", "ceph-disk: Error: ceph osd create failed: Command '/usr/bin/ceph' returned non-zero exit status 13: Error EACCES: access denied"], "stdout": "", "stdout_lines": []}
failed: [master-01] (item=/dev/sdb) => {"changed": false, "cmd": ["ceph-disk", "activate", "/dev/sdb1"], "delta": "0:00:01.192395", "end": "2018-06-15 16:23:20.234799", "item": "/dev/sdb", "msg": "non-zero return code", "rc": 1, "start": "2018-06-15 16:23:19.042404", "stderr": "got monmap epoch 1\n2018-06-15 16:23:19.853136 7f4544b42e00 -1 bluestore(/var/lib/ceph/tmp/mnt.ccBo1M/block) _check_or_set_bdev_label bdev /var/lib/ceph/tmp/mnt.ccBo1M/block fsid 94ac7a30-950a-4942-88a3-df3b1e14a41e does not match our fsid 7f5efc4f-007e-4ddf-ab30-664de3219fe4\n2018-06-15 16:23:20.159137 7f4544b42e00 -1 bluestore(/var/lib/ceph/tmp/mnt.ccBo1M) mkfs fsck found fatal error: (5) Input/output error\n2018-06-15 16:23:20.159162 7f4544b42e00 -1 OSD::mkfs: ObjectStore::mkfs failed with error (5) Input/output error\n2018-06-15 16:23:20.159280 7f4544b42e00 -1 \u001b[0;31m ** ERROR: error creating empty object store in /var/lib/ceph/tmp/mnt.ccBo1M: (5) Input/output error\u001b[0m\nmount_activate: Failed to activate\nTraceback (most recent call last):\n  File \"/usr/sbin/ceph-disk\", line 11, in <module>\n    load_entry_point('ceph-disk==1.0.0', 'console_scripts', 'ceph-disk')()\n  File \"/usr/lib/python2.7/dist-packages/ceph_disk/main.py\", line 5735, in run\n    main(sys.argv[1:])\n  File \"/usr/lib/python2.7/dist-packages/ceph_disk/main.py\", line 5688, in main\n    main_catch(args.func, args)\n  File \"/usr/lib/python2.7/dist-packages/ceph_disk/main.py\", line 5713, in main_catch\n    func(args)\n  File \"/usr/lib/python2.7/dist-packages/ceph_disk/main.py\", line 3776, in main_activate\n    reactivate=args.reactivate,\n  File \"/usr/lib/python2.7/dist-packages/ceph_disk/main.py\", line 3539, in mount_activate\n    (osd_id, cluster) = activate(path, activate_key_template, init)\n  File \"/usr/lib/python2.7/dist-packages/ceph_disk/main.py\", line 3716, in activate\n    keyring=keyring,\n  File \"/usr/lib/python2.7/dist-packages/ceph_disk/main.py\", line 3168, in mkfs\n    '--setgroup', get_ceph_group(),\n  File \"/usr/lib/python2.7/dist-packages/ceph_disk/main.py\", line 566, in command_check_call\n    return subprocess.check_call(arguments)\n  File \"/usr/lib/python2.7/subprocess.py\", line 186, in check_call\n    raise CalledProcessError(retcode, cmd)\nsubprocess.CalledProcessError: Command '['/usr/bin/ceph-osd', '--cluster', 'ceph', '--mkfs', '-i', u'0', '--monmap', '/var/lib/ceph/tmp/mnt.ccBo1M/activate.monmap', '--osd-data', '/var/lib/ceph/tmp/mnt.ccBo1M', '--osd-uuid', u'7f5efc4f-007e-4ddf-ab30-664de3219fe4', '--setuser', 'ceph', '--setgroup', 'ceph']' returned non-zero exit status 1", "stderr_lines": ["got monmap epoch 1", "2018-06-15 16:23:19.853136 7f4544b42e00 -1 bluestore(/var/lib/ceph/tmp/mnt.ccBo1M/block) _check_or_set_bdev_label bdev /var/lib/ceph/tmp/mnt.ccBo1M/block fsid 94ac7a30-950a-4942-88a3-df3b1e14a41e does not match our fsid 7f5efc4f-007e-4ddf-ab30-664de3219fe4", "2018-06-15 16:23:20.159137 7f4544b42e00 -1 bluestore(/var/lib/ceph/tmp/mnt.ccBo1M) mkfs fsck found fatal error: (5) Input/output error", "2018-06-15 16:23:20.159162 7f4544b42e00 -1 OSD::mkfs: ObjectStore::mkfs failed with error (5) Input/output error", "2018-06-15 16:23:20.159280 7f4544b42e00 -1 \u001b[0;31m ** ERROR: error creating empty object store in /var/lib/ceph/tmp/mnt.ccBo1M: (5) Input/output error\u001b[0m", "mount_activate: Failed to activate", "Traceback (most recent call last):", "  File \"/usr/sbin/ceph-disk\", line 11, in <module>", "    load_entry_point('ceph-disk==1.0.0', 'console_scripts', 'ceph-disk')()", "  File \"/usr/lib/python2.7/dist-packages/ceph_disk/main.py\", line 5735, in run", "    main(sys.argv[1:])", "  File \"/usr/lib/python2.7/dist-packages/ceph_disk/main.py\", line 5688, in main", "    main_catch(args.func, args)", "  File \"/usr/lib/python2.7/dist-packages/ceph_disk/main.py\", line 5713, in main_catch", "    func(args)", "  File \"/usr/lib/python2.7/dist-packages/ceph_disk/main.py\", line 3776, in main_activate", "    reactivate=args.reactivate,", "  File \"/usr/lib/python2.7/dist-packages/ceph_disk/main.py\", line 3539, in mount_activate", "    (osd_id, cluster) = activate(path, activate_key_template, init)", "  File \"/usr/lib/python2.7/dist-packages/ceph_disk/main.py\", line 3716, in activate", "    keyring=keyring,", "  File \"/usr/lib/python2.7/dist-packages/ceph_disk/main.py\", line 3168, in mkfs", "    '--setgroup', get_ceph_group(),", "  File \"/usr/lib/python2.7/dist-packages/ceph_disk/main.py\", line 566, in command_check_call", "    return subprocess.check_call(arguments)", "  File \"/usr/lib/python2.7/subprocess.py\", line 186, in check_call", "    raise CalledProcessError(retcode, cmd)", "subprocess.CalledProcessError: Command '['/usr/bin/ceph-osd', '--cluster', 'ceph', '--mkfs', '-i', u'0', '--monmap', '/var/lib/ceph/tmp/mnt.ccBo1M/activate.monmap', '--osd-data', '/var/lib/ceph/tmp/mnt.ccBo1M', '--osd-uuid', u'7f5efc4f-007e-4ddf-ab30-664de3219fe4', '--setuser', 'ceph', '--setgroup', 'ceph']' returned non-zero exit status 1"], "stdout": "", "stdout_lines": []}
```

thx for your replying

**Comment by ww110052181** [comment]
the file ceph.audit.log information ：

2018-06-15 16:48:46.053974 mon.master-01 mon.0 23.66.57.89:6789/0 465 : audit [INF] from='client.? 23.66.57.91:0/2206819720' entity='client.admin' cmd=[{"prefix": "osd pool create", "pg_num": 8, "pool": "cephfs_metadata"}]: dispatch
2018-06-15 16:52:16.282276 mon.master-01 mon.0 23.66.57.89:6789/0 496 : audit [INF] from='client.? 23.66.57.91:0/1554919521' entity='client.admin' cmd=[{"prefix": "osd pool create", "pg_num": 8, "pool": "cephfs_data"}]: dispatch
2018-06-15 16:52:16.961178 mon.master-01 mon.0 23.66.57.89:6789/0 497 : audit [INF] from='client.? 23.66.57.91:0/332495718' entity='client.admin' cmd=[{"prefix": "osd pool create", "pg_num": 8, "pool": "cephfs_metadata"}]: dispatch
2018-06-15 16:53:45.851848 mon.master-01 mon.0 23.66.57.89:6789/0 501 : audit [INF] from='client.? 23.66.57.92:0/2969630885' entity='client.bootstrap-osd' cmd=[{"prefix": "osd create", "uuid": "1e88d7f6-61f7-4171-94f1-691d7031c124"}]:  access denied

**Comment by guits** [comment]
can you share the command you've used to run the playbook ?

+ same as in #2769 could you share more details on your environment ?

thanks!

**Comment by ww110052181** [comment]
@guits 
thanks a lot,
this is my environment
$ ceph -v
ceph version 12.2.5 (cad919881333ac92274171586c827e01f554a70a) luminous (stable)
$ cat /proc/version 
Linux version 4.9.0-6-amd64 (debian-kernel@lists.debian.org) (gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1) ) #1 SMP Debian 4.9.88-1 (2018-04-29)

$cat inventory_hosts
[mons]
master-01
master-02
master-03


[mdss]
master-01
master-02
master-03

[mgrs]
master-01
master-02
master-03

[osds]
master-01
master-02
master-03
master-04

**Comment by guits** [comment]
@ww110052181 what about the ceph-ansible version? how did you launch the playbook ?

**Comment by ww110052181** [comment]
@guits thx a lot
I have solve this problem.
i remove the osd by shrink-osd.yml ,and then i reinstall the osd again

**Comment by guits** [comment]
ok, not sure what was wrong but i guess we can close this issue

**Comment by ww110052181** [comment]
@guits  thank you very much

**Comment by vincent50411** [comment]
failed: [node3] (item=/dev/vdc) => {"changed": false, "cmd": ["ceph-disk", "activate", "/dev/vdc1"], "delta": "0:00:00.181354", "end": "2019-09-25 17:12:58.799235", "item": "/dev/vdc", "msg": "non-zero return code", "rc": 1, "start": "2019-09-25 17:12:58.617881", "stderr": "mount_activate: Failed to activate\nceph-disk: Does not look like a Ceph OSD, or incompatible version: /var/lib/ceph/tmp/mnt.WDR0ej", "stderr_lines": ["mount_activate: Failed to activate", "ceph-disk: Does not look like a Ceph OSD, or incompatible version: /var/lib/ceph/tmp/mnt.WDR0ej"], "stdout": "", "stdout_lines": []}
failed: [node2] (item=/dev/vdc) => {"changed": false, "cmd": ["ceph-disk", "activate", "/dev/vdc1"], "delta": "0:00:00.510697", "end": "2019-09-25 17:12:59.057726", "item": "/dev/vdc", "msg": "non-zero return code", "rc": 1, "start": "2019-09-25 17:12:58.547029", "stderr": "mount_activate: Failed to activate\nceph-disk: Does not look like a Ceph OSD, or incompatible version: /var/lib/ceph/tmp/mnt.kpS0kL", "stderr_lines": ["mount_activate: Failed to activate", "ceph-disk: Does not look like a Ceph OSD, or incompatible version: /var/lib/ceph/tmp/mnt.kpS0kL"], "stdout": "", "stdout_lines": []}

hosts：
[mons]
node1

[osds]
node2
node3

[mgrs]
node1


node3 node2 
vdc                                                        
vdc1 ext4             a0575bee-de24-47d7-9d75-b6405014e030 


ceph -v
ceph version 12.2.12 (1436006594665279fe734b4c15d7e08c13ebd777) luminous (stable)

 ansible --version
[WARNING]: log file at /var/log/ansible.log is not writeable and we cannot create it, aborting

ansible 2.6.19
  config file = /disk1/home/wsliu2/ceph-ansible-stable-3.2/ansible.cfg
  configured module search path = [u'/disk1/home/wsliu2/ceph-ansible-stable-3.2/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
