### ISSUE TITLE
add something quick to create lvm's for ceph-volume

### ISSUE THREAD

**Issue by vasukulkarni** [ceph/ceph-ansible#2774]
we are using the following task in cm-ansible in teuthology to create lvm's for ceph-volume, I am thinking it should be possible to use something similar *as a starting point* to configure lvm's on user defined disk  https://github.com/ceph/ceph-cm-ansible/blob/master/roles/testnode/tasks/configure_lvm.yml

later it could be enhanced to meet other requirements but it still serves as a good initial use case to get something fast in builds? thoughts?

**Comment by alfredodeza** [comment]
we are working towards this, ceph-ansible will gain the capability of granular/configurable creation, while ceph-volume will be in charge of creating the lvs and firing up the osds.

Thanks for reporting this @vasukulkarni - it will be useful to keep track of

**Comment by alfredodeza** [comment]
This was resolved via https://github.com/ceph/ceph-ansible/pull/2980

Look for the `batch` subcommand in `ceph-volume lvm`, and in ceph-ansible you can read about the `devices:` configuration that will allow you to pass in a bunch of devices and get everything configured http://docs.ceph.com/ceph-ansible/master/osds/scenarios.html#lvm
