### ISSUE TITLE
Mode-clash on /var/run/ceph

### ISSUE THREAD

**Issue by ThoreKr** [ceph/ceph-ansible#2777]
Good evening,
when running ceph-ansible (stable-3.1) against Debian (Stretch), there is a mode clash between [`ceph-defaults/tasks/create_ceph_initial_dirs.yml`](https://github.com/ceph/ceph-ansible/blob/stable-3.1/roles/ceph-defaults/tasks/create_ceph_initial_dirs.yml#L24) and the fact for `rbd_client_directory_mode`  as defined in [`ceph-defaults/tasks/facts.yml` ](https://github.com/ceph/ceph-ansible/blob/stable-3.1/roles/ceph-defaults/tasks/facts.yml#L149)

Setting `rbd_client_directory_mode` to `755` manually in the group vars solves this issue, but I think this shouldn't happen in the first place and I guess the `770` has been set for a reason, as it affects the log path as well.

**Comment by leseb** [comment]
I understand the mode clash, but is this leading to an error? Thanks.

**Comment by ThoreKr** [comment]
It causes the permissions to be changed back and forth. So every run you have at least 2 changes.
