### ISSUE TITLE
AdminSocketConfigObs::init: failed: rbd-clients

### ISSUE THREAD

**Issue by ivomarino** [ceph/ceph-ansible#278]
After a fresh deployment on two nodes once I launch % ceph -w I always get the following error:

2015-06-10 18:34:06.599400 7f02fdce8700 -1 asok(0x7f02f8000bf0) AdminSocketConfigObs::init: failed: AdminSocket::bind_and_listen: failed to bind the UNIX domain socket to '/var/run/ceph/rbd-clients/ceph-client.admin.290250.139650727415008.asok': (2) No such file or directory

any suggestions? Thanks.

**Comment by leseb** [comment]
Well this is due to this entry in your ceph.conf: https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-common/templates/ceph.conf.j2#L68

A simple way to fix this is to create `/var/run/ceph/rbd-clients/`, the problem should disappear.

**Comment by ivomarino** [comment]
Fixed, thanks.

**Comment by JevonQ** [comment]
I encountered this issue as well, my fix is to create /var/run/ceph.

**Comment by curantes** [comment]
I have this issue as well, I have created the missing `/var/run/ceph/rbd-clients/` and the issue is resolved. However after a reboot of the node the directory is removed and I need to recreate this folder again. Is there another solution to this?

**Comment by dvusboy** [comment]
I didn't realize it until someone pointed it out. On RHEL/CentOS 7, `/var/run` or `/run` is a `tmpfs`. It is why `/var/run/ceph/rbd-clients` keep disappearing, after reboot, for me.

**Comment by rootfs** [comment]
you can redirect the directory by adding the following to `group_vars/all`

```yaml
rbd_client_admin_socket_path: /var/lib/ceph  
```

**Comment by erinboyd** [comment]
@rootfs this might be a regression, I am getting this on CentOS7 now
