### ISSUE TITLE
pg_num always 64

### ISSUE THREAD

**Issue by ivomarino** [ceph/ceph-ansible#279]
% ceph osd pool get rbd pg_num
pg_num: 64

I've set in production/group_vars/all:

pool_default_pg_num: 4096
pool_default_pgp_num: 4096

but this seems to be ignored in some way, suggestions? Thanks.

**Comment by leseb** [comment]
During the monitor bootstrap I have the impression that ceph does not honor the value set in the ceph.conf. The default value in the playbook is 128 anyway ao it's probably ceph. What do you get if you run rados mkpool foo?

**Comment by ivomarino** [comment]
% rados mkpool foo
successfully created pool foo

% ceph osd pool get foo pg_num
pg_num: 4096

so yes, the problem is during bootstrap. I have 10 OSDs, two nodes, 1 SSD on each node for journal.
With pg_num 64 I get:

  health HEALTH_WARN
            31 pgs peering
            64 pgs stuck inactive
            64 pgs stuck unclean
            too few PGs per OSD (12 < min 30)

Any ideas how to fix? Thanks.

**Comment by leseb** [comment]
Just increase the PG size like this:

`$ sudo ceph osd pool set rbd pg_num 512`

Wait a bit and then run:

`$ sudo ceph osd pool set rbd pgp_num 512`

**Comment by ivomarino** [comment]
Already tried:

% ceph osd pool set rbd pg_num 512
Error E2BIG: specified pg_num 512 is too large (creating 448 new PGs on ~10 OSDs exceeds per-OSD max of 32)

% ceph osd pool set rbd pg_num 128
Error EBUSY: currently creating pgs, wait

I can rebuild the whole ceph thing easily from scratch via ansible ceph as I wrote a purge complete script which brings me in a clean state on both nodes from where I can start over, problem persists anyway. I think the rbd pool must be created with higher pg_num during initial deployment (just guess). Thanks

**Comment by ivomarino** [comment]
and...
Error EBUSY: currently creating pgs, wait
will last forever, seems.

**Comment by dmick** [comment]
it'll finish, but it may have to move a lot of data.  However, you must have had a prior set pg_num in progress?

**Comment by ivomarino** [comment]
Ceph has been set up from scratch there's no data inside and only the rbd pool. The problem arises after each new ansible deployment, disks are completely cleaned up before so ansible ceph recreates also the partitions, so 100% sure no data is inside ceph.

**Comment by dmick** [comment]
could be then that with two nodes the crushmap is set up to try to replicate across nodes rather than osds, and thus can't get to replication level 3 (the default)?...

**Comment by ivomarino** [comment]
Replication level is 2, I set it to that as far as I've 2 nodes for now, a third node will join soon. But for now 2 and all is set up accordingly.

**Comment by dmick** [comment]
dunno.  I'm sure this works, though; maybe hop on #ceph and ask

**Comment by ivomarino** [comment]
Ok, thanks. Anyway it seems that pg num 64 in my case is not enough for rbd pool, it's all about increasing this value during bootstrap I presume.

**Comment by leseb** [comment]
As Dan mentioned it will eventually finish. Check the status of your cluster. I've never seen thus process getting stuck unless you have a crush map issue.

**Comment by ivomarino** [comment]
Alright, I'll wait and let you know. Anyway for now thanks to all the support, very appreciated!

**Comment by ivomarino** [comment]
At which point during deployment the rbd ceph pool is being created? Maybe we miss some parameters during creation which should specify a pg_num > 64? Thanks.

**Comment by ivomarino** [comment]
I've redeployed the whole cluster from scratch, two times, and now % ceph osd pool set rbd pg_num 256 works fine. No idea. Furthermore, is something like this correct?

devices:
  - /dev/sdb
  - /dev/sdc
  - /dev/sdd
  - /dev/sde
  - /dev/sdf

osd_auto_discovery: false

journal_collocation: false

raw_multi_journal: true
raw_journal_devices:
  - /dev/sdg
  - /dev/sdg
  - /dev/sdg
  - /dev/sdg
  - /dev/sdg

Thanks.

**Comment by ivomarino** [comment]
Problem seems to be related to private/public network config, set correctly. Now during deployment I can e.g. run: % watch -n 1 "ceph osd pool set rbd pg_num 512 ; ceph osd pool set rbd pgp_num 512" which sets pg_num and pgp_num fine now.

**Comment by leseb** [comment]
Glad to hear that it works now. Your config is correct yes.

**Comment by ivomarino** [comment]
Thanks Leseb. One last question: In case /dev/sdg (SSD Journal) dies I'll lose all my OSDs, can I mix having some OSD journals on /dev/sdX (SSD) and also on /dev/sdf2 let's say? Something like:

devices:
  /dev/sdb1
  /dev/sdc1
  /dev/sdd1
  /dev/sde1
  /dev/sdf1

osd_auto_discovery: false
journal_collocation: false

raw_multi_journal: true
raw_journal_devices:
  /dev/sdg
  /dev/sdg
  /dev/sdg
  /dev/sdf2
  /dev/sdf2

Thanks.

**Comment by leseb** [comment]
Yes you can, the current mapping will do:

* /dev/sdb1 will have /dev/sdg1 as journal
* /dev/sdc1 will have /dev/sdg2 as journal
* /dev/sdd1 will have /dev/sdg3 as journal
* /dev/sde1 will have /dev/sdf1 as journal
* /dev/sdf1 will have /dev/sdf2 as journal


I don't think we support using partitioned device for the journal. So you can't use /dev/sdf2, use the whole device instead.

**Comment by ivomarino** [comment]
Allright, thanks Leseb.
