### ISSUE TITLE
Feature: Use 'block' directives

### ISSUE THREAD

**Issue by mykaul** [ceph/ceph-ansible#2835]
Using blocks (https://docs.ansible.com/ansible/2.5/user_guide/playbooks_blocks.html ) can simplify some playbooks. For example, consider https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-nfs/tasks/pre_requisite_non_container.yml :

If we just use something like:
- name: Red Hat repository handling
  - block:
 ...
  when:
     - ansible_os_family == 'RedHat'
- name: Debian repository handling
 - block:
 ...
  when:
    - ansible_os_family == 'Debian'

It will simplify reading the code (and potentially running it). Nested blocks are also supported, btw.

**Comment by rishabh-d-dave** [comment]
PR - https://github.com/ceph/ceph-ansible/pull/3104
