### ISSUE TITLE
generage ceph configuration file failed on ubuntu

### ISSUE THREAD

**Issue by like-inspur** [ceph/ceph-ansible#2843]
I install ceph cluster successfully on centos with version 3.0.36, but failed on ubuntu, error is this:
TASK [ceph-config : generate ceph configuration file: ceph.conf] ********************************************************************************
Wednesday 04 July 2018  10:32:07 +0800 (0:00:00.494)       0:00:53.794 ******** 
fatal: [openstack-202]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (copy) module: original_basename Supported parameters include: _original_basename, attributes, backup, checksum, content, delimiter, dest, directory_mode, follow, force, group, local_follow, mode, owner, regexp, remote_src, selevel, serole, setype, seuser, src, unsafe_writes, validate"}

I check installation configuration is no problem, so what is the reason? Thank you! @hunter @gbraad @jd @dang @duritong

**Comment by vishalkanaujia** [comment]
What is the ansible playbook version?
`$ ansible-playbook --version`

**Comment by like-inspur** [comment]
2.6.0, is it too high?

**Comment by vishalkanaujia** [comment]
yes, I guess so. The ceph-ansible requirements say `ansible~=2.4,<2.5`.

Could you please try using `ansible-playbook 2.4`?

**Comment by jd** [comment]
Why the hell do you mention me @like-inspur? 🤨

**Comment by leseb** [comment]
@andymcc has this been reported already? Thanks.

**Comment by andymcc** [comment]
I believe this is fixed in master already: https://github.com/ceph/ceph-ansible/commit/eb836e7c3101aa89bb64f1515605cf717fd3d9d2 - although I only tested against ansible 2.5.0 and not ansible 2.6.0.

On a side note I wouldn't recommend using 2.5.0+ on stable 3.0 branch.

**Comment by andymcc** [comment]
yeah its broken on 2.6
I'll try fix this up.

**Comment by leseb** [comment]
@andymcc thanks, looking forward to it.

**Comment by kennethredler** [comment]
@andymcc will this be ported to `stable-3.1` branch, by chance?

**Comment by guits** [comment]
@kennethredler I don't think stable-3.1 is intended to run against ansible 2.6.

**Comment by kennethredler** [comment]
😿
