### ISSUE TITLE
How to set ntp server in ceph cluster

### ISSUE THREAD

**Issue by like-inspur** [ceph/ceph-ansible#2855]
I have configure ntp_service_enabled to true, and found that ntp service is running on every host. But When I install ceph cluster in private environment where host can't connect external network, how to set ntp server, so ceph cluster can ensure time is same. Thank you!  @hunter @gbraad @dang @duritong @verdurin

**Comment by guits** [comment]
@like-inspur perhaps you could setup one host as an NTP server for other host.

**Comment by leseb** [comment]
If you need to configure NTP, use an existing Ansible role for it. ceph-ansible will never configure NTP. We do best-effort only, so we make sure NTP is started to avoid issues with the monitors.
