### ISSUE TITLE
RFE: Support pre-generation of all secrets and don't allow their movement outside of the ceph hosts

### ISSUE THREAD

**Issue by ggillies** [ceph/ceph-ansible#2859]
Hi,
So I am looking at using ceph-ansible to deploy ceph clusters in a highly secure environment.

As part of our standard operating procedure for that environment, we have a secret management system that can generate secrets on all hosts as we require.

We would like to have the ability for ceph-ansible to support those existing keys (or even allow us greater control in specifying them as ansible variables), but most importantly, for maximum security, those keys must never get moved outside of the hosts they are on.

At the moment a lot of the ceph-ansible code just kind of lazily operates on dragging everything and anything back into a local fetch directory (a lot of the fetch calls are wildcarded so they take everything weather it is needed or not). This really isn't a great way of doing things security wise.

Cleaning this up to operate better would allow us to allow ceph-ansible to also operate cleaner with secret management systems such as hashicorp vault, and FreeIPA/dogtag. Which I think would be a very huge win for the project.

Regards,

Graeme

**Comment by ggillies** [comment]
Perhaps replacing fetch calls with slurp

https://docs.ansible.com/ansible/2.6/modules/slurp_module.html

would be a good first step in removing the use of fetch directory

**Comment by guits** [comment]
fixed by https://github.com/ceph/ceph-ansible/pull/4472/commits/812bd63ef48c8a980b26e7a971389465a8366316
