### ISSUE TITLE
Error in creating /etc/ceph/{{ cluster }}.conf

### ISSUE THREAD

**Issue by ghisl1** [ceph/ceph-ansible#2873]
Hi,
i'm using ansible 2.6
I want to deploy a micro luminous-based ceph lab over ubuntu 16.04
I encountered an error at /etc/ceph/myceph.conf as followed in config_template action :

<ceph2> (1, '\n{"msg": "Unsupported parameters for (copy) module: original_basename Supported parameters include: _original_basename, attributes, backup, checksum, content, delimiter, dest, directory_mode, follow, force, group, local_follow, mode, owner, regexp, remote_src, selevel, serole, setype, seuser, src, unsafe_writes, validate", "failed": true, "invocation": {"module_args": {"src": "/home/cephadmin/.ansible/tmp/ansible-tmp-1531318366.51-72724828001041/source", "group": "ceph", "dest": "/etc/ceph/myceph.conf", "original_basename": "ceph.conf.j2", "mode": "0644", "owner": "ceph", "follow": true}}}\n', 'OpenSSH_7.2p2 Ubuntu-4ubuntu2.4, OpenSSL 1.0.2g  1 Mar 2016\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 5573\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 1\r\n')
fatal: [ceph2]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "dest": "/etc/ceph/myceph.conf", 
            "follow": true, 
            "group": "ceph", 
            "mode": "0644", 
            "original_basename": "ceph.conf.j2", 
            "owner": "ceph", 
            "src": "/home/cephadmin/.ansible/tmp/ansible-tmp-1531318366.51-72724828001041/source"
        }
    }, 
    "msg": "Unsupported parameters for (copy) module: original_basename Supported parameters include: _original_basename, attributes, backup, checksum, content, delimiter, dest, directory_mode, follow, force, group, local_follow, mode, owner, regexp, remote_src, selevel, serole, setype, seuser, src, unsafe_writes, validate"
}

**Comment by andymcc** [comment]
ceph-ansible doesn't currently support Ansible 2.6+ - if you use 2.5 or 2.4 you should be able to get passed this issue.

**Comment by guits** [comment]
@andymcc is your PR #2878 going to fix this issue?

**Comment by andymcc** [comment]
@guits yeah - I'm not sure Ansible 2.6 will be supported after that merges though - just config_template will not be the issue, but there could be other failures as a result of changes in Ansible 2.6

**Comment by guits** [comment]
the CI will tell us soon I guess :-)

**Comment by guits** [comment]
@andymcc Just FI, i've tested your patch with ansible 2.6 and it seems to be OK

**Comment by ghisl1** [comment]
@andymcc
@guits
you're too quick guys...
I've just tested it with ansible 2.5.5 and it works fine

**Comment by guits** [comment]
Closed by #2878
