### ISSUE TITLE
Bluestore LVM documentation needs to be clarified

### ISSUE THREAD

**Issue by verdurin** [ceph/ceph-ansible#2879]
**Bug Report**

What happened:

I tried to follow the documented procedure with `bluestore` and `lvm`, which involves specifying the volume group for logical volumes (for WAL/DB).

This failed because there was an error about `blkid` not being able to find a `PARTUUID` for the specified LV.

What you expected to happen:

OSDs are created.

When I changed the configuration to include the volume group in the name of each device e.g. `db: vg0/lv0` it did work.

This should be clarified in the documentation. 

How to reproduce it (minimal and precise):

Use `db_vg` and `wal_vg` in the OSD configuration, as suggested at http://docs.ceph.com/ceph-ansible/master/osds/scenarios.html#bluestore

Share your group_vars files, inventory

**Environment**:
* OS (e.g. from /etc/os-release): CentOS 7.5
* Kernel (e.g. `uname -a`): 3.10.0-862.6.3
* Docker version if applicable (e.g. `docker version`):
* Ansible version (e.g. `ansible-playbook --version`): 2.4.2.0
* ceph-ansible version (e.g. `git head or tag or stable branch`): git head
* Ceph version (e.g. `ceph -v`): 12.2.6

**Comment by satishdotpatel** [comment]
I am confused too, How to create LVM if i have only single physical SSD and i want to keep journal + data on same disk?

**Comment by mcv21** [comment]
@satishdotpatel just specify it as `lvm_volumes`[`data`] directly as e.g. `/dev/sdb`.

**Comment by dsavineau** [comment]
everything is documented at http://docs.ceph.com/ceph-ansible/master/osds/scenarios.html#advanced-configuration
