### ISSUE TITLE
purge should cleanup fetch-directory

### ISSUE THREAD

**Issue by vasukulkarni** [ceph/ceph-ansible#2880]
after I purge the cluster, i see that fetch directory still has some kind of config, I think it is nice to cleanup fetch-directory as well when purge is issued, In a large cluster, we are having bit of issues with purge and recreate, I am not sure if its related to that but trying to see if that can cause issues.

**Comment by leseb** [comment]
which purge? container or non-container?

**Comment by dsavineau** [comment]
This is done in both purge playbooks

https://github.com/ceph/ceph-ansible/blob/master/infrastructure-playbooks/purge-cluster.yml#L712-L728
https://github.com/ceph/ceph-ansible/blob/master/infrastructure-playbooks/purge-docker-cluster.yml#L727-L743
