### ISSUE TITLE
test with ansible 2.6

### ISSUE THREAD

**Issue by ktdreyer** [ceph/ceph-ansible#2901]
Currently we test upstream in Jenkins with Ansible 2.4 and 2.5, as discussed in https://github.com/ceph/ceph-ansible/issues/2470

Please add testing for Ansible 2.6 as well as 2.4 and 2.5.

Ansible 2.4 is currently end-of-life, but it's the only one I know is well-tested with the RH Ceph Storage product.

Ansible 2.5 will go end-of-life after Ansible 2.7 is released (https://access.redhat.com/support/policy/updates/ansible-engine)

It would be great to use Ansible 2.6 in RH Ceph Storage 3.2.

**Comment by guits** [comment]
as per #2908, it looks like master passes testing against ansible 2.6

**Comment by ktdreyer** [comment]
That's great news, thanks @guits !

**Comment by guits** [comment]
> Currently we test upstream in Jenkins with Ansible 2.4 and 2.5, as discussed in #2470
> 
> Please add testing for Ansible 2.6 as well as 2.4 and 2.5.
> 
> Ansible 2.4 is currently end-of-life, but it's the only one I know is well-tested with the RH Ceph Storage product.
> 
> Ansible 2.5 will go end-of-life after Ansible 2.7 is released (https://access.redhat.com/support/policy/updates/ansible-engine)
> 
> It would be great to use Ansible 2.6 in RH Ceph Storage 3.2.

@ktdreyer we've been asked to test ceph-ansible stable-3.2 against ansible 2.6, from what I'm seeing today, correct me if I'm wrong but it seems RHCS 3.2 ships ansible 2.4 downstream?

**Comment by ktdreyer** [comment]
RH Ceph Storage 3.2 should be compatible with Ansible 2.6 because that is what we document for our customers to use ([rhbz#1613941](https://bugzilla.redhat.com/show_bug.cgi?id=1613941))

**Comment by guits** [comment]
@ktdreyer from what I can see, RHCS 3.2 ships with ansible 2.4 though

**Comment by ktdreyer** [comment]
Right, unfortunately there have been several changes in the way that the Ansible team preferred to have layered products consume their builds:

1.  Originally Ansible was [shipped](https://access.redhat.com/errata/RHEA-2017:2366) in the RHEL 7 Extras repository.
2. Later, the team [pulled the build](https://access.redhat.com/articles/3359651) out of RHEL 7 Extras.
3. At that point we agreed that we should cross-ship Ansible in our own layered products, so we [cross-shipped Ansible 2.4](https://access.redhat.com/errata/RHBA-2017:3387). That is the ansible build you see in the RH Ceph Storage 3 Yum repository today.
4. Later, the Ansible engineering team published their own repositories alongside RHEL. This is the preferred method today, and this is why we document that users should enable `rhel-7-server-ansible-2.6-rpms` on their administrator node.
