### ISSUE TITLE
activate osd(s) when device is a disk failed

### ISSUE THREAD

**Issue by like-inspur** [ceph/ceph-ansible#2945]
I config host install ceph-osd which version is luminious with bluestore, when ansible execute ceph-osd : activate osd(s) when device is a disk, it outpus error like this:
failed: [icp-104] (item=/dev/sdl) => {"changed": false, "cmd": ["ceph-disk", "activate", "/dev/sdl1"], "delta": "0:00:00.891850", "end": "2018-07-27 08:55:35.879458", "item": "/dev/sdl", "msg": "non-zero return code", "rc": 1, "start": "2018-07-27 08:55:34.987608", "stderr": "got monmap epoch 1\n2018-07-27 08:55:35.578050 7fd937a46d40 -1 WARNING: the following dangerous and experimental features are enabled: bluestore,rocksdb\n2018-07-27 08:55:35.578230 7fd937a46d40 -1 WARNING: the following dangerous and experimental features are enabled: bluestore,rocksdb\n2018-07-27 08:55:35.580213 7fd937a46d40 -1 WARNING: the following dangerous and experimental features are enabled: bluestore,rocksdb\n2018-07-27 08:55:35.581680 7fd937a46d40 -1 bluestore(/var/lib/ceph/tmp/mnt.YEYeI6/block) _check_or_set_bdev_label bdev /var/lib/ceph/tmp/mnt.YEYeI6/block fsid 58419450-77be-41d0-ab87-315c04d88c15 does not match our fsid 998006b0-f366-4933-b1ab-e0505e841aae\n2018-07-27 08:55:35.836202 7fd937a46d40 -1 bluestore(/var/lib/ceph/tmp/mnt.YEYeI6) mkfs fsck found fatal error: (5) Input/output error\n2018-07-27 08:55:35.836234 7fd937a46d40 -1 OSD::mkfs: ObjectStore::mkfs failed with error (5) Input/output error\n2018-07-27 08:55:35.836377 7fd937a46d40 -1 \u001b[0;31m ** ERROR: error creating empty object store in /var/lib/ceph/tmp/mnt.YEYeI6: (5) Input/output error\u001b[0m\nmount_activate: Failed to activate\nTraceback (most recent call last):\n  File \"/sbin/ceph-disk\", line 9, in <module>\n    load_entry_point('ceph-disk==1.0.0', 'console_scripts', 'ceph-disk')()\n  File \"/usr/lib/python2.7/site-packages/ceph_disk/main.py\", line 5735, in run\n    main(sys.argv[1:])\n  File \"/usr/lib/python2.7/site-packages/ceph_disk/main.py\", line 5688, in main\n    main_catch(args.func, args)\n  File \"/usr/lib/python2.7/site-packages/ceph_disk/main.py\", line 5713, in main_catch\n    func(args)\n  File \"/usr/lib/python2.7/site-packages/ceph_disk/main.py\", line 3776, in main_activate\n    reactivate=args.reactivate,\n  File \"/usr/lib/python2.7/site-packages/ceph_disk/main.py\", line 3539, in mount_activate\n    (osd_id, cluster) = activate(path, activate_key_template, init)\n  File \"/usr/lib/python2.7/site-packages/ceph_disk/main.py\", line 3716, in activate\n    keyring=keyring,\n  File \"/usr/lib/python2.7/site-packages/ceph_disk/main.py\", line 3168, in mkfs\n    '--setgroup', get_ceph_group(),\n  File \"/usr/lib/python2.7/site-packages/ceph_disk/main.py\", line 566, in command_check_call\n    return subprocess.check_call(arguments)\n  File \"/usr/lib64/python2.7/subprocess.py\", line 542, in check_call\n    raise CalledProcessError(retcode, cmd)\nsubprocess.CalledProcessError: Command '['/usr/bin/ceph-osd', '--cluster', 'ceph', '--mkfs', '-i', u'13', '--monmap', '/var/lib/ceph/tmp/mnt.YEYeI6/activate.monmap', '--osd-data', '/var/lib/ceph/tmp/mnt.YEYeI6', '--osd-uuid', u'998006b0-f366-4933-b1ab-e0505e841aae', '--setuser', 'ceph', '--setgroup', 'ceph']' returned non-zero exit status 1", "stderr_lines": ["got monmap epoch 1", "2018-07-27 08:55:35.578050 7fd937a46d40 -1 WARNING: the following dangerous and experimental features are enabled: bluestore,rocksdb", "2018-07-27 08:55:35.578230 7fd937a46d40 -1 WARNING: the following dangerous and experimental features are enabled: bluestore,rocksdb", "2018-07-27 08:55:35.580213 7fd937a46d40 -1 WARNING: the following dangerous and experimental features are enabled: bluestore,rocksdb", "2018-07-27 08:55:35.581680 7fd937a46d40 -1 bluestore(/var/lib/ceph/tmp/mnt.YEYeI6/block) _check_or_set_bdev_label bdev /var/lib/ceph/tmp/mnt.YEYeI6/block fsid 58419450-77be-41d0-ab87-315c04d88c15 does not match our fsid 998006b0-f366-4933-b1ab-e0505e841aae", "2018-07-27 08:55:35.836202 7fd937a46d40 -1 bluestore(/var/lib/ceph/tmp/mnt.YEYeI6) mkfs fsck found fatal error: (5) Input/output error", "2018-07-27 08:55:35.836234 7fd937a46d40 -1 OSD::mkfs: ObjectStore::mkfs failed with error (5) Input/output error", "2018-07-27 08:55:35.836377 7fd937a46d40 -1 \u001b[0;31m ** ERROR: error creating empty object store in /var/lib/ceph/tmp/mnt.YEYeI6: (5) Input/output error\u001b[0m", "mount_activate: Failed to activate", "Traceback (most recent call last):", "  File \"/sbin/ceph-disk\", line 9, in <module>", "    load_entry_point('ceph-disk==1.0.0', 'console_scripts', 'ceph-disk')()", "  File \"/usr/lib/python2.7/site-packages/ceph_disk/main.py\", line 5735, in run", "    main(sys.argv[1:])", "  File \"/usr/lib/python2.7/site-packages/ceph_disk/main.py\", line 5688, in main", "    main_catch(args.func, args)", "  File \"/usr/lib/python2.7/site-packages/ceph_disk/main.py\", line 5713, in main_catch", "    func(args)", "  File \"/usr/lib/python2.7/site-packages/ceph_disk/main.py\", line 3776, in main_activate", "    reactivate=args.reactivate,", "  File \"/usr/lib/python2.7/site-packages/ceph_disk/main.py\", line 3539, in mount_activate", "    (osd_id, cluster) = activate(path, activate_key_template, init)", "  File \"/usr/lib/python2.7/site-packages/ceph_disk/main.py\", line 3716, in activate", "    keyring=keyring,", "  File \"/usr/lib/python2.7/site-packages/ceph_disk/main.py\", line 3168, in mkfs", "    '--setgroup', get_ceph_group(),", "  File \"/usr/lib/python2.7/site-packages/ceph_disk/main.py\", line 566, in command_check_call", "    return subprocess.check_call(arguments)", "  File \"/usr/lib64/python2.7/subprocess.py\", line 542, in check_call", "    raise CalledProcessError(retcode, cmd)", "subprocess.CalledProcessError: Command '['/usr/bin/ceph-osd', '--cluster', 'ceph', '--mkfs', '-i', u'13', '--monmap', '/var/lib/ceph/tmp/mnt.YEYeI6/activate.monmap', '--osd-data', '/var/lib/ceph/tmp/mnt.YEYeI6', '--osd-uuid', u'998006b0-f366-4933-b1ab-e0505e841aae', '--setuser', 'ceph', '--setgroup', 'ceph']' returned non-zero exit status 1"], "stdout": "", "stdout_lines": []}

**Comment by vishalkanaujia** [comment]
Please share the o/p of the following:

~~~
- ceph -v
- copy of ceph.conf
- ceph osd tree
~~~

**Comment by like-inspur** [comment]
ceph -v
ceph version 12.2.5 (cad919881333ac92274171586c827e01f554a70a) luminous (stable)

 cat /etc/ceph/ceph.conf 
[client.rgw.icp-102]
host = icp-102
keyring = /var/lib/ceph/radosgw/ceph-rgw.icp-102/keyring
log file = /var/log/ceph/ceph-rgw-icp-102.log
rgw frontends = civetweb port=10.110.25.102:8082 num_threads=100

[client.rgw.icp-103]
host = icp-103
keyring = /var/lib/ceph/radosgw/ceph-rgw.icp-103/keyring
log file = /var/log/ceph/ceph-rgw-icp-103.log
rgw frontends = civetweb port=10.110.25.103:8082 num_threads=100

[client.rgw.icp-104]
host = icp-104
keyring = /var/lib/ceph/radosgw/ceph-rgw.icp-104/keyring
log file = /var/log/ceph/ceph-rgw-icp-104.log
rgw frontends = civetweb port=10.110.25.104:8082 num_threads=100

# Please do not change this file directly since it is managed by Ansible and will be overwritten
[global]
cluster network = 10.1.25.0/24
fsid = 41d25627-866c-45d5-b2d4-2ea8f047e705
mon host = 10.110.25.102,10.110.25.103,10.110.25.104
mon initial members = icp-102,icp-103,icp-104
public network = 10.110.25.0/24

[mds.icp-102]
host = icp-102

[mds.icp-103]
host = icp-103

[mds.icp-104]
host = icp-104

[osd]
enable experimental unrecoverable data corrupting features = bluestore rocksdb

ceph osd tree
ID CLASS WEIGHT   TYPE NAME        STATUS REWEIGHT PRI-AFF 
-1       32.69513 root default                             
-3       10.89838     host icp-102                         
 0   hdd  2.72459         osd.0        down  1.00000 1.00000 
 1   hdd  2.72459         osd.1        down  1.00000 1.00000 
 2   hdd  2.72459         osd.2        down  1.00000 1.00000 
 3   hdd  2.72459         osd.3        down  1.00000 1.00000 
-5       10.89838     host icp-103                         
 4   hdd  2.72459         osd.4        down  1.00000 1.00000 
 5   hdd  2.72459         osd.5        down  1.00000 1.00000 
 6   hdd  2.72459         osd.6        down  1.00000 1.00000 
 7   hdd  2.72459         osd.7        down  1.00000 1.00000 
-7       10.89838     host icp-104                         
 8   hdd  2.72459         osd.8        down  1.00000 1.00000 
 9   hdd  2.72459         osd.9        down  1.00000 1.00000 
10   hdd  2.72459         osd.10       down  1.00000 1.00000 
11   hdd  2.72459         osd.11       down  1.00000 1.00000

**Comment by vishalkanaujia** [comment]
@like-inspur thanks for sharing the diagnostic info. The primary problem we see here is that disk bluestore meta is corrupt. 

`_check_or_set_bdev_label bdev /var/lib/ceph/tmp/mnt.YEYeI6/block fsid 58419450-77be-41d0-ab87-315c04d88c15 does not match our fsid 998006b0-f366-4933-b1ab-e0505e841aae

2018-07-27 08:55:35.836202 7fd937a46d40 -1 bluestore(/var/lib/ceph/tmp/mnt.YEYeI6) mkfs fsck found fatal error: (5) Input/output error\n

2018-07-27 08:55:35.836234 7fd937a46d40 -1 OSD::mkfs: ObjectStore::mkfs failed with error (5) Input/output error`
 
I can suggest two things to fix the problem:

1. Wipe off the HDDs as follows and re-run ansible:
```
    $ ceph-disk zap /dev/sdl
    $ sgdisk -Z /dev/sdl
```
2. Also, skip the osd section in the ceph.conf since Bluestore is no more an experimental feature.
```
[osd]
enable experimental unrecoverable data corrupting features = bluestore rocksdb
```
