### ISSUE TITLE
Bluestore with lvm issue 

### ISSUE THREAD

**Issue by satishdotpatel** [ceph/ceph-ansible#2950]
I have simple question i want to use LVM with bluestore (Its recommended method), If i have only single SSD disk for osd in that case i want to keep journal + data on same disk so how should i create lvm to accommodate ?

Do i need to do following 

pvcreate /dev/sdb
vgcreate vg0 /dev/sdb

Now i have vg(500GB) so i will create two lv-01 (10G Journal) and lv-02 (490GB Data) 

I am doing correct?

**Comment by bengland2** [comment]
With Bluestore, you want to create a 10-GB RocksDB volume (block.db) and a 1-GB WAL (write-ahead log) volume on an SSD device if possible, and then create the LV with all 500 GB on the HDD device (assuming that's what /dev/sdb is).   Or you can do a single LVM volume with colocated RocksDB and WAL, but performance will be bad if this is an HDD.  See Bluestore config ref doc

**Comment by bengland2** [comment]
[here](http://docs.ceph.com/docs/master/rados/configuration/bluestore-config-ref/).

**Comment by satishdotpatel** [comment]
I totally agreed with you, in HDD case we have to have SSD for RoackDB/WAL but if i have all SSD then i can put all together. 

1GB WAL is enough for 1TB OSD ?

**Comment by mcv21** [comment]
You can just pass the raw device path ( `/dev/sdb` here ) to ceph-ansible as "lvm_volumes"["data"] in OSD group_vars - with Bluestore if you're just using 1 SSD for everything, you don't have to divide things up yourself.

**Comment by bengland2** [comment]
better yet do as the documentation now says, don't even use **lvm_volumes** or **osd_scenario**, just specify 1 variable, the **devices** list, and include your SSD device in that list, as long as scripts can detect that its non-rotational (i.e. /sys/block/your-device/queue/rotational), it will be used for WAL and RocksDB automatically.  All this is taken care of now by **ceph-volumes lvm batch** .

**Comment by bengland2** [comment]
haven't heard any complaints recently about this, closing...
