### ISSUE TITLE
RFE: need better validation of input parameters

### ISSUE THREAD

**Issue by bengland2** [ceph/ceph-ansible#2963]
This is an example of what frustrates ceph-ansible users - a situation where it doesn't like the input you gave it but it doesn't tell you why.  And it doesn't reject your input right away, so you have to wait a few minutes to find out.
```
TASK [ceph-config : generate ceph configuration file: ceph.conf] ************************************************************************************************************
fatal: [2600:3c03::f03c:91ff:feb8:6011]: FAILED! => {}
MSG:
No first item, sequence was empty.
```
And that's all it tells me!  I suspect it has to do with ipv6, but it's hard to figure out.  I tracked down the task that generates ceph.conf and it's clear that the problem was encountered while expanding the ceph.conf.j2 template file.   However, there are about a bazillion variables referenced in this file, and ansible doesn't help you by telling you which variable triggered the error - the latter may be an ansible bug perhaps?  Will append to this post when I figure out what was really wrong.

**Comment by guits** [comment]
@bengland2, this error rings a bell to me.
Although I'm not sure if python returns a traceback, could you share the full playbook run log with at least `-vv` so we can see it ?

Also, could you share which ceph-ansible, ansible, python versions you are using ?

Thanks!

**Comment by mykaul** [comment]
@bengland2 - has anyone looked at your BZ / RFE above?
We could add specific validations in ceph-ansible I reckon.
