### ISSUE TITLE
fact gathering delegation takes a long time

### ISSUE THREAD

**Issue by bengland2** [ceph/ceph-ansible#2985]
**Bug Report**

Fact gathering takes too long.

What happened:

See the bottom of the attached ceph-linode run for details.  

[deploy-2018-08-08-12-13.log.gz](https://github.com/ceph/ceph-ansible/files/2271053/deploy-2018-08-08-12-13.log.gz)

This was a cluster with 25 clients, 8 OSDs, 3 MDS servers, 1 ceph-mgr, 3 mons, for a total of 40 hosts.  It tooik 81 seconds out of the 320-second ceph-ansible run to just discover facts about the systems, or 25% of the execution time!  So this is approximately 2 seconds per host.  

What you expected to happen:

fact gathering on each host should be independent of the other hosts, therefore it should be a parallel activity, and should take ~1/10th the time (with a fork count of 20).  The problem is the with_items loop in the  'gather and delegate facts' task, which serializes this behavior.  Is there some way to do this in parallel without breaking ceph-ansible?  I think normally ansible fact-gathering works this way, but ceph-ansible turns off normal fact-gathering with "gather_facts: false" in site.yml.sample and does this manually in this task.

How to reproduce it (minimal and precise):

use the attached cluster.json, and group_vars files:

[cluster.json.gz](https://github.com/ceph/ceph-ansible/files/2271061/cluster.json.gz)
[all.yml.gz](https://github.com/ceph/ceph-ansible/files/2271062/all.yml.gz)
[osds.yml.gz](https://github.com/ceph/ceph-ansible/files/2271065/osds.yml.gz)

Run this command:

(linode-env) [root@li1015-91 ceph-linode]# ./launch.sh 2>&1 | tee l.log

which results in this inventory:

[ansible_inventory.gz](https://github.com/ceph/ceph-ansible/files/2271060/ansible_inventory.gz)

**Environment**:  linode 8 GB RAM , 3 cores
* OS (e.g. from /etc/os-release): centos 7
* Kernel (e.g. `uname -a`): 3.10.0-862.2.3.el7.x86_64
* Docker version if applicable (e.g. `docker version`):
* Ansible version (e.g. `ansible-playbook --version`): ansible-2.4.2.0-2.el7.noarch
* ceph-ansible version (e.g. `git head or tag or stable branch`): stable-3.1
* Ceph version (e.g. `ceph -v`):
ceph version 12.2.7 luminous (stable)

**Comment by bengland2** [comment]
Turns out ceph-ansible didn't run all the way because the firewall wasn't turned off in this run, but the absolute time duration of the delegate facts task was not affected by this.

**Comment by bengland2** [comment]
From Sai Malleni:

"We have not attempted large Ceph installs off late especially given that OSP 15 did not GA with ceph (plan is to add ceph support later). The 500 node effort was compute only (as goal from PM was to scale to as many computes as possible). But FWIW I ran into some issues with ansible taking too long to run (with latest Director ansible is used for configuring everything) https://bugzilla.redhat.com/show_bug.cgi?id=1746953 which fixes some ceph ansible issues with mistral trying to write large datasets to the DB (https://bugzilla.redhat.com/show_bug.cgi?id=1703618). Though you'd find that interesting."

So we don't even know if OSP15 can scale to 500 nodes with Ceph.   if we extrapolate from above, it would take 500*2 = 1000 seconds ~= 15 minutes to just have ansible run the discovery task.   Note that all the error checking for ansible happens after this step so it would be very expensive to discover configuration mistakes.   My suggestion would be to try this using Infrared to simulate a large number of openstack nodes, and then run ceph-ansible on that.   If it can't work there or takes too long, it probably can't work on the real thing either.  @fultonj ? 

excerpt from a [document I wrote about this problem](https://docs.google.com/document/d/11znGcxGZ8PCpM6p7Dkqqc4PlpwvpJ0PNJ_jXeCTN0bQ/edit#):  
"This graph shows that while fact-gathering memory overhead and O(N^2) behavior is gone,elapsed time is not improved for fact-gathering, from 1:07 to 1:17, 10 minutes to discover facts about ~90 hosts.  Root cause is serialization of fact gathering.  Also, there are still some memory spikes such as the one around tests for RHEL Atomic (unnecessary) immediately following the fact gathering plateau."

**Comment by fultonj** [comment]
I tthink reproducing is a good idea

**Comment by guits** [comment]
> The problem is the with_items loop in the 'gather and delegate facts' task, which serializes this behavior. Is there some way to do this in parallel without breaking ceph-ansible? I think normally ansible fact-gathering works this way, but ceph-ansible turns off normal fact-gathering with "gather_facts: false" in site.yml.sample and does this manually in this task.

We must do that to support `--limit` usage. You can still set `delegate_facts_host: false` when not using `--limit` (we could even change the default value for this) but the issue would still be present when using `--limit` since you would have to set `delegate_facts_host` to `True` anyway in that case.

Also, see  https://github.com/ansible/ansible/issues/26503 and https://groups.google.com/forum/#!topic/Ansible-project/f90Y4T4SJfQ

we already use facts caching so I'm not sure what we could do more at the ceph-ansible level.

@dsavineau any thoughts?

**Comment by bengland2** [comment]
@guits @fultonj is ceph-ansible dependent on per-client fact gathering?   For example, clients don't have to interact with each other (using Ceph).   The number of Ceph servers is usually far less than the number of clients for the really large configurations, so if we could eliminate clients from fact gathering loop perhaps this  would help?

**Comment by dsavineau** [comment]
I don't think so because the clients need the ceph configuration which is based on the monitor facts (like for the monitor ip address).
But this need to be tested to be sure.

**Comment by dsavineau** [comment]
Sorry I misunderstood the issue, we still have monitor facts. We just don't want clients facts.

**Comment by guits** [comment]
@bengland2 see:
https://github.com/ceph/ceph-ansible/commit/75733daf23d56008b246d8c05c5069303edd4197#diff-5e11e06bb360175675e3ae901c5d08db
and https://github.com/ceph/ceph-ansible/pull/4512
not sure why this was reintroduced.

**Comment by bengland2** [comment]
Thanks for finding the change.  The comment in the commit really doesn't explain this to me, sorry.  It looks like an attempt was made to remove the clients from fact gathering but for some reason this did not work.  Did the CI fail?  

[Here's an example ](https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-client/tasks/create_users_keys.yml#L23) where I think the ceph-clients role may depend on client fact gathering.   My questions are: how many of these are there?  Do we really have to depend on client fact gathering or is there some other way to accomplish the same goal?  @guits @dsavineau  what do you think?

Also, if we do need facts from clients, perhaps we don't need *all* of the facts, this too could cut down on time spent in the fact-gathering loop.  Here's an [article about subsetting fact gathering](https://stackoverflow.com/questions/34485286/how-to-filter-gathering-facts-inside-a-playbook).

I think this may be really important because I have seen clusters where there were 100 nodes but only 9 Ceph servers for example, this would make a significant difference in deployment time.  

Thx for your help in understanding this -ben
