### ISSUE TITLE
'dict' object has no attribute 'iteritems'

### ISSUE THREAD

**Issue by sdonnet** [ceph/ceph-ansible#2996]
**Bug Report**

What happened:

On a fresh, and supposed simple deploy of ceph-ansible, we got an error message during the 'roles/ceph-mon/tasks/deploy_monitors.yml', on the task 'generate monitor initial keyring', for our monitors  :   
`generate_caps\n    for k, v in caps.iteritems():\nAttributeError: 'dict' object has no attribute 'iteritems'`

How to reproduce it (minimal and precise):

Our group_cars/all.yml :  
```
mon_group_name: mons
osd_group_name: osds
client_group_name: clients
ceph_origin: repository
ceph_repository: community
ceph_stable_release: mimic
monitor_interface: "ens256"
public_network: "10.10.232.0/24"
cluster_network: "10.10.231.0/24"
```

Our group_vars/mons.yml :  
```
mon_group_name: mons
monitor_secret: "{{ monitor_keyring.stdout }}"
admin_secret: '*******'
secure_cluster: true
secure_cluster_flags:
  - nopgchange
  - nodelete
  - nosizechange
```
calamari: true

Share your group_vars files, inventory

**Environment**:
* OS (e.g. from /etc/os-release): **Ubuntu 18.04.1 TLS**
* Kernel (e.g. `uname -a`):  **linux 4.15.0-29-generic**
* Docker version if applicable (e.g. `docker version`):
* Ansible version (e.g. `ansible-playbook --version`): **2.6.2**
* ceph-ansible version (e.g. `git head or tag or stable branch`): **stable branch**
* Ceph version (e.g. `ceph -v`): **13.2.1**

**Comment by leseb** [comment]
Assuming stable-3.1, the failure you pasted doesn't match the task you indicated. `generate_caps` is a function from the `ceph_key` module.

Aren't you referring to `create monitor initial keyring` instead?

**Comment by sdonnet** [comment]
Hi,

Sorry, you're right, I made a typo. It is not generate monitor initial keyring, but `create monitor initial keyring`

**Comment by leseb** [comment]
That's strange, our CI does not have this issue. Which python do you use?

**Comment by sdonnet** [comment]
The site.yml playbook is played with :  
`-e 'ansible_python_interpreter=/usr/bin/python3'`

I have no python 2.7 installed on any server. Only python 3.

You think that's the matter ? I have to install the python-minimal ?

**Comment by leseb** [comment]
I guess this is the issue, `iteritems()` does not exist in python3.

**Comment by sdonnet** [comment]
Hi,

Retried with python-minimal on all servers. That's better !

Thanks !
