### ISSUE TITLE
don't use "include" in playbooks

### ISSUE THREAD

**Issue by rishabh-d-dave** [ceph/ceph-ansible#3020]
At lot of places in our codebase we use `include`, instead of `include_*` and `import_*`, which is now being "considered deprecated"[1] by the Ansible docs. Besides, `include_` and `import_` are much more unambiguous than `include` which also led to bugs in our playbooks. So IMO,  it would be nice to replace all of them.

Since this is more of a source code cleanup, I am not going with bug or feature template on while reporting.

[1] https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse.html#dynamic-vs-static

**Comment by rishabh-d-dave** [comment]
> What to take upon the task? :)

Sorry, I don't get your question.

**Comment by leseb** [comment]
Can I assign this task to you?

**Comment by rishabh-d-dave** [comment]
Sure. Since, I had the access I did it myself.  :)

**Comment by rishabh-d-dave** [comment]
At several places in out codebase the warning "Hard code this so we will skip the entire file instead of individual tasks (Default isn't Consistent)" is embedded in comments [[1]](https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-common/tasks/main.yml#L8) [[2]](https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-osd/tasks/main.yml#L4) [[3]](https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-rgw/tasks/main.yml#L9). I went through docs for Ansible's versions 2.3, 2.4, 2.5 and 2.6. `static` option's behaviour is mentioned only in 2.3's docs. So with respect to the "inconsistency", how do I figure out what to chose - `import_task` or `include_task` - while replacing `include` statements? Right now, I can't see the inconsistency by looking at the code.

**Comment by rishabh-d-dave** [comment]
Got resolved with PR - https://github.com/ceph/ceph-ansible/pull/3051.
