### ISSUE TITLE
Running deployment on large scale with ceph-ansible takes too much time

### ISSUE THREAD

**Issue by kobigi** [ceph/ceph-ansible#3021]
**Bug Report**

What happened: running or rerunning ceph-asible on a large scale  (40 blades) deployment takes ~2 Hours
This is killing me and my customers :)

What you expected to happen:
i'm pretty sure the time can be reduced the question is how ?

How to reproduce it (minimal and precise):
Run ceph-ansible on many computes, each one of them have 2 Disks e.g: 2 OSD's 

Share your group_vars files, inventory

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
3.10.0-862.6.3.el7.x86_64
* Docker version if applicable (e.g. `docker version`):
[root@undercloud (stackrc) ~]# docker version
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-63.git94f4240.el7.centos.x86_64
 Go version:      go1.9.4
 Git commit:      94f4240/1.13.1
 Built:           Fri May 18 15:44:33 2018
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-63.git94f4240.el7.centos.x86_64
 Go version:      go1.9.4
 Git commit:      94f4240/1.13.1
 Built:           Fri May 18 15:44:33 2018
 OS/Arch:         linux/amd64
 Experimental:    false

* Ansible version (e.g. `ansible-playbook --version`):
ansible-playbook 2.5.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible-playbook
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
* ceph-ansible version (e.g. `git head or tag or stable branch`):
ceph-ansible-3.1.0.0-0.rc9.1.el7.noarch
* Ceph version (e.g. `ceph -v`):
ceph version 12.2.5 (cad919881333ac92274171586c827e01f554a70a) luminous (stable)

Results of time consumption are too high especial client installation and OSD's:

2018-08-15 02:37:43,969 p=503 u=mistral |  172.31.0.9                 : ok=125  changed=12   unreachable=0    failed=0
2018-08-15 02:37:43,969 p=503 u=mistral |  INSTALLER STATUS ***************************************************************
2018-08-15 02:37:43,973 p=503 u=mistral |  Install Ceph Monitor        : Complete (0:06:38)
2018-08-15 02:37:43,974 p=503 u=mistral |  Install Ceph Manager        : Complete (0:01:25)
2018-08-15 02:37:43,974 p=503 u=mistral |  Install Ceph OSD            : Complete (0:44:01)
2018-08-15 02:37:43,974 p=503 u=mistral |  Install Ceph MDS            : Complete (0:01:36)
2018-08-15 02:37:43,975 p=503 u=mistral |  Install Ceph RGW            : Complete (0:01:29)
2018-08-15 02:37:43,975 p=503 u=mistral |  Install Ceph Client         : Complete (0:38:35)
2018-08-15 02:37:43,975 p=503 u=mistral |  Wednesday 15 August 2018  02:37:43 +0300 (0:00:00.158)       1:36:45.821 ******
2018-08-15 02:37:43,975 p=503 u=mistral |  ===============================================================================

See ansible cfg file also
[root@undercloud (stackrc) ceph-ansible]# cat ansible.cfg
# Comments inside this file must be set BEFORE the option.
# NOT after the option, otherwise the comment will be interpreted as a value to that option.

[defaults]
ansible_managed = Please do not change this file directly since it is managed by Ansible and will be overwritten
action_plugins = plugins/actions
callback_plugins = plugins/callback
roles_path = ./roles
# Be sure the user running Ansible has permissions on the logfile
log_path = /var/log/ansible.log

forks = 50
host_key_checking = False
gathering = smart
fact_caching = jsonfile
fact_caching_connection = $HOME/ansible/facts
fact_caching_timeout = 600
nocows = 1
callback_whitelist = profile_tasks

# Disable them in the context of https://review.openstack.org/#/c/469644
retry_files_enabled = False

# This is the default SSH timeout to use on connection attempts
# CI slaves are slow so by setting a higher value we can avoid the following error:
# Timeout (12s) waiting for privilege escalation prompt:
timeout = 30
deprecation_warnings = False

[ssh_connection]
# see: https://github.com/ansible/ansible/issues/11536
control_path = %(directory)s/%%h-%%r-%%p
ssh_args = -o ControlMaster=auto -o ControlPersist=600s
pipelining = True

# Option to retry failed ssh executions if the failure is encountered in ssh itself
retries = 5

**Comment by andymcc** [comment]
Are there more logs to determine which tasks were taking the most time?
I see the OSD/Client plays took the majority of the time but not too much beyond that.

In irc I believe your colleague mentioned the ceph.conf generation task?
I found those logs a bit odd since that task shouldn't run in serial, but it very much looked like it was generating the configuration file host by host - which would take time - can you give an idea of what playbook you ran? The forks value is set to 50 so it shouldn't be a case of too few forks.

**Comment by kobigi** [comment]
Hi @andymcc  , thanks for the response
i do agree with you that it seems working in SERIAL
which is strange , hence only the monitors part and mgr's i think are marked for SERIAL: 1

We did improved the client time using a patch, but i still think it is running SERIALY
adding the full log of the deployment after the improve of client keys, and the patch we used
also the original file we run during deploy

regards
[ceph-install-workflow.log.tar.gz](https://github.com/ceph/ceph-ansible/files/2312933/ceph-install-workflow.log.tar.gz)

**Comment by kobigi** [comment]
[site-docker.yml.sample.patch.txt](https://github.com/ceph/ceph-ansible/files/2312942/site-docker.yml.sample.patch.txt)

[site-docker.yml.sample.txt](https://github.com/ceph/ceph-ansible/files/2312945/site-docker.yml.sample.txt)

**Comment by k0ste** [comment]
@kobigi what is your deployment host hardware?

**Comment by k0ste** [comment]
I think this is fine if have enough cpu cores and ram.

**Comment by kobigi** [comment]
i suspect that this SERIAL for the mons

- hosts: mons
  become: True
  gather_facts: false
  roles:
    - ceph-fetch-keys
  serial: 1 # MUST be '1' WHEN DEPLOYING MONITORS ON DOCKER CONTAINERS

somehow propagates to the - hosts: osds
is that possible ?

**Comment by andymcc** [comment]
Here are the logs: https://pastebin.com/rBwRQUJg

With serial, you can only run serial at the playbook level, which means that it would run through the whole role/tasks on one host then the next - so that doesn't look like serial to me, since it only seems to be one task - although the timings seem that way. You can't run an individual task in serial at the moment, which would be a nice feature really.

If it truly is waiting to finish one host before starting the next (like it seems) that could be caused by an issue with the task or not enough forks - in which case it would wait for available forks to start another process. I'd be interested to know if it is actually waiting to finish one before doing the next - which would be very odd behaviour.

**Comment by gpocentek** [comment]
Hi!

We are having the same problem on a deployment with ~60 nodes.

The task `add ceph-osd systemd service overrides` also takes a very long time. It also uses the `config_template` module so my feeling is that the plugin might be doing something wrong. It definitely looks like the task is running sequentially on each host.

https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-osd/tasks/start_osds.yml#L91-L99

ansible version: 2.6.14
ceph-ansible: 3.2.5 from the openstack tripleo repos

**Comment by dsavineau** [comment]
@gpocentek could you share some logs and/or the systemd overrides for osd you're using ?

**Comment by gpocentek** [comment]
@dsavineau yes I'll try to get that next time we run the playbook, hopefully today.

Would it make sense for you to get an ARA log/db?

**Comment by dsavineau** [comment]
@gpocentek I could give it a try

**Comment by gpocentek** [comment]
We don't have systemd overrides, and the ceph_conf_overrides are:

```
global:
    osd_pool_default_pg_num: 32
    osd_pool_default_pgp_num: 32
    osd_pool_default_size: 3

**Comment by dsavineau** [comment]
@gpocentek well the task you mentionned is only triggered when ceph_osd_systemd_overrides is defined that's why I asked https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-osd/tasks/start_osds.yml#L98

Is it the ceph config generation task instead ? https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-config/tasks/main.yml#L142-L158

**Comment by gpocentek** [comment]
hum, I may have missed something for the systemd config then. Maybe it was this: https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-osd/tasks/start_osds.yml#L60

But several tasks take a long time, including the ceph generation task. From what I understand

We'll probably run a new deployment next week, I'll get as much log as I can.
