### ISSUE TITLE
Ceph on Utopic / Jessie

### ISSUE THREAD

**Issue by ti-mo** [ceph/ceph-ansible#305]
Hello @leseb 

Tried using the repo to install Ceph on 14.10 today, but I ran into a couple of issues. I realize using 14.10 isn't officially supported, but I'd be willing to contribute to a solution that does.

Source of the problem is package availability. `deb http://ceph.com/debian-hammer/ utopic main` was added to sources, but Ceph doesn't provide Hammer packages for utopic or jessie yet. Debian jessie users will face the same issues.

Surprisingly, even the official Utopic mirrors still stick with 0.80.9, jessie mirrors are currently at 0.80.7-2. (Vivid, however, is at 0.94.1!)

What's your take and/or previous experience on this? Would you press upstream for better package availability or install old packages on new distro releases? (eg. install wheezy on jessie or trusty on utopic, etc.) Let me know what you think or how I could help out.

Cheers!

Timo

**Comment by leseb** [comment]
Hi @ti-mo, I think it's safe to use Trusty packages for Utopic.
This is probably the reason why there is no repo available on the Ceph side.

Can you give it a shot?
Thanks!

**Comment by ti-mo** [comment]
Hey @leseb, sure, Trusty packages work just fine, no problems here. Should we just omit adding the Ceph repo on specific distributions (jessie, vivid), as well as providing a manual override ?

**Comment by leseb** [comment]
@ti-mo I wouldn't want to be distro specific and add a ton of exceptions/checks.
I'd rather create a new variable with a default value.

I just prototyped this in #310
It seems to be working for me.

**Comment by ti-mo** [comment]
@leseb, was about to push almost the exact same code. :) Works fine here, go for merge. I added the following comment in the default/group_vars configuration, though:

```
# Use the option below to specify your applicable package tree, eg. when using non-LTS Ubuntu versions
# for a list of available Debian distributions, visit http://ceph.com/debian-{{ ceph_stable_release }}/dists/
```

**Comment by leseb** [comment]
Cool :), let me re-use your comment then :)
Thanks!
