### ISSUE TITLE
CoreOS 1800.4.0 breaks ceph-common-coreos role

### ISSUE THREAD

**Issue by discostur** [ceph/ceph-ansible#3066]
**Bug Report**

What happened:

Tried to install ceph-ansible with coreos 1800.4.0 and it failed. CoreOS 1800.4.0 updates libncurses to version 6. which breaks python:

```
Container Linux by CoreOS stable (1800.4.0)
$ ls -al /opt/bin/pypy/lib_pypy/libtinfo.so.5 
lrwxrwxrwx. 1 root root 24 Jul 26 11:34 /opt/bin/pypy/lib_pypy/libtinfo.so.5 -> /lib64/libncurses.so.5.9
$ ls -al /lib64/libncurses.so.*  
lrwxrwxrwx. 1 root root     17 Jul 25 02:23 /lib64/libncurses.so.6 -> libncurses.so.6.1
-rwxr-xr-x. 1 root root 416392 Jul 24 22:04 /lib64/libncurses.so.6.1
``` 

What you expected to happen:

You should add a workaround / fix for pypy like this:

```
ln -snf $(ls /lib64/* | grep "libncurses.so.[0-9]\+.\?[0-9]\?" | tail -1) /opt/pypy/lib_pypy/libtinfo.so.5
``` 

After running that command, pyhton works as expected. Can you please add a new command / fix to your ceph-common-coreos role?

Thanks

Share your group_vars files, inventory

**Environment**:
* OS (e.g. from /etc/os-release): CoreOS stable (1800.4.0)
* ceph-ansible version (e.g. `git head or tag or stable branch`): 3.1 release

**Comment by leseb** [comment]
This role is not really maintained so if you're looking for a fix, the best/fastest way is to send a PR.
Thank you.
