### ISSUE TITLE
Install chrony instead of NTP for debian distros

### ISSUE THREAD

**Issue by bencherian** [ceph/ceph-ansible#3086]
Ceph-ansible currently installs ntpd on all hosts in order to synchronize time.

Chrony is more actively maintained and is a supported package on Ubuntu and Debian (unlike ntpd which is in universe for Ubuntu). I'd suggest changing the default NTP installation to chrony to be better aligned with the OS. I don't know if this would make sense to do for RPM distros as well since I'm unsure of the relative support level for Chrony vs. ntpd on RHEL/SUSE/etc.

This is easy enough to change myself, but given that there is no special configuration of ntpd going on, I figured it would be easy enough to change upstream and might be appreciated by others

**Comment by kcwong-verseon** [comment]
`chrony` is also available on RH/CentOS platforms as an alternative to `ntpd`.

**Comment by leseb** [comment]
I don't have any particular preference. I guess we should go with whatever if the most common/supported by each distro. @bencherian do you mind sending a PR so we can get it from here?

Thanks!

**Comment by bencherian** [comment]
Ok, this turns out to be a little more complicated than I thought...on Xenial (16.04) Ubuntu, the supported NTP daemon is the original NTP package (with chrony being in universe) while on Bionic (18.04) the opposite is the case. I'm not familiar at all with RH/CentOS packaging? (Some googling seems to indicate that chrony is the default on CentOS/RHEL 7.) Finally, it also appears that in most cases if you only need NTP client functionality, it is recommended that you just use system-timesyncd.

Just to make sure I'm not missing anything, we are usually only using the NTP client in Ceph, right? (We don't necessarily setup hosts to act as NTP peers?) Timesyncd may not be as good as Chronyd or ntpd because it doesn't track drift in as sophisticated a manner, but my understanding is that ~100 ms of clock skew is still acceptable for Ceph (we just don't want several seconds of clock discrepancies).

Perhaps the right thing to do is to just let the user choose a specific NTP daemon in a group_var. (Setting the default to be the most supported configuration may not be entirely practical.) Would there be any objections to a PR allowing for this?

**Comment by mykaul** [comment]
On RH/CentOS, we should use https://galaxy.ansible.com/linux-system-roles/timesync and not re-invent it.

**Comment by leseb** [comment]
@mykaul Good point, but we **only** make sure NTP/Chrony is started, based on that we assume the time in sync. Configuring the time is not part of ceph-ansible's job, it's up to the operator to make sure these "pre-requisites" are correct. Alternatively, we could try to integrate a validation in ceph-validate for that, but this won't quite work easily since NTP is started later in the play... So this requires more work.

**Comment by bencherian** [comment]
@leseb Ok, I will submit a PR similar to what I originally described in which timesyncd is the default NTP daemon and the user can choose to use chrony o ntpd instead. I am not really familiar with CentOS/RHEL installations, I assume it is included there as part of the default system installation as well so using it would not require installation of any specific packages.

**Comment by bencherian** [comment]
I've submitted PR #3099 to add this support. Please let me know if any changes are desired. Thanks!

**Comment by ktdreyer** [comment]
This seems related to http://tracker.ceph.com/issues/22751

**Comment by bencherian** [comment]
The default ntp client merged PR #3099 is now actually timesyncd, not chrony. It also has not yet been changed from ntpd for containerized installations.
