### ISSUE TITLE
Create unprivileged OSD containers

### ISSUE THREAD

**Issue by pahla1** [ceph/ceph-ansible#3089]
Hi all.
I'm going to create a containerized Ceph cluster with **unprivileged OSD containers**. but all the scenarios defined in ceph-ansible use privileged containers. Is there a solution to get around this issue?

Thanks in advance.
English is not my mother tongue; please excuse any errors on my part.

**Comment by leseb** [comment]
Hello, unfortunately, there are currently no ways to run unprivileged  OSD containers. Things might change in the future with Bluestore though.

Please close this issue if I answered your question.
