### ISSUE TITLE
Configure HAProxy frontends to balance load across radosgw servers.

### ISSUE THREAD

**Issue by smanjara** [ceph/ceph-ansible#3094]
Add support to use HAProxy and keepalived to balance the load across Ceph Object Gateway servers. Configure atleast two servers for HAProxy and keepalived.

haproxy config file would look something like this:

> frontend http_web *:80
> mode http
> default_backend rgw
> 
> frontend rgw­-https
> bind *:443 ssl crt /etc/ssl/private/example.com.pem
> default_backend rgw
> 
> backend rgw
> balance roundrobin
> mode http
> server rgw1 10.0.0.71:80 check
> server rgw2 10.0.0.80:80 check

**Comment by smanjara** [comment]
Or if there is already a WIP branch for this, please point me to it and feel free to close this one.

**Comment by leseb** [comment]
@mmgaggle do you have an HAProxy conf for rgw handy? Thanks!

**Comment by mmgaggle** [comment]
I do, but not like you're probably looking for - 

https://github.com/mmgaggle/ceph-lb

**Comment by mmgaggle** [comment]
FWIW, I helped the docs team flush out the configurations for keepalived and lvs-dsr. I haven't had a chance to update the ceph-lb repo yet, though.

**Comment by smanjara** [comment]
I have a very basic haproxy/keepalived templates based on our internal documentation up here: https://github.com/smanjara/ansible-haproxy/tree/master/haproxy-templates. I use this for our downstream test configuration.

**Comment by guihecheng** [comment]
@smanjara @leseb well, I am interested in this too, actually I've got a downstream version of keepalived + haproxy/lvs playbooks, I shall refine those works and open a PR soon :)

**Comment by guihecheng** [comment]
PR opend here: https://github.com/ceph/ceph-ansible/pull/3693.

**Comment by hoerup** [comment]
#3693 is merged so this can be closed
