### ISSUE TITLE
Add deployment of ganesha in the ooo-collocation CI job

### ISSUE THREAD

**Issue by gfidente** [ceph/ceph-ansible#3103]
**Is your feature request related to a problem? Please describe.**
The ooo-collocation job is not deploying Ganesha, so don't test that there.

**Describe the solution you'd like**
The ooo-collocation job should be updated to deploy Ganesha and the hosts/inventory updated with the new parameters as well.

**Comment by gfidente** [comment]
@guits @dsavineau can I help with this? do we just need the list of variables passed by tripleo to add them in the CI job?

**Comment by dsavineau** [comment]
@gfidente basically you need to update the inventory file https://github.com/ceph/ceph-ansible/blob/master/tests/functional/ooo-collocation/hosts
