### ISSUE TITLE
Switch to containerized ceph daemons fails with more than 99 OSDs

### ISSUE THREAD

**Issue by i-m-wisch** [ceph/ceph-ansible#3128]
**Bug Report**

What happened:

When converting an existing baremetal Ceph deployment that contains more than 99 OSDs to containerized, the https://github.com/ceph/ceph-ansible/blob/master/infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml#L193 playbook does not find and stop/disable/mask the services for OSDs with ids in triple digits or above.

What you expected to happen:

Playbook successfully manages baremetal services and converts to containerized services regardless of the number of OSDs.

How to reproduce it (minimal and precise):

Create non-containerized Ceph deployment with > 99 OSDs, run switch-from-non-containerized-to-containerized-ceph-daemons.yml, or just run:

systemctl list-units | grep -Eo 'ceph-osd@[0-9]{1,2}.service'

on OSD node with ids above 99.

Also, the gather facts task takes 30-45 minutes to complete, would be nice to get run_once: true added here as well:

https://github.com/ceph/ceph-ansible/blob/master/infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml#L42-L47

Reference: https://github.com/ceph/ceph-ansible/issues/2553

**Environment**:
* OS (e.g. from /etc/os-release): Red Hat Enterprise Linux Server 7.5 (Maipo)
* Kernel (e.g. `uname -a`): 3.10.0-862.11.6.el7.x86_64
* Docker version if applicable (e.g. `docker version`): 1.13.1
* Ansible version (e.g. `ansible-playbook --version`): 2.4.2.0
* ceph-ansible version (e.g. `git head or tag or stable branch`): 3.0.45
* Ceph version (e.g. `ceph -v`): 10.2.10-40.el7cp

**Comment by leseb** [comment]
https://github.com/ceph/ceph-ansible/pull/3171

**Comment by ktdreyer** [comment]
Can we close this ticket now that #3171 is merged?
