### ISSUE TITLE
ceph-volume broken when `devices` is not defined

### ISSUE THREAD

**Issue by alfredodeza** [ceph/ceph-ansible#3129]
**Bug Report**

What happened: Commit https://github.com/ceph/ceph-ansible/commit/27027a17d from PR https://github.com/ceph/ceph-ansible/pull/3113 broke ceph-volume tests because it is looking for an undefined var (devices).

This happens because `devices` is not always set (it isn't a requirement for ceph-volume always)

    TASK [ceph-config : count number of osds for non-lvm scenario] *****************
    task path: /tmp/tox.fjM8P3TRe0/xenial-filestore-dmcrypt/tmp/ceph-ansible/roles/ceph-config/tasks/main.yml:13
    skipping: [mon0] => {
        "changed": false, 
        "skip_reason": "Conditional result was False"
    }
    fatal: [osd0]: FAILED! => {}
    
    MSG:
    
    The conditional check 'devices | length > 0' failed. The error was: error while evaluating conditional (devices | length > 0): 'devices' is undefined
    
    The error appears to have been in '/tmp/tox.fjM8P3TRe0/xenial-filestore-dmcrypt/tmp/ceph-ansible/roles/ceph-config/tasks/main.yml': line 13, column 7, but may
    be elsewhere in the file depending on the exact syntax problem.
    
    The offending line appears to be:
    
      - block:
        - name: count number of osds for non-lvm scenario
          ^ here
    

What you expected to happen:

How to reproduce it (minimal and precise): Deploy Ceph with ceph-volume and no devices defined (vg/lvs are required)

**Comment by andrewschoen** [comment]
Closed with #3130
