### ISSUE TITLE
"ceph_origin" variable location/edit method not documented

### ISSUE THREAD

**Issue by dmick** [ceph/ceph-ansible#3139]
What happened:

ceph-ansible - choose installation method  says one must configure an installation method by setting the "ceph_origin" variable, but offers no guidance as to where one sets such a variable.  Apparently, it's set in group_vars/all.yml; the group_vars directory hasn't yet been introduced until the next stanza.  It would cost little to point this out in the documentation of installation methods and maintain the documentation as a sequential set of instructions.

What you expected to happen:

Documentation to flow from unknowns to knowns with in-order definitions.

**Comment by tyhal** [comment]
I believe this is resolved with:

http://docs.ceph.com/ceph-ansible/master/index.html#configuration

**Comment by dsavineau** [comment]
And even more with http://docs.ceph.com/ceph-ansible/master/installation/methods.html
