### ISSUE TITLE
mons.yml.sample crush warning unclear

### ISSUE THREAD

**Issue by dmick** [ceph/ceph-ansible#3140]
**Bug Report**

What happened:

mons.yml.sample says

```
# Caution: this will create crush roots and racks according to hostvars {{ osd_crush_location }}
# and will move hosts into them which might lead to significant data movement in the cluster!
#
# In order for the playbook to create CRUSH hierarchy, you have to setup your Ansible inventory file like so:
#
# [osds]
# ceph-osd-01 osd_crush_location="{ 'root': 'mon-roottt', 'rack': 'mon-rackkkk', 'pod': 'monpod', 'host': 'ceph-osd-01' }"
#
# Note that 'host' is mandatory and that you need to submit at least two bucket type (including the host)
#create_crush_tree: false
```

This implies, but does not state, that if create_crush_tree is not set and osds don't include the specific variable overrides in the inventory file, no crush hierarchy will be created.  Is that really true?  If so, the required variables need to be mentioned when describing the inventory file above; if not, this section needs to be clarified about when such inventory file settings are necessary.

What you expected to happen:

Clear docs

**Comment by leseb** [comment]
Thanks for reporting this.

I don't think this implies that no CRUSH hierarchy will be created, you won't get a customized CRUSH, instead, you will have what comes with Ceph by default. Basically: root > host > osd.
We can clarify all of that.
