### ISSUE TITLE
all.yml: call out mandatory variables clearly, describe defaults if no edits made

### ISSUE THREAD

**Issue by dmick** [ceph/ceph-ansible#3141]
**Bug Report**

What happened:

I was implicitly asked to copy all.yml.sample to all.yml and edit it.  There was some documentation of mandatory variables.  The file contains a number of different sections; none of them have the required variables enumerated.  These should be made obvious in their own section, with their own documentation.

Also, it is not made clear in any of the files whether the commented-out versions of the variables are the defaults if the commenting is not removed.  I'm assuming that is the case, but something should say so explicitly.

**Comment by leseb** [comment]
Thanks for reporting this, good point, we will clarify that.
