### ISSUE TITLE
all.yml includes "ceph_repository_type" with no documentation about what it means or how to set it

### ISSUE THREAD

**Issue by dmick** [ceph/ceph-ansible#3142]
What happened:
Reading through all.yml.sample, I see
```
###########
# INSTALL #
###########
#ceph_repository_type: dummy

```

I've been told I must choose ceph_repository.  No one said anything about _type.  What is it?  Do I need to set it?  What are valid values?

**Comment by ajarr** [comment]
> What happened:
> Reading through all.yml.sample, I see
> 
> ```
> ###########
> # INSTALL #
> ###########
> #ceph_repository_type: dummy
> ```
> 
> I've been told I must choose ceph_repository. No one said anything about _type. What is it? 
I looked up this doc,
http://docs.ceph.com/ceph-ansible/master/installation/methods.html#rhcs-repository
and
https://github.com/ceph/ceph-ansible/blob/master/group_vars/all.yml.sample#L178

ceph_repository_type  specifies the installation method of Red Hat Ceph Storage packages, CDN (content delivery network) or ISO.

> Do I need to set it?
You'll want to set if you'd set, 'ceph_repository' as 'rhcs'.

> What are valid values?
The valid values are 'cdn' or 'iso'
See,
https://github.com/ceph/ceph-ansible/blob/master/group_vars/all.yml.sample#L195
and
http://docs.ceph.com/ceph-ansible/master/installation/methods.html#rhcs-repository

**Comment by dmick** [comment]
Right, but, note that https://github.com/ceph/ceph-ansible/blob/master/group_vars/all.yml.sample#L128 introduces the variable, whereas https://github.com/ceph/ceph-ansible/blob/master/group_vars/all.yml.sample#L195 defines it and its options.  The questions above weren't questions I had before being able to use the product, but rather rhetorical questions to point out that, when reading the file from the top, those questions need to be answerable before a user can set the value.
