### ISSUE TITLE
ceph-volume lvm is not support batch command, and I got  unrecognized arguments: batch

### ISSUE THREAD

**Issue by Tanyy** [ceph/ceph-ansible#3146]
**Bug Report**

What happened:

when I use ceph-ansible to deploy a new ceph , I got this: 
 "ceph-volume lvm: error: unrecognized arguments: batch --bluestore --yes --crush-device-class foo /dev/sdb /dev/sdc"

when  I check :ceph-volume lvm -h , no "batch" at all.

like this:
Available subcommands:

activate                 Discover and mount the LVM device associated with an OSD ID and start the Ceph OSD
prepare                  Format an LVM device and associate it with an OSD
create                   Create a new OSD from an LVM device
list                     list logical volumes and devices associated with Ceph
trigger                  systemd helper to activate an OSD
zap                      Removes all data and filesystems from a logical volume or partition.

How to reproduce it (minimal and precise):

Share your group_vars files, inventory
all.yml:
---
dummy:
cluster: ceph
ceph_origin: distro
ceph_repository: local
ceph_stable_release: mimic
monitor_interface: eth0
public_network: 10.211.55.0/24
cluster_network: 10.211.55.0/24
radosgw_interface: eth0
radosgw_address: 10.211.55.0/24

osd.yml：
---
dummy:
osd_objectstore: bluestore
devices:
  - /dev/sdb
  - /dev/sdc
osd_scenario: lvm
lvm_volumes:
  - data: /dev/sdb
  - data: /dev/sdc
crush_device_class: foo
osds_per_device: 1

**Environment**:
* OS (e.g. from /etc/os-release): RHEL 7.4
* Kernel (e.g. `uname -a`): 3.10.0-862.9.1.el7.x86_64
* Docker version if applicable (e.g. `docker version`):
* Ansible version (e.g. `ansible-playbook --version`): 2.6.4
* ceph-ansible version (e.g. `git head or tag or stable branch`):master
* Ceph version (e.g. `ceph -v`): mimic 13.2.1
* Ceph-deploy : 2.0.1

**Comment by alfredodeza** [comment]
13.2.1 doesn't come with `batch`, it recently got backported so it will be available in the next 13.2.2 release

**Comment by guits** [comment]
@Tanyy using the latest commit on master should fix your issue.

**Comment by Tanyy** [comment]
got it , I will try it.

**Comment by alfredodeza** [comment]
@Tanyy 13.2.2 was released yesterday, this should work without a problem now
