### ISSUE TITLE
fatal: [mon3] => Version comparison: LooseVersion instance has no attribute 'version'

### ISSUE THREAD

**Issue by dfarrar117** [ceph/ceph-ansible#316]
Question, I've been testing with Vagrant and it's been working great.  Trying to deploy to my own VMs in preparation to deploy to hardware, and my 3 MON's keep getting stuck here with the latest git-pull from today.  I'm not sure why 2 fail and the 3rd is unreachable.

TASK: [ceph-mon | create filesystem pools] ************************************ 
fatal: [172.16.4.216] => Version comparison: LooseVersion instance has no attribute 'version'

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/USER/site.retry

172.16.4.212               : ok=20   changed=6    unreachable=0    failed=1   
172.16.4.215               : ok=20   changed=6    unreachable=0    failed=1   
172.16.4.216               : ok=26   changed=7    unreachable=1    failed=0

**Comment by leseb** [comment]
Ansible version issue?

**Comment by dfarrar117** [comment]
I believe it's a version issue, but I'm getting different errors with the latest git pull of ansible...

**Comment by leseb** [comment]
Ask if you need.

**Comment by dfarrar117** [comment]
what version of ansible do you use?  2.0.0 is having some syntax issues which I've been able to fix most of, but can't figure out the "generate ceph config file", keeps failing.

**Comment by leseb** [comment]
I use 1.9 on most of my envs.
Can you re-open an issue for the generate?

Could you also PR your fixes for 2.0?
Thanks!
