### ISSUE TITLE
Automatic Galaxy update

### ISSUE THREAD

**Issue by Yajo** [ceph/ceph-ansible#3165]
**Is your feature request related to a problem? Please describe.**
All [Ceph official roles in Ansible Galaxy](https://galaxy.ansible.com/ceph) are extremely outdated. This gives the impression that the project is dead. Also, when you look in the related repository, the master branch is usually outdated also (because the pushes are made as tags AFAIK), which gives the same impression.

**Describe the solution you'd like**
Some CI should import them when updated.

I use [these simple lines in a `.travis.yml`](https://github.com/Tecnativa/ansible-test-playground/blob/b94cfeaae80e294de4c2781e2f8215fc16bdc56d/.travis.yml#L7-L8) to do that, not sure if that helps...

**Describe alternatives you've considered**
Installing content directly from Github should be clearly documented.

**Comment by leseb** [comment]
@Yajo how does this https://github.com/Tecnativa/ansible-test-playground/blob/b94cfeaae80e294de4c2781e2f8215fc16bdc56d/.travis.yml#L7-L8 work exactly? Thanks

**Comment by Yajo** [comment]
Basically it communicates with an endpoint whenever there's a build.

Since Galaxy and is tightly integrated with Travis, if both are properly configured, pushes to master branch should create the needed imports in galaxy, using tags to provide versioned content.

The role at https://galaxy.ansible.com/yajo/ansible_test_playground is built through that mechanism.

- Docs for Galaxy: https://docs.ansible.com/ansible/latest/reference_appendices/galaxy.html#travis-integrations
- Docs for Travis: https://docs.travis-ci.com/user/notifications#configuring-webhook-notifications

Of course, a problem is that this repository contains several roles. That's a Galaxy limitation AFAIK: 1 role per repo. Not sure if maybe using Git subrepositories would be the fix for that? :thinking: Then add that travis configuration for each of them and you're done... Or, are we able to import a tar file into Galaxy? That could also be done in any CD quite easily, while keeping a single repo.

**Comment by leseb** [comment]
We have the mechanism to separate the roles here but this definitely needs to be adapted https://github.com/ceph/ceph-ansible/blob/master/contrib/push-roles-to-ansible-galaxy.sh

Also, I just came across that, https://galaxy.ansible.com/docs/contributing/creating_multi.html
That should do the job :)

I like the Travis workflow though. Will look into that.
Thanks!
