### ISSUE TITLE
should disable all ceph-volume services after purging cluster

### ISSUE THREAD

**Issue by wumingqiao** [ceph/ceph-ansible#3166]
After run purge-cluster.yml, ceph-volume is removed, but we have not disable ceph-volume services, which were enabled when creating osds.

[centos@wmq-1 ~]$ ls -l /etc/systemd/system/multi-user.target.wants/
total 0
lrwxrwxrwx. 1 root root 37 May 17 09:53 acpid.service -> /usr/lib/systemd/system/acpid.service
lrwxrwxrwx. 1 root root 35 Sep 25 16:22 atd.service -> /usr/lib/systemd/system/atd.service
lrwxrwxrwx. 1 root root 38 May 17 09:41 auditd.service -> /usr/lib/systemd/system/auditd.service
**lrwxrwxrwx. 1 root root 44 Sep 25 16:40 ceph-volume@lvm-0-8b2ebeaf-f076-4d71-afbf-5ee45bc42ee0.service -> /usr/lib/systemd/system/ceph-volume@.service
lrwxrwxrwx. 1 root root 44 Sep 25 16:40 ceph-volume@lvm-11-64b14a0d-2fff-42f6-8129-7665629d85e6.service -> /usr/lib/systemd/system/ceph-volume@.service
lrwxrwxrwx. 1 root root 44 Sep 25 16:40 ceph-volume@lvm-7-a91184b2-29de-4624-9841-d157e0aee101.service -> /usr/lib/systemd/system/ceph-volume@.service**
lrwxrwxrwx. 1 root root 44 May 17 12:42 cloud-config.service -> /usr/lib/systemd/system/cloud-config.service
lrwxrwxrwx. 1 root root 43 May 17 12:42 cloud-final.service -> /usr/lib/systemd/system/cloud-final.service
lrwxrwxrwx. 1 root root 48 May 17 12:42 cloud-init-local.service -> /usr/lib/systemd/system/cloud-init-local.service
lrwxrwxrwx. 1 root root 42 May 17 12:42 cloud-init.service -> /usr/lib/systemd/system/cloud-init.service
lrwxrwxrwx. 1 root root 37 May 17 09:41 crond.service -> /usr/lib/systemd/system/crond.service
lrwxrwxrwx. 1 root root 41 May 17 09:41 firewalld.service -> /usr/lib/systemd/system/firewalld.service
lrwxrwxrwx. 1 root root 42 May 17 09:41 irqbalance.service -> /usr/lib/systemd/system/irqbalance.service
lrwxrwxrwx. 1 root root 37 May 17 09:41 kdump.service -> /usr/lib/systemd/system/kdump.service
lrwxrwxrwx. 1 root root 46 May 17 09:41 NetworkManager.service -> /usr/lib/systemd/system/NetworkManager.service
lrwxrwxrwx. 1 root root 36 Sep 25 16:27 ntpd.service -> /usr/lib/systemd/system/ntpd.service
lrwxrwxrwx. 1 root root 39 May 17 09:41 postfix.service -> /usr/lib/systemd/system/postfix.service
lrwxrwxrwx. 1 root root 40 May 17 09:41 remote-fs.target -> /usr/lib/systemd/system/remote-fs.target
lrwxrwxrwx. 1 root root 39 May 17 09:41 rsyslog.service -> /usr/lib/systemd/system/rsyslog.service
lrwxrwxrwx. 1 root root 36 May 17 09:41 sshd.service -> /usr/lib/systemd/system/sshd.service
lrwxrwxrwx. 1 root root 37 May 17 09:41 tuned.service -> /usr/lib/systemd/system/tuned.service

**Comment by alfredodeza** [comment]
Related ceph-volume issue: http://tracker.ceph.com/issues/25029

**Comment by wumingqiao** [comment]
@alfredodeza Got it. So this should be done in ceph-volume zap?

**Comment by alfredodeza** [comment]
@wumingqiao not yet. But the purge playbook should remove everything/anything related to ceph in systemd, but you say that doesn't happen right?
