### ISSUE TITLE
Missing docs for stable-3.1/stable-3.2 on docs.ceph.com

### ISSUE THREAD

**Issue by berendt** [ceph/ceph-ansible#3224]
**Is your feature request related to a problem? Please describe.**
According to the README file the docs should be available at http://docs.ceph.com/ceph-ansible/stable-3.1/ and http://docs.ceph.com/ceph-ansible/stable-3.2/

**Describe the solution you'd like**
Publish docs to http://docs.ceph.com/ceph-ansible/stable-3.1/ and http://docs.ceph.com/ceph-ansible/stable-3.2/.

**Describe alternatives you've considered**
Fix the README.

**Comment by alfredodeza** [comment]
This happens because docs aren't being built for stable-3.2 or stable-3.1

What needs to happen here is that docs have to be built for stable branches. For example stable-2.1 had docs built which is why this URL succeeds http://docs.ceph.com/ceph-ansible/stable-2.1/
