### ISSUE TITLE
How to deploy a ceph cluster(containerized deployment) using ceph-ansible?

### ISSUE THREAD

**Issue by xs233** [ceph/ceph-ansible#3237]
I want to deploy a ceph cluster(containerized deployment) using ceph-ansible, but I didn't find any examples. Is there any suggestions and examples that can help me?

**Comment by xs233** [comment]
Just set the containerized_deployment variable and anything else? In other word, I know how to deploy a ceph cluster(non containerized deployment) using ceph-ansible. So I want to know the changes that comparing with non containerized deployment. The best thing is there is some examples that had deployed successfully.

**Comment by leseb** [comment]
Yes that's it, just set `containerized_deployment: True`.
