### ISSUE TITLE
detect osd_objectstore set at ceph_conf_overrides

### ISSUE THREAD

**Issue by vasukulkarni** [ceph/ceph-ansible#3242]
ceph docs recommends setting osd_objectstore to bluestore in ceph conf, if a admin has set the ceph_objectstore in ceph_conf_overrides, ceph-ansible should detect this and should be equivalent to setting it at group_vars/all level.

**Comment by leseb** [comment]
If `osd_objectstore` is set in `ceph_conf_overrides` ceph-ansible will pick it up. I don't understand your concern. Please clarify.

**Comment by vasukulkarni** [comment]
@leseb in the documentation we say it should be set in all.yml instead of ceph_conf_overrrides, is it a doc issue then? or has it to be defined at both level? Also check the RHCS documentation please.

http://docs.ceph.com/ceph-ansible/master/osds/scenarios.html

**Comment by leseb** [comment]
The doc says `Other (optional) supported settings:`, this does not mean we **have** to set that option in `all.yml`.

**Comment by vasukulkarni** [comment]
OK i missed the optinal part in the above link but the RHCS documentation should also be fixed in this case which has it documented at all.yml level(not optional),  if it doesn't work when set at ceph_conf_overrides I take it as a defect then.

**Comment by leseb** [comment]
@vasukulkarni if there is an issue downstream then please open a BZ.
