### ISSUE TITLE
osd_auto_discovery with lvm scenario

### ISSUE THREAD

**Issue by vasukulkarni** [ceph/ceph-ansible#3245]
I spoke to @alfredodeza and @andrewschoen on using osd_auto_discovery with lvm scenario, they are not sure how its supposed to behave and the input was it was added for ceph-disk use, we should make it clear in documenation whether its a supported option or admin should provide the Devices: explicitly in the config

**Comment by leseb** [comment]
Changing the tool to configure OSD doesn't mean introducing regression. This feature was never designed 'for' ceph-disk, it's just a handy functionality that anybody should be able to consume. Also ceph-volume has no equivalent as far as I know. This topic is being discussed in https://github.com/ceph/ceph-ansible/pull/3187 which I'm holding on purpose for `osd_auto_discovery` and other minor things too.

**Comment by guits** [comment]
I'm not sure to understand how we can state that something was developed for a ceph-disk thing if at the time ceph-volume was non-existent.
