### ISSUE TITLE
ceph_crush module can lose errors, output

### ISSUE THREAD

**Issue by dmick** [ceph/ceph-ansible#3246]
This is from code inspection of the ceph_crush module: it seems as though if there's more than one command in a list submitted to exec_commands(), commands 1 thru n-1's errors and output will be lost.  It doesn't seem like this is what you'd want.

```
def exec_commands(module, cmd_list):
    '''
    Creates Ceph commands
    '''
    for cmd in cmd_list:
        rc, out, err = module.run_command(cmd, encoding=None)
    return rc, cmd, out, err
```

**Comment by dmick** [comment]
(create_and_move_buckets_list can submit more than one command at once)

**Comment by leseb** [comment]
Yes, I guess we should check `rc` during each iteration and break exit the module.
Do you want to give it a try?

Thanks!
