### ISSUE TITLE
ceph-keys.yml seems to be examples of how to use the ceph_keys module

### ISSUE THREAD

**Issue by dmick** [ceph/ceph-ansible#3256]

**Comment by dmick** [comment]
"# You will find examples below on how the module can be used on daily operations"

but there is nothing but code in the file

**Comment by leseb** [comment]
Makes sense. Please send a PR picturing your thoughts and we will take it
from there.

**Comment by dmick** [comment]
trying to intuit intent from artifacts, and then clarify intent.  Whoever rebuilds is going to need to understand intent.
