### ISSUE TITLE
site-docker.yml.sample's final play missing action to set 'cluster'

### ISSUE THREAD

**Issue by dmick** [ceph/ceph-ansible#3282]
site-docker.yml.sample has a final play with two tasks, "get ceph status from the first monitor" and "show ceph status for cluster {{ cluster }}".  Both use the 'cluster' variable, but the play doesn't include a call to anything to set it.  It's possible that "roles: [ ceph-defaults ]" is the right fix (it works), but I'm not sure if that's minimal or not.

**Comment by dmick** [comment]
I just found 82ec5a29f235a07f396779564e0cec0b9a2ebfdd, but it seems wrong;  I don't understand why the default value for cluster set up by ceph-defaults, like all the other default config values, isn't the right answer; it seems like this hides the fact that the final play doesn't have access to the configuration, and if someone *had* set a variable in site{-docker}.yml, but the code remains as it is, they wouldn't get their custom value with that fix, right?

**Comment by dmick** [comment]
@leseb what do you think?

**Comment by leseb** [comment]
@dmick yes, I had to hardcode it to reflect the default value because there is no benefit of running ceph-defaults here. If someone had changed that value (`cluster`)  then site.yml will pick it up.

Sorry for the late reply, I'm closing this, feel free to re-open if you have any concerns.

**Comment by dmick** [comment]
what?  what do you mean there's no benefit of running ceph-defaults?  It's the exact thing that's needed to fix the problem.  What am I missing?

**Comment by guits** [comment]
@dmick yes, it would be the right fix, but I think what @leseb meant is that it's a pity to have to run the whole role `ceph-defaults` 'just' to play 2 tasks.

**Comment by leseb** [comment]
The only benefit of playing ceph-defaults role here is to get the default value of `cluster`. It's not like ceph-defaults is going to dynamically discover the cluster name or anything. So adding `|default('ceph')` allows us to:

* not fail
* not play the whole ceph-defaults role 'just' for a single variable value

Does that clarify a bit?
Thanks

**Comment by dmick** [comment]
it's a pity that things are defined in a complex ceph-defaults role, but that's the design.  If you're going to have a design and then explicitly violate it, there should at *least* be a comment explaining "yes, this looks wrong, but this is why it's done".  The user needs to understand the code.

**Comment by guits** [comment]
If we really want to be consistent with this design, maybe a solution would be to split again this role:
- `ceph-defaults`: for the 'very low level' default variables (cluster, *_group_name, etc...)
- `ceph-facts`: for all tasks setting a fact. Basically, everything in `./roles/ceph-defaults/tasks/facts.yml` would go in this role.

There's a couple of other places where this issue occurs, everywhere a call to a group of host is made, we hardcode the value although we have `*_group_name` variables:
eg:
- https://github.com/ceph/ceph-ansible/blob/master/site.yml.sample#L4-L15
- https://github.com/ceph/ceph-ansible/blob/master/site.yml.sample#L82

This way the current design would be respected in the whole playbook, we could play `ceph-defaults` in such situation without having to play `ceph-facts` which would be faster, I guess.

Is it worth it to do such a refact like this one 'just' for this? Should we settle for a comment explaining why things are done this way as suggested by @dmick  [here](https://github.com/ceph/ceph-ansible/issues/3282#issuecomment-445071051)?
