### ISSUE TITLE
incorrect path used for task include, breaks all Ubuntu deployments

### ISSUE THREAD

**Issue by alfredodeza** [ceph/ceph-ansible#3292]
**Bug Report**

What happened: Current ceph-ansible@master breaks all Ubuntu deployments because of this task:

    - name: debian based systems tasks
      block:
        - name: include installs/install_on_debian.yml
          include_tasks: installs/install_on_debian.yml
          tags:
            - package-install
        - name: include ntp debian setup tasks
          include_tasks: "misc/ntp_debian.yml"
          when:
            - ntp_service_enabled
      when:
        - ansible_os_family == 'Debian'

The `include_tasks: "misc/ntp_debian.yml" doesn't exist in ceph-common or the top/root level of ceph-ansible, so Ansible complains:

    TASK [ceph-common : include ntp debian setup tasks] ****************************
    task path: /tmp/tox.Ix8LZ1TUWJ/xenial-bluestore-single_type/tmp/ceph-ansible/roles/ceph-common/tasks/main.yml:20
    fatal: [mon0]: FAILED! => {
        "reason": "Unable to retrieve file contents\nCould not find or access '/tmp/tox.Ix8LZ1TUWJ/xenial-bluestore-single_type/tmp/ceph-ansible/misc/ntp_debian.yml' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"
    }
    fatal: [osd0]: FAILED! => {
        "reason": "Unable to retrieve file contents\nCould not find or access '/tmp/tox.Ix8LZ1TUWJ/xenial-bluestore-single_type/tmp/ceph-ansible/misc/ntp_debian.yml' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"
    }

Specifically: 

    "reason": "Unable to retrieve file contents\nCould not find or access '/tmp/tox.Ix8LZ1TUWJ/xenial-bluestore-single_type/tmp/ceph-ansible/misc/ntp_debian.yml' on the Ansible Controller.

Not sure how this could've worked when testing. Seems to have been caused by: https://github.com/ceph/ceph-ansible/pull/3104

What you expected to happen: Ubuntu deployments work

How to reproduce it (minimal and precise): Try to run any Ubuntu deployment. All ceph-volume tests for Xenial are broken, like e.g. https://jenkins.ceph.com/job/ceph-volume-prs-batch-xenial-bluestore-single_type/140/consoleFull

Share your group_vars files, inventory

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu Xenial
* ceph-ansible version (e.g. `git head or tag or stable branch`): master 
* Ceph version (e.g. `ceph -v`): master

**Comment by rishabh-d-dave** [comment]
PR #3294 aims to fix it.
