### ISSUE TITLE
ceph-ansible suite failed for 12.2.10 release

### ISSUE THREAD

**Issue by yuriw** [ceph/ceph-ansible#3306]
See http://pulpito.ceph.com/yuriw-2018-11-07_20:38:18-ceph-ansible-luminous-distro-basic-ovh
and
https://github.com/ceph/ceph-ansible/pull/3199#issuecomment-436792310

Here is a copy from IRC chat:

(02:07:15 PM) alfredodeza: the problem is that you can't enforce dependencies on an ansible project
(02:07:34 PM) alfredodeza: we went through the same issues when we added validation that required a new dependency
(02:09:29 PM) alfredodeza: it is like you are cloning a git repo and you need to use it, how do you enforce dependencies ?
(02:10:00 PM) alfredodeza: the problem here is that the ceph-ansible team made a change that suddenly meant that everyone needed to add a new dependency 
(02:11:45 PM) nwat: so it's like: what's the ./install-deps.sh for ceph-ansible? i guess i just assumed the sane thing would be clone then pip install -r reqs.txt or whatever
(02:11:56 PM) alfredodeza: sure
(02:11:59 PM) alfredodeza: there is a requirements.txt
(02:12:13 PM) alfredodeza: it is just that in the case of yuri's runs, and in the case of ceph-volume, we weren't doing that
(02:12:38 PM) nwat: ah! ok

We need this for 12.2.10 release!

@alfredodeza @noahdesu @liewegas FYI

**Comment by guits** [comment]
see https://github.com/ceph/ceph-ansible/pull/3199#issuecomment-436914784

**Comment by badone** [comment]
One of the problems is addressed by https://github.com/ceph/ceph-ansible/pull/3334 but I'm not sure that is all that's required. There are also changes required to the teuthology task.

**Comment by badone** [comment]
Looks like this is because for any ceph branch prior to Nautilus you now need to use the stable-3.2 branch. Trying to test this now.

**Comment by guits** [comment]
I think we can close this issue.
Feel free to reopen if needed
