### ISSUE TITLE
Unable to start service ceph-osd@vdb: Job for ceph-osd@vdb.service failed because the control

### ISSUE THREAD

**Issue by vasukulkarni** [ceph/ceph-ansible#3327]
ceph ansible version: master branch
ceph version: luminous

http://pulpito.ceph.com/yuriw-2018-11-14_16:36:42-ceph-ansible-luminous-distro-basic-ovh/

From IRC:

"""
guits
but i think the issue here is because you are running ceph-ansible@master to deploy luminous
10:14
guits
Unable to start service ceph-osd@vdb: Job for ceph-osd@vdb.service failed because the control process exited with error code. See "systemctl status ceph-osd@vdb.service" and "journalctl -xe" for details.
"""

**Comment by badone** [comment]
@vasukulkarni my current understanding is that any ceph release prior to nautilus requires the use of the stable-3.2 branch of ceph-ansible.

**Comment by leseb** [comment]
@badone is right, current master only supports Nautilus and above. If you're looking at deploying Luminous or Mimic then use stable-3.2.
