### ISSUE TITLE
Could not install successfully with latest code

### ISSUE THREAD

**Issue by selvakumarnms** [ceph/ceph-ansible#3328]
Hi ,
I tried to install ceph with two node cluster and I got below error,
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 138, in run
    res = self._execute()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 576, in _execute
    result = self._handler.run(task_vars=variables)
  File "/root/ceph-ansible/plugins/actions/validate.py", line 48, in run
    notario_store["containerized_deployment"] = host_vars["containerized_deployment"]
KeyError: 'containerized_deployment'

fatal: [compute-r1c3]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""

**Comment by guits** [comment]
Hi @selvakumarnms 

could you share your ceph-ansible and ansible version?

**Comment by selvakumarnms** [comment]
@guits 
it is based on luminous and  ansible version is 2.6.3

**Comment by guits** [comment]
@selvakumarnms "ceph-ansible" version, not "ceph" release

**Comment by selvakumarnms** [comment]
@guits thanks for response.

Now I am able to install successfully using ansible 2.6.3 and I have question regarding ceph status
my ceph status shows,
 ceph status
  cluster:
    id:     a659ee81-9f98-4573-bbd8-ef1b36aec537
    health: HEALTH_WARN
            no active mgr

  services:
    mon: 1 daemons, quorum master-r1c1
    mgr: no daemons active
    osd: 1 osds: 1 up, 1 in

  data:
    pools:   0 pools, 0 pgs
    objects: 0 objects, 0B
    usage:   0B used, 0B / 0B avail
    pgs:


I have created 1 new pool and It is not able to detect it. 
could you please help me in resolving this?
ceph osd pool ls
kube
[root@master-r1c1 ~]#

**Comment by guits** [comment]
@selvakumarnms you don't have mgr daemon deployed: 

`no active mgr`

 that's why.

**Comment by selvakumarnms** [comment]
@guits thanks.. is mgr is mandatory to be enabled in ceph ?

**Comment by guits** [comment]
yes it is

**Comment by cwqcwqmax9** [comment]
sorry , i have occurs same  problem
raceback (most recent call last):
File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 139, in run
res = self._execute()
File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 577, in _execute
result = self._handler.run(task_vars=variables)
File "/root/ceph-ansible/plugins/actions/validate.py", line 48, in run
notario_store["containerized_deployment"] = host_vars["containerized_deployment"]
KeyError: 'containerized_deployment'



what should  i  do to solve

**Comment by cwqcwqmax9** [comment]
my ansible version is 2.6.3

     ceph-ansible is master

**Comment by cwqcwqmax9** [comment]
> am able to install successfully

how did you  solve  the problem?

**Comment by guits** [comment]
@cwqcwqmax9 please, share more details
group_vars/*
playbook logs
how you launched the playbook, etc...

thanks
