### ISSUE TITLE
Support for different storage topologies.

### ISSUE THREAD

**Issue by srelf-ukcloud** [ceph/ceph-ansible#3329]
**Is your feature request related to a problem? Please describe.**
Currently we run different storage topologies inside our ceph cluster, once type of node conists of full SSD OSD's with the journal colocated on the SSD, the other consists of a set of spinning disks with journals located on the SSD.

**Describe the solution you'd like**
I would like a way to configure this topology using CEPH ansible, i believe that this can be partly achieved using devices as part of the inventory file, but i dont think you can mix and match, as you have to set the global colocation method.
 
**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by tssvl** [comment]
I think you can mix both this types of topology.

I do something like this:

**all.yml:**
`osd_scenario: non-collocated
`

An then using inventory devices and dedicated_devices you can configure whatever topology you want.

**inventory.yml:**
`
osds:
  hosts:
    ceph-s3-1:
      devices: ['/dev/sdd', '/dev/sde', '/dev/sdf', '/dev/sdb', '/dev/sdc']
      dedicated_devices: ['/dev/sda', '/dev/sda', '/dev/sda', '/dev/sdb', '/dev/sdc']
`

As result we see that **sdd**, **sde**, **sdf** are slow disks with journals on fast **sda** disk.
And **sdb**, **sdc** fast disks with self collocated journals.

**Comment by srelf-ukcloud** [comment]
ha. didnt think of that. that will work.

Thanks
