### ISSUE TITLE
ceph status : Reduced data availability: 250 pgs inactive

### ISSUE THREAD

**Issue by selvakumarnms** [ceph/ceph-ansible#3344]
I installed ceph luminous version and I got below warning message,
 ceph status
 cluster:
    id:     a659ee81-9f98-4573-bbd8-ef1b36aec537
    health: HEALTH_WARN
            Reduced data availability: 250 pgs inactive
            Degraded data redundancy: 250 pgs undersized

  services:
    mon: 1 daemons, quorum master-r1c1
    mgr: master-r1c1(active)
    osd: 1 osds: 1 up, 1 in

  data:
    pools:   1 pools, 250 pgs
    objects: 0 objects, 0B
    usage:   1.00GiB used, 8.99GiB / 10.0GiB avail
    pgs:     100.000% pgs not active
             250 undersized+peered

Ceph osd, monitor and mgr are all installed in one node

could not install pool with more that 250 pg
ceph --cluster ceph osd pool create kube 250 250   replicated replicated_rule  1000000

kindly suggest me to solve the above error

**Comment by dsavineau** [comment]
That's because you only have one OSD but the pool size (replicas count) is still set to 3.
If you decrease the size of the pool to 1, all PG will become available
```console
ceph osd pool set kube size 1
```

**Comment by abalib** [comment]
> That's because you only have one OSD but the pool size (replicas count) is still set to 3.
> If you decrease the size of the pool to 1, all PG will become available
> 
> ```
> ceph osd pool set kube size 1
> ```

Solved my exact problem.  Thank you.  In addition I must be running a backlevel ceph or kernel which required this
sudo rbd map mypool/foo
rbd: sysfs write failed
RBD image feature set mismatch. You can disable features unsupported by the kernel with "rbd feature disable mypool/foo object-map fast-diff deep-flatten"
sudo rbd feature disable mypool/foo object-map fast-diff deep-flatten
sudo rbd map mypool/foo
/dev/rbd0
