### ISSUE TITLE
luminous: 'ceph-create-keys:ceph-mon is not in quorum' exceeds retries on ovh nodes

### ISSUE THREAD

**Issue by yuriw** [ceph/ceph-ansible#3349]
This issue is a copy of http://tracker.ceph.com/issues/37351

**Bug Report**

What happened:

What you expected to happen:

How to reproduce it (minimal and precise):

Share your group_vars files, inventory

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Docker version if applicable (e.g. `docker version`):
* Ansible version (e.g. `ansible-playbook --version`):
* ceph-ansible version (e.g. `git head or tag or stable branch`):
* Ceph version (e.g. `ceph -v`):

**Comment by yuriw** [comment]
we are not yet sure this is `ceph-ansible` issue so only FYI ATM

**Comment by guits** [comment]
Looking at http://tracker.ceph.com/issues/37351 I think we can close this one.
Feel free to re-open if needed.
