### ISSUE TITLE
Ceph purge cluster not working

### ISSUE THREAD

**Issue by selvakumarnms** [ceph/ceph-ansible#3355]
Hi,
while purge cluster, I got below error, ceph-ansible taken from master and release is luminous.

ansible 2.7.1

/usr/share/ansible/ceph-ansible/infrastructure-playbooks/purge-cluster.yml

ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/usr/share/ansible/ceph-ansible/infrastructure-playbooks/purge-cluster.yml': line 353, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  - name: zap and destroy osds created by ceph-volume with lvm_volumes
    ^ here

**Comment by leseb** [comment]
Closing based on the last comment

**Comment by KingJ** [comment]
A note for anyone coming across this in the future - Ansible will automatically discover libraries that are located in a library folder, relative to the directory of the playbook being executed. If you execute a playbook in infrastructure-playbooks directory, then the libraries folder located within ceph-ansible's root cannot be discovered.

As above, you can work around this by editing the ansible.cfg file and adding an explicit path to the libraries folder, which will mean that the libraries are loaded regardless of which folder the executed playbook is in. Alternatively, you can copy the relevant playbook (i.e. purge-cluster.yml) to ceph-ansible's root directory (one level up) and execute it there, which will discover the libraries folder without needing to alter the configuration (the [README](https://github.com/ceph/ceph-ansible/blob/master/infrastructure-playbooks/README.md) suggests this is the best course of action too).
