### ISSUE TITLE
failed: [host3] (item=/var/lib/ceph/bootstrap-rbd-mirror/ceph.keyring)

### ISSUE THREAD

**Issue by aawm** [ceph/ceph-ansible#3357]
**Bug Report**

What happened:  Installed a 3 nodes ceph cluster, finished with 3 mons, 2 osds and 2 mgrs, and the keyring error happened, that stopped mgr, osd install on host3. The 3 nodes are identical physical servers.

Error log:  failed: [host3] (item=/var/lib/ceph/bootstrap-rbd-mirror/ceph.keyring) => {"changed": false, "item": "/var/lib/ceph/bootstrap-rbd-mirror/ceph.keyring", "msg": "file
not found: /var/lib/ceph/bootstrap-rbd-mirror/ceph.keyring"}

What you expected to happen: I was expecting the 3 nodes ceph cluster with mon, osd and mgr on each node.

How to reproduce it (minimal and precise):

 ansible-playbook site.yml -i ~/AHF/hosts_ceph

Share your group_vars files, inventory
~/AHF/hosts_ceph

[mons]
host1
host2
host3

[mgrs]
host1
host2
host3

[osds]
host1
host2
host3

group_vars/all.yml

fetch_directory: ~/ceph-ansible-keys
cluster: ceph

ceph_origin: repository
ceph_repository: community
ceph_stable_release: mimic

osd_objectstore: bluestore

monitor_interface: enp2s0f0
public_network: 10.x.x.0/24
cluster_network: 192.168.x.0/24

# General ceph options
generate_fsid: true
cephx: true

group_vars/osds.yml

osd_objectstore: bluestore
osd_scenario: lvm
dmcrypt: false

# devices common to all osd hosts
lvm_volumes:
  - data: /dev/sdb
  - data: /dev/sdc
  - data: /dev/sdd

**Environment**:
* OS (e.g. from /etc/os-release): CentOS Linux release 7.5.1804 (Core).
* Kernel (e.g. `uname -a`): Linux 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Docker version if applicable (e.g. `docker version`): NO. 
* Ansible version (e.g. `ansible-playbook --version`):
ansible 2.7.1
  config file = /root/ceph-ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules', u'/root/ceph-ansible/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

* ceph-ansible version (e.g. `git head or tag or stable branch`):
git branch
* master
  stable-3.2

* Ceph version (e.g. `ceph -v`): ceph -v
ceph version 13.2.2 (02899bfda814146b021136e9d8e80eba494e1126) mimic (stable)

ceph status
  cluster:
    id:     80a61c1c-e073-4d26-a21c-714faac5a840
    health: HEALTH_OK

  services:
    mon: 3 daemons, quorum host3,host1,host2
    mgr: host1(active), standbys: host2
    osd: 6 osds: 6 up, 6 in

  data:
    pools:   0 pools, 0 pgs
    objects: 0  objects, 0 B
    usage:   6.0 GiB used, 814 GiB / 820 GiB avail
    pgs:

**Comment by aawm** [comment]
@guits Just on master, I couldn't run stable-3.2 branche, as I have Ansible 2.7.1

**Comment by aawm** [comment]
I think the issue maybe related with the code in master/roles/ceph-mon/tasks/ceph_keys.yml

- name: copy keys to the ansible server
  fetch:
    src: "{{ item }}"
    dest: "{{ fetch_directory }}/{{ fsid }}/{{ item }}"
    flat: yes
  with_items:
    - "{{ ceph_keys.get('stdout_lines') | default([]) }}"
    - /var/lib/ceph/bootstrap-osd/{{ cluster }}.keyring
    - /var/lib/ceph/bootstrap-rgw/{{ cluster }}.keyring
    - /var/lib/ceph/bootstrap-mds/{{ cluster }}.keyring
    - /var/lib/ceph/bootstrap-rbd/{{ cluster }}.keyring
    - /var/lib/ceph/bootstrap-rbd-mirror/{{ cluster }}.keyring
  when:
    - cephx
    - inventory_hostname == groups[mon_group_name] | last

It failed on last node because /var/lib/ceph/bootstrap-rbd-mirror/{{ cluster }}.keyring doesn't exist on node.

**Comment by guits** [comment]
could you fetch the last content of master branch and try again? We've got a patch that should fix this issue I think.

**Comment by guits** [comment]
ceph-ansible@master is intended to deploy ceph@master only

if you want to deploy mimic, you must use ceph-ansible@stable-3.2

**Comment by aawm** [comment]
@guits Thanks for the clarification.
