### ISSUE TITLE
Allow clients to be exempt from firewall configuration

### ISSUE THREAD

**Issue by RichardStevenson** [ceph/ceph-ansible#3373]
Ceph clients may have a range of requirements to serve their intended purpose. Allowing ceph-ansible to configure the firewall on these hosts may break other services on that hosts. For this reason it would be convenient to have an option to set ceph ansible to configure the firewall on all hosts other than clients.

**Comment by guits** [comment]
@RichardStevenson this is possible by setting `configure_firewall: False` in `group_vars/clients.yml`
