### ISSUE TITLE
`tox -e luminous-cluster -- --provider=libvirt` fails as LVs are not created in OSD hosts

### ISSUE THREAD

**Issue by ajarr** [ceph/ceph-ansible#3399]
**Bug Report**

What happened: ``tox -e luminous-cluster -- --provider=libvirt`` fails with ceph-ansible stable 3.2 branch
at this stage,
```
TASK [ceph-osd : use ceph-volume to create bluestore osds] ********************************************************************************************************************************************************
task path: /home/rraja/git/ceph-ansible2/roles/ceph-osd/tasks/scenarios/lvm.yml:2
Friday 30 November 2018  16:52:50 +0530 (0:00:00.180)       0:21:49.558 ******* 
failed: [ceph-osd1] (item={u'data': u'data-lv1', u'data_vg': u'test_group'}) => {
    "changed": true, 
    "cmd": [
        "ceph-volume", 
        "--cluster", 
        "ceph", 
        "lvm", 
        "create", 
        "--bluestore", 
        "--data", 
        "test_group/data-lv1"
    ], 
    "delta": "0:00:00.374136", 
    "end": "2018-11-30 11:22:51.594509", 
    "item": {
        "data": "data-lv1", 
        "data_vg": "test_group"
    }, 
    "rc": 2, 
    "start": "2018-11-30 11:22:51.220373"
}

STDOUT:

 stderr: lsblk: test_group/data-lv1: not a block device
 stderr: error: test_group/data-lv1: No such file or directory
```

What you expected to happen: run successful

How to reproduce it (minimal and precise):

```
tox -e luminous-cluster -- --provider=libvirt
```
**Environment**:
* OS (e.g. from /etc/os-release): fedora 28
* Kernel (e.g. `uname -a`): 4.18.9-200.fc28.x86_64
* Ansible version (e.g. `ansible-playbook --version`): 2.6.4
* ceph-ansible version (e.g. `git head or tag or stable branch`): stable 3.2 , head at 452069cb3a2d0ee11552f
* Ceph version (e.g. `ceph -v`): 12.2.10

**Comment by leseb** [comment]
What's the failure?

**Comment by ajarr** [comment]
@leseb, I was updating the bug report while you asked the question. I've the PR fix

**Comment by guits** [comment]
`luminous-cluster` ?

**Comment by ajarr** [comment]
> `luminous-cluster` ?

are you saying it's not a valid scenario? it does show up with 'tox -l', and it defaults to luminous-centos7-cluster.

Please look at the PR. If you think the PR/bug is not useful, I can close it.

**Comment by ajarr** [comment]
The issue has been fixed with the merge.
