### ISSUE TITLE
directories shouldn't be created before ceph installs

### ISSUE THREAD

**Issue by alfredodeza** [ceph/ceph-ansible#3430]
**Bug Report**

What happened: ceph-ansible creates directories and sets permissions before installing Ceph

What you expected to happen: Directory creation and permission setting should happen by the packaging itself. If the packaging rules aren't setting paths or permissions correctly, it is a bug in Ceph, not ceph-ansible

How to reproduce it (minimal and precise): This task is running:
`ceph-config : create ceph initial directories owner={{ ceph_uid }}, group={{ ceph_uid }}, mode=493, state=directory, path={{ item }}]` Which does things like:

    changed: [mon0] => (item=/var/lib/ceph/bootstrap-osd) => {
        "changed": true,
        "gid": 167,
        "group": "ceph",
        "item": "/var/lib/ceph/bootstrap-osd",
        "mode": "0755",
        "owner": "ceph",
        "path": "/var/lib/ceph/bootstrap-osd",
        "secontext": "system_u:object_r:ceph_var_lib_t:s0",
        "size": 6,
        "state": "directory",
        "uid": 167
    }

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Docker version if applicable (e.g. `docker version`):
* Ansible version (e.g. `ansible-playbook --version`):
* ceph-ansible version (e.g. `git head or tag or stable branch`):
* Ceph version (e.g. `ceph -v`):

**Comment by leseb** [comment]
This is only needed for containers, let me fix this. Thanks.
