### ISSUE TITLE
Aliases in ceph-aliases.sh.j2 need to be renamed or removed

### ISSUE THREAD

**Issue by idryomov** [ceph/ceph-ansible#3445]
When "rbd map" is invoked on a host with a ceph-mon container on it, it gets redirected to that container.  However, "rbd map" requires privileges: on top of dealing with udev and device nodes, it has to be able to add a key to the keyring, which is locked down by docker's default seccomp profile.

```
# rbd map pool/img
rbd: failed to add secret 'client.admin' to kernel
In some cases useful info is found in syslog - try "dmesg | tail".
rbd: map failed: (1) Operation not permitted

# type rbd
rbd is a function
rbd ()
{
    sudo docker exec ceph-mon-c10-h19-r730xd rbd --cluster ceph ${@}
}
```

The silent aliasing has resulted in some profound confusion and is bound to cause more in the future, not just with "rbd map".  Version mismatches, subtle permission and file access issues, capabilities, seccomp, etc.

The original PR (https://github.com/ceph/ceph-ansible/pull/2426) sited [1] as an example, but these etcdctl wrappers have their own names and don't alias the actual etcdctl.  Neither do they silently exec into a container...

[1] https://github.com/openshift/openshift-ansible/blob/release-3.7/roles/etcd/etcdctl.sh

**Comment by leseb** [comment]
I believe the `ceph` and `radosgw-admin` commands will still be useful, perhaps we should remove `rbd` and `rados` only?

**Comment by idryomov** [comment]
I think they should all be renamed or removed.  Redirecting into a container is just too sneaky:

```
# ceph osd getcrushmap -o /tmp/cmap.bin
47
# stat /tmp/cmap.bin
stat: cannot stat ‘/tmp/cmap.bin’: No such file or directory
```

**Comment by leseb** [comment]
Yes because the file is in the container...
Ok we can remove that I suppose.
