### ISSUE TITLE
task "reuse cluster fsid when cluster is already running" run failed when cephx = false and generate_fsid = false

### ISSUE THREAD

**Issue by mslovy** [ceph/ceph-ansible#3453]
when setting cephx = false and generate_fsid = false, I got failed on tasks "reuse cluster fsid when cluster is already running"

The reason is the /tmp/fetch dir is not create on  tasks
- name: create a local fetch directory if it does not exist
  local_action:
    module: file
    path: "{{ fetch_directory }}"
    state: directory
  changed_when: false
  become: false
  when:
    - (cephx or generate_fsid)
it is skipped here.

**Comment by guits** [comment]
@mslovy we are definitely missing a lot of information here.
please, share full playbook log, ceph-ansible version, content of group_vars ...
