### ISSUE TITLE
Vagrant: Osd failed with no such file or directory

### ISSUE THREAD

**Issue by Serjal** [ceph/ceph-ansible#3468]
**Bug Report**

What happened: Task "ceph-osd : manually prepare ceph "bluestore" non-containerized osd disk(s) with collocated osd data and journal" is run in osd LVM scenario and failed with no such file or directory. See appended log file.

What you expected to happen: Expected the osds to come up without issues

How to reproduce it (minimal and precise):

1. Checkout master
2. Use group_var/config provided below
3. `mv vagrant_variables.yml.sample vagrant_variables.yml`
4. Install requirements `pip install -r requirements.txt`
5. Run `vagrant up`

Share your group_vars files, inventory

```
ceph_origin: repository
ceph_repository: dev
ceph_stable_release: mimic
public_network: "192.168.42.0/24"
cluster_network: "192.168.43.0/24"
monitor_interface: eth1
devices:
  - '/dev/sdb'
  - '/dev/sdc'
osd_scenario: lvm
```
The inventory was generated by Vagrant.

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 16.04 from Vagrant box ceph/ubuntu-xenial
* Kernel (e.g. `uname -a`): Linux osd0 4.4.0-22-generic #40-Ubuntu SMP Thu May 12 22:03:46 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
* Docker version if applicable (e.g. `docker version`): 
* Ansible version (e.g. `ansible-playbook --version`): ansible 2.7.5
* ceph-ansible version (e.g. `git head or tag or stable branch`): git master on commit 160090b441882daa7378b43b42fb110f1f6b5d64
* Ceph version (e.g. `ceph -v`): ceph version 14.0.1-2013-g0ccdc79 (0ccdc799384801faa728d5429e82b522ee3b618b) nautilus (dev)
[ansible.log](https://github.com/ceph/ceph-ansible/files/2710841/ansible.log)

**Comment by rishabh-d-dave** [comment]
Master only supports Ceph master; use stable-3.1 or stable-3.2 if you want to use mimic. See - http://docs.ceph.com/ceph-ansible/master/index.html#releases.

**Comment by Serjal** [comment]
@rishabh-d-dave 
As far as I understand Ceph-Ansible ignores the ceph_stable_release variable, if the ceph_repository is set to dev. 
And the ceph -v command has been run inside one of the mon-vms.  As you can see in my issue the ceph version installed by ceph-ansible is 

> ceph version 14.0.1-2013-g0ccdc79 (0ccdc799384801faa728d5429e82b522ee3b618b) nautilus (dev).

The line with mimic is leftover from earlier tests.

**Comment by guits** [comment]
@Serjal you must have `osd_scenario` overrided somewhere that makes the playbook including `collocated.yml`

**Comment by guits** [comment]
I think this is because of [this](https://github.com/ceph/ceph-ansible/blob/master/Vagrantfile#L81)

**Comment by rishabh-d-dave** [comment]
@guits 
But shouldn't the value in `group_vars/osd.yml` override the value in `Vagrantfile`?

**Comment by guits** [comment]
@rishabh-d-dave curiously, no. If I remember correctly, everything set in the Vagrantfile like this can't be overrided in `group_vars/*.yml`, this is something strange that I've been facing long time ago.
I've never got a chance to dive into this issue, I think this is something expected because of the vagrant layer.
To double check I'm not putting you on the wrong path, you can set something in the Vagrantfile, override it in group_vars and print it (early) in the playbook. If I'm not mistaking, you should see the value set in the Vagrantfile even if you expect it to be what you've set in group_vars.

**Comment by Bruceforce** [comment]
Isn't this the expected behavior of ansible? If you have a look at this https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable it states:

> extra vars (always win precedence)

so every variable in the `ansible.extra_vars` would always win.

**Comment by rishabh-d-dave** [comment]
@guits 
What about moving `osd_scenario` (and other default values) from `Vagrantfile` to `ceph-default`? This way these values would be override-able.

**Comment by guits** [comment]
@rishabh-d-dave I think we should simply remove the defalut value for osd_scenario from Vagrantfile.
The few default values in the Vagrantfile were there only so you could deploy a minimal cluster without having to set anything in group_vars. I'm unsure this is something really relevant, I would recommend to use ceph-nano for such use cases.
