### ISSUE TITLE
'not monitor_keyring_conf.stat.exists' failed

### ISSUE THREAD

**Issue by discostur** [ceph/ceph-ansible#3479]
**Bug Report**

What happened:

```
fatal: [ceph-mon01]: FAILED! => {"msg": "The conditional check 'not monitor_keyring_conf.stat.exists' failed. The error was: error while evaluating conditional (not monitor_keyring_conf.stat.exists): 'monitor_keyring_conf' is undefined\n\nThe error appears to have been in '/root/ansible-playbooks/ceph-ansible/roles/ceph-common/tasks/main.yml': line 44, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: include facts_mon_fsid.yml\n  ^ here\n"}
```

Just updated to ceph-ansible 3.2.1 and got the error above. Not shure, but i thought it was working with 3.2.0 ...

**Environment**:
* OS (e.g. from /etc/os-release): CentOS Linux release 7.6.1810 (Core) 
* ceph-ansible version (e.g. `git head or tag or stable branch`): 3.2.1
* Ceph version (e.g. `ceph -v`): ceph version 13.2.4 (b10be4d44915a4d78a8e06aa31919e74927b142e) mimic (stable)

**Comment by leseb** [comment]
@discostur Can we have a more complete log? Thanks. We need to see when `monitor_keyring_conf` was register earlier in the play to further debug this.

**Comment by discostur** [comment]
@leseb thanks for pointing me into the right direction. The variable _monitor_keyring_conf_ was never set! I figured out that i had an old site.yml which didn't include the latest changes. I just copied the site.yml.sample over my existing site.yml and now it is working again ;)

**Comment by marcoarildo** [comment]
@discostur @leseb Hi, I did the same thing and now I got success !!!
Congratulations !!!
