### ISSUE TITLE
initial keyring does not contain keys

### ISSUE THREAD

**Issue by snoopel** [ceph/ceph-ansible#3483]
Hello,
I have updated from version 3.0 to version 3.2.

I get the following error message:

2019-01-08 20:33:57,122 p=125021 u=root |  fatal: [10.253.91.132]: FAILED! => changed=false 
  msg: 'initial keyring does not contain keys: client.bootstrap-mgr client.bootstrap-rbd-mirror'
  rc: 1
2019-01-08 20:33:57,127 p=125021 u=root |  fatal: [10.253.91.131]: FAILED! => changed=false 
  msg: 'initial keyring does not contain keys: client.bootstrap-mgr client.bootstrap-rbd-mirror'
  rc: 1
2019-01-08 20:33:57,141 p=125021 u=root |  fatal: [10.253.91.133]: FAILED! => changed=false 
  msg: 'initial keyring does not contain keys: client.bootstrap-mgr client.bootstrap-rbd-mirror'

* OS (e.g. from /etc/os-release):
VERSION="16.04.3 LTS (Xenial Xerus)"
* Kernel (e.g. `uname -a`):
4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* Ansible version (e.g. `ansible-playbook --version`):
ansible-playbook --version
ansible-playbook 2.7.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]
* ceph-ansible version (e.g. `git head or tag or stable branch`):
Master-release 
* Ceph version (e.g. `ceph -v`):
ceph -v
ceph version 12.2.10 (177915764b752804194937482a39e95e0ca3de94) luminous (stable)

**Comment by zmc** [comment]
I've been hitting this consistently recently; I thought it must be a recent regression, but I haven't been able to work around it by reverting anything recent. Perhaps it has been broken for quite some time?

**Comment by leseb** [comment]
This is because you're using ceph-ansible@master to deploy L or M. Use stable-3.2 to deploy L or M.
