### ISSUE TITLE
monitor_address_block

### ISSUE THREAD

**Issue by batrick** [ceph/ceph-ansible#3491]
Letting you all know that ceph-linode no longer uses this. We now use the more robust solution of putting the monitor_address in the ansible_inventory [1]. As such, the original use-case for `monitor_address_block` is gone. Unless there is some other user, maybe you should feel free to drop it.

[1] https://github.com/batrick/ceph-linode/blob/a1e735c8e00b56985ae7348dc0bc4fd1a8c29c00/linode-launch.py#L178

**Comment by gfidente** [comment]
@guits correct we still do, we also use radosgw_address_block

I wonder why MONs don't pick up the binding addresses from the cluster/public networks like MDSs and MGRs do?

**Comment by gfidente** [comment]
@guits this one can probably be abandoned?
