### ISSUE TITLE
I have problem to enable the usage log on ceph.conf using the ansible-playbook

### ISSUE THREAD

**Issue by marcoarildo** [ceph/ceph-ansible#3496]
Hello, 
Somebody can help me, please ?

**I need to active the usage log.**

So I did this, I created the file **group_vars/rgws.yml** like this:

```
ceph_conf_overrides:
  "client.rgw.{{ hostvars[inventory_hostname]['ansible_hostname'] }}":
    rgw enable usage log = true
    rgw usage log tick interval = 30
    rgw usage log flush threshold = 1024
    rgw usage max shards = 32
    rgw usage max user shards = 1
```
This is my **ceph.conf** file before execute the changes:
```
[client.rgw.rgw01]
host = rgw01
keyring = /var/lib/ceph/radosgw/ceph-rgw.rgw01/keyring
log file = /var/log/ceph/ceph-rgw-rgw01.log

[client.rgw.rgw02]
host = rgw02
keyring = /var/lib/ceph/radosgw/ceph-rgw.rgw02/keyring
log file = /var/log/ceph/ceph-rgw-rgw02.log
```
So I executed the ansible-playbook this way:
```
# ansible-playbook site.yml -l rgw02
```

Now, this is my changed file **ceph.conf**, take a look:
```
[DEFAULT]
client.rgw.rgw01 = rgw enable usage log = true rgw usage log tick interval = 30 rgw usage log flush threshold = 1024 rgw usage max shards = 32 rgw usage max user shards = 1

[client.rgw.rgw01]
host = rgw01
keyring = /var/lib/ceph/radosgw/ceph-rgw.rgw01/keyring
log file = /var/log/ceph/ceph-rgw-rgw01.log

[client.rgw.rgw02]
host = rgw02
keyring = /var/lib/ceph/radosgw/ceph-rgw.rgw02/keyring
log file = /var/log/ceph/ceph-rgw-rgw02.log
```

The line "enable usage log ..." was inserted in the section "DEFAULT" and did not break the lines.

I was imagine that the information about rgw usage log and the others would be insert the section [client.rgw.rgw02]

What I did wrong ? I forgot something ?

Tks guys

My Environment:

* OS CentOS-7
* Kernel: 3.10.0-862.14.4.el7.x86_64
* Docker versison: N/A
* ceph-ansible: stable-3.2
* ceph version: 13.2.2

**Comment by andymcc** [comment]
@marcoarildo - i think the formatting on your overrides is the issue here, they should look something more like this:

ceph_conf_overrides:
  "client.rgw.{{ hostvars[inventory_hostname]['ansible_hostname'] }}":
    rgw_enable_usage_log: true
    rgw_usage_log_tick_interval: 30
    rgw_usage_log_flush_threshold: 1024
    rgw_usage_max_shards: 32
    rgw_usage_max_user_shards: 1

Note the change from "x = y" to "x: y".
Additionally, the change from "option name is this" to "option_name_is_this" with the underscores.
You may be able to leave the spaces by putting inverted commas around the option name like this:
"option name": value

But in my opinion its simpler to use the underscores.

Let us know if that works for you or if you have further issues. I'll close this issue out, but feel free to reopen it if it's not working for you!

**Comment by marcoarildo** [comment]
@andymcc - Unfortunately its did not work, the 'usage log' is not activated yeat.
Now in the ceph.conf file, two sessions are appearing.
See below.

see the contents of the file ceph.conf:

[client.rgw.rgw02]
host = rgw02
keyring = /var/lib/ceph/radosgw/ceph-rgw.rgw02/keyring
log file = /var/log/ceph/ceph-rgw-rgw02.log

[client.rgw.rgw02]
rgw enable usage log = true
rgw usage log tick interval = 30
rgw usage log flush threshold = 1024
rgw usage max shards = 32
rgw usage max user shards = 1

After execute **ansible-playbook** and to wait some hours, i tried to call the api, like this:

http://s3service/admin/usage?uid=nameid&format=json

I get the result:
{"entries":[],"summary":[]}

I guess is not right have two sessions with **[client.rgw.rgw02]**, is this the problem ? How can i solve this and put only one session ?

Other question, what is the right file to apply the ceph_conf_overrides, rgws.yml or all.yml ?

Tks again for help me.

**Comment by andymcc** [comment]
I believe rgws.yml takes precedence (it's alphabetical with the last read being taken as the value - probably test this to verify but I believe that's how it was), but if you want an option to only be applied to rgw hosts then the rgws.yml is the right place. This gets tricky because if you specify the same var in both places the one will be ignored in favour of the other.

I'm not sure why you are getting 2 of the same section though - that seems wrong. Can you show a copy of your group_vars files for rgws and all? something is going wrong to make it think there are 2 different sections and not collapse them properly.

**Comment by marcoarildo** [comment]
@andymcc - follow the contents of the files and thanks again.

In this case we have 2 sessions for **[client.rgw.rgw01]**

```
[root@ceph-deploy ceph-ansible]# grep -o '^[^#]*' group_vars/all.yml
---
ceph_release_num:
  luminous: 12
  mimic: 13
mon_group_name: mons
osd_group_name: osds
mgr_group_name: mgrs
configure_firewall: False
ntp_daemon_type: chronyd
ceph_origin: repository
ceph_repository: community
ceph_stable_release: mimic
monitor_interface: "bond0.51"
monitor_address_block: 10.250.6.0/25
journal_size: 20480
public_network: 10.250.6.0/25
cluster_network: 10.1.9.0/27
radosgw_interface: eth2
email_address: suporte@sianet.com.br
ceph_conf_overrides:
  mon:
      mon_allow_pool_delete: true
  "client.rgw.{{ hostvars[inventory_hostname]['ansible_hostname'] }}":
      rgw enable usage log: true
      rgw usage log tick interval: 30
      rgw usage log flush threshold: 1024
      rgw usage max shards: 32
      rgw usage max user shards: 1
	  
[root@ceph-deploy ceph-ansible]# grep -o '^[^#]*' group_vars/rgws.yml
---
rgw_override_bucket_index_max_shards: 32
rgw_bucket_default_quota_max_objects: 3276800

[root@ceph-deploy ceph-ansible]#

[root@rgw01 ~]# cat /etc/ceph/ceph.conf
[client.rgw.rgw01]
host = rgw01
keyring = /var/lib/ceph/radosgw/ceph-rgw.rgw01/keyring
log file = /var/log/ceph/ceph-rgw-rgw01.log
rgw frontends = civetweb port=192.168.194.4:8080 num_threads=100

[client.rgw.rgw02]
host = rgw02
keyring = /var/lib/ceph/radosgw/ceph-rgw.rgw02/keyring
log file = /var/log/ceph/ceph-rgw-rgw02.log
rgw frontends = civetweb port=192.168.194.5:8080 num_threads=100

[client.rgw.rgw01]
rgw enable usage log = True
rgw usage log flush threshold = 1024
rgw usage log tick interval = 30
rgw usage max shards = 32
rgw usage max user shards = 1

## Please do not change this file directly since it is managed by Ansible and will be overwritten
[global]
cluster network = 10.1.9.0/27
fsid = d6fd8a81-377c-47a7-b110-db9800be79cd
mon host = 10.250.6.1,10.250.6.2,10.250.6.3
public network = 10.250.6.0/25
rgw bucket default quota max objects = 3276800
rgw override bucket index max shards = 32

[mon]
mon_allow_pool_delete = True
```

**Comment by andymcc** [comment]
What does your inventory look like, for example are your RGW hosts ONLY RGW hosts, or are they also mon hosts? And are you using containerized deployment or not?

**Comment by marcoarildo** [comment]
@andymcc - The RGW are only RGW and we do not use containers. 
follow the inventory.

[mons]
mon01
mon02
mon03

[osds]
osd01
osd02
osd03
osd04

[rgws]
rgw01
rgw02

**Comment by andymcc** [comment]
I managed to recreate it - so it does seem to be a bug in the config_template module.
If you were to specify it (e.g. "client.rgw.rgw01:") it would work - but that would then mean each host has to have a specific addition which wouldn't be ideal. Using the hostvars[inventory_hostname]['ansible_hostname'] doesn't for some reason.

I managed to recreate a simple example to rule out ceph-ansible itself:

# cat playbooks/test.yml 
---
- name: test playbook
  hosts: localhost
  connection: local
  gather_facts: true
  tasks:
    - config_template:
        src: "templates/test.file.j2"
        config_type: "ini"
        config_overrides: "{{ my_overrides }}"
        dest: "/opt/test.file"
  vars:
    my_overrides:
      "{{ ansible_hostname }}":
        d: 4
        e: 5
        a: 3


# cat playbooks/templates/test.file.j2 
#This is my test file

[{{ ansible_hostname }}]
a = 1
b = 2
c = 3

This creates the same issue.
I've filed a bug with the OpenStack-Ansible bug tracker: https://bugs.launchpad.net/openstack-ansible/+bug/1812245

**Comment by marcoarildo** [comment]
@andymcc - Thank you,  I will be waiting for the solution.
If I can cooperate with anything else let me know.
Have a nice day.

**Comment by dsavineau** [comment]
This isn't a config_template/ansible issue.
If you need to use a key in a dict with a variable then the whole dict need to be a string.

```console
$ cat templates/ceph.conf.j2 
[client.rgw.{{ ansible_hostname }}]
a = 1
b = 2
c = 3
```

```yaml
---
- hosts: localhost
  vars:
    ceph_conf_override: |
      {
        'client.rgw.{{ ansible_hostname }}': {'d': 4, 'e': 5, 'a': 3}
      }
  tasks:
    - name: ceph config
      config_template:
        src: ceph.conf.j2
        dest: ./ceph.conf
        config_type: ini
        config_overrides: '{{ ceph_conf_override }}
```

```console
$ ansible-playbook -c local -i localhost, play.yml

PLAY [localhost] *****************************************************************************************************************************************************************************************************************************

TASK [ceph config] ***************************************************************************************************************************************************************************************************************************
Friday 30 August 2019  13:45:38 -0400 (0:00:00.080)       0:00:00.080 ********* 
changed: [localhost]

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

Friday 30 August 2019  13:45:38 -0400 (0:00:00.189)       0:00:00.270 ********* 
=============================================================================== 
ceph config --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.19s
$ cat ceph.conf 
[client.rgw.blood-island]
a = 3
b = 2
c = 3
d = 4
e = 5
```
