### ISSUE TITLE
Standalone Ceph Ansible role repositories have been deleted

### ISSUE THREAD

**Issue by dmsimard** [ceph/ceph-ansible#3508]
The OpenStack-Ansible project has been relying on standalone ceph Ansible role repositories for deployments on stable releases of OpenStack (< Queens) while newer releases have been using ceph-ansible exclusively.

See: https://github.com/openstack/openstack-ansible/blob/f4c7cd442cedf723792ec4c01dd64c041129c0f8/ansible-role-requirements.yml#L181-L204

Removing these repositories all of a sudden is impacting CI jobs and deployments.

Is it possible to bring those repositories back while we work out what's the right way forward ? Thanks.

cc @leseb @guits @alfredodeza

**Comment by leseb** [comment]
Hey @dmsimard,

Sorry about that, a couple of months ago I marked these repos as deprecated in the galaxy. Last day when doing some cleaning on the Ceph org I removed these repositories.

However, everything is still present here: https://galaxy.ansible.com/ceph/ceph_ansible
You still have all the tags with the right content, so we haven't lost anything.

I believe you can recover from there.
Thanks.

**Comment by robled** [comment]
Is it still possible to install the ceph roles via the **ansible-galaxy** command?  I'm not using **mazer** since it's tech-preview only at the moment.

```
$ ansible-galaxy install ceph_common
- downloading role 'ceph_common', owned by
 [WARNING]: - ceph_common was NOT installed successfully: Content has no field named 'owner'

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

**Comment by odyssey4me** [comment]
@robled I spent some time trying to make it work today, and it doesn't. Even if you provide the git source to ansible-galaxy, it does not just clone the repo - it modifies it, so it's rendered unusable.

**Comment by robled** [comment]
mazer is a no-go for me, due to [this](https://galaxy.ansible.com/docs/mazer/index.html):

> Mazer is experimental, and currently only available for tech-preview. Use with lots of caution! It is not intended for use in production environments, nor is it currently intended to replace the ansible-galaxy command-line tool.

Restoring ansible-galaxy support would help those who would like to use ceph-ansible in production.

**Comment by odyssey4me** [comment]
@leseb I did not. We now just ``git clone`` down the combined repo and add the path of that clone to the role paths. We've been doing that for newer builds anyway, but the old galaxy roles were still being used for old (stable) environments which had not made the switch.

**Comment by seronline** [comment]
@odyssey4me Could you please elaborate what repo you are cloning (assume https://github.com/ceph/ceph-ansible) and where you are making changes to the role paths? I'm stuck with deploying OS Ocata at this particular step (other repos have also slightly changed which I managed to fix myself)

**Comment by odyssey4me** [comment]
@seronline We use [a playbook](https://github.com/openstack/openstack-ansible/blob/a46dece4fbd6691f544c42bb6d75521c05e50176/scripts/get-ansible-role-requirements.yml) to clone down the ceph-ansible repo as specified in [our ansible-role-requirements.yml file](https://github.com/openstack/openstack-ansible/blob/a46dece4fbd6691f544c42bb6d75521c05e50176/ansible-role-requirements.yml#L189-L192) and then have the [library path](https://github.com/openstack/openstack-ansible/blob/a46dece4fbd6691f544c42bb6d75521c05e50176/scripts/openstack-ansible.rc#L24), [action plugin path](https://github.com/openstack/openstack-ansible/blob/a46dece4fbd6691f544c42bb6d75521c05e50176/scripts/openstack-ansible.rc#L27), [callback plugin path](https://github.com/openstack/openstack-ansible/blob/a46dece4fbd6691f544c42bb6d75521c05e50176/scripts/openstack-ansible.rc#L28), and [role path](https://github.com/openstack/openstack-ansible/blob/a46dece4fbd6691f544c42bb6d75521c05e50176/scripts/openstack-ansible.rc#L24) set appropriately. Each of those can be set via env vars as we do, or in ``ansible.cfg`` depending on what you prefer.

**Comment by seronline** [comment]
@odyssey4me thanks for the quick and detailed response. My fear is though that OS Ansible for Ocata requires cepth version 2.2.9, as configured in my ansible-role-requirements.yml. I created a new ceph-ansible repository on my private git with version 2.2.9 which was obtained via mazer first:

```bash
~/$ mazer install ceph.ceph_ansible,2.2.9
```

The repo can be found here https://github.com/seronline/ceph-ansible

Going to go through the steps described in your comment and will report if it worked. If successful, I'll try to feed this back to the OpenStack Ansible group (given that Ocata is still stable and used by folks out there).

**Comment by odyssey4me** [comment]
@seronline [OSA implemented changes to use the new repo correctly](https://github.com/openstack/openstack-ansible/commit/d528daf069559c3686f05a26f9b4d68c84a34b77) - if you just update your checkout, then you should be able to [run a normal minor upgrade procedure](https://docs.openstack.org/openstack-ansible/ocata/upgrade-guide/minor-upgrade.html) for OSA.

**Comment by seronline** [comment]
@odyssey4me When checking out OSA 15.1.28 this fix does not exist: https://github.com/openstack/openstack-ansible/blob/15.1.28/ansible-role-requirements.yml and the Ocata documentation mentions that this particular release is required for Ocata to run. So cloning the latest and reverting (not upgrading) back to 15.1.28 doesn't quite help. Anyway, I managed to overcome the issue thanks to your help!

**Comment by odyssey4me** [comment]
@seronline Yes, it won't be in the last release because Ocata is in extended maintenance - meaning that there are no more releases. You'll have to use the SHA or just use the head of the branch. I would recommend that you [upgrade to pike](https://docs.openstack.org/openstack-ansible/pike/user/index.html) ASAP - and, in fact, upgrade through Queens to Rocky too!
