### ISSUE TITLE
RFE: set log_path to use the fact_caching_connection parent directory

### ISSUE THREAD

**Issue by pcfe** [ceph/ceph-ansible#3509]
**Is your feature request related to a problem? Please describe.**
I find it mildly annoying to change `log_path` in `ansible.cfg` every time I install a new version of ceph-ansible-*el7cp.noarch (or clone from git).

**Describe the solution you'd like**
Since `fact_caching_connection` already writes to the directory `$HOME/ansible/facts/`, it would be nice if the log path was set to
```
log_path = $HOME/ansible/ansible.log
```

The attached patch does just that (tell if you'd rather I fork and pose a MR)

[0001-write-ansible.log-to-same-dir-fact_caching_connectio.txt](https://github.com/ceph/ceph-ansible/files/2766394/0001-write-ansible.log-to-same-dir-fact_caching_connectio.txt)

**Comment by leseb** [comment]
Not everyone has an `ansible` user on their system. So setting `log_path = $HOME/ansible/ansible.log
` won't work for everyone.
However, since we already have this path for `fact_caching_connection` I guess it does not hurt to have it for the log too.

@pcfe do you mind sending a PR for this?
@guits anything to add?

**Comment by pcfe** [comment]
> > Not everyone has an ansible user on their system. So setting log_path = $HOME/ansible/ansible.log won't work for everyone.
> 
> I don't mind setting `log_path` to `$HOME/ansible/ansible.log`, but just asking, why not doing the opposite then? Like fixing `fact_caching_connection` to a path everyone has ?

`fetch_directory: ~/ceph-ansible-keys`
gets created during an ansible run, just the first attempt to log fails.

Test log
```bash
pcfe@ceph-ansible-rhel7 ~ $ pwd
/home/pcfe
pcfe@ceph-ansible-rhel7 ~ $ ls
pcfe@ceph-ansible-rhel7 ~ $ cd /usr/share/ceph-ansible/
pcfe@ceph-ansible-rhel7 ceph-ansible $ ansible -m ping all
[WARNING]: log file at /home/pcfe/ansible/ansible.log is not writeable
and we cannot create it, aborting

^C
[...]
 [ERROR]: User interrupted execution

pcfe@ceph-ansible-rhel7 ceph-ansible $ cd /home/pcfe/
pcfe@ceph-ansible-rhel7 ~ $ ls
ansible
pcfe@ceph-ansible-rhel7 ~ $ ls ansible/
facts
pcfe@ceph-ansible-rhel7 ~ $ cd /usr/share/ceph-ansible/
pcfe@ceph-ansible-rhel7 ceph-ansible $ ansible -m ping all
^C
[...]
 [ERROR]: User interrupted execution

pcfe@ceph-ansible-rhel7 ceph-ansible $ ls /home/pcfe/ansible/
ansible.log  facts
```

Since it is recommended to try to `ansible -m ping all` before running the
`site.yml` playbook, maybe that is acceptable for you.
In practise only the first `ansible` or `ansible-playbook` does not get logged, all subsequent ones can log with the suggested PR.

If not, then I can adjust the pull request to `log_path = /var/tmp/ansible.log`

pcfe
