### ISSUE TITLE
Installation of nfs-ganesha fails on Debian because of missing repositories

### ISSUE THREAD

**Issue by styleart** [ceph/ceph-ansible#3511]
I'm trying to install nfs-ganesha with ceph-ansible on Debian Stretch, but it failes because of missing repositories. 

```
fatal: [cephnode-1]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: E:The repository 'http://download.ceph.com/nfs-ganesha/deb-V2.6-stable/luminous stretch Release' does not have a Release file."}
fatal: [cephnode-2]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: E:The repository 'http://download.ceph.com/nfs-ganesha/deb-V2.6-stable/luminous stretch Release' does not have a Release file."}
fatal: [cephnode-3]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: E:The repository 'http://download.ceph.com/nfs-ganesha/deb-V2.6-stable/luminous stretch Release' does not have a Release file."}
```

The repository link (http://download.ceph.com/nfs-ganesha/deb-V2.6-stable/luminous) contains only (not signed) packages for Ubuntu Xenial.

Is there any workaround to install it on Debian?

**Environment**:
* OS: Debian GNU/Linux 9 (stretch)
* Kernel: Linux ceph1 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux
* Ansible version: ansible-playbook 2.6.0 (OSX 10.14)
* ceph-ansible version/branch: stable-3.2
* Ceph version: 12.2.10 luminous (stable)

**Comment by jeinwag** [comment]
Same issue on Ubuntu Bionic.

**Comment by styleart** [comment]
@jeinwag you probably want to deploy Nautilus? then you might be interesting in temporary solution we used to deploy our cluster: https://github.com/ceph/ceph-ansible/issues/3789#issuecomment-487315017

For older versions of Ceph (Luminous and Mimic) also refer to stable repositories: http://download.ceph.com/nfs-ganesha/deb-V2.7-stable/ It worked for me with Xenial+Luminous and Bionic+Mimic.

**Comment by dsavineau** [comment]
This issue has nothing to do with ceph-ansible.
You can open an issue on the ceph tracker about this.
