### ISSUE TITLE
RadosGW using EC pool

### ISSUE THREAD

**Issue by hoerup** [ceph/ceph-ansible#3513]
When deploying a cluster with RGW it would be nice if i could
* Define EC profile eg. in all.yaml
* in rgws.yml create a pool utilizing this profile

Btw i think that the pool creation task block in roles/ceph-rgw/tasks/main.yml should be moved to before the rgw service is started otherwise the rgw will create the necessary pools with default settings ?

**Comment by mattbenjamin** [comment]
@hoerup just to be clear, we can do this for object data, but not presently for omap--so not bucket index nor log nor data extra pools (it is now agreed that we could fix that, but the required fix is at the RADOS level)

matt

**Comment by hoerup** [comment]
Yeah of course it should only be .data pool that's set as EC

**Comment by hoerup** [comment]
In group vars group_vars/all.yml.sample it is possible to define very detailed how cephfs pools should be created.  But for in group_vars/rgws.yml it's only possible to specify the pg_num.

#cephfs_data_pool:
#  name: "{{ cephfs_data if cephfs_data is defined else 'cephfs_data' }}"
#  pg_num: "{{ osd_pool_default_pg_num }}"
#  pgp_num: "{{ osd_pool_default_pg_num }}"
#  rule_name: "replicated_rule"
#  type: 1
#  erasure_profile: ""
#  expected_num_objects: ""
#  application: "cephfs"
#  size: "{{ osd_pool_default_size }}"
#  min_size: "{{ osd_pool_default_min_size }}"
