### ISSUE TITLE
ceph-defaults does not export variables to the rest of the playbook with ansible < 2.7

### ISSUE THREAD

**Issue by badone** [ceph/ceph-ansible#3516]
**Bug Report**

What happened:
https://github.com/ceph/ceph-ansible/commit/55fab6f547db8c0604abf536b8f1f469c4cfe2ec introduced ceph-facts and appears to have exposed an issue with the difference between the older "roles:" and the newer "import_role" declaration in ansible prior to 2.7 release (info here https://github.com/ansible/ansible/issues/21890). I believe the intention is to make the variables defined in roles/ceph-defaults/defaults/main.yml available to the rest of the playbook and that is not currently happening. So I guess the crux of this is are you still supporting ansible < 2.7?

```
TASK [ceph-facts : set_fact container_binary] ***********************************************************************************************************************************************************************************************
task path: /home/ubuntu/ceph-ansible/roles/ceph-facts/tasks/facts.yml:20
Monday 21 January 2019  04:09:04 +0000 (0:00:00.182)       0:00:08.680 ******** 
fatal: [ovh020.front.sepia.ceph.com]: FAILED! => {}

MSG:

The conditional check 'containerized_deployment' failed. The error was: error while evaluating conditional (containerized_deployment): 'containerized_deployment' is undefined

The error appears to have been in '/home/ubuntu/ceph-ansible/roles/ceph-facts/tasks/facts.yml': line 20, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: set_fact container_binary
  ^ here
```

What you expected to happen:
ceph-facts tasks should complete successfully.

How to reproduce it (minimal and precise):

http://tracker.ceph.com/issues/37973

If I apply the following patch to site.yml the play gets a lot further but still fails. Early testing with ansible 2.7 also appears to fail but I need to look into that further.

```
diff --git a/site.yml.sample b/site.yml.sample
index 2ee2fe8..d47d1c4 100644
--- a/site.yml.sample
+++ b/site.yml.sample
@@ -50,9 +50,12 @@
         - ansible_distribution == 'Fedora'
         - ansible_distribution_major_version|int >= 23
 
+  roles:
+    - ceph-defaults
+
   tasks:
-    - import_role:
-        name: ceph-defaults
+    #- import_role:
+    #    name: ceph-defaults
     - import_role:
         name: ceph-facts
     - import_role:
```

**Environment**:
* OS (e.g. from /etc/os-release): CentOS
* Kernel (e.g. `uname -a`): 3.10.0-957.1.3.el7.x86_64
* Docker version if applicable (e.g. `docker version`):
* Ansible version (e.g. `ansible-playbook --version`): 2.6
* ceph-ansible version (e.g. `git head or tag or stable branch`): master head
* Ceph version (e.g. `ceph -v`): master

**Comment by guits** [comment]
@badone ceph-ansible@master must be run against ansible 2.7 only

**Comment by guits** [comment]
see http://docs.ceph.com/ceph-ansible/master/#releases
