### ISSUE TITLE
How add a new osd to existing cluster ?

### ISSUE THREAD

**Issue by caisan** [ceph/ceph-ansible#3527]
how add a new osd to existing cluster ?
 i have noticed that ceph-ansible have supplyed a playbook
for add osd(infrastructure-playbooks/add-osd.yml). but i am still
confused about two question:
       1) how can i add another OSD Server ?
       this means, if i want to add another osd server to an running
cluster, what i should add to my hosts file, and run the
ansible-playbook ?
       2) how can i add another OSD disk on an running OSD Server ?
       this means, if i want to add an osd disk upon a running osd
server , what i should add to my hosts file to specify the add disk ?
and how to run the ansible-play ?
cloud you give some example about the two question ?

**Comment by rishabh-d-dave** [comment]
> how add a new osd to existing cluster ?
> i have noticed that ceph-ansible have supplyed a playbook
> for add osd(infrastructure-playbooks/add-osd.yml). but i am still
> confused about two question:
> 1) how can i add another OSD Server ?
> this means, if i want to add another osd server to an running
> cluster, what i should add to my hosts file, and run the
> ansible-playbook ?

You can do the following:
```
$ cd ceph-ansible-repo
$ cp infrastructure-playbooks/add-osd.yml ./
$ ansible-playbook -vv -i HOSTFILE --limit HOSTNAME add-osd.yml
```

This would a new node to your Ceph cluster with an OSD running on it.

> 2) how can i add another OSD disk on an running OSD Server ?
> this means, if i want to add an osd disk upon a running osd
> server , what i should add to my hosts file to specify the add disk ?
> and how to run the ansible-play ?
> cloud you give some example about the two question ?

@leseb @guits Can you please the answer the following one? I haven't ever tried this myself.

**Comment by diandiankou** [comment]
cd /opt/ceph-ansible
cp infrastructure-playbooks/add-osd.yml ./
修改group_vars/all.yml磁盘信息
ansible-playbook -vv -i hosts --limit 192.168.203.143 add-osd.yml

添加osd节点一个磁盘和添加一个osd节点步骤一样

**Comment by aawm** [comment]
It works. I've just added 3 disks on each running OSD server in the cluster. Thanks.

**Comment by caisan** [comment]
thank you all, i will try it later.

**Comment by minkimipt** [comment]
> It works. I've just added 3 disks on each running OSD server in the cluster. Thanks.

were disks added after executing 
```
ansible-playbook -vv -i hosts  add-osd.yml?
```

**Comment by jeevadotnet** [comment]
does one need to modify anything else when using erasure profiles?

**Comment by fenggolang** [comment]
execute:
[root@harbor ceph-ansible]# ansible-playbook -vv -i /etc/ansible/hosts --limit 10.xx.xx.xx add-osd.yml 

is failed,

![image](https://user-images.githubusercontent.com/16982786/197714881-5245c5b3-8f4f-4c95-81f5-8c21732056c4.png)

**Comment by jeevadotnet** [comment]
> execute: [root@harbor ceph-ansible]# ansible-playbook -vv -i /etc/ansible/hosts --limit 10.xx.xx.xx add-osd.yml
> 
> is failed,
> 
> ![image](https://user-images.githubusercontent.com/16982786/197714881-5245c5b3-8f4f-4c95-81f5-8c21732056c4.png)

`add-osd.yml` has been removed ages ago.
