### ISSUE TITLE
Style change question

### ISSUE THREAD

**Issue by msambol** [ceph/ceph-ansible#355]
If I changed the style to

```
apt_key: data="{{ lookup('file', '../../files/cephstable.asc') }}"
         state=present
```

instead of 

```
apt_key: >
         data="{{ lookup('file', '../../files/cephstable.asc') }}"
         state=present
```

would you allow it?

**Comment by leseb** [comment]
Why would you want to do this? :)
It depends, it you do this for the entire repo or not :)
The more I look at ansbile repos the I see this kind of yaml syntax.

However I was more thinking at something like:

````
apt_key:
  data:"{{ lookup('file', '../../files/cephstable.asc') }}"
  state:present
````

**Comment by msambol** [comment]
I think that's a good compromise. :+1: 
I submit a PR later today..

**Comment by leseb** [comment]
This is a huge refactor so thanks in advance.
Have a look at this repo: https://github.com/SamYaple/yaodu/tree/master/ansible/roles
The syntax is a good example to follow.

**Comment by leseb** [comment]
@msambol Any update on this?

**Comment by msambol** [comment]
Got a little distracted with work stuff, I'll submit a PR asap.

**Comment by leseb** [comment]
No worries it's not urgent, I was just checking in while looking at the opened issues :)

**Comment by msambol** [comment]
I'm refactoring the monitor role, and it's getting stuck in `start_monitor.yml` at `collect admin and bootstrap keys`. When I run the `ceph-create-keys --id <hostname>` I get the following error: 

```
INFO:ceph-create-keys:ceph-mon admin socket not ready yet.
admin_socket: exception getting command descriptions: [Errno 2] No such file or directory
```

Have you seen this?

**Comment by leseb** [comment]
Looks like the monitor is not started thus there is not socket that can called. Check that the monitor successfully started.

**Comment by leseb** [comment]
@msambol are you planning on working on the other roles as well? Thanks!

**Comment by msambol** [comment]
Yes! It's done for `monitor`... I'll submit soon.

**Comment by leseb** [comment]
@msambol awesome, looking forward to seeing your PR.

**Comment by leseb** [comment]
@msambol thanks a lot!
