### ISSUE TITLE
Allow creation of custom EC profiles during deployment

### ISSUE THREAD

**Issue by bencherian** [ceph/ceph-ansible#3556]
**Is your feature request related to a problem? Please describe.**
I want to have custom EC profiles setup on a new Ceph cluster
**Describe the solution you'd like**
I would like to be able to setup customized EC profiles when running deployment with ceph-ansible.

**Describe alternatives you've considered**
I could do in a post deployment playbook but since we can already define "simple rules" in ceph-ansible it would make sense to define these here as well.

**Comment by mistur** [comment]
Hello,

will this feature be available in the 4.0.0 release ? Thanks.

Best regards,

Yoann
