### ISSUE TITLE
Snap package suppport 

### ISSUE THREAD

**Issue by mikeroyal** [ceph/ceph-ansible#3563]
I was thinking the install and setup could be improved for Ubuntu and other Linux distros by having a [snap package](https://snapcraft.io/) version. If it's not a priority would you mind if I made the snap as a contribution?

[Crafting your first snap](https://tutorials.ubuntu.com/tutorial/create-your-first-snap#0)

[Build and test snap](https://snapcraft.io/build)

[Getting Started snap template](https://github.com/snapcrafters/fork-and-rename-me)

**Comment by guits** [comment]
I think it's not a priority at all, indeed.

I'm not familiar with snap packages so I don't know what such a packaging would entail here.
From what I've understood in the link you provided, there's not a lot to modify/change in ceph-ansible? (unless it's pretty light, I'm unsure we want to maintain anything related to snap in ceph-ansible itself.)

I would say I don't mind if you take care of this on snap side, but again, I'm not 100% sure of the implications here.

@leseb any thought?
