### ISSUE TITLE
Containerized deployment fails and throws an error message related to keyrings even when cephx is disabled

### ISSUE THREAD

**Issue by mustafaalam958** [ceph/ceph-ansible#3587]
**Bug Report**

**What happened:** The deployment with the below error message, when cephx is disabled: 

failed: [ostor3] (item=ostor0) => {"changed": false, "item": "ostor0", "msg": "file not found: /etc/ceph/ceph-o.mgr.ostor0.keyring"}
failed: [ostor3] (item=ostor1) => {"changed": false, "item": "ostor1", "msg": "file not found: /etc/ceph/ceph-o.mgr.ostor1.keyring"}
failed: [ostor3] (item=ostor2) => {"changed": false, "item": "ostor2", "msg": "file not found: /etc/ceph/ceph-o.mgr.ostor2.keyring"}
failed: [ostor3] (item=ostor3) => {"changed": false, "item": "ostor3", "msg": "file not found: /etc/ceph/ceph-o.mgr.ostor3.keyring"}

**Issue description:** This error comes even when cephx is disabled in containerized deployment. We have tested and checked when the cephx is enabled, the deployment is successful. It is important that we disable cephx.

**Share your group_vars files, inventory**
all.yml
ceph_conf_overrides:
  global:
    auth_cluster_required: none
    auth_service_required: none
    auth_client_required: none
...
ceph_repository: rhcs
ceph_rhcs_version: 3
ceph_repository_type: cdn
...
cephx: false
...

**Environment**:
* OS: Red Hat Enterprise Linux Server release 7.6 
* Kernel: 3.10.0-862.el7.x86_64
* Docker version if applicable: Docker version 1.13.1, build 07f3374/1.13.1
* Ansible version: ansible 2.6.
* ceph-ansible version: ceph-ansible-3.2.0
* Ceph version: ceph version 12.2.8-52.el7cp 

Need help please.

**Comment by mustafaalam958** [comment]
The deployment succeeded when:

cephx: false
auth_cluster_required: none
auth_service_required: none
auth_client_required: none

Not sure why it failed with cephx=true

**Comment by guits** [comment]
@mustafaalam958 please, provide the full log, full content of group_vars/*, full inventory host, ceph-ansible version, ansible version ...

**Comment by leseb** [comment]
And open a github issue instead, that'd be easier to track.

Thanks!
–––––––––
Sébastien Han
Principal Software Engineer, Storage Architect

"Always give 100%. Unless you're giving blood."
