### ISSUE TITLE
strange error

### ISSUE THREAD

**Issue by unixman99** [ceph/ceph-ansible#3598]
I get a strange error I can't understand, i'm using a custom repository in case thats any clue?

fatal: [172.20.3.20]: FAILED! =>
  msg: |-
    The conditional check '(ceph_health_raw.stdout | default('{}') | from_json)['state'] in ['leader', 'peon']
    ' failed. The error was: No JSON object could be decoded

**Comment by guits** [comment]
@unixman99 this is definitely missing lot of information.

please, provide full playbook log, full content of group_vars/*.yml, ceph-ansible version, ansible version, inventory host file ...

**Comment by unixman99** [comment]
ansible 2.7.6

How do I find out the ceph-ansible version?
Below are the diffs of the yml files, as you'll see its pretty basic.  The RPMS are getting installed ok
Do you want the full output from:  ansible-playbook site.yml -i hosts -s -K -vvv    


hosts file:
[mons]
172.20.3.20
172.20.3.22
172.20.3.23

[mdss]
172.20.3.20
172.20.3.22
172.20.3.23

[mgrs]
172.20.3.20
172.20.3.22
172.20.3.23

[osds]
172.20.3.24
172.20.3.25
172.20.3.26





$ diff all.yml all.yml.sample
135c135
< ceph_origin: repository
---
> #ceph_origin: dummy
142c142
< ceph_repository: custom
---
> #ceph_repository: dummy
158c158
< #ceph_stable_release: mimic
---
> #ceph_stable_release: dummy
251c251
< ceph_custom_repo: http://kickstart/ceph/mimic/el7/ceph-mimic.repo
---
> #ceph_custom_repo: https://server.domain.com/ceph-custom-repo
264c264
< use_installer: true
---
> #use_installer: false
340c340
< monitor_interface: ens160
---
> #monitor_interface: interface
366,367c366,367
< public_network: 172.20.3.0/24
< cluster_network: "172.20.7.0/25"
---
> #public_network: 0.0.0.0/0
> #cluster_network: "{{ public_network | regex_replace(' ', '') }}"
371c371
< osd_objectstore: bluestore
---
> #osd_objectstore: bluestore



$ diff mgrs.yml mgrs.yml.sample
25c25
< ceph_mgr_modules: [status,dashboard]
---
> #ceph_mgr_modules: []




$ diff osds.yml osds.yml.sample
36,37c36,37
< devices:
<   - /dev/sdb
---
> #devices:
> #  - /dev/sdb
44,46d43
< dedicated_devices:
<   - /dev/sdc
<
83c80
< osd_scenario: non-collocated
---
> #osd_scenario: dummy

**Comment by unixman99** [comment]
Looks like a bug, I can get it to work with 16ccac83fe27c63be1811a44d43c8b1df417e57e

**Comment by guits** [comment]
what is the ceph-ansible version you are using ? which commit on master ?

**Comment by unixman99** [comment]
I'm using the latest one.  I even tried again just now using d4e31b90a67a76d21d98cd956fc2809b980b8126  and its the same result.

**Comment by guits** [comment]
provide the full log please

**Comment by unixman99** [comment]
[ansible.log](https://github.com/ceph/ceph-ansible/files/2870893/ansible.log)

**Comment by unixman99** [comment]
This even happens when I try using the stable-3.2 branch

**Comment by unixman99** [comment]
I attached the log

**Comment by shez1461** [comment]
Facing similar issues with Master branch. The conditional check '(ceph_health_raw.stdout | default('{}') | from_json)
I had previously used 'from simplejson' instead of '_json' and it worked before, now its not working!

**Comment by dsavineau** [comment]
```json
{"stderr": "unable to parse addrs in '[v2:172.20.3.20:3300,v1:172.20.3.20:6789],[v2:172.20.3.22:3300,v1:172.20.3.22:6789],[v2:172.20.3.23:3300,v1:172.20.3.23:6789]'\n2019-02-15 13:11:41.444 7f142b8ea700 -1 monclient: get_monmap_and_config cannot identify monitors to contact\n[errno 22] error connecting to the cluster"}
```
That means your using the master branch to deploy mimic. The monitor address v2+v1 is only available in nautilus.
To deploy mimic you need to use the stable-3.2 branch and ansible 2.6 (you're using 2.7)
