### ISSUE TITLE
handling of CephFS

### ISSUE THREAD

**Issue by joerncgm** [ceph/ceph-ansible#3606]
While learning the features of ceph-ansible w.r.t CephFS, this happened:

I had created several pools (replicated and EC) and an FS manually, but forgot to instantiate the MDSs.

So I declared two MDSs in the ceph-ansible config and executed the playbook.

This created two new pools "cephfs_data" and "cephfs_metadata", but the creation of the FS conflicted with the already present FS, as "enable_multiple" was not set.

So I tried to convince ceph-ansible to create the MDSs, but not bother to create pools and the default FS:

cephfs:
cephfs_data:
cephfs_metadata:

This didn't work as expected. The playbook was executed, but with some errors.

So I thought: What the heck, let ceph-ansible do the job, and I added my current configuration to the playbook:

cephfs: data
cephfs_data: file2_data
cephfs_metadata: file_metadata

This didn't work either, because file2_data is an EC pool, and ansible reported

Error EINVAL: pool 'file2_data' cannot change to type replicated

So I thought: Okay, let's do not make things more complicated then necessary, and use a replicated pool:

cephfs: data
cephfs_data: file1_data
cephfs_metadata: file_metadata

N.B.: I did not remove "data" or the pools manually, I wanted to see how ceph-ansible would handle this situation.

Now the playbook was executed without any errors, but the FS still used the EC pool:

$ ceph fs ls
name: data, metadata pool: file_metadata, data pools: [file2_data ]

I think ceph-ansible should handle the first few situations more gracefully (i.e. allow the user to instantiate MDSs, but skip the creation of pools and FS), but bail on the last situation, where the resulting configuration differs from the desired one.

**Comment by dsavineau** [comment]
> I think ceph-ansible should handle the first few situations more gracefully (i.e. allow the user to instantiate MDSs, but skip the creation of pools and FS)

@joerncgm did you try to set the cephfs_pools to an empty list to avoid ceph-ansible to create/customize le pools ?

```yaml
cephfs_pools: []
```

**Comment by joerncgm** [comment]
Am 08.03.2019 um 15:58 schrieb Dimitri Savineau:
> @joerncgm <https://github.com/joerncgm> did you try to set the 
> cephfs_pools to an empty list to avoid ceph-ansible to create/customize 
> le pools ?
> 
> cephfs_pools:[]

No, I didn't. I'll try to check this and report back.

-- 
Jörn Clausen
Daten- und Rechenzentrum
GEOMAR Helmholtz-Zentrum für Ozeanforschung Kiel
Düsternbrookerweg 20
24105 Kiel

**Comment by joerncgm** [comment]
Hi!

Am 08.03.2019 um 15:58 schrieb Dimitri Savineau:
> @joerncgm <https://github.com/joerncgm> did you try to set the 
> cephfs_pools to an empty list to avoid ceph-ansible to create/customize 
> le pools ?
> 
> cephfs_pools:[]

I finally managed to test this. I did a complete redeploy of my test 
cluster, using ceph-ansible stable-4.0, target was Nautilus on CentOS 7.

If I define only

cephfs_pools: []

I get

fatal: [cephtmds01 -> 172.17.0.35]: FAILED! => changed=false
   cmd:
   - ceph
   - --cluster
   - ceph
   - fs
   - new
   - cephfs
   - cephfs_metadata
   - cephfs_data
   delta: '0:00:01.317320'
   end: '2019-04-03 10:12:08.074707'
   msg: non-zero return code
   rc: 2
   start: '2019-04-03 10:12:06.757387'
   stderr: 'Error ENOENT: pool ''cephfs_metadata'' does not exist'
   stderr_lines:
   - 'Error ENOENT: pool ''cephfs_metadata'' does not exist'
   stdout: ''
   stdout_lines: <omitted>


If in addition I define again

cephfs:
cephfs_data:
cephfs_metadata:

I get

fatal: [cephtmds01 -> 172.17.0.35]: FAILED! => changed=false
   cmd:
   - ceph
   - --cluster
   - ceph
   - fs
   - new
   delta: '0:00:01.401159'
   end: '2019-04-03 10:32:27.556945'
   msg: non-zero return code
   rc: 22
   start: '2019-04-03 10:32:26.155786'
   stderr: |-
     Invalid command: missing required parameter fs_name(<string>)
     fs new <fs_name> <metadata> <data> {--force} 
{--allow-dangerous-metadata-overlay} :  make new filesystem using named 
pools <metadata> and <data>
     Error EINVAL: invalid command
   stderr_lines:
   - 'Invalid command: missing required parameter fs_name(<string>)'
   - 'fs new <fs_name> <metadata> <data> {--force} 
{--allow-dangerous-metadata-overlay} :  make new filesystem using named 
pools <metadata> and <data>'
   - 'Error EINVAL: invalid command'
   stdout: ''
   stdout_lines: <omitted>


-- 
Jörn Clausen
Daten- und Rechenzentrum
GEOMAR Helmholtz-Zentrum für Ozeanforschung Kiel
Düsternbrookerweg 20
24105 Kiel

**Comment by guits** [comment]
at first glance, what you report here looks like a valid bug to me

**Comment by guits** [comment]
@rishabh-d-dave when you have some free times, do you mind sending a PR for this? Thanks!

**Comment by rishabh-d-dave** [comment]
Sure. I'll take a look into this. For time being, I'll assign it to myself so that I can keep a track of this.
