### ISSUE TITLE
docker cpu and memory limits need to be expressed differently

### ISSUE THREAD

**Issue by bengland2** [ceph/ceph-ansible#3617]
This concerns Ceph Luminous and any releases past that. 

memory limits:

Shouldn't container CGroup memory limit (i.e. the docker run --memory=) be eliminated from ceph-ansible?  The software itself has to decide not to use more than a certain amount of memory - using a memory CGroup limit is just a recipe for causing daemon crashes due to memory allocation failures.  osd_memory_limit param in ceph.conf is how it should be done.  The existing --memory= values for OSDs are not significant because it sets the CGroup limit to all of physical memory.

cpu limits:

Unlike memory, CPU CGroup limits are useful, particularly for hyperconverged configurations.  But in this [docker doc page](https://docs.docker.com/config/containers/resource_constraints/), it says not to use --cpu-quota option anymore: "If you use Docker 1.13 or higher, use --cpus instead."   This would replace the current --cpu-quota setting in[ ceph-osd-run.sh.j2 template](https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-osd/templates/ceph-osd-run.sh.j2), for example.     This makes it harder for people to see what CPU limits are at present.  It's tough enough to get the CPU limits set correctly for all Ceph containers as it is, and it can make Ceph really look bad (particularly for all-NVM configurations) if the default of 1 core is used.

comments?

**Comment by devster31** [comment]
Regarding the CPU limits `master` already has
https://github.com/ceph/ceph-ansible/blob/d2591b8b40b3f8927b2a827b1067f40d28a86528/roles/ceph-osd/templates/ceph-osd-run.sh.j2#L79-L83
which is in line with what you're suggesting. Checks for `docker` version and uses `--cpu` or `--cpu-quota` as appropriate.
I believe with newer versions of `ansible` the conditional could be written as:
```
  {% if (container_binary == 'docker' and ceph_docker_version is version('1.13', '>=')) or container_binary == 'podman' -%}
```
but it's a minor thing.
Can't comment on the memory.

**Comment by bengland2** [comment]
@devster Thanks, that takes care of the CPU piece.

**Comment by leseb** [comment]
`osd_memory_target` is only used by Bluestore. I think it makes to drop `--memory` for Bluestore OSDs that support `osd_memory_target`.

Makes sense?

**Comment by bengland2** [comment]
@leseb, Filestore OSDs don't do process-local caching so they shouldn't be growing that big anyway.  To control the amount of (unrecoverable) kernel RAM they use, use a low vm.dirty*ratio value (example: vm.dirty_ratio=10 vm.dirty_background_ratio=3).  To reduce memory allocation latency, vm.min_free_kbytes >= 0.5% RAM .  And over time, Filestore OSDs should go away.

if you set the CGroup memory limit to all of physical memory, which is what ceph-ansible does by default in RHCS 3.2, then you would probably get a system-wide OOM kill before the CGroup limit (RSS) was ever reached.   Sure, today you can set it lower than that using ceph_*_docker_memory_limit, but how do people know what should be, and that it will cause their daemon to crash if it's too low?   I think they don't know, and if they try to set it they will cause worse problems.  

What about RGW, ceph-mgr,   MDS,   iSCSI gateway?   we want to fix this problem for all of them to support hyperconverged storage.  MDS now has mds_cache_memory_limit parameter BTW.

suggestion:  Where a ceph daemon has a ceph.conf memory limit parameter defined, then we remove the corresponding CGroup memory limit parameter.  So for MDS and OSDs, we can remove it today.  For each remaining daemon, leave the CGroup limit  as it is until they too have ceph.conf memory limits.

**Comment by leseb** [comment]
@bengland2 sounds good thanks. For the other daemons like mgr and rgw I have no idea.

@dsavineau can you please drop the `--memory` flag on the OSD when using bluestore?
@ajarr please look at the MDS things and add support for `mds_cache_memory_limit`.

**Comment by bengland2** [comment]
@ajarr, mds_cache_memory_limit is already supported in ceph_conf_overrides, as is osd_memory_target.  @leseb I don't know of any such parameter for RGW so far, Perf & Scale will investigate

**Comment by leseb** [comment]
@bengland2 thanks for the update.

**Comment by bengland2** [comment]
RGW uses so little memory that we can ignore it, John Harrigan says 1 GB/RGW, closing this issue.
