### ISSUE TITLE
mon_host_v2_suffix is undefined

### ISSUE THREAD

**Issue by zoltan** [ceph/ceph-ansible#3618]
**Bug Report**

What happened:
While running site.yml I've run into an issue that has the same error as #3525, however, I'm not using tox, but actually running the playbook.

What you expected to happen:
Get a deployed ceph cluster.

How to reproduce it (minimal and precise):
I'm running ansible-playbook site.yml -vvvv -i inventory -u root, and get the error:

Share your group_vars files, inventory
the inventory file:
[mons]
s19

[mgrs]
s19

[osds]
s19

group_vars/all.yml:
---
dummy:
ceph_origin: repository
ceph_repository: community
ceph_stable_release: mimic
monitor_interface: enp139s0f0

group_vars/osds.yml:
---
dummy:
osd_scenario: lvm
lvm_volumes:
    - data: /dev/nvme0n1
osds_per_device: 1

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 18.04.2
* Kernel (e.g. `uname -a`): 4.18.0-15-generic
* Docker version if applicable (e.g. `docker version`): not using docker.
* Ansible version (e.g. `ansible-playbook --version`): 2.7.7
* ceph-ansible version (e.g. `git head or tag or stable branch`): master
* Ceph version (e.g. `ceph -v`): 13.2.4

**Comment by devster31** [comment]
It seems `master` has the following:
https://github.com/ceph/ceph-ansible/blob/82897c76fb7be987f04843ac65a9546c0f8c622f/roles/ceph-config/templates/ceph.conf.j2#L42-L50
which requires both variables defined.
Try commenting L42 and 45, or switch to `stable-3.2` for the time being.

**Comment by leseb** [comment]
This is expected, as @devster31 said you can't use master to deploy Mimic, please use stable-3.2 instead.

**Comment by totonho-apocalipse** [comment]
Hi,
I am trying to use the the ansible-ceph as well t it still show that error to me 

------------------------
TASK [ceph-config : generate ceph configuration file: ceph.conf] ******************************************************************************************
Sunday 10 March 2019  09:06:20 -0600 (0:00:00.239)       0:00:43.055 ********** 
fatal: [ceph2]: FAILED! => 
  msg: '''mon_host_v2_suffix'' is undefined'
--------------------------

Does not matter if if I state kraken, lumminous or mimic...

Here is the all.yml from the group vars
---
dummy:
ceph_origin: repository
ceph_repository: community
ceph_stable: true
ceph_mirror: http://download.ceph.com
ceph_stable_key: https://download.ceph.com/keys/release.asc
ceph_stable_release: mimic
ceph_stable_repo: https://download.ceph.com/rpm-mimic/el7/x86_64
ceph_stable_redhat_distro: el7
cephx: true
monitor_interface: eth0
monitor_address: 192.168.10.134
ip_version: ipv4
public_network: 192.168.10.134/24

** I followed the suggestion to coment line 42/45 in the clone I took  --- no deal.

**Comment by guits** [comment]
@totonho-apocalipse as already explained in that same issue.
**DO NOT** use ceph-ansible@**master** to deploy **mimic**.

**Comment by badone** [comment]
But Nautilus has not branched yet so ceph master *is* mimic?

**Comment by badone** [comment]
@guits What should ceph_stable_release be set to when testing the current HEAD of the ceph master branch?

**Comment by badone** [comment]
Or ceph_release

**Comment by guits** [comment]
@badone use `ceph_repository: dev`

**Comment by badone** [comment]
@guits Yes, I see now. Thanks.

**Comment by barbudone** [comment]
Confirm, this still persist. 
ceph_repository: community/dev not solve the issue. nor master/luminous:/mimic.
That task work only when the section with the mon_host_v2_suffix are {# commented. #}

**Comment by guits** [comment]
@barbudone share more details, you must have something wrong in your setup.

**Comment by yuezhuangshi** [comment]
use stable-3.2 to deploy mimic solved my issue, but ansible version must be between **2.4.x-2.6.x**

**Comment by guits** [comment]
@yuezhuangshi that's the expected behavior, indeed.

Everything is documented [here](http://docs.ceph.com/ceph-ansible/master/#releases)

so please, let's stop raising same "issue" again and again, just use the correct stack according to what you want to deploy.
