### ISSUE TITLE
Discrepancy in rados gateway keyring name

### ISSUE THREAD

**Issue by Abhishekvrshny** [ceph/ceph-ansible#362]
ceph-ansible creates the rados gateway keyring with the notation - client.rgw.{{ ansible_hostname  }}

--------------------------------------------------------------------------------
## roles/ceph-radosgw/tasks/pre_requisite.yml

- name: create rados gateway keyring

  command: >

    ceph --cluster ceph --name client.bootstrap-rgw --keyring /var/lib/ceph/bootstrap-rgw/ceph.keyring auth get-or-create client.rgw.{{ ansible_hostname }} osd 'allow rwx' mon      'allow rw' -o /var/lib/ceph/radosgw/ceph-rgw.{{ ansible_hostname }}/keyring

    creates=/var/lib/ceph/radosgw/ceph-rgw.{{ ansible_hostname }}/keyring

  changed_when: false

  when: cephx

--------------------------------------------------------------------------------------

On the other hand, radosgw expects the name to to client.radosgw

--------------------------------------------------------------------------------------
## /etc/init.d/radosgw

PREFIX='client.radosgw.'

-------------------------------------------------------------------------------------

Also, ceph command doesnt accept the key name to be client.radosgw. 

I am not sure if this is an issue with ceph-ansible or with radosgw.

**Comment by leseb** [comment]
Unfortunately it's a well known issue and will soon get fixed.
The fact that ceph-ansible uses client.rgw is because Ceph's monitors don't accept anything else than client.rgw. This is why client.radosgw would fail if you use the bootstrap key.

ceph-ansible does the right thing, you might have to modify the init script, but I somehow made it working without having to modify the radosgw init script.
Which distro are you running on?

**Comment by Abhishek-FK** [comment]
I am using ceph version 0.94.2 (5fb85614ca8f354284c713a2f9c610860720bbf3) on Debian wheezy 7.8
I had to modify the radosgw init script to get it working. How did you do that without modifying the init script?
If I use the ceph auth add command with input as as a file, it works fine even with client.radosgw. Is this a bug with ceph then?

**Comment by leseb** [comment]
The limitation doesn't come from the key itself but from its creation using a bootstrap key. If you use the admin key to create a client.radosgw then later you can use that key.
Let me see if I can find this back, I know I have it working on RHEL7.

**Comment by leseb** [comment]
Do you use systemd to run your daemons?

**Comment by Abhishek-FK** [comment]
radosgw init script uses start-stop-daemon I guess. Here is the version that I have https://github.com/ceph/ceph/blob/v0.94.2/src/init-radosgw

**Comment by leseb** [comment]
well it detects systemd it falls back to it. Otherwise yes, start-stop-daemon.

**Comment by aeroevan** [comment]
@leseb how did you manage to get it working without modifying the sysvinit script?

I got it working with a sed -i command task, but that's kinda hacky

**Comment by leseb** [comment]
@aeroevan sorry I think I've never really fixed that on Debian (works on RHEL and Ubuntu).
In the meantime, sed's magic is probably the best we can do...
