### ISSUE TITLE
Multiple NTP support does not support RHEL/CentOS 7 daemons properly

### ISSUE THREAD

**Issue by yoctozepto** [ceph/ceph-ansible#3628]
**Bug Report**

In RHEL/CentOS 7 systemd-timesyncd is not used (not even available), chronyd is the default NTP daemon and timedatectl actually controls the currently installed NTP daemon, hence there is a logic fail when running current tasks for NTP, see: ceph-infra/tasks/setup_ntp.yml which does e.g. `timedatectl set-ntp no`. I suggest it only manipulates the service itself and not uses this call, the handlers are already there for that.
Otherwise there are, for example, the 2 following scenarios:
1) the default is used (`timesyncd`) which "turns timesyncd on" (false assumption, it actually turns on chronyd by default) and then disables chronyd (so no NTP finally) - bad bad
2) the `chronyd` is used which makes ansible do disable/enable for it actually instead of just idempotently skipping it if it is already running - not that bad but still ugly

How to reproduce it (minimal and precise):
Run ceph-ansible (even with default settings) against RHEL/CentOS 7 (at minimum apply the ceph-infra role which controls NTP).

**Environment**:
* OS (e.g. from /etc/os-release): CentOS 7.6
* ceph-ansible version (e.g. `git head or tag or stable branch`): stable-3.2

**Comment by guits** [comment]
@rishabh-d-dave do you have a status for this? Thanks!

**Comment by guits** [comment]
valid and reproduced issue, need a fix asap
