### ISSUE TITLE
mistake in rbd.in causes it to fail

### ISSUE THREAD

**Issue by unixman99** [ceph/ceph-ansible#3629]
I see this file:  https://github.com/ceph/ceph/commits/6a57358add1157629a6d1f72ae48777e134c99e6/src/ocf/rbd.in

commit 6a57358add1157629a6d1f72ae48777e134c99e6

Has the latest commit from over a year ago appears to have a problem, for example the command changes in the diff don't even work.  See for an example:  https://lists.clusterlabs.org/pipermail/users/2019-February/016292.html

**Comment by dsavineau** [comment]
@unixman99 I think you wanted to open this issue against ceph/ceph and not ceph/ceph-ansible right ?
