### ISSUE TITLE
Permission problem with bluestore+lvm 

### ISSUE THREAD

**Issue by kaptenkrille** [ceph/ceph-ansible#3702]
**Bug Report**

What happened:
First of, I'm not sure if this is a problem with ceph-ansible or CentOS udev rules, but I put it here for now. I've setup a 7 host cluster with 84 osds. OSD's are LVM and bluestore with RocksDB and WAL on separate LVM volumne group. I created the volume group and the logical volumnes for DB and WAL myself. I ran the playbook and cluster worked as it should. But, after reboot of one host showed that DB and WAL's permissions was not set correct. I solved it by running: 

cd /dev
chown -R ceph:ceph ceph-db
cd ceph-db
for i in $(ls -la | awk '{print $11}') ; do chown ceph:ceph $i; done
ceph-volume lvm activate --all
reboot

After that the permissions stays correct after reboot and all works. 

What you expected to happen:
Permissions of disks to be correct. 

How to reproduce it (minimal and precise):

I created the volume group ceph-lvm and the logical volumnes for DB and WAL myself and than ran site.yml.

Share your group_vars files, inventory
osd_objectstore: bluestore
osd_scenario: lvm
lvm_volumes:
  - data: /dev/sdc
    db: db-sdc
    db_vg: ceph-lvm
    wal: wal-sdc
    wal_vg: ceph-lvm
  - data: /dev/sdd
    db: db-sdd  
    db_vg: ceph-lvm
    wal: wal-sdd
    wal_vg: ceph-lvm

**Environment**:
* OS (e.g. from /etc/os-release): CentOS Linux release 7.6.1810 (Core)
* Kernel (e.g. `uname -a`): Linux 3.10.0-957.5.1.el7.x86_64
* Ansible version (e.g. `ansible-playbook --version`): 2.6.14
* ceph-ansible version (e.g. `git head or tag or stable branch`): stable-3.2
* Ceph version (e.g. `ceph -v`): ceph version 13.2.4 (b10be4d44915a4d78a8e06aa31919e74927b142e) mimic (stable)

**Comment by dsavineau** [comment]
With a similar setup (centos 7.6, ansible 2.6, ceph mimic 13.2.4 and ceph-ansible stable 3.2), the owner/group are set correctly during the create and (re)boot process.

```console
# ls -hl /dev/ceph_bluestore/*
lrwxrwxrwx. 1 ceph ceph 7 Mar 11 18:14 /dev/ceph_bluestore/sdc_db -> ../dm-0
lrwxrwxrwx. 1 ceph ceph 7 Mar 11 18:14 /dev/ceph_bluestore/sdc_wal -> ../dm-1
lrwxrwxrwx. 1 ceph ceph 7 Mar 11 18:15 /dev/ceph_bluestore/sdd_db -> ../dm-2
lrwxrwxrwx. 1 ceph ceph 7 Mar 11 18:15 /dev/ceph_bluestore/sdd_wal -> ../dm-3
# ls -hl /dev/dm-*
brw-rw----. 1 ceph ceph 253, 0 Mar 11 18:14 /dev/dm-0
brw-rw----. 1 ceph ceph 253, 1 Mar 11 18:15 /dev/dm-1
brw-rw----. 1 ceph ceph 253, 2 Mar 11 18:15 /dev/dm-2
brw-rw----. 1 ceph ceph 253, 3 Mar 11 18:15 /dev/dm-3
brw-rw----. 1 ceph ceph 253, 4 Mar 11 18:14 /dev/dm-4
brw-rw----. 1 ceph ceph 253, 5 Mar 11 18:15 /dev/dm-5
```

This part is done via ceph-volume at [creation time](https://github.com/ceph/ceph/blob/v13.2.4/src/ceph-volume/ceph_volume/devices/lvm/activate.py#L165-L180) via system.chown function.

After a reboot of the host, you should have systemd trying to start/activate the OSD.
```console
Mar 11 18:37:32 osd0 systemd[1]: Starting Ceph object storage daemon osd.0...
Mar 11 18:37:32 osd0 systemd[1]: Starting Ceph object storage daemon osd.1...
Mar 11 18:37:32 osd0 systemd[1]: Started Ceph object storage daemon osd.0.
Mar 11 18:37:32 osd0 systemd[1]: Started Ceph object storage daemon osd.1.
Mar 11 18:37:32 osd0 sh[2795]: Running command: /usr/sbin/ceph-volume lvm trigger 0-6d179476-c018-4f55-8916-56d3dd9facdb
Mar 11 18:37:32 osd0 systemd[1]: Started Ceph Volume activation: lvm-0-6d179476-c018-4f55-8916-56d3dd9facdb.
Mar 11 18:37:32 osd0 sh[2792]: Running command: /usr/sbin/ceph-volume lvm trigger 1-7984d8de-8628-48b1-aa83-077f727b1f40
Mar 11 18:37:32 osd0 systemd[1]: Started Ceph Volume activation: lvm-1-7984d8de-8628-48b1-aa83-077f727b1f40.
```
OSD daemons are triggered by ceph-osd@.service systemd unit but there's also [ceph-volume@](https://github.com/ceph/ceph/blob/v13.2.4/systemd/ceph-volume%40.service) that should be executed and will rerun the ceph-volume lvm activate part via the [trigger code](https://github.com/ceph/ceph/blob/v13.2.4/src/ceph-volume/ceph_volume/devices/lvm/trigger.py#L70)


You should have some logs in /var/log/ceph/ceph-volume.log and /var/log/ceph/ceph-volume-systemd.log

**Comment by kaptenkrille** [comment]
Thanks for response. I see in /var/log/ceph/ceph-volume.log that it did the "chown". I guess this is not something system related and I will see if I can find out why it happend.
