### ISSUE TITLE
Error: "[ceph-mon : collect admin and bootstrap keys]"

### ISSUE THREAD

**Issue by TimMacho** [ceph/ceph-ansible#3709]
**Bug Report**

Hey, i am trying to install ceph (mimic) by using ceph-ansible. 
Cent Os 7
stable-branch: 3.2
ansible: 2.6.9 (downgrade)
python: 2.7.5
1 Admin and 3 Nodes

I want to have 3 Mons and 3 Osd per Node.

But when i play "ansible-playbook site.yml" i become a error by [ceph-mon : collect admin and bootstrap keys]

It says: fatal: [node1]: FAILED! => {"changed": false, "cmd": ["ceph-create-keys", "--cluster", "ceph", "-i", "node2", "-t", "30"], 
"delta": "0:00:33.470949", "end": "2019-03-13 08:28:21.090144", "msg": "non-zero return code", "rc": 1, "start": "2019-03-13 08:27:47.619195", 
"stderr": "admin_socket: exception getting command descriptions: [Errno 2]
 No such file or directory\nINFO:ceph-create-keys:ceph-mon admin socket not ready yet.\nadmin_socket: exception getting command descriptions: [Errno 2]

The last sentence wirte it very often and this by every node. 

The Play Recap is:
PLAY RECAP *********************************************************************
node1                      : ok=86   changed=17   unreachable=0    failed=1
node2                      : ok=78   changed=14   unreachable=0    failed=1
node3                      : ok=78   changed=13   unreachable=0    failed=1

I use the yml: all, osd
[all.txt](https://github.com/ceph/ceph-ansible/files/2960398/all.txt)
[osd.txt](https://github.com/ceph/ceph-ansible/files/2960406/osd.txt)

In the "/etc/ceph/" they are only two files inside: ceph.conf, rbdmap
But not a "admin.secret" file.

What is the actually problem, how can i solve this? Any Ideas?

**Comment by dsavineau** [comment]
Please provide full ansible.log and inventory file.

Looking quickly I don't see mons.yml file so you don't set a value for admin_secret et mgr_secret.

**Comment by TimMacho** [comment]
@dsavineau than u for your answer, i solved this problem by myself.

**Comment by guits** [comment]
@TimMacho just curious, what did you do to solve it? (could be usefull if someone has the same issue)

**Comment by TimMacho** [comment]
@guits i had somewhere in the all.yml or in the osd.yml a failure.

**Comment by chadcao** [comment]
Ｉhad the same issue and I could not find the root cause.
@TimMacho do you still remember how did you fix the issue?

**Comment by lmpeiris** [comment]
ceph: luminous
ceph-ansible: 3.2.53
OS: centos 7.9

In my case, i had manually created the ceph user before. However the ceph-ansible was expecting ceph user to be uid:gid 167:167, and hence ceph mon did not have permission to start the socket in the folder which the installer created, giving below error:

2020-12-12 09:11:39.597178 7f4a27da8000 -1 asok(0x5632ea7f01c0) AdminSocketConfigObs::init: failed: AdminSocket::bind_and_listen: failed to bind the UNIX domain socket to '/var/run/ceph/ceph-mon.cephserverc.asok': (13) Permission denied

I stopped the ceph mons, and relabeled ceph's uid/gid to 167 and ran the ceph-ansible again. This time it was success.
