### ISSUE TITLE
Rolling Update Playbook broken

### ISSUE THREAD

**Issue by discostur** [ceph/ceph-ansible#3712]
Hi,

i'm trying to upgrade my ceph mimic cluster via ceph-ansible but i get the following error:

```
ansible-playbook -i ../hosts infrastructure-playbooks/rolling_update.yml 
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/root/ansible-playbooks/ceph-ansible/roles/ceph-config/tasks/main.yml': line 30, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


    - name: run 'ceph-volume lvm batch --report' to see how many osds are to be created
      ^ here
``` 

I'm on the latest 3.2 stable branch:
```
git status
# Auf Zweig stable-3.2
```

**Comment by dsavineau** [comment]
@discostur ceph custom modules (ceph_volume, ceph_key, etc...) are referenced via the ansible.cfg file in the main ceph-ansible directory.
If you try to run playbooks from the infrastructure-playbooks directory then it will fails.
You need to copy the playbook in the main directory.

https://github.com/ceph/ceph-ansible/blob/master/infrastructure-playbooks/README.md

**Comment by JoshuaLyle** [comment]
Encountered this as well in `stable-3.1` running ansible 2.4.0. Doesn't occur in `stable-3.2` running ansible 2.6.3
