### ISSUE TITLE
Failed at TASK [ceph-mon : push ceph files to the ansible server]

### ISSUE THREAD

**Issue by gregoryo2014** [ceph/ceph-ansible#3715]
**Bug Report**

What happened:
Previously I built a one node containerised cluster with minimal customisation, and no trouble. I then added a mgrs group to the host file, and that worked too.
Rebuilding it from scratch, it fails trying to fetch non-existent bootstrap keys.

What you expected to happen:
Fresh cluster with container mons and osds

How to reproduce it (minimal and precise):
cp site-docker.yml.sample docker.yml
time ansible-playbook docker.yml

Share your group_vars files, inventory
group_vars/all.yml:
```
monitor_interface: br_strstorage
docker: true
containerized_deployment: true
```
group_vars/osds.yml:
```
osd_scenario: lvm
lvm_volumes:
  - data: /dev/sdc
    db: /dev/sda1
  - data...
```
[ansible.log](https://github.com/ceph/ceph-ansible/files/2969647/ansible.log)

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 18.04.2 LTS
* Kernel (e.g. `uname -a`): 4.15.0-46-generic
* Docker version if applicable (e.g. `docker version`): 18.09.2
* Ansible version (e.g. `ansible-playbook --version`): 2.6.14
* ceph-ansible version (e.g. `git head or tag or stable branch`): 3.2-stable
* Ceph version (e.g. `ceph -v`): 14.1.1

**Comment by gregoryo2014** [comment]
Same behaviour when wipe it and put `ceph_stable_release: mimic` in all.yml before rebuild. ... except it still appears to be nautilus:
```
sudo docker exec ceph-mon-stratus-r6-5139 ceph -v
ceph version 14.1.1 (ae1b3cf8e2e29118c0682f0895e3f48a79895cbc) nautilus (rc)
```

**Comment by dsavineau** [comment]
> * ceph-ansible version (e.g. `git head or tag or stable branch`): 3.2-stable
> * Ceph version (e.g. `ceph -v`): 14.1.1

stable-3.2 branch is used to deploy luminous or mimic but not nautilus. You should use master instead.
In containerized deployment ceph_stable_release variable has no effect because we're not installing any ceph packages on the system just running containers.

Could you provide your ceph_docker_* variables ?

**Comment by gregoryo2014** [comment]
Yes, I remember reading that, and I want mimic. Can you tell me what I'm doing wrong that I'm getting nautilus?

I don't have any ceph_docker_* variables, or any others - I literally do:
```
$ cd /tmp
$ git clone -b stable-3.2 https://github.com/ceph/ceph-ansible.git
$ cd ceph-ansible
$ pip install -r requirements.txt
$ cp site-docker.yml.sample docker.yml
```
... then
* set up /etc/ansible/hosts with the hostname in [mons] and [osds]
* configure group_vars/{all,osds}.yml and run, as above

**Comment by dsavineau** [comment]
https://github.com/ceph/ceph-ansible/blob/stable-3.2/roles/ceph-defaults/defaults/main.yml#L535-L537

Using tag latest was at some point referring to mimic but now it's pointing to nautilus.

```console
$ docker run --rm --entrypoint ceph docker.io/ceph/daemon:latest --version
ceph version 14.1.1 (ae1b3cf8e2e29118c0682f0895e3f48a79895cbc) nautilus (rc)
```

You'll need to change this in your group_vars/all.yml
```yaml
ceph_docker_image_tag: latest-mimic
```

```console
$ docker run --rm --entrypoint ceph docker.io/ceph/daemon:latest-mimic --version
ceph version 13.2.5 (cbff874f9007f1869bfd3821b7e33b2a6ffd4988) mimic (stable)
```

**Comment by gregoryo2014** [comment]
Right, that's sorted out the bootstrap keys, thank you. I had to
```
$ sudo docker rm -f `sudo docker ps -q`
$ sudo docker image rm ceph/daemon:latest
```
otherwise it recreated with `latest` instead of `latest-mimic`. The problem is fix now (more popped up, but I'll handle them separately), thank you!
