### ISSUE TITLE
wait for client.admin key exists hangs in Debian

### ISSUE THREAD

**Issue by Abhishekvrshny** [ceph/ceph-ansible#372]
./roles/ceph-mon/tasks/ceph_keys.yml hangs in Debian.

----------------------------------------

- name: wait for client.admin key exists

  wait_for: path=/etc/ceph/ceph.client.admin.keyring

----------------------------------------

I have sent a PR for this. https://github.com/Abhishekvrshny/ceph-ansible/pull/1

**Comment by leseb** [comment]
can you send your PR or ceph-ansible and not on your fork? :)

**Comment by leseb** [comment]
Closed by #380
