### ISSUE TITLE
ceph mds stat  goes to creating always

### ISSUE THREAD

**Issue by selvakumars3** [ceph/ceph-ansible#3721]
Hi.
I have used ceph jewel release for deployment.
I tried to create ceph filesystem.

 ceph fs ls
name: cephfs, metadata pool: cephfs_metadata, data pools: [cephfs_data ]
However ceph mds stat goes to "creating " state and it never comes to active state.
[root@cephserver3 ceph]# ceph mds stat
cephfs-1/1/1 up  {0=cephserver3=up:creating}

[root@cephserver3 ceph]# ceph -s
  cluster:
    id:     35b0fc67-17f4-4643-852d-f0d194737e52
    health: HEALTH_WARN
            1 MDSs report slow metadata IOs
            Reduced data availability: 64 pgs inactive
            Degraded data redundancy: 64 pgs undersized

  services:
    mon: 1 daemons, quorum cephserver3
    mgr: cephserver3(active)
    mds: cephfs-1/1/1 up  {0=cephserver3=up:creating}
    osd: 3 osds: 1 up, 1 in

  data:
    pools:   2 pools, 64 pgs
    objects: 0  objects, 0 B
    usage:   1.0 GiB used, 1.5 TiB / 1.5 TiB avail
    pgs:     100.000% pgs not active
             64 undersized+peered
Request your help to resolve this

**Comment by selvakumars3** [comment]
sorry it is mimic version

**Comment by dsavineau** [comment]
Please provide full ansible.log file, inventory and group_vars/*
Also be sure that your cluster is healthy because I can see 1/3 OSDs up and all pgs aren't active.

**Comment by almahaja** [comment]
We are getting this issue, so checking if there's any resolution for this?
