### ISSUE TITLE
Error :  'ansible_lsb' is undefined

### ISSUE THREAD

**Issue by Abhishekvrshny** [ceph/ceph-ansible#373]
I git this error everytime I run ansible first time for a host. It disappears in the subsequent run though.

TASK: [ceph-common | add ceph stable repository] ******************************
fatal: [10.33.85.62] => One or more undefined variables: 'ansible_lsb' is undefined

FATAL: all hosts have already failed -- aborting

**Comment by leseb** [comment]
Hum I've never seen this issue before.
Which version of Ansible do you use?

**Comment by Abhishekvrshny** [comment]
@leseb . I am using ansible 1.7.2.

**Comment by leseb** [comment]
@Abhishekvrshny by any chance can you try to upgrade to something like 1.9?

**Comment by leseb** [comment]
Any updates on this?

**Comment by Abhishekvrshny** [comment]
@leseb . I am working on debian wheezy and it's ansible v1.7.2 that comes with the official repositories of debian wheezy (in wheezy-backports) and even with the later debian jessie. I was thinking of building ansible v1.9.2 for wheezy and then testing it out. Haven't been able to find time for that. IIRC, I did try ceph-ansible with ansible v1.9.2 once and it was fine.

**Comment by leseb** [comment]
@Abhishekvrshny building from source is easy take a look at https://github.com/ceph/ceph-ansible/blob/master/install-ansible.sh#L15-L22

**Comment by leseb** [comment]
Closing this as it appears to work on 1.9.x
