### ISSUE TITLE
stable-3.2: default docker image tag refers to nautilus release

### ISSUE THREAD

**Issue by devster31** [ceph/ceph-ansible#3734]
#### What happened
without changing the default docker image tag in the following files (references I could find)
https://github.com/ceph/ceph-ansible/blob/e4a71eabd90a35741136d67cd9e9a4575f1e74d7/roles/ceph-defaults/defaults/main.yml#L536
https://github.com/ceph/ceph-ansible/blob/e4a71eabd90a35741136d67cd9e9a4575f1e74d7/roles/ceph-nfs/defaults/main.yml#L118
the current image deployed refers to the nautilus release of ceph.

#### What you expected to happen
as suggested `stable-3.2` should be for `luminous` or `mimic` releases

#### How to reproduce it (minimal and precise)
simply running the default playbook on branch `stable-3.2` will pull a docker image as follows:
```
$ docker pull ceph/daemon:latest
$ docker inspect ceph/daemon:latest --format '{{ json .Config.Labels }}' | jq
{
  "CEPH_POINT_RELEASE": "",
  "GIT_BRANCH": "HEAD",
  "GIT_CLEAN": "False",
  "GIT_COMMIT": "778c7f91f0ccf325aae783020eb1f35a451231da",
  "GIT_REPO": "https://github.com/ceph/ceph-container.git",
  "RELEASE": "master-778c7f9",
  "maintainer": "Erwan Velu <evelu@redhat.com>",
  "org.label-schema.build-date": "20190305",
  "org.label-schema.license": "GPLv2",
  "org.label-schema.name": "CentOS Base Image",
  "org.label-schema.schema-version": "1.0",
  "org.label-schema.vendor": "CentOS"
}
$ docker run -it --rm --entrypoint=ceph ceph/daemon -v
ceph version 14.2.0 (3a54b2b6d167d4a2a19e003a705696d4fe619afc) nautilus (stable)
```
The tag should probably be `latest-mimic`.

#### Share your group_vars files, inventory
no change from defaults

#### Environment
* OS (e.g. from /etc/os-release): Ubuntu LTS 18.04.2
* Kernel (e.g. `uname -a`): `Linux 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
* Docker version if applicable (e.g. `docker version`):
```
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:53:11 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       774a1f4
  Built:            Thu Feb 28 05:59:55 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```
* Ansible version (e.g. `ansible-playbook --version`): 
```
ansible-playbook 2.7.9
  config file = /Users/devster/code/infrastructure/ansible/ansible.cfg
  configured module search path = ['/Users/devster/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/devster/code/infrastructure/ansible/env/lib/python3.7/site-packages/ansible
  executable location = /Users/devster/code/infrastructure/ansible/env/bin/ansible-playbook
  python version = 3.7.2 (default, Feb 12 2019, 08:16:11) [Clang 9.0.0 (clang-900.0.39.2)]
```
* ceph-ansible version (e.g. `git head or tag or stable branch`): `stable-3.2`
* Ceph version (e.g. `ceph -v`):
`ceph version 14.2.0 (3a54b2b6d167d4a2a19e003a705696d4fe619afc) nautilus (stable)`

**Comment by guits** [comment]
the `latest` tag refers to the latest stable release.

nautilus has been released two days ago, see https://ceph.com/releases/v14-2-0-nautilus-released/
it means it's the latest stable release at the moment.

If you want to stick to luminous or mimic, you should use `latest-luminous` or `latest-mimic`.

However, what you report here is still a valid bug, IMO, the default value for `ceph_docker_image_tag` variable in `stable-3.2` branch should be either `latest-luminous` or `latest-mimic`
