### ISSUE TITLE
UCA defaults need to be uncommented

### ISSUE THREAD

**Issue by mcv21** [ceph/ceph-ansible#3745]
**Bug Report**

What happened:

The UCA-related defaults in https://github.com/ceph/ceph-ansible/blob/4cca3661023ee52dc414ed2a44ed381c6470504f/roles/ceph-defaults/defaults/main.yml#L205-L207 are commented out, meaning that attempting to use the `uca` method fails:

```
 FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'ceph_stable_repo_uca' is undefined\n\nThe error appears to have been in '/nfs/users/nfs_m/mv3/software/ceph-ansible/roles/ceph-common/tasks/installs/debian_uca_repository.yml': line 6, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: add ubuntu cloud archive repository\n  ^ here\n"}
```

What you expected to happen:

Those lines should be uncommented, then installing from `uca` works (well, modulo fixing #3739 ).

I can probably put together a PR to fix both issues if you'd like :)

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 16.04 or 18.04
* Ansible version (e.g. `ansible-playbook --version`): 2.6
* ceph-ansible version (e.g. `git head or tag or stable branch`): 3.2.3
* Ceph version (e.g. `ceph -v`): luminous

**Comment by guits** [comment]
hi @mcv21 

thanks for reporting this, do you mind sending a PR please?

thanks!

**Comment by mcv21** [comment]
Hi @guits 
I've submitted a PR to fix this now :)
