### ISSUE TITLE
Move device checks to be in osd only

### ISSUE THREAD

**Issue by andymcc** [ceph/ceph-ansible#376]
At the moment the device/raw_journal_devices have to be specified globally so that mons will pass the checks - even though mons don't need these values to operate.

This prevents you from being able to only set these on a "per osd" basis. 

The desired outcome would be that you could have say /dev/sda on osd1, and /dev/sda, /dev/sdb on osd2 (as an example) - this is possible if you also specify a global value for devices: so that the check passes (even though that value is bogus and unimportant). It would be better imo if these checks were run against the osds only.

Happy to fix it up if thats considered a suitable fix.

**Comment by leseb** [comment]
Hum  device/raw_journal_devices checks are part of the ceph-common role which is a dependancy of all the roles, the check is only performed on osd nodes (`osd_group_name is defined`) so the declaration is not needed for the mon to succeed.

Am I missing something?

**Comment by andymcc** [comment]
Maybe I'm doing it wrong here.

The check is that osd_group_name is defined, which it is (because its defaulted in defaults/main.yml for ceph-common). So that bool will always pass, since ceph-mon includes ceph-common also the test is run on ceph-mons as well as osds (and all other roles), but unless devices is specified globally (for osds) it won't work. As a work around I've done inventory_hostname in groups['osds'] but it probably would work to just move the device checks (last 3 tasks in that task file) to be only run on osds (so put them in the osd role).

**Comment by andymcc** [comment]
Ahh think I see - that check is only done on the last "osd_dir" check, I think it should happen on the other 2 - I've made a PR.

**Comment by andymcc** [comment]
https://github.com/ceph/ceph-ansible/pull/379/ for ref

**Comment by leseb** [comment]
Oh right my bad... Looking at the PR.
