### ISSUE TITLE
ceph-ansible stable-4.0 ceph-base-14.2.0-0.el7.x86_64 not found ceph-disk command

### ISSUE THREAD

**Issue by JackyChenNgu** [ceph/ceph-ansible#3761]
os: CentOS Linux release 7.6.1810 (Core)
ansible 2.7.9
ceph-ansible stable 4.0
ceph version : ceph version 14.2.0

lead to ： 
task path: /root/ceph-ansible/roles/ceph-osd/tasks/scenarios/collocated.yml:53  failed

**Comment by dsavineau** [comment]
Nautilus release doesn't support ceph-disk anymore that's why the command couldn't be found.
You should now use ceph-volume instead (osd_scenario: lvm). We still have to remove ceph-disk support in stable-4.0 branch (collocated and non-collocated scenarios)

**Comment by guits** [comment]
@dsavineau somehow, there's still a valid bug here I think.
we must patch ceph-validate to stop the playbook if osd_scenario is set to either non-collocated or collocated

**Comment by guits** [comment]
should be addressed by #3187

**Comment by dsavineau** [comment]
this has been done in #3837
