### ISSUE TITLE
Activate osd

### ISSUE THREAD

**Issue by msambol** [ceph/ceph-ansible#377]
I have a question about the `ceph-osd` role. In the task `activate osd(s) when device is a disk` why do you need to check if `item.0.rc == 0` (where item.0 is parted)? It causes the task to be skipped on a fresh deploy because the partitions are not there when `parted` was registered. However, after the disks are prepared, the partitions are there.

/cc @lyandrew

**Comment by leseb** [comment]
Hum I'm not sure to follow. The `activate_osds.yml` will always get triggered after a preparation step so I don't understand how partitions could not be present.
I tend to agree that the check is not really necessary as the `activate_osds.yml` is harmless but skipping the task is always faster than relying on the idempotency of `ceph-disk activate`.

**Comment by msambol** [comment]
`activate_osds.yml` will get triggered but that specific task will not fire on the very first run because when `parted` was registered there were no partitions. I think it should almost be `item.0.rc !=0`?

**Comment by leseb** [comment]
Oh right now I get it. What bugs me now is that with Vagrant I can get everything configured with a single run... AFAIR sometimes I've seen setups where the preparation step triggered the OSD start but I'm not 100%, that might explain this.

**Comment by leseb** [comment]
Just bootstrapped a vagrant env and it seems to be the case, the preparation step starts the OSDs, probably thanks to the udev rules.
I believe we should remove this condition, thanks for pointing that out.

I'd be happy to merge any PR regarding this topic :)

**Comment by msambol** [comment]
I'll submit a PR soon here!

**Comment by leseb** [comment]
Thanks!

**Comment by leseb** [comment]
Fixed by #382
