### ISSUE TITLE
Ceph :How to specify NIC name for cluster network

### ISSUE THREAD

**Issue by selvakumars3** [ceph/ceph-ansible#3821]
Hi,
As part of ceph-deployment , For Cluster network, is ther any way to specify NIC name instead of subnet.?
I have two same subnets configured for different interfaces.

**Comment by dsavineau** [comment]
I don't think so because that's how ceph in using the cluster network value in the ceph config.

http://docs.ceph.com/docs/nautilus/rados/configuration/network-config-ref/#cluster-network
http://docs.ceph.com/docs/nautilus/rados/configuration/network-config-ref/#id2

**Comment by selvakumars3** [comment]
Thanks @dsavineau
