### ISSUE TITLE
Allow fetch directory location to be specified

### ISSUE THREAD

**Issue by mattt416** [ceph/ceph-ansible#383]
Hi @leseb,

I'd like to store the fetch directory outside of my current working directory.  I'm happy to create a PR for this adding the necessary variable to each role's defaults file, and then referencing that instead of "fetch/".  However, before I do this I wanted to confirm there is no specific reason for using the working directory.

Thanks!

--Matt

**Comment by leseb** [comment]
Hey @mattt416, AFAIR there is no specific reasons for storing files under the `fetch` directory unless that this is in the git repo. I don't think this is a limitation of the module either so you can go ahead with this :).

**Comment by leseb** [comment]
Fixes by #395
