### ISSUE TITLE
ceph-common dependencies in RHEL7.1

### ISSUE THREAD

**Issue by ti-mo** [ceph/ceph-ansible#384]
Hey @leseb !

Some minor issues with an Enterprise 1.3 install on RHEL7.1 (fresh from the RH site):

ceph-common/tasks/install_on_redhat.yml:
```
- name: install dependencies
...
    - yum-plugin-priorities.noarch
    - epel-release
```

* `yum-plugin-priorities.noarch` is in `rhel-7-server-optional-rpms`, the user needs to manually intervene with `subscription-manager repos --enable rhel-7-server-optional-rpms`
* The `epel-release` RPM is absent from RH mirrors

`yum-plugin-priorities` is useful to have, but the code doesn't enable `optional-rpms` by default.
Could we conditionally install epel? Perhaps only on CentOS/Fedora/SLES; epel-release-*.rpm seems to be included out-of-the-box there according a quick pbone search.

Cheers, let me know if I can help!

Timo

**Comment by leseb** [comment]
Hey @ti-mo I understand the issue, the reasoning looks good to me. Do you want me to fix this or do you you to submit a PR?

**Comment by ti-mo** [comment]
I'll try and get a PR out later this week, thanks for the reply.

**Comment by leseb** [comment]
@ti-mo thanks! Looking forward to seeing your PR :)
