### ISSUE TITLE
Section [rgw] is not supported in ceph.conf

### ISSUE THREAD

**Issue by flaf** [ceph/ceph-ansible#3841]
Hi,

According to the [doc](http://docs.ceph.com/ceph-ansible/master/#ceph-conf-configuration-file) (and according some `yaml.sample` files), the section `[rgw]` is supported by `ceph_conf_overrides` via the subkey `rgw`. But, for me, it's impossible because the section `[rgw]` is not supported by Ceph itself (tested with Nautilus in my case), no?

Regards.

**Comment by dsavineau** [comment]
I'm not sure that the [rgw] section is supported in the config because the radosgw configuration should be under the [client.rgw.{{ instance_name }}] section.
Also the documentation seems to be outdated

http://docs.ceph.com/docs/master/radosgw/config-ref/
