### ISSUE TITLE
crash in igw_gateway (tgt) | configure iscsi target (gateway)

### ISSUE THREAD

**Issue by hoerup** [ceph/ceph-ansible#3870]
Using latest dev builds of nautilus + ceph-ansible/stable-4.0 git + ceph-iscsi 3.0 latest

Playbook crashes with the followin stacktrace:

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'iqn.2003-01.com.redhat.iscsi-gw:th'
fatal: [hpceph03]: FAILED! => changed=false
  module_stderr: |-
    Traceback (most recent call last):
      File "<stdin>", line 113, in <module>
      File "<stdin>", line 105, in _ansiballz_main
      File "<stdin>", line 48, in invoke_module
      File "/tmp/ansible_igw_gateway_payload_FTb7IO/__main__.py", line 135, in <module>
      File "/tmp/ansible_igw_gateway_payload_FTb7IO/__main__.py", line 105, in ansible_main
      File "/usr/lib/python2.7/site-packages/ceph_iscsi_config/target.py", line 542, in manage
        self.update_acl(config)
      File "/usr/lib/python2.7/site-packages/ceph_iscsi_config/target.py", line 233, in update_acl
        target_config = config.config["targets"][self.iqn]
    KeyError: 'iqn.2003-01.com.redhat.iscsi-gw:th'
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1

To be honest, i don't know if it is a bug in ceph-ansible or ceph-iscsi ?

**Comment by dsavineau** [comment]
that's probably on ceph-ansible side because we're using custom ansible modules for ceph iscsi (like igw_gateway) and this has been tested only with 2.x so if the ceph iscsi python binding changed in 3.x that could be related.
The question is maybe more about do we support ceph iscsi 3 with stable-4.0

@guits wdyt ?

**Comment by hoerup** [comment]
Doesn't it also depend on which version of ceph-iscsi should be used together with nautilus ?

Maybe @mikechristie has some input on this ?

**Comment by ricardoasmarques** [comment]
@hoerup looks like your `ceph-iscsi` configuration is outdated.

What is the output of `# gwcli / export copy | grep version`? It should be '**"version": 8**'.

If the config is outdated you have to restart the `rbd-target-api` service to see it updated.

**Comment by hoerup** [comment]
@ricardoasmarques my/our question to you was more on which version of ceph-iscsi should ceph-ansible use for 4.0/nautilus (currently their modules are developed for ceph-iscsi 2.x)

**Comment by ricardoasmarques** [comment]
@hoerup For Nautilus you should use `3.x` release  because Ceph Dashboard will not work with `2.x`). **But** unfortunately, `ceph-iscsi 3.0` (the latest available release) has a bug that was fixed on PR https://github.com/ceph/ceph-iscsi/pull/52, so you have to wait for `ceph-iscsi 3.1` or use the latest code from ceph-iscsi master branch directly.

**Comment by hoerup** [comment]
@dsavineau it seems that ceph-iscsi 3.x is the choice for Nautilus/stable-4.0

**Comment by dnehring7** [comment]
I fixed the python code according to PR [ceph/ceph-iscsi#52](https://github.com/ceph/ceph-iscsi/pull/52), but the problem still exists:

KeyError: 'iqn.2003-01.com.redhat.iscsi-gw:ceph-igw'
The full traceback is:
Traceback (most recent call last):
  File "<stdin>", line 113, in <module>
  File "<stdin>", line 105, in _ansiballz_main
  File "<stdin>", line 48, in invoke_module
  File "/tmp/ansible_igw_gateway_payload_pFM8vT/__main__.py", line 135, in <module>
  File "/tmp/ansible_igw_gateway_payload_pFM8vT/__main__.py", line 105, in ansible_main
  File "/usr/lib/python2.7/site-packages/ceph_iscsi_config/target.py", line 540, in manage
    self.update_acl(config)
  File "/usr/lib/python2.7/site-packages/ceph_iscsi_config/target.py", line 233, in update_acl
    target_config = config.config["targets"][self.iqn]
KeyError: 'iqn.2003-01.com.redhat.iscsi-gw:ceph-igw'

fatal: [iscsi2]: FAILED! => changed=false 
  module_stderr: |-
    Traceback (most recent call last):
      File "<stdin>", line 113, in <module>
      File "<stdin>", line 105, in _ansiballz_main
      File "<stdin>", line 48, in invoke_module
      File "/tmp/ansible_igw_gateway_payload_pFM8vT/__main__.py", line 135, in <module>
      File "/tmp/ansible_igw_gateway_payload_pFM8vT/__main__.py", line 105, in ansible_main
      File "/usr/lib/python2.7/site-packages/ceph_iscsi_config/target.py", line 540, in manage
        self.update_acl(config)
      File "/usr/lib/python2.7/site-packages/ceph_iscsi_config/target.py", line 233, in update_acl
        target_config = config.config["targets"][self.iqn]
    KeyError: 'iqn.2003-01.com.redhat.iscsi-gw:ceph-igw'
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1

iscsigws.yml
```

gateway_iqn: "iqn.2003-01.com.redhat.iscsi-gw:ceph-igw"
gateway_ip_list: 192.168.4.128,192.168.4.129
rbd_devices:
  - { pool: 'rbd', image: 'ansible1', size: '30G', host: 'iscsi1', state: 'present' }

```
I have no acl defined in the yml-file.

**Comment by ricardoasmarques** [comment]
@dnehring7 I'm not familiar with `ceph-ansible`, but it really looks like the `ceh-iscsi` internal config (the `gateway.conf` rados object) is outdated. You should consider checking this https://github.com/ceph/ceph-ansible/issues/3870#issuecomment-486289292.

**Comment by dnehring7** [comment]
`root@iscsi1:~# gwcli / export copy | jq -r '.["version"]'
8

root@iscsi1:~# rpm -q ceph-iscsi
ceph-iscsi-3.0-25.gd17fe4c.el7.noarch

root@iscsi1:~# gwcli ls
o- / ..................................................................... [...]
  o- cluster ..................................................... [Clusters: 1]
  | o- ceph ........................................................ [HEALTH_OK]
  |   o- pools ...................................................... [Pools: 5]
  |   | o- .rgw.root ........ [(x3), Commit: 0.00Y/2711357696K (0%), Used: 768K]
  |   | o- default.rgw.control  [(x3), Commit: 0.00Y/2711357696K (0%), Used: 0.00Y]
  |   | o- default.rgw.log . [(x3), Commit: 0.00Y/2711357696K (0%), Used: 0.00Y]
  |   | o- default.rgw.meta  [(x3), Commit: 0.00Y/2711357696K (0%), Used: 0.00Y]
  |   | o- rbd ...... [(x3), Commit: 0.00Y/2711357696K (0%), Used: 13844938827b]
  |   o- topology ............................................ [OSDs: 4,MONs: 3]
  o- disks ................................................... [0.00Y, Disks: 0]
  o- iscsi-targets ........................... [DiscoveryAuth: None, Targets: 0]
`
I can see no problems so far.

**Comment by hoerup** [comment]
Hmm are we sure that the ceph-iscsi RPM has picked up the right files from git ? Because the stacktrace lines from dnehring7 doesnt seem to correspond with the lines from https://github.com/ceph/ceph-iscsi/blob/master/ceph_iscsi_config/target.py

 File "/usr/lib/python2.7/site-packages/ceph_iscsi_config/target.py", line 540, in manage
self.update_acl(config)
File "/usr/lib/python2.7/site-packages/ceph_iscsi_config/target.py", line 233, in update_acl
target_config = config.config["targets"][self.iqn]


https://github.com/ceph/ceph-iscsi/blob/master/ceph_iscsi_config/target.py#L540
https://github.com/ceph/ceph-iscsi/blob/master/ceph_iscsi_config/target.py#L233

**Comment by ricardoasmarques** [comment]
Also, if you reached the `target.py#L540` it would be expected that target `iqn.2003-01.com.redhat.iscsi-gw:ceph-igw` already exists in the configuration but I see zero targets on your `# gwcli ls`.

@hoerup - agree, looks like we are using the wrong files here.

**Comment by dnehring7** [comment]
@hoerup Yes, it the current version from

[https://3.chacra.ceph.com/r/ceph-iscsi/master/d17fe4c0f432f12e0868b284e991b06e4b7ad116/centos/7/flavors/default/noarch/ceph-iscsi-3.0-25.gd17fe4c.el7.noarch.rpm](url)

The message was from yesterday (old version), now it's line 545:

`      File "/usr/lib/python2.7/site-packages/ceph_iscsi_config/target.py", line 545, in manage
        target_config = config.config["targets"][self.iqn]
    KeyError: 'iqn.2003-01.com.redhat.iscsi-gw:ceph-igw'
`
Line 233 seems to be not in the traceback anymore.

**Comment by mikechristie** [comment]
Sorry for the late reply. I do not think ceph-iscsi will work well with ceph-ansible for the target/lun/client setup/management. We are in the process of moving away from ceph-ansible for target/lun/client setup and only use ceph-ansible for the installation. You would then use gwcli or dashboard to create/manage targets/luns/clients.

So if using ceph-ansible and ceph-iscsi the iscsigws/iscsi-gws.yml file should not be used for target/lun/client setup. You would need to use the older ceph-iscsi-config package.

**Comment by hoerup** [comment]
@mikechristie so, does it mean that
1) the ceph-ansible iscsi setup for non-containerized deployment, should stop after the packages is installed and services are enabled and running
2) docs http://docs.ceph.com/docs/master/rbd/iscsi-target-ansible/ should be cleaned up accordingly

**Comment by dnehring7** [comment]
It seems that ceph-ansible has problems with setup the initial configuration. I do a manual setup of the iscsi-gw:

`gwcli
cd /iscsi-targets
create iqn.2003-01.com.redhat.iscsi-gw:ceph-igw
cd iqn.2003-01.com.redhat.iscsi-gw:ceph-igw/gateways
create iscsi1 192.168.4.128
create iscsi2 192.168.4.129
cd /disks
create pool=rbd image=ansible1 size=30G
cd /iscsi-targets/iqn.2003-01.com.redhat.iscsi-gw:ceph-igw/hosts
create iqn.1994-05.com.redhat:c73d51e71e4a
auth username=myusername password=mysecret
disk add rbd/ansible1

`

After that, ceph-ansible accepts the configuration. It's not possible for me to create an initial bootstrap setup with ceph-ansible, even without initiator config.

**Comment by mikechristie** [comment]
> @mikechristie so, does it mean that
> 
> 1. the ceph-ansible iscsi setup for non-containerized deployment, should stop after the packages is installed and services are enabled and running
> 2. docs http://docs.ceph.com/docs/master/rbd/iscsi-target-ansible/ should be cleaned up accordingly

Yes. I am testing a patch for ceph-ansible.

**Comment by mikechristie** [comment]
> After that, ceph-ansible accepts the configuration. It's not possible for me to create an initial bootstrap setup with ceph-ansible, even without initiator config.

I did not understand this last part of the comment. You are only installing the ceph iscsi rpms and it is only setting up the daemons/containers right?

You are not having ansible setup the targets/luns/initiators correct?

What is failing?

**Comment by hoerup** [comment]
> Yes. I am testing a patch for ceph-ansible.
Ok - I was just waiting for confirmation on my assumptions before starting of a patch of my own. But if you already have a patch in pipeline then i'll just wait for that one instead.

**Comment by dnehring7** [comment]
@mikechristie, ceph-ansible installs ceph-iscsi and tcmu-runner, but the initial configuration is broken (see my comments above, python errors while installing). When I manually configure gwcli (target, target IPs), ceph-ansible runs flawlessly afterwards. I try to track down the problem:

1. Remove manually the gwcli-configuration
2. on both iscsi-gateways: `yum remove tcmu-runner ceph-iscsi`
3. on the ansible host
```
cat group_vars/iscsigws.yml
gateway_iqn: "iqn.2003-01.com.redhat.iscsi-gw:ceph-igw"
gateway_ip_list: 192.168.4.128,192.168.4.129
trusted_ip_list: 192.168.4.128,192.168.4.129,192.168.4.136

ansible-playbook -i inventory site.yml
```

Result: broken gwcli-config
```
root@iscsi2:~#  rpm -q ceph-iscsi
ceph-iscsi-3.0-25.gd17fe4c.el7.noarch
root@iscsi2:~#  rpm -q tcmu-runner
tcmu-runner-1.4.1-1.el7marcant.x86_64
root@iscsi2:~# gwcli ls
o- / ..................................................................... [...]
  o- cluster ..................................................... [Clusters: 1]
  | o- ceph ........................................................ [HEALTH_OK]
  |   o- pools ...................................................... [Pools: 5]
  |   | o- .rgw.root ........ [(x3), Commit: 0.00Y/2670874368K (0%), Used: 768K]
  |   | o- default.rgw.control  [(x3), Commit: 0.00Y/2670874368K (0%), Used: 0.00Y]
  |   | o- default.rgw.log . [(x3), Commit: 0.00Y/2670874368K (0%), Used: 0.00Y]
  |   | o- default.rgw.meta  [(x3), Commit: 0.00Y/2670874368K (0%), Used: 0.00Y]
  |   | o- rbd ..... [(x3), Commit: 0.00Y/2670874368K (0%), Used: 106980901161b]
  |   o- topology ............................................ [OSDs: 4,MONs: 3]
  o- disks ................................................... [0.00Y, Disks: 0]
  o- iscsi-targets ........................... [DiscoveryAuth: None, Targets: 0]
```
Now I have to fix the iscsi-targets configuration manually.

**Comment by hoerup** [comment]
@mikechristie is the before-mentioned patch available a place where I can see it ?

**Comment by mikechristie** [comment]
Ah I see what you mean. Above when I was saying you cannot use ansible to setup the targets and related iscs/scsi objects I meant you cannot have lines like this:

gateway_iqn: "iqn.2003-01.com.redhat.iscsi-gw:ceph-igw"
gateway_ip_list: 192.168.4.128,192.168.4.129

in your example. But I am guessing you added them because ansible will report errors about not having them right now.

I will post what I have today. I was just waiting to hear back from Sebastien and Guillaume about if they wanted me to rip out all target/lun/client and ceph-iscsi-config/cli related support or leave it for old setups and then add some sort of compat/detection code for newer setups that will use the ceph-iscsi package.
