### ISSUE TITLE
fatal error while comparing with luminous in "allow multimds"

### ISSUE THREAD

**Issue by bbtaeuber** [ceph/ceph-ansible#3873]
**Bug Report**

**Environment**:
* Debian buster
* Linux 4.19.0-4-amd64 #1 SMP Debian 4.19.28-2 (2019-03-15) x86_64 GNU/Linux
* ansible-playbook 2.7.9.post0 (stable-2.7 3c4affeafc) last updated 2019/04/01 12:50:25 (GMT +200)
  python version = 2.7.16 (default, Apr  6 2019, 01:42:57) [GCC 8.3.0]
* ceph-ansible stable-4.0 Tue Apr 16 09:58:52 2019 +0200
* ceph version 14.2.0 (3a54b2b6d167d4a2a19e003a705696d4fe619afc) nautilus (stable)

There is a failure I get running site.yml:

```
fatal: [mds1]: FAILED! => 
  msg: |-
    The conditional check 'ceph_release_num[ceph_release] == ceph_release_num.luminous' failed. The error was: error while evaluating conditional (ceph_release_num[ceph_release] == ceph_release_num.luminous): 'int object' has no attribute u'dummy'
  
    The error appears to have been in '/home/toor/ceph-ansible/roles/ceph-mds/tasks/create_mds_filesystems.yml': line 66, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
    - name: allow multimds
      ^ here  
```

When commenting out the following ansible doesn't complain:

```
#- name: allow multimds
#  command: "{{ docker_exec_cmd | default('') }} ceph --cluster {{ cluster }} fs set {{ cephfs }} allow_multimds true --yes-i-really-mean-it"
#  changed_when: false
#  delegate_to: "{{ groups[mon_group_name][0] }}"
#  when:
#    - ceph_release_num[ceph_release] == ceph_release_num.luminous
```

I think this is a bug in ceph-ansible.

**Comment by dsavineau** [comment]
`'int object' has no attribute u'dummy'`

That's probably because you didn't set `ceph_stable_release` variable in group_vars/all.yml. The default value is dummy but you should set it to nautilus.

Could you share you inventory and variables set in group_vars/*.yml ?

**Comment by bbtaeuber** [comment]
This is our osd.yml (comments removed):
```
---
dummy:
osd_scenario: lvm
bluestore_wal_devices: []
```

This is our all.yml (comments removed):
```
---
dummy:

ceph_release_num: 14
cluster: first
ntp_service_enabled: false

ceph_origin: repository
ceph_repository: custom
ceph_custom_repo: http://IP-ADDR/ceph-custom-repo

monitor_interface: bondfe
ip_version: ipv4
cephfs: cephfs_X

public_network: 192.168.X.0/24
cluster_network: 10.0.Y.0/24
osd_objectstore: bluestore

mds_max_mds: 2

ceph_conf_overrides:
    mon:
        mon allow pool delete: true
```

There is no other file in group_vars.
This is our inventory (comments removed):
```
[mgrs]
cephsible.ceph ansible_user=XXXX
mon[1:3] ansible_user=XXXX

[mons]
mon[1:3] ansible_user=XXXX

[mdss]
mds[1:3] ansible_user=XXXX

[osds]
onode[1:7] ansible_user=XXXX
```

I didn't set `ceph_repository = 'community'`, so I believed this variable `ceph_stable_release` is not important for me like the comments suggest.

**Comment by dsavineau** [comment]
> ceph_release_num: 14

That's because you change the `ceph_release_num` definition.

This shouldn't be changed. https://github.com/ceph/ceph-ansible/blob/stable-4.0/roles/ceph-defaults/defaults/main.yml#L11-L23

Any reason to do this ?

`ceph_release_num[ceph_release] == ceph_release_num.luminous` condition is failing because `ceph_release_num` isn't a dict anymore.
This dict is used to determine the ceph release from the ceph version.

**Comment by bbtaeuber** [comment]
I incorrectly interpreted `ceph_release_num` as a choice to be taken. I'm new to YAML too.
Maybe there is a better place for this definition?

But changing it back to 
```
ceph_release_num:
  dumpling: 0.67
  emperor: 0.72
  firefly: 0.80
  giant: 0.87
  hammer: 0.94
  infernalis: 9
  jewel: 10
  kraken: 11
  luminous: 12
  mimic: 13
  nautilus: 14
  dev: 99
```
leads to another failure:
```
fatal: [mds1]: FAILED! => 
  msg: |-
    The conditional check 'ceph_release_num[ceph_release] == ceph_release_num.luminous' failed. The error was: error while evaluating conditional (ceph_release_num[ceph_release] == ceph_release_num.luminous): 'dict object' has no attribute u'dummy'
  
    The error appears to have been in '/home/toor/ceph-ansible/roles/ceph-mds/tasks/create_mds_filesystems.yml': line 66, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
    - name: allow multimds
      ^ here
```

What's missing in my config now?

Thanks

**Comment by guits** [comment]
@bbtaeuber you have to set `ceph_stable_release: nautilus` in your group_var/all.yml

**Comment by bbtaeuber** [comment]
setting `ceph_stable_release: nautilus` in your `group_var/all.yml` removes the failure

Thanks
