### ISSUE TITLE
Quorum control fails

### ISSUE THREAD

**Issue by ghisl1** [ceph/ceph-ansible#3891]
**Bug Report**

What happened:
site.yml playbook failed when controlling the quorum
TASK [ceph-mon : waiting for the monitor(s) to form the quorum...] **********************************************************************************************************
Friday 19 April 2019  14:12:19 +0000 (0:00:00.175)       0:01:04.571 ********** 
fatal: [zenko-ceph-mimic-0001]: FAILED! => 
  msg: |-
    The conditional check '(ceph_health_raw.stdout != "") and (ceph_health_raw.stdout | default('{}') | from_json)['state'] in ['leader', 'peon']
    ' failed. The error was: No JSON object could be decoded

What you expected to happen:
as Ceph-mon are running and listening on port 6789, it whoud pass but
ceph -s also fails 
ceph -s
server name not found: [v2:192.168.0.74:3300 (Name or service not known)
unable to parse addrs in '[v2:192.168.0.74:3300,v1:192.168.0.74:6789],[v2:192.168.0.38:3300,v1:192.168.0.38:6789],[v2:192.168.0.123:3300,v1:192.168.0.123:6789]'
2019-04-19 14:12:46.726 7f1aca492700 -1 monclient: get_monmap_and_config cannot identify monitors to contact
[errno 22] error connecting to the cluster

>>> seems to wait for a service listening on port 3300

How to reproduce it (minimal and precise):
installation from scratch.
ceph lab : 3 servers with mon, mgr and 3 osds each, and an external rgw

Share your group_vars files, inventory
inventory:
[mons]
zenko-ceph-mimic-0001
zenko-ceph-mimic-0002
zenko-ceph-mimic-0003

[mgrs]
zenko-ceph-mimic-0001
zenko-ceph-mimic-0002
zenko-ceph-mimic-0003

[osds]
zenko-ceph-mimic-0001 devices="['/dev/xvdb','/dev/xvdc','/dev/xvdd']"
zenko-ceph-mimic-0002 devices="['/dev/xvdb','/dev/xvdc','/dev/xvdd']"
zenko-ceph-mimic-0003 devices="['/dev/xvdb','/dev/xvdc','/dev/xvdd']"

[rgws]
zenko-ceph-mimic-rgw

group_vars:
grep -v "^#" all.yml | sed '/^$/d'
---
dummy:
fetch_directory: ~/ceph-ansible-keys
cluster: ceph
ceph_origin: repository
ceph_repository: community
ceph_repository_type: cdn
ceph_stable_release: mimic
cephx: true
monitor_interface: eth0
public_network: 192.168.0.0/24
cluster_network: 192.168.0.0/24
osd_objectstore: bluestore
radosgw_civetweb_port: 80
radosgw_interface: eth0
ceph_conf_overrides:
  global:
    mon_allow_pool_delete: true
    mon_health_preluminous_compat: true
    mon_health_preluminous_compat_warning: false
    osd_pool_default_size: 3
    osd_scrub_begin_hour: 20
    osd_scrub_end_hour: 6
  client.rgw.zenko-mimic-rgw:
    host: zenko-mimic-rgw
    rgw realm: myrealm
    rgw zonegroup: myzonegroup
    rgw zone: myzone

grep -v "^#" osds.yml| sed '/^$/d'
---
dummy:
copy_admin_key: true
osd_scenario: collocated

grep -v "^#" mgrs.yml| sed '/^$/d'
---
dummy:
copy_admin_key: true

grep -v "^#" rgws.yml| sed '/^$/d'
---
dummy:
copy_admin_key: true

**Environment**:
* OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
* Kernel (e.g. `uname -a`):
Linux zenko-ceph-admin 4.15.0-38-generic #41-Ubuntu SMP Wed Oct 10 10:59:38 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Docker version if applicable (e.g. `docker version`):
No docker
* Ansible version (e.g. `ansible-playbook --version`):
ansible 2.7.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/cloud/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
* ceph-ansible version (e.g. `git head or tag or stable branch`):
stable brach
* Ceph version (e.g. `ceph -v`):
ceph version 13.2.5 (cbff874f9007f1869bfd3821b7e33b2a6ffd4988) mimic (stable)

Do I miss something in the configuration ?

**Comment by dsavineau** [comment]
You should use the stable-3.2 branch for mimic and not stable-4.0 (nautilus)

**Comment by ghisl1** [comment]
Hi
works fine with right branch
thx

**Comment by alitvak69** [comment]
I wonder why we cannot use stable-4.0 for Mimic?  I thought that your code should work with supported ceph versions.   Should I assume that there is no backward compatibility between releases?  If so, it has to be documented and no options to enable releases older than supported should be allowed.

**Comment by dsavineau** [comment]
> I wonder why we cannot use stable-4.0 for Mimic?

Because Nautilus introduced a lot a changes and Mimic was already supported on the stable-3.x branch

> Should I assume that there is no backward compatibility between releases? If so, it has to be documented and no options to enable releases older than supported should be allowed

http://docs.ceph.com/ceph-ansible/master/#releases

**Comment by alitvak69** [comment]
Thank you for your reply.   Unfortunately, some good changes like possible podman support or fixes from the master will possibly not backported to stable-3.2.  I assume that versions are related to RHEL storage cluster versions and whence there is no reason to backport new features.  Nautilus is relatively young so we would like to push Mimic in production for now.     Especially because of the massive changes such as v2 messaging etc .
