### ISSUE TITLE
ERROR: Exception caught: org.fedoraproject.FirewallD1.Exception: INVALID_ADDR

### ISSUE THREAD

**Issue by BlackLotus** [ceph/ceph-ansible#3914]
**Bug Report**

What happened:
After trying to update our cluster with ceph-ansible it fails with INVALID_ADDR
```
failed: [foo04.ceph-sh.xxx.de] (item={u'service': u'ceph-mon', u'zone': u'public'}) =>
{"changed": false, "item": {"service": "ceph-mon", "zone": "public"},
"msg": "ERROR: Exception caught: org.fedoraproject.FirewallD1.Exception: INVALID_ADDR: aa.bb.186.0/24, xx.yy.9.0/24, xx.yy.231.160/27, xx.yy.231.130/27 Permanent and Non-Permanent(immediate) operation"}         >
failed: [bar-01-mon.ceph-2.yyy.de] (item={u'service': u'ceph', u'zone': u'public'}) =>
{"changed": false, "item": {"service": "ceph", "zone": "public"},
"msg": "ERROR: Exception caught: org.fedoraproject.FirewallD1.Exception: INVALID_ADDR: aa.bb.186.0/24, xx.yy.9.0/24, xx.yy.231.160/27, xx.yy.231.130/27 Permanent and Non-Permanent(immediate) operation"}
```

How to reproduce it (minimal and precise):
Try to use multiple public networks like described http://docs.ceph.com/docs/luminous/rados/configuration/network-config-ref/

(Share your group_vars files, inventory - will share later have to pseudo. some lines)

**Environment**:
* OS (e.g. from /etc/os-release):
```
NAME="Red Hat Enterprise Linux Server"
VERSION="7.6 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.6"
PRETTY_NAME=Storage
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.6:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.6"
```
* Kernel (e.g. `uname -a`):
Linux bar-01-mon.ceph-2.yyy.de 3.10.0-957.5.1.el7.x86_64 #1 SMP Wed Dec 19 10:46:58 EST 2018 x86_64 x86_64 x86_64 GNU/Linux

* Ansible version (e.g. `ansible-playbook --version`):
```
ansible-playbook 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```
* ceph-ansible version (e.g. `git head or tag or stable branch`):
3.2.4-1.el7cp
* Ceph version (e.g. `ceph -v`):
```
ceph version 12.2.8-89.el7cp (2f66ab2fa63b2879913db6d6cf314572a83fd1f0) luminous (stable)
```

**Comment by dsavineau** [comment]
> Try to use multiple public networks like described http://docs.ceph.com/docs/luminous/rados/configuration/network-config-ref/

We currently don't support multiple networks for public and cluster network in ceph-ansible.
I suppose you specify something like `public_network: 192.168.1.0/24,192.168.2.0/24` but the `public_network` (and `cluster_network`) are supposed to be an unique value.

You issue comes from the firewalld module because we're using the public_network variable as value for the firewalld source parameter. This field doesn't support multiple networks.

https://github.com/ceph/ceph-ansible/blob/stable-3.2/roles/ceph-infra/tasks/configure_firewall.yml#L26
https://docs.ansible.com/ansible/latest/modules/firewalld_module.html#parameters

**Comment by BlackLotus** [comment]
That's exactly what I expected, problem is only that until a few weeks ago everything just worked and not supporting multiple networks causes way more problems.

**Comment by BlackLotus** [comment]
I'm using check_firewall maybe I have to use configure_firewall. 
It's a bit irritating when configuration options are renamed or deprecated without any real notice.

**Comment by dsavineau** [comment]
Yes, you need to use configure_firewall.
https://github.com/ceph/ceph-ansible/blob/stable-3.2/RELEASE-NOTE.md#removed-features
