### ISSUE TITLE
rolling_update.yml fails at restarting upgraded rgw

### ISSUE THREAD

**Issue by JoshuaLyle** [ceph/ceph-ansible#3926]
**Bug Report**

What happened: `rolling_update.yml` when upgrading from luminous to mimic fails the playbook every time when running the `restart ceph rgw daemon(s) - non container` handler shown below

```
RUNNING HANDLER [ceph-handler : restart ceph rgw daemon(s) - non container] ************************************************************
Sunday 28 April 2019  15:56:07 -0500 (0:00:01.083)       0:03:38.557 ********** 
skipping: [x.x.x.249] => (item=x.x.x.245) 
failed: [x.x.x.249 -> x.x.x.249] (item=x.x.x.249) => {"changed": true, "cmd": ["/usr/bin/env", "bash", "/tmp/restart_rgw_daemon.sh"], "delta": "0:01:40.251344", "end": "2019-04-28 20:57:49.317083", "item": "x.x.x.249", "msg": "non-zero return code", "rc": 1, "start": "2019-04-28 20:56:09.065739", "stderr": "", "stderr_lines": [], "stdout": "Socket file /var/run/ceph/ceph-client.rgw.xxx.asok could not be found, which means Rados Gateway is not running.
...
```

What you expected to happen:
I expected the playbook to wait for the rgw to come back up and for the playbook to proceed with the update. The upgrade process works fine if you just rerun the playbook because by the time the playbook gets to this point, the rgw has had enough time to come back up properly.

How to reproduce it (minimal and precise):
running `ansible-playbook -i hosts infrastructure-playbooks/rolling_update.yml` with `ceph_stable_release: mimic` on a luminous cluster triggers this

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 16.04.6
* Ansible version (e.g. `ansible-playbook --version`): `ansible 2.6.0`
* ceph-ansible version (e.g. `git head or tag or stable branch`): `stable-3.2`
* Ceph version (e.g. `ceph -v`): `12.2.12`

**Comment by dsavineau** [comment]
Could you share your ansible.log, inventory and group_vars/*.yml files ?

**Comment by JoshuaLyle** [comment]
hosts
```
[mons]
x.x.x.245
x.x.x.249
x.x.x.253

[osds]
x.x.x.245
x.x.x.249
x.x.x.253
x.x.x.64
x.x.x.65
x.x.x.66
x.x.x.67

[mdss]
x.x.x.245
x.x.x.249
x.x.x.253

[mgrs]
x.x.x.245
x.x.x.249
x.x.x.253

[rgws]
x.x.x.245
x.x.x.249
x.x.x.253

[clients]
x.x.x.1
x.x.x.245
x.x.x.249
x.x.x.253

[all:vars]
ansible_ssh_user=root
```

Here are the variables from `group_vars/*.yml`
```
ceph_origin: 'repository'
ceph_repository: community
ceph_stable_release: mimic
monitor_interface: br_storage
public_network: x.x.x.0/22
osd_objectstore: bluestore
radosgw_interface: br_storage
cephfs_pools:
  - { name: "{{ cephfs_data }}", pgs: "64" }
  - { name: "{{ cephfs_metadata }}", pgs: "64" }
devices:
  - /dev/sdb
osd_scenario: collocated
fetch_directory: ~/ceph-ansible-keys
ceph_origin: repository
ceph_repository: rhcs
```

**Comment by dsavineau** [comment]
`ceph_repository` is defined twice with community and rhcs value. What's the right one ?

**Comment by JoshuaLyle** [comment]
Sorry, my grep included an unused sample file. I edited it to remove the copied `ceph_origin` and incorrect `ceph_repository: rhcs`.

The correct variables I used are (the correct complete list is above)
```
ceph_origin: 'repository'
ceph_repository: community
```

**Comment by dsavineau** [comment]
It seems to come from the radosgw socket with Ubuntu 16.04 (don't know if 18.04 is affected too) and Ceph mimic.
I was able to reproduce the issue during the Luminous (12.2.12-1xenial) to Mimic (13.2.5-1xenial) upgrade.

* Luminous:
```console
# ls -hl /var/run/ceph/ceph-client.rgw.*
srwxr-xr-x 1 ceph ceph 0 May  6 18:26 ceph-client.rgw.cephaio-1.asok
```
* Mimic:
```console
# ls -hl /var/run/ceph/ceph-client.rgw.*
srwxr-xr-x 1 ceph ceph 0 May  6 18:41 /var/run/ceph/ceph-client.rgw.cephaio-1.16913.23928832.asok
```
So there's two extra fields before the `.asok` suffix : `<pid>.<random>`
This is causing the radosgw restart script (triggered by the handler) to fail because this pattern isn't checked

https://github.com/ceph/ceph-ansible/blob/stable-3.2/roles/ceph-handler/templates/restart_rgw_daemon.sh.j2#L11-L12

So we're still testing the old pattern (`SOCKET=/var/run/ceph/{{ cluster }}-client.rgw.{{ ansible_hostname }}.asok`) causing the failure.

**Comment by dsavineau** [comment]
Ubuntu 18.04 is affected too but on a fresh deployment we can't see the issue.
