### ISSUE TITLE
iscsi: install gwtop

### ISSUE THREAD

**Issue by hoerup** [ceph/ceph-ansible#3929]
I'm not sure if this should be part of main igw role, or a seperate playbook under infrastructure-playbooks ?

Actions needed to get gwtop working: 

```
yum install ceph-iscsi-tools #latest from shaman + patch from https://github.com/ceph/ceph-iscsi-tools/pull/8
cd /var/lib/pcp/pmdas/lio/
./Install

systemctl enable pmcd
systemctl start pmcd

firewall-cmd --permanent --add-port 44321/tcp
firewall-cmd --reload
```

**Comment by dsavineau** [comment]
I'm not sure ceph-ansible is the right place to do that.
we only need to install ceph-iscsi-config and ceph-iscsi-cli packages in order to get the rbd-target services up & running.
