### ISSUE TITLE
Ceph-ansible deploy issue No JSON object could be decoded

### ISSUE THREAD

**Issue by fbsduser** [ceph/ceph-ansible#3948]
Similar Issue !  
https://github.com/ceph/ceph-ansible/issues/3598
I have 5 Virtual Machines -vbox 
I'd  tried  ceph-ansible 3.2.15,4.0.0rc5
And same issue ...
OS : Debian strech latest update.
two nic 1 nat "ed"  to internet, 1 nat private for cluster network
Each machine has 2 GB of ram, 2 Cpu,1 8 GB os hdd , two 20 GB storages.

```
ansible 2.7.10
  config file = /home/prj/ceph-ansible-4.0.0rc5/ansible.cfg
  configured module search path = [u'/home/prj/ceph-ansible-4.0.0rc5/library']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]
```
Results :
```
debian                     : ok=82   changed=5    unreachable=0    failed=1   
mon1                       : ok=76   changed=2    unreachable=0    failed=0   
osd1                       : ok=34   changed=1    unreachable=0    failed=0   
osd2                       : ok=34   changed=1    unreachable=0    failed=0   
osd3                       : ok=34   changed=1    unreachable=0    failed=0   
```

Ceph configuration file  : /etc/ceph/ceph.conf

```
[global]
mon initial members = debian,mon1
osd pool default crush rule = -1
fsid = 8c1e689d-76dc-4894-8f47-3c31503c8a43
mon host = [v2:10.0.2.20:3300,v1:10.0.2.20:6789],[v2:10.0.2.20:3300,v1:10.0.2.20:6789]
public network = 192.168.20.0/24
cluster network = 10.0.2.0/24
```

Ansible host config  /etc/ansible/hosts

```
[osds]
osd1
osd2
osd3

[mons]
debian
mon1
```

full log 
[ansible.log](https://github.com/ceph/ceph-ansible/files/3160765/ansible.log)

**Comment by guits** [comment]
please, share your group_vars/

**Comment by fbsduser** [comment]
Thanks for reply
But share to/with ? may you explain ?
copy here ?

**Comment by dsavineau** [comment]
Yes share the content of the group_vars directory here.

You can do something like:
```console
$ egrep -v '^(#|$|dummy)' group_vars/*.yml
```

And remove/replace the sensitive information.

On a first quick look I can see that the IP address of both monitor nodes seems to be the same (10.0.2.20) from the mon_host value in the ceph.conf file.
Also this IP address isn't part of the public_network (192.168.20.0/24)

**Comment by fbsduser** [comment]
`group_vars/all.yml:---
group_vars/all.yml:cluster: ceph
group_vars/all.yml:mon_group_name: mons
group_vars/all.yml:osd_group_name: osds
group_vars/all.yml:rgw_group_name: rgws
group_vars/all.yml:ntp_daemon_type: timesyncd
group_vars/all.yml:ceph_use_distro_backports: false # DEBIAN ONLY
group_vars/all.yml:ceph_origin: repository 
group_vars/all.yml:ceph_repository: community 
group_vars/all.yml:ceph_mirror: http://download.ceph.com
group_vars/all.yml:ceph_stable_key: https://download.ceph.com/keys/release.asc
group_vars/all.yml:ceph_stable_release: nautilus 
group_vars/all.yml:ceph_stable_repo: "{{ ceph_mirror }}/debian-{{ ceph_stable_release }}"
group_vars/all.yml:monitor_interface: enp0s3 
group_vars/all.yml:monitor_address: 192.168.x.y, 192.168.x.z 
group_vars/all.yml:ip_version: ipv4
group_vars/all.yml:public_network: 192.168.x.0/24 
group_vars/all.yml:cluster_network: "{{ public_network | regex_replace(' ', '') }}"
group_vars/all.yml:devices:
group_vars/all.yml: - '/dev/sdb'
group_vars/all.yml: - '/dev/sdc'
group_vars/mons.yml:---
group_vars/mons.yml:mon_group_name: mons
group_vars/mons.yml:secure_cluster: false
group_vars/mons.yml:client_admin_ceph_authtool_cap:
group_vars/mons.yml:  mon: allow *
group_vars/mons.yml:  osd: allow *
group_vars/mons.yml:  mds: allow *
group_vars/mons.yml:crush_rule_config: false
group_vars/osds.yml:---
group_vars/osds.yml:devices:
group_vars/osds.yml:  - /dev/sdb
group_vars/osds.yml:  - /dev/sdc
group_vars/osds.yml:osd_auto_discovery: true 
group_vars/osds.yml:osds_per_device: 1
`

**Comment by guits** [comment]
@fbsduser define the `monitor_address` variable for each monitor in your inventory host file:

```ini
[mons]
debian monitor_address=10.0.2.XY
mon1 monitor_address=10.0.2.XX
```

**Comment by fbsduser** [comment]
Nothing .:(

**Comment by guits** [comment]
not sure to understand the last output you shared

**Comment by fbsduser** [comment]
I tried to test is working  ansible hostname   .

**Comment by guits** [comment]
sorry but it's still unclear, did you try to rerun ceph-ansible?

you may find support on IRC at irc.oftc.net #ceph-ansible as well

**Comment by fbsduser** [comment]
![snapshot_799](https://user-images.githubusercontent.com/26079108/57507465-25123080-7314-11e9-8941-8a5a40aabf05.png)

**Comment by fbsduser** [comment]
I've tested some changes but all steps returned the same results 

fatal: [mon1]: FAILED! => 
  msg: |-
    The conditional check '(ceph_health_raw.stdout != "") and (ceph_health_raw.stdout | default('{}') | from_json)['state'] in ['leader', 'peon']
    ' failed. The error was: No JSON object could be decoded


egrep -v '^(#|$|dummy)' group_vars/*.yml
group_vars/all.yml:---
group_vars/all.yml:cluster: ceph
group_vars/all.yml:mon_group_name: mons
group_vars/all.yml:osd_group_name: osds
group_vars/all.yml:rgw_group_name: rgws
group_vars/all.yml:ntp_daemon_type: timesyncd
group_vars/all.yml:ceph_use_distro_backports: false # DEBIAN ONLY
group_vars/all.yml:ceph_origin: repository 
group_vars/all.yml:ceph_repository: community 
group_vars/all.yml:ceph_mirror: http://download.ceph.com
group_vars/all.yml:ceph_stable_key: https://download.ceph.com/keys/release.asc
group_vars/all.yml:ceph_stable_release: nautilus 
group_vars/all.yml:ceph_stable_repo: "{{ ceph_mirror }}/debian-{{ ceph_stable_release }}"
group_vars/all.yml:monitor_interface: enp0s8 
group_vars/all.yml:monitor_address: 10.0.2.43, 10.0.2.47 
group_vars/all.yml:ip_version: ipv4
group_vars/all.yml:public_network: 192.168.20.0/24 
group_vars/all.yml:cluster_network: 10.0.2.0/24 # "{{ public_network | regex_replace(' ', '') }}"
group_vars/all.yml:devices:
group_vars/all.yml: - '/dev/sdb'
group_vars/all.yml: - '/dev/sdc'
group_vars/mons.yml:---
group_vars/mons.yml:mon_group_name: mons
group_vars/mons.yml:secure_cluster: false
group_vars/mons.yml:client_admin_ceph_authtool_cap:
group_vars/mons.yml:  mon: allow *
group_vars/mons.yml:  osd: allow *
group_vars/mons.yml:  mds: allow *
group_vars/mons.yml:crush_rule_config: false
group_vars/osds.yml:---
group_vars/osds.yml:devices:
group_vars/osds.yml:  - /dev/sdb
group_vars/osds.yml:  - /dev/sdc
group_vars/osds.yml:osd_auto_discovery: true 
group_vars/osds.yml:osds_per_device: 1

**Comment by guits** [comment]
@fbsduser please share your inventory and ceph.conf from all your monitors.

**Comment by guits** [comment]
if you are using inventory to set monitor_address you can remove `group_vars/all.yml:monitor_address: 10.0.2.43, 10.0.2.47`

**Comment by guits** [comment]
@fbsduser please share the output of `ip a` from all your monitors, thanks.

**Comment by fbsduser** [comment]
I ran command below in console - found in /var/log/message in mon1 - 

ceph --cluster ceph -n mon. -k /var/lib/ceph/mon/ceph-mon1/keyring mon_status --format json removes=None argv=None creates=None chdir=None stdin=None

and with any range (10/192) the result is the same 

server name not found: [v2:192.168.20.47:3300 (Name or service not known)
unable to parse addrs in '[v2:192.168.20.47:3300,v1:192.168.20.47:6789],[v2:192.168.20.43:3300,v1:192.168.20.43:6789]'
Error connecting to cluster: Error

**Comment by fbsduser** [comment]
[ip.txt](https://github.com/ceph/ceph-ansible/files/3165944/ip.txt)

**Comment by fbsduser** [comment]
[ceph.conf.txt](https://github.com/ceph/ceph-ansible/files/3166089/ceph.conf.txt)
[site.yml.txt](https://github.com/ceph/ceph-ansible/files/3166090/site.yml.txt)

**Comment by guits** [comment]
> Similar Issue !
> #3598
> I have 5 Virtual Machines -vbox
> I'd tried ceph-ansible 3.2.15,4.0.0rc5

> `group_vars/all.yml:ceph_stable_release: nautilus`

you are trying to deploy nautilus with ceph-ansible 3.2 which is not possible, please upgrade to v4.0.0rc6
or set `ceph_stable_release` to luminous

**Comment by fbsduser** [comment]
changed to :
ceph_stable_release: luminous 

&& 
fatal: [mon1]: FAILED! => 
  msg: |-
    The conditional check '(ceph_health_raw.stdout != "") and (ceph_health_raw.stdout | default('{}') | from_json)['state'] in ['leader', 'peon']
    ' failed. The error was: No JSON object could be decoded
:(

**Comment by dsavineau** [comment]
try to replace
```yaml
group_vars/all.yml:monitor_interface: enp0s8 
group_vars/all.yml:monitor_address: 10.0.2.43, 10.0.2.47
```
by
```yaml
group_vars/all.yml:monitor_interface: enp0s3
```

enp0s3 is the interface configured with `public_network` network

Also you should have an odd number of monitor nodes to avoid quorum issue in the future.

**Comment by fbsduser** [comment]
monitor_interface: enp0s3 
THE PROBLEM  STIL IS Not solved:(

**Comment by dsavineau** [comment]
did you just re run ceph-ansible playbook or recreate the nodes as well ?

**Comment by fbsduser** [comment]
Can you explain a bit more about recreate nodes ?
Thanks.

**Comment by dsavineau** [comment]
did you reinstall the nodes from scratch ?
If you don't want to reinstall your nodes, you probably need to purge the cluster via the dedicated playbook https://github.com/ceph/ceph-ansible/blob/master/infrastructure-playbooks/purge-cluster.yml

**Comment by fbsduser** [comment]
I did and got same result :( again.

**Comment by fbsduser** [comment]
I can't believe that
root@debian:/home/prj/ceph-ansible-4.0.0rc5# grep -r "ceph_origin" . | grep  dummy
root@debian:/home/prj/ceph-ansible-4.0.0rc5#
and 
Friday 10 May 2019  23:13:21 +0430 (0:00:00.080)       0:00:21.744 ************ 
 [ERROR]: [osd1] Validation failed for variable: ceph_repository

 [ERROR]: [osd1] Given value for ceph_repository: dummy

 [ERROR]: [osd1] Reason: ceph_repository must be either 'community', 'rhcs', 'dev', 'custom' or 'uca'

fatal: [osd1]: FAILED! => changed=false 
when i tried to 
 ansible-playbook infrastructure-playbooks/add-mon.yml site.yml -u root 
What ? :( Is it about version mismatch or something else ?

**Comment by dsavineau** [comment]
Why are you running infrastructure-playbooks/add-mon.yml and site.yml playbooks in the same time ?

Just run :
```console
$ ansible-playbook infrastructure-playbooks/purge-cluser.yml -u root
```
And then rerun the `site.yml` playbook

**Comment by fbsduser** [comment]
Not the same time. I tried your command and as you can see the result is failed ! 
So I decieded to try the other tools, to get any information.

**Comment by fbsduser** [comment]
No change ! 
ansible-playbook infrastructure-playbooks/purge-cluster.yml -u root

changed: [localhost]

PLAY RECAP **********************************************************************************************************************************************************************************
debian                     : ok=15   changed=9    unreachable=0    failed=0   
localhost                  : ok=2    changed=1    unreachable=0    failed=0   
mon1                       : ok=15   changed=9    unreachable=0    failed=0   
osd1                       : ok=31   changed=19   unreachable=0    failed=0   
osd2                       : ok=28   changed=13   unreachable=0    failed=0   
osd3                       : ok=28   changed=13   unreachable=0    failed=0   

DONE ! OK 

And 

ansible-playbook site.yml -u root

fatal: [mon1]: FAILED! => 
  msg: |-
    The conditional check '(ceph_health_raw.stdout != "") and (ceph_health_raw.stdout | default('{}') | from_json)['state'] in ['leader', 'peon']
    ' failed. The error was: No JSON object could be decoded

**Comment by dsavineau** [comment]
Could you check on both debian and mon1 nodes if ceph-mon is started, the binding address related to this service, if both nodes can communicate on those IP addresses (+ port), etc...

**Comment by fbsduser** [comment]
ps auxw | grep ceph 
ceph        7549  0.0  1.4 411696 28996 ?        Ssl  23:52   0:00 /usr/bin/ceph-mon -f --cluster ceph --id osd1 --setuser ceph --setgroup ceph
root        7600  0.0  0.0  12780   940 pts/0    S+   23:56   0:00 grep ceph
root@mon1:~# ps auxw | grep ceph
ceph        8951  0.0  1.4 412716 30444 ?        Ssl  May10   0:00 /usr/bin/ceph-mon -f --cluster ceph --id mon1 --setuser ceph --setgroup ceph
root        9045  0.0  0.0  12780   952 pts/0    R+   00:09   0:00 grep ceph
root@mon1:~#
root@debian:/home/prj/ceph-ansible-4.0.0rc5# ps auxw | grep ceph 
ceph       15933  0.0  1.4 412728 30432 ?        Ssl  May10   0:00 /usr/bin/ceph-mon -f --cluster ceph --id debian --setuser ceph --setgroup ceph
root       16034  0.0  0.0  12780   984 pts/0

**Comment by dsavineau** [comment]
When I said
> the binding address related to this service,

It was to run this on the monitor nodes
```console
$ netstat -lntup | grep ceph-mon
```

**Comment by fbsduser** [comment]
tcp        0      0 192.168.20.43:6789      0.0.0.0:*               LISTEN      15933/ceph-mon      
root@osd1:~# netstat -lntup | grep ceph-mon
tcp        0      0 192.168.20.44:6789      0.0.0.0:*               LISTEN      7549/ceph-mon root@mon1:~# netstat -lntup | grep ceph-mon
tcp        0      0 192.168.20.47:6789      0.0.0.0:*               LISTEN      8951/ceph-mon

**Comment by dsavineau** [comment]
How could you have 3 ceph-mon processes when you only have 2 nodes declared in the inventory ? did you add another mon node ?

Are you able to reach the other mon processes from each monitor nodes ?

like (or using nc instead of telnet)
```console
# from 192.168.20.43 node
$ telnet 192.168.20.44 6789
$ telnet 192.168.20.47 6789

# from 192.168.20.44 node
$ telnet 192.168.20.43 6789
$ telnet 192.168.20.47 6789

etc...
```

Or at least are you able to ping them ?

**Comment by fbsduser** [comment]
3 nodes are

**Comment by dsavineau** [comment]
I can see you're using ceph-ansible-4.0.0rc5 so you want to deploy nautilus right ? because you should have 2 ceph-mon process per mon nodes (port 3300 and 6789) in nautilus but it's not the case.
You're only using the legacy mon port. Is it possible that you're using the ceph-ansible 4.0.0rc5 to deploy luminous ?

**Comment by fbsduser** [comment]
Yes ! right. Is that wrong ?
I'm using rc5 and luminous

**Comment by dsavineau** [comment]
it has already been mentionned in that thread.

3.2.x => Luminous or Mimic
4.0.x => Nautilus

**Comment by fbsduser** [comment]
Thanks.I will try it.
