### ISSUE TITLE
bogus "please provide devices to your osd scenario" error when osd_auto_discovery: true

### ISSUE THREAD

**Issue by einot** [ceph/ceph-ansible#399]
group_vars/ceph-osd:

    osd_auto_discovery: true
    journal_collocation: true

In ./ceph-ansible/roles/ceph-common/tasks/checks/check_mandatory_vars.yml there is:

    ...
    - name: verify devices have been provided
      fail: msg="please provide devices to your osd scenario"
      when:
        osd_group_name is defined and
        osd_group_name in group_names and
        journal_collocation and
        devices is not defined

I think the test for devices should be replaced with "not ( devices is defined or osd_auto_discovery )".

**Comment by leseb** [comment]
Hey @einot thanks for reporting.
Why not simply adding `not osd_auto_discovery and`?

**Comment by einot** [comment]
Of course, that's it.

**Comment by leseb** [comment]
Great closing this then.
