### ISSUE TITLE
Can we set containerized_deployment per service?

### ISSUE THREAD

**Issue by hatdropper1977** [ceph/ceph-ansible#3992]
I notice that the "switch from non-containerized to containerize" [playbook](https://github.com/ceph/ceph-ansible/blob/master/infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml) sets the **containerized_deployment** parameter per service.  Does this mean that we could deploy, for example, osd, manager and admin as containers, and then RGW as a bare metal service?  Would that work?

**Comment by hatdropper1977** [comment]
This is more of a question for ASK vs. an issue.

I asked the question on [ask.openstack.org](https://ask.openstack.org/en/question/122134/can-we-set-containerized_deployment-per-service/)

**Comment by guits** [comment]
@hatdropper1977 I think it's fine to ask here as well.
Although I've never tested it so I couldn't say I'm 100% sure, that might be possible if you deploy a full baremetal cluster first then running the switch to container playbook excluding the rgw node.
