### ISSUE TITLE
container-common role vars override host/group vars

### ISSUE THREAD

**Issue by KingJ** [ceph/ceph-ansible#4019]
**Bug Report**

What happened:
In my group vars I set ``container_package_name: "docker-ce"`` and ran the ``switch-from-non-containerized-to-containerized-ceph-daemons`` playbook. However, the install container package task installed the ``docker.io`` package resulting in the existing ``docker-ce`` package being uninstalled on the targeted hosts, causing disruption to existing containerised workloads.

As the ceph-container-common role defines platform specific variables in the role's vars folder, these [take precedence over variables defined in host and group variables](https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable). It may be preferable to instead define these variables in the role's defaults folder to allow them to be overridden by host and group variables defined by the user.

What you expected to happen:
Existing ``docker-ce`` package to remain in place and for all Ceph daemons to be containerised.

How to reproduce it (minimal and precise):

1. Set ``install container package`` in an appropriate group or host variables file.
2. Run switch-from-non-containerized-to-containerized-ceph-daemons infrastructure playbook.

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 18.04.2 LTS
* Kernel (e.g. `uname -a`): 4.18.0-20-generic #21~18.04.1-Ubuntu SMP Wed May 8 08:43:37 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Docker version if applicable (e.g. `docker version`): Docker version 18.09.6, build 481bc77
* Ansible version (e.g. `ansible-playbook --version`): ansible-playbook 2.8.0
* ceph-ansible version (e.g. `git head or tag or stable branch`): stable-4.0
* Ceph version (e.g. `ceph -v`): ceph version 14.2.1 (d555a9489eb35f84f2e1ef49b77e19da9d113972) nautilus (stable)

**Comment by dsavineau** [comment]
> As the ceph-container-common role defines platform specific variables in the role's vars folder, these take precedence over variables defined in host and group variables. It may be preferable to instead define these variables in the role's defaults folder to allow them to be overridden by host and group variables defined by the user.

The purpose of this was to define the container package/service per Linux distribution in role vars instead of doing this logic with multiple `when` statements in the code.
Those variables are not supposed to be overrided in the host/group_vars.

> What you expected to happen:
Existing docker-ce package to remain in place and for all Ceph daemons to be containerised.

You can still do it via the ansible extra vars with the CLI
```console
$ ansible-playbook -i hosts infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml -e container_package_name=docker-ce
```

**Comment by KingJ** [comment]
Many thanks for the quick reply @dsavineau , I wasn't sure if this was intended behaviour and thought it best to check. I understand now why this was defined in the role vars.

Although it is possible to override the role vars using extra vars, unless i'm mistaken I think i'll need to ensure that I always override it via extra vars when running other playbooks such as rolling_update in the future? My original aim for setting container_package_name via host/group vars was to set it once avoid needing to pass extra vars with every future playbook execution.

**Comment by dsavineau** [comment]
> Although it is possible to override the role vars using extra vars, unless i'm mistaken I think i'll need to ensure that I always override it via extra vars when running other playbooks such as rolling_update in the future?

Yes you need to set this via extra vars for all playbooks

**Comment by KingJ** [comment]
> Yes you need to set this via extra vars for all playbooks

Thank you for confirming, i'll close this issue now.
