### ISSUE TITLE
ansible 2.8 deprecation warning in dashboard

### ISSUE THREAD

**Issue by hoerup** [ceph/ceph-ansible#4022]
[DEPRECATION WARNING]: evaluating dashboard_enabled as a bare variable, this behaviour will go away and you might need to add |bool to the expression in the future. Also see 
CONDITIONAL_BARE_VARS configuration toggle.. This feature will be removed in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

**Comment by guits** [comment]
this doesn't show up only in dashboard afaik.

@hoerup If you want to submit a PR for this that would be great :relieved: 

otherwise, I think @rishabh-d-dave can take care of this.

**Comment by guits** [comment]
should be addressed by #4025

**Comment by guits** [comment]
we shouldn't close issues until PRs fixing them are actually merged
