### ISSUE TITLE
Complete dashboard

### ISSUE THREAD

**Issue by hoerup** [ceph/ceph-ansible#4026]
With current module there are still some manual steps to perform to get a complete setup:

* download dashboards to /etc/grafana/dashboards/ceph-dashboard/
* enable prometheus mgr: ceph mgr module enable prometheus

Either these steps should be put into playbook or at least be described in a README-dashboard

**Comment by guits** [comment]
@hoerup thanks for your feedback about the dashboard

**Comment by hoerup** [comment]
Depends on this one to be completed as well https://github.com/ceph/ceph/pull/28101

**Comment by hoerup** [comment]
Hmm the dashboards are packaged in rpm - so on grafana node we should install the package ceph-grafana-dashboards

**Comment by guits** [comment]
> Hmm the dashboards json files are packaged so on grafana node we should install the package ceph-grafana-dashboards
>
> http://download.ceph.com/rpm-nautilus/el7/noarch/ceph-grafana-dashboards-14.2.1-0.el7.noarch.rpm


@hoerup is it related to this issue you mentioned ?

> download dashboards to /etc/grafana/dashboards/ceph-dashboard/

**Comment by hoerup** [comment]
Yes grafana needs the dashboards json files, and first I thought that we would need to download them in a ansible task - but theres no need for that when they are packed in a RPM

**Comment by guits** [comment]
@b-ranto do you know whether this package will be available downstream ?

**Comment by guits** [comment]
@dsavineau I think we need to add this package in a new container image for containerized deployments.

**Comment by dsavineau** [comment]
@guits I'm a little bit confused by the ceph-grafana-dashboards package installation. Currently it's installed on either mgr or mon but should it be done on the grafana node instead ?

**Comment by hoerup** [comment]
yes it is a dependency on the grafana node !

**Comment by b-ranto** [comment]
Hey, this is trickier than one might hope. We have originally used the ceph-grafana-dashboards package and the grafana provisioning on the grafana node but later, this was supposed to be superseded by making the dashboard module push the dashboards to the grafana node. I am not sure what the state of that PR is upstream, Zack was working on this.

@zmc Can you elaborate on this matter? Was the dashboard PR merged?

**Comment by guits** [comment]
> I am not sure what the state of that PR is upstream 

@b-ranto I guess you are referring to: https://github.com/ceph/ceph/pull/26415 ?
