### ISSUE TITLE
Failure importing the ceph stable repo key

### ISSUE THREAD

**Issue by matthewrees** [ceph/ceph-ansible#403]
This issue seems to be intermittent, but it has happened twice in the last 2 weeks and the first time it was no longer an issue when I ran the playbook less than an hour later.

Workstation: Linux Mint 17.1 (based on Ubuntu 14.04) with Ansible 1.9.3
Servers: CentOS 7.1 with latest updates

Trace of the playbook failing:

TASK: [ceph-common | install the ceph stable repository key] ****************** 
failed: [XXX] => {"failed": true, "parsed": false}
BECOME-SUCCESS-vpcuvjvkadqieptjwkavpyewfqoisxnh
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1441356162.03-168602942242488/rpm_key", line 2587, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1441356162.03-168602942242488/rpm_key", line 199, in main
    RpmKey(module)
  File "/root/.ansible/tmp/ansible-tmp-1441356162.03-168602942242488/rpm_key", line 87, in __init__
    keyfile = self.fetch_key(key)
  File "/root/.ansible/tmp/ansible-tmp-1441356162.03-168602942242488/rpm_key", line 121, in fetch_key
    key = rsp.read()
AttributeError: 'NoneType' object has no attribute 'read'
OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Shared connection to XXX closed.

Testing importing the key manually on the ceph host:

[root@XXX ~]# rpm --import https://ceph.com/git/?p=ceph.git;a=blob_plain;f=keys/release.asc
error: https://ceph.com/git/?p=ceph.git: key 1 not an armored public key.

For what it's worth, when running this playbook, this test fails on both hosts being provisioned for the first time as well as hosts that have already been provisioned with ceph-ansible and are actively running ceph.

**Comment by leseb** [comment]
Hum can't really reproduce this, I suspect this is a system issue not related to ansible or anything.

**Comment by matthewrees** [comment]
I haven't been able to reproduce this today. If it happens again I will attempt to wget the key at the same time as the playbook fails to see if it is a problem with the ceph.com infrastructure or with the rpm_key module (or something else).

**Comment by bsanders** [comment]
I actually ran into this today on Centos7 VM's.

SSH'ing into the VM and running the rpm --import command by hand with that url fails, just like it did for @matthewrees.

However, If I escape the semicolons in the RPM import command, it does work:

$ sudo rpm --import https://ceph.com/git/?p=ceph.git\;a=blob_plain\;f=keys/release.asc
$ rpm -q gpg-pubkey --qf '%{name}-%{version}-%{release} --> %{summary}\n' 
gpg-pubkey-f4a80eb5-53a7ff4b --> gpg(CentOS-7 Key (CentOS 7 Official Signing Key) <security@centos.org>)
gpg-pubkey-460f3994-55f88609 --> gpg(Ceph.com (release key) <security@ceph.com>)

But ansible still won't provision if I set "ceph_stable_key" to that escaped string.  And importing the key manually doesn't appear to trigger rpm_key's "present" state.

Any thoughts?

**Comment by bsanders** [comment]
Perhaps it has something to do with a HTTP 301 status code?  Maybe urllib2 is unhappy about the 301?

$ wget https://ceph.com/git/?p=ceph.git\;a=blob_plain\;f=keys/release.asc -O release.asc
--2015-10-07 14:27:27--  https://ceph.com/git/?p=ceph.git;a=blob_plain;f=keys/release.asc
Resolving ceph.com (ceph.com)... 173.236.248.54, 2607:f298:6050:51f3:f816:3eff:fe62:31d3
Connecting to ceph.com (ceph.com)|173.236.248.54|:443... connected.
HTTP request sent, awaiting response... **301 Moved Permanently**
Location: https://git.ceph.com/?p=ceph.git;a=blob_plain;f=keys/release.asc [following]
--2015-10-07 14:27:27--  https://git.ceph.com/?p=ceph.git;a=blob_plain;f=keys/release.asc
Resolving git.ceph.com (git.ceph.com)... 67.205.20.229
Connecting to git.ceph.com (git.ceph.com)|67.205.20.229|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1645 (1.6K) [text/plain]
Saving to: ‘release.asc’

100%[===========================================================================================================================================================================>] 1,645       --.-K/s   in 0.04s   

2015-10-07 14:27:29 (40.7 KB/s) - ‘release.asc’ saved [1645/1645]

**Comment by bsanders** [comment]
Not sure what exactly is going on.  This is definitely intermittent.  It has both succeeded and failed on multiple machines (my dev workstation, a VM on that workstation, a server in our lab, and on a remote server hosted by Dreamhost).

I'm attempting to reproduce this with I can reproduce this with just:
> import urllib2
> key = 'https://ceph.com/git/?p=ceph.git;a=blob_plain;f=keys/release.asc'
> req = urllib2.Request(key, None)
> data = urllib2.urlopen(req, data=None, timeout=10)

The series of relevant calls is something like:
[--- in https://github.com/ansible/ansible-modules-core/blob/devel/packaging/os/rpm_key.py ]:
Rpmkey(key_url) ->
fetch_key(key_url) ->
[--- in https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/urls.py ]:
fetch_url(key_url) ->
open_url(key_url) ->   (..... really...?)
r = urllib2.urlopen(urllib2.request(key_url), data=None, timeout=10))

The actual error gets caught in fetch_key() when we try to do a read on 'r' which is a None.  This can happen if the urlopen() call raises an exception which will be caught in fetch_url().  In the exception case I'm seeing, its an "ssl.SSLError: The read operation timed out" exception, which fetch_url is catching with "except Exception" adding to some sort of debug object, and passing up to fetch_key()

The traceback, when the exception does trigger:

>Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 442, in error
    result = self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 629, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1224, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib64/python2.7/urllib2.py", line 1189, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib64/python2.7/httplib.py", line 1067, in getresponse
    response.begin()
  File "/usr/lib64/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python2.7/httplib.py", line 365, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib64/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib64/python2.7/ssl.py", line 246, in recv
    return self.read(buflen)
  File "/usr/lib64/python2.7/ssl.py", line 165, in read
    return self._sslobj.read(len)
ssl.SSLError: The read operation timed out
