### ISSUE TITLE
eth1 won't get an IP address with libvirt provider

### ISSUE THREAD

**Issue by deejay2** [ceph/ceph-ansible#4037]
**Bug Report**

What happened:
I ran: vagrant up --provision
It resulted in this error:
msg": "eth1 does not have any IPv4 address on mon0"   (for each mon nodes).

How to reproduce it (minimal and precise):
Run "vagrant up" with libvirt as provider

Share your group_vars files, inventory

**Environment**:
* OS (e.g. from /etc/os-release):
NAME="Pop!_OS"
VERSION="19.04"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.04"
VERSION_ID="19.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=disco
UBUNTU_CODENAME=disco

* Kernel (e.g. `uname -a`):
Linux pop-os 5.0.0-15-generic #16pop0-Ubuntu SMP Wed May 15 14:41:25 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Ansible version (e.g. `ansible-playbook --version`):
ansible-playbook 2.6.16.post0 (stable-2.6 7a1ccef131) last updated 2019/05/16 15:48:09 (GMT -400)
  config file = /home/admin/projects/ceph-ansible/ansible.cfg
  configured module search path = [u'/home/admin/projects/ceph-ansible/library']
  ansible python module location = /home/admin/projects/ansible-2.6/lib/ansible
  executable location = /home/admin/projects/ansible-2.6/bin/ansible-playbook
  python version = 2.7.16 (default, Apr  6 2019, 01:42:57) [GCC 8.3.0]

* ceph-ansible version (e.g. `git head or tag or stable branch`):
stable-3.2

[vagrant_variables.yml.txt](https://github.com/ceph/ceph-ansible/files/3238892/vagrant_variables.yml.txt)

[error.log](https://github.com/ceph/ceph-ansible/files/3238890/error.log)

**Comment by deejay2** [comment]
I just noticed that the VM's interfaces file has:

auto eth1
iface eth1 inet manual

It should be:
iface eth1 inet dhcp

**Comment by dsavineau** [comment]
Similar to https://github.com/ceph/ceph-ansible/issues/4036 this comes from the vagrant box used.

**Comment by guits** [comment]
@deejay2 share output of `ip a` from one monitor please. thanks!

**Comment by deejay2** [comment]
@guits sure!

Here it is:

vagrant@ubuntubox:~$ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:aa:64:69 brd ff:ff:ff:ff:ff:ff
    inet 192.168.121.236/24 brd 192.168.121.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::5054:ff:feaa:6469/64 scope link 
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:5b:54:9d brd ff:ff:ff:ff:ff:ff
    inet6 fe80::5054:ff:fe5b:549d/64 scope link 
       valid_lft forever preferred_lft forever

**Comment by deejay2** [comment]
I changed for vagrant_box: guits/ubuntu-bionic64

I got the very same error after:
vagrant destroy -f
vagrant up

TASK [ceph-validate : fail if eth1 does not exist on mon0] *********************
task path: /home/deejay2/projects/ceph-ansible/roles/ceph-validate/tasks/check_eth_mon.yml:2
Tuesday 04 June 2019  12:04:52 -0400 (0:00:00.508)       0:00:48.322 ********** 
META: noop
fatal: [mon0]: FAILED! => {
    "changed": false, 
    "msg": "eth1 does not exist on mon0"
}
META: noop
META: noop
META: noop
META: noop
META: noop
fatal: [mon1]: FAILED! => {
    "changed": false, 
    "msg": "eth1 does not exist on mon1"
}
fatal: [mon2]: FAILED! => {
    "changed": false, 
    "msg": "eth1 does not exist on mon2"
}

**Comment by deejay2** [comment]
Ahhh got it! It was ens6 for  guits/ubuntu-bionic64
