### ISSUE TITLE
add-osd.yml fails replacing osd after the physical device broke down in collocated and non-collocated scenarios

### ISSUE THREAD

**Issue by jadebustos** [ceph/ceph-ansible#4041]
**Bug Report**

What happened:

After a disk device crashed and after replacing by a new one using add-osd.yml to replace the osd the following error happens:

ASK [ceph-osd : prepare ceph containerized osd disk collocated] **************************************************************************************************************************************************
Tuesday 28 May 2019  23:32:59 +0200 (0:00:00.107)       0:03:09.062 ***********
failed: [ceph3-bs.frontend.lab] (item=[{'_ansible_parsed': True, '_ansible_item_result': True, '_ansible_item_label': u'/dev/vdb', u'script': u"unit 'MiB' print", '_ansible_no_log': False, u'changed': False, 'failed': False, 'item': u'/dev/vdb', u'invocation': {u'module_args': {u'part_start': u'0%', u'part_end': u'100%', u'name': None, u'align': u'optimal', u'number': None, u'label': u'msdos', u'state': u'info', u'part_type': u'primary', u'flags': None, u'device': u'/dev/vdb', u'unit': u'MiB'}}, u'disk': {u'dev': u'/dev/vdb', u'physical_block': 512, u'table': u'gpt', u'logical_block': 512, u'model': u'Virtio Block Device', u'unit': u'mib', u'size': 20480.0}, '_ansible_ignore_errors': None, u'partitions': []}, u'/dev/vdb']) => {"changed": true, "cmd": "docker run --net=host --pid=host --privileged=true --name=ceph-osd-prepare-ceph3-bs-vdb -v /etc/ceph:/etc/ceph:z -v /var/lib/ceph/:/var/lib/ceph/:z -v /dev:/dev -v /etc/localtime:/etc/localtime:ro -e DEBUG=verbose -e CLUSTER=ceph -e CEPH_DAEMON=OSD_CEPH_DISK_PREPARE -e OSD_DEVICE=/dev/vdb -e OSD_BLUESTORE=1 -e OSD_FILESTORE=0 -e OSD_DMCRYPT=0 -e OSD_JOURNAL_SIZE=2048 registry.access.redhat.com/rhceph/rhceph-3-rhel7:latest", "delta": "0:00:00.039004", "end": "2019-05-28 23:32:59.795437", "item": [{"_ansible_ignore_errors": null, "_ansible_item_label": "/dev/vdb", "_ansible_item_result": true, "_ansible_no_log": false, "_ansible_parsed": true, "changed": false, "disk": {"dev": "/dev/vdb", "logical_block": 512, "model": "Virtio Block Device", "physical_block": 512, "size": 20480.0, "table": "gpt", "unit": "mib"}, "failed": false, "invocation": {"module_args": {"align": "optimal", "device": "/dev/vdb", "flags": null, "label": "msdos", "name": null, "number": null, "part_end": "100%", "part_start": "0%", "part_type": "primary", "state": "info", "unit": "MiB"}}, "item": "/dev/vdb", "partitions": [], "script": "unit 'MiB' print"}, "/dev/vdb"], "msg": "non-zero return code", "rc": 125, "start": "2019-05-28 23:32:59.756433", "stderr": "/usr/bin/docker-current: Error response from daemon: Conflict. The container name \"/ceph-osd-prepare-ceph3-bs-vdb\" is already in use by container d104e10b8500c26120ccd34be5625e215a7c52b2e641200bd0b73c68cdcfe54b. You have to remove (or rename) that container to be able to reuse that name..\nSee '/usr/bin/docker-current run --help'.", "stderr_lines": ["/usr/bin/docker-current: Error response from daemon: Conflict. The container name \"/ceph-osd-prepare-ceph3-bs-vdb\" is already in use by container d104e10b8500c26120ccd34be5625e215a7c52b2e641200bd0b73c68cdcfe54b. You have to remove (or rename) that container to be able to reuse that name..", "See '/usr/bin/docker-current run --help'."], "stdout": "", "stdout_lines": []}

What you expected to happen:

How to reproduce it (minimal and precise):
Simulate an osd failure (collocated adn non-collocated scenario). Remove the osd from cluster, replace the disk for a new one an run ansible-playbook -i hosts-add-osd add-osd.yml.
[ceph-admin@cephmetrics-bs ceph-ansible]$ cat hosts-add-osd 
[all:vars]
ansible_user=ceph-admin

[mons]
ceph1-bs.frontend.lab
ceph2-bs.frontend.lab
ceph3-bs.frontend.lab

[osds]
#ceph1-bs.frontend.lab
#ceph2-bs.frontend.lab devices="['/dev/vdc']"
#ceph3-bs.frontend.lab devices="['/dev/vdb']"
ceph4-bs.frontend.lab devices="['/dev/vdd']"

[mgrs]
ceph1-bs.frontend.lab
ceph2-bs.frontend.lab
ceph3-bs.frontend.lab
[ceph-admin@cephmetrics-bs ceph-ansible]$ 

Share your group_vars files, inventory
[yml-files.tar.gz](https://github.com/ceph/ceph-ansible/files/3242240/yml-files.tar.gz)

**Environment**:
* OS (e.g. from /etc/os-release): Red Hat Enterprise Linux Server release 7.6 (Maipo)
* Kernel (e.g. `uname -a`): Linux ceph1-bs.frontend.lab 3.10.0-957.12.2.el7.x86_64 #1 SMP Fri Apr 19 21:09:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Docker version if applicable (e.g. `docker version`):  1.13.1
* Ansible version (e.g. `ansible-playbook --version`): ansible-playbook 2.6.16
* ceph-ansible version (e.g. `git head or tag or stable branch`): ceph-ansible-3.2.15-1.el7cp.noarch
* Ceph version (e.g. `ceph -v`): ceph version 12.2.8-128.el7cp (030358773c5213a14c1444a5147258672b2dc15f) luminous (stable)

**Comment by dsavineau** [comment]
The add-osd.yml playbook isn't used to replace an OSD but only to add a new OSD disk on a host.

https://access.redhat.com/documentation/en-us/red_hat_ceph_storage/3/html/operations_guide/managing-the-storage-cluster-size#adding-a-ceph-osd-using-ansible-with-the-same-disk-topology-ops

https://github.com/ceph/ceph-ansible/blob/master/infrastructure-playbooks/add-osd.yml#L2-L5

The only playbook designed for this is [1] but it's untested, outdated and unmaintained.

[1] https://github.com/ceph/ceph-ansible/blob/master/infrastructure-playbooks/untested-by-ci/replace-osd.yml

**Comment by jadebustos** [comment]
I though that it can also be used to add osds according the comments at the beginning of the file. 

I have tested with bluestore (lvm and collocated) and it works, and it was tested with filestore (I do not know the scenario) working as well.

I will make a pull request just to consider if this workarround can be merged on upstream code.

Thanks in advance,
