### ISSUE TITLE
Unable to start Rados Gateway

### ISSUE THREAD

**Issue by thiagodasilva** [ceph/ceph-ansible#408]
I'm trying to deploy rgw on VMs using Centos 7.1, but even thou Vagrant and Ansible runs without any issues, the rados gateway is not running automatically.

I've checked port 80 of rgw0 and there's nothing listening on it. Also trying to run: "sudo /etc/init.d/ceph-radosgw start" results in the following:

Sep 18 15:36:56 ceph-rgw0 sudo[5700]: vagrant : TTY=pts/0 ; PWD=/home/vagrant ; USER=root ; COMMAND=/sbin/service ceph-radosgw start
Sep 18 15:36:56 ceph-rgw0 systemd[1]: Starting LSB: radosgw RESTful rados gateway...
Sep 18 15:36:56 ceph-rgw0 ceph-radosgw[5717]: Starting radosgw instance(s)...
Sep 18 15:36:57 ceph-rgw0 ceph-radosgw[5717]: /bin/radosgw is not running.
Sep 18 15:36:57 ceph-rgw0 systemd[1]: ceph-radosgw.service: control process exited, code=exited status=1
Sep 18 15:36:57 ceph-rgw0 systemd[1]: Failed to start LSB: radosgw RESTful rados gateway.
Sep 18 15:36:57 ceph-rgw0 systemd[1]: Unit ceph-radosgw.service entered failed state.

Any suggestions on how to get rgw running?

**Comment by leseb** [comment]
Can you at least run rgw manually? Do you have anything in rgw's logs?

**Comment by thiagodasilva** [comment]
Hello @leseb 

I tried this command as suggested by @yehudasa:
`sudo radosgw -c /etc/ceph/ceph.conf -f --log-to -stderr --debug-rgw=20 --debug-ms=1`

Running the command returned an error about missing the keyring.

Here's the output:

```
[vagrant@ceph-rgw0 ~]$ sudo radosgw -c /etc/ceph/ceph.conf -f --log-to -stderr --debug-rgw=20 --debug-ms=1
2015-09-22 17:17:07.521508 7f51118a3880  0 ceph version 0.94.3
(95cefea9fd9ab740263bf8bb4796fd864d9afe2b), process radosgw, pid 8563
2015-09-22 17:17:07.558672 7f51118a3880  0 ext_mime_map_init(): failed
to open file=/etc/mime.types ret=-2
2015-09-22 17:17:07.559001 7f51118a3880  1 -- :/0 messenger.start
2015-09-22 17:17:07.559071 7f51118a3880 -1 monclient(hunting): ERROR:
missing keyring, cannot use cephx for authentication
2015-09-22 17:17:07.559079 7f51118a3880  0 librados: client.admin
initialization error (2) No such file or directory
2015-09-22 17:17:07.559447 7f51118a3880  1 -- :/1008563 mark_down_all
2015-09-22 17:17:07.559676 7f51118a3880  1 -- :/1008563 shutdown
complete.
2015-09-22 17:17:07.560027 7f51118a3880 -1 Couldn't init storage
provider (RADOS)
[vagrant@ceph-rgw0 ~]$ 
```

I added the client.admin keyring to ceph.conf:

```
[vagrant@ceph-rgw0 ~]$ cat /etc/ceph/ceph.conf | grep keyring
  keyring = /etc/ceph/ceph.client.admin.keyring
  keyring = /var/lib/ceph/radosgw/ceph-rgw.ceph-rgw0/keyring
  keyring = /var/lib/ceph/restapi/ceph-restapi/keyring
```
Now, when running again the command below:

`sudo radosgw -c /etc/ceph/ceph.conf -f --log-to-stderr --debug-rgw=20 --debug-ms=1`

I see a lot of logging that looks like rgw is running correctly, at
least I don't see any error or failure messages. They look more like
typical heartbeat type of messages:

```
2015-09-22 18:14:24.391473 7fd1cb7fe700  1 -- 192.168.42.40:0/1008928 -
-> 192.168.42.102:6804/5909 -- ping magic: 0 v1 -- ?+0 0x7fd1bc257420
con 0x2d5c6f0
2015-09-22 18:14:24.391484 7fd1cb7fe700  1 -- 192.168.42.40:0/1008928 -
-> 192.168.42.101:6804/5900 -- ping magic: 0 v1 -- ?+0 0x7fd1bc2576b0
con 0x2d6b890
2015-09-22 18:14:24.391492 7fd1cb7fe700  1 -- 192.168.42.40:0/1008928 -
-> 192.168.42.102:6800/5362 -- ping magic: 0 v1 -- ?+0 0x7fd1bc2579c0
con 0x2d72420
2015-09-22 18:14:24.391500 7fd1cb7fe700  1 -- 192.168.42.40:0/1008928 -
-> 192.168.42.101:6800/5358 -- ping magic: 0 v1 -- ?+0 0x7fd1bc257cd0
con 0x2d7a360
2015-09-22 18:14:24.395421 7fd1c82f3700  1 -- 192.168.42.40:0/1008928
<== osd.0 192.168.42.101:6800/5358 1089 ==== osd_op_reply(3082 notify.4
[watch ping cookie 47691488] v0'0 uv24 ondisk = 0) v6 ==== 175+0+0
(1255968610 0 0) 0x7fd1bc2500f0 con 0x2d7a360
2015-09-22 18:14:24.395533 7fd1c82f3700  1 -- 192.168.42.40:0/1008928
<== osd.0 192.168.42.101:6800/5358 1090 ==== osd_op_reply(3083 notify.6
[watch ping cookie 47695488] v0'0 uv24 ondisk = 0) v6 ==== 175+0+0
(1240792457 0 0) 0x7fd1bc2553c0 con 0x2d7a360
2015-09-22 18:14:24.395608 7fd1c82f3700  1 -- 192.168.42.40:0/1008928
<== osd.0 192.168.42.101:6800/5358 1091 ==== osd_op_reply(3084 notify.7
[watch ping cookie 47697776] v0'0 uv24 ondisk = 0) v6 ==== 175+0+0
(2040385786 0 0) 0x7fd1bc256710 con 0x2d7a360
2015-09-22 18:14:24.395715 7fd1c84f5700  1 -- 192.168.42.40:0/1008928
<== osd.2 192.168.42.102:6800/5362 1113 ==== osd_op_reply(3085 notify.1
[watch ping cookie 47658752] v0'0 uv24 ondisk = 0) v6 ==== 175+0+0
(4057252612 0 0) 0x7fd1b408bd60 con 0x2d72420
2015-09-22 18:14:24.395792 7fd1c84f5700  1 -- 192.168.42.40:0/1008928
<== osd.2 192.168.42.102:6800/5362 1114 ==== osd_op_reply(3086 notify.3
[watch ping cookie 47662672] v0'0 uv24 ondisk = 0) v6 ==== 175+0+0
(2102748158 0 0) 0x7fd1b408bd60 con 0x2d72420
```

The problem is that when trying to run either S3 or Swift tests
detailed here: http://docs.ceph.com/docs/master/radosgw/config/
I get this error: `socket.error: [Errno 111] Connection refused`

Running netstat doesn't seem to show anything listening on port 80

```
[vagrant@ceph-rgw0 ~]$ netstat -tpln
(No info could be read for "-p": geteuid()=1000 but you should be
root.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address        
 State       PID/Program name    
tcp        0      0 0.0.0.0:22              0.0.0.0:*              
 LISTEN      -                   
tcp        0      0 0.0.0.0:7480            0.0.0.0:*              
 LISTEN      -                   
tcp        0      0 127.0.0.1:25            0.0.0.0:*              
 LISTEN      -                   
tcp6       0      0 :::22                   :::*                   
 LISTEN      -                   
tcp6       0      0 ::1:25                  :::*                   
 LISTEN      -          
```

I'm running CentOS-7.1, here's how I modified `vagrant_variables.yml`
```
vagrant_box: bento/centos-7.1
vagrant_storagectl: 'SATA Controller'
```
Note the extra space of `vagrant_storagectl`

Thanks for the help :)

**Comment by liewegas** [comment]
Hi Thiago,

On Tue, 22 Sep 2015, Thiago da Silva wrote:
> 
> Hello @leseb
> 
> I tried this command as suggested by @yehudasa:
> sudo radosgw -c /etc/ceph/ceph.conf -f --log-to -stderr --debug-rgw=20 --debug-ms=1
> 
> Running the command returned an error about missing the keyring.
> 
> Here's the output:
> 
> [vagrant@ceph-rgw0 ~]$ sudo radosgw -c /etc/ceph/ceph.conf -f --log-to -stderr --debug-rgw=20 --debug-ms=1
> 2015-09-22 17:17:07.521508 7f51118a3880  0 ceph version 0.94.3
> (95cefea9fd9ab740263bf8bb4796fd864d9afe2b), process radosgw, pid 8563
> 2015-09-22 17:17:07.558672 7f51118a3880  0 ext_mime_map_init(): failed
> to open file=/etc/mime.types ret=-2
> 2015-09-22 17:17:07.559001 7f51118a3880  1 -- :/0 messenger.start
> 2015-09-22 17:17:07.559071 7f51118a3880 -1 monclient(hunting): ERROR:
> missing keyring, cannot use cephx for authentication
> 2015-09-22 17:17:07.559079 7f51118a3880  0 librados: client.admin
> initialization error (2) No such file or directory
> 2015-09-22 17:17:07.559447 7f51118a3880  1 -- :/1008563 mark_down_all
> 2015-09-22 17:17:07.559676 7f51118a3880  1 -- :/1008563 shutdown
> complete.
> 2015-09-22 17:17:07.560027 7f51118a3880 -1 Couldn't init storage
> provider (RADOS)
> [vagrant@ceph-rgw0 ~]$ 
> 
> I added the client.admin keyring to ceph.conf:
> 
> [vagrant@ceph-rgw0 ~]$ cat /etc/ceph/ceph.conf | grep keyring
>   keyring = /etc/ceph/ceph.client.admin.keyring
>   keyring = /var/lib/ceph/radosgw/ceph-rgw.ceph-rgw0/keyring
>   keyring = /var/lib/ceph/restapi/ceph-restapi/keyring
> 
> Now, when running again the command below:
> 
> sudo radosgw -c /etc/ceph/ceph.conf -f --log-to-stderr --debug-rgw=20 --debug-ms=1
> 
> I see a lot of logging that looks like rgw is running correctly, at
> least I don't see any error or failure messages. They look more like
> typical heartbeat type of messages:
> 
> 2015-09-22 18:14:24.391473 7fd1cb7fe700  1 -- 192.168.42.40:0/1008928 -
> -> 192.168.42.102:6804/5909 -- ping magic: 0 v1 -- ?+0 0x7fd1bc257420
> con 0x2d5c6f0
> 2015-09-22 18:14:24.391484 7fd1cb7fe700  1 -- 192.168.42.40:0/1008928 -
> -> 192.168.42.101:6804/5900 -- ping magic: 0 v1 -- ?+0 0x7fd1bc2576b0
> con 0x2d6b890
> 2015-09-22 18:14:24.391492 7fd1cb7fe700  1 -- 192.168.42.40:0/1008928 -
> -> 192.168.42.102:6800/5362 -- ping magic: 0 v1 -- ?+0 0x7fd1bc2579c0
> con 0x2d72420
> 2015-09-22 18:14:24.391500 7fd1cb7fe700  1 -- 192.168.42.40:0/1008928 -
> -> 192.168.42.101:6800/5358 -- ping magic: 0 v1 -- ?+0 0x7fd1bc257cd0
> con 0x2d7a360
> 2015-09-22 18:14:24.395421 7fd1c82f3700  1 -- 192.168.42.40:0/1008928
> <== osd.0 192.168.42.101:6800/5358 1089 ==== osd_op_reply(3082 notify.4
> [watch ping cookie 47691488] v0'0 uv24 ondisk = 0) v6 ==== 175+0+0
> (1255968610 0 0) 0x7fd1bc2500f0 con 0x2d7a360
> 2015-09-22 18:14:24.395533 7fd1c82f3700  1 -- 192.168.42.40:0/1008928
> <== osd.0 192.168.42.101:6800/5358 1090 ==== osd_op_reply(3083 notify.6
> [watch ping cookie 47695488] v0'0 uv24 ondisk = 0) v6 ==== 175+0+0
> (1240792457 0 0) 0x7fd1bc2553c0 con 0x2d7a360
> 2015-09-22 18:14:24.395608 7fd1c82f3700  1 -- 192.168.42.40:0/1008928
> <== osd.0 192.168.42.101:6800/5358 1091 ==== osd_op_reply(3084 notify.7
> [watch ping cookie 47697776] v0'0 uv24 ondisk = 0) v6 ==== 175+0+0
> (2040385786 0 0) 0x7fd1bc256710 con 0x2d7a360
> 2015-09-22 18:14:24.395715 7fd1c84f5700  1 -- 192.168.42.40:0/1008928
> <== osd.2 192.168.42.102:6800/5362 1113 ==== osd_op_reply(3085 notify.1
> [watch ping cookie 47658752] v0'0 uv24 ondisk = 0) v6 ==== 175+0+0
> (4057252612 0 0) 0x7fd1b408bd60 con 0x2d72420
> 2015-09-22 18:14:24.395792 7fd1c84f5700  1 -- 192.168.42.40:0/1008928
> <== osd.2 192.168.42.102:6800/5362 1114 ==== osd_op_reply(3086 notify.3
> [watch ping cookie 47662672] v0'0 uv24 ondisk = 0) v6 ==== 175+0+0
> (2102748158 0 0) 0x7fd1b408bd60 con 0x2d72420
> 
> The problem is that when trying to run either S3 or Swift tests
> detailed here: http://docs.ceph.com/docs/master/radosgw/config/
> I get this error: socket.error: [Errno 111] Connection refused
> 
> Running netstat doesn't seem to show anything listening on port 80
> 
> [vagrant@ceph-rgw0 ~]$ netstat -tpln
> (No info could be read for "-p": geteuid()=1000 but you should be
> root.)
> Active Internet connections (only servers)
> Proto Recv-Q Send-Q Local Address           Foreign Address        
>  State       PID/Program name    
> tcp        0      0 0.0.0.0:22              0.0.0.0:*              
>  LISTEN      -                   
> tcp        0      0 0.0.0.0:7480            0.0.0.0:*              
>  LISTEN      -                   

This is radosgw, on port 7480 by default.  You can put it on port 80 with 

 rgw frontends = "civetweb port=80"

in ceph.conf.

sage

**Comment by thiagodasilva** [comment]
@liewegas,

ceph.conf was already configured with port 80
```
[vagrant@ceph-rgw0 ~]$ cat /etc/ceph/ceph.conf | grep civet
  rgw frontends = civetweb port=80
```

I changed the swift test to point to port 7480 and it seems to be working fine:
```
[vagrant@ceph-rgw0 ~]$ swift -A http://ceph-rgw0:7480/auth/1.0 -U testuser:swift -K KCwWMLOLqqyfvVsCVtECenMPnEB8fgqCRSW\/Gu+0 upload container1 s3test.py 
s3test.py
[vagrant@ceph-rgw0 ~]$ 
[vagrant@ceph-rgw0 ~]$ swift -A http://ceph-rgw0:7480/auth/1.0 -U testuser:swift -K KCwWMLOLqqyfvVsCVtECenMPnEB8fgqCRSW\/Gu+0 list
container1
[vagrant@ceph-rgw0 ~]$ 
[vagrant@ceph-rgw0 ~]$ swift -A http://ceph-rgw0:7480/auth/1.0 -U testuser:swift -K KCwWMLOLqqyfvVsCVtECenMPnEB8fgqCRSW\/Gu+0 list container1
s3test.py
``` 

Now, I just need to figure out why port 80 is not working and why running `sudo service ceph-radosgw start` also fails...

Thanks for all the help!

**Comment by yehudasa** [comment]
@thiagodasilva make sure that the frontends line is in the correct ceph.conf section (you're running it under user client.admin by default, so you should have a [client.admin] section, and that's where the configurable is supposed to be if you're running it manually).

**Comment by thiagodasilva** [comment]
@yehudasa Here's the link for my ceph.conf: http://ur1.ca/nubaj
I guess the part that I'm confused about is that in the `[client.rgw.ceph-rgw0]` section there's a keyring option already set (not the client.admin keyring), but it was still necessary for me to add the keyring option in the `[global]` section. 

I realize this is probably very specific to ceph-ansible and how @leseb configured the cluster, so I'm just trying to be helpful and figure out if there is indeed anything that needs to be fixed in ceph-ansible.

**Comment by yehudasa** [comment]
@thiagodasilva I'm not familiar with the ansible stuff, but I assume that when running rgw through it, it uses a different ceph user. That's why everything there is under the `[client.rgw.ceph-rgw0]` section. When you run it manually, it runs under the `client.admin` user, so different config versions are being applied. If you specify `-n client.rgw.ceph-rgw0` on the command line, then it will use the other user that was configured.

**Comment by leseb** [comment]
@thiagodasilva you shouldn't be using the admin keyring to run rgw.
It might be an issue with the init script.
As @yehudasa said it uses a different user `client.rgw.ceph-rgw0`.
So you should try to run it manually again with the proper user.

This will give you:

`radosgw -c /etc/ceph/ceph.conf -f -n client.rgw.ceph-rgw0`

**Comment by thiagodasilva** [comment]
@leseb, @yehudasa,
Thanks, that fixed the problem. I'm now able to (manually) run with the proper user and rgw is listening on port 80.

**Comment by leseb** [comment]
@thiagodasilva I think now you need to have a look at the init script and check what goes wrong and why. :)

**Comment by leseb** [comment]
Closing this for now, feel free to reopen.

**Comment by suab321321** [comment]
@leseb 
Following Steps I did: 
1. `RGW=1 ../src/vstart.sh -d -n -x` (worked fine)
2. `swift -A http://localhost:8000/auth -U test:tester -K testing list`(worked fine)
3.`swift -A http://localhost:8000/auth -U test:tester -K testing upload mycontainer ceph` (worked fine)

Now I implement jaeger tracing in /src/librados/IoCtxImpl.cc,
Now everything is working fine except for step 3: above
Error message : 
```
Warning: failed to create container 'mycontainer': HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /swift/v1/mycontainer (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3409f45150>: Failed to establish a new connection: [Errno 111] Connection refused',))
HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /auth (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3409f28e50>: Failed to establish a new connection: [Errno 111] Connection refused',))
```
JaegerTracing implemented part : 
```
oid librados::IoCtxImpl::queue_aio_write(AioCompletionImpl *c)
{
  std::cout<<"yes"<<std::endl;
    JTracer tracer;
    tracer.initTracer("Writing Started","/home/abhinav/Desktop/GSOC/deepika/ceph/src/librados/tracerConfig.yaml");
    Span span=tracer.newSpan("writing started");
    span->Finish();
    // try{
    //   auto yaml = YAML::LoadFile("/home/abhinav/Desktop/GSOC/deepika/ceph/src/librados/tracerConfig.yaml");
    // }catch(const YAML::ParserException& pe){
    //   // ldout<<pe.what()<<dendl;
    //   std::cout<<pe.what()<<std::endl;
    //   ofstream f;
    //   f.open("/home/abhinav/Desktop/err.txt");
    //   f<<pe.what();
    //   f.close();
    // }
      // auto config = jaegertracing::Config::parse(yaml);
    // auto tracer=jaegertracing::Tracer::make(
    //     "Writing",
    //     config,
    //     jaegertracing::logging::consoleLogger()
    // );
    // opentracing::Tracer::InitGlobal(
    //     static_pointer_cast<opentracing::Tracer>(tracer)
    // );
    // auto span = opentracing::Tracer::Global()->StartSpan("Span1");
    get();
    ofstream file;
    file.open("/home/abhinav/Desktop/write.txt",std::ios::out | std::ios::app);
    file<<"Writing /src/librados/IoCtxImpl.cc 310.\n";
    file.close();
    std::scoped_lock l{aio_write_list_lock};
    ceph_assert(c->io == this);
    c->aio_write_seq = ++aio_write_seq;
    ldout(client->cct, 20) << "queue_aio_write " << this << " completion " << c
        << " write_seq " << aio_write_seq << dendl;
    aio_write_list.push_back(&c->aio_write_list_item);
    // opentracing::Tracer::Global()->Close();
}
```
