### ISSUE TITLE
grafana dashboards not installed causing grafana crash loop

### ISSUE THREAD

**Issue by pcuzner** [ceph/ceph-ansible#4080]
In the ceph-grafana role https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-grafana/tasks/configure_grafana.yml#L9 skips the deployment of the dashboards when containerized_deployment is true. In my case I'm using containerized_deployment=true, since I want all ceph daemons to be container based.

Without the dashboards grafana fails to initialize since it has a provisioning entry for a directory that doesn't exist (/etc/grafana/dashboards is installed by the ceph-grafana-dashboards package)

group_vars:
---
ceph_origin: repository
ceph_repository: community
ceph_stable_release: nautilus
ceph_version_num: 14
cluster_network: 10.90.90.0/24
containerized_deployment: true
dashboard_enabled: true
docker_pull_timeout: 600s
ip_version: ipv4
monitor_address_block: 10.90.90.0/24
public_network: 10.90.90.0/24
radosgw_address_block: 10.90.90.0/24

**Environment**:
- CentOS7 hosts
- docker 
- ansible 2.8
- ceph-ansible - master

**Comment by guits** [comment]
@pcuzner 

> In the ceph-grafana role https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-grafana/tasks/configure_grafana.yml#L9 skips the deployment of the dashboards when containerized_deployment is true. In my case I'm using containerized_deployment=true, since I want all ceph daemons to be container based.
> 
> Without the dashboards grafana fails to initialize since it has a provisioning entry for a directory that doesn't exist (/etc/grafana/dashboards is installed by the ceph-grafana-dashboards package)

This should be fixed by https://github.com/ceph/ceph/pull/26415

**Comment by pcuzner** [comment]
@guits should we close this once @zmc does the backport to Nautilus - so there is visibility to others trying to install?

**Comment by guits** [comment]
@pcuzner sure, thanks for taking care of this!

**Comment by b-ranto** [comment]
btw: This is a nautilus back-port: https://github.com/ceph/ceph/pull/28635

**Comment by guits** [comment]
closing it since the backport has been merged
