### ISSUE TITLE
Dashboard success message points to wrong host

### ISSUE THREAD

**Issue by pcuzner** [ceph/ceph-ansible#4081]
When the final ceph-dashboard role executes it uses a hosts parameter that picks up the grafana-server group. 
https://github.com/ceph/ceph-ansible/blob/d0840217f3e8ffd3fe9d45fbd41b60444b70a290/site-container.yml.sample#L547

This means that instead of a link to the dashboard in the output, you get a link to the grafana server which yields this;
e.g The dashboard has been deployed! You can access your dashboard web UI at  http://nautilus-metrics.storage.lab:8234/  as an 'admin' user with 'admin' password.

In the above example nautilus-metrics is my grafana host not a mgr host that is running the dashboard

**Comment by guits** [comment]
@pcuzner could you share your inventory please?

**Comment by pcuzner** [comment]
Hi @guits here's the ansible inventory
`all:
  children:
    grafana-server:
      hosts:
        nautilus-metrics: null
    mdss:
      hosts:
        nautilus-2: null
    mgrs:
      hosts:
        nautilus-1: null
        nautilus-2: null
        nautilus-3: null
    mons:
      hosts:
        nautilus-1: null
        nautilus-2: null
        nautilus-3: null
    osds:
      hosts:
        nautilus-1: null
        nautilus-2: null
        nautilus-3: null
    rgws:
      hosts:
        nautilus-1: null
`

**Comment by b-ranto** [comment]
Yes, we shouldn't use `groups["grafana-server"][0]`. The ceph-dashboard role is meant to be run on ceph-mgr node (or fall-back to ceph-mon if ceph-mgr nodes were not defined).

**Comment by guits** [comment]
fixed by #4107
