### ISSUE TITLE
dashboards not embedding in mgr/dashboard with grafana >= 6.2

### ISSUE THREAD

**Issue by pcuzner** [ceph/ceph-ansible#4084]
Grafana has introduced clickjacking protection and added a allow_embedding option to grafana.ini (v6.2). The default is false. Without setting this to true, all embedded dashboards fail to load in mgr/dashboard UI due to a default header from grafana containing - X-Frame-Options = deny

refer to https://grafana.com/docs/installation/configuration/#allow-embedding

**Comment by sebastien-prudhomme** [comment]
@dsavineau @guits Is it possible to also update the documentation here: https://github.com/ceph/ceph/blob/master/doc/mgr/dashboard.rst

**Comment by dsavineau** [comment]
@sebastien-prudhomme this isn't related to ceph/ceph and mgr/dashboard.
The change was about grafana settings.

**Comment by sebastien-prudhomme** [comment]
@dsavineau As the doc give instructions about how to configure Grafana (anonymous mode, plugins, dashboards, https mode because of iframe) i find it will be useful to add that.
