### ISSUE TITLE
ceph-mon fail at "copy keys to the ansible server"

### ISSUE THREAD

**Issue by xahare** [ceph/ceph-ansible#410]
ceph-ansible version:
commit 2c01567a4f0016aa5a0762c871f479ff40689fcf
Date:   Mon Sep 21 18:29:20 2015 +0200

when trying this on 3 dells with a stock, updated ubuntu 14.04 lts. they used to run ceph giant. 

heres a typescript of the ansible run and the vars used. https://gist.github.com/xahare/d67078edd88cd6eb6c60

the problem seems to start at line 3002:

[0;31mfailed: [ceph1] => (item=/var/lib/ceph/bootstrap-rgw/ceph.keyring) => {"checksum": "da39a3ee5e6b4b0d3255bfef95601890afd80709", "dest": "/void/pixel/ansible/westcoastdata/fetch/6AAABE05-8E3A-476F-B55C-6F5AACC342AC/var/lib/ceph/bootstrap-rgw/ceph.keyring", "failed": true, "file": "/var/lib/ceph/bootstrap-rgw/ceph.keyring", "item": "/var/lib/ceph/bootstrap-rgw/ceph.keyring", "md5sum": "d41d8cd98f00b204e9800998ecf8427e", "remote_checksum": "074703eeaa1b4288e19ed432437d211683620140", "remote_md5sum": null}[0m
[0;31mmsg: checksum mismatch[0m

cant reproduce this on vmware or virtualbox.

**Comment by leseb** [comment]
Hum could it be an underlying problem? Like a fs issue or something.
If you calculate the md5 manually what do you get?

**Comment by xahare** [comment]
wrote a script to generate preseeded ubuntu isos to make sure all the nodes were the same and reinstalled on all the nodes. maybe a hardware problem? any ideas on how to look? threw a couple ceph command after the 2nd run on the end. this time it thinks it worked, but im still skeptical.

as before, everything was fine on vmware. heres the same section this time. had to take the /usr/sbin/ off sgdisk in the purge playbook for that work. manually running after the playbook, they all had the same md5sum.

failed: [ceph1] => (item=/etc/ceph/ceph.client.admin.keyring) => {"checksum": "da39a3ee5e6b4b0d3255bfef95601890afd80709", "dest": "/void/pixel/ansible/westcoastdata/fetch/FC8DE193-85F2-4CBE-ADAA-64BE1C6D4231/etc/ceph/ceph.client.admin.keyring", "failed": true, "file": "/etc/ceph/ceph.client.admin.keyring", "item": "/etc/ceph/ceph.client.admin.keyring", "md5sum": "d41d8cd98f00b204e9800998ecf8427e", "remote_checksum": "f285ddf1405bee8d983b5fe356be90ab2b068587", "remote_md5sum": null}
msg: checksum mismatch
changed: [ceph3] => (item=/etc/ceph/ceph.client.admin.keyring)
changed: [ceph2] => (item=/etc/ceph/ceph.client.admin.keyring)
ok: [ceph2] => (item=/var/lib/ceph/bootstrap-osd/ceph.keyring)
changed: [ceph1] => (item=/var/lib/ceph/bootstrap-osd/ceph.keyring)
changed: [ceph3] => (item=/var/lib/ceph/bootstrap-osd/ceph.keyring)
ok: [ceph3] => (item=/var/lib/ceph/bootstrap-rgw/ceph.keyring)
changed: [ceph2] => (item=/var/lib/ceph/bootstrap-rgw/ceph.keyring)
changed: [ceph1] => (item=/var/lib/ceph/bootstrap-rgw/ceph.keyring)
changed: [ceph3] => (item=/var/lib/ceph/bootstrap-mds/ceph.keyring)
failed: [ceph2] => (item=/var/lib/ceph/bootstrap-mds/ceph.keyring) => {"checksum": "da39a3ee5e6b4b0d3255bfef95601890afd80709", "dest": "/void/pixel/ansible/westcoastdata/fetch/FC8DE193-85F2-4CBE-ADAA-64BE1C6D4231/var/lib/ceph/bootstrap-mds/ceph.keyring", "failed": true, "file": "/var/lib/ceph/bootstrap-mds/ceph.keyring", "item": "/var/lib/ceph/bootstrap-mds/ceph.keyring", "md5sum": "d41d8cd98f00b204e9800998ecf8427e", "remote_checksum": "6490de4d4e14223e04ec3bf5486dd93a8595d2a8", "remote_md5sum": null}
msg: checksum mismatch
changed: [ceph1] => (item=/var/lib/ceph/bootstrap-mds/ceph.keyring)

ansible ceph -a "md5sum /etc/ceph/ceph.client.admin.keyring"
ceph2 | success | rc=0 >>
f7a0564d79305667b7e405ddad1da75a  /etc/ceph/ceph.client.admin.keyring
ceph1 | success | rc=0 >>
f7a0564d79305667b7e405ddad1da75a  /etc/ceph/ceph.client.admin.keyring
ceph3 | success | rc=0 >>
f7a0564d79305667b7e405ddad1da75a  /etc/ceph/ceph.client.admin.keyring

after running the playbook again, the same section acts like it worked the first time.
ok: [ceph2] => (item=/etc/ceph/ceph.client.admin.keyring)
ok: [ceph1] => (item=/etc/ceph/ceph.client.admin.keyring)
ok: [ceph3] => (item=/etc/ceph/ceph.client.admin.keyring)
ok: [ceph2] => (item=/var/lib/ceph/bootstrap-osd/ceph.keyring)
ok: [ceph3] => (item=/var/lib/ceph/bootstrap-osd/ceph.keyring)
ok: [ceph1] => (item=/var/lib/ceph/bootstrap-osd/ceph.keyring)
ok: [ceph2] => (item=/var/lib/ceph/bootstrap-rgw/ceph.keyring)
ok: [ceph3] => (item=/var/lib/ceph/bootstrap-rgw/ceph.keyring)
ok: [ceph1] => (item=/var/lib/ceph/bootstrap-rgw/ceph.keyring)
ok: [ceph2] => (item=/var/lib/ceph/bootstrap-mds/ceph.keyring)
ok: [ceph3] => (item=/var/lib/ceph/bootstrap-mds/ceph.keyring)
ok: [ceph1] => (item=/var/lib/ceph/bootstrap-mds/ceph.keyring)

$ ansible ceph1 -a "ceph -s"
ceph1 | success | rc=0 >>
    cluster fc8de193-85f2-4cbe-adaa-64be1c6d4231
     health HEALTH_WARN
            too few PGs per OSD (10 < min 30)
     monmap e1: 3 mons at {ceph1=10.1.10.31:6789/0,ceph2=10.1.10.32:6789/0,ceph3=10.1.10.33:6789/0}
            election epoch 6, quorum 0,1,2 ceph1,ceph2,ceph3
     osdmap e85: 18 osds: 18 up, 18 in
      pgmap v169: 64 pgs, 1 pools, 0 bytes data, 0 objects
            620 MB used, 66849 GB / 66850 GB avail
                  64 active+clean

$ ansible ceph1 -a "ceph osd tree"
ceph1 | success | rc=0 >>
ID WEIGHT   TYPE NAME      UP/DOWN REWEIGHT PRIMARY-AFFINITY 
-1 65.33981 root default                                     
-2 21.77994     host ceph3                                   
 0  3.62999         osd.0       up  1.00000          1.00000 
 1  3.62999         osd.1       up  1.00000          1.00000 
 2  3.62999         osd.2       up  1.00000          1.00000 
 3  3.62999         osd.3       up  1.00000          1.00000 
 4  3.62999         osd.4       up  1.00000          1.00000 
 5  3.62999         osd.5       up  1.00000          1.00000 
-3 21.77994     host ceph1                                   
 6  3.62999         osd.6       up  1.00000          1.00000 
 8  3.62999         osd.8       up  1.00000          1.00000 
11  3.62999         osd.11      up  1.00000          1.00000 
13  3.62999         osd.13      up  1.00000          1.00000 
15  3.62999         osd.15      up  1.00000          1.00000 
17  3.62999         osd.17      up  1.00000          1.00000 
-4 21.77994     host ceph2                                   
 7  3.62999         osd.7       up  1.00000          1.00000 
 9  3.62999         osd.9       up  1.00000          1.00000 
10  3.62999         osd.10      up  1.00000          1.00000 
12  3.62999         osd.12      up  1.00000          1.00000 
14  3.62999         osd.14      up  1.00000          1.00000 
16  3.62999         osd.16      up  1.00000          1.00000

**Comment by mattt416** [comment]
Oddly I just started seeing this also.  Could this not be a race condition w/ multiple MONs trying to write the same local file on the deployment host at the same time?  Perhaps we can update this code:

```
- name: copy keys to the ansible server
  fetch:
    src: "{{ item }}"
    dest: "{{ fetch_directory }}/{{ fsid }}/{{ item }}"
    flat: yes
  with_items:
    - "{{ ceph_keys.stdout_lines }}"
    - /var/lib/ceph/bootstrap-osd/ceph.keyring
    - /var/lib/ceph/bootstrap-rgw/ceph.keyring
    - /var/lib/ceph/bootstrap-mds/ceph.keyring
  when: cephx
```

... to use `flat: no` instead?  That way, each MON will write to a unique location rather than them all stamping on the same file at (potentially) the same time.

Thoughts?

**Comment by leseb** [comment]
@mattt416 I like this idea, just need to make sure that this won't break the fetch sequence afterwards.

**Comment by mattt416** [comment]
@leseb Yeah that could work but perhaps adding a `run_once` to the task will be simpler?  I'll need to test and report back.

**Comment by leseb** [comment]
@mattt416 if you have time yes, it will be nice to test that out as well :).
