### ISSUE TITLE
pool_default_pg_num ignored? set wrong?

### ISSUE THREAD

**Issue by xahare** [ceph/ceph-ansible#411]
after running the playbook (twice, see last comment) the pgmap says only 64 pgs, but i set 
pool_default_pg_num: 800
pool_default_pgp_num: 800
pool_default_size: 3
pool_default_min_size: 2

ceph1 | success | rc=0 >>
    cluster fc8de193-85f2-4cbe-adaa-64be1c6d4231
     health HEALTH_WARN
            too few PGs per OSD (10 < min 30)
     monmap e1: 3 mons at {ceph1=10.1.10.31:6789/0,ceph2=10.1.10.32:6789/0,ceph3=10.1.10.33:6789/0}
            election epoch 6, quorum 0,1,2 ceph1,ceph2,ceph3
     osdmap e85: 18 osds: 18 up, 18 in
      pgmap v169: 64 pgs, 1 pools, 0 bytes data, 0 objects
            620 MB used, 66849 GB / 66850 GB avail
                  64 active+clean

**Comment by xahare** [comment]
in /etc/ceph.conf, its set right, so i dont think this is related to the playbook.

  osd pool default pg num = 800
  osd pool default pgp num = 800
  osd pool default size = 3
  osd pool default min size = 2
  osd pool default crush rule = 0

**Comment by leseb** [comment]
I think it's somehow related to ceph, during bootstrap default pools seem to be populated with default values and don't honour the config set in ceph.conf (just an assumption)

**Comment by xahare** [comment]
seems so. 
root@ceph2:~# ceph osd pool delete rbd rbd --yes-i-really-really-mean-it
root@ceph2:~# ceph osd pool create rbd 800
pool 'rbd' created
root@ceph2:~# ceph osd lspools
1 rbd,
root@ceph2:~# ceph osd pool get rbd pgp_num
pgp_num: 800
root@ceph2:~# ceph osd pool get rbd pg_num
pg_num: 800
root@ceph2:~# ceph osd pool get rbd size
size: 3
