### ISSUE TITLE
add role for haproxy in front of dashboard

### ISSUE THREAD

**Issue by hoerup** [ceph/ceph-ansible#4178]
since the dashboard can reside on any of the mgr nodes, create a haproxy that knows how to direct traffic to the current active mgr with dashboard

the check for active node can be something like :
```
    option httpchk GET /
    http-check expect status 200
```

**Comment by dsavineau** [comment]
The current workflow only deploys the dashboard on one mgr node not multiple.

**Comment by hoerup** [comment]
grafana and prometheus are only installed on single node, but mgr-dashboard is installed on all mgr nodes and enabled on all mgr's  for mgr service failover

**Comment by hoerup** [comment]
Please see https://tracker.ceph.com/issues/24662 as well

If dashboard+grafana is setup then dashboard should be configured to have grafana endpoint pointing at proxy
