### ISSUE TITLE
bug: cant resolve grafana server

### ISSUE THREAD

**Issue by hoerup** [ceph/ceph-ansible#4182]
using ceph-ansible: head @ stable-4.0 

```
fatal: [dspv-cephmgmt01]: FAILED! => 
  msg: |-
    The task includes an option with an undefined variable. The error was: No first item, sequence was empty.
  
    The error appears to be in '/home/cephadm/ceph-ansible/roles/ceph-facts/tasks/facts.yml': line 306, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
    - name: set grafana_server_addr fact - ipv4
^ here

```
my hosts.ini contains

[grafana-server]
dspv-cephmgmt01

the code before this commits works fine
https://github.com/ceph/ceph-ansible/commit/366b309c12adfcef7dba3548ad3f05000148e867

**Comment by guits** [comment]
@hoerup can you provide full group_vars/ content, inventory, playbook logs ...

please, always provide these details when opening an issue, although there's a note about that in the bug report template we keep asking for them again and again...

**Comment by hoerup** [comment]
This was at a customer, so I can't provide the files. Tried to replicate on my lab env, but no luck
