### ISSUE TITLE
rolling upgrade disables mgr modules

### ISSUE THREAD

**Issue by hoerup** [ceph/ceph-ansible#4186]
zabbix module was enabled before doing a rolling upgrade. After rolling-upgrade.yml the zabbix modules is listed as disabled.

**Comment by dsavineau** [comment]
please provide full ansible log, inventory and variables in group_vars/*.yml files.

**Comment by hoerup** [comment]
i don't think we added zabbix module to mgrs.yml. Is it expected behaviour for the playbooks to disable any modules that aren't enabled in config (eg disable manually enabled modules) ?

**Comment by guits** [comment]
> i don't think we added zabbix module to mgrs.yml. Is it expected behaviour for the playbooks to disable any modules that aren't enabled in config (eg disable manually enabled modules) ?

yes it is

**Comment by hoerup** [comment]
perfect. then there's nothing wrong after all.
