### ISSUE TITLE
setup selinux for device monitoring

### ISSUE THREAD

**Issue by hoerup** [ceph/ceph-ansible#4187]
even though sudoers is configured for usage with device management, the call is still blocket by selinux.

Using: nautilus 14.2.1 
ceph-ansible latest @ stable-4.0
Centos 7

**Comment by dsavineau** [comment]
please provide full ansible log, inventory and variables in group_vars/*.yml files.

**Comment by hoerup** [comment]
I think this should be allowed in ceph-selinux. Opened http://tracker.ceph.com/issues/40683 instead
