### ISSUE TITLE
Error when adding a new server with add-osd.yml

### ISSUE THREAD

**Issue by jeevadotnet** [ceph/ceph-ansible#4216]
What happened:
```
TASK [set noup flag] ***************************************************************************************************************************************
Wednesday 10 July 2019  13:11:49 +0200 (0:00:00.156)       0:01:50.326 ********
fatal: [B-01-05-cephosd.maas -> B-03-11-cephctl.maas]: FAILED! => {"changed": false, "cmd": ["docker", "exec", "ceph-mon-B-03-11-cephctl", "ceph", "--cluster", "ceph", "osd", "set", "noup"], "delta": "0:00:00.042578", "end": "2019-07-10 11:11:49.423061", "msg": "non-zero return code", "rc": 126, "start": "2019-07-10 11:11:49.380483", "stderr": "", "stderr_lines": [], "stdout": "OCI runtime state failed: exec: \"docker-runc\": executable file not found in $PATH: : unknown", "stdout_lines": ["OCI runtime state failed: exec: \"docker-runc\": executable file not found in $PATH: : unknown"]}

NO MORE HOSTS LEFT *****************************************************************************************************************************************

PLAY RECAP *************************************************************************************************************************************************
B-01-05-cephosd.maas       : ok=33   changed=0    unreachable=0    failed=1
```

What you expected to happen:
1) I deploy a new server from MAAS, exactly the same way as our other ceph nodes.
2) From my management `/opt/ceph-ansible` box I run
`ansible-playbook -i inventory --limit B-01-05-cephosd.maas add-osd.yml`
Output:
http://pastefile.fr/04b8a5d2704665b55f76e1615a5eba0e

How to reproduce it (minimal and precise):
Don't know how to reproduce, just trying to bring another osd node into the cluster

VARS
combined
http://pastefile.fr/1562bec4cd11bbda1919bb94189e00ea

all.yml
http://pastefile.fr/9dbe6e39f6fbeff40b689847a44dfc4d

docker-commons.yml
http://pastefile.fr/cdb7b05cd367f7073aa4de41f0c2451a

mdss.yml
http://pastefile.fr/402e6b7a0afbe0a3435a40710caff366

mgrs.yml
http://pastefile.fr/7d1ba1ac33e5a4c37d6585843da97861

mons.yml
http://pastefile.fr/96b2d01798eadd0a2667adf1a8b136d1

osds.yml
http://pastefile.fr/8ae120a5a2a952af70cdf63ec0e269f1

inventory
http://pastefile.fr/85345bbb6cf0b96703759c783bede579
B-01-05-cephosd.maas wasn't previously in/or part of the cluster - this is what I'm trying to add in.

**Environment**:
* OS (e.g. from /etc/os-release):
`NAME="Ubuntu" VERSION="16.04.6 LTS (Xenial Xerus)`
* Kernel (e.g. `uname -a`):
`Linux sentry 4.4.0-130-generic #156-Ubuntu SMP Thu Jun 14 08:53:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
* Docker version if applicable (e.g. `docker version`):
* Ansible version (e.g. `ansible-playbook --version`):
`ansible-playbook 2.5.15`
* ceph-ansible version (e.g. `git head or tag or stable branch`):
`ref: refs/heads/stable-3.2`
* Ceph version (e.g. `ceph -v`):
`ceph version 12.2.12`

**Comment by guits** [comment]
valid bug, this happens when an osd node has never been deployed previously, the role ceph-docker-common is called after that failing task.

**Comment by dsavineau** [comment]
@guits stable-3.2 branch isn't supposed to support jewel right?

**Comment by guits** [comment]
@dsavineau i think it's a typo/mistake, he's well deploying luminous afaik

**Comment by jeevadotnet** [comment]
I'm using site-docker.yml and the playbook runs 100% with no issues. However the containers on the new node I'm trying to bring into the ceph cluster constantly restarts.

http://pastefile.fr/a0718d58cb599fb7822537e35cc1fc5d

**Comment by dsavineau** [comment]
It seems that the OSD already exist but the keyring isn't the same
`Error EEXIST: entity osd.198 exists but key does not match`

**Comment by jeevadotnet** [comment]
Yes that part I saw, but this is a new server/node I'm trying to bring into the cluster. How would one do it then since it seems like site-docker.yml nor add-osd.yml does the job correctly.

**Comment by jeevadotnet** [comment]
I manually added the fetch location in `all.yml` since the details in `/opt/ceph-ansible/fetch` looks correct

**Comment by jeevadotnet** [comment]
Added the `fsid: "xxxxxxxx-xxxxxxxxxxx-xxxxxxxx-xxxx"` and `generated_fsid; false` to `all.yml`

**Comment by jeevadotnet** [comment]
i found ceph auth now
`ceph auth del osd.198` seems to be doing the trick.

**Comment by jeevadotnet** [comment]
Okay i've manually `ceph auth del osd.198 -> osd.215` and all the containers came up stable on the new node & part of the cluster now
