### ISSUE TITLE
Prometheus and Grafana URLs not configured

### ISSUE THREAD

**Issue by ayaseen** [ceph/ceph-ansible#4221]
**Bug Report**

What happened:
Install ceph with dashboard enable, Prometheus and Grafana URLs are not configured either firewall ports.

What you expected to happen:

fully-worked dashboard

How to reproduce it (minimal and precise):
I ran ansible-playbook  site.yml with dashboard enabled in all.yml 

**The following two steps fix the issues:

1. I enable Permotheus and Grafan manually, and enable firewall ports:

2.  ceph dashboard set-grafana-api-url http://ceph01.rhlab.dev:3000**

**Environment**: 
* OS (e.g. from /etc/os-release): CentOs 7

* Ansible version (e.g. `ansible-playbook --version`):
ansible-playbook 2.8.1
  config file = /root/ceph-ansible/ansible.cfg
  configured module search path = [u'/root/ceph-ansible/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Jun 20 2019, 20:27:34) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

* ceph-ansible version (e.g. `git head or tag or stable branch`): master

* Ceph version (e.g. `ceph -v`): ceph version 14.2.1 (d555a9489eb35f84f2e1ef49b77e19da9d113972) nautilus (stable)

**Comment by dsavineau** [comment]
please share your ansible log, inventory and variables defined in group_vars/*.yml

note that this should be already be done by https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-infra/tasks/configure_firewall.yml#L167-L214

**Comment by ayaseen** [comment]
Output of all.yml file
---

fetch_directory: ~/ceph-ansible-keys
configure_firewall: True
ceph_mon_firewall_zone: public
ceph_mgr_firewall_zone: public
ceph_osd_firewall_zone: public
ceph_rgw_firewall_zone: public
ceph_mds_firewall_zone: public
ceph_nfs_firewall_zone: public
ceph_rbdmirror_firewall_zone: public
ceph_iscsi_firewall_zone: public
ceph_dashboard_firewall_zone: public
ceph_rgwloadbalancer_firewall_zone: public
ceph_conf_local: true

centos_package_dependencies:
  - epel-release
  - libselinux-python
ntp_service_enabled: true
upgrade_ceph_packages: True
ceph_repository: community
ceph_mirror: http://download.ceph.com
ceph_stable_key: https://download.ceph.com/keys/release.asc
ceph_stable_release: nautilus

rbd_cache: "true"
rbd_cache_writethrough_until_flush: "true"
rbd_concurrent_management_ops: 20
rbd_client_log_path: /var/log/ceph
rbd_client_log_file: "{{ rbd_client_log_path }}/qemu-guest-$pid.log" # must be writable by QEMU and allowed by SELinux or AppArmor
rbd_client_admin_socket_path: /var/run/ceph # must be writable by QEMU and allowed by SELinux or AppArmor


monitor_interface: eth0
public_network: 192.168.1.0/24
cluster_network: "{{ public_network | regex_replace(' ', '') }}"
osd_mkfs_type: xfs
osd_mkfs_options_xfs: -f -i size=2048
osd_mount_options_xfs: noatime,largeio,inode64,swalloc
osd_objectstore: bluestore
devices:
 - /dev/nvme0n1

ceph_conf_overrides:
 global:
   mon_osd_allow_primary_affinity: 1
   mon_clock_drift_allowed: 0.5
   osd_pool_default_size: 2
   osd_pool_default_min_size: 1
   mon_pg_warn_min_per_osd: 0
   mon_pg_warn_max_per_osd: 0
   mon_pg_warn_max_object_skew: 0
 client:
  rbd_default_features: 1

#############
# DASHBOARD #
#############
dashboard_enabled: True
dashboard_protocol: http
dashboard_port: 8234
dashboard_admin_user: admin
dashboard_admin_password: admin
node_exporter_container_image: prom/node-exporter:latest
grafana_admin_user: admin
grafana_admin_password: admin
grafana_container_image: "grafana/grafana:latest"
grafana_container_cpu_period: 100000
grafana_container_cpu_cores: 2
grafana_uid: 472
grafana_datasource: Dashboard
grafana_dashboards_path: "/etc/grafana/dashboards/ceph-dashboard"
grafana_plugins:
  - vonage-status-panel
  - grafana-piechart-panel
grafana_allow_embedding: True
prometheus_container_image: prom/prometheus:latest
prometheus_container_cpu_period: 100000
prometheus_data_dir: /var/lib/prometheus
prometheus_conf_dir: /etc/prometheus
prometheus_user_id: '65534'  # This is the UID used by the prom/prometheus container image
alertmanager_container_image: prom/alertmanager:latest
alertmanager_container_cpu_period: 100000
alertmanager_container_cpu_cores: 2
alertmanager_data_dir: /var/lib/alertmanager
alertmanager_conf_dir: /etc/alertmanager

**Comment by dsavineau** [comment]
FYI (but it shouldn't impact the issue), for nautilus release you should use the stable-4.0 branch or the v4.0.x tag instead of the master branch.

**Comment by ayaseen** [comment]
Yes, I have switched into stable-4.0, it's working fine.
Thanks
