### ISSUE TITLE
Unable to build a ceph-ansible environment

### ISSUE THREAD

**Issue by jeevadotnet** [ceph/ceph-ansible#4240]
**Bug Report**

What happened:
In our research live environment I've been unable to add a server to the existing ceph cluster - been trying for the last 3-4 weeks now (had some chats with Guits with this on IRC). I then went over to my test environment (12.2.7+ceph_ansible3.1 which was upgraded to 12.2.12 recently and upgraded to 3.2) and purged it.

I flushed git & hard stable-3.2 branch it as well to clear out everything not applicable. 

However when I build I get an issue which stops the build from happening:
output | http://pastefile.fr/e35049dd564745dcb1572eedee578df1

What you expected to happen:
To build successful as with stable-3.1 ceph ansible.

How to reproduce it (minimal and precise):
Purged the ceph-docker environment, so it is vanilla state except the group_vars, inventory & site-docker.yml

Share your group_vars files, inventory
all vars | http://pastefile.fr/6c6a6c8e3f963ea660fe9efe8cd48ad0
site-docker | http://pastefile.fr/c2730b6b32507fecd304a43327f2c46b
inventory | http://pastefile.fr/a0c8015a90b4515bff39c054a884d31d

**Environment**:
* OS (e.g. from /etc/os-release): `VERSION="16.04.6 LTS (Xenial Xerus)"`
* Kernel (e.g. `uname -a`): `4.15.0-47-generic #50~16.04.1-Ubuntu SMP Fri Mar 15 16:06:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
* Docker version if applicable (e.g. `docker version`): docker gets installed but install fails after that 
`Server:
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       2d0083d
  Built:            Mon Jul  1 19:31:53 2019
  OS/Arch:          linux/amd64
  Experimental:     false
`
* Ansible version (e.g. `ansible-playbook --version`):
`ansible-playbook 2.4.1.0
  config file = /opt/ceph-ansible/ansible.cfg
  configured module search path = [u'/opt/ceph-ansible/library']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]`
* ceph-ansible version (e.g. `git head or tag or stable branch`): `ref: refs/heads/stable-3.2`
* Ceph version (e.g. `ceph -v`): `12.2.12`

**Comment by dsavineau** [comment]
On a first thought it seems that you're still using the `site-docker.yml`playbook from stable-3.1
On stable-3.2 branch the `cluster_uuid` variable is defined in `ceph-facts` role which is not present in stable-3.1 (it was in `ceph-defaults` instead) [1] but added in stable-3.2 [2].

Could you test with the right version ? Also you shouldn't have to modify the playbook and comment the unused groups. They will be ignored if not defined in the ansible inventory.

Finally I can see that you're using ansible 2.4. On the stable-3.2 branch you should use ansible 2.6 [3]

[1] https://github.com/ceph/ceph-ansible/blob/stable-3.1/site-docker.yml.sample#L53
[2] https://github.com/ceph/ceph-ansible/blob/stable-3.2/site-docker.yml.sample#L55
[3] http://docs.ceph.com/ceph-ansible/master/#releases

**Comment by jeevadotnet** [comment]
Hi @dsavineau 

Thanks for the feedback.

I've git hard reset to ceph-ansible 3.2 and used the site-docker playbook that comes with it. (matched the contents of the URL you provided to make double sure it is correct).

I've upgraded ansible and it is now on version 2.8.2, up from 2.4.1.

When I run the `ansible-playbook -i inventory site-docker.yml` i get the following error straight from the bat off:
```ERROR! 'delegate_to' is not a valid attribute for a TaskInclude

The error appears to be in '/opt/ceph-ansible/roles/ceph-mon/tasks/main.yml': line 20, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: include secure_cluster.yml
  ^ here
```

**Comment by jeevadotnet** [comment]
Just tested again, with the details provided as above + changes:
Ansible - 2.6.0
Ceph-ansible 3.2.0 (hard reset)
Site-docker.yml , as is, from URL you provided

http://pastefile.fr/316e59524b0ba627f7a1a94266e7ec84

**Comment by jeevadotnet** [comment]
Okay I purged the docker cluster completely and ran the site-docker playbook again.
Seems like it went through but i must still confirm.

provisional logs: http://pastefile.fr/bf3b9360ac1f4bd3cd97b99a87876f7f

**Comment by jeevadotnet** [comment]
Great my testbed is working. Going to try add in a server in the production environment

**Comment by dsavineau** [comment]
Nice, If everything is fine then feel free to close the issue.
