### ISSUE TITLE
generate {{ cluster }}.conf configuration file Task is taking Long Long time on large cluster

### ISSUE THREAD

**Issue by kobigi** [ceph/ceph-ansible#4257]
**Bug Report**

What happened:
While we are deploying large environment (Actually not that large)
The ceph-ansible task that generates ceph.conf is taking too much time
and We end up with Deployment timeout.
Seems that almost 1 Minute for each compute that this task runs upon.
if we install 30 Computes (HCI) + 3 Controllers
for each compute we will have 1 Minute for Only 1 Task ending up with 30 Minutes.

What you expected to happen:
i expect this task and the general overall to be much faster and not taking me to Timeout of the deployment.

How to reproduce it (minimal and precise):
Deploy 3 Monitors and 30 Computes with tripleo , deploying ceph with ceph-ansible

Share your group_vars files, inventory

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`): 
Linux overcloud-controller-jerusalem-0 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Docker version if applicable (e.g. `docker version`):
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-96.gitb2f74b2.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      b2f74b2/1.13.1
 Built:           Wed May  1 14:55:20 2019
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-96.gitb2f74b2.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      b2f74b2/1.13.1
 Built:           Wed May  1 14:55:20 2019
 OS/Arch:         linux/amd64
 Experimental:    false

* Ansible version (e.g. `ansible-playbook --version`):
ansible-playbook 2.5.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible-playbook
  python version = 2.7.5 (default, Jun 20 2019, 20:27:34) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

* ceph-ansible version (e.g. `git head or tag or stable branch`):
|[root@undercloud (stackrc) ~]# rpm -qa | grep ceph-ans
ceph-ansible-3.1.6-1.el7.noarch

* Ceph version (e.g. `ceph -v`):
ceph version 12.2.8 (ae699615bac534ea496ee965ac6192cb7e0e07c0) luminous (stable)

**Comment by kobigi** [comment]
The relevant task that is taking very  long is:
File: /usr/share/ceph-ansible/roles/ceph-config/tasks/main.yml

  - name: "generate {{ cluster }}.conf configuration file"
    action: config_template
    args:
      src: "ceph.conf.j2"
      dest: "{{ ceph_conf_key_directory }}/{{ cluster }}.conf"
      owner: "root"
      group: "root"
      mode: "0644"
      config_overrides: "{{ ceph_conf_overrides }}"
      config_type: ini
    notify:
      - run ceph post
      - restart ceph mons
      - restart ceph osds
      - restart ceph mdss
      - restart ceph rgws
      - restart ceph mgrs
      - restart ceph rbdmirrors

Log file attached:

**Comment by dsavineau** [comment]
Please provides ansible logs, inventory and variables in group_vars/*.yml

Also I don't think this is coming from the `generate {{ cluster }}.conf configuration file` task itself because it's only a template generation so it shouldn't take a very long time (< 1s) but it's probably the handlers triggered by this task that could take some time.
Especially the `restart ceph osds` one because we have to restart all osds daemons **sequentially**

**Comment by kobigi** [comment]
[ceph_ansible_command.zip](https://github.com/ceph/ceph-ansible/files/3424362/ceph_ansible_command.zip)
Attaching teh ceph ansible log

**Comment by kobigi** [comment]
Also group vars + ceph .conf , 
please note this is tripleo deployment so the group_vars may have only default samples and some value are overrided from tripleo templates
Adding also resulting ceph.conf - to give the notion of the values being created.

Also Important , i did not notice any OSD's restart during this Actions being run , i would also suspects those actions and willing to have a run without this notifies to eliminate that if required.
[group_vars.tar.gz](https://github.com/ceph/ceph-ansible/files/3424375/group_vars.tar.gz)

[ceph.conf.txt](https://github.com/ceph/ceph-ansible/files/3424377/ceph.conf.txt)
