### ISSUE TITLE
[stable-4.0] firewalld issues on SLES 15

### ISSUE THREAD

**Issue by johanneskastl** [ceph/ceph-ansible#4263]
Firewalld cannot be configured, as the python module cannot be found, even though it is installed.

**Bug Report**

What happened:
```
TASK [ceph-infra : open monitor and manager ports] ******************************************************************************************************************************************
Tuesday 23 July 2019  18:08:13 +0000 (0:00:01.303)       0:00:42.185 ********** 
failed: [XXXhostnameXXX] (item={'service': 'ceph-mon', 'zone': 'public'}) => changed=false 
  ansible_loop_var: item
  item:
    service: ceph-mon
    zone: public
  msg: 'Python Module not found: firewalld and its python module are required for this module,                         version 0.2.11 or newer required (0.3.9 or newer for offline operations)'                
```

Those packages are installed:
```
# rpm -qa|grep firewall
python3-firewall-0.5.5-4.24.9.noarch
firewalld-0.5.5-4.24.9.noarch
```
```
# zypper info python3-firewall
Loading repository data...
Reading installed packages...


Information for package python3-firewall:
-----------------------------------------
Repository     : SLE-Module-Basesystem15-Updates 
Name           : python3-firewall                
Version        : 0.5.5-4.24.9                    
Arch           : noarch                          
Vendor         : SUSE LLC <https://www.suse.com/>
Support Level  : Level 3                         
Installed Size : 1.6 MiB                         
Installed      : Yes (automatically)             
Status         : up-to-date                      
Source package : firewalld-0.5.5-4.24.9.src      
Summary        : Python3 bindings for FirewallD  
Description    :                                 
    The python3 bindings for firewalld
```

What you expected to happen:
Ansible should be able to configure firewalld properly.

How to reproduce it (minimal and precise):
Run the site.yml playbook targeting a SLES15 SP0 server.
The responsible lines seem to be [here](https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-infra/tasks/configure_firewall.yml#L22).

**Environment**:
* OS : `SUSE Linux Enterprise Server 15`
* Kernel: `Linux XXXhostnameXXX 4.12.14-150.27-default #1 SMP Thu Jul 11 11:24:28 UTC 2019 (bf2abc2) x86_64 x86_64 x86_64 GNU/Linux`
* Ansible version (e.g. `ansible-playbook --version`): `2.8.2`
* ceph-ansible version (e.g. `git head or tag or stable branch`): both `stable-4.0` and `fac1b030cbc67a`

**Comment by dsavineau** [comment]
Are you sure that you're not still using the python2 ansible python interpreter ?

**Comment by johanneskastl** [comment]
Yes, at least to what I can see:

```
ansible --version

ansible 2.8.2
  config file = /home/tux/ceph-ansible/ansible.cfg
  configured module search path = ['/home/tux/ceph-ansible/library']
  ansible python module location = /home/tux/.venv/lib/python3.6/site-packages/ansible
  executable location = /home/tux/.venv/bin/ansible
  python version = 3.6.8 (default, Apr 30 2019, 13:27:23) [GCC]```

**Comment by johanneskastl** [comment]
Also, the only python executable in `/usr/bin` is python3-related:
```
# ll /usr/bin/python*
lrwxrwxrwx 1 root root     9 Mai 10 14:47 /usr/bin/python3 -> python3.6
-rwxr-xr-x 2 root root 10448 Mai 10 14:48 /usr/bin/python3.6
-rwxr-xr-x 2 root root 10448 Mai 10 14:48 /usr/bin/python3.6m
```

**Comment by dsavineau** [comment]
That's the python version used on the ansible controller not ont the Ceph ansible nodes.
Basically you can run:
```console
ansible -i hosts all -b -m setup -a 'filter=ansible_python'
```
And replace `hosts` by your ansible inventory path.

**Comment by johanneskastl** [comment]
This looks like python3 to me...

```
XXXhostnameXXX | SUCCESS => {
    "ansible_facts": {
        "ansible_python": {
            "executable": "/usr/bin/python3.6",
            "has_sslcontext": true,
            "type": "cpython",
            "version": {
                "major": 3,
                "micro": 8,
                "minor": 6,
                "releaselevel": "final",
                "serial": 0
            },
            "version_info": [
                3,
                6,
                8,
                "final",
                0
            ]
        },
        "discovered_interpreter_python": "/usr/bin/python3.6"
    },
    "changed": false
```

**Comment by dsavineau** [comment]
Well that doesn't seem to be a ceph-ansible issue then and more an ansible issue with the firewalld module on SLES 15.
From my point of view, your setup is correct (default py3 interpreter + py3 firewalld bindinds) so you should open an issue on ansible project.
According to the firewalld documentation (it might be outdated), the module requires the python2 bindings [1] even if you shouldn't. Maybe you could give it a try if python2-firewall is still available on SLES 15.

[1] https://github.com/ansible/ansible/blob/stable-2.8/lib/ansible/modules/system/firewalld.py#L100-L102

**Comment by johanneskastl** [comment]
Thanks, I'll try to find a solution and report back, in case this needs changes in ceph-ansible.

**Comment by dsavineau** [comment]
BTW I just tested one firewalld on RHEL 8 using python 3.6.8 (same than SLES 15) and it's working fine

```console
TASK [open monitor and manager ports] ********************************************************************************************************************************************************************************************************
Tuesday 23 July 2019  16:03:02 -0400 (0:00:02.860)       0:00:02.961 ********** 
changed: [xxxxx] => (item={'service': 'ceph-mon', 'zone': 'public'}) => changed=true 
  ansible_loop_var: item
  item:
    service: ceph-mon
    zone: public
  msg: Permanent and Non-Permanent(immediate) operation, Changed service ceph-mon to enabled, Permanent and Non-Permanent(immediate) operation, Added 192.168.100.0/24 to zone public
ok: [xxxxx] => (item={'service': 'ceph', 'zone': 'public'}) => changed=false 
  ansible_loop_var: item
  item:
    service: ceph
    zone: public
  msg: Permanent and Non-Permanent(immediate) operation, Changed service ceph to enabled, Permanent and Non-Permanent(immediate) operation
```

The only difference is the firewalld release (0.6.3 vs 0.5.5):

```console
# rpm -qa *firewall*
python3-firewall-0.6.3-7.el8.noarch
firewalld-filesystem-0.6.3-7.el8.noarch
firewalld-0.6.3-7.el8.noarch
```

**Comment by johanneskastl** [comment]
I also tested using a Leap 15.0 package of firewalld (SLES15 and Leap 15.0 are binary compatible), which was version 0.6.4, but this also failed.

To me this seems like an issue with the ansible firewalld module not detecting the module correctly.

**Comment by dsavineau** [comment]
I could be wrong but testing on Leap 15.0 in a container, I can see that the python release is 3.6.5 but you reported that the version was 3.6.8.
Do you know how we could have such difference in a release ?
Otherwise when re-reading the comments, tt seems that you're using a virtualenv for installing ansible. By chance, are you trying to apply a firewalld rule on the same host than the ansible controller ?
The virtualenv doesn't have the firewall bindings because it's not something available on pypi (that's the same thing for selinux).

**Comment by dsavineau** [comment]
I was have to run a firewalld task on Leap 15.1 without issue

```console
# rpm -qa *firewall*
python3-firewall-0.5.5-lp151.5.1.noarch
firewalld-0.5.5-lp151.5.1.noarch
# python3 --version
Python 3.6.5
```

So I don't think this is coming from ansible firewalld module too.

Could you explain a little bit more your setup:
  - OS running on the ansible controller and ceph nodes
  - python release available on the ansible controller and ceph nodes
  - etc...

**Comment by johanneskastl** [comment]
Hmmmm. Interesting.

My setup is having four nodes running SLES15 SP0 (not SP1!).

Yes, I was running ansible from a virtualenv, but not on the nodes that I tried to provision, only on the controller.

I'll try to test with SLES15 SP1 and report back.

**Comment by johanneskastl** [comment]
I could successfully deploy a ceph node on openSUSE Leap 15.0 and 15.1, using the modifications in #4276

I had lots of strange errors on SLES15 SP0, I will try to re-test this using SLES15 SP1. If the problem persists, I'll reopen this issue.

**Comment by johanneskastl** [comment]
Seems like some part of ceph-ansible installs packages that pull in python2.7, which makes `/usr/bin/python` point to Python2.7 suddenly, and the rest of the deployment fails due to that.
