### ISSUE TITLE
Enable ceph-dashboard by default

### ISSUE THREAD

**Issue by epuertat** [ceph/ceph-ansible#4269]
**Is your feature request related to a problem? Please describe.**
Currently Ceph-dashboard is disabled by default. As it's now a key component in Ceph it should be enabled by default. The target use case for this is RHCS, but also upstream would benefit from deploying ceph-dashboard by default. It would also promote adoption of dashboard within community.

**Describe the solution you'd like**
Change `dashboard_enabled` default from `False` to `True`. Additionally, Grafana service should run in a separate node, instead of collocated with ceph-mgr and ceph-dashboard (performance impacting deployment).

**Describe alternatives you've considered**
N/A.

**Additional context**
N/A.

**Comment by epuertat** [comment]
Downstream-only change: see https://github.com/ceph/ceph-ansible/pull/4268

**Comment by rishabh-d-dave** [comment]
This PR aims to accomplish the same request for the downstream part - https://github.com/ceph/ceph-ansible/pull/4268.

**Comment by guits** [comment]
fixed by #4268
