### ISSUE TITLE
Client Node uses V1 protocol

### ISSUE THREAD

**Issue by lz006** [ceph/ceph-ansible#4272]
**Bug Report**

What happened:
Ceph client fails when tryin to map rbd by using *rbd device map mypool/myimage1 --id admin -k /etc/ceph/ceph.client.admin.keyring* . (Only!) Sometimes it prints:
``` bash
rbd: sysfs write failed
In some cases useful info is found in syslog - try "dmesg | tail".
rbd: map failed: (110) Connection timed out
```
dmesg | tail brings:

``` bash
[62023.257916] libceph: mon0 172.21.21.217:3300 socket closed (con state CONNECTING)
[62024.283454] libceph: mon0 172.21.21.217:3300 socket closed (con state CONNECTING)
[62025.307529] libceph: mon0 172.21.21.217:3300 socket closed (con state CONNECTING)
[62029.274696] libceph: mon0 172.21.21.217:3300 socket closed (con state CONNECTING)
[62030.299610] libceph: mon0 172.21.21.217:3300 socket closed (con state CONNECTING)
[62031.259589] libceph: mon0 172.21.21.217:3300 socket closed (con state CONNECTING)
```

A look into log file /var/log/ceph/ceph-mon.mynode.log show:
``` bash
...-1 s=BANNER_ACCEPTING pgs=0 cs=0 l=0 rx=0 tx=0)._handle_peer_banner peer  is using msgr V1 protocol
...-1 s=BANNER_ACCEPTING pgs=0 cs=0 l=0 rx=0 tx=0)._handle_peer_banner peer  is using msgr V1 protocol
...-1 s=BANNER_ACCEPTING pgs=0 cs=0 l=0 rx=0 tx=0)._handle_peer_banner peer  is using msgr V1 protocol
...-1 s=BANNER_ACCEPTING pgs=0 cs=0 l=0 rx=0 tx=0)._handle_peer_banner peer  is using msgr V1 protocol
...-1 s=BANNER_ACCEPTING pgs=0 cs=0 l=0 rx=0 tx=0)._handle_peer_banner peer  is using msgr V1 protocol
...-1 s=BANNER_ACCEPTING pgs=0 cs=0 l=0 rx=0 tx=0)._handle_peer_banner peer  is using msgr V1 protocol
```

And to make it even more strange: When I try to map same rbd with same command and creds on a mon node it works just fine. Client and mon nodes have same same package version installed (2:14.2.2-0.el7 alias nautilus). 

What you expected to happen:
rbd device map to on client nodes like on mon nodes

How to reproduce it (minimal and precise):
Deploy ceph by using ceph-ansible "origin/stable-4.0" in conjunction with community repositories in all.yml then run
``` bash
# Create pool
ceph osd pool create mypool 50 50

# Enable pool
rbd pool init mypool

# Create image
rbd create mypool/myimage1 --size 1024

## Mounting on client side
rbd list mypool --user inst222
modprobe rbd
rbd feature disable mypool/myimage1 exclusive-lock object-map fast-diff deep-flatten --user inst222

## Mapping fails
rbd device map mypool/myimage1 --id inst222
```

Share your group_vars files, inventory
*Inventory*
[mons]
inst217

[osds]
inst218
inst219
inst220

[clients]
inst221
inst222

*group_vars/clients.yml*

copy_admin_key: true

**Environment**:
* OS (e.g. from /etc/os-release): Centos7
* Kernel (e.g. `uname -a`): 5.2.2-1.el7.elrepo.x86_64 *and* 3.10.0-957.1.3.el7.x86_64
* Docker version if applicable (e.g. `docker version`):
* Ansible version (e.g. `ansible-playbook --version`): 2.8.0
* ceph-ansible version (e.g. `git head or tag or stable branch`): origin/stable-4.0
* Ceph version (e.g. `ceph -v`): ceph version 14.2.2 (4f8fa0a0024755aae7d95567c63f11d6862d55be) nautilus (stable)

Hopefully someone could confirm this bug OR could bring me back on the right track.

Thanks in advance. cheers

**Comment by dsavineau** [comment]
I tested the same thing except that I ran the rbd command using the admin keyring and not inst222 id like you and everything was fine.

```console
### from the client node
# ceph osd pool create mypool 128 128
pool 'mypool' created
# rbd pool init mypool
# rbd create mypool/myimage1 --size 1024
# rbd list mypool
myimage1
# modprobe rbd
# rbd feature disable mypool/myimage1 exclusive-lock object-map fast-diff deep-flatten
# rbd device map mypool/myimage1
/dev/rbd0
```

Could you share more information about the ceph configuration and/or variables configured in group_vars/*.yml for ceph-ansible ?

On my side the ceph.conf is very light on the clients node and I'm using both v2 and v1 msgr protocols.

```console
# cat /etc/ceph/ceph.conf 
[client.libvirt]
admin socket = /var/run/ceph/$cluster-$type.$id.$pid.$cctid.asok # must be writable by QEMU and allowed by SELinux or AppArmor
log file = /var/log/ceph/qemu-guest-$pid.log # must be writable by QEMU and allowed by SELinux or AppArmor

# Please do not change this file directly since it is managed by Ansible and will be overwritten
[global]
cluster network = 192.168.100.0/24
fsid = 8dabd465-7762-41a1-9658-7aadf82273b6
mon host = [v2:192.168.100.15:3300,v1:192.168.100.15:6789]
public network = 192.168.100.0/24
```


The ceph version is the same than yours.

```console
# ceph --version
ceph version 14.2.2 (4f8fa0a0024755aae7d95567c63f11d6862d55be) nautilus (stable)
```

So the first thing I suggest is to try to executed the rbd command without the inst222.
Then if it doesn't change anything I would try to fallback to the main CentOS 7 kernel instead of the 5.2.2 you're using. Because we're using the rbd kernel module maybe the one in the latest kernel release isn't compatible with nautilus.

```console
# uname -r
3.10.0-957.21.3.el7.x86_64
```

**Comment by dsavineau** [comment]
Ok so it seems to come from the rbd command only using the msgr v1 and not v2.
In my case it was working because I configured both v2 and v1 so the client was talking to the mon on v1 (port 6789).
I've tried the same and disabled v1 in the configuration and I have now the same result.

```console
[client.libvirt]
admin socket = /var/run/ceph/$cluster-$type.$id.$pid.$cctid.asok # must be writable by QEMU and allowed by SELinux or AppArmor
log file = /var/log/ceph/qemu-guest-$pid.log # must be writable by QEMU and allowed by SELinux or AppArmor

# Please do not change this file directly since it is managed by Ansible and will be overwritten
[global]
cluster network = 192.168.100.0/24
fsid = 8dabd465-7762-41a1-9658-7aadf82273b6
mon host = [v2:192.168.100.15:3300]
public network = 192.168.100.0/24

# rbd device map mypool/myimage1
rbd: sysfs write failed
In some cases useful info is found in syslog - try "dmesg | tail".
rbd: map failed: (110) Connection timed out
```

And dmesg fooding with:
```console
[ 7225.664822] libceph: mon0 192.168.100.15:3300 socket closed (con state CONNECTING)
[ 7226.664789] libceph: mon0 192.168.100.15:3300 socket closed (con state CONNECTING)
[ 7227.670899] libceph: mon0 192.168.100.15:3300 socket closed (con state CONNECTING)
[ 7228.664864] libceph: mon0 192.168.100.15:3300 socket closed (con state CONNECTING)
[ 7229.664784] libceph: mon0 192.168.100.15:3300 socket closed (con state CONNECTING)
[ 7230.670912] libceph: mon0 192.168.100.15:3300 socket closed (con state CONNECTING)
[ 7231.664907] libceph: mon0 192.168.100.15:3300 socket closed (con state CONNECTING)
[ 7232.664931] libceph: mon0 192.168.100.15:3300 socket closed (con state CONNECTING
```

Even if the v2 port is reachable
```console
# telnet 192.168.100.15 3300
Trying 192.168.100.15...
Connected to 192.168.100.15.
Escape character is '^]'.
ceph v2
```

So I don't really know if it's coming from the rbd command, rbd kernel module or something missing in the configuration (I doubt)

**Comment by dsavineau** [comment]
It doesn't seem to be supported in the ceph-client code [1]. But I'm not 100% sure.
I didn't see any reference to msgr v2 in the code.
So it will be better to ask this on the ceph ML or open an issue on the ceph tracker [2] to be honest.

[1] https://github.com/ceph/ceph-client/blob/for-linus/include/linux/ceph/msgr.h
[2] https://tracker.ceph.com/projects/ceph

**Comment by lz006** [comment]
hi Drmitri,
I'm glad hearing from you. My configuration is absolute the same as yours.

I'm out of ideas why client is using v1 even though both are configured.

Is there any way to come closer to whaz is causing this issue?

br
lu

On 26 July 2019 21:38:03 CEST, Dimitri Savineau <notifications@github.com> wrote:
>Ok so it seems to come from the rbd command only using the msgr v1 and
>not v2.
>In my case it was working because I configured both v2 and v1 so the
>client was talking to the mon on v1 (port 6789).
>I've tried the same and disabled v1 in the configuration and I have now
>the same result.
>
>```console
>[client.libvirt]
>admin socket = /var/run/ceph/$cluster-$type.$id.$pid.$cctid.asok # must
>be writable by QEMU and allowed by SELinux or AppArmor
>log file = /var/log/ceph/qemu-guest-$pid.log # must be writable by QEMU
>and allowed by SELinux or AppArmor
>
># Please do not change this file directly since it is managed by
>Ansible and will be overwritten
>[global]
>cluster network = 192.168.100.0/24
>fsid = 8dabd465-7762-41a1-9658-7aadf82273b6
>mon host = [v2:192.168.100.15:3300]
>public network = 192.168.100.0/24
>
># rbd device map mypool/myimage1
>rbd: sysfs write failed
>In some cases useful info is found in syslog - try "dmesg | tail".
>rbd: map failed: (110) Connection timed out
>```
>
>And dmesg fooding with:
>```console
>[ 7225.664822] libceph: mon0 192.168.100.15:3300 socket closed (con
>state CONNECTING)
>[ 7226.664789] libceph: mon0 192.168.100.15:3300 socket closed (con
>state CONNECTING)
>[ 7227.670899] libceph: mon0 192.168.100.15:3300 socket closed (con
>state CONNECTING)
>[ 7228.664864] libceph: mon0 192.168.100.15:3300 socket closed (con
>state CONNECTING)
>[ 7229.664784] libceph: mon0 192.168.100.15:3300 socket closed (con
>state CONNECTING)
>[ 7230.670912] libceph: mon0 192.168.100.15:3300 socket closed (con
>state CONNECTING)
>[ 7231.664907] libceph: mon0 192.168.100.15:3300 socket closed (con
>state CONNECTING)
>[ 7232.664931] libceph: mon0 192.168.100.15:3300 socket closed (con
>state CONNECTING
>```
>
>Even if the v2 port is reachable
>```console
># telnet 192.168.100.15 3300
>Trying 192.168.100.15...
>Connected to 192.168.100.15.
>Escape character is '^]'.
>ceph v2
>```
>
>So I don't really know if it's coming from the rbd command, rbd kernel
>module or something missing in the configuration (I doubt)
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ceph/ceph-ansible/issues/4272#issuecomment-515574865

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dsavineau** [comment]
That's probably because the client is still using the legacy v1 protocol and v2 isn't implemented but I'm not 100% sure, that's why's it should be a good idea to ask on the ceph ML and/or the ceph tracker.
BTW an easy workaround could be to activate both v2 + v1 on the monitor nodes.

**Comment by lz006** [comment]
hi, 

I've tried activating v2 on mon node without any effect unfortunately. I guess V1 doesn't need to be enabled because it's the default protocol, right?

As next step I'm going to try port forwarding from 3300 to 6789 on mon node. I'll report results here.

thank you very much dimitri!

br
lu

On 26 July 2019 22:32:01 CEST, Dimitri Savineau <notifications@github.com> wrote:
>That's probably because the client is still using the legacy v1
>protocol and v2 isn't implemented but I'm not 100% sure, that's why's
>it should be a good idea to ask on the ceph ML and/or the ceph tracker.
>BTW an easy workaround could be to activate both v2 + v1 on the monitor
>nodes.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ceph/ceph-ansible/issues/4272#issuecomment-515590102

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by lz006** [comment]
Ok, I got it working finally. It turned out that both ports 6789 as well as 3300 from mon nodes must be reachable. Ceph client requires communication that utilizes V2 **and** V1 of messenger protocol at the same time despite that in docs V1 is called "legacy" which is a misleading term in my eyes.

**Comment by lz006** [comment]
Opened issue at ceph issue tracker:
https://tracker.ceph.com/issues/40996?issue_count=1&issue_position=1
