### ISSUE TITLE
default values are not read

### ISSUE THREAD

**Issue by superxor** [ceph/ceph-ansible#4301]
fresh clone

if I try to setup a cluster I have to uncomment every line from site.yml because I get endless errors like:

The task includes an option with an undefined variable. The error was: 'docker_pull_timeout' is undefined

In this case I am not even using Docker and containerized_deployment is False.

Or what am I doing wrong here?

**Comment by dsavineau** [comment]
> if I try to setup a cluster I have to uncomment every line from site.yml because I get endless errors like:

What lines are you uncommented in the site.yml playbook ? Because you don't really need to modify this playbook.
Instead you need to create the group_vars files based on the samples files in that directory.

https://docs.ceph.com/ceph-ansible/master/#configuration

**Comment by superxor** [comment]
I moved all .sampe to .yml but I still get:

  msg: |-
    The conditional check 'containerized_deployment | bool' failed. The error was: error while evaluating conditional (containerized_deployment | bool): 'containerized_deployment' is undefined

**Comment by dsavineau** [comment]
Could you share :
  - the full ansible log
  - the ansible command used
  - the ansible version
  - the ceph-ansible version (branch, tag)

The default variables are initialized via the ceph-defaults role which is executed at the start of the playbook.

https://github.com/ceph/ceph-ansible/blob/master/site.yml.sample#L65-L66

**Comment by superxor** [comment]
not full but should suffice

> TASK [ceph-facts : set_fact monitor_name ansible_fqdn] *****************************************************
> Thursday 01 August 2019  15:49:13 +0200 (0:00:00.412)       0:00:12.126 ******* 
> skipping: [m1-1045558]
> skipping: [m2-1045557]
> skipping: [m3-1045556]
> 
> TASK [ceph-facts : set_fact container_exec_cmd] ************************************************************
> Thursday 01 August 2019  15:49:13 +0200 (0:00:00.290)       0:00:12.416 ******* 
> fatal: [m1-1045558]: FAILED! => 
>   msg: |-
>     The conditional check 'containerized_deployment | bool' failed. The error was: error while evaluating conditional (containerized_deployment | bool): 'containerized_deployment' is undefined
>   
>     The error appears to have been in '/home/xe/ceph-ansible/roles/ceph-facts/tasks/facts.yml': line 39, column 3, but may
>     be elsewhere in the file depending on the exact syntax problem.
>   
>     The offending line appears to be:
>   
>   
>     - name: set_fact container_exec_cmd
>       ^ here
> fatal: [m2-1045557]: FAILED! => 
>   msg: |-
>     The conditional check 'containerized_deployment | bool' failed. The error was: error while evaluating conditional (containerized_deployment | bool): 'containerized_deployment' is undefined
>   
>     The error appears to have been in '/home/xe/ceph-ansible/roles/ceph-facts/tasks/facts.yml': line 39, column 3, but may
>     be elsewhere in the file depending on the exact syntax problem.
>   
>     The offending line appears to be:
>   
>   
>     - name: set_fact container_exec_cmd
>       ^ here
> fatal: [m3-1045556]: FAILED! => 
>   msg: |-
>     The conditional check 'containerized_deployment | bool' failed. The error was: error while evaluating conditional (containerized_deployment | bool): 'containerized_deployment' is undefined
>   
>     The error appears to have been in '/home/xe/ceph-ansible/roles/ceph-facts/tasks/facts.yml': line 39, column 3, but may
>     be elsewhere in the file depending on the exact syntax problem.
>   
>     The offending line appears to be:
>   
>   
>     - name: set_fact container_exec_cmd
>       ^ here
> 
> NO MORE HOSTS LEFT *****************************************************************************************
> 
> PLAY RECAP *************************************************************************************************
> m1-1045558                 : ok=12   changed=0    unreachable=0    failed=1   
> m2-1045557                 : ok=11   changed=0    unreachable=0    failed=1   
> m3-1045556                 : ok=11   changed=0    unreachable=0    failed=1   
> 
> 
> Thursday 01 August 2019  15:49:13 +0200 (0:00:00.223)       0:00:12.640 ******* 
> =============================================================================== 
> gather and delegate facts --------------------------------------------------------------------------- 3.54s
> check for python ------------------------------------------------------------------------------------ 0.87s
> set_fact is_atomic ---------------------------------------------------------------------------------- 0.80s
> ceph-facts : check if podman binary is present ------------------------------------------------------ 0.76s
> ceph-facts : include facts.yml ---------------------------------------------------------------------- 0.76s
> check if it is atomic host -------------------------------------------------------------------------- 0.63s
> ceph-facts : check if it is atomic host ------------------------------------------------------------- 0.62s
> ceph-facts : set_fact is_podman --------------------------------------------------------------------- 0.53s
> install python for fedora --------------------------------------------------------------------------- 0.51s
> gather facts ---------------------------------------------------------------------------------------- 0.41s
> ceph-facts : set_fact monitor_name ansible_hostname ------------------------------------------------- 0.41s
> ceph-facts : set_fact is_atomic --------------------------------------------------------------------- 0.40s
> ceph-facts : set_fact container_binary -------------------------------------------------------------- 0.40s
> ceph-facts : set_fact ceph_release ceph_stable_release ---------------------------------------------- 0.38s
> install python for debian based systems ------------------------------------------------------------- 0.36s
> ceph-facts : set_fact monitor_name ansible_fqdn ----------------------------------------------------- 0.29s
> install required packages for fedora > 23 ----------------------------------------------------------- 0.28s
> install python for opensuse ------------------------------------------------------------------------- 0.27s
> ceph-facts : set_fact container_exec_cmd ------------------------------------------------------------ 0.22s

ansible-playbook site.yml -i inventory/inventory

ii  ansible                               2.5.1+dfsg-1ubuntu0.1
ceph-ansible: latest, just git cloned

**Comment by superxor** [comment]
Now I am stuck with

>   msg: |-
>     The task includes an option with an undefined variable. The error was: 'timeout_command' is undefined
>   
>     The error appears to have been in '/home/xe/ceph-ansible/roles/ceph-facts/tasks/facts.yml': line 49, column 3, but may
>     be elsewhere in the file depending on the exact syntax problem.
>   
>     The offending line appears to be:
>   
>     # of the rolling update
>     - name: is ceph running already?
>       ^ here

I already got everything as .yml file....I just want a basic mon/mds/mgr installation.

**Comment by dsavineau** [comment]
Without the full ansible log I can't really help.

Your ansible execution is failing during the ceph-facts but the defaults variables are initialized during the ceph-defaults role just before 

https://github.com/ceph/ceph-ansible/blob/master/site.yml.sample#L65-L68

Do you have those lines in your site.yml ansible playbook ?

Also:
> ii ansible 2.5.1+dfsg-1ubuntu0.1

You should be using ansible 2.8

https://docs.ceph.com/ceph-ansible/master/#releases

**Comment by superxor** [comment]
There are no errors prior in the log though, you see atthe bottom what it checked?
Yes I have those lines.
I'll try an upgrade.

This is pretty much default, I barely touched anything in the all.yml

**Comment by superxor** [comment]
fixed: ansible version

**Comment by superxor** [comment]
Something is still not right.
I managed to install mons, mds etc.
But now upon trying to install OSDs I get:

 [ERROR]: [m1-1045558] Validation failed for variable: ceph_origin

 [ERROR]: [m1-1045558] Given value for ceph_origin: dummy

 [ERROR]: [m1-1045558] Reason: ceph_origin must be either 'repository', 'distro' or 'local'

fatal: [m1-1045558]: FAILED! => changed=false 
  msg: |-
    [m1-1045558] Validation failed for variable: ceph_origin
    [m1-1045558] Reason: ceph_origin must be either 'repository', 'distro' or 'local'
    [m1-1045558] Given value for ceph_origin: dummy

Which is wrong, I set them, otherwise mon/mds wouldn't have installed?

**Comment by dsavineau** [comment]
mons, mds and osds are sharing the same validation code [1] and validation is done on the same time on all nodes so it's not even possible to deploy mons/mds and fail on ceph-validate for osd unless you defined variables per host/group instead of globally (group_vars/all.yml)

[1] https://github.com/ceph/ceph-ansible/blob/master/site.yml.sample#L69-L70

**Comment by superxor** [comment]
No I defined the basic vars in all.yml. 

The thing is: site.yml runs. It setups everything again incl my osds. But I need to add more OSDs and before there was an extra yml for that..which should be add-osds.yml?
But if I run that I get the above errors. How can that be? 

> cat group_vars/all.yml | head -n20
> ---
> # Variables here are applicable to all host groups NOT roles
> 
> # This sample file generated by generate_group_vars_sample.sh
> 
> # Dummy variable to avoid error because ansible does not recognize the
> # file as a good configuration file when no variable in it.
> dummy:
> 
> # You can override vars by using host or group vars
> 
> generate_fsid: false
> fsid: "c4068f25-d46d-438d-af63-5679a2d56efb"
> ceph_origin: repository
> ceph_repository: community
> ceph_stable_release: nautilus
> public_network: "10.3.0.0/22"
> cluster_network: "10.3.0.0/22"
> monitor_interface: enp101s0

**Comment by dsavineau** [comment]
Again, providing the ansible command and ansible full log will help a lot.

BTW we're going to remove the add-osd.yml playbook since you can do the same by running the main playbook with `--limit` option

https://github.com/ceph/ceph-ansible/pull/4209

**Comment by superxor** [comment]
@dsavineau If I run :  ansible-playbook site.yml -i inventory/inventory --limit osds
Ansible hangs forever at the first step. Without --limit it works but then everything runs again.

`ansible-playbook site.yml -i inventory/inventory --limit osds
[DEPRECATION WARNING]: The TRANSFORM_INVALID_GROUP_CHARS settings is set to allow bad characters in group names 
by default, this will change, but still be user configurable on deprecation. This feature will be removed in 
version 2.10. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
 [WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details

 [WARNING]: Could not match supplied host pattern, ignoring: nfss

 [WARNING]: Could not match supplied host pattern, ignoring: rbdmirrors

 [WARNING]: Could not match supplied host pattern, ignoring: clients

 [WARNING]: Could not match supplied host pattern, ignoring: iscsigws

 [WARNING]: Could not match supplied host pattern, ignoring: iscsi-gws

 [WARNING]: Could not match supplied host pattern, ignoring: rgwloadbalancers


PLAY [mons,osds,mdss,rgws,nfss,rbdmirrors,clients,mgrs,iscsigws,iscsi-gws,grafana-server,rgwloadbalancers] ******
 [WARNING]: While constructing a mapping from /home/xe/ceph-ansible/group_vars/all.yml, line 8, column 1, found
a duplicate dict key (ceph_origin). Using last defined value only.

 [WARNING]: While constructing a mapping from /home/xe/ceph-ansible/group_vars/all.yml, line 8, column 1, found
a duplicate dict key (ceph_repository). Using last defined value only.


TASK [check for python] *****************************************************************************************
Friday 09 August 2019  08:32:54 +0200 (0:00:00.261)       0:00:00.261 ********* 
`
