### ISSUE TITLE
docker deployment doesn't create fetch files

### ISSUE THREAD

**Issue by nihilifer** [ceph/ceph-ansible#431]
Deployment in docker mode fails like this:

```
TASK: [ceph-mon | try to fetch ceph config and keys] ************************** 
fatal: [mon0] => input file not found at /home/mrostecki/ceph-ansible/roles/ceph-mon/tasks/files/fetch/docker_mon_files/etc/ceph/ceph.client.admin.keyring or /home/mrostecki/ceph-ansible/fetch/docker_mon_files/etc/ceph/ceph.client.admin.keyring

FATAL: all hosts have already failed -- aborting
```

That's probably because ceph-common role is used only on deployments without docker [1] and in the same time the configuration in fetch directory are generated in ceph-common. [2]

[1] https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-mon/meta/main.yml#L14
[2] https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-common/tasks/main.yml#L52-L89

**Comment by leseb** [comment]
It does work for me, are you still experiencing this issue?

**Comment by leseb** [comment]
@nihilifer haven't heard from you for a while, closing this, feel free to re-open.
