### ISSUE TITLE
Install ceph-common Packages on "client" systems

### ISSUE THREAD

**Issue by christiancloudibility** [ceph/ceph-ansible#4354]
It would be nice, to have the option to directly install ceph-common on client machines

**Describe the solution you'd like**
A task for Package ceph-common installation on client machines depending on "When" condition

Something like this :
```
$ cat group_vars/clients/clients.yml 
...
copy_admin_key: True
install_packages: True
...
```
and 
````
$ cat tasks/install_packages.yml
---
- name: install ceph-common package
  package:
    name: ceph-common
    state: present
  when:
    - install_packages
````

**Comment by christiancloudibility** [comment]
If you want to create a dedicated "admin" node
or a monitoring node which needs that stuff.
And is ceph-common not needed on any host, which wants to mount a volume provided by ceph?a

**Comment by dsavineau** [comment]
In fact this is already handle in the current code [1][2].
So on the client nodes it will install ceph-common, ceph-base and ceph-fuse.

https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-common/tasks/installs/install_redhat_packages.yml#L18-L23
https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-common/vars/main.yml

**Comment by christiancloudibility** [comment]
You are right, I have to check why it didn't work on my side :/ Didn't saw that case in ceph-common
