### ISSUE TITLE
Installing python in add-osd.yml

### ISSUE THREAD

**Issue by alidadar7676** [ceph/ceph-ansible#4368]
**Bug Report**

What happened:
When I want to use add-osd.yml for adding new osd to the cluster, I get this error:

> failed: [lab-mon1 -> {ip} ] (item=lab-osd4) => changed=false 
  ansible_loop_var: item
  item: lab-osd4
  module_stderr: |-
    /bin/sh: 1: /usr/bin/python: not found
  module_stdout: ''
  msg: |-
    The module failed to execute correctly, you probably need to set the interpreter.
    See stdout/stderr for the exact error
  rc: 127

What you expected to happen:
I expected add-osd.yml automatically installs the python package.

I think this line should be at the first of the pre_tasks in add-osd.yml:
`- import_tasks: raw_install_python.yml`

**Comment by Scooty5** [comment]
small note: it also doesn't install docker on containerized deployment.

**Comment by guits** [comment]
@alidadar7676 did you deploy your cluster with ceph-ansible?

**Comment by alidadar7676** [comment]
Yes @guits

**Comment by guits** [comment]
@alidadar7676 are you trying to add a new node or a new OSD on an existing node?

**Comment by alidadar7676** [comment]
No, At first I deployed Ceph cluster with ansible on my VMs and after that I used add-osd.yml to deploy a new OSD on a separate VM.
