### ISSUE TITLE
ceph-osd | prepare osd disk(s) ignored when GPT labels missing

### ISSUE THREAD

**Issue by BjoernT** [ceph/ceph-ansible#437]
The current ceph-osd tasks are ignoring disks with missing GPT labels leading to issues during later tasks to actually prepare/activate the OSDs so you end up with missing OSDs in your tree.
I personally would prefer to bail out the tasks so it can be fixed. Or is this intentionally ?

TASK: [ceph-osd | prepare osd disk(s)] ****************************************
skipping: [617569-cinder01] => (item=[{'cmd': "parted --script /dev/sdc print | egrep -sq '^ 1.*ceph'", 'end': '2015-11-19 19:45:10.241914', 'stderr': u'', 'stdout': u'', 'item': u'/dev/sdc', 'changed': False, 'rc': 0, 'failed': False, 'warnings': [], 'delta': '0:00:00.004694', 'invocation': {'module_name': u'shell', 'module_complex_args': {}, 'module_args': u"parted --script /dev/sdc print | egrep -sq '^ 1.*ceph'"}, 'stdout_lines': [], 'failed_when_result': False, 'start': '2015-11-19 19:45:10.237220'}, {'cmd': "echo '/dev/sdc' | egrep '/dev/(([a-z]{3,4}[0-9]$)|(cciss/c[0-9]{1}d[0-9]{1}p[0-9]$))'", 'end': '2015-11-19 19:45:10.069739', 'stderr': u'', 'stdout': u'', 'item': u'/dev/sdc', 'changed': False, 'rc': 1, 'failed': False, 'warnings': [], 'delta': '0:00:00.002533', 'invocation': {'module_name': u'shell', 'module_complex_args': {}, 'module_args': u"echo '/dev/sdc' | egrep '/dev/(([a-z]{3,4}[0-9]$)|(cciss/c[0-9]{1}d[0-9]{1}p[0-9]$))'"}, 'stdout_lines': [], 'failed_when_result': False, 'start': '2015-11-19 19:45:10.067206'}, u'/dev/sdc', u'/dev/sdc'])
failed: [617569-cinder01] => (item=[{'cmd': "parted --script /dev/sdd print | egrep -sq '^ 1.*ceph'", 'end': '2015-11-19 19:45:10.305827', 'stderr': u'', 'stdout': u'', 'item': u'/dev/sdd', 'changed': False, 'rc': 1, 'failed': False, 'warnings': [], 'delta': '0:00:00.011399', 'invocation': {'module_name': u'shell', 'module_complex_args': {}, 'module_args': u"parted --script /dev/sdd print | egrep -sq '^ 1.*ceph'"}, 'stdout_lines': [], 'failed_when_result': False, 'start': '2015-11-19 19:45:10.294428'}, {'cmd': "echo '/dev/sdd' | egrep '/dev/(([a-z]{3,4}[0-9]$)|(cciss/c[0-9]{1}d[0-9]{1}p[0-9]$))'", 'end': '2015-11-19 19:45:10.123249', 'stderr': u'', 'stdout': u'', 'item': u'/dev/sdd', 'changed': False, 'rc': 1, 'failed': False, 'warnings': [], 'delta': '0:00:00.002509', 'invocation': {'module_name': u'shell', 'module_complex_args': {}, 'module_args': u"echo '/dev/sdd' | egrep '/dev/(([a-z]{3,4}[0-9]$)|(cciss/c[0-9]{1}d[0-9]{1}p[0-9]$))'"}, 'stdout_lines': [], 'failed_when_result': False, 'start': '2015-11-19 19:45:10.120740'}, u'/dev/sdd', u'/dev/sdd']) => {"changed": false, "cmd": ["ceph-disk", "prepare", "/dev/sdd", "/dev/sdd"], "delta": "0:00:00.108754", "end": "2015-11-19 19:45:10.545153", "item": [{"changed": false, "cmd": "parted --script /dev/sdd print | egrep -sq '^ 1.*ceph'", "delta": "0:00:00.011399", "end": "2015-11-19 19:45:10.305827", "failed": false, "failed_when_result": false, "invocation": {"module_args": "parted --script /dev/sdd print | egrep -sq '^ 1.*ceph'", "module_complex_args": {}, "module_name": "shell"}, "item": "/dev/sdd", "rc": 1, "start": "2015-11-19 19:45:10.294428", "stderr": "", "stdout": "", "stdout_lines": [], "warnings": []}, {"changed": false, "cmd": "echo '/dev/sdd' | egrep '/dev/(([a-z]{3,4}[0-9]$)|(cciss/c[0-9]{1}d[0-9]{1}p[0-9]$))'", "delta": "0:00:00.002509", "end": "2015-11-19 19:45:10.123249", "failed": false, "failed_when_result": false, "invocation": {"module_args": "echo '/dev/sdd' | egrep '/dev/(([a-z]{3,4}[0-9]$)|(cciss/c[0-9]{1}d[0-9]{1}p[0-9]$))'", "module_complex_args": {}, "module_name": "shell"}, "item": "/dev/sdd", "rc": 1, "start": "2015-11-19 19:45:10.120740", "stderr": "", "stdout": "", "stdout_lines": [], "warnings": []}, "/dev/sdd", "/dev/sdd"], "rc": 1, "start": "2015-11-19 19:45:10.436399", "warnings": []}
stderr: Caution: invalid main GPT header, but valid backup; regenerating main header
from backup!

Warning! One or more CRCs don't match. You should repair the disk!

Invalid partition data!
ceph-disk: Error: Command '['/sbin/sgdisk', '--new=2:0:1000M', '--change-name=2:ceph journal', '--partition-guid=2:da32d58c-c513-4805-b287-d0bdbaf3e171', '--typecode=2:45b0969e-9b03-4f30-b4c6-b4b80ceff106', '--mbrtogpt', '--', '/dev/sdd']' returned non-zero exit status 2
stdout: Caution! After loading partitions, the CRC doesn't check out!
...ignoring

**Comment by leseb** [comment]
@BjoernT so you would like to stop the play and fix your issue instead of ignoring the error?
I'm not hiding it but I agree it'd be easy to miss it from the long verbose play logs.

**Comment by BjoernT** [comment]
Yes I personally would prefer that since you would expect that everything was successful when the playbooks finished

**Comment by leseb** [comment]
Perhaps we can fail earlier than that by checking the GPT status of the device.
Would you be happy with something like:

* run a parted print and look for errors such as:
  * `Error: /dev/sdb: unrecognised disk label`
  * `Caution: invalid main GPT header`

If we find one of these or simply if the command returns 1, we fail.

**Comment by BjoernT** [comment]
:+1:

**Comment by leseb** [comment]
currently testing #439
