### ISSUE TITLE
clients : fail at "ceph-config : generate ceph configuration file: ceph.conf"

### ISSUE THREAD

**Issue by computer045** [ceph/ceph-ansible#4451]
**Bug Report**

What happened: ansible-playbook failed on "ceph-config : generate ceph configuration file: ceph.conf" step. I got the following message:
```
fatal: [workstation1]: FAILED! => changed=false 
  msg: Source /home/user/.ansible/tmp/ansible-tmp-1568398356.14-4663637031807/source not found
```
The file exists, so I am confused as to why it shows me this error.
```
[user@workstation1 ~]$ cat /home/user/.ansible/tmp/ansible-tmp-1568398356.14-4663637031807/source 
[client.libvirt]
admin socket = /var/run/ceph/$cluster-$type.$id.$pid.$cctid.asok # must be writable by QEMU and allowed by SELinux or AppArmor
log file = /var/log/ceph/qemu-guest-$pid.log # must be writable by QEMU and allowed by SELinux or AppArmor

# Please do not change this file directly since it is managed by Ansible and will be overwritten
[global]
cluster network = ...
fsid = ...
mon host = [..., ...],[..., ...],[..., ...]
public network = ...
```

What you expected to happen: I expected the file to be found and the `ceph.conf` to be created.

How to reproduce it (minimal and precise):

```
$ vim hosts
[clients]
workstation1
...

$ ansible-playbook site.yml --limit=clients
```

Share your group_vars files, inventory
```
# group_vars/clients.yml
---
dummy:
copy_admin_key: false
```
**Environment**:
* OS (e.g. from /etc/os-release): CentOS Linux 7 (Core)
* Kernel (e.g. `uname -a`): 3.10.0-957.27.2.el7.x86_64 
* Docker version if applicable (e.g. `docker version`): N/A
* Ansible version (e.g. `ansible-playbook --version`): ansible 2.8.4
* ceph-ansible version (e.g. `git head or tag or stable branch`): v4.0.0rc15
* Ceph version (e.g. `ceph -v`): ceph version 14.2.3 (0f776cf838a1ae3130b2b73dc26be9c95c6ccc39) nautilus (stable)

**Comment by muellert** [comment]
Can't really help you atm, but this worked for me:
1. Use ceph-ansible stable-4.0
2. Run the infrastructure-playbooks/purge-cluster.yml playbook, then try again.

**Comment by computer045** [comment]
I ran the purge-cluster.yml playbook and I have tested the same configuration using ceph-ansible stable-4.0. I still get the same error.

From what I found out, the problem is that the `/home/user/.ansible` folder is not accessible to the root user.

```
[root@workstation1 user]# ls -al .ansible/
ls: cannot open directory .ansible/: Permission denied
```

**Comment by computer045** [comment]
This StackOverflow answer fixed my issue: https://stackoverflow.com/a/49747156/11874603

It required that I define the "remote_tmp" variable in my `ansible.cfg`
```
[defaults]
remote_tmp = /tmp/ansible-$USER
```

It wasn't necessary on the other systems I configured. All the mons, osds, mdss, ... were using the default configuration. I only had that problem with clients.

**Comment by dsavineau** [comment]
Can we close the issue then ?

**Comment by computer045** [comment]
Yes, we can close it. Never found out why it behaved like that on my client node though.
