### ISSUE TITLE
osd_memory_target value in all.yml not use even if it set.

### ISSUE THREAD

**Issue by mistur** [ceph/ceph-ansible#4463]
**Bug Report**

What happened:
I have server with plenty of memory (384GB) I'd like to limit the osd memory to 16GB and so I did this : 
all.yml:osd_memory_target: 17179869184

But after running the playbook, the value is still the one calculates.

What you expected to happen:
if the value is set in the group_vars/all.yml, it shouldn't be calculated by the playbook and set to the value chosen. 

https://github.com/ceph/ceph-ansible/blob/9fa98d79fde5f886e43fb27a9c8139e8271c0095/roles/ceph-config/templates/ceph.conf.j2#L94

How to reproduce it (minimal and precise):
if the osd_memory_target value is less than "ansible_memtotal_mb * 1048576 * hci_safety_factor / _num_osds" or than "ansible_memtotal_mb * 1048576 * non_hci_safety_factor / _num_osd" the one calculates will be set.

Share your group_vars files, inventory

**Environment**:
* OS (e.g. from /etc/os-release): 
Ansible host : Ubuntu 18.04
OSDs node : Ubuntu 16.04 
* Kernel (e.g. `uname -a`):
Ansible host : Linux icitsrv5 4.15.0-55-generic #60-Ubuntu SMP Tue Jul 2 18:22:20 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
OSDs node : Linux iccluster169.iccluster.epfl.ch 4.13.0-26-generic #29~16.04.2-Ubuntu SMP Tue Jan 9 22:00:44 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Docker version if applicable (e.g. `docker version`): no
* Ansible version (e.g. `ansible-playbook --version`):  2.8.5 
* ceph-ansible version (e.g. `git head or tag or stable branch`): stable-4.0
* Ceph version (e.g. `ceph -v`): Nautilus 14.2.1

Best regards,

Yoann

**Comment by JoshuaLyle** [comment]
running mimic in `stable/3.2` I've run into the same issue and had to manually set the below line in `ceph-ansible/roles/ceph-config/templates/ceph.conf.j2` to 
```
osd memory target = {{ osd_memory_target }}
```
in order to force the use of the `osd_memory_target` from `all.yml`

Line referenced above is linked here.
https://github.com/ceph/ceph-ansible/blob/c878e99589bde0eecb8ac72a7ec8bc1f66403eeb/roles/ceph-config/templates/ceph.conf.j2#L106

**Comment by dsavineau** [comment]
@mistur sorry I didn't reply to this issue but the answer in [1] will probably help you

[1] https://github.com/ceph/ceph-ansible/issues/4763#issuecomment-557584661
