### ISSUE TITLE
mount_activate: Failed to activate，ceph-disk: Does not look like a Ceph OSD, or incompatible version: /var/lib/ceph/tmp/mnt.kpS0kL

### ISSUE THREAD

**Issue by vincent50411** [ceph/ceph-ansible#4464]
**Bug Report**

What happened:
$ ansible-playbook site.yml -i hosts

error:
failed: [node3] (item=/dev/vdc) => {"changed": false, "cmd": ["ceph-disk", "activate", "/dev/vdc1"], "delta": "0:00:00.181354", "end": "2019-09-25 17:12:58.799235", "item": "/dev/vdc", "msg": "non-zero return code", "rc": 1, "start": "2019-09-25 17:12:58.617881", "stderr": "mount_activate: Failed to activate\nceph-disk: Does not look like a Ceph OSD, or incompatible version: /var/lib/ceph/tmp/mnt.WDR0ej", "stderr_lines": ["mount_activate: Failed to activate", "ceph-disk: Does not look like a Ceph OSD, or incompatible version: /var/lib/ceph/tmp/mnt.WDR0ej"], "stdout": "", "stdout_lines": []}
failed: [node2] (item=/dev/vdc) => {"changed": false, "cmd": ["ceph-disk", "activate", "/dev/vdc1"], "delta": "0:00:00.510697", "end": "2019-09-25 17:12:59.057726", "item": "/dev/vdc", "msg": "non-zero return code", "rc": 1, "start": "2019-09-25 17:12:58.547029", "stderr": "mount_activate: Failed to activate\nceph-disk: Does not look like a Ceph OSD, or incompatible version: /var/lib/ceph/tmp/mnt.kpS0kL", "stderr_lines": ["mount_activate: Failed to activate", "ceph-disk: Does not look like a Ceph OSD, or incompatible version: /var/lib/ceph/tmp/mnt.kpS0kL"], "stdout": "", "stdout_lines": []}

node3 node2
vdc
vdc1 ext4 a0575bee-de24-47d7-9d75-b6405014e030

Share your group_vars files, inventory hosts
[mons]
node1

[osds]
node2
node3

[mgrs]
node1

**Environment**:
* OS (e.g. from /etc/os-release):  centos7
* Kernel (e.g. `uname -a`):
* Docker version if applicable (e.g. `docker version`):
* Ansible version (e.g. `ansible-playbook --version`): ansible 2.6.19
* ceph-ansible version (e.g. `git head or tag or stable branch`):  ceph-ansible-stable-3.2
* Ceph version (e.g. `ceph -v`): ceph version 12.2.12

**Comment by dsavineau** [comment]
Are you sure that the device was wiped before the deployment to avoid legacy configuration from previous cluster ?

What's the output of `ceph-disk list` ?
