### ISSUE TITLE
add-osd.yml creates new OSDs on existing node with OSDs

### ISSUE THREAD

**Issue by jeevadotnet** [ceph/ceph-ansible#4473]
What happened:
I ran
`ansible-playbook site-docker.yml -i inventory add-osd.yml --limit=osds` to add `/dev/sdn` and it ended up adding another bunch of OSDS on the existing server that keeps on restarting.

Screenshot: https://prnt.sc/pb7pjn

What you expected to happen:
That it add's the removed OSD (osd.4 /dev/sdn) back into the cluster

How to reproduce it (minimal and precise):
This is on my test cluster, so everything vanilla with luminous 12.2.12 

Share your group_vars files, inventory
Group Vars: http://pastefile.fr/f7f693a55e76881b1a319e21849f72bd
Inventory: http://pastefile.fr/a0c8015a90b4515bff39c054a884d31d
Journalctl of node | tail -100 | http://pastefile.fr/0c2fbf07ab5d0d111dfc6de3c070e83c (this on the server on that it happened but the /dev/sdn is not even on this node)

**Environment**:
* OS (e.g. from /etc/os-release): `"Ubuntu 16.04.6 LTS`
* Kernel (e.g. `uname -a`): `Linux idia-maas-mgmt 4.15.0-47-generic #50~16.04.1-Ubuntu SMP Fri Mar 15 16:06:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
* Docker version if applicable (e.g. `docker version`): `18.09.7`
* Ansible version (e.g. `ansible-playbook --version`): `ansible-playbook 2.6.0`
* ceph-ansible version (e.g. `git head or tag or stable branch`): `stable-3.2.27`
* Ceph version (e.g. `ceph -v`): `12.2.12`

**Comment by jeevadotnet** [comment]
After rebooting the node, it removed the original 40 OSDS from the node, (node 1 = osd1-40, node 2-osd=41-80, node 3 = osd81-120). Now node 3 is osd121-159 and the original 40 osds restarts non stop.

**Comment by dsavineau** [comment]
If you want to add a new device (like /dev/sdn) on your existing OSD nodes then you don't need to remove the old devices from the configuration.
In fact you need to keep the full list. The devices already deployed won't be modified.

> group_vars/osds.yml:devices:
> group_vars/osds.yml:  - /dev/sdn

This should be:
```yaml
devices:
  - /dev/sdb
  - /dev/sdc
  (...)
  - /dev/sdn
```

**Comment by jeevadotnet** [comment]
Hi @dsavineau 

Thanks for the feedback. I commented out all the disks expect /dev/sda (OS drive) and ran `ansible-playbook -vv -i inventory add-osd.yml`

Eventually it gets stuck on a massive amount of red lines and doesn't proceed any further so I had to kill it: 
http://pastefile.fr/e19115040b8abba5ee6b4db7c6ef9859 

`journalctl -u ceph-osd@121.service | tail -n 50` since osd-121 keeps on restarting: Error ` /opt/ceph-container/bin/entrypoint.sh: static: does not generate config`
http://pastefile.fr/fb6ffb7f42048dacec1d5e4c705c3c40

**Comment by guits** [comment]
I think this is related to this bz:
https://bugzilla.redhat.com/show_bug.cgi?id=1739365

**Comment by guits** [comment]
@jeevadotnet could you link the full log? Thanks!

**Comment by jeevadotnet** [comment]
Hi as per IRC:
 http://pastefile.fr/368cbb7ab0e09fb49ad12c23910b772e
ignore the first 100 lines or so. from 2019-10-03
