### ISSUE TITLE
''osd_memory_target'' in section ''osd'' redefined Error during FSID fetch

### ISSUE THREAD

**Issue by KingJ** [ceph/ceph-ansible#4492]
**Bug Report**

What happened: When running a rolling update, ceph-facts : get current fsid task fails as the executed command returns a non-zero return code, with the stderr containing a warning that the osd_memory_target setting has been redefined.

`stderr: 'Can''t get admin socket path: unable to get conf option admin_socket for mon.host: warning: line 17: ''osd_memory_target'' in section ''osd'' redefined '`

I suspect may be due to the `bluestore_cache_autotune` setting in Ceph. ceph-ansible sets the `osd memory target` setting (with spaces rather than understores) [here](https://github.com/ceph/ceph-ansible/blob/v4.0.0rc16/roles/ceph-config/templates/ceph.conf.j2#L106). However, ceph itself appears to set the `osd_memory_target` setting instead if `bluestore_cache_autotune` is enabled, which is the default setting ([ref](https://docs.ceph.com/docs/nautilus/rados/configuration/bluestore-config-ref/#automatic-cache-sizing)). As a result, the same variable is defined twice - once with spaces, once with underscores. This does not appear to affect regular cluster functionality, however it does cause some commands (such as the one to retrieve the fsid) to output a warning to stderr and a return code of 22.

What you expected to happen: The rolling update playbook to function as normal, including correct retrieval of the FSID.

How to reproduce it (minimal and precise):
Create a `ceph.conf` file containing a single setting defined both using underscores and spaces, for example;

```
[osd]
bluestore compression algorithm = lz4
bluestore compression mode = aggressive
osd max backfills = 8
osd memory target = 4294967296
osd recovery max active = 8

osd_memory_target = 4242538496
osd_memory_base = 2147483648
osd_memory_cache_min = 3195011072
```

Run the rolling update playbook. The ceph-facts : get current fsid task will fail with the task's stderr containing the message `Can''t get admin socket path: unable to get conf option admin_socket for mon.host: warning: line 17: ''osd_memory_target'' in section ''osd'' redefined`.

Remove one of the identical configuration entries and re-run the playbook. The task will no longer fail, however the value will be silently added back.

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 18.04.3
* Kernel (e.g. `uname -a`):  5.0.0-29-generic #31~18.04.1-Ubuntu SMP Thu Sep 12 18:29:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Docker version if applicable (e.g. `docker version`): 18.09.7
* Ansible version (e.g. `ansible-playbook --version`): 2.8.5
* ceph-ansible version (e.g. `git head or tag or stable branch`): v4.0.0rc16
* Ceph version (e.g. `ceph -v`): 14.2.2/14.2.3

**Comment by dsavineau** [comment]
This isn't related to the duplicate key in the configuration. It's just a warning and has no impact.

The real problem here is that the ceph command to get the fsid from the config [1] isn't working at this moment of the upgrade.

Please share the full ansible logs, inventory and variables defined in [group|hos]_vars/*.yml

[1] https://github.com/ceph/ceph-ansible/blob/v4.0.0rc16/roles/ceph-facts/tasks/facts.yml#L87

**Comment by KingJ** [comment]
Although it's a warning and should have no impact, it definitely has an impact and prevents any ceph daemon commands, including config get fsid, from working. As a reproducible example;

1. Regular ceph.conf with no duplication;

```
cat /etc/ceph/ceph.conf
# Please do not change this file directly since it is managed by Ansible and will be overwritten
[global]
cluster network = 10.1.16.0/24
fsid = 53bad213-c5f2-4884-bd21-25eaeb0b60f6
mon host = [v2:10.1.15.22:3300,v1:10.1.15.22:6789],[v2:10.1.15.23:3300,v1:10.1.15.23:6789],[v2:10.1.15.25:3300,v1:10.1.15.25:6789],[v2:10.1.15.27:3300,v1:10.1.15.27:6789],[v2:10.1.15.28:3300,v1:10.1.15.28:6789]
mon initial members = nagisa,freyja,hitomi,holo,kasumi
osd pool default crush rule = -1
public network = 10.1.15.0/24

[osd]
bluestore compression algorithm = lz4
bluestore compression mode = aggressive
osd max backfills = 8
osd memory target = 4294967296
osd recovery max active = 8
```

2. config get fsid works;

```
docker exec ceph-mon-hitomi ceph daemon mon.hitomi config get fsid
{
    "fsid": "53bad213-c5f2-4884-bd21-25eaeb0b60f6"
}
```

3. Duplicate the `osd memory target` configuration option using underscores instead of spaces;

```
echo 'osd_memory_target = 4294967296' >> /etc/ceph/ceph.conf
```

```
cat /etc/ceph/ceph.conf
# Please do not change this file directly since it is managed by Ansible and will be overwritten
[global]
cluster network = 10.1.16.0/24
fsid = 53bad213-c5f2-4884-bd21-25eaeb0b60f6
mon host = [v2:10.1.15.22:3300,v1:10.1.15.22:6789],[v2:10.1.15.23:3300,v1:10.1.15.23:6789],[v2:10.1.15.25:3300,v1:10.1.15.25:6789],[v2:10.1.15.27:3300,v1:10.1.15.27:6789],[v2:10.1.15.28:3300,v1:10.1.15.28:6789]
mon initial members = nagisa,freyja,hitomi,holo,kasumi
osd pool default crush rule = -1
public network = 10.1.15.0/24

[osd]
bluestore compression algorithm = lz4
bluestore compression mode = aggressive
osd max backfills = 8
osd memory target = 4294967296
osd recovery max active = 8

osd_memory_target = 4294967296
```

4. config get fsid now fails, returning only the warning.

```
docker exec ceph-mon-hitomi ceph daemon mon.hitomi config get fsid
Can't get admin socket path: unable to get conf option admin_socket for mon.hitomi: warning: line 17: 'osd_memory_target' in section 'osd' redefined
```

Admittedly this does seem more like an upstream issue than a ceph-ansible issue, and there are [two](https://bugzilla.redhat.com/show_bug.cgi?id=1190451) [bugs](https://tracker.ceph.com/issues/37664) on the trackers. The first one however was closed with commentary saying that the warning shouldn't affect the output, when it definitely does!

[Looking at the the ceph CLI command code](https://github.com/ceph/ceph/blob/abce85bbd2fac9077dc84d13438e3cde86e3ab65/src/ceph.in), it tries to read the `admin_socket` configuration option by using `ceph-conf`. [However, if `ceph-conf` returns _any_ standard error output](https://github.com/ceph/ceph/blob/abce85bbd2fac9077dc84d13438e3cde86e3ab65/src/ceph.in#L526), then the an exception is raised and no further data is returned.

A quick run of `ceph-conf` when the configuration file has duplicated sections confirms that the warning about redefined configuration options is indeed output to stderr.

**Comment by dsavineau** [comment]
> [Looking at the the ceph CLI command code](https://github.com/ceph/ceph/blob/abce85bbd2fac9077dc84d13438e3cde86e3ab65/src/ceph.in), it tries to read the `admin_socket` configuration option by using `ceph-conf`. [However, if `ceph-conf` returns _any_ standard error output](https://github.com/ceph/ceph/blob/abce85bbd2fac9077dc84d13438e3cde86e3ab65/src/ceph.in#L526), then the an exception is raised and no further data is returned.

The command output with the `admin socket path` is really confusing because it's usually a good candidate of daemon/service not running.

But as you mentioned this doesn't look a ceph-ansible issue. However we need to find a workaound for this because it prevents one task to be executed correctly.

**Comment by dsavineau** [comment]
So I reproduced the issue and probably found a workaround.

```console
# ceph daemon mon.cephaio-1 config get fsid
Can't get admin socket path: unable to get conf option admin_socket for mon.cephaio-1: warning: line 13: 'osd_memory_target' in section 'osd' redefined
```

This `ceph daemon` command tries to resolve the sock path by running a `ceph-conf` command [1] and as you mentioned this command raises an exception. That's weird that the command is executed properly with rc 0 but the warning message is present in the stdout so maybe the python stderr/stdout handling is wrong somewhere

```console
# ceph-conf --name mon.cephaio-1 --show-config-value admin_socket
warning: line 13: 'osd_memory_target' in section 'osd' redefined 
/var/run/ceph/ceph-mon.cephaio-1.asok
# echo $?
0
```

The `ceph daemon` command could be change by using the` --admin-daemon` option to avoid to resolve the socket path from the config [2] (even with the duplicate entries in the config)

```console
# ceph --admin-daemon=/var/run/ceph/ceph-mon.cephaio-1.asok config get fsid
{
    "fsid": "5deaf2cd-a9c3-436b-9611-4a6a86719aa0"
}
```

[1] https://github.com/ceph/ceph/blob/nautilus/src/ceph.in#L749-L750
[2] https://github.com/ceph/ceph/blob/nautilus/src/ceph.in#L736-L759

**Comment by KingJ** [comment]
Thanks for the fast turnaround on the fix!
