### ISSUE TITLE
disable SSL for dashboard

### ISSUE THREAD

**Issue by Snegohod** [ceph/ceph-ansible#4529]
**Bug Report**

What happened:
When change default cluster name cannot deploy Dashboard

What you expected to happen:
Deploy dashboard with non default Ceph cluster name

How to reproduce it (minimal and precise):

Change default cluster in group_vars/all.yml

Share your group_vars files, inventory
Can add only in Monday

**Environment**:
* OS (e.g. from /etc/os-release): 7.7-1908
* Kernel (e.g. `uname -a`): 3.10.0-1062
* Docker version if applicable (e.g. `docker version`): 1.13.1
* Ansible version (e.g. `ansible-playbook --version`): 2.8.2
* ceph-ansible version (e.g. `git head or tag or stable branch`): stable-4.0
* Ceph version (e.g. `ceph -v`): 14.2.4

Workaround:
Add --cluster {{ cluster }} to ceph command in roles/ceph-dashboard/tasks/configure_dashboard.yml

**Comment by Snegohod** [comment]
Not working

> TASK [ceph-dashboard : disable SSL for dashboard] ****************************************************************
> Monday 07 October 2019  10:33:57 +0300 (0:00:00.190)       0:14:49.831 ********
> fatal: [node1.internet.nio2 -> node1.internet.nio2]: FAILED! => changed=true
>   cmd:
>   - docker
>   - exec
>   - ceph-mon-node1
>   - ceph
>   - --cluster
>   - ceph
>   - config
>   - set
>   - mgr
>   - mgr/dashboard/ssl
>   - 'false'
>   delta: '0:00:00.380883'
>   end: '2019-10-07 10:37:43.949208'
>   msg: non-zero return code
>   rc: 13
>   start: '2019-10-07 10:37:43.568325'
>   stderr: '[errno 13] error connecting to the cluster'
>   stderr_lines: <omitted>
>   stdout: ''
>   stdout_lines: <omitted>
> 

Argument --cluster {{ cluster }} is added to command but it value is empty

**Comment by dsavineau** [comment]
Could you share the full ansible log ?

**Comment by Snegohod** [comment]
> 
> 
> Could you share the full ansible log ?

I'm sorry. Dashboard install works correctly.
This is my mistake. There was an incorrectly configured soft link to /etc/ansible/group_vars
