### ISSUE TITLE
dict object' has no attribute u'mons'

### ISSUE THREAD

**Issue by saurav-nar** [ceph/ceph-ansible#4536]
I am getting below error while executing the ceph-ansible
fatal: [XX-XXC-td1.]: FAILED! => {
    "msg": "'dict object' has no attribute u'mons'"
}

**Comment by dsavineau** [comment]
Please provide the full ansible logs, inventory and variables defined in [host|group]_vars/*.yml

**Comment by saurav-nar** [comment]
Task :
TASK [ceph-facts : generate cluster fsid] *************************************************************************************
task path: /opt/ceph/ceph-ansible-master/roles/ceph-facts/tasks/facts.yml:116
fatal: [mkm-ubn-ttnkha.ccc.com]: FAILED! => {
    "msg": "'dict object' has no attribute u'mons'"
}
Inventory:
[nfss]
mkm-ubn-ttnkha.ccc.com
[mon]
mkm-ubn-ttnkha.ccc.com
[osd]
mkm-ubn-ttnkha.ccc.com
[admin]
mkm-ubn-ttnkha.ccc.com

 all.yml
# Inventory host group variables
mon_group_name: mons
#osd_group_name: osds
#rgw_group_name: rgws
#mds_group_name: mdss
#nfs_group_name: nfss
#rbdmirror_group_name: rbdmirrors
#client_group_name: clients
#iscsi_gw_group_name: iscsigws
#mgr_group_name: mgrs
#rgwloadbalancer_group_name: rgwloadbalancers
#grafana_server_group_name: grafana-server

# Directory to fetch cluster fsid, keys etc...
fetch_directory: ~/ceph-ansible-keys


ceph_origin: repository
ceph_repository: community
ceph_stable_release: nautilus
ceph_repository_type: cdn


monitor_interface: ens160
#monitor_address: 0.0.0.0
#monitor_address_block: subnet
# set to either ipv4 or ipv6, whichever your network is using
ip_version: ipv4
mon_use_fqdn: false # if set to true, the MON name used will be the fqdn in the ceph.conf

#mon_host_v1:
#  enabled: True
#  suffix: ':6789'
#mon_host_v2:
#  suffix: ':3300'

##########
# CEPHFS #
##########
cephfs: cephfs # name of the ceph filesystem


journal_size: 4096
#block_db_size: -1 # block db size in bytes for the ceph-volume lvm batch. -1 means use the default of 'as big as possible'.
public_network: 0.0.0.0/0
cluster_network: "{{ public_network | regex_replace(' ', '') }}"
osd_mkfs_type: xfs
osd_mkfs_options_xfs: -f -i size=2048
#osd_mount_options_xfs: noatime,largeio,inode64,swalloc
osd_objectstore: bluestore


dashboard_enabled: False

**Comment by dsavineau** [comment]
```yaml
mon_group_name: mons
```
and
```yaml
[mon]
mkm-ubn-ttnkha.ccc.com
```

You need to change your mon group name in the inventory file with `mons` and not `mon`. This 
is also true for `osds` instead of `osd`
