### ISSUE TITLE
radosgw doesn't start due to prefix mismatch

### ISSUE THREAD

**Issue by crcceph** [ceph/ceph-ansible#454]
ceph.conf gets created with radosgw instances that look like:
[ceph.rgw.hostname]
 ....

but the service file
https://github.com/ceph/ceph/blob/master/systemd/ceph-radosgw@.service#L12
uses "--name client.%i" to identify the instance (no rgw)

This mismatch causes radosgw not to start and gives an error "couldn't init storage provider"
Technically this seems like an error in the service file, as ceph documentation seems to encourage the 
client.daemon.hostname syntax, so I apologize if this should be under ceph proper.  There is a similar issue on previous versions, as the sysvinit script has PREFIX value which doesn't match the ceph.conf either.

**Comment by leseb** [comment]
Yes I really need to spend some time on this...
Are you running on Debian?

**Comment by crcceph** [comment]
CentOS7.  For the time being I just edit the service file.  After thinking about this a little more it does seem like this really belongs to ceph and not ceph-ansible?

**Comment by leseb** [comment]
Correct not a ceph-ansible issue.
