### ISSUE TITLE
error on task "create ceph mgr keyring(s) on a mon node"

### ISSUE THREAD

**Issue by rain8220** [ceph/ceph-ansible#4547]
**Bug Report**

What happened:
I'm using ceph-ansible to deploy a containerized ceph cluster.
I ran into the following issue:
`
ASK [ceph-mgr : create ceph mgr keyring(s) on a mon node] ************************************************************Saturday 05 October 2019  09:16:10 +0000 (0:00:00.132)       0:14:34.451 ******
failed: [ceph-node4 -> ceph-node4] (item=ceph-node4) => {"changed": false, "cmd": "ceph -n client.admin -k /etc/ceph/ceph.client.admin.keyring --cluster ceph auth get mgr.ceph-node4 -f json", "item": "ceph-node4", "msg": "[Errno 2] No such file or directory", "rc": 2}
`

The weird thing is when I tried to run the command (ceph -n client.admin -k /etc/ceph/ceph.client.admin.keyring --cluster ceph auth get mgr.ceph-node4 -f json)  for this task manually, it worked. But when I tried to execute ansible-playbook site-docker.yml, I ran into the same error again.

additional information:
the OSD, MON services are up and running on my system:

[root@ceph-node4 ceph-ansible]# ceph -s
  cluster:
    id:     346291af-2403-4cfa-986c-d5ff3a45e1d8
    health: HEALTH_OK

  services:
    mon: 3 daemons, quorum ceph-node4,ceph-node5,ceph-node6
    mgr: no daemons active
    osd: 0 osds: 0 up, 0 in

  data:
    pools:   0 pools, 0 pgs
    objects: 0  objects, 0 B
    usage:   0 B used, 0 B / 0 B avail
    pgs:

What you expected to happen:

How to reproduce it (minimal and precise):

Share your group_vars files, inventory

**Environment**:
* OS (e.g. from /etc/os-release):
CentOS 7.6
* Kernel (e.g. `uname -a`):
* Docker version if applicable (e.g. `docker version`):
[root@ceph-node4 ceph-ansible]# docker -v
Docker version 1.13.1, build 7f2769b/1.13.1

* Ansible version (e.g. `ansible-playbook --version`):

* ceph-ansible version (e.g. `git head or tag or stable branch`):
[root@ceph-node4 ceph-ansible]# ansible-playbook --version
ansible-playbook 2.6.19
  config file = /root/ceph-ansible/ansible.cfg
  configured module search path = [u'/root/ceph-ansible/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible-playbook
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

* Ceph version (e.g. `ceph -v`):
[root@ceph-node4 docker]# ceph -v
ceph version 13.2.6-466-g1720691 (17206912981387416f4e0759804d403ab5e4cf52) mimic (stable)

**Comment by dsavineau** [comment]
I suppose that you're using stable-3.2 branch or 3.2.x tag ?

Could you also share the full ansible log, inventory and variables in [host|group]_vars/*.yml ?

**Comment by kevincoakley** [comment]
#4559 seems to have fixed the original issue but caused a new issue. 

I am now have origin/stable-4.0 (fd759f9) checked out. I have 3 mgr servers (ceph-mon-0, ceph-mon-1 and ceph-mon-2) and the ceph cluster is named ceph. 

ceph-mon-0 tried to copy the key to /var/lib/ceph/mgr/ceph-ceph-mon-0 on ceph-mon-1 and ceph-mon-2, which doesn't exist.  `"msg": "Destination directory /var/lib/ceph/mgr/ceph-ceph-mon-0 does not exist"`. 

-vvv error logs at https://pastebin.com/LcRJaEwh
