### ISSUE TITLE
TASK [ceph-validate : validate provided configuration] ** IndexError: list index out of range

### ISSUE THREAD

**Issue by saurav-nar** [ceph/ceph-ansible#4558]
task path: /opt/ceph/ceph-ansible-master/roles/ceph-validate/tasks/main.yml:2 The full traceback is: Traceback (most recent call last):   File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 145, in run     res = self._execute()   File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 664, in _execute     result = self._handler.run(task_vars=variables)   File "/opt/ceph/ceph-ansible-master/plugins/actions/validate.py", line 118, in run     host, error.path[0]) IndexError: list index out of range  fatal: [clm-.vcb.com]: FAILED! => {     "msg": "Unexpected failure during module execution.",     "stdout": "" }

**Comment by dsavineau** [comment]
Please share the full ansible logs, inventory and variables in [group|host]_vars/*.yml

**Comment by saurav-nar** [comment]
task path: /opt/ceph/ceph-ansible-master/roles/ceph-validate/tasks/main.yml:2
The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 145, in run
    res = self._execute()
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 664, in _execute
    result = self._handler.run(task_vars=variables)
  File "/opt/ceph/ceph-ansible-master/plugins/actions/validate.py", line 118, in run
    host, error.path[0])
IndexError: list index out of range

fatal: [clm-phn-ttnkha.abc.com]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}


Hosts:

[nfss]
mkm-ubn-ttnkha.ccc.com
[mons]
mkm-ubn-ttnkha.ccc.com
[osds]
mkm-ubn-ttnkha.ccc.com
[admin]
mkm-ubn-ttnkha.ccc.com




# Inventory host group variables
mon_group_name: mons
osd_group_name: osds
#rgw_group_name: rgws
#mds_group_name: mdss
nfs_group_name: nfss



# Directory to fetch cluster fsid, keys etc...
fetch_directory: ~/ceph-ansible-keys


ceph_origin: repository
ceph_repository: community
ceph_stable_release: nautilus
ceph_repository_type: cdn


monitor_interface: ens160
#monitor_address: 0.0.0.0
#monitor_address_block: subnet
# set to either ipv4 or ipv6, whichever your network is using
ip_version: ipv4
mon_use_fqdn: false # if set to true, the MON name used will be the fqdn in the ceph.conf

#mon_host_v1:
#  enabled: True
#  suffix: ':6789'
#mon_host_v2:
#  suffix: ':3300'

##########
# CEPHFS #
##########
cephfs: cephfs # name of the ceph filesystem


journal_size: 4096
#block_db_size: -1 # block db size in bytes for the ceph-volume lvm batch. -1 means use the default of 'as big as possible'.
public_network: 0.0.0.0/0
cluster_network: "{{ public_network | regex_replace(' ', '') }}"
osd_mkfs_type: xfs
osd_mkfs_options_xfs: -f -i size=2048
#osd_mount_options_xfs: noatime,largeio,inode64,swalloc
osd_objectstore: bluestore


dashboard_enabled: False

**Comment by dsavineau** [comment]
What ansible release are you using ?
What ceph-ansible branch or tag are you using ?

**Comment by saurav-nar** [comment]
2.8

**Comment by saurav-nar** [comment]
Master branch

**Comment by dsavineau** [comment]
Could you run the ansible-playbook with more verbosity ? (ie: -vvv)

**Comment by saurav-nar** [comment]
> Could you run the ansible-playbook with more verbosity ? (ie: -vvv)

I ran with -vvv only and i can see below error logs only
TASK [ceph-validate : validate provided configuration] ************************************************************************
task path: /opt/ceph/ceph-ansible-master/roles/ceph-validate/tasks/main.yml:2
The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 145, in run
    res = self._execute()
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 664, in _execute
    result = self._handler.run(task_vars=variables)
  File "/opt/ceph/ceph-ansible-master/plugins/actions/validate.py", line 118, in run
    host, error.path[0])
IndexError: list index out of range

fatal: [clm-phn-ttnkha.abc.com]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}

**Comment by guits** [comment]
Fixed by #4598
