### ISSUE TITLE
mgr: "copy ceph key(s) if needed" tries to copy keys to the wrong directory

### ISSUE THREAD

**Issue by kevincoakley** [ceph/ceph-ansible#4602]
**Bug Report**

What happened: Follow up to issue #4518. Pull #4591 didn't fix my issues.

I have 3 mgr servers (ceph-mon-0, ceph-mon-1 and ceph-mon-2) and the ceph cluster is named ceph.

Ansible tries to copy the key from ceph-mon-0 to /var/lib/ceph/mgr/ceph-ceph-mon-0 on ceph-mon-1 and ceph-mon-2, which doesn't exist. "msg": "Destination directory /var/lib/ceph/mgr/ceph-ceph-mon-0 does not exist". 

-vvv error logs at https://pastebin.com/LcRJaEwh

Share your group_vars files, inventory

```
[mons]
ceph-mon-0 ansible_host=192.168.0.6 ansible_port=22 ansible_user=centos ansible_become=yes ansible_become_method=sudo
ceph-mon-1 ansible_host=192.168.0.26 ansible_port=22 ansible_user=centos ansible_become=yes ansible_become_method=sudo
ceph-mon-2 ansible_host=192.168.0.24 ansible_port=22 ansible_user=centos ansible_become=yes ansible_become_method=sudo

[mgrs:children]
mons

[rgws:children]
mons

[osds]
ceph-osd-0 ansible_host=192.168.0.22 ansible_port=22 ansible_user=centos ansible_become=yes ansible_become_method=sudo osd_crush_location="{ 'root': 'default', 'pod': 'pod-01', 'rack': 'rack-01', 'host': 'sdsc-dev-osd-0' }"
ceph-osd-1 ansible_host=192.168.0.12 ansible_port=22 ansible_user=centos ansible_become=yes ansible_become_method=sudo osd_crush_location="{ 'root': 'default', 'pod': 'pod-01', 'rack': 'rack-01', 'host': 'sdsc-dev-osd-1' }"
ceph-osd-2 ansible_host=192.168.0.44 ansible_port=22 ansible_user=centos ansible_become=yes ansible_become_method=sudo osd_crush_location="{ 'root': 'default', 'pod': 'pod-01', 'rack': 'rack-01', 'host': 'sdsc-dev-osd-2' }"
ceph-osd-3 ansible_host=192.168.0.25 ansible_port=22 ansible_user=centos ansible_become=yes ansible_become_method=sudo osd_crush_location="{ 'root': 'default', 'pod': 'pod-01', 'rack': 'rack-01', 'host': 'sdsc-dev-osd-3' }"
ceph-osd-4 ansible_host=192.168.0.40 ansible_port=22 ansible_user=centos ansible_become=yes ansible_become_method=sudo osd_crush_location="{ 'root': 'default', 'pod': 'pod-01', 'rack': 'rack-01', 'host': 'sdsc-dev-osd-4' }"
```

**Environment**:
* OS (e.g. from /etc/os-release): CentOS 7.7
* Kernel (e.g. `uname -a`): 3.10.0-1062.1.1.el7.x86_64
* Docker version if applicable (e.g. `docker version`): None
* Ansible version (e.g. `ansible-playbook --version`): ansible 2.8.5
* ceph-ansible version (e.g. `git head or tag or stable branch`): origin/stable-4.0 (fd759f9)
* Ceph version (e.g. `ceph -v`): ceph version 14.2.4 (75f4de193b3ea58512f204623e6c5a16e6c1e1ba) nautilus (stable)

**Comment by lukasstockner** [comment]
Same problem here - in fact, for me #4591 broke the deployment, going back to 9c05470 fixes the issue.

**Comment by guits** [comment]
#4604 should fix this issue

**Comment by kevincoakley** [comment]
It looks like #4604 resolves my issue

**Comment by lukasstockner** [comment]
Same here, works with #4604.
