### ISSUE TITLE
ceph L version to the N version, rolling_update.yml error

### ISSUE THREAD

**Issue by lnsyyj** [ceph/ceph-ansible#4632]
**Bug Report**

What happened:
`[root@ceph1 ceph-ansible]# ansible-playbook infrastructure-playbooks/rolling_update.yml 
`
I want to upgrade the ceph L version to the N version, using rolling_update.yml, but report the task path: /root/github/ceph14/ceph-ansible/roles/ceph-facts/tasks/set_monitor_address.yml:53
Friday 18 October 2019 09:49:31 +0800 (0:00:00.115) 0:00:13.581 ********
Fatal: [10.20.10.8]: FAILED! =>
   Msg: '''_monitor_addresses'' is undefined'
What you expected to happen:
Can be used

How to reproduce it (minimal and precise):

Share your group_vars files, inventory

**Environment**:
* OS (e.g. from /etc/os-release):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

* Kernel (e.g. `uname -a`):
Linux ceph1 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

* Docker version if applicable (e.g. `docker version`):
* Ansible version (e.g. `ansible-playbook --version`):
[root@ceph1 ceph-ansible]# ansible-playbook --version
ansible-playbook 2.8.5
  config file = /root/github/ceph14/ceph-ansible/ansible.cfg
  configured module search path = [u'/root/github/ceph14/ceph-ansible/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

* ceph-ansible version (e.g. `git head or tag or stable branch`):
remotes/origin/stable-4.0

* Ceph version (e.g. `ceph -v`):
ceph version 12.2.12 (1436006594665279fe734b4c15d7e08c13ebd777) luminous (stable)

**Comment by guits** [comment]
@lnsyyj share the full log, group_vars, and inventory as required in the issue template
