### ISSUE TITLE
Stucked on  waiting for the monitor(s) to form the quorum... when executing add-mon.yml

### ISSUE THREAD

**Issue by kmadac** [ceph/ceph-ansible#4634]
**Bug Report**

What happened:
I have working dockerized deployment with 3 monitors and I would to add 2 more monitors. I added monitors to [mons] ansible group. Execution of playbook add_mon.yaml stops on 
```
TASK [ceph-mon : waiting for the monitor(s) to form the quorum...]
```
`ceph -s` shows only 3 mon processes and I can see many errors in log in journalctl on new mon nodes:
```
Oct 18 12:58:06 node-0.ceph.novalocal docker[19729]: debug 2019-10-18 12:58:06.677 7f60518c4700 -1 mon.node-0@1(probing) e0 handle_auth_bad_method hmm, they didn't like 2 result (13) Permission denied
```

What you expected to happen:
playbook finishes without error and 2 new mons appears in ceph -s output.

How to reproduce it (minimal and precise):
Deploy dockerized nautilus ceph with v4.0.4-stable-4.0-nautilus-centos-7-x86_64 docker image on 3 nodes and try to add 2 more mon nodes.

Share your group_vars files, inventory

Inventory:
[localhost]
ceph-ansible ansible_connection=local

[ceph_nodes]
node-3.ceph.novalocal
node-4.ceph.novalocal
node-5.ceph.novalocal

[mons]
node-0.ceph.novalocal
node-1.ceph.novalocal
node-3.ceph.novalocal
node-4.ceph.novalocal
node-5.ceph.novalocal

[mgrs:children]
ceph_nodes

[osds:children]
ceph_nodes

[mdss:children]
ceph_nodes

[rgws:children]
ceph_nodes

**Environment**:
* OS (e.g. from /etc/os-release): centos 7
* Kernel (e.g. `uname -a`): Linux node-0.ceph.novalocal 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

* Docker version if applicable (e.g. `docker version`): 18.09.6
* Ansible version (e.g. `ansible-playbook --version`): 2.8.5
* ceph-ansible version (e.g. `git head or tag or stable branch`): stable-4.0
* Ceph version (e.g. `ceph -v`): ceph version 14.2.4 (75f4de193b3ea58512f204623e6c5a16e6c1e1ba) nautilus (stable)

**Comment by dsavineau** [comment]
Please share your full ansible logs, variables defined in [group|host]_vars/*.yml

**Comment by kmadac** [comment]
Here are requested files:
[ansible.log](https://github.com/ceph/ceph-ansible/files/3767309/ansible.log)
[group_vars.zip](https://github.com/ceph/ceph-ansible/files/3767319/group_vars.zip)

**Comment by kmadac** [comment]
Please reopen the issue. Fix #4663 which closed this issue, fixes the fact that docker has not been installed on the nodes, but that is not an root cause of a problem.

**Comment by dsavineau** [comment]
I tried this successfully after fixing https://github.com/ceph/ceph-ansible/pull/4671
However you need to add the new mon nodes at the end of the mons group in the inventory file otherwise you will have a new cluster bootstraped with a different fsid.

**Comment by kmadac** [comment]
Thanks for advice @dsavineau, that was exactly where was root cause of this issue.  Once I added, new nodes to the end of mons group adding of nodes successfully finished. I will add the info about it to add-mon.yml usage comment and will create PR.
