### ISSUE TITLE
mgr/dashboard: dashboard host ip not added in iscsi-gateway.cfg

### ISSUE THREAD

**Issue by alfonsomthd** [ceph/ceph-ansible#4638]
**Bug Report**

What happened:
After a deploy with ```dashboard_enabled: true```

in ```group_vars/all.yml```
the dashboard cannot access iSCSI REST API:
> mgr[dashboard] iscsi REST API failed GET req status: 403

What you expected to happen:

The dashboard host IP should be added to
```trusted_ip_list``` in ```iscsi-gateway.cfg``` so the dashboard can access the API.

How to reproduce it (minimal and precise):
Deploy with ```dashboard_enabled: true```
and enable iSCSI management:
https://docs.ceph.com/docs/nautilus/mgr/dashboard/#enabling-iscsi-management

Share your group_vars files, inventory

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Docker version if applicable (e.g. `docker version`):
* Ansible version (e.g. `ansible-playbook --version`):
* ceph-ansible version (e.g. `git head or tag or stable branch`):
* Ceph version (e.g. `ceph -v`):

**Comment by mkasturi18** [comment]
Environment details
[root@magna031 ubuntu]# cat /etc/os-release 
NAME="Red Hat Enterprise Linux"
VERSION="8.0 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.0"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.0 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.0:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.0
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.0"


uname -a
Linux magna031 4.18.0-80.11.2.el8_0.x86_64 #1 SMP Sun Sep 15 11:24:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux


[root@magna031 ubuntu]# podman version
Version:       1.0.5
Go Version:    go1.11.5
OS/Arch:       linux/amd64


ceph-ansible-4.0.2-2.el8cp.noarch
[root@magna019 ubuntu]# ceph -v
ceph version 14.2.4-25.el8cp (9fbed2b6595af440cb0c2de58877262e7dad459d) nautilus (stable)
[root@magna019 ubuntu]# ansible-playbook  --version
ansible-playbook 2.8.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /bin/ansible-playbook
  python version = 3.6.8 (default, Jun 12 2019, 01:12:31) [GCC 8.2.1 20180905 (Red Hat 8.2.1-3)]
