### ISSUE TITLE
purge-cluster limit ignored

### ISSUE THREAD

**Issue by Ejdesgaard** [ceph/ceph-ansible#4645]
During teardown of a test cluster, running luminous, I tried to decommision the rgw service first instead of the whole cluster, so I limited the purge-cluster.yml to the rgws group.
The test deployment is containerized, so I expected purge-cluster with limit on rgws, to clean out the rgws related containers and not touch the osds containers.
What happened was that both rgw and osd services were purged.

If this is the intended behaviour, then I would suggest that we put an extra warning in, that clearifies this, if a containerized deployment is detected.

inventory contains 4 nodes.
mons: 1 2 3
mgrs: 1 2 3
osds: 1 2 3 4
rgws: 3 4

## commands ##
`ansible-playbook -i hosts.yml -l rgws purge-docker-cluster.yml`

## result ##

> PLAY RECAP 
> 
> satv-test03            : ok=45   changed=26   unreachable=0    failed=0   
> satv-test04            : ok=35   changed=21   unreachable=0    failed=0   
...

`ceph -s`

> 
>   cluster:
>     id:     b0f7554a-6ed0-4b30-85d1-dafb3a0b72b0
>     health: HEALTH_WARN
>             8 osds down
>             2 hosts (8 osds) down
>             Reduced data availability: 204 pgs inactive
>             Degraded data redundancy: 106175/318525 objects degraded (33.333%), 316 pgs degraded, 448 pgs undersized
>             1/3 mons down, quorum satv-test01,satv-test02
>  
>   services:
>     mon: 3 daemons, quorum satv-test01,satv-test02, out of quorum: satv-test03
>     mgr: satv-test02(active), standbys: satv-test01
>     osd: 16 osds: 8 up, 16 in
>  
>   data:
>     pools:   10 pools, 448 pgs
>     objects: 106.17k objects, 102GiB
>     usage:   335GiB used, 11.9TiB / 12.2TiB avail
>     pgs:     45.536% pgs not active
>              106175/318525 objects degraded (33.333%)
>              161 active+undersized+degraded
>              155 undersized+degraded+peered
>              83  active+undersized
>              49  undersized+peered
>  

`ceph osd tree`

> ID CLASS WEIGHT   TYPE NAME                    STATUS REWEIGHT PRI-AFF 
> -1       12.18787 root default                                         
> -2       12.18787     room site-a                                      
> -4        3.04697         host satv-test01                         
>  0   10t  0.97659             osd.0                up  1.00000 1.00000 
>  1   10t  0.97659             osd.1                up  1.00000 1.00000 
>  2   10t  0.97659             osd.2                up  1.00000 1.00000 
>  3  nvme  0.11719             osd.3                up  1.00000 1.00000 
> -5        3.04697         host satv-test02                         
>  4   10t  0.97659             osd.4                up  1.00000 1.00000 
>  5   10t  0.97659             osd.5                up  1.00000 1.00000 
>  6   10t  0.97659             osd.6                up  1.00000 1.00000 
>  7  nvme  0.11719             osd.7                up  1.00000 1.00000 
> -6        3.04697         host satv-test03                         
>  8   10t  0.97659             osd.8              down  1.00000 1.00000 
>  9   10t  0.97659             osd.9              down  1.00000 1.00000 
> 10   10t  0.97659             osd.10             down  1.00000 1.00000 
> 11  nvme  0.11719             osd.11             down  1.00000 1.00000 
> -7        3.04697         host satv-test04                         
> 12   10t  0.97659             osd.12             down  1.00000 1.00000 
> 13   10t  0.97659             osd.13             down  1.00000 1.00000 
> 14   10t  0.97659             osd.14             down  1.00000 1.00000 
> 15  nvme  0.11719             osd.15             down  1.00000 1.00000                                
> 

#### Packages and versions #####
ceph-ansible-3.2.24
` ceph versions`
> {
>     "mon": {
>         "ceph version 12.2.8-52.el7cp (3af3ca15b68572a357593c261f95038d02f46201) luminous (stable)": 3
>     },
>     "mgr": {
>         "ceph version 12.2.8-52.el7cp (3af3ca15b68572a357593c261f95038d02f46201) luminous (stable)": 2
>     },
>     "osd": {
>         "ceph version 12.2.8-52.el7cp (3af3ca15b68572a357593c261f95038d02f46201) luminous (stable)": 8
>     },
>     "mds": {},
>     "overall": {
>         "ceph version 12.2.8-52.el7cp (3af3ca15b68572a357593c261f95038d02f46201) luminous (stable)": 13
>     }
> }

**Comment by vumrao** [comment]
Downstream bug - https://bugzilla.redhat.com/show_bug.cgi?id=1763896

**Comment by guits** [comment]
purge playbooks aren't intended to purge a part of a node only they are made to purge a node completely.
If you don't want to purge the whole node, this means you want to use shrink playbooks instead.
