### ISSUE TITLE
chown failed: failed to look up user ceph

### ISSUE THREAD

**Issue by pschiffe** [ceph/ceph-ansible#465]
Hey guys,

ansible playbook failed on me when installing restapi:
```
TASK: [ceph-restapi | create ceph rest api directory (for or after infernalis release)] *** 
failed: [XXX] => {"failed": true, "gid": 0, "group": "root", "mode": "0755", "owner": "root", "path": "/var/lib/ceph/restapi", "secontext": "unconfined_u:object_r:var_lib_t:s0", "size": 6, "state": "directory", "uid": 0}
msg: chown failed: failed to look up user ceph
```

I'm installing restapi on one of mon server (together with rgw), configuration is very close to defaults. OS is clean RHEL-7.2.

**Comment by leseb** [comment]
Arf let me look at that.

**Comment by leseb** [comment]
Looks like I forgot to implement the infernalis check logic for restapi. Fixing this.

**Comment by sureshcvh** [comment]
Hello Guys,

Ansible failed while installing Mysql

fatal: [cvhnd-comm-s-alberto]: FAILED! => {"changed": false, "failed": true, "gid": 0, "group": "root", "mode": "0755", "msg": "chown failed: failed to look up user mysql", "owner": "root", "path": "/home/mysql/.aws", "size": 4096, "state": "directory", "uid": 0}
Please help me
