### ISSUE TITLE
default group name for grafana role is using '-' which is deprecated in ansible 2.8

### ISSUE THREAD

**Issue by pcuzner** [ceph/ceph-ansible#4651]
Is there a plan to change the default grafana-server group name to avoid this issue ahead of 2.10?
e.g.
[DEPRECATION WARNING]: The TRANSFORM_INVALID_GROUP_CHARS settings is set to allow bad characters in group names by default, this will change, but still be user configurable on
deprecation. This feature will be removed in version 2.10. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
 [WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details

ceph-ansible version: master

**Comment by dsavineau** [comment]
Not yet but we will probably do the same than we have done for the iscsi group (iscsi-gws vs iscsigws) and try to keep backward compatibily before the removal with ansible 2.10.

**Comment by ppbrown** [comment]
Additional related bug, is that a few things HARDCODE "grafana-server" instead of using
groups[grafana_server_group_name]
