### ISSUE TITLE
ipaddrs_in_ranges.py

### ISSUE THREAD

**Issue by larmar** [ceph/ceph-ansible#4656]
When running ansible

[WARNING]: Skipping plugin (/root/ceph-
ansible/plugins/filter/test_ipaddrs_in_ranges.py) as it seems to be invalid:
cannot import name 'ipaddrs_in_ranges'

I change to 

from . import ips_in_ranges

in test_ipaddrs_in_ranges.py
it seems changed in Latest commit e695efc on Aug 14

Warning gone

**Comment by larmar** [comment]
When running ansible-playbook I get the warning again ?
ansible all -m ping works OK
but ansible-playbook site.yml seem to still give the WARNING

**Comment by discostur** [comment]
seeing the same output:

```
 [WARNING]: Skipping plugin (/root/ansible-playbooks/ceph-ansible-dev/plugins/filter/test_ipaddrs_in_ranges.py) as it seems to be invalid: cannot import name ipaddrs_in_ranges
``` 

ansible: 2.8.5
ceph-ansible: 4.0.4
