### ISSUE TITLE
RFE firewall support? iptables/firewalld

### ISSUE THREAD

**Issue by pschiffe** [ceph/ceph-ansible#466]
Hello,

is there, or are you planning to add support for firewall configuration? It would be really handy for new users.

**Comment by leseb** [comment]
Hey,

I've been wondering about this one for a while.
I usually believe that firewall rules should sit outside of this playbook and should be managed by an infrastructure playbook.
I'm just not sure how to address that yet, the only thing I can do for now is to provide the list of ports that must be opened...

wdyt?

**Comment by pschiffe** [comment]
That would by actually great start. Document the needed ports on the readme. Because I didn't find it anywhere here, even demo video didn't mention this, so when I started the playbook, it failed on timeout, and I had to investigate what's going on. And since on clean OS firewall is enabled by default, I was hit by that.

Another step could by just to add configuration option to open ports in firewall, commented out by default. I mean in all.sample in group_vars. I think there are valid use cases for this, when deploying on internal infra, or when networking isn't very complicated..

**Comment by leseb** [comment]
Hum actually one thing I can potentially do is to perform some networking test in the playbook and fail if we detect that some ports are not reachable. So if it does, you know that's a firewalling issue and can act accordingly.
wdyt?

**Comment by pschiffe** [comment]
Sounds good to me, definitely better than current state.

**Comment by leseb** [comment]
Ok tested and valided on #469. Feel free to test, closing this :)
