### ISSUE TITLE
site.yml.sample: 'install required packages for fedora > 23' does not work on F31

### ISSUE THREAD

**Issue by pcfe** [ceph/ceph-ansible#4690]
**Bug Report**

What happened:
`site.yml.sample` in stable-3.2 does what was needed for an out of the box Fedora 23 and upward. It runs `raw: sudo dnf -y install python2-dnf libselinux-python ntp`.
But when using ceph-ansible to set up a F31 OSD (well this week-end's release candidate to be precise) with that site.yml, I get two package not found errors.

What you expected to happen:
site.yml.sample usable for a F31 OSD
(FWIW, the node running ceph-ansible is RHEL7)

How to reproduce it (minimal and precise):
always, you can reproduce the raw command easily from shell on any F31 box.

```
[root@odroid-hc2-00 ~]# dnf -y install python2-dnf libselinux-python ntp
Fedora Modular 31 - armhfp                                                              73 kB/s |  18 kB     00:00    
Fedora Modular 31 - armhfp - Updates                                                   113 kB/s |  21 kB     00:00    
Fedora 31 - armhfp - Updates                                                            99 kB/s |  21 kB     00:00    
Fedora 31 - armhfp                                                                      99 kB/s |  19 kB     00:00    
No match for argument: python2-dnf
No match for argument: libselinux-python
Error: Unable to find a match: python2-dnf libselinux-python
```

Additional info:
It seem there is no need to add package lists with conditions for 31 and up, since I had the following 2 already installed in a `Fedora-Minimal-armhfp-31-1.9-sda.raw.xz` image

- python3-libselinux-2.9-5.fc31.armv7hl
- python3-dnf-4.2.9-5.fc31.noarch

So an additional
```
        - ansible_distribution_major_version|int < 31
```
should be enough, since using chrony instead of ntp has been working just fine for a while now with stable-3.2

**Environment**:
* OS (e.g. from /etc/os-release): Fedora-Minimal-armhfp-31-1.9-sda.raw.xz
* Kernel (e.g. `uname -a`): Linux odroid-hc2-00.internal.pcfe.net 5.3.7-301.fc31.armv7hl #1 SMP Mon Oct 21 22:12:15 UTC 2019 armv7l armv7l armv7l GNU/Linux
* Docker version if applicable (e.g. `docker version`):
* Ansible version (e.g. `ansible-playbook --version`): ansible-playbook 2.6.20
* ceph-ansible version (e.g. `git head or tag or stable branch`): ceph-ansible-3.2.30-1.el7cp.noarch and stable-3.2 branch
* Ceph version (e.g. `ceph -v`): playbook aborts before ceph packages are attempted to install

**Comment by dsavineau** [comment]
Full python3 support is only available starting stable-4.0 branch.
There's no way we will change the stable-3.2 branch for supporting newer distro like Fedora 31
