### ISSUE TITLE
No package matching 'ceph-iscsi' found available

### ISSUE THREAD

**Issue by ArnaudTa** [ceph/ceph-ansible#4691]
**Bug Report**

What happened:
Error during site.yml playbook
```TASK [ceph-iscsi-gw : install ceph iscsi package] ***********************************************************************************************************************************************
Tuesday 29 October 2019  12:05:15 +0100 (0:00:00.301)       0:07:40.182 ******* 
FAILED - RETRYING: install ceph iscsi package (3 retries left).
FAILED - RETRYING: install ceph iscsi package (3 retries left).
FAILED - RETRYING: install ceph iscsi package (3 retries left).
FAILED - RETRYING: install ceph iscsi package (3 retries left).
...
failed: [node2] (item=tcmu-runner) => changed=false 
  ansible_loop_var: item
  attempts: 3
  item: tcmu-runner
  msg: No package matching 'tcmu-runner' found available, installed or updated
  rc: 126
  results:
  - No package matching 'tcmu-runner' found available, installed or updated
...
```
What you expected to happen:
No error and next task ;)

How to reproduce it (minimal and precise):
set vars like below and launch playbook.

all.yml
```---
dummy:
mon_group_name: mons
osd_group_name: osds
rgw_group_name: rgws
mds_group_name: mdss
iscsi_gw_group_name: iscsigws
ceph_origin: repository
ceph_repository: community
ceph_mirror: http://download.ceph.com
ceph_stable_key: https://download.ceph.com/keys/release.asc
ceph_stable_release: nautilus
ceph_stable_repo: "{{ ceph_mirror }}/rpm-{{ ceph_stable_release }}"
ceph_stable_redhat_distro: el7
monitor_address_block: 172.20.0.0/16
ip_version: ipv4
radosgw_interface: enp0s3```

osds.yml
```
dummy:
devices:
  - /dev/sdb
osd_auto_discovery: true```

**Environment**:
* OS (e.g. from /etc/os-release): CentOS 7
* Kernel (e.g. `uname -a`): Linux node1.xxxxx.xxx 3.10.0-1062.el7.x86_64 #1 SMP Wed Aug 7 18:08:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Docker version if applicable (e.g. `docker version`):
* Ansible version (e.g. `ansible-playbook --version`): ansible-playbook 2.8.6
* ceph-ansible version (e.g. `git head or tag or stable branch`): stable-4.0
* Ceph version (e.g. `ceph -v`): ceph version 14.2.4 (75f4de193b3ea58512f204623e6c5a16e6c1e1ba) nautilus (stable)

I'm a bit lost, I'm not familiar with ceph and ansible. I can try to give more details if you need it.

Thanks for your help!

**Comment by dsavineau** [comment]
Could you share the full ansible log ?
