### ISSUE TITLE
storagectl name not set

### ISSUE THREAD

**Issue by nwl** [ceph/ceph-ansible#470]
Host: OSX 10.10.6
Vagrant: 1.8.1

After running vagrant up, I am getting:

A customization command failed:

["storageattach", :id, "--storagectl", nil, "--port", 3, "--device", 0, "--type", "hdd", "--medium", "disk-0-0.vdi"]

The following error was experienced:

#<Vagrant::Errors::VBoxManageError: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["storageattach", "ac4ccdf0-1c99-4cbf-96a8-a5cc1c213405", "--storagectl", "", "--port", "3", "--device", "0", "--type", "hdd", "--medium", "disk-0-0.vdi"]

Stderr: VBoxManage: error: Could not find a controller named ''
>

Please fix this customization and try again.

**Comment by leseb** [comment]
Hey @nwl, what's the value of `vagrant_storagectl` in the file `vagrant_variables.yml`?
Thanks!

**Comment by nwl** [comment]
Ah, it wasn't set (I hadn't merged in the new variables since my last git pull).
Now fighting with nmap detection :-)

**Comment by leseb** [comment]
Please pull again then :).
