### ISSUE TITLE
ceph-ansible + Fresh deployment problem : config_template is missing interpreter line

### ISSUE THREAD

**Issue by HammerZ3it** [ceph/ceph-ansible#4717]
Hi,
I am trying to deploy a new cluster with ceph-ansible with stable-4.0
Everything is working great until I reach the task : 
`TASK [ceph-config : generate ceph configuration file: ceph.conf]`
It returns this error : 
`fatal: [mon_host01]: FAILED! => {"msg": "module (config_template) is missing interpreter line"}`

I'm running ansible v 2.8.1 in a virtualenv with only ansible and the requirements.
I am executing my playing from the ceph-ansible directory, where ./library can be found.

`(ceph_ansible2) root@myworkstation:/workdir/ansible/ansible_ceph/ceph-ansible# ls -d */
actions_plugins/  callback_plugins/  contrib/  docs/  fetch/  filter_plugins/  group_vars/  host_vars/  infrastructure-playbooks/  library/  plugins/  profiles/  roles/  tests/`

`(ceph_ansible2) root@myworkstation:/workdir/ansible/ansible_ceph/ceph-ansible# ls -al ./library/

`ceph_add_users_buckets.py / ceph_crush.py / ceph_facts ceph_key.py / ceph_volume.py / config_template igw_client.py / igw_gateway.py / igw_lun.py / igw_purge.py / _init__.py / validate`

Following this documentation : https://docs.ansible.com/ansible/latest/dev_guide/developing_locally.html#adding-a-plugin-locally
I still don't understand why it can't find the module properly.

Regards,

**Comment by HammerZ3it** [comment]
Module in library seem to be executed I ran this test : 

    Place a customModule.py into ./library :

```
    #!/usr/bin/python
    import json
    print json.dumps({"hello" : "world"})
```

    Made the following playboook.yml :

```
    ---
    - hosts: localhost
      tasks:
        - name: custom module
          custom_module:
```

    Run the command : 
`ansible-playbook -vv playbook.yml`

And I ended with the expected result : 
```
TASK [custom module] *************************************************************************************************************************************************************************
task path: /workdir/ansible/ansible_ceph/ceph-ansible/playbook.yml:4
ok: [localhost] => {"changed": false, "hello": "world"}
```
Atm I am still trying to make guess about what can go wrong.

**Comment by dsavineau** [comment]
Please share the full ansible log, inventory and variables present in group_vars/*.yml

> I'm running ansible v 2.8.1 in a virtualenv with only ansible and the requirements.

You could try to use the requirements.txt file present in the repository [1] and run in your virtualenv :

```console
$ pip install -r requirements.txt
 ```

[1] https://github.com/ceph/ceph-ansible/blob/master/requirements.txt

**Comment by HammerZ3it** [comment]
Here is the inventory : 

```
[mons]
ceph_cluster_mon01
ceph_cluster_mon02
ceph_cluster_mon03

[osds]
ceph_clustercli_COG01
ceph_clustercli_COG02
ceph_clustercli_COG03
ceph_clustercli_SIB01
ceph_clustercli_SIB02
ceph_clustercli_SIB03
ceph_clustercli_TDF01
ceph_clustercli_TDF02
ceph_clustercli_TDF03

[mgrs]
ceph_cluster_mon01
ceph_cluster_mon02
ceph_cluster_mon03

[grafana-server]
ceph_cluster_mon01

[all:children]
mons
osds
mgrs
```

group_vars/*.yml

all.yml
```
ceph_origin: repository
ceph_repository: community
ceph_stable_release: nautilus
monitor_interface: ens192
journal_size: 5120
#public_network: 0.0.0.0/0 - leave commented
cluster_network: 172.29.242.0/24 #specify the network for internal traffic
osd_objectstore: bluestore

ceph_mirror: http://download.ceph.com
ceph_stable_key: https://download.ceph.com/keys/release.asc
ceph_stable_repo: "{{ ceph_mirror }}/debian-{{ ceph_stable_release }}"
upgrade_ceph_packages: True
ntp_daemon_type: ntpd
ntp_service_enabled: True

mon_group_name: mons
osd_group_name: osds
mgr_group_name: mgrs
```

mgrs.yml
```
ceph_mgr_modules:
  - status
  - dashboard
```

osds.yml
`osd_scenario: non-collocated`

I have vars in a host_vars for all my hosts : 
```
devices:
  - /dev/sdb
  - /dev/sdc
  - /dev/sdd
  - /dev/sde

dedicated_devices:
  - /dev/sdf
  - /dev/sdf
  - /dev/sdf
  - /dev/sdf
  
bluestore_wal_devices:
  - /dev/sdf
  - /dev/sdf
  - /dev/sdf
  - /dev/sdf
```

**Comment by dsavineau** [comment]
> osds.yml
> `osd_scenario: non-collocated`
> 
> I have vars in a host_vars for all my hosts :
> 
> ```
> devices:
>   - /dev/sdb
>   - /dev/sdc
>   - /dev/sdd
>   - /dev/sde
> 
> dedicated_devices:
>   - /dev/sdf
>   - /dev/sdf
>   - /dev/sdf
>   - /dev/sdf
>   
> bluestore_wal_devices:
>   - /dev/sdf
>   - /dev/sdf
>   - /dev/sdf
>   - /dev/sdf
> ```

`osd_scenario: non-collocated` doesn't exist anymore in stable-4.0 / nautilus because ceph-disk has been removed.
Please look at the lvm scenario instead (based on ceph-volume) [1][2]

Note that this shouldn't be the root cause of your issue.

[1] https://docs.ceph.com/ceph-ansible/master/#osd-configuration
[2] https://docs.ceph.com/ceph-ansible/master/osds/scenarios.html#lvm

**Comment by HammerZ3it** [comment]
I have modified my ansible following what you told me : 
osds.yml : 
```
osd_auto_discovery: false
osds_per_device: 1
osd_scenario: lvm
```
 and now the content of my host.yml : 
```
---
lvm_volumes:
- data: vg_osd_sdb/lv_osd_sdb
  wal: vg_wal_sdf/lv_wal_sdb
- data: vg_osd_sdc/lv_osd_sdc
  wal: vg_wal_sdf/lv_wal_sdc
- data: vg_osd_sdd/lv_osd_sdd
  wal: vg_wal_sdf/lv_wal_sdd
- data: vg_osd_sde/lv_osd_sde
  wal: vg_wal_sdf/lv_wal_sde
- data: vg_osd_sdf/lv_osd_sdf
  wal: vg_wal_sdf/lv_wal_sdf
```

NOTE : This is not my actual production setup as I wanted to get confortable with ceph-ansible before real deployment.

Regards,

**Comment by dsavineau** [comment]
> $ pip freeze
> ansible==2.8.1
> cffi==1.13.2
> cryptography==2.8
> enum34==1.1.6
> ipaddress==1.0.23
> Jinja2==2.10.3
> MarkupSafe==1.1.1
> netaddr==0.7.19
> pycparser==2.19
> PyYAML==5.1.2
> six==1.13.0

Is that an old virtualenv ? Because you're using an old ansible 2.8 and I don't have the same version at all

```console
$ pip list
Package       Version
------------- -------
ansible       2.8.6  
asn1crypto    0.24.0 
cffi          1.12.3 
cryptography  2.7    
Jinja2        2.10.1 
MarkupSafe    1.1.1  
netaddr       0.7.19 
pip           19.3.1 
pkg-resources 0.0.0  
pycparser     2.19   
PyYAML        5.1.1  
setuptools    41.0.1 
six           1.12.0 
wheel         0.33.4
```

Could you try with a fresh virtualenv ?

**Comment by HammerZ3it** [comment]
New virtualenv : 
```
(ceph_ansible2) root@PCCLT4282:/mnt/c/Users/cuzaf/Documents/ansible/ansible_ceph/ceph-ansible# pip freeze
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
ansible==2.8.6
cffi==1.13.2
cryptography==2.8
enum34==1.1.6
ipaddress==1.0.23
Jinja2==2.10.3
MarkupSafe==1.1.1
netaddr==0.7.19
pycparser==2.19
PyYAML==5.1.2
six==1.13.0
```

Result : 
```
TASK [ceph-config : generate ceph configuration file: ceph.conf] **************************************************************************************************************************************************************************************************************
fatal: [ceph_cluster_mon01]: FAILED! => {"msg": "module (config_template) is missing interpreter line"}
fatal: [ceph_cluster_mon02]: FAILED! => {"msg": "module (config_template) is missing interpreter line"}
fatal: [ceph_cluster_mon03]: FAILED! => {"msg": "module (config_template) is missing interpreter line"}
```

Btw, Thank you for your help and time.

Regards,

**Comment by dsavineau** [comment]
Would you be able to run ansible-playbook again but with more verbosity (`-vv`) ? and attach the log file.
Thanks

**Comment by HammerZ3it** [comment]
As requested 
[ansible_log.txt](https://github.com/ceph/ceph-ansible/files/3820603/ansible_log.txt)

**Comment by dsavineau** [comment]
Can't really reproduce on my side :/ and the logs aren't very useful

> Module in library seem to be executed I ran this test

Also config_template isn't a custom module but an action plugin.
The big difference there is that the action plugin won't be copy on the remote host and be executed. Everything is process locally but only the template generated will but send to the remote host.

The only thing related to the log (`module (config_template) is missing interpreter line`) is that there's not shebang in the config_template action plugin [1]
But this worked for years.

Anything specific on the host running ansible ?

[1] https://github.com/ceph/ceph-ansible/blob/master/plugins/actions/config_template.py

**Comment by HammerZ3it** [comment]
I made a new server to deploy from it (Ubuntu 18.04) clean install, only ansible (2.8.1) and the requirement and I am facing the same issue.

I even added the shebang to the .py script. 
I have to mention that I had to create a actions_plugin / filter_plugin and callback_plugin with the respective scripts in it.

Regards,

**Comment by HammerZ3it** [comment]
Any idea anyone ?
I guess I'll stick to ceph-deploy :(

**Comment by dsavineau** [comment]
Not really unfortunately.

BTW why are you still using ansible 2.8.1 and not the latest minor release ?

**Comment by dsavineau** [comment]
I just tried again on a fresh Ubuntu 18.04 environment successfully.

So I'm not sure what' wrong with your setup.

**Comment by HammerZ3it** [comment]
I'm using 2.8.1 to stick with the requirements.
I made a test with the 2.8.6 and still got the same result. Well I must be missing something here but I still can't find what.

**Comment by dsavineau** [comment]
> I'm using 2.8.1 to stick with the requirements.

What requirements ?

Because the one from ceph-ansible is using the latest 2.8.x ansible release.

As we saw this shouldn't be the root cause of the issue

**Comment by muff1nman** [comment]
I'd bet your issue is:

```
 [WARNING] Ansible is being run in a world writable directory (/mnt/c/Users/cuzaf/Documents/ansible/ansible_ceph/ceph-ansible), ignoring it as an ansible.cfg source. For more information see https://docs.ansible.com/ansible/devel/reference_appendices/config.html#cfg-in-world-writable-dir
```

**Comment by bnhashmi** [comment]
Dear HammerZ3it please update you /etc/anisble/ansible.cfg file   accordingly
i am using stack user to deply ceph-4.0 on ubuntu 18.04

action_plugins     = /home/stack/ceph-ansible/plugins/actions/

**Comment by mike-sirs** [comment]
@HammerZ3it Hi, how did you run ansible-playbook, can you share command?

**Comment by HammerZ3it** [comment]
My bad for answering that late :
My command use to run playbook : ansible-playbook -i inventory site.yml --user infra -K
I'll try to post a solution if I find it one as soon as I have time to get back on it.

Regards,

**Comment by mike-sirs** [comment]
> My bad for answering that late :
> My command use to run playbook : ansible-playbook -i inventory site.yml --user infra -K
> I'll try to post a solution if I find it one as soon as I have time to get back on it.
> 
> Regards,

I had the same issue. The issue was cuz I run ansible like ansible-playbook -i **ceph-ansible/hosts** **ceph-ansible/site.yml** -u ans-mgm

**Comment by secret104278** [comment]
Maybe you miss `ANSIBLE_CONFIG=$(where ceph-ansible directory located)/ansible.cfg`

**Comment by venkat-ar** [comment]
> I'd bet your issue is:
> 
> ```
>  [WARNING] Ansible is being run in a world writable directory (/mnt/c/Users/cuzaf/Documents/ansible/ansible_ceph/ceph-ansible), ignoring it as an ansible.cfg source. For more information see https://docs.ansible.com/ansible/devel/reference_appendices/config.html#cfg-in-world-writable-dir
> ```

Nice lead. that was the case in my issue

**Comment by Osa1989** [comment]
I had the same issue. Adding action_plugins as @bnhashmi suggested solved it. 
It is the first time I run int this issue, and I have used ceph-ansible a couple of times. 
Don't know why

**Comment by boxrice007** [comment]
> Dear HammerZ3it please update you /etc/anisble/ansible.cfg file accordingly
> i am using stack user to deply ceph-4.0 on ubuntu 18.04
> 
> action_plugins = /home/stack/ceph-ansible/plugins/actions/

nice，thank you
