### ISSUE TITLE
Rolling update playbook crashing on unnecessary migration from ceph-disk to ceph-volume

### ISSUE THREAD

**Issue by styleart** [ceph/ceph-ansible#4729]
**Bug Report**

Hey guys, just started the rolling-update.yaml playbook to upgrade from Nautilus 14.2.1 to Nautilus 14.2.4. The playbook crashed on task `activate scanned ceph-disk osds and migrate to ceph-volume if deploying nautilus`. But we're already using ceph-volume.

Before that, some months ago, we updated our cluster from Mimic to Nautilus. We had to manually migrate from `ceph-disk` to `ceph-volume` (as I wrote here: https://github.com/ceph/ceph-ansible/issues/4055#issuecomment-500792350), since then it was running fine. Why does the playbook try to migrate it, if it's already running on ceph-volume? 

How to reproduce it (minimal and precise):

On Nautilus 14.2.1:
- Migrate your ceph-disk to ceph-volume as described here: https://docs.ceph.com/docs/nautilus/rados/operations/add-or-rm-osds/#replacing-an-osd
- Run the rolling update playbook to upgrade the cluster from 14.2.1 to 14.2.4

**Environment**:
* OS (e.g. from /etc/os-release): 18.04.3 LTS (Bionic Beaver)
* Kernel (e.g. `uname -a`): Linux ceph1-40-10 5.0.0-16-generic #17~18.04.1-Ubuntu
* Ansible version (e.g. `ansible-playbook --version`): ansible-playbook 2.8.6
* ceph-ansible version (e.g. `git head or tag or stable branch`): stable-4.0
* Ceph version (e.g. `ceph -v`): 14.2.1 / 14.2.4

Crash message:
```
TASK [activate scanned ceph-disk osds and migrate to ceph-volume if deploying nautilus] ****************************************************
Monday 11 November 2019  16:46:21 +0100 (0:00:01.319)       0:09:03.711 ******* 
fatal: [ceph1-40-10.rz1.barzahlen.de]: FAILED! => changed=true 
  cmd:
  - ceph-volume
  - --cluster=ceph
  - simple
  - activate
  - --all
  delta: '0:00:00.243683'
  end: '2019-11-11 16:46:21.568056'
  msg: non-zero return code
  rc: 1
  start: '2019-11-11 16:46:21.324373'
  stderr: |-
    --> activating OSD specified in /etc/ceph/osd/0-95a0dc80-a3e8-4274-8acc-655ab1900d5f.json
    Running command: /bin/mount -v  /var/lib/ceph/osd/ceph-0
     stderr: mount: /var/lib/ceph/osd/ceph-0: wrong fs type, bad option, bad superblock on , missing codepage or helper program, or other error.
    Traceback (most recent call last):
      File "/usr/sbin/ceph-volume", line 11, in <module>
        load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')()
      File "/usr/lib/python2.7/dist-packages/ceph_volume/main.py", line 38, in __init__
        self.main(self.argv)
      File "/usr/lib/python2.7/dist-packages/ceph_volume/decorators.py", line 59, in newfunc
        return f(*a, **kw)
      File "/usr/lib/python2.7/dist-packages/ceph_volume/main.py", line 149, in main
        terminal.dispatch(self.mapper, subcommand_args)
      File "/usr/lib/python2.7/dist-packages/ceph_volume/terminal.py", line 194, in dispatch
        instance.main()
      File "/usr/lib/python2.7/dist-packages/ceph_volume/devices/simple/main.py", line 33, in main
        terminal.dispatch(self.mapper, self.argv)
      File "/usr/lib/python2.7/dist-packages/ceph_volume/terminal.py", line 194, in dispatch
        instance.main()
      File "/usr/lib/python2.7/dist-packages/ceph_volume/devices/simple/activate.py", line 280, in main
        self.activate(args)
      File "/usr/lib/python2.7/dist-packages/ceph_volume/decorators.py", line 16, in is_root
        return func(*a, **kw)
      File "/usr/lib/python2.7/dist-packages/ceph_volume/devices/simple/activate.py", line 178, in activate
        process.run(['mount', '-v', data_device, osd_dir])
      File "/usr/lib/python2.7/dist-packages/ceph_volume/process.py", line 153, in run
        raise RuntimeError(msg)
    RuntimeError: command returned non-zero exit status: 32
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
```

**Comment by dsavineau** [comment]
@alfredodeza @andrewschoen is it expected to have the `ceph-volume simple active` failing on ceph-volume OSD previously scanned ?
If yes do we need something smarter by checking the ceph-volume inventory and ceph-disk OSD ?
Note that we're already doing something similar to this in ceph-container [1]

[1] https://github.com/ceph/ceph-container/blob/master/src/daemon/osd_scenarios/osd_volume_activate.sh#L6

**Comment by dsavineau** [comment]
@styleart Could you share the ansible inventory and the variables defined in group_vars/*.yml ?

**Comment by alfredodeza** [comment]
@dsavineau the `simple activate --all` call looks in `/etc/ceph/osd/*.json` to activate everything that it finds. If there is nothing to activate then there shouldn't be anything in that directory. From the description in this issue, it seems that OSDs have already been migrated, but it is not clear to me if:

* does that mean it is using ceph-disk OSDs that have been scanned?
* Or nothing has been scanned and OSDs are LVs already?

If the OSDs are LVM already, created by ceph-volume, then there shouldn't be anything in /etc/ceph/osd/

**Comment by styleart** [comment]
@dsavineau sure! Maybe we just missed to reconfigure something after manual migration (beside switching from 'collocated' to 'lvm').

**inventory** (ini)
```
[mons]
ceph1-40-10.dc1.example.com
ceph1-40-11.dc1.example.com
ceph1-40-12.dc1.example.com

[osds]
ceph1-40-10.dc1.example.com
ceph1-40-11.dc1.example.com
ceph1-40-12.dc1.example.com

[mgrs]
ceph1-40-10.dc1.example.com
ceph1-40-11.dc1.example.com
ceph1-40-12.dc1.example.com

[rgws]
ceph1-40-10.dc1.example.com
ceph1-40-11.dc1.example.com
ceph1-40-12.dc1.example.com

[ceph:children]
mons
osds
mgrs
rgws
```

**group_vars/osds.yaml**
```
osd_scenario: lvm #we changed this one from 'collocated' to 'lvm' after manual migration
devices:
  - '/dev/sdc'
  - '/dev/sdd'
  - '/dev/sde'
  - '/dev/sdf'

osd_mkfs_type: xfs
osd_objectstore: bluestore
```
**group_vars/ceph.yaml**
```
ceph_mirror: http://download.ceph.com
ceph_origin: repository
ceph_repository: community
ceph_stable: true
ceph_stable_key: https://download.ceph.com/keys.release.asc
ceph_stable_release: nautilus
ceph_stable_repo: "{{ ceph_mirror }}/debian-{{ ceph_stable_release }}"
upgrade_ceph_packages: True

cluster: ceph
ceph_conf_key_directory: /etc/ceph
fetch_directory: fetch/
ntp_service_enabled: true
configure_firewall: false

monitor_interface: bond0
radosgw_interface: bond0

mon_group_name: mons
osd_group_name: osds
mgr_group_name: mgrs
rgw_group_name: rgws

ceph_mgr_modules:
  - status
  - dashboard
```
Btw: we managed to do the rolling update by commenting out two tasks:
- `name: scan ceph-disk osds with ceph-volume if deploying nautilus`  
- `name: activate scanned ceph-disk osds and migrate to ceph-volume if deploying nautilus`

We also had to remove tasks for MDS, since we don't use it and playbook crashed on them. Just wondering, why it even tries to update MDS.

@alfredodeza that seems to be the reason, since we still have json files in `/etc/ceph/osd/`. Do we have to remove them? We just followed this guide for every disk: https://docs.ceph.com/docs/nautilus/rados/operations/add-or-rm-osds/#replacing-an-osd
Also, after the mimic to nautilus upgrade there's no `ceph-disk` binary anymore on hosts.

**Comment by alfredodeza** [comment]
@styleart if all your OSDs are ceph-volume already, yes, remove all the /etc/ceph/osd/* files. You will also need to poke around at systemd and see if there are any unit files that were created in the process... you might need to delete any ceph-disk related ones

**Comment by styleart** [comment]
@alfredodeza just tested it out, removed files from `/etc/ceph/osd` and rebooted the node - everything came back automatically. I'll test the rolling update playbook again next days and give you a feedback. Thanks for the hint with json files so far :+1:

**Comment by alfredodeza** [comment]
@styleart sure thing. I would ensure that there are no systemd issues, and all your (expected) OSDs are coming back fine. Thanks for reporting back!

**Comment by styleart** [comment]
@alfredodeza ok, just removed json files from all nodes and rebooted - no issues with systemd, everything came back and is running fine. Also did a playbook run - this time without any errors. Awesome, much thanks for your help! Issue can be closed :slightly_smiling_face:
