### ISSUE TITLE
run 'ceph-volume lvm batch --report fails

### ISSUE THREAD

**Issue by ashoksangee** [ceph/ceph-ansible#4748]
**Bug Report**

What happened:
run 'ceph-volume lvm batch --report fails with following error when we run  playbook against a running cluster.

How to reproduce it (minimal and precise):
```console
fatal: [dal13cephosd01]: FAILED! => changed=false
  cmd:
  - podman
  - run
  - --rm
  - --privileged
  - --net=host
  - --ipc=host
  - --ulimit
  - nofile=1024:4096
  - -v
  - /run/lock/lvm:/run/lock/lvm:z
  - -v
  - /var/run/udev/:/var/run/udev/:z
  - -v
  - /dev:/dev
  - -v
  - /etc/ceph:/etc/ceph:z
  - -v
  - /run/lvm/:/run/lvm/
  - -v
  - /var/lib/ceph/:/var/lib/ceph/:z
  - -v
  - /var/log/ceph/:/var/log/ceph/:z
  - --entrypoint=ceph-volume
  - dal13cephdash01:443/rhceph/rhceph-4-rhel8:latest
  - --cluster
  - ceph
  - lvm
  - batch
  - --bluestore
  - --yes
  - --prepare
  - /dev/sdb
  - /dev/sdc
  - /dev/sdd
  - /dev/sde
  - /dev/sdf
  - /dev/sdg
  - /dev/sdh
  - /dev/sdi
  - /dev/sdj
  - /dev/sdk
  - /dev/nvme0n1
  - /dev/nvme1n1
  - --report
  - --format=json
  msg: non-zero return code
  rc: 1
  stderr: |-
    WARNING: The same type, major and minor should not be used for multiple devices.
    WARNING: The same type, major and minor should not be used for multiple devices.
    WARNING: The same type, major and minor should not be used for multiple devices.
    WARNING: The same type, major and minor should not be used for multiple devices.
    WARNING: The same type, major and minor should not be used for multiple devices.
    WARNING: The same type, major and minor should not be used for multiple devices.
    WARNING: The same type, major and minor should not be used for multiple devices.
 --> Aborting because strategy changed from bluestore.MixedType to bluestore.SingleType after filtering    
```
What you expected to happen:
We expect playbook to continue and complete without any errors/skip this step as OSD's are already configured and running.

Share your group_vars files, inventory

**Environment**:
* OS (e.g. from /etc/os-release): Ceph Ansible running on RHEL 7 and Ceph Cluster running on 8.0
* Kernel (e.g. `uname -a`):
Ceph-Ansible machine: Linux dal13cephdash01.sdslab.net 3.10.0-1062.1.1.el7.x86_64 #1 SMP Tue Aug 13 18:39:59 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Ceph cluster machiens: Linux dal13cephosd01 4.18.0-80.el8.x86_64 #1 SMP Wed Mar 13 12:02:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

* Docker version if applicable (e.g. `docker version`): 
[root@dal13cephosd01 ~]# docker version
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Version:            1.4.2
RemoteAPI Version:  1
Go Version:         go1.12.6
OS/Arch:            linux/amd64

* Ansible version (e.g. `ansible-playbook --version`):
[root@dal13cephdash01 ceph-ansible]# ansible-playbook --version
ansible-playbook 2.8.6
  config file = /usr/share/ceph-ansible/ansible.cfg
  configured module search path = [u'/usr/share/ceph-ansible/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Jun 11 2019, 14:33:56) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

* ceph-ansible version (e.g. `git head or tag or stable branch`): https://github.com/ceph/ceph-ansible

* Ceph version (e.g. `ceph -v`): Natilus 4.0

**Comment by dsavineau** [comment]
Honestly that sounds more a ceph-volume issue than a ceph-ansible issue.

> `The same type, major and minor should not be used for multiple devices`

Are you using multipath with your devices ?

Could you run on one of your ceph osd node :
```console
podman run --rm --privileged --net=host --ipc=host --ulimit nofile=1024:4096 -v /run/lock/lvm:/run/lock/lvm:z -v /var/run/udev/:/var/run/udev/:z -v /dev:/dev -v /etc/ceph:/etc/ceph:z -v /run/lvm/:/run/lvm/ -v /var/lib/ceph/:/var/lib/ceph/:z -v /var/log/ceph/:/var/log/ceph/:z --entrypoint=ceph-volume dal13cephdash01:443/rhceph/rhceph-4-rhel8:latest --cluster ceph inventory
```

**Comment by ashoksangee** [comment]
These are local disk and no multipath.
Below is the requested output.

[root@dal13cephosd01 ~]# podman run --rm --privileged --net=host --ipc=host --ulimit nofile=1024:4096 -v /run/lock/lvm:/run/lock/lvm:z -v /var/run/udev/:/var/run/udev/:z -v /dev:/dev -v /etc/ceph:/etc/ceph:z -v /run/lvm/:/run/lvm/ -v /var/lib/ceph/:/var/lib/ceph/:z -v /var/log/ceph/:/var/log/ceph/:z --entrypoint=ceph-volume dal13cephdash01:443/rhceph/rhceph-4-rhel8:latest --cluster ceph inventory
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.

Device Path               Size         rotates available Model name
/dev/dm-10                139.00 GB    False   True
/dev/dm-11                3.64 TB      True    True
/dev/dm-12                139.00 GB    False   True
/dev/dm-13                3.64 TB      True    True
/dev/dm-14                139.00 GB    False   True
/dev/dm-15                3.64 TB      True    True
/dev/dm-16                139.00 GB    False   True
/dev/dm-17                3.64 TB      True    True
/dev/dm-18                139.00 GB    False   True
/dev/dm-19                3.64 TB      True    True
/dev/dm-20                139.00 GB    False   True
/dev/dm-21                3.64 TB      True    True
/dev/dm-22                139.00 GB    False   True
/dev/dm-3                 3.64 TB      True    True
/dev/dm-4                 139.00 GB    False   True
/dev/dm-5                 3.64 TB      True    True
/dev/dm-6                 139.00 GB    False   True
/dev/dm-7                 3.64 TB      True    True
/dev/dm-8                 139.00 GB    False   True
/dev/dm-9                 3.64 TB      True    True
/dev/nvme0n1              698.64 GB    False   False     INTEL SSDPED1K750GA
/dev/nvme1n1              698.64 GB    False   False     INTEL SSDPED1K750GA
/dev/sda                  931.00 GB    True    False     MR9361-8i
/dev/sdb                  3.64 TB      True    False     MR9361-8i
/dev/sdc                  3.64 TB      True    False     MR9361-8i
/dev/sdd                  3.64 TB      True    False     MR9361-8i
/dev/sde                  3.64 TB      True    False     MR9361-8i
/dev/sdf                  3.64 TB      True    False     MR9361-8i
/dev/sdg                  3.64 TB      True    False     MR9361-8i
/dev/sdh                  3.64 TB      True    False     MR9361-8i
/dev/sdi                  3.64 TB      True    False     MR9361-8i
/dev/sdj                  3.64 TB      True    False     MR9361-8i
/dev/sdk                  3.64 TB      True    False     MR9361-8i
[root@dal13cephosd01 ~]#

**Comment by dsavineau** [comment]
@alfredodeza any thoughts ?

**Comment by alfredodeza** [comment]
This message:

>  --> Aborting because strategy changed from bluestore.MixedType to bluestore.SingleType after filtering    

Happens when one creates OSDs based on a "mixed" strategy with solid and spinning drives, and then tries again but with just a single type of devices. The user might not understand that devices are already used, and therefore they are being excluded. In the log file on /var/lib/ceph/ceph-volume.log a few entries like this one should show:

> Ignoring devices already used by ceph: ....

In the inventory output, one can see that the dm-* devices are available but not the nvme ones, hence the change in strategy and the error.

This looks like a non-issue to me.

**Comment by ashoksangee** [comment]
I completely understand the issue and why it is switching back to single type however, we are not able to make any further changes to cluster using ansible in particular to OSD's. So this is the way ceph-ansible is designed to work in mixed environment?

**Comment by alfredodeza** [comment]
@ashoksangee it isn't that this is how ceph-ansible is designed. A storage administrator should try to manage a cluster in the most homogeneous way possible. It is unfeasible to expect tooling to support every combination possible, and *that* is a design choice of ceph-volume, which allows some automatic detection to ease the LVM handling at the cost of reducing support for every other non-compliant variation.

My recommendation would be to try and keep the same strategy. If you can't, then don't rely on the automatic behavior and pre-create the LVs. The ceph-volume tool will happily consume those and ceph-ansible has full support for this

**Comment by ashoksangee** [comment]
@alfredodeza I think your suggestion makes lot of sense. Thank you so much for your time.
