### ISSUE TITLE
meaningful naming convention for rbd image

### ISSUE THREAD

**Issue by coolpalani** [ceph/ceph-ansible#4759]
Hello Team,

We've integrated Ceph cluster storage with Kubernetes and provisioning volumes through rbd-provisioner. When we're creating volumes from yaml files in Kubernetes, pv > pvc > mounting to pod, In kubernetes end pvc are showing as meaningful naming convention as per yaml file defined. But in ceph cluster, rbd image name is creating with dynamic uid.

During troubleshooting time, this will be tedious to find exact rbd image. Please find the provisioning logs in below pasted snippet.

 `kubectl get pods,pv,pvc`
`NAME            READY   STATUS    RESTARTS   AGE`
`pod/sleepypod   1/1     Running   0          4m9s`

`NAME                                                        CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                         STORAGECLASS   REASON   AGE`
`persistentvolume/pvc-cd37d2d6-cecc-4a05-9736-c8d80abde7f5   1Gi        RWO            Delete           Bound    default/test-dyn-pvc                          ceph-rbd                4m9s`

`NAME                                 STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE`
`persistentvolumeclaim/test-dyn-pvc   Bound    pvc-cd37d2d6-cecc-4a05-9736-c8d80abde7f5   1Gi        RWO            ceph-rbd       4m11s`

**rbd-provisioner logs**

`I1121 10:59:15.009012       1 provision.go:132] successfully created rbd image "kubernetes-dynamic-pvc-f4eac482-0c4d-11ea-8d70-8a582e0eb4e2"
I1121 10:59:15.009092       1 controller.go:1087] provision "default/test-dyn-pvc" class "ceph-rbd": volume "pvc-cd37d2d6-cecc-4a05-9736-c8d80abde7f5" provisioned
I1121 10:59:15.009138       1 controller.go:1101] provision "default/test-dyn-pvc" class "ceph-rbd": trying to save persistentvvolume "pvc-cd37d2d6-cecc-4a05-9736-c8d80abde7f5"
I1121 10:59:15.020418       1 controller.go:1108] provision "default/test-dyn-pvc" class "ceph-rbd": persistentvolume "pvc-cd37d2d6-cecc-4a05-9736-c8d80abde7f5" saved
I1121 10:59:15.020476       1 controller.go:1149] provision "default/test-dyn-pvc" class "ceph-rbd": succeeded
I1121 10:59:15.020802       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"test-dyn-pvc", UID:"cd37d2d6-cecc-4a05-9736-c8d80abde7f5", APIVersion:"v1", ResourceVersion:"24545639", FieldPath:""}): type: 'Normal' reason: 'ProvisioningSucceeded' Successfully provisioned volume pvc-cd37d2d6-cecc-4a05-9736-c8d80abde7f5`

**rbd image details in Ceph cluster end**

`rbd -p kube ls  --long`
`NAME                                                        SIZE    PARENT FMT PROT LOCK`
`kubernetes-dynamic-pvc-f4eac482-0c4d-11ea-8d70-8a582e0eb4e2   1 GiB          2`

is there way to setup proper naming convention for rbd image as well during kubernetes deployment itself.

Kubernetes version: `v1.15.5`
Ceph cluster version: `14.2.2 nautilus (stable)`

**Comment by dsavineau** [comment]
What's the relationship with ceph-ansible here ?

**Comment by coolpalani** [comment]
@dsavineau 

As mentioned in https://ceph.io/irc/  I tried to connect in IRC channel but none of them in channel and respond back. Could you please let me know the way for reach out Ceph community to discuss this feature requirement.

**Comment by dsavineau** [comment]
You could try the mailing list as mentioned on https://ceph.io/irc/

I'm closing this because it's unrelated to the ceph-ansible project.
