### ISSUE TITLE
osd memory target calculation seems incorrect

### ISSUE THREAD

**Issue by JoshuaLyle** [ceph/ceph-ansible#4763]
On `mimic` using `stable/3.2` on commit bf8bd4c0f1337d0867b319139a5f701758078df3. I didn't see modifications to the relevant lines in the `master` branch so I believe this issue should still persist.

The calculation used to set `osd_memory_target` in the line below seems to be incorrect. With several machines, each with 64GB of ram and 1 OSD in each, this calculation set `osd_memory_target` to 48GB of RAM and caused massive resident memory in my OSD daemon. I had to manually edit the .j2 to use the `osd_memory_target` in `all.yml` to set it to the reasonable 4GB default.

https://github.com/ceph/ceph-ansible/blob/c878e99589bde0eecb8ac72a7ec8bc1f66403eeb/roles/ceph-config/templates/ceph.conf.j2#L103

I haven't investigated how the line below calculates the value but it results in a memory value that is way too large in my case.

**Comment by dsavineau** [comment]
> The calculation used to set osd_memory_target in the line below seems to be incorrect.

It's no incorrect. It's just not adapted to your setup.

On non HCI deployment the memory target of all OSD on the same node is 70% of the RAM.
This is control via the `non_hci_safety_factor` variable (default to 0.7).
If this value is too high for you then you can still override it in the group_vars [1]
Setting this value to 0 will fallback to the 4G RAM configuration or alternatively reduce the ratio to 0.1 or 0.2.

```yaml
non_hci_safety_factor: 0
```

If this value is still too high (4G) for you then you can also set the `osd memory target` value via the `ceph_conf_overrides` variable.

```yaml
ceph_conf_overrides:
  osd:
    osd memory target: 1073741824
```

[1] https://github.com/ceph/ceph-ansible/blob/master/group_vars/all.yml.sample#L375
