### ISSUE TITLE
bug: ansible.cfg not ssh portable at present

### ISSUE THREAD

**Issue by ppbrown** [ceph/ceph-ansible#4826]
disclaimer: Im very new at ceph and ceph-ansible.
but not at linux. Been a UNIX sysadmin for 20 years.

just grabbed ceph-ansible 4.0.5 release. on Centos 7.7.

I'm getting a bunch of connect errors when I try to do anything with ceph-ansible

The very first one is

```console
[WARNING]: Unhandled error in Python interpreter discovery for host localhost:
Failed to connect to the host via ssh: Permission denied (publickey,gssapi-
keyex,gssapi-with-mic,password).
```

Your delivered ansible.cfg is screwing things up for me.

doing an ansible ping OUTSIDE your directory works fine.
but inside it, bad things.

the ping CONNECTS, at least, when I add an override, of
  -c paramiko
but it then throws nasty python errors after connect.
```console
$ ansible -c paramiko -k -m ping localhost
SSH password: 
Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/__init__.py", line 851, in emit
    msg = self.format(record)
  (blahblah more errors)
```

Commenting out the ssh_connection block at the end of ansible.cfg, gets rid of the problem entirely.
No problems connecting, and no wierd python errors.

Please find a DIFFERENT fix for  ""issue 11536", as mentioned in the comments for that block.

**Comment by dsavineau** [comment]
> ```
> [WARNING]: Unhandled error in Python interpreter discovery for host localhost:
> Failed to connect to the host via ssh: Permission denied (publickey,gssapi-
> keyex,gssapi-with-mic,password).
> ```

Well it seems that you're not allowed to ssh to your node due to the ssh permission denied error.

Also if you're using a node with localhost then you can use the `local` connection method instead of the default ssh.

https://docs.ansible.com/ansible/latest/plugins/connection.html

**Comment by ppbrown** [comment]
I'm confused. Did you only bother reading half the bug report or something?
I wrote how when I'm outside the influence of ansible.cfg I have no problems connecting.
So how is it that I'm "not allowed to ssh"?

If you need even more clarity:

$ ssh localhost echo i am fine
xxxx@localhost's password: 
i am fine
$

As I mentioned in the original writeup, all problems go away, when I remove the block added for the 11563 workaround.
It seems wrong to "fix" an issue for one group of people, by making things more difficult for another group of people.

**Comment by dsavineau** [comment]
> I'm confused. Did you only bother reading half the bug report or something?

Yes I did, only one word every two words.

> So how is it that I'm "not allowed to ssh"?

The ansible output isn't clear enough ?
```console
Failed to connect to the host via ssh: Permission denied (publickey,gssapi-
keyex,gssapi-with-mic,password)
```
Could you run the command with more verbosity ?
What's the host configuration in the inventory ?

Also using ssh backend for a local node doesn't make any sense. The local connection is more appropriate

> the ping CONNECTS, at least, when I add an override, of -c paramiko

Because paramiko connection doesn't use the ssh_connections block in the configuration.

> As I mentioned in the original writeup, all problems go away, when I remove the block added for the 11563 workaround.

First the workaround mentioned is only for the `control_path` variable not the `ssh_connection` block

> It seems wrong to "fix" an issue for one group of people, by making things more difficult for another group of people.

Which group of people ? I'm not sure to understand...
If the default ansible.cfg doesn't match with your infrastructure setup then feel free to:
- modify it
- override the value via the ansible environment variables.

**Comment by ppbrown** [comment]
Additional information.

when I downgraded from ansible 2.9 to ansible 2.8, 
  ansible -k -m ping  localhost

now works. So that's nice.  
But the full site.yml run still fails with the old error.

TASK [check for python] ***************************************************************************
Friday 06 December 2019  13:28:45 -0800 (0:00:00.302)       0:00:00.302 ******* 
failed: [localhost] (item=/usr/bin/python) => 
  ansible_loop_var: item
  item: /usr/bin/python
  msg: |-
    Data could not be sent to remote host "localhost". Make sure this host can be reached over ssh: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
  unreachable: true


Note that our business disallows use of stored public keys for auth. It needs to be live input.
I'm guessing you folks only tested the change via stored public keys.


**Please note:**

When I just remove

 -o PreferredAuthentications=publickey

then it works okay for me.

**Comment by guits** [comment]
@ppbrown take it easy, I don't really like the way you talk here, you won't gain much attention this way.

> It seems wrong to "fix" an issue for one group of people, by making things more difficult for another group of people.

I'm unsure your use-case is the most common one, why would we change it given that it suits for a majority...? 

In any case, this file is intended to be modified to fit your infrastructure.

**Comment by ppbrown** [comment]
As a software writer, my personal ethos is to try to write software
and configs that work for everyone out of the box, where possible.
This seems like a case where that is possible.

At minimum, it would be beneficial to at least add a comment in that
section along the lines of, "If you arent using keys for auth, then
you will need to modify or remove this section."

Ideal would be to either add an explicit check calling out, "hey you
arent using keys you need to do X", or better yet, automatically
adjust.
I'm not an ansible expert, but I would hope there is some kind of
check for "did the user use the -k flag?"

Or contrariwise, only enable those options in that block, if you
detect that the user is NOT using -k flag.

**Comment by guits** [comment]
fair enough, I just wish you would have argued like this instead of looking unpleasant at first glance.
