### ISSUE TITLE
_monitor_addresses is undefined

### ISSUE THREAD

**Issue by ppbrown** [ceph/ceph-ansible#4827]
ceph-ansible 4.0.5
centos 7.7
ansible 2.9
ceph nautilus

both test.yml and site.yml fail complaining about this, although in slightly different ways.
site.yml fails with:

TASK [ceph-facts : set_fact _current_monitor_address] **************************
Friday 06 December 2019  09:56:23 -0800 (0:00:00.151)       0:00:22.667 ******* 
fatal: [localhost]: FAILED! => 
  msg: '''_monitor_addresses'' is undefined'

test.yml fails with:

TASK [ceph-mon : start the monitor service] ************************************
Friday 06 December 2019  09:17:43 -0800 (0:00:00.181)       0:01:09.085 ******* 
fatal: [localhost]: FAILED! => 
  msg: |-
    The task includes an option with an undefined variable. The error was: 'monitor_name' is undefined

Seems like this should be kinda impossible, since 
roles/ceph-facts/tasks/facts.yml
seems to define it one way or another, so this is weird.

I have
mon_use_fqdn: false 

set, from all.yml
So, it SHOULD be calling
  set_fact:
    monitor_name: "{{ ansible_hostname }}"

and yet... ansible is claiming monitor_name not set???

Edit: additional info:
Given the three choices of 
"You must define either monitor_interface, monitor_address or monitor_address_block.
"
I chose
monitor_address: 0.0.0.0

monitor_address: 0.0.0.0

**Comment by dsavineau** [comment]
> ceph-ansible 4.0.5
> centos 7.7
> ansible 2.9
> ceph nautilus

We don't support ansible 2.9 in ceph-ansible 4.0.x. Only ansible 2.8

https://docs.ceph.com/ceph-ansible/master/#releases

> monitor_address: 0.0.0.0

If you choose `monitor_address` then you need to specify the IP address of the monitor node

**Comment by ppbrown** [comment]
aha.

i finally ran into an ansible version check waaaay down in the automated
checklist.
it would be nice if you guys moved that up near the top?
probably save a lot of confusion.

**Comment by ppbrown** [comment]
> > monitor_address: 0.0.0.0
> 
> If you choose `monitor_address` then you need to specify the IP address of the monitor node

aha. Thank you. that got me through to the next hurdle.

For userfriendliness, I might suggest adding a more eplicit comment about "you have to set the specific IP address", since 
"bind to 0.0.0.0"
is a fairly common practice in other software configs.

Better yet though, could be to simply replace

   monitor_address: 0.0.0.0
with
   monitor_address: #.#.#.#

or x.x.x.x, or similar.

**Comment by dsavineau** [comment]
> aha. i finally ran into an ansible version check waaaay down in the automated checklist. it would be nice if you guys moved that up near the top? probably save a lot of confusion.

https://github.com/ceph/ceph-ansible/pull/4829

**Comment by ppbrown** [comment]
Thanks

**Comment by ppbrown** [comment]
oh wait. closed prematurely. should leave it open for the 0.0.0.0 issue I think.

**Comment by guits** [comment]
I think changing the default value for `monitor_address` is fine
