### ISSUE TITLE
common_single_host_mode not being used consistently? quorum check fails

### ISSUE THREAD

**Issue by ppbrown** [ceph/ceph-ansible#4828]
centos 7.7
ceph nautilus
ansible 2.8
ceph-ansible 4.0.5

I have set

common_single_host_mode: true

but setup is failing, waiting for my single monitor, to establish a quorum?

ASK [ceph-mon : start the monitor service] *******************************************************
Friday 06 December 2019  12:46:46 -0800 (0:00:00.148)       0:01:17.516 ******* 
ok: [localhost]

TASK [ceph-mon : include_tasks ceph_keys.yml] *****************************************************
Friday 06 December 2019  12:46:48 -0800 (0:00:01.955)       0:01:19.472 ******* 
included: /home/xxx/ceph-ansible-4.0.5/roles/ceph-mon/tasks/ceph_keys.yml for localhost

TASK [ceph-mon : waiting for the monitor(s) to form the quorum...] ********************************
Friday 06 December 2019  12:46:48 -0800 (0:00:00.280)       0:01:19.752 ******* 
fatal: [localhost]: FAILED! => 
  msg: |-
    The conditional check '(ceph_health_raw.stdout | length > 0) and (ceph_health_raw.stdout | default('{}') | from_json)['state'] in ['leader', 'peon']
    ' failed. The error was: error while evaluating conditional ((ceph_health_raw.stdout | length > 0) and (ceph_health_raw.stdout | default('{}') | from_json)['state'] in ['leader', 'peon']
    ): 'dict object' has no attribute 'stdout'

**Comment by dsavineau** [comment]
please share the full ansible logs with verbosity, inventory and all variables defined in group_vars/*.yml

**Comment by ppbrown** [comment]
okay. I'll start with the inventory, aka hosts file. whichis nothing more than:


[mons]
localhost


[mgrs]
localhost

[mdss]
localhost

[grafana-server]
localhost

**Comment by ppbrown** [comment]
attempting to attach my all.yml file...

file:///tmp/all.yml.upload

**Comment by ppbrown** [comment]
[all.yml.txt](https://github.com/ceph/ceph-ansible/files/3934016/all.yml.txt)

**Comment by ppbrown** [comment]
what are you specifically asking for, when you ask for, 
" full ansible logs with verbosity," ?
Do you just want me to save and upload the output of

ansible-playbook -v -kK site.yml

?

**Comment by ppbrown** [comment]
If so, then here that is.
[ansible.log](https://github.com/ceph/ceph-ansible/files/3934141/ansible.log)

**Comment by ppbrown** [comment]
mons.yml file:


---


dummy:


mon_group_name: mons

monitor_secret: "{{ monitor_keyring.stdout }}"
admin_secret: 'XXXXXX'

client_admin_ceph_authtool_cap:
  mon: allow *
  osd: allow *
  mds: allow *
  mgr: allow *

crush_rule_config: false

crush_rule_hdd:
  name: HDD
  root: HDD
  type: host
  default: false

crush_rule_ssd:
  name: SSD
  root: SSD
  type: host
  default: false

**Comment by ppbrown** [comment]
workaround:

I just took the whole task
name: waiting for the monitor(s) to form the quorum.

out.
Things happily are proceeding after that.

**Comment by ppbrown** [comment]
I found the problem.
A few other things were failing down the line.
I noticed that the common problem was that they all had a
{{ container_exec_cmd }}

clause.

in the all.yml file,  there are two lines:
#container_exec_cmd:
#docker: false

I thought I had to define the first one, to allow me to define docker as false.
when I commented out both lines, everything was happier.


It could be helpful if you added a comment, right below,
##########
# DOCKER #
##########


to say, 

#  if you are not using docker, leave this entire section commented out.

**Comment by guits** [comment]
@ppbrown do you mind sending a PR for that?
Thanks!
