### ISSUE TITLE
ceph-ansible documentation: purpose missing

### ISSUE THREAD

**Issue by ppbrown** [ceph/ceph-ansible#4845]
Looking at https://docs.ceph.com/ceph-ansible/master/
All it says as a summary is,

"ceph-ansible¶
Ansible playbooks for Ceph, the distributed filesystem."

Some people are used to using ansible as a touch-up system, to bring existing hosts in line. So they may expect running ceph-ansible to be safe to run on existing configs.

If ceph-ansible is purposed ONLY for from-scratch cluster configuration, it would be nice to warn people up front, by stating that at the top of the docs

If on the other hand, ceph-ansible is meant for both initial cluster configuration, AND adding additional systems into an existing cluster... it would be nice to see more explicit docs on how to use this safe mode.
(and warnings at the top, "go use safe mode if you have an existing cluster")

So far, my experience has been that by default, ceph-ansible completely blows away all existing OSD and recreates from scratch. and actually, the entire ceph.conf file, basically.
I haven't found a way to usefully change that yet.

(I've tried tinkering a little with the generate_fsid and fsid values, to attempt to incrementally add in new features to my experimental cluster, but no luck. So far, either it does nothing, or it blows everything away. I havent found a middle way yet)

(Edit: hmm. previously, I noticed it calling "ceph-volume lvm zap" on every run. but now it's not doing that. for some reason.)

**Comment by ppbrown** [comment]
More details, going from memory: in my "messes up my configuration" times, it kept regenerating fsid.
The fetch directory kept getting new config files with a new fsid.
Expected behaviour to me, would be "is there an fsid in /etc/cep/ceph.conf already? if so then use it".
but it wasnt.

**Comment by dsavineau** [comment]
> More details, going from memory: in my "messes up my configuration" times, it kept regenerating fsid.
The fetch directory kept getting new config files with a new fsid.

Are you using `generate_fsid: true` ? if yes then that's expected.

**Comment by ppbrown** [comment]
I took the comments to mean "generate an fsid if one is missing".
not "make a new one every time, reguardless".

If that is its expected behaviour, then some more detailed comments would be nice. both for 
"This is what it actually DOES", and
"This is why you would ever want to turn this thing on".

Personally, I am having difficulty understanding why someone would ever deliberately do that.

**Comment by dsavineau** [comment]
> I took the comments to mean "generate an fsid if one is missing". not "make a new one every time, reguardless".

That's it. In fact the fsid is only generated if there's no ceph cluster up & running otherwise the fsid value will be read from the current cluster (not from the ceph.conf file but from the ceph status).

If it's not what you can see then we need to understand why so please share the logs and configuration files.

**Comment by ppbrown** [comment]
Aha.

`That's it. In fact the fsid is only generated if there's no ceph cluster up & running otherwise the fsid value will be read from the current cluster (not from the ceph.conf file but from the ceph status).
`

Can I suggest that you add in a check for "if there's an fsid in ceph.conf, dont mess with it" reguardless of whether you can talk to the running cluster ?
I suspect that may be what was happening.

consider the case where a new ceph admin such as myself may have gotten a very bare-bones ceph cluster running... but then temporarily screwed up auth or something.
in those cases, really not a good idea to generate a whole new fsid and config, just because you cant talk to a running cluster.
