### ISSUE TITLE
purge-cluster.yml doesn't remove all services

### ISSUE THREAD

**Issue by Hobadee** [ceph/ceph-ansible#4850]
**Bug Report**

## What happened:
When using the `purge-cluster.yml` playbook, not all services are removed.  Some are stopped but not removed, and others aren't even stopped.

Services left behind: (Clipped output of `systemctl`)
```
● ceph-osd@0.service    not-found failed failed    ceph-osd@0.service
● ceph-osd@1.service    not-found failed failed    ceph-osd@1.service
● ceph-osd@5.service    not-found failed failed    ceph-osd@5.service
● node_exporter.service    not-found failed failed    node_exporter.service
● rbd-target-api.service    not-found active running   rbd-target-api.service
  rbd-target-gw.service    loaded    active running   Setup system to export rbd images through LIO
  tcmu-runner.service    loaded    active running   LIO Userspace-passthrough daemon
  system-ceph\x2dmgr.slice    loaded    active active    system-ce
  system-ceph\x2dmon.slice    loaded    active active    system-ce
  system-ceph\x2dosd.slice    loaded    active active    system-ce
```

## What you expected to happen:
All Ceph related services should be stopped and removed.

## How to reproduce it (minimal and precise):
Deploy a cluster using ceph-ansible, then remove it using purge-cluster.yml

### all.yml
```
---
dummy:
fetch_directory: fetch/
mon_group_name: mons
osd_group_name: osds
iscsi_gw_group_name: iscsigws
grafana_server_group_name: grafanaserver
configure_firewall: True
ceph_mon_firewall_zone: public
ceph_mgr_firewall_zone: public
ceph_osd_firewall_zone: public
ceph_iscsi_firewall_zone: public
ceph_dashboard_firewall_zone: public
centos_package_dependencies:
  - epel-release
  - libselinux-python
ceph_origin: repository
ceph_repository: community
ceph_stable_release: nautilus
monitor_address_block: 10.7.11.0/24
ip_version: ipv4
public_network: 10.7.11.0/24
cluster_network: 10.7.12.0/24
ceph_tcmalloc_max_total_thread_cache: 0
```

### iscsigws.yml
```
---
dummy:
gateway_iqn: "<redacted>"
```

### mgrs.yml
```
dummy:
ceph_mgr_modules:
  - dashboard
  - prometheus
ceph_mgr_packages:
  - ceph-mgr
  - ceph-mgr-dashboard
  - ceph-mgr-diskprediction-local
```

## Environment:
* OS (e.g. from /etc/os-release):
    NAME="CentOS Linux"
    VERSION="7 (Core)"
    ID="centos"
    ID_LIKE="rhel fedora"
    VERSION_ID="7"
    PRETTY_NAME="CentOS Linux 7 (Core)"
    ANSI_COLOR="0;31"
    CPE_NAME="cpe:/o:centos:centos:7"
    HOME_URL="https://www.centos.org/"
    BUG_REPORT_URL="https://bugs.centos.org/"

    CENTOS_MANTISBT_PROJECT="CentOS-7"
    CENTOS_MANTISBT_PROJECT_VERSION="7"
    REDHAT_SUPPORT_PRODUCT="centos"
    REDHAT_SUPPORT_PRODUCT_VERSION="7"

* Kernel (e.g. `uname -a`): Linux <redacted> 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

* Docker version if applicable (e.g. `docker version`):
    Client:
     Version:         1.13.1
     API version:     1.26
     Package version: docker-1.13.1-103.git7f2769b.el7.centos.x86_64
     Go version:      go1.10.3
     Git commit:      7f2769b/1.13.1
     Built:           Sun Sep 15 14:06:47 2019
     OS/Arch:         linux/amd64
    
    Server:
     Version:         1.13.1
     API version:     1.26 (minimum version 1.12)
     Package version: docker-1.13.1-103.git7f2769b.el7.centos.x86_64
     Go version:      go1.10.3
     Git commit:      7f2769b/1.13.1
     Built:           Sun Sep 15 14:06:47 2019
     OS/Arch:         linux/amd64
     Experimental:    false

* Ansible version (e.g. `ansible-playbook --version`): 2.8.2
* ceph-ansible version (e.g. `git head or tag or stable branch`): v4.0.5
* Ceph version (e.g. `ceph -v`):

**Comment by guits** [comment]
I'm not sure to understand, you are talking about `purge-cluster.yml`, you are providing docker version and I see you shared this:
```
ceph_origin: repository
ceph_repository: community
ceph_stable_release: nautilus
```

it's a bit confusing. please, clarify.

**Comment by Hobadee** [comment]
It's a bare metal install, but I noticed docker was installed and had some services running.  (Prometheus, alertmanager, grafana, and node-exporter)  Since it's requested information, I gave it.

**Comment by dsavineau** [comment]
I've started to investigate this issue and create a PR for that

https://github.com/ceph/ceph-ansible/pull/4856
