### ISSUE TITLE
mon demon ignoring monitor_address

### ISSUE THREAD

**Issue by ppbrown** [ceph/ceph-ansible#4851]
ansible 2.8. 
ceph-ansible 4.0.5. 
ceph nautilus

previously I was trying things with a single interface. now I'm trying with a more real physical config, and multiple nics.
starting from scratch.

I've specified monitor_address: as a specific IP addr in all.yml

that IP address is successfully showing up in /etc/ceph/ceph.conf

but the actual mon demon listening on port 3300.. is listening on a DIFFERENT IP address.
It happens to be listening on the first IP address returned by "Ip addr".
and ONLY that IP address.

Seems like a bug to me.

If this is actually "working as designed", and it is expected that sysadmin is *required* to specify interface name in the case of having multiple interfaces... then one might call this a documentation bug.

currently, the comments, aka documetation, say,

```
"If you want to specify for each monitor which address the monitor will bind to you can set it in your **inventory host file** by using 'monitor_address' variable.
 Preference will go to monitor_address if both monitor_address and monitor_interface are defined.

```

but.. I DID specify monitor_address.
and it is not affecting the address the monitor binds to.

(where is the actual demon configured? I looked through 
 /etc/systemd/system/ceph-mon.target.wants/ceph-mon@corpceph1n01.service 
and
  /etc/sysconfig/ceph
but didnt see anything promising.
)

**Comment by dsavineau** [comment]
Could you share the full ansible log, inventory and variables defined in group_vars/*.yml ?

**Comment by ppbrown** [comment]
I dont think I can share actual internal IPs publicly.... and unfortunately
this is all about specific IP address use :-/

Might you tell me first if it is expected for the ceph-mon demon to bind to
the monitor_address, regardless of how many physical interfaces there are,
and in what order?

**Comment by dsavineau** [comment]
if you specify `monitor_address` the ceph-mon daemon will bind on that IP address.
if you specify `monitor_interface` the ceph-mon daemon will bind on the first IP address present on that interface.
if you specify `monitor_address_block` the ceph-mon daemon will bind on the first IP address present  in that CIDR range present on the node.

**Comment by ppbrown** [comment]
doing a quick grep through roles/ceph-mon/tasks, I dont see any mention of
monitor_address
monitor_interface

only monitor_name.

Which yml file is supposed to handle passing on monitor_interface to the
actual running mon demon configs?

I see
templates/ceph-mon.service.j2

but that looks nothing like the actually deployed service file,

 /etc/systemd/system/ceph-mon.target.wants/ceph-mon@HOSTNAME.service  ->
  /usr/lib/systemd/system/ceph-mon@.service

Hmmm.

I see a very short "SYSTEMD" commented out section in mons.yml.sample.
When I read the comments, it didnt seem relevant.

Is there something I need to set there to make the running mon demon
actually know about the monitor_address set with ceph-ansible?

**Comment by dsavineau** [comment]
> Which yml file is supposed to handle passing on monitor_interface to the
>actual running mon demon configs?

`monitor_address`, `monitor_interface` and `monitor_address_block` variables are consume in the ceph-facts role to generate the `_monitor_addresses` and `_current_monitor_address` facts which are used later during the ceph-config/ceph-mon roles.

https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-facts/tasks/set_monitor_address.yml

> I see templates/ceph-mon.service.j2

It's only for containerized deployment otherwise this file comes from the ceph-mon package.

**Comment by ppbrown** [comment]
Hmm.

weird.

for what it's worth, I tried using ceph-deploy to purge the machine.
it came up with a working system by default... interestingly,
defaulting to using the 10gig interface, instead of the first listed
1gig interface.

ran ceph-deploy purge again.
then  ran ceph-ansible.
Same problem of the demon coming up listening to 1gig IP address
instead of the 10gig IP specified in the ceph.conf file.


I dont see any normal config file its' using. So I guess it's all
about how the "monmap" info gets put together at bootstrap time.
judging by https://docs.ceph.com/docs/master/rados/operations/add-or-rm-mons/

**Comment by dsavineau** [comment]
> ran ceph-deploy purge again.

There's a ceph-ansible for this.

https://github.com/ceph/ceph-ansible/blob/master/infrastructure-playbooks/purge-cluster.yml

You probably have leftovers from a previous deployment.

**Comment by ppbrown** [comment]
except that ceph-deploy purge plus purgedata would have taken care of any
leftovers shouldn’t it?

unless you are saving state in the ceph-ansible tree.
could that be the problem?

**Comment by dsavineau** [comment]
> except that ceph-deploy purge plus purgedata would have taken care of any leftovers shouldn’t it?

I don't know, I only use ceph-ansible

> unless you are saving state in the ceph-ansible tree. could that be the problem?

There's the fetch directory created at the root ceph-ansible directory which should be deleted by the purge-cluster.yml cluster.

**Comment by ppbrown** [comment]
fetch directory is empty.

**Comment by dsavineau** [comment]
Could you try to remove the facts directory ?

**Comment by ppbrown** [comment]
rather than just removing (~/ansible/facts/HOSTNAME), how about we examine what's in there.

The IP related chunks are not ceph or ceph-ansible related. They are:

"ansible_all_ipv4_addresses":
   .x.x.x.x
ansible_default_ipv4"
   x.x.x.x
ansible_device_links:
   ansible_NICNAME:
      ipv4:
         x.x.x.x


Some of them are in "desirable" order. and some are not.
If ceph-ansible is pulling from any of those, instead of from the user-supplied .yml files, I would suggest that be rectified.

**Comment by dsavineau** [comment]
> If ceph-ansible is pulling from any of those, instead of from the user-supplied .yml files, I would suggest that be rectified.

As mentioned previously, the IP address is only get from the facts when using `monitor_interface` or `monitor_address_block` variables.

In your case, you said you're using `monitor_address` so it should use the value that you've set.

And again, it's difficult to debug this without logs and configuration.
