### ISSUE TITLE
comments about separate WAL devs in osds.yml.sample

### ISSUE THREAD

**Issue by ppbrown** [ceph/ceph-ansible#4853]
ceph-ansible 4.0.5

there's a bunch of historical comments in group_vars/osds.yaml.sample, telling people about special options such as

bluestore_wal_devices: []

and fancyschmancy lvm_volume layouts.

Thing is though... these days, they are almost completely unneccesary.
ceph nautilus in bluestore mode, at least, lets you just give all the devices to ceph-volume -batch...
and then it will figure out, "oh, this is an SSD. I'm going to use it just for caching,etc".

its probably good to leave in a comment about, "if you REALLY want to hand tune things, you can do it this way", but I would suggestion the top level default commented bit should encourage users to just dump all their devs in the devices: array.

I can submit another comment pull request if you like.  but mine will be another very short one at the top, rather than  a full restructuring. figure I'd leave that kind of stuff to you guys.

**Comment by ppbrown** [comment]
except there also needs to be some missing piece of information added.
It worked great for me... ONE TIME.

but now any time I try to run it I get this error:

``fatal: [HOSTNAME]: FAILED! => changed=false 
  cmd:
  - ceph-volume
  - --cluster
  - ceph
  - lvm
  - batch
  - --bluestore
  - --yes
  - /dev/sda
  - /dev/sdb
  - /dev/sdd
  - /dev/sde
  - /dev/sdf
  - /dev/sdg
  - /dev/sdh
  - /dev/sdi
  - /dev/sdj
  - /dev/sdk
  - --report
  - --format=json
  msg: non-zero return code
  rc: 1
  stderr: --> Aborting because strategy changed from bluestore.MixedType to bluestore.SingleType after filtering
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
``

**Comment by guits** [comment]
could you share your ceph.conf ?

**Comment by ppbrown** [comment]
my ceph.conf? huh, okay. its pretty short.
right now there are only two OSD hosts, and a single mon. which is running on one of the OSDs.
no gateways or anything yet.


```
# Please do not change this file directly since it is managed by Ansible and wil
l be overwritten
[global]
cluster network = 0.0.0.0/0
fsid = ###########-0495-4b30-a6ec-126a77bb2d30
mon host = [v2:x.x.x.x:3300,v1:x.x.x.x:6789]
mon initial members = HOSTNAME
osd pool default crush rule = -1
public network = 0.0.0.0/0

```

if you're interested, ceph -s says:
```

$ sudo ceph -s
[sudo] password for xxxxxx:
  cluster:
    id:     xxxxx-0495-4b30-a6ec-126a77bb2d30
    health: HEALTH_WARN
            Degraded data redundancy: 2/4 objects degraded (50.000%), 1 pg degraded, 256 pgs undersized

  services:
    mon: 1 daemons, quorum HOSTNAME (age 15h)
    mgr: HOSTNAME(active, since 15h)
    osd: 13 osds: 13 up (since 15h), 13 in (since 15h)

  data:
    pools:   1 pools, 256 pgs
    objects: 1 objects, 19 B
    usage:   345 GiB used, 24 TiB / 24 TiB avail
    pgs:     2/4 objects degraded (50.000%)
             255 active+undersized
             1   active+undersized+degraded

```
