### ISSUE TITLE
Error, when "ceph-ansible" trying to create user for dashboard but user already exists.

### ISSUE THREAD

**Issue by enter2608** [ceph/ceph-ansible#4902]
**Bug Report**

_What happened:_
I'm upgrading ceph using ceph-ansible. It crashes with following message:

TASK [ceph-dashboard : get the rgw access and secret keys] *********************************************************************************************************
fatal: [cephsrv1-ka-8d6d.storage]: FAILED! => {"msg": "the field 'args' has an invalid value ({u'rgw_secret_key': u\"{{ (rgw_user_output.stdout | from_json)['keys'][0]['secret_key'] }}\", u'rgw_access_key': u\"{{ (rgw_user_output.stdout | from_json)['keys'][0]['access_key'] }}\"}), and could not be converted to an dict.The error was: No JSON object could be decoded\n\nThe error appears to be in '/deploy/ceph-ansible/roles/ceph-dashboard/tasks/configure_dashboard.yml': line 139, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n - name: get the rgw access and secret keys\n ^ here\n"}

_What you expected to happen:_
Finish upgrade without error :-)

How to reproduce it (minimal and precise):
We are using existing, production ceph 14.2.4 installed/upgraded in past by ceph-ansible 4.0.0. We upgraded ceph-ansible to 4.0.6 and we want to upgrade cluster to ceph 14.2.5 using site.yml. The same when we execute ceph-ansible site.yml playbook after upgrade. In both cases ceph-ansible crashes.
Ceph-ansible trying to create user for dashboard but user already exists.

_Share your group_vars files, inventory_
It is not necessary in my opinion, look at the end of bug description: my solution proposal

**Environment**:
* OS (e.g. from /etc/os-release): 18.04.3 LTS
* Kernel (e.g. `uname -a`): 4.15.0-74-generic
* Docker version if applicable (e.g. `docker version`): i'm not using docker
* Ansible version (e.g. `ansible-playbook --version`): 2.8.7
* ceph-ansible version (e.g. `git head or tag or stable branch`): v4.0.6
* Ceph version (e.g. `ceph -v`): 14.2.5

_Solution proposal:_
I replaced part of ceph-ansible beginning from  line
https://github.com/ceph/ceph-ansible/blob/v4.0.6/roles/ceph-dashboard/tasks/configure_dashboard.yml#L130
to line 141 with following:

    - name: get radosgw system user
      command: "timeout --foreground -s KILL 20 {{ container_exec_cmd }} radosgw-admin --cluster {{ cluster }} user info --uid={{ dashboard_rgw_api_user_id }}"
      register: rgw_user_output_get
      delegate_to: "{{ groups[mon_group_name][0] }}"
      run_once: true
      failed_when: false

    - name: create radosgw system user
      command: "timeout --foreground -s KILL 20 {{ container_exec_cmd }} radosgw-admin --cluster {{ cluster }} user create --uid={{ dashboard_rgw_api_user_id }} --display-name='Ceph dashboard' --system"
      register: rgw_user_output
      until: rgw_user_output.rc == 0
      retries: 3
      delegate_to: "{{ groups[mon_group_name][0] }}"
      run_once: true
      when:
        - rgw_user_output_get.rc != 0

    - name: get the rgw access and secret keys
      set_fact:
        rgw_access_key: "{{ (rgw_user_output.stdout | from_json)['keys'][0]['access_key'] }}"
        rgw_secret_key: "{{ (rgw_user_output.stdout | from_json)['keys'][0]['secret_key'] }}"
      when:
        - rgw_user_output.rc is defined
        - rgw_user_output.rc == 0

    - name: get the rgw access and secret keys
      set_fact:
        rgw_access_key: "{{ (rgw_user_output_get.stdout | from_json)['keys'][0]['access_key'] }}"
        rgw_secret_key: "{{ (rgw_user_output_get.stdout | from_json)['keys'][0]['secret_key'] }}"
      when:
        - rgw_user_output_get.rc is defined
        - rgw_user_output_get.rc == 0

After change it works for me - I can deploy using site.yml on existing cluster without error.
Regards,
Wojtek

**Comment by yampilop** [comment]
I faced the same error and solved it changing the order of the environment files in the deployment command from:

```
...
-e /usr/share/openstack-tripleo-heat-templates/environments/ceph-ansible/ceph-ansible.yaml \
-e /usr/share/openstack-tripleo-heat-templates/environments/ceph-ansible/ceph-dashboard.yaml \
-e /usr/share/openstack-tripleo-heat-templates/environments/ceph-ansible/ceph-rgw.yaml \
-e /usr/share/openstack-tripleo-heat-templates/environments/ceph-ansible/ceph-mds.yaml \
...
```

to:

```
...
-e /usr/share/openstack-tripleo-heat-templates/environments/ceph-ansible/ceph-ansible.yaml \
-e /usr/share/openstack-tripleo-heat-templates/environments/ceph-ansible/ceph-rgw.yaml \
-e /usr/share/openstack-tripleo-heat-templates/environments/ceph-ansible/ceph-mds.yaml \
-e /usr/share/openstack-tripleo-heat-templates/environments/ceph-ansible/ceph-dashboard.yaml \
...
```
