### ISSUE TITLE
Provisioning a new cluster fails with ''running_mon'' is undefined'

### ISSUE THREAD

**Issue by administratorius** [ceph/ceph-ansible#4977]
**Bug Report**

What happened:

Provisioning a new cluster fails with an error:

```TASK [ceph-mgr : get keys from monitors] *******************************************************************************************************************************************************************
Wednesday 22 January 2020  10:17:56 +0000 (0:00:00.102)       0:03:40.982 *****
skipping: [osd1] => (item={u'path': u'/etc/ceph/ceph.client.admin.keyring', u'name': u'client.admin', u'copy_key': u'copy_admin_key'})
fatal: [osd1]: FAILED! =>
  msg: '''running_mon'' is undefined'
```

This is due the fact `running_mon` is not set on `ceph-racts` role

This is possibly introduced on this [commit](https://github.com/ceph/ceph-ansible/commit/86f3eeb717c7daac8c6330fdaa7f8a3c83f94b0d#diff-25c2ce69ca1d8f04f11ccaecae0a3c77R88)

The offending [line](https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-facts/tasks/facts.yml#L86):

`- item.rc == 1`

Proposed fix:

`- item.rc == 0`

What you expected to happen:

No errors

How to reproduce it (minimal and precise):
Run `ceph ansible` on a fresh cluster. Failed on two isolated occurences, with latest `ceph-ansible` commits

**Environment**:
* OS (e.g. from /etc/os-release): CentOS 7 and MacOS 10.15.2
* Ansible version (e.g. `ansible-playbook --version`): 2.8.4 and 2.9.2

**Comment by dsavineau** [comment]
what ceph-ansible version are you using ?

Because this should have been fixed by https://github.com/ceph/ceph-ansible/commit/2478a7b94856fc1b4639b4293383f7c3f2ae0f05

**Comment by dsavineau** [comment]
ok this looks a valid issue
