### ISSUE TITLE
tries to install pip, when it should install python-pip

### ISSUE THREAD

**Issue by Raboo** [ceph/ceph-ansible#499]
This playbook tries to install pip, when it should install python-pip.
In Ubuntu python package is named python-pip.
But this playbook has specified that for debian family it should install pip.

a bit of log:
```
TASK [ceph-mon : install pip on debian] ****************************************
fatal: [vm01gb]: FAILED! => {"changed": false, "failed": true, "msg": "No package matching 'pip' is available"}

PLAY RECAP *********************************************************************
vm01gb    : ok=8    changed=0    unreachable=0    failed=1
```

**Comment by leseb** [comment]
Are you trying to deploy containerised ceph daemons?
This is correct, can you PR the change?

Or do you want me to fix this?

**Comment by leseb** [comment]
Fixed, thanks for reporting!

**Comment by Raboo** [comment]
Yes it was containerized setup..
Thanks for fixing.

**Comment by leseb** [comment]
Np np ;)
