### ISSUE TITLE
group/all.yml  variable grafana_server_group_name , not useful for dashboard.yml 

### ISSUE THREAD

**Issue by MrSate** [ceph/ceph-ansible#5026]
default group name for grafana role is using grafana-server, it will trigger a [DEPRECATION WARNING]. So I changed grafana_server_group_name: grafana-server  to grafana_server_group_name: grafana in group/all.yml to avoid warnings. Also use [granrfa] in the host file. 

But, after the change， the dashboard task（import_playbook: dashboard.yml）will lost task (- hosts: "{{ grafana_server_group_name }}" ) , it only executed when grafana role is [granrfa-server], Even if variable grafana_server_group_name has been change 

OS: Centos7.4:
ansible-playbook version: 2.8.5:
ceph-ansible version: stable-4.0

**Comment by styleart** [comment]
It's already here: https://github.com/ceph/ceph-ansible/issues/4651
`grafana-server` is hardcoded in some places, so currently the only possibility is to ignore deprecation warnings...
