### ISSUE TITLE
Error generating ceph configuration file

### ISSUE THREAD

**Issue by hiroru** [ceph/ceph-ansible#503]
I've tried many things but I always get this error during deployment:

TASK: [ceph-common | generate ceph configuration file] ************************ 
fatal: [X.X.X.X] => One or more undefined variables: 'dict object' has no attribute u'mons'
fatal: [Y.Y.Y.Y] => One or more undefined variables: 'dict object' has no attribute u'mons'

FATAL: all hosts have already failed -- aborting

I'm using this version:
>ansible --version
ansible 1.9.4
  configured module search path = None

Could you please help me with this.

Thanks in advance

**Comment by leseb** [comment]
Hi @hiroru, 

Can you share your inventory file and your `site.yml`?

**Comment by hiroru** [comment]
Of course:
>cat site.yml
---
# Defines deployment design and assigns role to server groups
- hosts: ceph-mon
  sudo: True
  roles:
     - ceph-mon

- hosts: ceph-osd
  sudo: True
  roles:
    - ceph-osd

- hosts: ceph-mds
  sudo: True
  roles:
    - ceph-mds


>cat inventory.list 
[ceph-mon]
104.197.181.65
146.148.48.54
[ceph-osd]
146.148.32.191
104.197.127.60
104.197.186.145
[ceph-mds]
104.197.96.183

**Comment by leseb** [comment]
Ok, you need to modify those https://github.com/ceph/ceph-ansible/blob/master/group_vars/all.sample#L31-L35

And set `ceph-mon`, `ceph-osd`, etc.

**Comment by hiroru** [comment]
Worked like a charm!

Thank you! ;-)

**Comment by leseb** [comment]
;-)
