### ISSUE TITLE
Tag and versionning

### ISSUE THREAD

**Issue by HanXHX** [ceph/ceph-ansible#504]
Hi,

Can you create a process release (git tag + ansible-galaxy)? It's hard to maintain a rolling release role.

Thank-you!

Emilien

**Comment by leseb** [comment]
Hi,

I've never done that, do you have any pointer?

**Comment by HanXHX** [comment]
You can check all my roles on Github. I use tags and i can hold version role on machines. In a requirements.yml, you can do something like:

```
- src: HanXHX.nginx
  version: 1.2
```

**Comment by leseb** [comment]
Ok I see, I'll start doing this as of next week.

**Comment by leseb** [comment]
https://github.com/ceph/ceph-ansible/releases/tag/v1.0.0
