### ISSUE TITLE
ceph-osd-prestart.sh[]:   OSD data directory ... does not exist; bailing out.

### ISSUE THREAD

**Issue by cloudguy23** [ceph/ceph-ansible#5057]
**Bug Report**

What happened:
4 node cluster with 10 OSDs each fails to reliably restart OSD daemons when applying ceph-ansible playbook (4.0.14).

What you expected to happen:
Successful (exit 0) execution of playbook - error free.

How to reproduce it (minimal and precise):
In my environment I can reproduce this consistently:
- Ceph 14.2.7
- Ceph-Ansible 4.0.14

Running playbook via `ansible-playbook -I ceph-hosts site.yml -vvv`

Results in sporadic errors:

```
failed: [osd27.domain.tld] (item=7) => changed=false 
  ansible_loop_var: item
  invocation:
    module_args:
      daemon_reexec: false
      daemon_reload: true
      enabled: true
      force: null
      masked: false
      name: ceph-osd@7
      no_block: false
      scope: null
      state: started
      user: null
  item: '7'
  msg: |-
    Unable to start service ceph-osd@7: Job for ceph-osd@7.service failed because the control process exited with error code. See "systemctl status ceph-osd@7.service" and "journalctl -xe" for details.
```

Host level logs:
```
ceph-osd-prestart.sh[xxxxx]: OSD data directory /var/lib/ceph/osd/ceph-7 does not exist; bailing out.
```

I was able to apply a workaround on OSD hosts themselves.   

Changed the following stanza in /usr/lib/ceph/ceph-osd-prestart.sh:

```
# assert data directory exists - see http://tracker.ceph.com/issues/17091
if [ ! -d "$data" ]; then
    echo "OSD data directory $data does not exist; bailing out." 1>&2
#    exit 1
    sleep 5
fi
```

It appears that ceph-ansible playbook doesn't throttle rolling / parallel restart of OSD daemons 

Share your group_vars files, inventory

Ceph sensible deploys without issue with above workaround.   Specific in order to throttle the following were applied:

```
# OSD handler checks
handler_health_osd_check_retries: 40
handler_health_osd_check_delay: 60
handler_health_osd_check: true
```

**Environment**:
* OS (e.g. from /etc/os-release):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

* Kernel (e.g. `uname -a`): `Linux  3.10.0-1062.4.1.el7.x86_64 #1 SMP Fri Oct 18 17:15:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

* Docker version if applicable (e.g. `docker version`): n/a
* Ansible version (e.g. `ansible-playbook --version`): 2.8.8
* ceph-ansible version (e.g. `git head or tag or stable branch`): 4.0.14
* Ceph version (e.g. `ceph -v`):
`ceph version 14.2.7 (3d58626ebeec02d8385a4cefb92c6cbc3a45bfe8) nautilus (stable)`

**Comment by dsavineau** [comment]
Could you share the full ansible logs, {group,host}_vars/*.yml and inventory ?

> ceph-osd-prestart.sh[xxxxx]: OSD data directory /var/lib/ceph/osd/ceph-7 does not exist; bailing out.

The OSD directory is supposed to be created during the OSD creation via ceph-volume so we shouldn't have to modified scripts coming from the ceph-osd package.
But without the logs it's hard to say if it's a valid bug or not

**Comment by cloudguy23** [comment]
Hello @dsavineau ..  Attaching logs + supporting yml.
[Archive.zip](https://github.com/ceph/ceph-ansible/files/4207664/Archive.zip)

**Comment by dsavineau** [comment]
Looks like the there's no OSDs created during the playbook execution but there's still some legacy OSD data in /var/lib/ceph/osd which could explain the error.
Did you purge any previous deployment before creating a new one ?

 `devices` fact isn't populated with the `ansible_devices` fact (all items skipped)

```console
2020-02-13 11:19:53,644 p=2138 u=root |  TASK [ceph-facts : set_fact devices generate device list when osd_auto_discovery] ***************************
2020-02-13 11:19:53,644 p=2138 u=root |  task path: /opt/playbooks/ceph/ceph-ansible-4.0.14/roles/ceph-facts/tasks/facts.yml:236
2020-02-13 11:19:53,645 p=2138 u=root |  Thursday 13 February 2020  11:19:53 -0500 (0:00:00.371)       0:00:27.057 *****
2020-02-13 11:19:54,584 p=2138 u=root |  skipping: [stor23.domain.tld] => ....
2020-02-13 11:19:54,591 p=2138 u=root |  skipping: [stor23.domain.tld] => ....
2020-02-13 11:19:54,825 p=2138 u=root |  skipping: [stor23.domain.tld] => ....
(...)
```

The lvm and lvm-batch scenario tasks are all skipped (because `devices` is empty).

```console
2020-02-13 11:22:42,555 p=2138 u=root |  TASK [ceph-osd : include_tasks scenarios/lvm.yml] ***********************************************************
2020-02-13 11:22:42,555 p=2138 u=root |  task path: /opt/playbooks/ceph/ceph-ansible-4.0.14/roles/ceph-osd/tasks/main.yml:52
2020-02-13 11:22:42,556 p=2138 u=root |  Thursday 13 February 2020  11:22:42 -0500 (0:00:00.154)       0:03:15.967 *****
2020-02-13 11:22:42,590 p=2138 u=root |  skipping: [stor23.domain.tld] => changed=false
  skip_reason: Conditional result was False
2020-02-13 11:22:42,711 p=2138 u=root |  TASK [ceph-osd : include_tasks scenarios/lvm-batch.yml] *****************************************************
2020-02-13 11:22:42,711 p=2138 u=root |  task path: /opt/playbooks/ceph/ceph-ansible-4.0.14/roles/ceph-osd/tasks/main.yml:58
2020-02-13 11:22:42,712 p=2138 u=root |  Thursday 13 February 2020  11:22:42 -0500 (0:00:00.155)       0:03:16.123 *****
2020-02-13 11:22:42,752 p=2138 u=root |  skipping: [stor23.domain.tld] => changed=false
  skip_reason: Conditional result was False
```

But we can see a lot of OSD ids present in the /var/lib/ceph/osd directory.

```console
2020-02-13 11:22:43,316 p=2138 u=root |  TASK [ceph-osd : get osd ids] *******************************************************************************
2020-02-13 11:22:43,316 p=2138 u=root |  task path: /opt/playbooks/ceph/ceph-ansible-4.0.14/roles/ceph-osd/tasks/start_osds.yml:13
2020-02-13 11:22:43,317 p=2138 u=root |  Thursday 13 February 2020  11:22:43 -0500
2020-02-13 11:22:43,541 p=2138 u=root |  ok: [stor23.domain.tld] => changed=false
  cmd: |-
    set -o pipefail;
    ls /var/lib/ceph/osd/ | sed 's/.*-//'
  delta: '0:00:00.006390'
  end: '2020-02-13 11:22:43.516846'
  invocation:
    module_args:
      _raw_params: |-
        set -o pipefail;
    ls /var/lib/ceph/osd/ | sed 's/.*-//'
  delta: '0:00:00.006390'
  end: '2020-02-13 11:22:43.516846'
  invocation:
    module_args:
      _raw_params: |-
        set -o pipefail;
        ls /var/lib/ceph/osd/ | sed 's/.*-//'
      _uses_shell: true
      argv: null
      chdir: null
      creates: null
      executable: /bin/bash
      removes: null
      stdin: null
      stdin_add_newline: true
      strip_empty_ends: true
      warn: true
  rc: 0
  start: '2020-02-13 11:22:43.510456'
  stderr: ''
  stderr_lines: <omitted>
  stdout: |-
    0
    10
    12
    14
    16
    18
    20
    22
    24
    26
    28
    30
    32
    34
    36
    38
    4
    6
    8
    0
    12
    16
    20
    24
    28
    32
    36
    6
    8
  stdout_lines: <omitted>
```

**Comment by cloudguy23** [comment]
This is interesting..   I do see a (failed / prior / old) deployment when using ceph-ansible-4.0rc3 of the playbook last year referenced in the `/var/lib/ceph/osd` directory:

```
drwxr-xr-x 2 ceph ceph   6 Apr 12  2019 old_cluster-0
drwxr-xr-x 2 ceph ceph   6 Apr 12  2019 old_cluster-10
drwxr-xr-x 2 ceph ceph   6 Apr 12  2019 old_cluster-12
drwxr-xr-x 2 ceph ceph   6 Apr 12  2019 old_cluster-14
drwxr-xr-x 2 ceph ceph   6 Apr 12  2019 old_cluster-16
drwxr-xr-x 2 ceph ceph   6 Apr 12  2019 old_cluster-18
drwxr-xr-x 2 ceph ceph   6 Apr 12  2019 old_cluster-20
drwxr-xr-x 2 ceph ceph   6 Apr 12  2019 old_cluster-22
drwxr-xr-x 2 ceph ceph   6 Apr 12  2019 old_cluster-24
drwxr-xr-x 2 ceph ceph   6 Apr 12  2019 old_cluster-26
drwxr-xr-x 2 ceph ceph   6 Apr 12  2019 old_cluster-28
drwxr-xr-x 2 ceph ceph   6 Apr 12  2019 old_cluster-30
drwxr-xr-x 2 ceph ceph   6 Apr 12  2019 old_cluster-32
drwxr-xr-x 2 ceph ceph   6 Apr 12  2019 old_cluster-34
drwxr-xr-x 2 ceph ceph   6 Apr 12  2019 old_cluster-36
drwxr-xr-x 2 ceph ceph   6 Apr 12  2019 old_cluster-38
drwxr-xr-x 2 ceph ceph   6 Apr 12  2019 old_cluster-4
drwxr-xr-x 2 ceph ceph   6 Apr 12  2019 old_cluster-6
drwxr-xr-x 2 ceph ceph   6 Apr 12  2019 old_cluster-8
drwxrwxrwt 2 ceph ceph 200 Feb 12 14:50 ceph-0
drwxrwxrwt 2 ceph ceph 200 Feb 12 14:50 ceph-12
drwxrwxrwt 2 ceph ceph 200 Feb 12 14:50 ceph-16
drwxrwxrwt 2 ceph ceph 200 Feb 12 14:50 ceph-20
drwxrwxrwt 2 ceph ceph 200 Feb 12 14:50 ceph-24
drwxrwxrwt 2 ceph ceph 200 Feb 12 14:50 ceph-28
drwxrwxrwt 2 ceph ceph 200 Feb 12 14:50 ceph-32
drwxrwxrwt 2 ceph ceph 200 Feb 12 14:50 ceph-36
drwxrwxrwt 2 ceph ceph 200 Feb 12 14:50 ceph-6
drwxrwxrwt 2 ceph ceph 200 Feb 12 14:50 ceph-8
```

With respect to `devices` observation above, I do have `osd_auto_discovery: true`, understanding is that given the only scenario applicable to nautilus is LVM, this would not require `devices` to be explicitly defined.

Only the `ceph-*` are mounted.   The `old_cluster-*` appear empty.   
Is the guidance to remove these stale records?

**Comment by dsavineau** [comment]
> With respect to `devices` observation above, I do have `osd_auto_discovery: true`, understanding is that given the only scenario applicable to nautilus is LVM, this would not require `devices` to be explicitly defined.

That's true, but what `osd_auto_discovery` is doing for you is to filled the `devices` variable for you

> Only the `ceph-*` are mounted. The `old_cluster-*` appear empty.

Check the cluster fsid of those ceph-* osd mounted compared to the current one used in the cluster. I'm pretty sure they are different.

> Is the guidance to remove these stale records?

https://docs.ceph.com/docs/nautilus/rados/operations/add-or-rm-osds/#removing-osds-manual

or 

```console
$ ansible-playbook -vv -i /path/to/inventory infrastructure-playbooks/purge-cluster.yml
```

**Comment by cloudguy23** [comment]
Confirming that removing the stale directories did the trick.   I reverted back to the stock ceph-osd-prestart.sh and was able to apply the playbook without issue.   In my case i simply removed `old_cluster-0` directories as nothing was mounted or active cluster using them.  @dsavineau thanks for your help!
