### ISSUE TITLE
Avoiding unnecessary package updates

### ISSUE THREAD

**Issue by mattt416** [ceph/ceph-ansible#506]
Hi all,

What are everyone's thoughts on the change in https://github.com/ceph/ceph-ansible/commit/476c5df38feb3525b7c7c32e79b1498f5f2df7d2?  Is this likely to cause issues if you re-run playbooks resulting in package updates?  You won't get a major version update and this won't necessarily result in service restarts (unless there are config changes that happen also), but with something as critical as a storage system I do wonder if package updates need to be more controlled.

As this was done specifically for the rolling upgrade play, an immediate solution that jumps to mind is to require a variable passed in on the command line when running the rolling upgrade play which then decides if packages are installed to present or latest.  I've seen this pattern used elsewhere and it seems to work OK.

I'd love to hear what others think before I put a PR through unnecessarily.

Thanks!

--Matt

**Comment by leseb** [comment]
Yes the commit partially adresses the concern where we don't really want to upgrade the storage system. I think we should find a way to control the behaviour, perhaps we could use a flag for rolling upgrades.
So just exactly as you suggested the variable thing should do the trick.

I'd be more than happy to see a PR for this.
Thanks for highlighting this @mattt416

**Comment by leseb** [comment]
Addressed by #508
