### ISSUE TITLE
Improve PR tests in the CI

### ISSUE THREAD

**Issue by leseb** [ceph/ceph-ansible#507]
Hey @andrewschoen, @alfredodeza 

Since we now have a CI thanks to #493, I was wondering how we could go further with testing PR.
#1. Ansible Galaxy

As you might now, all the daemon roles are part of the Ansible Galaxy and all live in their individual repos here:
- https://github.com/ceph/ansible-ceph-common
- https://github.com/ceph/ansible-ceph-mon
- https://github.com/ceph/ansible-ceph-osd
- https://github.com/ceph/ansible-ceph-mds
- https://github.com/ceph/ansible-ceph-rgw

And then we have the repo we are currently in: https://github.com/ceph/ceph-ansible/ which gathers all the roles. All the galaxy roles don't expect PR and all the PRs should come in this current repo. This means that every time there is a new PR getting merged **I** manually run the following in order to propagate the change in the necessary Ansible Galaxy repos:

`ansible-playbook -i dummy-ansible-hosts contrib/splitup.yml --tags update`

This kinda annoying as the repo gets more and more attention and that I'm not always 24/7 available. That's why I was wondering if we could have another job that triggers the command above every time a new PR gets merged. So this is my first request.
#2. Distro support

As far as I know, (well see @andrewschoen last comment in #493), we only run a single slave and we don't exactly know which distro it'll run, so basically we can either get CentOS or Ubuntu. Ideally we should test both.
So this is my second request
#3. Ansible version support

Currently the CI uses the last stable release: `2.0.0.2`. I think it'd be nice to also test against `1.9.4` since version 2 is rather new.
#4. More CI tests

The playbook is really flexible and provides several different capabilities. If we take a look at the OSD scenarios for example, we support:
- journal collocation
- a dedicated journal device for N OSDs
- a directory path for the OSDs

It'd be nice to have the ability to test all of them depending on the kind of PR we are getting.
Same could be applied to which role is involved in the change, at the moment we 'blindly' run a mon, an osd and a rgw where the patch could potentially only concern a monitor. Perhaps it's too granular and this doesn't impact the time spent to roll out the playbook or perhaps we can consider the time spent reasonable.

A couple of ideas here:
- use tags in the PR to pin a role
- use a naming convention to prefix each commit (ie: ceph-mon: my super funky change)
- parse variables in the PR (this is tricky and would require a refactor of all the variables, people might not like this one)

It'd say this is the fourth and probably the most complex request :).
#5. Docker

We have the ability to bootstrap containerized ceph daemons, would be nice to get a node where we can run docker containers.
#6. Test code quality/syntax

Using:
-  https://github.com/willthames/ansible-lint
- https://github.com/willthames/ansible-review

Possible using https://github.com/metacloud/molecule too.

Sorry for the long post :).

Requests completion status:
- [x] 1. Ansible Galaxy
- [x] 2. Distro support
- [x] 3. Ansible version support
- [x] 4. More CI tests
- [ ] 5. Docker 
- [x] 6. Syntax

**Comment by andrewschoen** [comment]
@leseb Your first request should have been taken care of with https://github.com/ceph/ceph-build/pull/320

Next time a merge happens let's take a look at https://jenkins.ceph.com/job/ceph-ansible-galaxy/ to make sure it does what's expected.

**Comment by leseb** [comment]
@andrewschoen great, I have a PR to merge so I'll check that :)

**Comment by andrewschoen** [comment]
@leseb hmmm, doesn't look like the job fired. We've been having this issue with other jobs that are triggered by a merge to master on github, I'll investigate.

**Comment by leseb** [comment]
@andrewschoen how much time should I wait to get this triggered? Merged #515 40 minutes ago and I don't see the commit here https://github.com/ceph/ansible-ceph-common

**Comment by leseb** [comment]
Oh right, I was just writing to say that https://github.com/ceph/ansible-ceph-common didn't get update :/
Thanks!

**Comment by andrewschoen** [comment]
@leseb alright, I've bounced the jenkins service. IIRC, this is all we needed to do in the past when this specific issue started happening.

If it's working correctly the job should be triggered almost immediately, definitely within a minute of merge.

**Comment by leseb** [comment]
@andrewschoen ok so for the next PR merge then, right? So I should update #515 manually.

**Comment by andrewschoen** [comment]
@leseb yeah, the next PR merge.

**Comment by leseb** [comment]
@andrewschoen still not happening, #512 merged and nothing on https://github.com/ceph/ansible-ceph-common :(

**Comment by andrewschoen** [comment]
@leseb ugh, ok. It looks like the github hooks for ceph-ansible needed tweaking. We didn't have it configured to send a ping to jenkins on any push to the repository, only on PRs.

I'm thinking this should work as expected next time, apologies for the struggle.

**Comment by leseb** [comment]
@andrewschoen ok will wait for the next PR then :)

**Comment by leseb** [comment]
@andrewschoen no luck for #519 :(

**Comment by bengland2** [comment]
I would greatly appreciate coverage for RHCS (Red Hat Ceph Storage) releases, although I think it's right to do upstream first.

**Comment by andrewschoen** [comment]
@leseb bummer. This seems to be a problem with all our jobs that accept a push notification from github, not only this one. We're investigating.

**Comment by leseb** [comment]
@andrewschoen ok, np np :)

**Comment by alfredodeza** [comment]
We identified an ssl issue on one of the hooks we are using that github talks to and was failing. This since has been corrected and all other jobs are now working nicely. ceph-ansible pull requests should totally work now! I swear!

**Comment by leseb** [comment]
@alfredodeza awesome :) let's wait for #523 then :) Thanks!

**Comment by leseb** [comment]
@alfredodeza just merged #524, still nothing in https://github.com/ceph/ansible-ceph-rgw :(

**Comment by bengland2** [comment]
Here's a suggestion which I've done for my own benefit outside of here:
- run ceph-ansible with all roles on 1 VM, setting ceph default pool size to 1 and verify that the cluster is functional with RBD, RGW and Cephfs.  You only need /dev/vdb defined as an OSD.
- run purge-cluster.yml to tear it down
We could do this with Ubuntu and Centos VMs. This would be a start to catching problems like the ones I've reported.

**Comment by andrewschoen** [comment]
Request 2 should be taken care of with https://github.com/ceph/ceph-build/pull/346

**Comment by leseb** [comment]
@great thanks, are we going to have 2 jobs now showing on github?

**Comment by leseb** [comment]
@andrewschoen @alfredodeza can we get an additional VM for Ubuntu 16.04?
Thanks!

**Comment by alfredodeza** [comment]
We should get Xenial soon-ish (hopefully by tomorrow)

**Comment by leseb** [comment]
@alfredodeza thanks!

**Comment by font** [comment]
@leseb How about a CI improvement to do some analysis/review on the playbooks? I came across these projects https://github.com/willthames/ansible-lint and https://github.com/willthames/ansible-review, which we may be able to leverage in order to get some sort of static analysis on our playbooks. This should help ease the process of reviewing incoming PRs and improve the overall quality of the code. Thoughts?

Also, I was going to open up a new enhancement request issue, but then I saw this generic CI improvement issue already existed. Let me know if you'd like me to open a new issue for this.

**Comment by leseb** [comment]
@font this can easily be done with Travis, I already have something really simple being done here: https://github.com/ceph/ceph-ansible/blob/master/.travis.yml#L21
But the ansible-lint might be a good addition.

Other than that, I was also hoping to have a look at https://github.com/metacloud/molecule
which seems to be a really nice framework to test Ansible playbooks.

Everything with CI improvement should be kept here :).
