### ISSUE TITLE
facing the grafana crash loop

### ISSUE THREAD

**Issue by gvikram18** [ceph/ceph-ansible#5079]
I want to try single node cluster with containers. When running containerized deployment with dashboard disabled from a single node, ansible skips the grafana-server as i have not mentioned it in my inventory file. But, it doesn't allow me to proceed installing the cluster without adding grafana-server. 

![oie_BolU9BRrsCW2](https://user-images.githubusercontent.com/28858181/74712140-9e4b9600-524b-11ea-94b0-5435f95a290f.png)

![oie_OaUHcfvgjWy7](https://user-images.githubusercontent.com/28858181/74712156-a4da0d80-524b-11ea-9556-526025b0c0c6.png)

group_vars:

generate_fsid: true
monitor_interface: enp0s3
monitor_address: 192.168.1.61
ceph_docker_image: "ceph/daemon"
ceph_docker_image_tag: latest-master
containerized_deployment: true
dashboard_enabled: false
ceph_docker_registry: docker.io
radosgw_interface: enp0s3

inventory_hosts:

[mons]
192.168.1.61
[osds]
192.168.1.61
[mgrs]
192.168.1.61
[rgws]
192.168.1.61

Environment: 
CentOS 7  
Linux Kernel 3.10.0-957.el7.x86_64 
Ansible-2.8.8 (git checkout stable-4.0)

**Comment by dsavineau** [comment]
where are located the ansible inventory, group_vars files ?

How do you run the ansible-playbook ?

**Comment by gvikram18** [comment]
> where are located the ansible inventory, group_vars files ?
> 
> How do you run the ansible-playbook ?

ansible inventory path: /home/cephuser/ceph-ansible/inventory_hosts
group_vars path : /home/cephuser/ceph-ansible/group_vars/

**Comment by dsavineau** [comment]
What's the name of the file in the group_vars directory that contains the `dashboard_enabled` variable ? `all` ? `all.yml` ?

Because your config looks good but doesn't seem to be loaded during the ansible-playbook execution

**Comment by fmount** [comment]
@gvikram18 , @dsavineau is right, sounds like the [1] is not skipped and it means you need to check the `dashboard_enabled` variable on `group_vars/all.yml`

[1] https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-validate/tasks/main.yml#L216

**Comment by gvikram18** [comment]
> What's the name of the file in the group_vars directory that contains the `dashboard_enabled` variable ? `all` ? `all.yml` ?
> 
> Because your config looks good but doesn't seem to be loaded during the ansible-playbook execution

yeah. its all.yml
The contents of the all.yml file are as follows -

```
ceph_docker_image: "ceph/daemon"
ceph_docker_image_tag: latest-nautilus
ceph_docker_registry: docker.io
ceph_docker_registry_auth: false
containerized_deployment: True

dashboard_enabled: True
dashboard_protocol: http
dashboard_port: 8443
dashboard_admin_user: admin
dashboard_admin_password: P@ssw0rd

monitor_interface: enp0s3
radosgw_interface: enp0s3
```

**Comment by fmount** [comment]
Ok @gvikram18 , as you can see in [1], `if dashboard_enabled is True` but no `[grafana-server]` group exists, this failure is the expected behaviour.
To make the validation pass you must have the `[grafana-server]` group, it must contain at least one node and I suggest you to review the `grafana_*` variables.
If the dashboard deployment is out of scope for you, you can set `dashboard_enabled: False` in your `group_vars/all.yml`.


[1] https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-validate/tasks/main.yml#L216

**Comment by gvikram18** [comment]
> Ok @gvikram18 , as you can see in [1], `if dashboard_enabled is True` but no `[grafana-server]` group exists, this failure is the expected behaviour.
> To make the validation pass you must have the `[grafana-server]` group, it must contain at least one node and I suggest you to review the `grafana_*` variables.
> If the dashboard deployment is out of scope for you, you can set `dashboard_enabled: False` in your `group_vars/all.yml`.
> 
> [1] https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-validate/tasks/main.yml#L216

Thanks @fmount
