### ISSUE TITLE
Difference between playbooks iscsigws and iscsi-gws

### ISSUE THREAD

**Issue by modir** [ceph/ceph-ansible#5089]
I couldn't find anywhere in the documentation the difference between playbooks iscsigws and iscsi-gws.
Furthermore I would like to know how to disable the installation of the iSCSI gateways as I don't need them in my scenario.
It would be nice if this information is added to the documentation.

**Comment by dsavineau** [comment]
> I couldn't find anywhere in the documentation the difference between playbooks iscsigws and iscsi-gws.

Do you mean iscsigws and iscsi-gws groups instead of playbooks ?

iscsi-gws is the legacy iscsi group name for backward compatibility and you should use iscsigws if needed

> Furthermore I would like to know how to disable the installation of the iSCSI gateways as I don't need them in my scenario.

If you don't add hosts in the iscsigws group in the ansible inventory then this won't be enabled

**Comment by modir** [comment]
> Do you mean iscsigws and iscsi-gws groups instead of playbooks ?

Could be. Created a first configuration and ran then the command as described in the documentation. And then one of the output was something like this:

`Running plays: ... [iscsgws] [iscsi-gws] ...`

So I thought that it is talking about some kind of sub-playbooks now. But could very well be the group name in this case. Sadly the documentation is not always that clear.

> If you don't add hosts in the iscsigws group in the ansible inventory then this won't be enabled

OK. Thanks. This helped me. Would be nice if this is clearer in the documentation. But I am closing this issue for now as I have another one regarding the documentation open which is more important.
