### ISSUE TITLE
when use shrink-mon.yml delete 2 nodes to 1 node, the only monitor process hang.

### ISSUE THREAD

**Issue by fat8701** [ceph/ceph-ansible#5091]
**Bug Report**

What happened:
```
[root@ceph-test-1 ceph-ansible]# ceph -s
  cluster:
    id:     7cb05067-cd44-4d65-abc7-a3692a3e5484
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum ceph-test-1,ceph-test-2,ceph-test-3
    mgr: ceph-test-2(active), standbys: ceph-test-1, ceph-test-3
    osd: 3 osds: 3 up, 3 in
    rgw: 2 daemons active
 
  data:
    pools:   12 pools, 152 pgs
    objects: 2.37 k objects, 6.3 GiB
    usage:   16 GiB used, 281 GiB / 297 GiB avail
    pgs:     152 active+clean
```
when use shrink-mon.yml to delete from 3 nodes to 2 nodes, everthing is ok;
but  after update the ceph.conf and inventory file, continue to delete from 2 nodes to single node.
the command of ceph mon is hang.
```
TASK [remove monitor from the quorum] ******************************************************************************************************************************************
Monday 24 February 2020  10:23:29 +0800 (0:00:00.363)       0:00:07.715 ******* 
changed: [localhost -> 192.168.xx.xxx]

TASK [verify the monitor is out of the cluster] ********************************************************************************************************************************
Monday 24 February 2020  10:23:29 +0800 (0:00:00.762)       0:00:08.477 ******* 
FAILED - RETRYING: verify the monitor is out of the cluster (2 retries left).
```
and ceph-mon log show some slow ops. i need to create a new monmap through monmaptool to recover it...

What you expected to happen:
I have test several times, if i modify the shrink-mon.yml that run "remove monitor from the quorum" task  before "stop monitor service(s)" task. it make success.

How to reproduce it (minimal and precise):

Share your group_vars files, inventory

**Environment**:
* OS (e.g. from /etc/os-release): centos 7
* Kernel (e.g. `uname -a`): 3.10.0-123
* Ansible version (e.g. `ansible-playbook --version`): 2.6.20
* ceph-ansible version (e.g. `git head or tag or stable branch`): stable-3.2
* Ceph version (e.g. `ceph -v`): mimic-13.2.8

**Comment by guits** [comment]
When shrinking a mon, if you have 3 mons setup, the only valid operation that should come after that is adding a new monitor.
Trying to shrink a second monitor doesn't seem to be a valid operation then.
However, an interesting question is: what about a 5 monitors setup? You have 5 mons, you try to shrink 1 mon, then another one. IMO, trying to get from 5 monitors to 3 monitors sounds like a valid scenario to me.
