### ISSUE TITLE
UUID generation does not fail if uuid-runtime is not installed

### ISSUE THREAD

**Issue by Logan2211** [ceph/ceph-ansible#510]
Just ran into this today deploying from an LXC container which does not have uuid-runtime installed.

TASK: [ceph-common | generate cluster uuid] ***********************************
changed: [lsn-d5481_ceph-mon_container-bb84e883 -> 127.0.0.1]
changed: [lsn-d4057_ceph-mon_container-e078483d -> 127.0.0.1]
changed: [lsn-d3544_ceph-mon_container-900f1327 -> 127.0.0.1]

This writes an empty ceph_cluster_uuid file to the fetch directory and the play does not fail until later when it is trying to deploy the monitors and tries to pass an empty uuid.

using > redirection instead of piping to tee would cause the task to fail due to return code, but it would still cause an empty ceph_cluster_uuid file to be written...

**Comment by leseb** [comment]
Hey @Logan2211,

I see several ways to fix this issue:

1. Make uuidgen mandatory, check and fail if not present
2. Find another way to generate an UUID that can make everyone happy (OSX, Linux, FreeBSD)

It looks like python should be a raisonnable alternative. I'm currently thinking at `python -c 'import uuid; print str(uuid.uuid4())'`.

Thoughts?

**Comment by Logan2211** [comment]
Yes, that does work. Thanks!
