### ISSUE TITLE
error while installing RadosGW

### ISSUE THREAD

**Issue by Chrislevi** [ceph/ceph-ansible#513]
I got an error while I got to the stage of installing the rgws
fatal: [Gateway name] => input file not found at 
/home/username/ceph-ansible/roles/ceph-rgw/files/fetch/id/var/lib/ceph/bootstrap-rgw/ceph.keyring
or
/home/username/ceph-ansible/fetch/id/var/lib/ceph/bootstrap-rgw/ceph.keyring
Just to mention I'm trying to install Firefly and I use Ubuntu 14.04

**Comment by mattt416** [comment]
I was hitting a similar error trying to test all services running on a single CentOS instance.  I'm wondering if colocating services is not a valid use case?

**Comment by Chrislevi** [comment]
I think that the problem is with the way keys created for firefly.
In firefly there is not any bootstrap-rgw.
How can we fix it?

**Comment by leseb** [comment]
Well Firefly doesn't even have Civetweb IIRC :(
It looks like I broke that with this commit: https://github.com/ceph/ceph-ansible/commit/57d6ddc56b332a64bc86bc9c90f790a0c5f4f674

Do you mind trying to apply this patch and see if it works?

**Comment by Chrislevi** [comment]
Thanks,
 It helps changing back the code

**Comment by leseb** [comment]
Great, I'll leave this open a bit and will try to update the doc.
