### ISSUE TITLE
Install specific version of Ceph

### ISSUE THREAD

**Issue by clwluvw** [ceph/ceph-ansible#5145]
Is there a plan to support version installing with ansible so we can Install specific version of Ceph instead of installing latest version of that branch?

**Comment by dsavineau** [comment]
If you mean be able to install something like 14.2.3 instead of the current (latest) 14.2.8 Nautilus release then the answer is no.

That said you can probably workaround this by:
  - using an old container tag when using containerized_deployment.
  - create and use a custom repository with your specific ceph version.

**Comment by clwluvw** [comment]
@dsavineau Yes I mean that. But won't you use http://download.ceph.com/debian-nautilus/pool/main/c/ceph/ deb packages to automatically install from those in Ansible?

**Comment by dsavineau** [comment]
if you use `ceph_origin: repository` and `ceph_repository: community` then yes.
What I am saying is to use `ceph_repository: custom` instead.

**Comment by clwluvw** [comment]
@dsavineau Yes I get that but my idea is that for example when I set `ceph_version` variable to `14.2.4`, and set to use Ceph repository, Ceph Ansible performs and try to install deb files from Ceph repository automatically.
Isn't this a good idea? :thinking:

**Comment by guits** [comment]
> @dsavineau Yes I get that but my idea is that for example when I set `ceph_version` variable to `14.2.4` and set to use Ceph repository, Ceph Ansible performs and try to install deb files from Ceph repository automatically.

`ceph_version` isn't a variable intended to be modified by the user.

> Isn't this a good idea? 🤔

when `ceph_origin: repository ` and `ceph_repository: community ` the expected ceph-ansible behavior is to consume the latest and up to date packages that are provided upstream. I don't think we want to add some code complexity (which, by the way, could be a burden to maintain at some point) so ceph-ansible could install specific minor releases of a given ceph release.
If for any reason you want to strive to use an old minor version of a ceph release it's up to you to set such a repository and use `ceph_repository: custom`.
