### ISSUE TITLE
prevent ceph-container-engine installation if not necessary 

### ISSUE THREAD

**Issue by mistur** [ceph/ceph-ansible#5159]
**What happened:**
During an install of a Nautilus cluster on an existing K8s cluster, ceph-ansible playbook tries to remove the docker-ce package already installed to install  docker.io instead.
```
TASK [ceph-container-engine : install container packages] ***************************************************************************************************************************************************************************************************************************************************************
2020-03-17 16:34:52,557 p=54151 u=ragnar |  Tuesday 17 March 2020  16:34:52 +0100 (0:00:03.066)       0:21:15.920 ********* 
2020-03-17 16:35:17,972 p=54151 u=ragnar |  FAILED - RETRYING: install container packages (3 retries left).
[snip]
2020-03-17 16:35:18,135 p=54151 u=ragnar |  FAILED - RETRYING: install container packages (1 retries left).
2020-03-17 16:35:44,314 p=54151 u=ragnar |  fatal: [icclusterXXX.iccluster.epfl.ch]: FAILED! => changed=false 
  attempts: 3
  cache_update_time: 1584457304
  cache_updated: false
  msg: |-
    '/usr/bin/apt-get -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold"      install 'docker.io' 'python3-docker'' failed: E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
  rc: 100
  stderr: |-
    E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
  stderr_lines: <omitted>
  stdout: |-
    Reading package lists...
    Building dependency tree...
    Reading state information...
    Some packages could not be installed. This may mean that you have
    requested an impossible situation or if you are using the unstable
    distribution that some required packages have not yet been created
    or been moved out of Incoming.
    The following information may help to resolve the situation:
  
    The following packages have unmet dependencies:
     docker-ce : Conflicts: docker.io but 18.09.7-0ubuntu1~18.04.4 is to be installed
  stdout_lines: <omitted>
```

**What you expected to happen:**
Do not execute ceph-container-engine roles on nodes where it's not necessary, only the dashboard seems to depend on container-engine, it should be installed only on the dashboard node.

Or at least, use the docker version already installed if possible.

**How to reproduce it (minimal and precise):**
Each time I try to install ceph nautilus on a k8s cluster nodes.

**Share your group_vars files, inventory**
[cluster-ragnar.zip](https://github.com/ceph/ceph-ansible/files/4347879/cluster-ragnar.zip)

**Environment**:
* Roles:
```
---------------
iccluster[184-208].iccluster.epfl.ch (25)
---------------
OSDs/K8s exec node
---------------
icadmin[006-008].iccluster.epfl.ch (3)
---------------
MONs/MGRs/MDSs/K8s admin nodes
```

* OS (e.g. from /etc/os-release):
```
$ clush -b -w icadmin[006-008].iccluster.epfl.ch -w iccluster[184-208].iccluster.epfl.ch "cat /etc/os-release"
---------------
iccluster[184-208].iccluster.epfl.ch (25)
---------------
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
---------------
icadmin[006-008].iccluster.epfl.ch (3)
---------------
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

* Kernel (e.g. `uname -a`):
```
$ clush -b -w icadmin[006-008].iccluster.epfl.ch -w iccluster[184-208].iccluster.epfl.ch "uname -s -r -v -m -p -i -o"
---------------
iccluster[184-208].iccluster.epfl.ch (25)
---------------
Linux 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
---------------
icadmin[006-008].iccluster.epfl.ch (3)
---------------
Linux 4.15.0-22-generic #24~16.04.1-Ubuntu SMP Fri May 18 09:46:31 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

* Docker version if applicable (e.g. `docker version`):
```
---------------
iccluster[184-208].iccluster.epfl.ch (25)
---------------
Client:
 Version:           18.06.2-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        6d37f41
 Built:             Sun Feb 10 03:47:56 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.2-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       6d37f41
  Built:            Sun Feb 10 03:46:20 2019
  OS/Arch:          linux/amd64
  Experimental:     false
---------------
icadmin[006-008].iccluster.epfl.ch (3)
---------------
Client:
 Version:           18.06.2-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        6d37f41
 Built:             Sun Feb 10 03:48:06 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.2-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       6d37f41
  Built:            Sun Feb 10 03:46:30 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

* Ansible version (e.g. `ansible-playbook --version`):
```
$ ansible-playbook --version
ansible-playbook 2.8.10
  config file = /home/ragnar/ceph-ansible/ansible.cfg
  configured module search path = [u'/home/ragnar/ceph-ansible/library']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 7.4.0]
```
* ceph-ansible version (e.g. `git head or tag or stable branch`):
```
$ git branch
  master
* stable-4.0
```

* Ceph version (e.g. `ceph -v`):
```---------------
icadmin[006-008].iccluster.epfl.ch,iccluster[184-208].iccluster.epfl.ch (28)
---------------
ceph version 14.2.8 (2d095e947a02261ce61424021bb43bd3022d35cb) nautilus (stable)
```

**Comment by dsavineau** [comment]
> **What happened:**
> During an install of a Nautilus cluster on an existing K8s cluster, ceph-ansible playbook tries to remove the docker-ce package already installed to install docker.io instead.
> 

If the default docker package name present in ceph-ansible doesn't match with your requirement then you can still override it.

```console
$ ansible-playbook site.yml.sampl -e container_package_name=docker-ce
```

> 
> **What you expected to happen:**
> Do not execute ceph-container-engine roles on nodes where it's not necessary, only the dashboard seems to depend on container-engine, it should be installed only on the dashboard node.
> 

If you have the dashboard feature enabled (`dashboard_enabled: true`) then you also have node-exporter installed on all the nodes via containers so it's not only for the dashboard node.

**Comment by mistur** [comment]
Hello

Adding ` -e container_package_name=docker-ce` works for me, thanks!

I'd like to set this in the group_vars yml files now, but if I add `container_package_name: docker-ce` in group_vars/all.yml, it does not use it. Variables in all.yml are not supposed to override the defaults values?

Thanks a lot

**Comment by mistur** [comment]
Is it possible to deploy the dashboard without node-exporter and grafana but just give to it the data-source? We already have a node-exporter + grafana on our k8s cluster and because OSDs runs on k8s nodes, we have a conflict.

Best, 

Yoann

**Comment by dsavineau** [comment]
> I'd like to set this in the group_vars yml files now, but if I add `container_package_name: docker-ce` in group_vars/all.yml, it does not use it. Variables in all.yml are not supposed to override the defaults values?

You can only use the extra vars here because the `container_*_name` variables are defined as role default variables so you can't override them via the group_vars/host_vars.

> Is it possible to deploy the dashboard without node-exporter and grafana but just give to it the data-source? We already have a node-exporter + grafana on our k8s cluster and because OSDs runs on k8s nodes, we have a conflict.

This isn't possible ATM and not planned for the future.

**Comment by mistur** [comment]
> > I'd like to set this in the group_vars yml files now, but if I add `container_package_name: docker-ce` in group_vars/all.yml, it does not use it. Variables in all.yml are not supposed to override the defaults values?
> 
> You can only use the extra vars here because the `container_*_name` variables are defined as role default variables so you can't override them via the group_vars/host_vars.
> 
> > Is it possible to deploy the dashboard without node-exporter and grafana but just give to it the data-source? We already have a node-exporter + grafana on our k8s cluster and because OSDs runs on k8s nodes, we have a conflict.
> 
> This isn't possible ATM and not planned for the future.

OK thanks for the feed back.

**Comment by dsavineau** [comment]
Shoud we close this ?

**Comment by mistur** [comment]
Yes, sure, sorry.
