### ISSUE TITLE
ceph ansible restarts existing mon and mds daemons without permission

### ISSUE THREAD

**Issue by superxor** [ceph/ceph-ansible#5160]
What happened:

`RUNNING HANDLER [ceph-handler : restart ceph mon daemon(s) - non container] 
....
RUNNING HANDLER [ceph-handler : restart ceph mds daemon(s) - non container]`

What you expected to happen: ansible-playbook -i inventory/inventory.NEW site.yml --limit rgws should install another rgw daemon

This is SUPER sketchy

**Environment**:
* OS (e.g. from /etc/os-release): 18.04
* Ansible version (e.g. `ansible-playbook --version`): 2.9.6
* ceph-ansible version (e.g. `git head or tag or stable branch`): stable
* Ceph version (e.g. `ceph -v`): 14.2.8 Nautilus

**Comment by guits** [comment]
this definitely lacks information... afaik, when you open an issue, there's a template asking you to share details.

**Comment by guits** [comment]
share group_vars, inventory and full ceph-ansible log

**Comment by superxor** [comment]
> this definitely lacks information... afaik, when you open an issue, there's a template asking you to share details.

information is there, run it yourself to see, i run all default settings

**Comment by dsavineau** [comment]
> information is there, run it yourself to see, i run all default settings

no ansible logs, no ansible inventory and you can't even run the playbook with all default settings so this statement isn't true.

> check your play book, you're restarting other demons despite the limit, do your job people at RedHat, I'm getting tired of debugging your software every day

It will be helpful to get the information asked to debug this from our side.

Also you need to understand how handlers are working and why other daemons are restarted even if you're only running the playbook on a subset of the hosts.

To keep the cluster in a right state, daemons need to be restart when:
  - the ceph.conf changes
  - the systemd unit changes
  - the container image changes (if containerized deployment).

So if you're changing something in the radosgw configuration when collocated with other daemons like mon or mds then it's expected to restart them as well like the rgw when the ceph.conf is modified.

Now if it's not your issue then share the information and we will figure out the problem.
