### ISSUE TITLE
Add support for custom group names in infrastructure-playbooks/add-osd.yml

### ISSUE THREAD

**Issue by gpocentek** [ceph/ceph-ansible#5172]
**Is your feature request related to a problem? Please describe.**
Most playbooks in ceph-ansible support custom group names for the different ceph components (mons, osds, mgrs, ...), but this is not supported in the `add-osd.yml` playbook. This makes this particular playbook harder to use.

**Describe the solution you'd like**
Add support for custom group names, as it is done in other playbooks.

**Describe alternatives you've considered**
No alternative considered.

**Additional context**
None.

**Comment by guits** [comment]
see 3496a0efa2d7ae2872476387e9d801fb32414f63
