### ISSUE TITLE
can't deploy mimic with stable 3.1/3.2 

### ISSUE THREAD

**Issue by lumir-sliva** [ceph/ceph-ansible#5173]
**Bug Report**

What happened:
Cannot deploy mimic

```console
TASK [ceph-validate : validate ceph_repository_community] ***********************************************************
task path: /home/ubuntu/mimic/ceph-ansible/roles/ceph-validate/tasks/main.yml:20
Monday 23 March 2020  12:12:56 +0000 (0:00:00.109)       0:00:14.039 ********** 
fatal: [mimic1]: FAILED! => changed=false 
  msg: ceph_stable_release must be either 'nautilus' or 'octopus'
fatal: [mimic2]: FAILED! => changed=false 
  msg: ceph_stable_release must be either 'nautilus' or 'octopus'
fatal: [mimic3]: FAILED! => changed=false 
  msg: ceph_stable_release must be either 'nautilus' or 'octopus'
```

If I comment the role for checks I get:
```console
TASK [ceph-mon : waiting for the monitor(s) to form the quorum...] **************************************************
task path: /home/ubuntu/mimic/ceph-ansible/roles/ceph-mon/tasks/ceph_keys.yml:2
Monday 23 March 2020  12:15:48 +0000 (0:00:00.181)       0:01:13.393 ********** 
FAILED - RETRYING: waiting for the monitor(s) to form the quorum... (10 retries left).
```

What you expected to happen:

Be able to deploy ceph mimic with stable 3.2 or 3.1

How to reproduce it (minimal and precise):

clone ceph-ansible repo and use the groupvars I have

Share your group_vars files, inventory

group_vars/all.yml
```yaml
ceph_origin: repository
ceph_repository: community
ceph_repository_type: cdn
monitor_interface: eth0
public_network: 172.31.0.0/16

osd_scenario: collocated
osd_objectstore: bluestore
devices:
  - /dev/xvdb
  - /dev/xvdc

monitor_interface: eth0

ceph_mirror: http://download.ceph.com
ceph_stable_key: https://download.ceph.com/keys/release.asc
ceph_stable_release: mimic
ceph_stable_repo: "{{ ceph_mirror }}/debian-{{ ceph_stable_release }}"
```
inventory 
```yaml
[mons]
mimic1 monitor_address_block=172.31.42.162/24
mimic2 monitor_address_block=172.31.33.244/24
mimic3 monitor_address_block=172.31.38.130/24

[mgrs]
mimic2

[osds]
mimic1
mimic2
mimic3

#[rgws]
#ceph1 radosgw_address=172.31.38.93

[mdss]
mimic2 
```

**Environment**:
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
Linux mimic1 4.15.0-1057-aws #59-Ubuntu SMP Wed Dec 4 10:02:00 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

```console
ansible-playbook 2.8.10
  config file = /home/ubuntu/mimic/ceph-ansible/ansible.cfg
  configured module search path = [u'/home/ubuntu/mimic/ceph-ansible/library']
  ansible python module location = /home/ubuntu/virtualenv/lib/python2.7/site-packages/ansible
  executable location = /home/ubuntu/virtualenv/bin/ansible-playbook
  python version = 2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 7.4.0]
```

Am I missing something? 

I also see, that it's taking luminous not mimic in some roles

```console
TASK [ceph-facts : set_fact ceph_release ceph_stable_release] *******************************************************
task path: /home/ubuntu/mimic/ceph-ansible/roles/ceph-facts/tasks/facts.yml:23
Monday 23 March 2020  12:06:23 +0000 (0:00:00.103)       0:00:05.261 ********** 
ok: [mimic1] => changed=false 
  ansible_facts:
    ceph_release: luminous
```

Let me know, if I can help somehow. TIA

**Comment by dsavineau** [comment]
I'm pretty sure that you're not using the right ceph-ansible branch because
  - ansible 2.8 is only supported on stable-4.0 and master branches not stable-3.{1,2}
  - the ceph-validate role says "nautilus or octopus" which is also only supported on stable-4.0 and master branches.

I would suggest to checkout the stable-3.2 branch or the latest 3.2.x tag (v3.2.40 atm)
  - git clone -b stable-3.2 https://github.com/ceph/ceph-ansible.git
  - OR git clone -b v3.2.40 https://github.com/ceph/ceph-ansible.git
  - OR download the artifact from https://github.com/ceph/ceph-ansible/releases/tag/v3.2.40

**Comment by lumir-sliva** [comment]
you were right, please close this and sorry for the noise!
