### ISSUE TITLE
Installing qemu with ansible

### ISSUE THREAD

**Issue by modir** [ceph/ceph-ansible#5183]
**Is your feature request related to a problem? Please describe.**
I was stumbling over the same problem as described here: https://github.com/ceph/ceph-ansible/issues/2224
Furthermore I got a similar error message for libvirtd as well.

**Describe the solution you'd like**
It would be great if qemu und libvirt are installed by the ansible script as well. As I don't see any reason why it shouldn't get installed automatically.

**Comment by guits** [comment]
it's unrelated to ceph-ansible which isn't in charge of installing libvirtd.
You can still use these variables [1] so ceph-ansible will install whatever you estimate is needed for your cluster.

[1] https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-defaults/defaults/main.yml#L77-L85
