### ISSUE TITLE
rolling_update.yml fails because it can't find ../dashboard.yml

### ISSUE THREAD

**Issue by Ejdesgaard** [ceph/ceph-ansible#5210]
**Bug Report**

What happened:
cd ceph-ansible
git checkout v4.0.17
run rolling_update.yml playbook from ceph-ansible root folder
fails with the error that it can't find ../dashboard.yml
Does not honor 
dashboard_enabled: false
or if it's not set at all.

What you expected to happen:
Playbook runs. 
It finds dashboard.yml if dashboard_enabled: true

How to reproduce it (minimal and precise):
checkout 4.0.17
ln -s or cp infrastructure-playbooks/rolling_update.yml .
ensure dashboard_enabled is either not set or set to false.
try to ugprade the luminous cluster to nautilus.
The playbook will fail before asking if i'm sure, because dashboard.yml can't be found.
This should not be a problem for 2 reasons.
#1 dashboard_enabled is not true
#2 on 3.2, rolling_update.yml could be run from the ceph-ansible root directory.

Share your group_vars files, inventory and **full** ceph-ansibe log
```
$ grep -v -e \# -e ^$ group_vars/all.yml
---
dummy:
fetch_directory: ceph-ansible-keys/
configure_firewall: False
ceph_mon_firewall_zone: public
ceph_mgr_firewall_zone: "{{ ceph_mon_firewall_zone }}"
ceph_osd_firewall_zone: cluster
centos_package_dependencies:
  - epel-release
  - libselinux-python
ntp_service_enabled: true
ntp_daemon_type: ntpd
ceph_origin: repository
ceph_repository: community
ceph_stable_release: nautilus
fsid: 7e40f113-2a3f-4d61-9b7b-89e8fdba534e
generate_fsid: false
monitor_interface: team1.10
ip_version: ipv4
public_network: "10.0.0.0/24"
cluster_network: "10.0.1.0/24"
osd_objectstore: bluestore
ceph_conf_overrides:
  global:
    mon osd down out interval: 1200
    osd_pool_default_size: 3
    osd_pool_min_size: 2
    osd_max_scrubs: 1
    osd_scrub_sleep: 0.1
  mon:
    mon allow pool delete: false
  osd:
    bluestore_cache_kv_max: 1073741824
    bluestore_cache_kv_ratio: 0.4
disable_transparent_hugepage: "{{ false if osd_objectstore == 'bluestore' else true }}"
os_tuning_params:
  - { name: fs.file-max, value: 26234859 }
  - { name: vm.zone_reclaim_mode, value: 0 }
  - { name: vm.swappiness, value: 2 }
dashboard_enabled: false
```

```
$ grep -v -e \# -e ^$ group_vars/osds.yml
---
dummy:
devices:
  - /dev/sda
...
osd_auto_discovery: false
osd_scenario: lvm
lvm_volumes:
  - data: /dev/sda
    crush_device_class: ssd
...
```

**Environment**:
* OS (e.g. from /etc/os-release):` CentOS Linux release 7.7.1908 (Core)`
* Kernel (e.g. `uname -a`): `Linux node01 3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
* Docker version if applicable (e.g. `docker version`): `N/A`
* Ansible version (e.g. `ansible-playbook --version`): `ansible-playbook 2.9.5`
* ceph-ansible version (e.g. `git head or tag or stable branch`):` HEAD detached at v4.0.17`
* Ceph version (e.g. `ceph -v`): `from Luminous 12.2.13 to ceph version 14.2.8 (2d095e947a02261ce61424021bb43bd3022d35cb) nautilus (stable)`

**Comment by guits** [comment]
see 195944b123c0dc6780f3e3ede070f2ad9235f54d
