### ISSUE TITLE
After using the playbook can't using S3

### ISSUE THREAD

**Issue by nivazri** [ceph/ceph-ansible#522]
I tried to run the  playbook and after all finished,Swift worked correctly and S3 not with the error 403 Access  Denied when tried to create new bucket.
Any ideas?
Thank you

**Comment by leseb** [comment]
can you share more logs?

**Comment by nivazri** [comment]
In the logs I saw sync_user() failed error
This it the only error I found

**Comment by leseb** [comment]
`sync_user()` failed is not really an error and I agree this is a bit misleading :). I need more info
