### ISSUE TITLE
tasks/create_mds_filesystems: don't enable application 'cephfs' on the filesystem's pools

### ISSUE THREAD

**Issue by ajarr** [ceph/ceph-ansible#5278]
**Bug Report**

_What happened_: Before creating a filesystem using the 'fs new' command, the pools of the filesystems's have application `cephfs` enabled. This is not necessary as the `fs new` command already does this. Also, currently `fs new` command has a bug that if the application pool is already enabled,then incorrect application metadata is set in the FS pools. See,https://tracker.ceph.com/issues/43761 

_What you expected to happen_:  Simply remove the step that enables application `cephfs` on the FS pools [1]. This would  allow correct application metadata to be set on the FS pools.

Also, please backport the fix to stable-4.0, which has the same issue. 

[1] https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-mds/tasks/create_mds_filesystems.yml#L73

**Comment by guits** [comment]
@ajarr is there a BZ for this?

**Comment by ajarr** [comment]
> @ajarr is there a BZ for this?

No. Just this and the Ceph tracker ticket.

**Comment by guits** [comment]
@ajarr isn't expected to have this fix in RHCS 4.1 ?

**Comment by guits** [comment]
@ajarr ?

**Comment by ajarr** [comment]
@guits https://bugzilla.redhat.com/show_bug.cgi?id=1827607
