### ISSUE TITLE
Playbook for NFS purge

### ISSUE THREAD

**Issue by styleart** [ceph/ceph-ansible#5295]
**Is your feature request related to a problem? Please describe.**
Unfortunately, the NFS isn't supported anymore on Debian-based systems. Basically, there was no release for stable NFS-ganesha repositories since Mimic. For Nautilus there was a chakra repo that could be used, but it wasn't stable. For Octopus there are no packages at all, so to be able to update the cluster to Octopus we had to remove the NFS update part from the rolling update playbook.
However, we decided to drop the usage of NFS on our Ceph cluster, but how do we remove it now?

**Describe the solution you'd like**
There are other playbooks to remove components from the cluster (shrink or purge). It would be nice to have a playbook for NFS shrink/purge.

**Comment by dsavineau** [comment]
FYI
For Ubuntu there's https://launchpad.net/~nfs-ganesha
For Debian there's https://download.nfs-ganesha.org/
