### ISSUE TITLE
config_template: ImportError: No module named ansible

### ISSUE THREAD

**Issue by zmc** [ceph/ceph-ansible#531]
I filed #530 because I was getting "module is missing interpreter line" when "ceph-common | generate ceph configuration file" was reached. Now I'm seeing:

```
failed: [vpm144.front.sepia.ceph.com] => {"failed": true, "parsed": false}
BECOME-SUCCESS-iumeaotkbiahmnmxrtqhbnwpncjtlmcm
Traceback (most recent call last):
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1455129608.28-97582742881113/config_template", line 364, in <module>
    from ansible import errors
ImportError: No module named ansible
```

Shouldn't ``config_template`` be running on the master and not the target?

**Comment by zmc** [comment]
It occurs to me that this is likely happening because I'd used ``--module-path`` to point to ``plugins/actions/``. I haven't yet found another way to get ``ansible-playbook`` to find ``config_template.py``. In my use case it's necessary for the playbook to live outside the ``ceph-ansible`` tree.

**Comment by leseb** [comment]
what about editing your `ansible.cfg` just like here: https://github.com/ceph/ceph-ansible/blob/master/ansible.cfg#L3

**Comment by zmc** [comment]
I've actually also tried using an ``ansible.cfg`` with ``action_plugins = /the/path`` and that isn't working.

I've even used strace to see if it was *attempting* to look for action plugins. The strace output doesn't contain "action_plugins" or "plugins/action" at all.

**Comment by leseb** [comment]
hum just gave it a try and this is what I did:

* moved plugins/actions to roles/ceph-common
* edited `ansible.cfg` with `action_plugins = roles/ceph-common/plugins/actions`

Then ran ansible without any issue.
You do have a similar setup right?

**Comment by zmc** [comment]
I do, except my playbook is outside the repo path. As an experiment, I moved it *to* the repo path, and now it finds the plugin. Bizarre.

**Comment by leseb** [comment]
Ok glad to know that it works :)
