### ISSUE TITLE
Installation with dashboard_protocol=https fails with self-signed grafana TLS certificates

### ISSUE THREAD

**Issue by jvleminc** [ceph/ceph-ansible#5324]
**What happened:**
I am trying to set up a ceph cluster where the GUIs (Dashboard, Grafana) should use _https_. To achieve this, I set the flag _dashboard_protocol_ in my inventory to _https_.

The installation fails in the step:
`TASK [ceph-dashboard : inject grafana dashboard layouts]`

```
Install Ceph Dashboard         : In Progress (0:01:05)
	This phase can be restarted by running: roles/ceph-dashboard/tasks/main.yml

```

with the error:
```
fatal: [node-1 -> 10.0.0.3]: FAILED! => changed=false 
  cmd:
  - docker
  - exec
  - ceph-mon-node-1
  - ceph
  - --cluster
  - ceph
  - dashboard
  - grafana
  - dashboards
  - update
  delta: '0:00:01.274663'
  end: '2020-04-24 23:06:26.607792'
  msg: non-zero return code
  rc: 22
  start: '2020-04-24 23:06:25.333129'
  stderr: |-
    Error EINVAL: Traceback (most recent call last):
      File "/usr/share/ceph/mgr/mgr_module.py", line 974, in _handle_command
        return self.handle_command(inbuf, cmd)
      File "/usr/share/ceph/mgr/dashboard/module.py", line 386, in handle_command
        push_local_dashboards()
      File "/usr/share/ceph/mgr/dashboard/grafana.py", line 133, in push_local_dashboards
        retry()
      File "/usr/share/ceph/mgr/dashboard/grafana.py", line 90, in __call__
        result = self.func(*self.args, **self.kwargs)
      File "/usr/share/ceph/mgr/dashboard/grafana.py", line 128, in push
        grafana.push_dashboard(body)
      File "/usr/share/ceph/mgr/dashboard/grafana.py", line 54, in push_dashboard
        raise GrafanaError("Could not connect to Grafana server")
    GrafanaError: Could not connect to Grafana server
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>

```
And only the Dashboard answers on a _https_ call.

**What you expected to happen:**
The installation should finalize succesfully and the Dasboard and Grafana GUIs should respond on https.

**C-A files**
[install.20200424.225715.log](https://github.com/ceph/ceph-ansible/files/4531949/install.20200424.225715.log)
[inventory.txt](https://github.com/ceph/ceph-ansible/files/4531950/inventory.txt)

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 18.04
* Kernel (e.g. `uname -a`): 4.15.0-96-generic
* Docker version if applicable (e.g. `docker version`): 19.03.8
* Ansible version (e.g. `ansible-playbook --version`): 2.8.8
* ceph-ansible version (e.g. `git head or tag or stable branch`): 4.0.22
* Ceph-Daemon version: 4.0.12-stable-4.0-nautilus-centos-7

**Comment by dsavineau** [comment]
Could you try to run the following commands ? (from node-1)

```console
# docker exec ceph-mon-node-1 ceph --cluster ceph dashboard set-grafana-api-ssl-verify False
# docker exec ceph-mon-node-1 ceph --cluster ceph dashboard grafana dashboards update
```

As you're using self signed certificate for grafana, I suspect that the `dashboard grafana dashboards update` subcommand to fail because the TLS certificate isn't trusted.

**Comment by jvleminc** [comment]
After running the commands you mentioned, I reran the installer, which this time ended correctly and the Dashboards are shown on https! Thank you very much! 

Any chance this can be fixed in the future?
