### ISSUE TITLE
RGW container fails to start. Incorrect IP notation for rgw frontends when using IPv6

### ISSUE THREAD

**Issue by alexdepalex** [ceph/ceph-ansible#5325]
**Possible Bug**

We're using ceph-ansible v4.0.20 site-container to deploy our environment. This env is mainly IPv6. When the playbook deploys rgw, starting the container fails. This seems to be due to the fact that the IPv6 notation in the `rgw frontends` definition is lacking the square brackets as defined in https://github.com/ceph/ceph/blob/master/doc/radosgw/frontends.rst

**rgw section in ceph.conf**
```
[client.rgw.node1.rgw0]
host = node1
keyring = /var/lib/ceph/radosgw/ceph-rgw.node1.rgw0/keyring
log file = /var/log/ceph/ceph-rgw-node1.rgw0.log
rgw frontends = beast endpoint=IPv6_address:8080
rgw thread pool size = 512
```

**Error message from unit ceph-radosgw@rgw.node1.rgw0.service**
```
Apr 27 13:07:00 node1 podman[34735]: 2020-04-27 13:07:00.632 7ff6f2e610c0  0 framework: beast
Apr 27 13:07:00 node1 podman[34735]: 2020-04-27 13:07:00.632 7ff6f2e610c0  0 framework conf key: endpoint, val: IPv6_address:8080
Apr 27 13:07:00 node1 podman[34735]: 2020-04-27 13:07:00.633 7ff6f2e610c0  0 deferred set uid:gid to 167:167 (ceph:ceph)
Apr 27 13:07:00 node1 podman[34735]: 2020-04-27 13:07:00.633 7ff6f2e610c0  0 ceph version 14.2.4-125.el8cp (db63624068590e593c47150c7574d08c1ec0d3e4) nautilus (stable), process radosgw, pid 50
Apr 27 13:07:01 node1 podman[34735]: 2020-04-27 13:07:01.005 7ff6f2e610c0  0 starting handler: beast
Apr 27 13:07:01 node1 podman[34735]: 2020-04-27 13:07:01.005 7ff6f2e610c0 -1 failed to parse endpoint=IPv6_address:8080
Apr 27 13:07:01 node1 podman[34735]: 2020-04-27 13:07:01.005 7ff6f2e610c0 -1 ERROR: failed initializing frontend
Apr 27 13:07:01 node1 podman[34735]: 2020-04-27 13:07:01.005 7ff6ba6b3700  0 RGWReshardLock::lock failed to acquire lock on reshard.0000000000 ret=-16
Apr 27 13:07:01 node1 podman[34735]: teardown: managing teardown after SIGCHLD
```

**What you expected to happen**
Ceph-ansible should place the `beast endpoint` in square brackets when the relevant IP address of IPv6.

**Environment**
- RHEL 8.1
- Kernel 4.18.0-147.5.1.el8_1.x86_64 #1 SMP
- Podman 1.6.4
- ansible-playbook 2.8.10
- ceph-ansbible 4.0.20
- Ceph version 14.2.4-125.el8cp

**Comment by dsavineau** [comment]
Please share the inventory, full ansible logs and variables defined in group_vars/*.yml

The important information are either
```yaml
#radosgw_interface: interface
#radosgw_address: x.x.x.x
#radosgw_address_block: subnet
```

**Comment by alexdepalex** [comment]
We've only set `radosgw_interface` to `team0.<vlan id>` which is the same across all hosts. Both other options are not set.

**Comment by dsavineau** [comment]
Looks like a missing `ipwrap` filter on that condition https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-facts/tasks/set_radosgw_address.yml#L40-L43
