### ISSUE TITLE
Reconfigure without redeploy?

### ISSUE THREAD

**Issue by bodleytunes** [ceph/ceph-ansible#5333]
Hi

I'm trying to see if it's possible to add a feature and reconfigure without redeploying.  I can't seem to find out how to do this?

do we just redeploy if say I want to add rbd mirroring features?
Cheers,
Jon.

**Comment by dsavineau** [comment]
What do you mean by redeploy ? from scratch ?

**Comment by bodleytunes** [comment]
Well I thought if I run 
**ansible-playbook -i inventory.ini site.yml**
It's just going to blast everything away rather than just add components?

**Comment by bodleytunes** [comment]
I want to keep what is already setup and working and add rbd-mirroring

**Comment by bodleytunes** [comment]
I assume its not been added as I can't see the container running for this service.

**Comment by dsavineau** [comment]
> Well I thought if I run
> **ansible-playbook -i inventory.ini site.yml**
> It's just going to blast everything away rather than just add components?

Nope, that's one of the feature of ansible : idempotence

If you rerun the main playbook then it won't change anything that is already there.

But it should add more stuff (like rbd-mirror node) then it will add it.

**Comment by bodleytunes** [comment]
OK thats good to know thanks, will give it a shot!
