### ISSUE TITLE
Cannot deploy to ubuntu nodes

### ISSUE THREAD

**Issue by CodingSpiderFox** [ceph/ceph-ansible#5381]
**Bug Report**

What happened:
I followed a tutorial to setup a cluster for ceph, but the installation failed with the following error message

```
TASK [ceph-infra : update cache for Debian based OSs] *****************************************************************************************************************************************************************************************
Monday 18 May 2020  15:21:14 +0200 (0:00:00.109)       0:00:27.751 ************ 
changed: [server3]
changed: [server2]
FAILED - RETRYING: update cache for Debian based OSs (3 retries left).
FAILED - RETRYING: update cache for Debian based OSs (2 retries left).
sudo apFAILED - RETRYING: update cache for Debian based OSs (1 retries left).
fatal: [server1]: FAILED! => changed=false 
  attempts: 3
  msg: 'Failed to update apt cache: W:Updating from such a repository can''t be done securely, and is therefore disabled by default., W:See apt-secure(8) manpage for repository creation and user configuration details., E:The repository ''http://download.ceph.com/nfs-ganesha/deb-V3.2-stable/octopus bionic Release'' does not have a Release file.'
```

What you expected to happen:
All steps should have finished with status "OK".

How to reproduce it (minimal and precise):
Set up 3 VMs, use the following inventory:

```
[mons]
server1 monitor_address=10.0.0.x
server2 monitor_address=10.0.0.y
server3 monitor_address=10.0.0.z

[mgrs]
server1
server2
server3

[osds]
server1
server2
server3

[rgws]
server1

[nfss]
server1

[mdss]
server1
server2
server3

[grafana-server]
server1

[clients]
server1

```

Share your group_vars files, inventory and **full** ceph-ansibe log

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 18.04
* Kernel (e.g. `uname -a`): 4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linu

* Ansible version (e.g. `ansible-playbook --version`): ansible-playbook 2.9.9
* ceph-ansible version (e.g. `git head or tag or stable branch`): master (44e1ebaaff61b5317bae0a3483f5d485c12bd18b)
* Ceph version (e.g. `ceph -v`): 15.2.1 (9fd2f65f91d9246fae2c841a6222d34d121680ee) octopus (stable)

**Comment by dsavineau** [comment]
There's not upstream nfs-ganesha 3.2 build for Octopus on Ubuntu at the moment.

As an alternative you can try to use the containerized deployment because the container image is based on CentOS.
Or use an alternate ganesha repository on `nfss` nodes like https://launchpad.net/~nfs-ganesha/+archive/ubuntu/nfs-ganesha-3.0
