### ISSUE TITLE
iscsi path goes down

### ISSUE THREAD

**Issue by NFMyrzik** [ceph/ceph-ansible#5386]
Hello to all!

I have some problems with ceph iscsi and esxi. I have a 2 HP c7000 with 20 blade servers, on each of him installed esxi 6.7U3 and placed on sd-cards, on each I have a 2 HDD usable for ceph:)
My ceph cluster: 20 VMs on each blade with 2 disk for ceph. One admin VM with ceph-ansible. 
Environment of VMs: 
- CentOS 8
- Linux 5.6.12-1.el8.elrepo.x86_64 #1 SMP Fri May 8 19:48:47 EDT 2020 x86_64 GNU/Linux
- Branch - stable 5.0
- ceph version 15.2.1 (9fd2f65f91d9246fae2c841a6222d34d121680ee) octopus (stable)

**Bug Report**

All components installed successfully. I create rbd image and present it by iscsi(target created via gui) to 4 esxi hosts. All goes fine(from 1 to 5 days), but from one mystical moment all path going down by one. I find moment at one node and collect logs in attachment. Probably, I missed some major setting, I hope u can help me:)

After hit a problem I can not restart the rbd-target-gw service and I can not restart OS, the kernel is blocked. tcmu-runner log stops at the time of the crash. No other issues on ceph cluster I can't find, my proxmox cluster with rbd images from that ceph working fine.

Attachments:
[group_vars.txt](https://github.com/ceph/ceph-ansible/files/4655503/group_vars.txt)
[rmp.txt](https://github.com/ceph/ceph-ansible/files/4655505/rmp.txt)
[messages.txt](https://github.com/ceph/ceph-ansible/files/4655509/messages.txt)
[tcmu-runner.log](https://github.com/ceph/ceph-ansible/files/4655513/tcmu-runner.log)
[ansible_hosts.txt](https://github.com/ceph/ceph-ansible/files/4655704/ansible_hosts.txt)

**Comment by dsavineau** [comment]
This isn't related to ceph-ansible so you should open this issue on the ceph-iscsi repository instead.

https://github.com/ceph/ceph-iscsi
