### ISSUE TITLE
No information in documentation about containerized vs non-containerized

### ISSUE THREAD

**Issue by modir** [ceph/ceph-ansible#5392]
The current documentation lists in some chapters that it is possible to install ceph containerized or normal. But the information is rather sparse. What I am missing is:

1. What is the recommended way to install ceph these days when using ceph-ansible? Containerized or not?
2. Is there something to consider when going for containerized? E.g are there limitations?
3. What technology is used in the background when installing ceph containerized? (e.g. docker or LXD)

I came up with this because I stumbled upon this commit and realized there is not enough information in the official documentation of this project: https://github.com/ceph/ceph-ansible/commit/2547ab601a5187251f9dd41246d3dcedb653030f

**Comment by dsavineau** [comment]
> * What is the recommended way to install ceph these days when using ceph-ansible? Containerized or not?

There's no recommended way. It's up to you to choose.

> * Is there something to consider when going for containerized? E.g are there limitations?

You have the same features between non containerized and containerized deployment. The only thing that is different is the name of some playbook (like site, purge)

> * What technology is used in the background when installing ceph containerized? (e.g. docker or LXD)

The container runtime depends on the OS you're using but at the moment ceph-ansible is only supporting docker and podman.

**Comment by modir** [comment]
> You have the same features between non containerized and containerized deployment. The only thing that is different is the name of some playbook (like site, purge)

This means that for the "clients" (e.g. nodes in a KVM cloud cluster) that they have no differences how they mount data disks to a VM? 

> The container runtime depends on the OS you're using but at the moment ceph-ansible is only supporting docker and podman.

It would be great if right after this title https://docs.ceph.com/ceph-ansible/master/#installation would be a sub-title "Requirements for containerized deployment". And there you would have this sentence. (and maybe more information.)
I will try to make a commit with this change.

**Comment by dsavineau** [comment]
> This means that for the "clients" (e.g. nodes in a KVM cloud cluster) that they have no differences how they mount data disks to a VM?

I don't understand what you mean.

The "clients" nodes only import the keyrings and create the pools.

**Comment by modir** [comment]
> The "clients" nodes only import the keyrings and create the pools.

Well, I am not that good with ceph yet, but according to https://docs.ceph.com/docs/master/start/quick-rbd/ the clients create the map of a device image to a local block device as well. Or is this outdated? And if I understood it correctly then I could use those device images to create VMs and mount the images with librados to the VM.
This part would then have to be done outside of the container because there would be a system like e.g. Open Nebula which would be doing this for the users. From my understanding. But I could be wrong.

**Comment by dsavineau** [comment]
> > The "clients" nodes only import the keyrings and create the pools.
> 
> Well, I am not that good with ceph yet, but according to https://docs.ceph.com/docs/master/start/quick-rbd/ the clients create the map of a device image to a local block device as well. Or is this outdated? And if I understood it correctly then I could use those device images to create VMs and mount the images with librados to the VM.
> This part would then have to be done outside of the container because there would be a system like e.g. Open Nebula which would be doing this for the users. From my understanding. But I could be wrong.

Yes, you can still do that but this isn't done in ceph-ansible. Again, the "clients" nodes only import the keyrings and create the pools.
The extra operations you're mentioned have to be done by the user.

The only difference here is that you don't have the `rbd` command on the host when using the containerized deployment so everything related to ceph needs to be executed within a container.

**Comment by modir** [comment]
> The only difference here is that you don't have the rbd command on the host when using the containerized deployment so everything related to ceph needs to be executed within a container.

OK. So in the case that I have a software like e.g. Open Nebula which requires that the rbd command is accessible directly on the host (non-containerized) then I would have to install the rbd command by myself on those servers outside of containers. (Or make sure that Open Nebula somehow runs within containers as well and that they can access rbd.

From a user perspective this is something important to consider before you start deploying a ceph cluster. So from my point of view this should be mentioned in the documentation as well. I will create another pull request for this once the first one got accepted. Thanks so far.

**Comment by modir** [comment]
I will close this issue now. Further communication can be done in the pull request.
