### ISSUE TITLE
No package matching 'calamari-server' is available.

### ISSUE THREAD

**Issue by armaan** [ceph/ceph-ansible#545]
TASK [ceph-agent : install dependencies] ***************************************
fatal: [192.168.122.115]: FAILED! => {"changed": false, "failed": true, "msg": "No package matching 'calamari-server' is available"}
fatal: [192.168.122.116]: FAILED! => {"changed": false, "failed": true, "msg": "No package matching 'calamari-server' is available"}
fatal: [192.168.122.114]: FAILED! => {"changed": false, "failed": true, "msg": "No package matching 'calamari-server' is available"}

**Comment by leseb** [comment]
@armaan a bit more information about your setup will be useful. On which distro are you running on?
@alfredodeza :)

**Comment by armaan** [comment]
@leseb: A 3 node cluster running Ubuntu 14.04.3 LTS. I moved the HEAD to 20e6f932dd50a87bc2db868098d7a61263572562 and successfully installed Ceph.

**Comment by leseb** [comment]
Closing this because of #546 , feel free to re-open.
