### ISSUE TITLE
Run CI for stable-4.0 branch using ansible stable-2.9

### ISSUE THREAD

**Issue by gfidente** [ceph/ceph-ansible#5459]
**Is your feature request related to a problem? Please describe.**
Test ceph-ansible with future ansible 2.9 updates

**Describe the solution you'd like**
Reconfigure CI to install ansible from stable-2.9 branch

**Additional context**
Should be possible to install it with pip doing:
`# pip install --user git+https://github.com/ansible/ansible.git@stable-2.9`

**Comment by gfidente** [comment]
@guits @dsavineau @fultonj @fmount @jctanner

**Comment by fultonj** [comment]
You should be able to avoid https://github.com/ansible/ansible/issues/70168 by setting ansible_python_interpreter no need to block all of 2.9.10.
