### ISSUE TITLE
Purge-cluster is not cleaning NVMe OSD properly resulting in errors of new deployments

### ISSUE THREAD

**Issue by dmitry-rachkov** [ceph/ceph-ansible#5490]
**Bug Report**

Purge-cluster is not cleaning NVMe OSD properly lvm device on bare-metal (containerized)  installation. The purge-cluster itself ends with success, though the new iteration of deployment (on seemingly cleaned system) results in error and breaks on 
_ceph-osd : wait for all osd to be up_

**What happened:**
Deployment of new cluster fails after purge-cluster have not cleaned OSD volumes.
```
[root@node1 ~]# lvs | grep ceph  
  osd-data-41996f11-8ca7-45a5-ab6b-668b751aaf30 ceph-a69b8ee0-56e4-440d-86bb-24ac11545d6c -wi-a----- <465.76g  
[root@node1 ~]# ls -la /var/lib/ceph/
total 4
drwxr-xr-x. 14  167  167  209 Jul  2 09:09 .
drwxr-xr-x. 40 root root 4096 Jun 30 13:53 ..
drwxr-xr-x.  2  167  167   26 Jul  2 09:10 bootstrap-mds
drwxr-xr-x.  2  167  167   26 Jul  2 09:10 bootstrap-mgr
drwxr-xr-x.  2  167  167   26 Jul  2 09:10 bootstrap-osd
drwxr-xr-x.  2  167  167   26 Jul  2 09:10 bootstrap-rbd
drwxr-xr-x.  2  167  167   26 Jul  2 09:10 bootstrap-rbd-mirror
drwxr-xr-x.  2  167  167   26 Jul  2 09:10 bootstrap-rgw
drwxr-xr-x.  3  167  167   24 Jul  2 09:09 mds
drwxr-xr-x.  3  167  167   24 Jul  2 09:09 mgr
drwxr-xr-x.  3  167  167   24 Jul  2 09:09 mon
drwxr-xr-x.  3  167  167   20 Jul  2 09:11 osd
drwxr-xr-x.  3  167  167   28 Jul  2 09:09 radosgw
drwxr-xr-x.  2  167  167   31 Jul  2 09:09 tmp
```

**What you expected to happen:**
Purge-cluster -> purged clean with removal of all ceph-lvm volumes/devices and new deployments afterwards end in success.

**How to reproduce it (minimal and precise):**
- Bare-metal installation, 4 OSD nodes each having NVMe 500G device. 
- Deploy new cluster -> success. 
- Run purge-cluster to destroy and clean (Success exit code, but not actual)
- Run deployment again and experiencing OSD not brought up and exit after 60 retries

Share your group_vars files, inventory and **full** ceph-ansibe log
**Inventory***
node1 ansible_host=192.168.1.4 monitor_address=192.168.1.4
node2 ansible_host=192.168.1.5 monitor_address=192.168.1.5
node3 ansible_host=192.168.1.6 monitor_address=192.168.1.6
node4 ansible_host=192.168.1.7

[mons]
node1
node2
node3

[mgrs]
node1
node2
node3

[osds]
node1
node2
node3
node4

[mdss]
node1
node2
node3
node4

[grafana-server]
node4

**Environment**:
* OS (e.g. from /etc/os-release):
Ansible-controller
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
OSD, MGR. MON, MDS nodes

```
NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="centos"
```
* Kernel (e.g. `uname -a`):

```
[root@node1 ~]# uname -a
Linux osce1.sh.net 4.18.0-193.6.3.el8_2.x86_64 #1 SMP Wed Jun 10 11:09:32 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
* Docker version if applicable (e.g. `docker version`):

```
[root@node1 ~]# podman version
Version:            1.6.4
RemoteAPI Version:  1
Go Version:         go1.13.4
OS/Arch:            linux/amd64
```

* Ansible version (e.g. `ansible-playbook --version`):

```
ansible-playbook 2.9.9
  config file = /tmp/20200701T134544/ceph-ansible/ansible.cfg
  configured module search path = ['/tmp/20200701T134544/ceph-ansible/library']
  ansible python module location = /data/python/virtenvs/ceph-ansible/lib/python3.6/site-packages/ansible
  executable location = /data/python/virtenvs/ceph-ansible/bin/ansible-playbook
  python version = 3.6.9 (default, Nov 11 2019, 11:24:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

* ceph-ansible version (e.g. `git head or tag or stable branch`):

```
(ceph-ansible) (python3) [user@kvm1 ceph-ansible]$ git b
  master
* stable-5.0
```
* Ceph version (e.g. `ceph -v`):
octopus

* Ceph config group_vars
```
(ceph-ansible) (python3) [user@kvm1 ceph-ansible]$ find group_vars/ -type f | xargs grep -v -E "^#|^$" | cut -d: -f2,3,4,5
---
dummy:
configure_firewall: False
ntp_service_enabled: true
ntp_daemon_type: chronyd
ceph_origin: repository
ceph_repository: community
ceph_stable_release: octopus
monitor_interface: eno1
ip_version: ipv4
public_network: 192.168.1.1/24
ceph_docker_image: "ceph/daemon"
ceph_docker_image_tag: latest
ceph_docker_registry: docker.io
containerized_deployment: True
node_exporter_container_image: "docker.io/prom/node-exporter:v0.17.0"
grafana_server_fqdn: 'ceph-dashboard.sh.net'
grafana_container_image: "docker.io/grafana/grafana:5.4.3"
grafana_datasource: Dashboard
grafana_dashboards_path: "/etc/grafana/dashboards/ceph-dashboard"
grafana_dashboard_version: master
grafana_plugins:                                                                                                                                                              
  - vonage-status-panel
  - grafana-piechart-panel
prometheus_container_image: "docker.io/prom/prometheus:v2.7.2"
alertmanager_container_image: "docker.io/prom/alertmanager:v0.16.2"
dashboard_admin_user: admin
dashboard_admin_password: p@ssw0rd
grafana_admin_user: admin
grafana_admin_password: admin
---
dummy:
monitor_secret: "{{ monitor_keyring.stdout }}"
secure_cluster: false
admin_secret: '<my_custom_key>'
---
dummy:
ceph_mgr_packages:
  - ceph-mgr
mgr_secret: '<my_custom_key>'
---
dummy:
devices:
  - /dev/nvme0n1
---
dummy:
---
dummy:
---
dummy:
---
```

I have an idea how to fix it as was looking into the code of purge-cluster and plan to do a pull request, but first wanted to check up with community and hear out maybe somebody has came across already and have a solution.

Thanks

**Comment by dsavineau** [comment]
> Run purge-cluster to destroy and clean (Success exit code, but not actual)

Just to be sure, because you're using a containerized deployment, are you using the purge-container-cluster.yml playbook ?

Also there's no difference between an OSD backed by NVMe, SSD or HDD so it should be purged the same way.

**Comment by dmitry-rachkov** [comment]
Yep, purge-container-cluster.yml 
Okay, I see, I have just mentioned NVMe to provide as more info as possible.

**Comment by dmitry-rachkov** [comment]
That's my bad indeed, I  have overseen the second playbook. Should we delete my dummy thread?
Sorry.

**Comment by dsavineau** [comment]
There's no dummy question, this could be useful to someone else in the future. Let's just close it.
