### ISSUE TITLE
Playbook comments and documentation change for mandatory host_groups indication

### ISSUE THREAD

**Issue by dmitry-rachkov** [ceph/ceph-ansible#5511]
**Is your feature request related to a problem? Please describe.**
After spending quite some time in testing it appeared to me that there is a room for improvement in [documentation, playbook section](https://docs.ceph.com/ceph-ansible/stable-5.0/ ) and comments sections inside _site.yml/site-container.yml_ playbooks related host_groups modifications. 

In particular I learned that there are mandatory host_groups that have to be always described, in my opinion that has to be clearly explained.

**Describe the solution you'd like**
Modify  [documentation](https://docs.ceph.com/ceph-ansible/stable-5.0/ ) and _site.yml/site-container.yml_ that certain host_groups (osds, mons, mgrs, grafana-server) are mandatory and can't be left undefined even if you already have a cluster and let's say want to deploy +1 client (those host_groups are mandatory for proper logic of validation and facts).

In fact, I propose to clearly mention inside all.yml, playbooks and in documentation which of the host_groups are required/mandatory which are optional, similarly to how [openstack_user_config.yml ](https://github.com/openstack/openstack-ansible/blob/master/etc/openstack_deploy/openstack_user_config.yml.example) for instance is commented out. That is especially important, because in documentation there is an encouragement to change the host_groups block 

> Modify the playbook as necessary for the requirements of your cluster

Hence, it make sense give people a hint on what to do and what not based on current functionality.

**Additional context**
I had a cluster and wished to deploy additional components (clients, rgws) and only after spending some time in tests, learned which host_groups are mandatory and that I can't launch the logic only for 1 component.

**Comment by guits** [comment]
@dmitry-rachkov do you mind sending a PR for that? 🙂 
Thanks!

**Comment by dmitry-rachkov** [comment]
Sure, will do.
