### ISSUE TITLE
docs: stable-5.0 documentation doesn't document which ansible versions stable-5.0 support

### ISSUE THREAD

**Issue by tim-seoss** [ceph/ceph-ansible#5519]
The stable-5.0 branch version of the docs ( `docs/source/index.rst` )  don't document which Ceph version(s) are supported by the stable-5.0 branch of ceph-ansible

- ``stable-4.0`` Supports Ceph version ``nautilus``. This branch requires Ansible version ``2.8``.

- ``master`` Supports the master branch of Ceph. This branch requires Ansible version ``2.8``.

... whereas the master version does contain info about which version is supported by stable-5.0:

- ``stable-5.0`` Supports Ceph version ``octopus``. This branch requires Ansible version ``2.9``.

**Comment by guits** [comment]
we are probably missing a backport in stable-5.0
