### ISSUE TITLE
Auto start container after host reboot

### ISSUE THREAD

**Issue by riupie** [ceph/ceph-ansible#5533]
Hi, so I deploy containerized ceph-ansible on found out that after host reboot my container didnt start automatically. In docker environment usually container will start automatically. But because podman is daemonless, we should create systemd for each container so it will start after reboot.

Could we add a playbook where it will create systemd to auto start container?

**Comment by dsavineau** [comment]
We already manage the containers via systemd (both docker or podman) so they should start automatically on reboot.

If it doesn't start then you should check the logs from the systemd service.

**Comment by riupie** [comment]
1. Could I choose docker instead podman?
2. I found the error here, happened on all service not only node-exporter:
```
Error: error creating container storage: the container name "node-exporter" is already in use by "ca80a743ad73576d19019269bf70bad251a1110790907f550f12de41cfc7c24c". You have to remove that container to be able to reuse that name.: that name is already in use
```

I think this part doesnt work:
```
[Service]
EnvironmentFile=-/etc/environment
ExecStartPre=-/usr/bin/rm -f /%t/%n-pid /%t/%n-cid
. . .
ExecStop=-/usr/bin/sh -c "/usr/bin/podman rm -f `cat /%t/%n-cid`"
```
And there is no `-/etc/environment` and `/etc/environment` was empty


I am using Centos 8 + Octopus

**Comment by fultonj** [comment]
This issue should be fixed by:

 https://github.com/ceph/ceph-ansible/pull/5570
