### ISSUE TITLE
The playbook doesn't copy the keyring files accross the cluster

### ISSUE THREAD

**Issue by Chrislevi** [ceph/ceph-ansible#555]
The playbook doesn't copy the keyring files accross the cluster.
It only fetch the keyring from monitors and do not copy the files to the servers in the cluster.

Thank you

**Comment by leseb** [comment]
Can you clarify that? Which files are not being copied?

**Comment by Chrislevi** [comment]
The keyring files fetched to the deployer.
The playbook does not copy them to the other servers.
 
Thanks

**Comment by leseb** [comment]
Well only the necessary keyring are being copied. What are the keys that are not present and that you are looking for?

**Comment by Chrislevi** [comment]
I know their location and I can fix this manually but I want to be able to run ceph command from my osd or from my restapi and my rgw 
Thank you

**Comment by leseb** [comment]
Sorry but this is considered as a bad practice. Nodes other than monitors should not have the admin key. 
Sorry but we won't implement that. However if you can find a flexible way to do it without disrupting the current behavior then I'm good with that. 
Feel free to send a PR for that :). I'm closing this now. 

Thanks!

**Comment by leseb** [comment]
Re-opening this as I've found an easy way to do this.

**Comment by OrFriedmann** [comment]
I wanted this feature too, Thank you

**Comment by Chrislevi** [comment]
Thanks!
