### ISSUE TITLE
Cannot override config 

### ISSUE THREAD

**Issue by uncelvel** [ceph/ceph-ansible#5560]
**Bug Report**

What happened: Cannot override config
https://i.imgur.com/fKvGTwZ.png

What you expected to happen: override config in group_vars set to global cluster ceph 

How to reproduce it (minimal and precise):

Share your group_vars files, inventory and **full** ceph-ansibe log
group_vars: https://termbin.com/5csu
ceph-ansible log: https://termbin.com/c8qe

**Environment**:
* OS (e.g. from /etc/os-release): CentOS 7 
* Kernel (e.g. `uname -a`): 3.10
* Docker version if applicable (e.g. `docker version`): none 
* Ansible version (e.g. `ansible-playbook --version`): 2.8.12
* ceph-ansible version (e.g. `git head or tag or stable branch`): 4.0
* Ceph version (e.g. `ceph -v`): 14.2.10

**Comment by dsavineau** [comment]
The override config works great but you're issue is that you're not using the right ceph section for the `rbd_default_features` parameter.
This should be part of the `client` section instead of `global`.

```yaml
---
ceph_conf_overrides: 
  client:
    rbd_default_features: 125
```

```console
# cat /etc/ceph/ceph.conf 
[client]
rbd_default_features = 125

# Please do not change this file directly since it is managed by Ansible and will be overwritten
[global]
cluster network = 192.168.100.0/24
fsid = 35d3e6e7-6dea-4ccd-abfd-0ea1aa0eae05
mon host = [v2:192.168.100.13:3300,v1:192.168.100.13:6789]
mon initial members = cephaio
osd pool default crush rule = -1
public network = 192.168.100.0/24

# ceph-conf --lookup rbd_default_features
125
```

**Comment by jpic** [comment]
Thank you! Setting it to 7 fixed the following errors for me (sticking here for google indexation):

```
librbd::image::CloneRequest: 0x7f41380513f0 validate_child: cloning image must support layering
```
