### ISSUE TITLE
push tags to GitHub

### ISSUE THREAD

**Issue by ktdreyer** [ceph/ceph-ansible#557]
Would you mind tagging releases occasionally?

Without tags, the only way to track versions is the output of `git rev-parse`, which isn't linear or easy to read :)

**Comment by leseb** [comment]
Hey, yeah yeah I'm currently in the process of doing, I needed to clarify a couple of things first.
I'm currently traveling, so I'll do that next week, first release and tag.

Thanks @ktdreyer

**Comment by leseb** [comment]
https://github.com/ceph/ceph-ansible/releases/tag/v1.0.0
