### ISSUE TITLE
Upgrade fails because podman sees the old image

### ISSUE THREAD

**Issue by rmahique** [ceph/ceph-ansible#5607]
what problem/issue/behavior are you having trouble with?  What do you expect to see?
it fails to pick up the right image, this is related to bug:
https://bugzilla.redhat.com/show_bug.cgi?id=1844496
it tries to use the image for 4.0 instead of the latest as specified in the vars file.

The task "inspect ceph osd container" runs podman inspect which finds the right image but with the wrong image ID of the old one.
...
      "Image": "111111111",
      "ImageName": "myregistry/ceph/rhceph-4-rhel8:latest"
...

if we check the id we find it belongs to another image:
podman inspect 111111111
...
 "RepoTags": [
            "myregistry/ceph/rhceph-4-rhel8:4-20"
        ],
...

the playbook task should use the image defined in the vars file with the right tag to prevent this problem.

Where are you experiencing the behavior? What environment?
fresh install of ceph 4.0, upgrading to latest ceph 4.1

When does the behavior occur? Frequency? Repeatedly? At certain times?
Always

**Comment by dsavineau** [comment]
You don't need to create an issue here if you already have a BZ
