### ISSUE TITLE
OSD's dont load after computer restart

### ISSUE THREAD

**Issue by gilkedar** [ceph/ceph-ansible#562]
Hello
I've been trying to deploy a Ceph cluster for a while now. Every time i succeed, after a computer restart my Ceph cluster is unreachable.
I deployed 5 VMS on Virtualbox, and installed Ceph-depoy version 1.5.31, installed ceph infernalis 9.2.
One admin , 3 nodes(1 mon and 3 osd's each) and one MDS ( i intend to use CephFS).
The cluster functioned very well and was very responsive, but now every command that starts with ceph, such as ceph -s, ceph osd tree is not responsive. after 300 seconds its timed out.

i entered systemctl list-units and found out that ALL OSDs on all nodes wont start up.
Do you have any idea what the problem may be?
I added a few photos to help describe my situation.

if you need additional info please let me know how to get it and i will post.
This is very important to me, Thank you very much in advance!
Gil

![ceph osd failure node1](https://cloud.githubusercontent.com/assets/14829279/13282913/f16d4b04-daf3-11e5-82f2-60d9ace657cd.PNG)
![ceph osd failure](https://cloud.githubusercontent.com/assets/14829279/13282912/f168fc5c-daf3-11e5-8291-5ca08313dc93.PNG)
![systemctl error detail](https://cloud.githubusercontent.com/assets/14829279/13282911/f16708e8-daf3-11e5-9f66-c656b15d304f.PNG)
![systemctl error detail2](https://cloud.githubusercontent.com/assets/14829279/13283000/5c223c98-daf4-11e5-9c53-dba864019edf.PNG)

**Comment by leseb** [comment]
hey @gilkedar, what does `systemctl is-enabled` say about ceph services?

**Comment by gilkedar** [comment]
![is-enabled](https://cloud.githubusercontent.com/assets/14829279/13290935/7144ec9a-db1e-11e5-9c01-8fae0e4c8eba.PNG)

**Comment by leseb** [comment]
Please use the "is-enabled" command instead

**Comment by gilkedar** [comment]
Sorry, wanted to add this pic as well.
all Ceph services are enabled

![is-enabled](https://cloud.githubusercontent.com/assets/14829279/13293086/f067e48e-db26-11e5-82e5-2ce957164dee.PNG)

**Comment by leseb** [comment]
So services are enabled but they don't start at boot right?

**Comment by gilkedar** [comment]
they try to start, but they are unresponsive for some reason. I cant even start them manually =\
Its not the first time it happened to me, every time it happened i had to start all over again. This time i hope to finally find a solution. Im running out of options

**Comment by leseb** [comment]
what do you see when you try manually then?

**Comment by gilkedar** [comment]
the last picture from the first post. It waits a long time and then just failes

**Comment by bengland2** [comment]
I saw a failure to start Ceph mons in Jewel, where it appeared to be expecting sysvinit script but ceph itself is transitioned to native systemd.   Is this related?  if you do "systemctl | grep ceph", what do you see?
