### ISSUE TITLE
at collect admin and bootstrap keys stage, mons all at fault so play hangs.

### ISSUE THREAD

**Issue by snerdish** [ceph/ceph-ansible#565]
Seeing the following on a clean build. 

After seeing a hang in this portion of the play, I logged into the monitor that wasn't coming up and killed the create-key command to see what would come out in the wash. Go this later in the play:

Can't get admin socket path: unable to get conf option admin_socket for mon.storage02: warning: line 77: 'host' in section 'mon.storage02' redefined 
warning: line 78: 'mon_addr' in section 'mon.storage02' redefined 

My inventory contains 

[mons]
192.168.141.16
192.168.141.18
192.168.40.42

The issue would seem to be that 192.168.141.18 maps to storage02.foo.bar, whilst 192.168.40.42 maps to storage02.qux.bar.

The generated ceph.conf section:

[mon.storage01]
host = storage01
mon addr = 192.168.141.16
[mon.storage02]
host = storage02
mon addr = 192.168.141.18
[mon.storage02]
host = storage02
mon addr = 192.168.40.42

Not sure where to go from here.

**Comment by leseb** [comment]
Hum that's because we use the `ansible_hostname` variable. I believe we used to use fqdn, just not sure why we dropped it.
Unfortunately, this is a big change for everyone that is using the playbook, as it will generate a new `ceph.conf` file.

It'll be easier if you could change the hostname of one of the nodes.
Thanks!

**Comment by snerdish** [comment]
Changing the hostname of a node isn't possible; I'm trying to workaround it by using a virtualised host but that's another suite of issues. Happy to close this out but it'd be worth a note in the README

**Comment by snerdish** [comment]
Actually, I really can't change the hostnames of these hosts at all. Not sure if a CNAME will surfice. 

Could there be an option to use FQDN again?

**Comment by leseb** [comment]
@snerdish I'll look into that. Using a FQDN seems legit :)

**Comment by snerdish** [comment]
Given that I'm also using osd nodes as mon nodes, would this not also be required for osds?

**Comment by leseb** [comment]
Not an issue, it will work. We don't have any host section for OSDs.
