### ISSUE TITLE
Adding https support for radosgw in the playbook

### ISSUE THREAD

**Issue by OrFriedmann** [ceph/ceph-ansible#566]
I want to use the playbook and I don't see any option to create certificates and to use https in apache nor civetweb.

Thanks

**Comment by leseb** [comment]
@OrFriedmann well, I'm not sure if this playbook should create certificates and stuff.
It's probably the role of another ansible "role".

**Comment by snerdish** [comment]
I'd terminate SSL on haproxy.

**Comment by leseb** [comment]
Same here, usually HAProxy does the job perfectly.
