### ISSUE TITLE
Running site.yml causes daemon restarts

### ISSUE THREAD

**Issue by jjahns** [ceph/ceph-ansible#5660]
**Bug Report**

What happened:

- Subsequent runs of the site.yml playbook causes daemon restarts on an already configured environment.

What you expected to happen:

- Nothing. Should be idempotent. The only task that was being done was the addition of clients.

How to reproduce it (minimal and precise):

- Run site.yml on an already provisioned environment.

Share your group_vars files, inventory and **full** ceph-ansibe log

- Can attach these, but not sure its necessary for the purpose of this issue.

**Environment**:
* OS (e.g. from /etc/os-release):

NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

* Kernel (e.g. `uname -a`):

Linux sc2-e02-s07 4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

* Docker version if applicable (e.g. `docker version`):

Client:
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        369ce74a3c
 Built:             Fri Feb 28 23:45:43 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       369ce74a3c
  Built:            Wed Feb 19 01:06:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu1~18.04.2
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:     

* Ansible version (e.g. `ansible-playbook --version`):

ansible-playbook 2.9.11
  config file = /repository/ansible/ceph-ansible/ansible.cfg
  configured module search path = [u'/repository/ansible/ceph-ansible/library']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.17 (default, Jul 20 2020, 15:37:01) [GCC 7.5.0]

* ceph-ansible version (e.g. `git head or tag or stable branch`):

stable-5.0

* Ceph version (e.g. `ceph -v`):

ceph version 15.2.4 (7447c15c6ff58d7fce91843b705a268a1917325c) octopus (stable)

**Comment by jjahns** [comment]
Some additional statistics on the environment:

Servers: 12
OSDs: 144
Network: 2x10G (LACP)

Just note this caused quite a bit of recovery churn.

**Comment by jjahns** [comment]
There is another problem.

Pools that were previously created and set to PG autoscale have had their number of PGs dramatically increased which should NOT have happened.

These pools were previously set to 32 PGs, and after running the site playbook again, they expanded to 2048 pages each!

**Comment by GillesMocellin** [comment]
Same here with ceph-ansible stable-5.0 on a 6 node cluster.
More than an hour to execute the site.yml playbook without any modification.
mons, mgr, rgws and especially osds are restarted after every play I think, via handlers.
