### ISSUE TITLE
alertmanager container fails to start with ansible-2.9.12

### ISSUE THREAD

**Issue by karelyatin** [ceph/ceph-ansible#5677]
**Bug Report**

Tried deploying TripleO(which uses ceph-ansible to deploy ceph services) with ansible-2.9.12 https://review.rdoproject.org/r/#/c/28996/ but alertmanager container is not able to start. It's due to ansible-2.9.12 made the file permissions strict[1] and now "mode" needs to be specified explicitly, alertmanger.yml create task[2] doesn't have "mode" defined so permissions are set to 600 instead of 666 as in earlier ansible versions.
 
Warning is also reported for /etc/prometheus/prometheus.yml but issue not seen in it as "owner" is set[3] and it has read permission.

[1] https://github.com/ansible/ansible/commit/0199b1cf05e1838bc65ac26d99f2c5505c24ad0f
[2] https://github.com/ceph/ceph-ansible/blob/622d9feae924b216d02fc10a90c5a2089ab98794/roles/ceph-prometheus/tasks/main.yml#L41-L45
[3] https://github.com/ceph/ceph-ansible/blob/622d9feae924b216d02fc10a90c5a2089ab98794/roles/ceph-prometheus/tasks/main.yml#L15

What you expected to happen:

Deployment should succeed with ansible-2.9.12.

How to reproduce it (minimal and precise):

A deployment of alertmanager with ansible-2.9.12 should reproduce it.

Share your group_vars files, inventory and **full** ceph-ansibe log
Log link:- https://logserver.rdoproject.org/96/28996/1/check/rdoinfo-tripleo-master-testing-centos-8-scenario004-standalone/e13825e/logs/undercloud/home/zuul/standalone-ansible-0ofy65b3/ceph-ansible/ceph_ansible_command.log.txt.gz
Pasting relevent warnings from log here:-
[WARNING]: File '/etc/prometheus/prometheus.yml' created with default permissions '600'. The previous default was '666'. Specify 'mode' to avoid this warning.
[WARNING]: File '/etc/alertmanager/alertmanager.yml' created with default permissions '600'. The previous default was '666'. Specify 'mode' to avoid this warning.

**Environment**:
* OS (e.g. from /etc/os-release): CentOS-8
* Kernel (e.g. `uname -a`): Linux ykarel-ansible-debug.localdomain 4.18.0-147.3.1.el8_1.x86_64 #1 SMP Fri Jan 3 23:55:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Docker version if applicable (e.g. `docker version`): Using podman-1.6.4-10.module_el8.2.0+305+5e198a41.x86_64
* Ansible version (e.g. `ansible-playbook --version`): 2.9.12
* ceph-ansible version (e.g. `git head or tag or stable branch`): ceph-ansible-4.0.25-1.el8.noarch
* Ceph version (e.g. `ceph -v`): docker.io/ceph/daemon:v4.0.8-stable-4.0-nautilus-centos-7-x86_64

**Comment by mwhahaha** [comment]
Caused by https://github.com/ansible/ansible/issues/71200
