### ISSUE TITLE
Monitors fail to form the quorum

### ISSUE THREAD

**Issue by mikabytes** [ceph/ceph-ansible#5713]
**Bug Report**

What happened:
I ran ceph-ansible and it failed after 10 attempts of `RETRYING: waiting for the monitor(s) to form the quorum... ` and a status dump:

```
{"name":"g0","rank":-1,"state":"probing","election_epoch":0,"quorum":[],"features":{"required_con":"0","required_mon":[],"quorum_con":"0","quorum_mon":[]},"outside_quorum":["g0"],"extra_probe_peers":[{"addrvec":[{"type":"v2","addr":"10.0.0.1:3300","nonce":0},{"type":"v1","addr":"10.0.0.1:6789","nonce":0}]},{"addrvec":[{"type":"v2","addr":"10.0.0.2:3300","nonce":0},{"type":"v1","addr":"10.0.0.2:6789","nonce":0}]},{"addrvec":[{"type":"v2","addr":"10.0.0.3:3300","nonce":0},{"type":"v1","addr":"10.0.0.3:6789","nonce":0}]}],"sync_provider":[],"monmap":{"epoch":0,"fsid":"9a2c999e-e251-4545-ad83-479ec66fb500","modified":"2020-08-26T18:50:29.031816Z","created":"2020-08-26T18:50:29.031816Z","min_mon_release":0,"min_mon_release_name":"unknown","features":{"persistent":[],"optional":[]},"mons":[{"rank":0,"name":"g0","public_addrs":{"addrvec":[]},"addr":"(unrecognized address family 0)/0","public_addr":"(unrecognized address family 0)/0","priority":0,"weight":0},{"rank":1,"name":"g1","public_addrs":{"addrvec":[{"type":"v1","addr":"0.0.0.0:0","nonce":1}]},"addr":"0.0.0.0:0/1","public_addr":"0.0.0.0:0/1","priority":0,"weight":0},{"rank":2,"name":"g2","public_addrs":{"addrvec":[{"type":"v1","addr":"0.0.0.0:0","nonce":2}]},"addr":"0.0.0.0:0/2","public_addr":"0.0.0.0:0/2","priority":0,"weight":0}]},"feature_map":{"mon":[{"features":"0x3f01cfb8ffadffff","release":"luminous","num":1}]}}
```

```
# all.yml

ceph_origin: distro
ceph_stable_release: octopus
monitor_interface: tun0
public_network: 2001:9b1::/32
cluster_network: 10.0.0.0/32
```

I have also tried using an IPv4 address range for the `public_network` key. Same result.

```
# hosts

[mons]
g0
g1
g2

[osds]
g0

[grafana-server]
g0
```

What you expected to happen:
Monitors to be installed on all three nodes which are connected through the tun0 device. Instead, it says something about "unrecognized address family 0". I don't have any `0.0.0.0` anywhere.

How to reproduce it (minimal and precise):
Install ubuntu server 20.04 on three computers, set them up with a common cluster network called "tun0" and run ceph-ansible with provided values.

**Environment**:
* OS (e.g. from /etc/os-release):Ubuntu Server 20.04
* Kernel (e.g. `uname -a`): Linux g0 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Docker version if applicable (e.g. `docker version`):
* Ansible version (e.g. `ansible-playbook --version`): 2.9.6
* ceph-ansible version (e.g. `git head or tag or stable branch`): stable-5.0
* Ceph version (e.g. `ceph -v`): ceph version 15.2.3 (d289bbdec69ed7c1f516e0a093594580a76b78d0) octopus (stable)

[group_vars/all.yml](https://gist.github.com/mikabytes/ed4f4618b44e82c1337aeaf6a7a1710f)
[ansible_log](https://gist.github.com/mikabytes/367da317efc1f4bcb9269a09b7d1df29)

**Comment by dsavineau** [comment]
A couple of comments.

```yaml
public_network: 2001:9b1::/32
cluster_network: 10.0.0.0/32
```

I've never tried this but I'm pretty sure we don't support a mix of IPv4 and IPv6 networks for `public_network` and `cluster_network`

If you want to use IPv6 addresses then you need to set the `ip_version` variable to `ipv6` (ipv4 is the default value [1])

We can see from the ansible log that the ipv4 monitor fact are executed and ipv6 skipped [2]

```yaml
monitor_interface: tun0
```
Be sure to have the ipv6 address from the `public_network` cidr present on that interface.

Last thing

```yaml
cluster_network: 10.0.0.0/32
```
This will probably never work due to the /32 netmask. Is this a typo ?

[1] https://gist.github.com/mikabytes/ed4f4618b44e82c1337aeaf6a7a1710f#file-all-yml-L319
[2] https://gist.github.com/mikabytes/367da317efc1f4bcb9269a09b7d1df29#file-ansible-log-L826-L847

**Comment by mikabytes** [comment]
Ahhh, yep, that did the trick.

For some reason I assumed the monitors would be talking on the cluster network. No wonder they couldn't talk to each-other.

So to sum up for others, this is what I did:
1. Switch cluster network to ipv6 and set configuration to ipv6 (now everything is ipv6).
2. Change the monitor addresses to use the public network


(about the netmask, yeah /32 was wrong, it should have been /24)
