### ISSUE TITLE
os_tuning_params:  cause panic to the osd in the deployment

### ISSUE THREAD

**Issue by Chrislevi** [ceph/ceph-ansible#574]
The vm* options cause panic to the osd in deployment while using ubuntu vms (VirtualBox and Vsphere) 
#os_tuning_params:
#   - { name: kernel.pid_max, value: 4194303 }
#  - { name: fs.file-max, value: 26234859 }
#  - { name: vm.zone_reclaim_mode, value: 0 }
#  - { name: vm.vfs_cache_pressure, value: 50 }
#  - { name: vm.min_free_kbytes, value: "{{ vm_min_free_kbytes }}" }

**Comment by leseb** [comment]
Hum well all the past issues were related to `vm_min_free_kbytes`, this was fixed in #543, do you know which value is causing the kernel panic?

**Comment by Chrislevi** [comment]
After ive disabled those vars, I ran the playbook again and it worked, after it finished to install ceph I ran it again with those vars and it wasn't causing 'panic'.. how come?

**Comment by leseb** [comment]
@Chrislevi would you mind trying line per line so we can check which var is causing this?
Thanks!

btw: we don"t have any issue on the CI (VMs), same for my laptop (vagrant env).
