### ISSUE TITLE
Docs vanished

### ISSUE THREAD

**Issue by pcolledg-xilinx** [ceph/ceph-ansible#5798]
http://docs.ceph.com/ceph-ansible/ is no more! It gives a 404!

Looks like `docs.ceph.com` domain moved to new readthedocs.org hosting yesterday (16th).

```bash
$ curl -svL http://docs.ceph.com/ceph-ansible/
> GET /ceph-ansible/ HTTP/1.1
> Host: docs.ceph.com
...
< HTTP/1.1 302 Found
...
< Location: https://docs.ceph.com/en/latest/ceph-ansible/
...
* Server certificate:
*  start date: Sep 16 00:00:00 2020 GMT
...
> GET /en/latest/ceph-ansible/ HTTP/2
> Host: docs.ceph.com
...
< HTTP/2 404
```

**Comment by tchaikov** [comment]
i added ceph-ansible as a subproject and added a redirect rule, hopefully this could address the issue you had.

**Comment by dsavineau** [comment]
Now the url is working again do we need to do something else ? Like changing the jenkins doc job ? or is it only something about vhost and redirection ? @tchaikov

**Comment by tchaikov** [comment]
> Now the url is working again do we need to do something else ? Like changing the jenkins doc job ? 

no need. as RTD is now subscribed to github events. so whenever a new commit is pushed to master, RTD will clone and rebuilt the document.

> or is it only something about vhost and redirection ? @tchaikov

something like that. to be specific, we just added a CNAME record to point docs.ceph.com to ceph.readthedocs.io and also updated the settings of our RTD project to use docs.ceph.com as the canonical domain name.

**Comment by pcolledg-xilinx** [comment]
The documentation appears to now be located at https://docs.ceph.com/projects/ceph-ansible/

The old URL published in [README.rst](https://github.com/ceph/ceph-ansible/blob/master/README.rst) (ie. without `/projects/`) is still broken.

**Comment by tchaikov** [comment]
> The old URL published in [README.rst](https://github.com/ceph/ceph-ansible/blob/master/README.rst) (ie. without `/projects/`) is still broken.

added a redirect rule for http://docs.ceph.com/ceph-ansible/master/. should be good now.

**Comment by SLongofono** [comment]
> > The old URL published in [README.rst](https://github.com/ceph/ceph-ansible/blob/master/README.rst) (ie. without `/projects/`) is still broken.
> 
> added a redirect rule for http://docs.ceph.com/ceph-ansible/master/. should be good now.

This README and the associated link are still broken

**Comment by tchaikov** [comment]
> 
> This README and the associated link are still broken

@SLongofono could you be more specific ? which URLs are broken?

**Comment by SLongofono** [comment]
The ones in the comment I quoted: 

https://github.com/ceph/ceph-ansible/blob/master/README.rst
http://docs.ceph.com/ceph-ansible/master/

I'm still getting a 404 for the latter.



This one is accessible:
> The documentation appears to now be located at https://docs.ceph.com/projects/ceph-ansible/
> 
> The old URL published in [README.rst](https://github.com/ceph/ceph-ansible/blob/master/README.rst) (ie. without `/projects/`) is still broken.

**Comment by tchaikov** [comment]
i am able to access http://docs.ceph.com/ceph-ansible/master/ though. could you try it again?

**Comment by SLongofono** [comment]
> i am able to access http://docs.ceph.com/ceph-ansible/master/ though. could you try it again?

It is still broken on my end, I tried from several networks and devices to rule out any local problems/caching.

**Comment by tchaikov** [comment]
> > i am able to access http://docs.ceph.com/ceph-ansible/master/ though. could you try it again?
> 
> It is still broken on my end, I tried from several networks and devices to rule out any local problems/caching.

thank you @SLongofono ! i asked my workmate to verify this. and it turns out i was using chrome / chromium to test this link. but when it comes to firefox and curl, they just have 404. i created a fix last night. it should address this 404 issue once and for all. no redirect needed anymore.

**Comment by mschindl** [comment]
Same issue with Safari for http://docs.ceph.com/ceph-ansible/master/ 

" SORRY            /
         \                         /
          \    This page does     /
           ]   not exist yet. "

Is it possible that the right link is following?
https://docs.ceph.com/projects/ceph-ansible/en/latest/index.html

**Comment by tchaikov** [comment]
@mschindl yes. just updated README.rst.

**Comment by SLongofono** [comment]
@tchaikov I know this is not the right way to do this, but the create issue button is hidden on the various Ceph projects.

The same documentation issue seems to be happening on the ceph-deploy repo as well.

[This link](http://ceph.com/ceph-deploy/docs) is broken in README.rst there.

**Comment by tchaikov** [comment]
@SLongofono quite a few Ceph projects are using http://ceph.com/ceph-deploy/docs for tracking bug reports. but yeah, it's a convenience venue to report the issues. =(

i just fixed ceph-deploy's README.rst.

but jewel is EOL, and i am not able to change Google's behavior. so probably we need to wait longer.

the api links are known issue. as we cannot build them on RTD at the time of writing.
