### ISSUE TITLE
Add possibilily to create erasure profile for datapool

### ISSUE THREAD

**Issue by makinapower** [ceph/ceph-ansible#5825]
**Is your feature request related to a problem? Please describe.**

- In the all.yml file, (in the CEPHFS Section) the creation of datapool allows us to specify **_erasure_profiles_**, but we do not have the possibility to create them upstream, only the default profile is available.

**Describe the solution you'd like**

- Add the ability to create erasure profiles before pool creation

**Comment by BurkovBA** [comment]
Same issue here.

Clearly, for larger storages erasure coded profiles give a huge advantage over replicated pools, yet, you can't create anything but the default (pretty useless) profile, using ceph-ansible.

Please, provide a configuration option to allow for erasure-code-profile creation.
