### ISSUE TITLE
redhat dependency list should not install EPEL

### ISSUE THREAD

**Issue by alfredodeza** [ceph/ceph-ansible#584]
It currently tries to install `epel-release` on RH systems which should not happen as dependencies should be met by RHCS.

On *CentOS* systems, yes, that should be installed.

This should be changed to reflect that: https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-common/defaults/main.yml#L38

Bugzilla ticket: https://bugzilla.redhat.com/show_bug.cgi?id=1313037

**Comment by leseb** [comment]
@alfredodeza, since it's a list you can remove the epel-release. Is this really an issue?
You can update the group_vars/all file and you're good.

**Comment by alfredodeza** [comment]
@leseb I am concerned about allowing upstream packages for a redhat box instead of whatever is provided by the CDN.

By default, that list will include `epel-release` which is already not available in a redhat box, so the deployment process breaks. There has to be a clear distinction between CentOS and RedHat (ceph-ansible currently sees both as the same I think) and a further distinction between RedHat using community packages or CDN provided ones.

I would rather default to have a RedHat system be detected and assume that it will want CDN/downstream packages. In the case it doesn't then *the user* should change its playbook to accommodate for that.

**Comment by leseb** [comment]
@alfredodeza yes I agree, I guess my previous response was just me being a bit lazy haha.
I believe we need to work on a clearer distinction between RHEL and CentOS.

I think we can remove epel from this variable and expend the `with_items` list with epel here https://github.com/ceph/ceph-ansible/blob/e9f3e792b03d36a6bd6837762465c54a45a5dfcb/roles/ceph-common/tasks/installs/install_on_redhat.yml#L6 when we run CentOS.

Would you mind taking care of the change?

**Comment by alfredodeza** [comment]
@leseb :) Yep, no worries, I self-assigned this to me. Will send something for review today. Your input is always super awesome. Thank you so much.

**Comment by leseb** [comment]
@alfredodeza thanks thanks! :D
