### ISSUE TITLE
msg: Error when trying to enable ceph: rc=1 Failed to execute operation: No such file or directory

### ISSUE THREAD

**Issue by snerdish** [ceph/ceph-ansible#585]
Getting the following in TASK: [ceph-osd | start and add that the OSD service to the init sequence] **** 

TASK: [ceph-osd | start and add that the OSD service to the init sequence] **** 
failed: [foo.bar] => {"failed": true}
msg: Error when trying to enable ceph: rc=1 Failed to execute operation: No such file or directory

Seem to be some issues with systemd unit file management atm.

**Comment by leseb** [comment]
Yes, it looks like it cannot find the systemd unit files

**Comment by leseb** [comment]
Oh I see you're using the directory scenario, can you check if the OSD gets started anyway?
If so, we can probably remove this task.

**Comment by snerdish** [comment]
Looks like the OSD gets started.
