### ISSUE TITLE
[adding new mon] new mon hangs on 'fetch ceph initial keys' for a long time

### ISSUE THREAD

**Issue by Scooty5** [ceph/ceph-ansible#5864]
**Bug Report**

**IMPORTANT**: This bug may be connected with https://github.com/ceph/ceph-ansible/issues/5863 (but not necessarily)

What happened:
When adding new mon using `infrastructure-playbooks/add-mon.yml`, the playbook hangs on task `fetch ceph initial keys` on newly created node for a extremly long time(i'm not sure what is exact timeout but approx. 20-30min).

```
TASK [ceph-mon : fetch ceph initial keys] ****************************************************************************
Monday 28 September 2020  19:07:13 +0200 (0:00:21.772)       0:03:20.310 ******
ok: [controller0]
ok: [controller1]
(now ansible waits for controller2)
```

What you expected to happen:
I see 2 possible scenarios:
1. Do not execute this task at all if it could end with timeout and everything still works fine.
2. Set a small `--connect-timeout` for this task to avoid a huge waste of time caused by waiting for this task to finish(with timeout)

How to reproduce it (minimal and precise):
Just add new mon running playbook `infrastructure-playbooks/add-mon.yml`

**Environment**:
* OS (e.g. from /etc/os-release): Centos 8
* Kernel (e.g. `uname -a`): 4.18.0-193.19.1.el8_2.x86_64
* Docker version if applicable (e.g. `docker version`): 19.03.13
* Ansible version (e.g. `ansible-playbook --version`): 2.9.13
* ceph-ansible version (e.g. `git head or tag or stable branch`): origin/stable-5.0
* Ceph version (e.g. `ceph -v`): 15.2.5

**Comment by ksingh7** [comment]
+1  to this issue , i am facing the same

**Comment by chandidas** [comment]
+1 . same issue found on both `stable-5.0` and `stable-4.0`

**Comment by itsafire** [comment]
+1 Same problem here. Im on stable-4.0. Problem here is, that the newly created monitor is indeed running and trying to join the other monitors, but it has a different monitor keyring in /var/lib/ceph/mon/ceph-<monid>/keyring. 

The log for the newly created monitor thus shows:

```
[...]
2020-11-06 10:25:29.426 7f7b3af590 -1 mon.miniceph5@0(probing) e0 handle_auth_bad_method hmm, they didn't like 2 result (13) Permission denied
2020-11-06 10:25:44.350 7f7abae590 -1 mon.miniceph5@0(probing) e0 handle_auth_bad_method hmm, they didn't like 2 result (13) Permission denied
[...]
```

Changing the keyring to the cluster monitor keyring and restarting the monitor, will allow the monitor to join the quorum.

@chandidas @ksingh7 Are you seeing this as well?

**Comment by Eljaja** [comment]
+2

**Comment by jeevadotnet** [comment]
When I add a new monitor with `add-mon.yml` or `site-container.yml`

`add-mon.yml` - runbook successful, however it doesn't +1 to ceph status
when `/bin/bash` on the mon container and `ceph status`
```[errno 13] RADOS permission denied (error connecting to the cluster)```

`site-container.yml` 
runbook errors out
```[errno 13] RADOS permission denied (error connecting to the cluster)```

**Comment by jvleminc** [comment]
Also happens in "6.0.3"; task took 50m to go through...
```
TASK [ceph-mon : fetch ceph initial keys] ********************************
Monday 19 April 2021  23:38:48 +0000 (0:02:44.797)       0:04:30.566
ok: [ceph3]
ok: [ceph1]

ok: [ceph2]  <<-------50m

TASK [ceph-mon : include secure_cluster.yml] ***************************
Tuesday 20 April 2021  00:28:48 +0000 (0:50:00.674)       0:54:31.241 
skipping: [ceph1]
skipping: [ceph2]
skipping: [ceph3]

```
