### ISSUE TITLE
TASK [ceph-mon : collect admin and bootstrap keys]  hangs while installing master branch

### ISSUE THREAD

**Issue by smanjara** [ceph/ceph-ansible#587]
This is found only while installing master dev branch. The task hangs while doing ceph-create-keys.

/usr/bin/python /usr/bin/ceph --cluster=ceph --admin-daemon=/var/run/ceph/ceph-mon.node1.asok mon_status
admin_socket: exception getting command descriptions: [Errno 2] No such file or directory
INFO:ceph-create-keys:ceph-mon admin socket not ready yet.

The admin socket is not being created.

**Comment by leseb** [comment]
Hum probably because the monitor didn't start, can you check that?

**Comment by smanjara** [comment]
That's true. It hasn't started the mon. Not sure why. I don't really see anything in the logs.

**Comment by leseb** [comment]
Please try start it manually from the command line using the "ceph" user if you run infernalus or above.

**Comment by smanjara** [comment]
I did try to start it manually: # sudo start ceph-mon id=mon.node1
ceph-mon (ceph/mon.node1) stop/pre-start, process 1423
# sudo status ceph-mon id=mon.node1
status: Unknown instance: ceph/mon.node1
Doesn't seem like it is able to start it. 
I am able to install a stable branch like infernalis. I see this issue only on dev branch like master.

**Comment by smanjara** [comment]
ceph-mon is not being installed from master branch. All other packages are installed. Started it using "ceph-mon -i node1" which started the mon process successfully.
#dpkg-query -l | grep ceph
ceph                                 10.0.3-2483-g3d8fc94-1trusty 
ceph-common                          10.0.3-2483-g3d8fc94-1trusty
ceph-fs-common                       10.0.3-2483-g3d8fc94-1trusty

**Comment by leseb** [comment]
Oh right, now packages are split with ceph-mon, ceph-osd etc.
We need to work on that.

**Comment by masterdubs** [comment]
solved also with adding your hosts in /etc/hosts

**Comment by pujamud** [comment]
I am still facing this issue. Recently i cloned the repository and it hangs at this point:
TASK [ceph-mon : collect admin and bootstrap keys].
I used a 2 weeks old repository which I had issued for ceph deployment using ansible and it worked perfectly fine. Please can you let me know what was the change that was made that has caused this issue.

**Comment by leseb** [comment]
@pujamud which distro are you running on?

**Comment by pujamud** [comment]
I am running this on RHEL7.2.

**Comment by pujamud** [comment]
rpm -qa | grep ceph
ceph-coomon-0.94.5-9.el7cp.x86_64
ceph-osd-0.94.5-9.el7cp.x8_64
ceph-mon-0.94.5-9.el7cp.x86_64
ceph-0.94.5-9.el7cp.x86_64

**Comment by leseb** [comment]
@pujamud why don't you use Jewel instead of Hammer? Especially if you're deploying a new cluster.

**Comment by pujamud** [comment]
I will try using Jewel.
