### ISSUE TITLE
Tracking local deployment in Git - infrastructure as a code

### ISSUE THREAD

**Issue by martingolas** [ceph/ceph-ansible#5892]
Cheers,
this is not a bug or feature request, more like a gerenal question.

How does one keep track of own deployment of CEPH via ceph-ansible in Git? Sort of like infrastructure as a code? Should I fork the repo, modify .gitignore and push to my own repo? Or should I keep my group_vars, inventory and site.yml completely out of the tree and track upstream ceph-ansible as a submodule?

How do you guys do it?

Thanks.

**Comment by dsavineau** [comment]
> Or should I keep my group_vars, inventory and site.yml completely out of the tree and track upstream ceph-ansible as a submodule?

You should definitly have a dedicated repository for your data (inventory, group_vars and host_vars). Not sure if you really need to track this via git submodule as you can do that without it.
