### ISSUE TITLE
When deploying monitoring to its own node, container packages are not installed

### ISSUE THREAD

**Issue by distributorofpain** [ceph/ceph-ansible#5930]
**Bug Report**

What happened:  
I setup a stand alone node just for monitoring(prometheus and grafana ).  When the playbooks are run, it does not install container packages on that node.  Since the monitoring is not setup, the rest of the dashboard installation fails as well when the monitoring system fails to start.

During the install you can see it not including the container package installation on the stand alone monitoring node.

What you expected to happen:
Expected the required container packages to be installed on the independent monitoring node.

How to reproduce it (minimal and precise):
Add a separate node not being used for any ceph installs ( rgw/mon/osd/etc ) to the ansible hosts file under the monitoring section.  I can install podman manually ( dnf install podman ) on that node and then rerun the ceph cluster setup playbook site.yml and it will then finish the cluster installation.

I do have the the "containerized_deployment: False" setting in the all.yml file, but i assumed that was for containerizing ALL of the ceph components, which i dont want to do at this time.

Also, speaking of ansible things during setup, it appears some pieces of the full script select ALL entries in the inventory file.  I am not quite certain if this was done for a reason or not, its not a huge problem, but it does require me to use a separate inventory file for the ceph-ansible installs since it will try to do things on any host listed in the inventory file.  I use some preflight scripts to do basic pre-installation tasks.

Share your group_vars files, inventory and **full** ceph-ansibe log

**Environment**:
* OS (e.g. from /etc/os-release):  CentOS 8
* Kernel (e.g. `uname -a`): Linux localhost.localdomain 4.18.0-193.el8.x86_64 #1 SMP Fri May 8 10:59:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Docker version if applicable (e.g. `docker version`):
* Ansible version (e.g. `ansible-playbook --version`):  2.9.13
* ceph-ansible version (e.g. `git head or tag or stable branch`): 5.0
* Ceph version (e.g. `ceph -v`): 15.2.5

**Comment by dsavineau** [comment]
> I do have the the "containerized_deployment: False" setting in the all.yml file, but i assumed that was for containerizing ALL of the ceph components, which i dont want to do at this time

That's right, the `containerized_deployment` variable has no effect for the monitoring stack because it's always containerized so you should have podman or docker installed on that node too.

https://github.com/ceph/ceph-ansible/blob/stable-5.0/dashboard.yml#L30-L31

> Share your group_vars files, inventory and full ceph-ansibe log

Because there's no information as asked, I will try to guess : did you set `dashboard_enabled: true` ?

**Comment by distributorofpain** [comment]
Here are the requested files...
[5930_Requested_Files.zip](https://github.com/ceph/ceph-ansible/files/5375508/5930_Requested_Files.zip)

**Comment by dsavineau** [comment]
The monitoring group is only present on the master branch and not on the stable-5.0 branch so it's still grafana-server for that one.

https://github.com/ceph/ceph-ansible/commit/eefe11d90cc82ddcaa257b91a1b797810f026c29

**Comment by distributorofpain** [comment]
This issue was related to the git client on the local machine not syncing with the correct version main folder.  I wiped the local repository and pulled the repository again.  The correct files were pulled in the second time.  Could have been user error.
