### ISSUE TITLE
Better Documentation!

### ISSUE THREAD

**Issue by kuthedk** [ceph/ceph-ansible#5977]
I'm quite frustrated with how there is almost no documentation around the playbook and the configuration of all.yml file.

The solution I would like to see is an update to the documentation that has a section for what each thing in the all.yml configuration file does, and when you would use it. Also, would like to see better documentation on setting Ceph Docker on OpenStack up.

**Comment by modir** [comment]
I had the same frustration as you. Don't expect many changes unless you do it yourself. What I did and what I recommend you is this: Ask here specific questions and once you have the answer go to https://github.com/ceph/ceph-ansible/tree/master/docs/source and then edit the documentation and add a new section with the answer you got here. This way the documentation here gets slowly better and everyone can benefit.

**Comment by jeevadotnet** [comment]
Believe me its been discussed on IRC and other places over & over. They don't have the human capital to do documentation. Your best bet is asking #ceph on IRC or firing of an email to the ceph user mailing list.

**Comment by kuthedk** [comment]
cool. will eventually get around to it

**Comment by zdover23** [comment]
> cool. will eventually get around to it

@kuthedk I'm the upstream docs guy for Ceph. Send me an email at zac.dover@gmail.com and we'll talk about this.
