### ISSUE TITLE
error while using radosgw_keystone: true

### ISSUE THREAD

**Issue by OrFriedmann** [ceph/ceph-ansible#598]
I got an error :  failed: [ceph01] => (item=openssl x509 -in /etc/keystone/ssl/certs/ca.pem -pubkey |certutil -d /var/lib/ceph/radosgw/ceph-radosgw.ceph01/nss -A -n ca -t 'TCu,Cu,Tuw') => {"changed": true, "cmd": "openssl x509 -in /etc/keystone/ssl/certs/ca.pem -pubkey |certutil -d /var/lib/ceph/radosgw/ceph-radosgw.ceph01/nss -A -n ca -t 'TCu,Cu,Tuw'", "delta": "0:00:00.006398", "end": "2016-03-03 08:29:34.348250", "item": "openssl x509 -in /etc/keystone/ssl/certs/ca.pem -pubkey |certutil -d /var/lib/ceph/radosgw/ceph-radosgw.ceph01/nss -A -n ca -t 'TCu,Cu,Tuw'", "rc": 255, "start": "2016-03-03 08:29:34.341852", "warnings": []}

At the begin I installed manually libnss3-tools
and now I got the error above.
Any ideas?

Thanks

**Comment by leseb** [comment]
Perhaps I'm blind but I can't see the error, can you run the command manually and paste the error?

**Comment by OrFriedmann** [comment]
failed: [ceph01] => (item=openssl x509 -in /etc/keystone/ssl/certs/ca.pem -pubkey |certutil -d /var/lib/ceph/radosgw/ceph-radosgw.ceph01/nss -A -n ca -t 'TCu,Cu,Tuw') => {"changed": true, "cmd": "openssl x509 -in /etc/keystone/ssl/certs/ca.pem -pubkey |certutil -d /var/lib/ceph/radosgw/ceph-radosgw.ceph01/nss -A -n ca -t 'TCu,Cu,Tuw'", "delta": "0:00:00.006398", "end": "2016-03-03 08:29:34.348250", "item": "openssl x509 -in /etc/keystone/ssl/certs/ca.pem -pubkey |certutil -d /var/lib/ceph/radosgw/ceph-radosgw.ceph01/nss -A -n ca -t 'TCu,Cu,Tuw'", "rc": 255, "start": "2016-03-03 08:29:34.341852", "warnings": []}
stderr: Error opening Certificate /etc/keystone/ssl/certs/ca.pem
140144414439072:error:02001002:system library:fopen:No such file or directory:bss_file.c:398:fopen('/etc/keystone/ssl/certs/ca.pem','r')
140144414439072:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:400:
unable to load certificate
Notice: Trust flag u is set automatically if the private key is present.
certutil: could not decode certificate: SEC_ERROR_INVALID_ARGS: security library: invalid arguments.
failed: [ceph01] => (item=openssl x509 -in /etc/keystone/ssl/certs/signing_cert.pem -pubkey | certutil -A -d /var/lib/ceph/radosgw/ceph-radosgw.ceph01/nss -n signing_cert -t 'P,P,P') => {"changed": true, "cmd": "openssl x509 -in /etc/keystone/ssl/certs/signing_cert.pem -pubkey | certutil -A -d /var/lib/ceph/radosgw/ceph-radosgw.ceph01/nss -n signing_cert -t 'P,P,P'", "delta": "0:00:00.006289", "end": "2016-03-03 08:29:34.435869", "item": "openssl x509 -in /etc/keystone/ssl/certs/signing_cert.pem -pubkey | certutil -A -d /var/lib/ceph/radosgw/ceph-radosgw.ceph01/nss -n signing_cert -t 'P,P,P'", "rc": 255, "start": "2016-03-03 08:29:34.429580", "warnings": []}
stderr: Error opening Certificate /etc/keystone/ssl/certs/signing_cert.pem
139998442296992:error:02001002:system library:fopen:No such file or directory:bss_file.c:398:fopen('/etc/keystone/ssl/certs/signing_cert.pem','r')
139998442296992:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:400:
unable to load certificate
certutil: could not decode certificate: SEC_ERROR_INVALID_ARGS: security library: invalid arguments.

**Comment by OrFriedmann** [comment]
ok while running it manually: user@ceph01:~/Ceph$ openssl x509 -in /etc/keystone/ssl/certs/ca.pem -pubkey |certutil -d /var/lib/ceph/radosgw/ceph-radosgw.ceph01/nss/ -A -n ca -t 'TCu,Cu,Tuw'  
Error opening Certificate /etc/keystone/ssl/certs/ca.pem
140165439157920:error:02001002:system library:fopen:No such file or directory:bss_file.c:398:fopen('/etc/keystone/ssl/certs/ca.pem','r')
140165439157920:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:400:
unable to load certificate
certutil: function failed: SEC_ERROR_LEGACY_DATABASE: The certificate/key database is in an old, unsupported format.

**Comment by leseb** [comment]
No such file or directory?

**Comment by OrFriedmann** [comment]
Found the problem I had to get the certificates from the keystone controller to the ceph, to the directory that the openssl looked for /etc/keystone/ssl/certs

Another thing maybe the playbook should install libnss3-tools when using integration with openstack

Thank you
