### ISSUE TITLE
Deploy octopus with specific version

### ISSUE THREAD

**Issue by clwluvw** [ceph/ceph-ansible#5980]
**Describe the solution you'd like**
Ceph support specific version of octopus releases in download.ceph.com like `debian-15.2.5`

**Comment by dsavineau** [comment]
Use:

```yaml
ceph_stable_repo: "{{ ceph_mirror }}/debian-15.2.5"
```

Instead of the default value [1] that use the latest release available.

[1] https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-defaults/defaults/main.yml#L137
