### ISSUE TITLE
Add support for CoreOS.

### ISSUE THREAD

**Issue by PiotrProkop** [ceph/ceph-ansible#600]
Currently dockerized deployment of ceph-ansible supports only RedHat and CentOS. CoreOS is an os that perfectly suits a dockerized applications. In addition new ceph/daemon containers support etcd as an kvstore for configuration which is natively installed on CoreOS.

**Comment by leseb** [comment]
I don't think we don't anything specific to RedHat and/or CentOS for Docker.
My initial tests were on CoreOS so it should work, did you give it a try?
Yes, I'm planning on adding the support of etcd. In the meantime, I'd like to merge the docker branch in master.

**Comment by PiotrProkop** [comment]
I had problems with running docker branch on CoreOS and I wrote my own playbook for deploying ceph on CoreOS https://github.com/PiotrProkop/ceph-coreos-ansible. I would be happy to help you enable ceph-ansible on CoreOS.

**Comment by leseb** [comment]
That'd be great if you could:

* integrate ansible-coreos-bootstrap (the repo is not really moving and works well as is so we can simply import it.
* enabling an etcd scenario as well

You can do everything on the docker branch, it's fine, we will merge it into master later.
Thanks in advance.

**Comment by leseb** [comment]
Partially fixed in #622
@PiotrProkop are you still planning on proposing the kv support as well?

**Comment by PiotrProkop** [comment]
Yes i am working on it tommorow i will make first PR.
