### ISSUE TITLE
IOPS limits for pool don't work

### ISSUE THREAD

**Issue by kuhar2007** [ceph/ceph-ansible#6019]
**Bug Report**

What happened:

When we try limit iops usage for pool, it isn't work.
We setuped limit by command:
`rbd config pool set test rbd_qos_iops_burst 50`

Or tried iops usage by second:
`rbd config pool set test rbd_qos_iops_limit 50`

Ceph dashboard always show iops usage (R+W) more then 500. 

We tried limit for one image and have no results.
The system uses as much as it needs despite the established restrictions.
So how can we limit iops usage for pool?
Maybe we need to update ceph ?

PS Global configuration don't work too. System said that limited was installed, but nothing make.

**Environment**:
* OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

* Kernel (e.g. `uname -a`):
Linux ceph01 4.15.0-122-generic #124-Ubuntu SMP Thu Oct 15 13:03:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

* Ceph version (e.g. `ceph -v`):
ceph version 14.2.10 (b340acf629a010a74d90da5782a2c5fe0b54ac20) nautilus (stable)

**Comment by kuhar2007** [comment]
I think that can close issue, because limits don't implement change if image have writers now.
rbd_qos_iops_limit 50 - mean that each image in pool have limit 50 OPS/s for read and 50 OPS/s write, it isn't summary 50 IOPS/s for all pool and summary for each image as I thought before.
Maybe ceph have solution for limit IOPS usage for pool, not for each image in pool?

**Comment by dsavineau** [comment]
You should ask this on ceph mailing list or open an issue on the ceph tracker because that's not related to ceph-ansible.
