### ISSUE TITLE
rework purge playbook with ceph-disk commands

### ISSUE THREAD

**Issue by leseb** [ceph/ceph-ansible#604]
only for jewel: https://github.com/ceph/ceph/pull/5867

**Comment by snerdish** [comment]
As a note, the purge playbook also doesn't work with the osd directory scenario.

**Comment by leseb** [comment]
Implemented and part of this playbook now: https://github.com/ceph/ceph-ansible/blob/master/infrastructure-playbooks/shrink-osd.yml
