### ISSUE TITLE
add-mons.yml - Could not find or access '/opt/raw_install_python.yml'

### ISSUE THREAD

**Issue by jeevadotnet** [ceph/ceph-ansible#6049]
Command: `ansible-playbook -vv -e 'ansible_python_interpreter=/usr/bin/python3' -i /opt/ceph-ansible/inventory add-mon.yml` 

Error:
```
ERROR! Unable to retrieve file contents
Could not find or access '/opt/raw_install_python.yml' on the Ansible Controller.
If you are using a module and expect the file to exist on the remote, see the remote_src option
```

"Fix"
Change `add-mon.yml` import_task line:
`import_tasks: "{{ playbook_dir }}/../raw_install_python.yml"`

to
`import_tasks: "{{ playbook_dir }}/raw_install_python.yml"`

**Comment by dsavineau** [comment]
Where is located the add-mon.yml playbook on your host ?

It looks like you euther copied this playbook in the main directory or executed it from a different directory than the ceph-ansible rootdir.

**Comment by jeevadotnet** [comment]
Hi @dsavineau 

I copy my infrastructure runbooks to ../ (ceph-ansible root). Before @guits told me it is not the recommended method yesterday, I thought it was the correct way to use it.
