### ISSUE TITLE
[Feature request]RadosGW multi site replication + HAPROXY with Ansible deployment.

### ISSUE THREAD

**Issue by OrFriedmann** [ceph/ceph-ansible#605]
Hey,
Recently i've encoutered few companies with the same interest about adding a quiet valueable and a reasonable feature which me and the community aswell would be gladly to have in our Ceph inventory.
The feature is RadosGW multisite along with HAPROXY support towards the Playbooks deployment.

Thanks.

**Comment by leseb** [comment]
The only problem is that we will have a dependency with the HAProxy module. It is always really annoying to work with external playbooks. Perhaps I can add an example directory for the HAProxy config template.
I don't really have time for this at the moment, I'll pick up that task later.
Thanks!

**Comment by Chrislevi** [comment]
Is it still on the table? I would like to have that feature as well.

**Comment by leseb** [comment]
Hum yes and no, at some point it might be but I'll not integrate the HAProxy role in this repo.

**Comment by leseb** [comment]
I'm closing this since this should not be part of this repo.
