### ISSUE TITLE
dashboard: unable to list iscsi rbd images

### ISSUE THREAD

**Issue by solune** [ceph/ceph-ansible#6061]
**Bug Report**
Since I have configured iscsi , when I go to dashboard /block/rbd , It's very slow and I have the message :
(iscsi is the pool name for iscsi rbd)
Warning
--
Displaying previously cached data for pool iscsi.

Share your group_vars files, inventory and **full** ceph-ansibe log

**Environment**:
* OS (e.g. from /etc/os-release): centos 7 containerized
* Kernel (e.g. `uname -a`): 3.10.0-693.el7.x86_64 on manager node
* Docker version if applicable (e.g. `docker version`): 1.13.1
* Ansible version (e.g. `ansible-playbook --version`): 2.9.13
* ceph-ansible version (e.g. `git head or tag or stable branch`):stable-5.0
* Ceph version (e.g. `ceph -v`):15.2.3

iscsigws.yml:
```
# Dummy variable to avoid error because ansible does not recognize the
# file as a good configuration file when no variable in it.
dummy:

# You can override vars by using host or group vars

###########
# GENERAL #
###########
# Whether or not to generate secure certificate to iSCSI gateway nodes
#generate_crt: False

#iscsi_conf_overrides: {}
iscsi_pool_name: iscsi
iscsi_pool_size: 3

copy_admin_key: True
deploy_settings: True
```

**Comment by dsavineau** [comment]
I'm not sure to understand what's the issue.

Could you elaborate more ?

**Comment by solune** [comment]
![image](https://user-images.githubusercontent.com/6870794/100128836-11d89e80-2e81-11eb-9db8-7cc6914a651f.png)
Since I have configured iscsigws I have this warning message in dashboard

**Comment by dsavineau** [comment]
Did you use the iscsi pool for anything else that iSCSI ?

**Comment by solune** [comment]
no it's dedicated to iscsi
