### ISSUE TITLE
take-over-existing-cluster.yml fails if fetch_directory not set

### ISSUE THREAD

**Issue by scriptkiddy** [ceph/ceph-ansible#6072]
**Bug Report**

What happened: take-over-existing-cluster.yml fails because fetch_directory was not set

What you expected to happen: 
* fetch directory creates as per default and then used

How to reproduce it (minimal and precise):
* simply run take-over-existing-cluster.yml on any ceph-cluster without setting the fetch_directory variable

Problem: 
* in roles/ceph-fetch-keys/tasks/main.yml a fetch directory is first created via fetch_directory variable or by a default('fetch/') 
* afterwards in the same role only the variable is used

simple fix: use {{ fetch_directory | default('fetch/') }} instead of {{ fetch_directory }} everywhere or set the variable to it default if it isn't set already

I don't think there is any need for inventory, group_vars or log files here

**Environment**:
* OS ubuntu: 16.04
* Kernel:  4.4.0-186-generic #216-Ubuntu SMP Wed Jul 1 05:34:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Ansible version: ansible-playbook 2.9.15
* ceph-ansible version:  git head
* Ceph version: ceph version 10.2.11 (e4b061b47f07f583c92a050d9e84b1813a35671e) (I know embarrassing ...)

**Comment by guits** [comment]
@scriptkiddy to be honest, `take-over-existing-cluster.yml` isn't really maintained anymore, it didn't get engineering effort for a while now

> * ceph-ansible version:  git head
do you mean you are using ceph-ansible@master branch? The latest branch supporting `jewel` was `stable-3.0`

Neither `stable-3.1` nor ceph 10 is supported today, they are both EOL

**Comment by scriptkiddy** [comment]
Yes I just threw the master branch version against a virtual copy of a ceph I'm trying to save/uprade to a stable version.

I already saw that 3.0 ist last version to support jewel. I just thought I'de start with the latest version and work my way back if need be.

Is anyone still interested in fixes for the take-over-existing-cluster.yml playbook?

If not I'll just fix it for myself and won't bother you guys with pull requests and issues. If yes I'll submit the fixes myself ...

cheers Kalle

**Comment by guits** [comment]
@scriptkiddy PRs are always welcome. At the moment we just don't have the bandwidth to take care of this playbook.
That said, if you are interested in fixing it I'll be happy to review and merge a PR.
