### ISSUE TITLE
wait for all osd to be up task stuck on not healthy cluster

### ISSUE THREAD

**Issue by clwluvw** [ceph/ceph-ansible#6073]
**Bug Report**

What happened:
If there is an OSD that is down/destroyed because of failure and we are using ceph-ansible to add nodes `wait for all osd to be up` task will be stuck because `num_osds` won't equal to `num_up_osds` anytime!

What you expected to happen:
I think the task should only check the OSDs that is related to the target host by ansible.

How to reproduce it (minimal and precise):
1. Mark one OSD down
1. Try to add a new node to your cluster

**Comment by guits** [comment]
why would you want to add a node with an OSD marked down? can't you fix this before adding your new node?
I would say most of the time, a day 2 operation requires your cluster is in a good state.

**Comment by clwluvw** [comment]
@guits I think it has lots of scenarios for this situation, the ones I get into was I wanted to add new nodes to my SSD tier in an urgent but a minutes before one of my disks from HDD tier fails and I can't replace/recover the disk too fast!

**Comment by guits** [comment]
@clwluvw we (@dsavineau and I) had a discussion, he has a good point:

since your HDD disk is failed anyway, why don't you remove it completely before adding your new nodes?

The proposed patch would prevent from doing multiple operations in one single run if you want to add new nodes + adding a new crush rule for instance.

**Comment by clwluvw** [comment]
@guits @dsavineau I don't think making decisions for clients is good behavior here, I mean we can't preserve the client situation that for example, the client should replace the failed disk first and then add its new node! Maybe the client doesn't have extra disks and should buy a new one and it takes time (the new node disks are SSD it can't be replaced with HDD tier disks!) or the disks aren't hot-swappable and the client can't replace it in a meantime.
I was in urgent to add a new node to my SSD tier and there was no time to replace my failed disk! Also having multiple operations in two different tiers isn't very strange!
Also, I mention here again that it can have **too many other scenarios** that this task stuck the operations and I think the correct behavior for this task is to check only the OSDs in the target host!

**Comment by guits** [comment]
@clwluvw that wouldn't require that you replace the failed disk by a new one.
It just requires that you remove it "logically" from the cluster, not "physically".
You can then add your new nodes this way.

> Also, I mention here again that it can have **too many other scenarios** that this task stuck the operations and I think the correct behavior for this task is to check only the OSDs in the target host!

That's incorrect, this task has to be run against *all* osd nodes, see original commit [1]

[1] 9d5265fe11fb5c1d0058525e8508aba80a396a6b

**Comment by clwluvw** [comment]
@guits What do you mean about "logically"? If you mean to remove it from the crush map I mentioned it here:
> I don't want to remove it from the crush map because I just want to replace the disk and make it in again and removing it completely from the crush map will cause too many misplaced in the cluster and is unnecessary because I can replace my disk without removing and adding it again to the crush map!

The commit you have mentioned is for creating pools and this is done in the ceph-client role I think and pools aren't created in the ceph-osd role. If I'm wrong please correct me.
I found this [commit](https://github.com/ceph/ceph-ansible/commit/9fa5b296ca60edebfe7784acc948d44a0e781547) that explains it needed for creating crush rules and I think checking crush rules before this and check if it needed to be created can prevent this issue because adding a new node won't create crush rule.

**Comment by guits** [comment]
@clwluvw what about using `noout`flag ?

**Comment by guits** [comment]
> The commit you have mentioned is for creating pools and this is done in the ceph-client role I think and pools aren't created in the ceph-osd role. If I'm wrong please correct me.

openstack pools are created in the ceph-osd role

**Comment by dsavineau** [comment]
> > The commit you have mentioned is for creating pools and this is done in the ceph-client role I think and pools aren't created in the ceph-osd role. If I'm wrong please correct me.
> 
> openstack pools are created in the ceph-osd role

https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-osd/tasks/openstack_config.yml#L2-L22

**Comment by clwluvw** [comment]
> @clwluvw what about using `noout`flag ?

Cluster gets unhealthy until the disk replaced and it's not good because if one disk gets segfault for any reason In that time it can't get in and it's full of risk!

**Comment by clwluvw** [comment]
> > The commit you have mentioned is for creating pools and this is done in the ceph-client role I think and pools aren't created in the ceph-osd role. If I'm wrong please correct me.
> 
> openstack pools are created in the ceph-osd role

@guits Again same as this can prevent from this issue I think
>  I think checking crush rules before this and check if it needed to be created can prevent this issue because adding a new node won't create crush rule.
