### ISSUE TITLE
Could not find current folder in /var/lib/ceph/osd/ceph-1

### ISSUE THREAD

**Issue by hundredwz** [ceph/ceph-ansible#6080]
**Bug Report**

What happened:
I could not find the current folder in ceph directory

What you expected to happen:
 I wish to find it and try to test the stability of ceph

How to reproduce it (minimal and precise):

I use rados put one file and I can get the file. But I could not find the "current" folder.
I don't know if it's the version difference or I install ceph failed

Share your group_vars files, inventory and **full** ceph-ansibe log

This is the content in all.yml in group_vars folder
```
ceph_origin: repository
ceph_repository: community
ceph_stable_release: luminous
ceph_mirror: http://mirrors.aliyun.com/ceph
ceph_stable_key: http://mirrors.aliyun.com/ceph/keys/release.asc
ceph_stable_repo: "{{ ceph_mirror }}/rpm-{{ ceph_stable_release }}"
public_network: "192.168.0.0/24"
cluster_network: "192.168.0.0/24"
monitor_interface: eth0
devices:
  - '/dev/vdb'
osd_scenario: collocated
cephfs: cephfs
cephfs_data: cephfs_data
cephfs_metadata: cephfs_metadata

cephfs_pools:
  - { name: "{{ cephfs_data }}", pgs: "{{ osd_pool_default_pg_num }}", size: "{{ osd_pool_default_size }}" }
  - { name: "{{ cephfs_metadata }}", pgs: "{{ osd_pool_default_pg_num }}", size: "{{ osd_pool_default_size }}" }
```

And this is the hosts information
```
[mons]
192.168.0.101
192.168.0.102
192.168.0.103
[mgrs]
192.168.0.101
[mdss]
192.168.0.101
[osds]
192.168.0.101
192.168.0.102
192.168.0.103
```

I am sorry that I couldn't find full deploy log.

And this is the content in /etc/ceph/ceph.conf
```
# Please do not change this file directly since it is managed by Ansible and will be overwritten

[global]
fsid = a2f28533-7713-4d59-a18f-05b4855e4675



mon initial members = host1,host2,host3
osd pool default crush rule = -1

mon host = 192.168.0.101,192.168.0.102,192.168.0.103

public network = 192.168.0.0/24
cluster network = 192.168.0.0/24


[osd]
osd memory target = 8818314444
```

**Environment**:
* OS (e.g. from /etc/os-release):
CentOS Linux release 7.6.1810 (Core)
* Kernel (e.g. `uname -a`):
Linux hosts 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Docker version if applicable (e.g. `docker version`):
* Ansible version (e.g. `ansible-playbook --version`):
ansible-playbook 2.7.4
* ceph-ansible version (e.g. `git head or tag or stable branch`):
stable-3.2
* Ceph version (e.g. `ceph -v`):
ceph version 12.2.13 (584a20eb0237c657dc0567da126be145106aa47e) luminous (stable)

**Comment by dsavineau** [comment]
> Share your group_vars files, inventory and full ceph-ansibe log

Please share the required information

**Comment by hundredwz** [comment]
I update the information and I wonder how could i find the path that I store files. @dsavineau 
Most articles says that the file is in /var/lib/ceph/osd/ceph-X/current, but I couldn't find this folder.
Thank you.

**Comment by dsavineau** [comment]
> Most articles says that the file is in /var/lib/ceph/osd/ceph-X/current, but I couldn't find this folder.

If you put a file in a pool via the rados command then you won't see the file on disk in /var/lib/ceph/osd/ceph-X/

Looking at your configuration, you should have a cluster with 3 OSDs (0, 1, 2). The /var/lib/ceph/osd/ceph-{0,1,2} directories (0 could be on .101, 1 on .102, and 2 on .103, it's totally random) only contain the bluestore metadata.
The data are stored on a raw devices so you can't see the files (ie: there's no filesystem on the data device)

Your /dev/vdb device should have 2 partitions
  - /dev/vdb1 which is the bluestore metadata partition (the one mounted in /var/lib/ceph/osd/ceph-{0,1,2})
  - /dev/vdb2 which is the bluestore data partition (you should be able to see the symlink to this partition in /var/lib/ceph/osd/ceph-{0,1,2}/block)
