### ISSUE TITLE
[ceph-dashboard : add iscsi gateways - ipv4 fails when `api_secure: true` due to ip being used instead of fqdn

### ISSUE THREAD

**Issue by Venator-Fox** [ceph/ceph-ansible#6137]
**Bug Report**

What happened: `TASK [ceph-dashboard : add iscsi gateways - ipv4 fails` when `api_secure: true` due to the task running `podman exec <someHost> ceph --cluster ceph dashboard iscsi-gateway-add https://<ip>` instead of `https://<fqdn>`. I probably am not understanding the task correctly, but expecting the IP to be in the subject alternative names in the certificate seems a bit strange? A PR is submitted here to change it to use the fqdn from ip, which allowed the play to run successfully in my environment but I'm not sure if it will break other things (or if I'm configuring incorrectly in the first place).

I'm not sure if #5165 is related

What you expected to happen: The task to complete successfully

How to reproduce it (minimal and precise):

Set `api_secure: true`, add tls certificates, and add hosts to `[iscsigws]` in inventory

Share your group_vars files, inventory and **full** ceph-ansible log
~~~
TASK [ceph-dashboard : add iscsi gateways - ipv4] **********************************************************************Monday 14 December 2020  12:20:42 -0700 (0:00:00.128)       0:42:37.637 *******
failed: [redacted-ceph-node-000 -> redacted-ceph-node-000] (item=redacted-ceph-node-000) => changed=false
  ansible_loop_var: item
  cmd:
  - podman
  - exec
  - ceph-mon-redacted-ceph-node-000
  - ceph
  - --cluster
  - ceph
  - dashboard
  - iscsi-gateway-add
  - https://admin:<redacted>@10.224.71.11:5000
  delta: '0:00:01.093222'
  end: '2020-12-14 12:20:44.063241'
  item: redacted-ceph-node-000
  msg: non-zero return code
  rc: 22
  start: '2020-12-14 12:20:42.970019'
  stderr: |-
    Error EINVAL: Traceback (most recent call last):
      File "/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
        chunked=chunked)
      File "/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
        self._validate_conn(conn)
      File "/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
        conn.connect()
      File "/lib/python3.6/site-packages/urllib3/connection.py", line 364, in connect
        _match_hostname(cert, self.assert_hostname or server_hostname)
      File "/lib/python3.6/site-packages/urllib3/connection.py", line 374, in _match_hostname
        match_hostname(cert, asserted_hostname)
      File "/lib64/python3.6/ssl.py", line 287, in match_hostname
        % (hostname, ', '.join(map(repr, dnsnames))))
    ssl.CertificateError: hostname '10.224.71.11' doesn't match either of', ':sredacted-ceph-node-000.int.colorado.edu', 'bunch.of.alt.names.etc'...
  
    During handling of the above exception, another exception occurred:
  
    Traceback (most recent call last):
      File "/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
        timeout=timeout
      File "/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
        _stacktrace=sys.exc_info()[2])
      File "/lib/python3.6/site-packages/urllib3/util/retry.py", line 399, in increment
        raise MaxRetryError(_pool, url, error or ResponseError(cause))
    urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='10.224.71.11', port=5000): Max retries exceeded with url: /api/sysinfo/hostname (Caused by SSLError(CertificateError("hostname '10.224.71.11' doesn't match either of 'redacted-ceph-node-000.int.colorado.edu', 'bunch.of.alt.names.etc' ),))

    During handling of the above exception, another exception occurred:
      
    Traceback (most recent call last):
      File "/usr/share/ceph/mgr/dashboard/rest_client.py", line 392, in do_request
        url, headers=request_headers, params=params, auth=self.auth)
      File "/lib/python3.6/site-packages/requests/sessions.py", line 546, in get
        return self.request('GET', url, **kwargs)
      File "/usr/share/ceph/mgr/dashboard/rest_client.py", line 47, in request
        return super(TimeoutRequestsSession, self).request(*args, **kwargs)
      File "/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
        resp = self.send(prep, **send_kwargs)
      File "/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
        r = adapter.send(request, **kwargs)
      File "/lib/python3.6/site-packages/requests/adapters.py", line 514, in send
        raise SSLError(e, request=request)
~~~

**Environment (All nodes are the same)**:
* OS (e.g. from /etc/os-release): `Red Hat Enterprise Linux 8.3`
* Kernel (e.g. `uname -a`): `4.18.0-240.1.1.el8_3.x86_64`
* Docker version if applicable (e.g. `docker version`): `podman version 2.0.5`
* Ansible version (e.g. `ansible-playbook --version`): `ansible-playbook 2.9.15`
* ceph-ansible version (e.g. `git head or tag or stable branch`): `tag/v5.0.3`
* Ceph version (e.g. `ceph -v`): `ceph version 15.2.6 (cb8c61a60551b72614257d632a574d420064c17a) octopus (stable)`

**Comment by dsavineau** [comment]
I think you're partially true because we don't cover the scenario where an user is providing its own TLS certificate/key instead of using the self generated one (via `generate_crt` variable).

When the TLS certificate/key are generated by ceph-ansible then the TLS verification when adding the iscsi gateway with `https` is disable [1].

So we probably a way to:
  - use the real CN from the certificate when provided instead of the IP address
  - be able to disable the TLS verification when providing the TLS certificate/key as self signed certificate. 

[1] https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-dashboard/tasks/configure_dashboard.yml#L260-L266

**Comment by Venator-Fox** [comment]
Ah I see, so based on that if I made the following changes instead, would that work?
- Revert back to IP for `add iscsi gateways - ipv4` and `add iscsi gateways - ipv6
- Add a conditional that checks if `api_secure` is false
  - If false use the IP as is, else use `ansible_fqdn`

But I guess that may not always cover all basis since you mentioned `ansible_fqdn` may not always be configured with an IP address. So in this case would I need to add another check for that somehow? (Am still thinking how I would validate it is an fqdn that is resolvable)

If I grab the real CN from the certificate, I would still need to somehow check if it's resolvable, correct? And if it is resolvable, then use `ansible_fqdn` instead of ip.
