### ISSUE TITLE
module is missing interpreter line in roles/ceph-common/tasks/main.yml

### ISSUE THREAD

**Issue by snerdish** [ceph/ceph-ansible#615]
I'm encountering the following - I've patched the ansible error message to show the offending module.

ASK: [ceph.ceph-common | generate ceph configuration file] *******************
<storage03.qux.foo01.foobar> REMOTE_MODULE config_template owner=ceph mode=0644 config_type=ini dest=/etc/ceph/ceph.conf group=ceph src=ceph.conf.j2
<storage01.qux.foo01.foobar> REMOTE_MODULE config_template owner=ceph mode=0644 config_type=ini dest=/etc/ceph/ceph.conf group=ceph src=ceph.conf.j2
<storage02.qux.bar01.foobar> REMOTE_MODULE config_template owner=ceph mode=0644 config_type=ini dest=/etc/ceph/ceph.conf group=ceph src=ceph.conf.j2
fatal: [storage03.qux.foo01.foobar] => module is missing interpreter line - config_template
fatal: [storage01.qux.foo01.foobar] => module is missing interpreter line - config_template
fatal: [storage02.qux.bar01.foobar] => module is missing interpreter line - config_template

**Comment by leseb** [comment]
You need to edit the plugin action path in your ansible config. Just look at the ansible.cfg in the repo as an example.

**Comment by snerdish** [comment]
Woops, thanks!
