### ISSUE TITLE
Minor bug in ceph_volume.py

### ISSUE THREAD

**Issue by trickert76** [ceph/ceph-ansible#6153]
Please have a look at library/ceph_volume.py in the module definition is:

    containerized=dict(type='str', required=False, default=False)

This generates a warning on the console, because the string parameter `containerized` will be initialized with a boolean `False`.

In other modules it is correct:

    containerized=dict(type='str', required=False, default=None)

**Comment by dsavineau** [comment]
In fact, this parameter isn't used anymore so we can remove it.
