### ISSUE TITLE
Return stdout as json

### ISSUE THREAD

**Issue by trickert76** [ceph/ceph-ansible#6155]
**Is your feature request related to a problem? Please describe.**

If you want to use registered response of a module (f.e. roles/ceph-osd/tasks/start_osds.yml:42), then you always use `registered_var.stdout | from_json`... This is ugly. Because the output of the module itself can be already be parsed inside the module.

**Describe the solution you'd like**

An easy example is in ceph_volume.py. Change the result dict to

    if out and len(out) > 0:
        out_json = json.loads(out)

    result = dict(
        cmd=cmd,
        start=str(startd),
        end=str(endd),
        delta=str(delta),
        rc=rc,
        json=out_json,
        stdout=out.rstrip('\r\n'),
        stderr=err.rstrip('\r\n'),
        changed=changed,
    )

Of course it would be better if any action will manage that itself. Maybe there aren't always JSON responses from a CLI command.

**Comment by dsavineau** [comment]
There's only two actions from the ceph-volume module that returns a json output (inventory and list), the others don't.
