### ISSUE TITLE
Add more disks to the running cluster  ( just a question, not a bug ) 

### ISSUE THREAD

**Issue by grharry** [ceph/ceph-ansible#6158]
Hello all, 
Just a question to make sure  I won't destroy something. 

ansible-ceph 3.0 was used to create the ceph cluster
ansible 2.8.6
ubuntu/xenial running luminous 

group_vars/osds.yml  is updated with the newly added disks 

In order to add the new disks to the running cluster, meaning while the cluster is running normally. 

a) Do I replay the site.yml file  with the --limit [ osd-host_NUMBER ] option  per each host ?? 
b) or run the infrastructure-playbooks/osd-configure.yml  ?? 
c) Something else ?? 

Thanks in advance for your answers! 
Regards

**Comment by guits** [comment]
@grharry you can rerun the main playbook in order to add new disks
However, I'm unsure using `--limit` on stable-3.0 works well, this release is quite old now and not maintained anymore, I would advise you to upgrade your ceph-ansible version to `stable-3.2`
