### ISSUE TITLE
ansible playbook failed at lvm batch

### ISSUE THREAD

**Issue by dbenduga** [ceph/ceph-ansible#6164]
I am trying to install ceph version 14.2.16 and ansible playbook failed at lvm batch

TASK [ceph-config : set_fact num_osds from the output of 'ceph-volume lvm batch --report'] ******************************************************************
Thursday 24 December 2020  13:08:25 +0000 (0:00:02.396)       0:05:55.122 *****
fatal: [pr1cephnp1osd01]: FAILED! =>
  msg: |-
    The conditional check '(lvm_batch_report.stdout | from_json).changed' failed. The error was: error while evaluating conditional ((lvm_batch_report.stdout | from_json).changed): 'list object' has no attribute 'changed'

    The error appears to be in '/home/onbmc.com/dbenduga/ceph/ceph-ansible/roles/ceph-config/tasks/main.yml': line 36, column 5, but may
    be elsewhere in the file depending on the exact syntax problem.

    The offending line appears to be:

      - name: set_fact num_osds from the output of 'ceph-volume lvm batch --report'
        ^ here
fatal: [pr1cephnp1osd02]: FAILED! =>
  msg: |-
    The conditional check '(lvm_batch_report.stdout | from_json).changed' failed. The error was: error while evaluating conditional ((lvm_batch_report.stdout | from_json).changed): 'list object' has no attribute 'changed'

    The error appears to be in '/home/onbmc.com/dbenduga/ceph/ceph-ansible/roles/ceph-config/tasks/main.yml': line 36, column 5, but may
    be elsewhere in the file depending on the exact syntax problem.

    The offending line appears to be:

      - name: set_fact num_osds from the output of 'ceph-volume lvm batch --report'
        ^ here
fatal: [pr1cephnp1osd03]: FAILED! =>
  msg: |-
    The conditional check '(lvm_batch_report.stdout | from_json).changed' failed. The error was: error while evaluating conditional ((lvm_batch_report.stdout | from_json).changed): 'list object' has no attribute 'changed'

    The error appears to be in '/home/onbmc.com/dbenduga/ceph/ceph-ansible/roles/ceph-config/tasks/main.yml': line 36, column 5, but may
    be elsewhere in the file depending on the exact syntax problem.

    The offending line appears to be:

      - name: set_fact num_osds from the output of 'ceph-volume lvm batch --report'
        ^ here

**Comment by dsavineau** [comment]
What ceph-ansible version are you using ?

Assuming you're using the stable-4.0 branch on any tag present on that branch because you're deploying nautilus then you might have hit https://github.com/ceph/ceph-ansible/pull/6144

This has been fixed on the stable-4.0 branch and part of the v4.0.42 release.

Could you give it a try ?
