### ISSUE TITLE
Error when installing : TASK [ceph-dashboard : create dashboard admin user] stderr: 'Error ENOENT: User ''admin'' does not exist'

### ISSUE THREAD

**Issue by BojungKim** [ceph/ceph-ansible#6197]
**Bug Report**

What happened:
ceph-ansible fatal failed. TASK [ceph-dashboard : create dashboard admin user] stderr: 'Error ENOENT: User ''admin'' does not exist'.

What you expected to happen:
Creating admin does not working. 

How to reproduce it (minimal and precise):

Share your group_vars files, inventory and **full** ceph-ansibe log

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 18.04
* Kernel (e.g. `uname -a`):  4.15.0-128-generic
* Docker version if applicable (e.g. `docker version`): No use
* Ansible version (e.g. `ansible-playbook --version`): ansible-playbook 2.9.16
* ceph-ansible version (e.g. `git head or tag or stable branch`):
I don't know git well. Just latest commit id : 13427eddac03f9f62e98f6689948e98e7baeef29

* Ceph version (e.g. `ceph -v`): ceph version 15.2.8 (bdf3eebcd22d7d0b3dd4d5501bee5bac354d5b55) octopus (stable)

### hosts (file)
[mgrs]
ceph-mon01 ansible_host=10.254.3.91
ceph-mon02 ansible_host=10.254.3.92
ceph-mon03 ansible_host=10.254.3.93

[rgws]
ceph-mon01 ansible_host=10.254.3.91
ceph-mon02 ansible_host=10.254.3.92
ceph-mon03 ansible_host=10.254.3.93

[osds]
ceph-osd01 ansible_host=10.254.3.94
ceph-osd02 ansible_host=10.254.3.95
ceph-osd03 ansible_host=10.254.3.96

[mons]
ceph-mon01 ansible_host=10.254.3.91
ceph-mon02 ansible_host=10.254.3.92
ceph-mon03 ansible_host=10.254.3.93

[mdss]
ceph-mon01 ansible_host=10.254.3.91
ceph-mon02 ansible_host=10.254.3.92
ceph-mon03 ansible_host=10.254.3.93

[rgwloadbalancers]
ceph-mon01 ansible_host=10.254.3.91
ceph-mon02 ansible_host=10.254.3.92
ceph-mon03 ansible_host=10.254.3.93

[monitoring]
ceph-mon01 ansible_host=10.254.3.91
ceph-mon02 ansible_host=10.254.3.92
ceph-mon03 ansible_host=10.254.3.93

[clients]
ceph-mon01 ansible_host=10.254.3.91
ceph-mon02 ansible_host=10.254.3.92
ceph-mon03 ansible_host=10.254.3.93

### group_vars/all.yml (file)
ceph_release_num:
octopus: 15
cluster: ceph
mon_group_name: mons
osd_group_name: osds
rgw_group_name: rgws
client_group_name: clients
mgr_group_name: mgrs
rgloadbalancer_group_name: rgwloadbalancers
monitoring-server_group_name: monitoring
configure_firewall: True
ntp_service_enabled: true
ntp_daemon_type: chronyd
ceph_repository_type: cdn
ceph_origin: repository
ceph_repository: community
ceph_stable_release: octopus
monitor_interface: eth1
public_network: 10.254.3.0/24
cluster_network: 10.254.2.0/24
radosgw_civetweb_port: 8080
radosgw_interface: eth1
dashboard_enabled: True
dashboard_protocol: http
dashboard_port: 8443
dashboard_admin_user: admin
dashboard_admin_password: P@ssw0rd
dashboard_frontend_vip: 10.254.3.90
grafana_admin_user: admin
grafana_admin_password: P@ssw0rd
containerized_deployment: False

copy_admin_key: True
devices:
  - /dev/vdb
    #- /dev/vdc

haproxy_frontend_port: 8081
virtual_ips:
   - 10.254.3.90
virtual_ip_netmask: 24
virtual_ip_interface: eth1

### ansible-playbook -i hosts site.yml

**Comment by dsavineau** [comment]
Please use the stable-5.0 branch for deploying Octopus

https://docs.ceph.com/projects/ceph-ansible/en/latest/#releases

**Comment by BojungKim** [comment]
> Please use the stable-5.0 branch for deploying Octopus
> 
> https://docs.ceph.com/projects/ceph-ansible/en/latest/#releases

Thanks for your reply.
But

**Comment by keuko** [comment]
this is causing weak password, please, add a warning for user !

**Comment by dsavineau** [comment]
> this is causing weak password, please, add a warning for user !

@keuko Could you give more details or at best open a dedicated issue if needed ?

**Comment by keuko** [comment]
@dsavineau  here it is -> https://blog.loudgefly.it/2020/11/debugging-ansible-modules/ << i've solved after i've read that article :)

**Comment by dsavineau** [comment]
@keudo thanks for the link, it was very useful to understand the issue.

So bad that the issue wasn't raised earlier with clear explanation.

I've sent a PR for this.
