### ISSUE TITLE
Support installing from local mirrors

### ISSUE THREAD

**Issue by bdastur** [ceph/ceph-ansible#620]
For internal private clouds that do not have access to upstream repositories and which maintain a local mirror of packages, there should be a way to allow specifying private mirrors.

**Comment by leseb** [comment]
Can you give me a concrete example?
Something like building a local ceph repo file?

**Comment by bdastur** [comment]
Yes. So we have a local mirror for all the packages that we need. 
Our environment is centos, and for that we create /etc/yum.repos.d/ceph_deploy.repo, and /etc/yum.repos.d/ceph.repo, which points to your mirrors. We cannot access any external repositories from our environment.

eg:
[ceph-deploy]
baseurl=http://mirror.env2.acme.net/mrepo/centos$releasever-$basearch/RPMS.ceph_hammer_noarch
enabled=1
gpgcheck=0
name=CentOS -ceph packages
priority=1

**Comment by bdastur** [comment]
Also, I could not figure out if this is something that is already supported, so I have a patch for this which I have made changes to my local fork.

I have added a new varibale in group_vars/all called "ceph_local_mirror: true", and repo file list, and a new file called custom_install_on_centos.yaml, to generate the repo files, if it is ok, I would like to submit for review

**Comment by andrewschoen** [comment]
@bdastur does setting ``ceph_origin`` to ``distro`` not work for you?

I've not tested on centos, but that should just use the repos present on the system and not attempt to download the upstream repos.

**Comment by bdastur** [comment]
yes, but I still need to create these .repo files and place them on the host. It would be good if it was done as part of the same automation.

**Comment by leseb** [comment]
@andrewschoen is right `ceph_origin: distro` should be sufficient. I believe this feature goes beyond ceph-ansible scope... I'm not strongly against it but I think the repo creation (when it's not something related to ceph), I just think this should be part of your infrastructure playbook.
@bdastur If you want to submit a PR then I'll have a look at it.

**Comment by bdastur** [comment]
Thanks @andrewschoen , @leseb. Looking at it again, yes, the repo creation does not need to be part of the ceph roles. I have a patch, with a sample site.yaml with the additional step to generate the repo files.
Is the procedure to submit the PR same as mentioned in the README? I have the patch ready for submission, but get a permission error:

ERROR: Permission to ceph/ceph-ansible.git denied to bdastur.
fatal: Could not read from remote repository.

**Comment by bdastur** [comment]
https://github.com/ceph/ceph-ansible/pull/623
