### ISSUE TITLE
unwanted pacific upgrade

### ISSUE THREAD

**Issue by solune** [ceph/ceph-ansible#6250]
**Bug Report**

What happened:
My three monitors not start with this error: 
Feb  8 12:29:20 cephir1n4 docker: debug 2021-02-08T12:29:20.049+0100 7fe8864e3700 -1 ERROR: on disk data includes unsupported features: compat={},rocompat={},incompat={13=pacific ondisk layout}

What you expected to happen:

How to reproduce it (minimal and precise):
I just run ansible-playbook -vv site.yml -i hosts to add osd. My cluster  health was ok in octopus version.

now  my osds are in pacific version
ceph version 16.1.0-100-g74275226 (74275226ac79999bfd40e683dc9a1309e76033bf) pacific (rc)
docker.io/ceph/daemon:latest

and my mons are stil in octopus
docker.io/ceph/daemon:latest-octopus

stable 5 branch isn't associated to octopus version ?

**Environment**:
* OS (e.g. from /etc/os-release): centos 7
* Kernel (e.g. `uname -a`): 3.10.0-693.el7
* Docker version if applicable (e.g. `docker version`): 1.13.1
* Ansible version (e.g. `ansible-playbook --version`): 2.9.13
* ceph-ansible version (e.g. `git head or tag or stable branch`): stable 5.0
* Ceph version (e.g. `ceph -v`): 15.2.8

**Comment by solune** [comment]
I just saw that you have changed the ceph_docker_image_tag from latest to latest-octopus , it's very dangerous ! 
I suppose I can't downgrade osd to latest-octopus ?

**Comment by guits** [comment]
> stable 5 branch isn't associated to octopus version ?

yes it is

**Comment by guits** [comment]
`latest` refers to the latest stable release, it is expected to be updated at some point.

see: https://github.com/ceph/ceph-ansible/blob/master/docs/source/installation/containerized.rst#custom-container-image

from the documentation :

> ceph_docker_image_tag should be set to a fixed tag, not to any "latest" tags unless you know what you are doing.

**Comment by guits** [comment]
> I just saw that you have changed the ceph_docker_image_tag from latest to latest-octopus , it's very dangerous !
> I suppose I can't downgrade osd to latest-octopus ?

IMO, what would have been dangerous would have been to keep `latest` instead of `latest-octopus`. The intent of this change was especially for avoiding this kind of issue.
