### ISSUE TITLE
Fail to use ceph-volume lvm batch to create bluestore osds

### ISSUE THREAD

**Issue by ephracis** [ceph/ceph-ansible#6251]
**Bug Report**

What happened:

```
TASK [ceph-osd : use ceph-volume lvm batch to create bluestore osds] ***************************************************************************************************************************************
Tuesday 09 February 2021  10:05:59 +0100 (0:00:00.105)       0:07:33.353 ******
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: list indices must be integers or slices, not str
fatal: [osd2.ceph.chre.basalt.se]: FAILED! => {
    "changed": false,
    "rc": 1
}

MSG:

MODULE FAILURE
See stdout/stderr for the exact error


MODULE_STDOUT:

Traceback (most recent call last):
  File "/home/centos/.ansible/tmp/ansible-tmp-1612861559.2638772-27198-133299779535338/AnsiballZ_ceph_volume.py", line 102, in <module>
    _ansiballz_main()
  File "/home/centos/.ansible/tmp/ansible-tmp-1612861559.2638772-27198-133299779535338/AnsiballZ_ceph_volume.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/centos/.ansible/tmp/ansible-tmp-1612861559.2638772-27198-133299779535338/AnsiballZ_ceph_volume.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.ceph_volume', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_ceph_volume_payload_c8rn9u6m/ansible_ceph_volume_payload.zip/ansible/modules/ceph_volume.py", line 706, in <module>
  File "/tmp/ansible_ceph_volume_payload_c8rn9u6m/ansible_ceph_volume_payload.zip/ansible/modules/ceph_volume.py", line 702, in main
  File "/tmp/ansible_ceph_volume_payload_c8rn9u6m/ansible_ceph_volume_payload.zip/ansible/modules/ceph_volume.py", line 669, in run_module
TypeError: list indices must be integers or slices, not str
```

What you expected to happen:

- Task succeeds

How to reproduce it (minimal and precise):

Group vars:

```
ceph_origin: repository
ceph_repository: community

public_network: "192.168.0.0/24"
cluster_network: "192.168.0.0/24"

containerized_deployment: True

monitor_interface: eth0
radosgw_interface: eth0

dashboard_admin_password: changeme
grafana_admin_password: changeme

devices:
 - /dev/vdb
```

It seems that the result is a list and not a dict, I tried to run the command manually:

```
[centos@osd1 ~]$ sudo podman run --rm --privileged --net=host --ipc=host --ulimit nofile=1024:4096 -v /run/lock/lvm:/run/lock/lvm:z -v /var/run/udev/:/var/run/udev/:z -v /dev:/dev -v /etc/ceph:/etc/ceph:z -v /run/lvm/:/run/lvm/ -v /var/lib/ceph/:/var/lib/ceph/:z -v /var/log/ceph/:/var/log/ceph/:z --entrypoint=ceph-volume docker.io/ceph/daemon:latest-nautilus --cluster ceph lvm batch --bluestore --yes --prepare /dev/vdb --report --format=json
[{"encryption": "None", "data": "/dev/vdb", "data_size": "50.00 GB"}]
--> DEPRECATION NOTICE
--> You are using the legacy automatic disk sorting behavior
--> The Pacific release will change the default to --no-auto
--> passed data devices: 1 physical, 0 LVM
--> relative data size: 1.0
```

Seems related to https://github.com/ceph/ceph-ansible/issues/6164.

**Environment**:
* OS (e.g. from /etc/os-release): CentOS 8.3
* Kernel (e.g. `uname -a`): Linux osd1.ceph.chre.basalt.se 4.18.0-240.1.1.el8_3.x86_64 #1 SMP Thu Nov 19 17:20:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Docker version if applicable (e.g. `docker version`):  Podman 2.0.5
* Ansible version (e.g. `ansible-playbook --version`): 2.9.15
* ceph-ansible version (e.g. `git head or tag or stable branch`): 4.0.45
* Ceph version (e.g. `ceph -v`): ceph version 14.2.16 (762032d6f509d5e7ee7dc008d80fe9c87086603c) nautilus (stable)

**Comment by guits** [comment]
@ephracis I believe this is a ceph-volume bug that has already been fixed.
Are you still seeing this issue?

**Comment by ephracis** [comment]
No, I am still stuck on 4.0.12 but I will try to update to latest and see if it works without issues this time. Hopefully I can find some time this week to do it and report back here.

**Comment by guits** [comment]
> No, I am still stuck on 4.0.12 

4.0.12? what does it correspond to?

**Comment by ephracis** [comment]
I mean [4.0.12 of Ceph Ansible](https://github.com/ceph/ceph-ansible/tree/v4.0.12) and the [4.0.12 tag of the daemon container](https://hub.docker.com/layers/ceph/daemon/v4.0.12-stable-4.0-nautilus-centos-7-x86_64/images/sha256-3cea45e68320ec76d60e55887e4a406cc0501a8582d8839bc6eeb4a304a52ee2?context=explore).

I'm not sure what the version of `ceph-volume` is inside the container since it doesn't have a `--version` flag.

**Comment by guits** [comment]
@ephracis in the initial report you mentioned ceph-ansible v4.0.45, I'm a bit confused

> * ceph-ansible version (e.g. `git head or tag or stable branch`): 4.0.45

**Comment by ephracis** [comment]
Yes, that's the version I was trying out but where i ran into the issue. So I had to stay on my current version: 4.0.12.

**Comment by ephracis** [comment]
Sorry, I realised now that of course my current version will not have the bug. That's why it works. How silly of me.

Well, I guess I need to try the upgrade again, but to a later 4.x version, to see if the problem has been solved.

I am a little tempted to upgrade to 5.x and get Octopus too, as long as I'm at it. Do you want me to try for the latest 4.x first and see if the bug has been solved there?

**Comment by ephracis** [comment]
Ok, I can now confirm that both 4.0.50 and 5.0.5 works for me without issues. Closing this.
