### ISSUE TITLE
grafana_server not being installed.

### ISSUE THREAD

**Issue by lphabc** [ceph/ceph-ansible#6285]
**Bug Report**

What happened: Running cockpit ceph installer and it said everything was good, but the grafana server was not installed

What you expected to happen: The grafana server installed with dashboards etc.

How to reproduce it (minimal and precise):
Rerun ansible-playbook

Share your group_vars files, inventory and **full** ceph-ansibe log
[all.yml.txt](https://github.com/ceph/ceph-ansible/files/5976722/all.yml.txt)
[dashboards.yml.txt](https://github.com/ceph/ceph-ansible/files/5976723/dashboards.yml.txt)
[mgrs.yml.txt](https://github.com/ceph/ceph-ansible/files/5976724/mgrs.yml.txt)
[mons.yml.txt](https://github.com/ceph/ceph-ansible/files/5976725/mons.yml.txt)
[osds.yml.txt](https://github.com/ceph/ceph-ansible/files/5976726/osds.yml.txt)

**Environment**:
* OS (e.g. from /etc/os-release): Centos 7
[hosts.txt](https://github.com/ceph/ceph-ansible/files/5976719/hosts.txt)

* Kernel (e.g. `uname -a`): Linux star1 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* Docker version if applicable (e.g. `docker version`):
* Ansible version (e.g. `ansible-playbook --version`): ansible-playbook 2.9.16
* ceph-ansible version (e.g. `git head or tag or stable branch`): ceph-ansible-4.0.41-1.el7.noarch
* Ceph version (e.g. `ceph -v`): ceph version 14.

2.16 (762032d6f509d5e7ee7dc008d80fe9c87086603c) nautilus (stable)
[logit.txt](https://github.com/ceph/ceph-ansible/files/5976712/logit.txt)

**Comment by jeevadotnet** [comment]
think you're missing the dashboard users:

```
#############
# DASHBOARD #
#############
dashboard_enabled: True
# Choose http or https
# For https, you should set dashboard.crt/key and grafana.crt/key
# If you define the dashboard_crt and dashboard_key variables, but leave them as '',
# then we will autogenerate a cert and keyfile
dashboard_protocol: http
dashboard_port: 8443
dashboard_admin_user: admin
dashboard_admin_user_ro: false```
```
grafana_admin_user: admin
# This variable must be set with a strong custom password when dashboard_enabled is True
grafana_admin_password: admin
```

**Comment by lphabc** [comment]
so does this mean I need to add:
dashboard_protocol: http
dashboard_port: 8443
dashboard_admin_user: admin
dashboard_admin_user_ro: false

to my all.yml file?
Does the admin user need to have an account on the dash server? Dash is the server I'm trying to deploy grafana too.
There is no .ansible directory on the dash server in the /root directory while there is on all of the osd's amd mons'.
Is it even talking to it?

**Comment by lphabc** [comment]
When looking at the output I see:
PLAY [grafana-server] **********************************************************

TASK [set ceph grafana install 'In Progress'] **********************************
Tuesday 23 February 2021  06:27:58 -0500 (0:00:00.075)       0:04:37.250 ****** 
skipping: [dash]

TASK [ceph-facts : include facts.yml] ******************************************
Tuesday 23 February 2021  06:27:58 -0500 (0:00:00.062)       0:04:37.313 ****** 
skipping: [dash]

TASK [ceph-facts : set grafana_server_addr fact - ipv4] ************************
Tuesday 23 February 2021  06:27:58 -0500 (0:00:00.053)       0:04:37.367 ****** 
skipping: [dash]

TASK [ceph-facts : set grafana_server_addr fact - ipv6] ************************
Tuesday 23 February 2021  06:27:58 -0500 (0:00:00.076)       0:04:37.443 ****** 
skipping: [dash]

TASK [ceph-facts : set grafana_server_addrs fact - ipv4] ***********************
Tuesday 23 February 2021  06:27:58 -0500 (0:00:00.052)       0:04:37.496 ****** 
skipping: [dash] => (item=dash) 

TASK [ceph-facts : set grafana_server_addrs fact - ipv6] ***********************
Tuesday 23 February 2021  06:27:58 -0500 (0:00:00.061)       0:04:37.558 ****** 
skipping: [dash] => (item=dash) 

TASK [ceph-prometheus : create prometheus directories] *************************
Tuesday 23 February 2021  06:27:58 -0500 (0:00:00.067)       0:04:37.626 ****** 
skipping: [dash] => (item=/etc/prometheus) 
skipping: [dash] => (item=/var/lib/prometheus) 

TASK [ceph-prometheus : write prometheus config file] **************************
Tuesday 23 February 2021  06:27:58 -0500 (0:00:00.069)       0:04:37.696 ****** 
skipping: [dash]

TASK [ceph-prometheus : make sure the alerting rules directory exists] *********
Tuesday 23 February 2021  06:27:58 -0500 (0:00:00.053)       0:04:37.749 ****** 
skipping: [dash]

TASK [ceph-prometheus : copy alerting rules] ***********************************
Tuesday 23 February 2021  06:27:58 -0500 (0:00:00.054)       0:04:37.804 ****** 
skipping: [dash]

TASK [ceph-prometheus : create alertmanager directories] ***********************
Tuesday 23 February 2021  06:27:59 -0500 (0:00:00.053)       0:04:37.857 ****** 
skipping: [dash] => (item=/etc/alertmanager) 
skipping: [dash] => (item=/var/lib/alertmanager) 

TASK [ceph-prometheus : write alertmanager config file] ************************
Tuesday 23 February 2021  06:27:59 -0500 (0:00:00.071)       0:04:37.929 ****** 
skipping: [dash]

TASK [ceph-prometheus : include setup_container.yml] ***************************
Tuesday 23 February 2021  06:27:59 -0500 (0:00:00.057)       0:04:37.987 ****** 
skipping: [dash]

TASK [ceph-grafana : include setup_container.yml] ******************************
Tuesday 23 February 2021  06:27:59 -0500 (0:00:00.046)       0:04:38.033 ****** 
skipping: [dash]

TASK [ceph-grafana : include configure_grafana.yml] ****************************
Tuesday 23 February 2021  06:27:59 -0500 (0:00:00.055)       0:04:38.089 ****** 
skipping: [dash]

TASK [set ceph grafana install 'Complete'] *************************************
Tuesday 23 February 2021  06:27:59 -0500 (0:00:00.057)       0:04:38.147 ****** 
skipping: [dash]

**Comment by jeevadotnet** [comment]
https://github.com/ceph/ceph-ansible/blob/master/group_vars/all.yml.sample will show you the example under the dashboard section. I however have had no luck getting the dashboard installed.

Regards

**Comment by guits** [comment]
@lphabc if your dashboard installation is entirely skipped, it's because either:

- you have overridden `dashboard_enabled` and set it to `false` somewhere in your group_vars/host_vars/inventory
or
- you don't have at least 1 node in your `grafana-server` group


see from the current code in stable-4.0:

```yaml
- import_playbook: dashboard.yml
  when:
    - dashboard_enabled | bool
    - groups.get(grafana_server_group_name, []) | length > 0
```
