### ISSUE TITLE
Cephfs PVC getting permission denied error

### ISSUE THREAD

**Issue by dbenduga** [ceph/ceph-ansible#6298]
We have configured cephfs and integrated with k8s using cephfs provisioner.

Fileystem was mounted and working fine since log time. suddenly we are getting permission error for some pvc's .
There are multiple pvc's but getting error for few pvc..

After restarting pods, issue got resolved. 

is there any way to find why this happened? Is it because of network issue? .. I have checked ceph logs but didn't find anything related to error message.

Note: We have rebooted 2 osd nodes out of 6 osd nodes. We have enough replicas to avoid any kind of io errors.    

### Error ###
10.175.150.214:6789,10.176.150.214:6789:/k8s-prod/optimize/kubernetes/kubernetes-dynamic-pvc-ef978a51-6ab4-11ea-92c2-d2f7f4750034   37T  205G   36T   1% /opt/BCO/repository

sh-4.2$ ls -l
ls: cannot access repository: Permission denied
total 76
**d?????????? ? ?    ?        ?            ? repository**

**Comment by dsavineau** [comment]
That's more a question to ask on the ceph irc on ceph mailing list for the cephfs people because this doesn't seem related to ceph-ansible.
