### ISSUE TITLE
operation osd issues

### ISSUE THREAD

**Issue by Auggie321** [ceph/ceph-ansible#6299]
**Is your feature request related to a problem? Please describe.**
```
Test Server Env: 
OS: Ubuntu 18.04.5 LTS ; Three server nodes ; Ceph version: octopus (stable)
ceph-ansible/group_vars (origin/stable-5.0)
```
[Adding osd(s) tutorials](https://docs.ceph.com/projects/ceph-ansible/en/latest/day-2/osds.html)
server's disk localtion maybe not different, i mean some server's root disk boot from /dev/sdb not /dev/sda；
how to configure devices for ceph osd within osds.yml in that situation;

example1
```
Specify the hard disk partition to create osd in new ceph cluster: 
server1:     
/dev/sdc
/dev/sdd

server2:
/dev/sdb
/dev/sdc

server3:
/dev/vdb
/dev/vdc

how to configure osds.yml,and which command execute it with ceph-ansible;
```

example2
```
if server1 add disk, then it will have /dev/sde, and wanna add /dev/sde in ceph cluster;
how to configure osds.yml, and and which command reconfigure it with ceph-ansible;
```
example3
```
if server1 need remove /dev/sdd, and this disk partition have been add in ceph cluster;
how to configure osds.yml, and and which command reconfigure it with ceph-ansible;
```

osds.yml device , is there have any chance to use as following configuraion；
```osds.yml
devices:
  ## Description format : exmaple HOSTNAME: ["/dev/xx","/dev/xx"]
  ## example server1: ["/dev/sdc","/dev/sdd"], and server1 must add domain in /etc/hosts
  ## if HOSTNAME will have some issues with docker, then hostname could replace with ip address;
  ## example 172.16.10.21: ["/dev/sdc","/dev/sdd"]
  server1: ["/dev/sdc","/dev/sdd"]
  server2: ["/dev/sdb","/dev/sdc"]
  server3: ["/dev/vdb","/dev/vdc"]
```
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

```
https://docs.ceph.com/projects/ceph-ansible/en/latest/day-2/osds.html

Does ceph-ansible tutorials will add more system release support description, 
ubuntu16 can't install ceph within (ceph-ansible/ (origin/stable-5.0))  that deault python3.5's issuse conflict with ansible, 
but same confiugration could install in ubuntu18.
and more operation description will have any chance to add in tutorials?

ceph-ansible is good stuff, thank you for your sharing.
```

**Comment by dsavineau** [comment]
> osds.yml device , is there have any chance to use as following configuraion；
> 
> ```yaml
> devices:
>   ## Description format : exmaple HOSTNAME: ["/dev/xx","/dev/xx"]
>   ## example server1: ["/dev/sdc","/dev/sdd"], and server1 must add domain in /etc/hosts
>   ## if HOSTNAME will have some issues with docker, then hostname could replace with ip address;
>   ## example 172.16.10.21: ["/dev/sdc","/dev/sdd"]
>   server1: ["/dev/sdc","/dev/sdd"]
>   server2: ["/dev/sdb","/dev/sdc"]
>   server3: ["/dev/vdb","/dev/vdc"]
> ```

You should take a look to the ansible documentation about variable configuration per group vs host [1][2]

If you use the `osds.yml` file (group_vars) then the configuration is applied to ALL osd nodes and they should have the same devices layout.

If you don't have the same devices layout then you have to use the ansible `host_vars`

* host_vars/server1.yml
```yaml
devices:
  - /dev/sdc
  - /dev/sdd
```
* host_vars/server2.yml
```yaml
devices:
  - /dev/sdb
  - /dev/sdc
```
* host_vars/server3.yml
```yaml
devices:
  - /dev/vdb
  - /dev/vdc
```

Or alternatively set this configuration in the ansible inventory

```ini
[osds]
server1 devices="['/dev/sdc', '/dev/sdd']"
server2 devices="['/dev/sdb', '/dev/sdc']"
server3 devices="['/dev/vdb', '/dev/vdc']"
```

[1] https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable
[2] https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#splitting-out-vars
