### ISSUE TITLE
Libselinux issue centos7

### ISSUE THREAD

**Issue by egonzalez90** [ceph/ceph-ansible#631]
While installing ceph from upstream on centos 7, it gives error creating configuration files related with selinux.
Doesn't matter if selinux is enabled or disabled.
```
TASK: [ceph.ceph-common | generate ceph configuration file] ******************* 
failed: [192.168.1.49] => {"failed": true}
msg: Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!
failed: [192.168.1.52] => {"failed": true}
msg: Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!

```
The issue gets resolved installing libselinux-python as error message suggest.
Once installed in mons nodes, when tasks pass to other role nodes. Same error happens.
My question, should libselinux-python package marked as required dependency while installing ceph to avoid this issue?

Regards

**Comment by leseb** [comment]
Hi @egonzalez90, weird, i've never seen that. You can edit this variable and add `libselinux-python` https://github.com/ceph/ceph-ansible/blob/master/group_vars/all.sample#L46
I'll update the file.

**Comment by satishdotpatel** [comment]
Even i have installed that package in CentOS7 i am seeing issue.. not sure what is wrong.. even i disabled SELinux and reboot system but same error..
