### ISSUE TITLE
Ceph-ansible with docker-ce 

### ISSUE THREAD

**Issue by yemenlinux** [ceph/ceph-ansible#6314]
When installing ceph using ceph-ansible it conflicts with OpenStack kolla-ansible because kolla-ansible uses docker-ce while ceph-ansible use podman. 

I used this command to pass docker-ce to ceph-ansible:
ansible-playbook -i hosts site.yml -e container_package_name=docker-ce

**Bug Report**

What happened:
How to locate OpenStack controller and Ceph monitor and manager in the same nodes?

What you expected to happen:
Ceph-ansible uses podman to start containers for grafana which is conflicts with docker-ce required by kolla-ansible.

How to reproduce it (minimal and precise):

This issue can be reproduced by colocating the ceph monitor, manager, and grafana-server with openstack controller nodes.

Share your group_vars files, inventory and **full** ceph-ansibe log
CentOS 8
4.18.0-240.10.1.el8_3.x86_64

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Docker version if applicable (e.g. `docker version`):
* Ansible version (e.g. `ansible-playbook --version`):
* ceph-ansible version (e.g. `git head or tag or stable branch`):
* Ceph version (e.g. `ceph -v`):

**Comment by guits** [comment]
@yemenlinux could you share a full ceph-ansible from the command you tried to run ? (`ansible-playbook -i hosts site.yml -e container_package_name=docker-ce`)

**Comment by dsavineau** [comment]
I think you will need to override the `container_binary` to docker too otherwise the default value for CentOS 8 will be set to podman

```console
$ ansible-playbook -i hosts site.yml -e container_package_name=docker-ce -e container_binary=docker
```
