### ISSUE TITLE
roles/ceph-osd/tasks/activate_osds.yml:38 should that not be '== 0'

### ISSUE THREAD

**Issue by dvusboy** [ceph/ceph-ansible#636]
Branch: master

The name of that task seems to suggest it should fire when the device for OSD data is a partition, in which case, that line should say `item.0.get("rc", 0) == 0` instead of `item.0.get("rc", 0) != 0`. BTW, I think I may also found a problem with the `egrep` regexp for partition detection. I think this part, `{h,s,v}`, early in the expression, should be `[hsv]`.

**Comment by leseb** [comment]
You're right, thanks for pointing that out.

**Comment by leseb** [comment]
You're right for the regex too, will fix and enhance it as well.
