### ISSUE TITLE
Convert repository to a Galaxy-compatible collection

### ISSUE THREAD

**Issue by greg-hellings** [ceph/ceph-ansible#6372]
**Is your feature request related to a problem? Please describe.**
This repository has many excellent modules for working with and manipulating a Ceph cluster. These would be marvelously helpful if they were accessible to other tools, roles, playbooks, and collections. Using them straight out of this repository is difficult.

**Describe the solution you'd like**
Please modify this repository to be accessible as an Ansible Collection, thus exposing both the modules and roles to other Ansible authors. With the next release of ansible-core, it would also be possible to expose the playbooks directly as well.

**Describe alternatives you've considered**
I have tried adding this repository as a git submodule for my repository, but that is unseemly. Other options are to download and install as part of a script, but that doesn't allow another collection to use the modules and just declare this as a collection dependency.

**Additional context**
As Ansible moves towards collections, having a collection that enables manipulation of Ceph and not just its installation would be a great benefit to the comunity

**Comment by eengstrom** [comment]
I agree.  We've used these playbooks for years now, but it's always cumbersome and it would be awesome if we could integrate with the rest of our ansible infrastructure.

**Comment by greg-hellings** [comment]
Any comments by core developers on this?

**Comment by eengstrom** [comment]
Any thoughts from the devs?

**Comment by greg-hellings** [comment]
I'm working to contact the devs directly. I'll update with further information as I hear it.

**Comment by eengstrom** [comment]
@greg-hellings - if you need help (persuasion or coding), LMK.

**Comment by greg-hellings** [comment]
So it sounds like the new version of Ceph is going to deprecate this in favor of their own built-in admin tool that... well, it basically does what Ansible does. So the development team seems disinterested in pursuiing further work on this project that's not absolutely necessary.

**Comment by guits** [comment]
@greg-hellings / @eengstrom 

As I said in the ceph-users mailing list:

> Hi all,
>
> ceph-ansible@stable-6.0 supports pacific and the current content in the branch 'master' (future stable-7.0) is intended to support Ceph Quincy.
>
> I can't speak on behalf of Dimitri but I'm personally willing to keep maintaining ceph-ansible if there are interests, but people must be aware that:
>
> - the official and supported installer will be cephadm,
> - officially, ceph-ansible will be unsupported with the consequences it might bring (testing efforts, ci ressources, etc.),
> - Fewer engineering efforts will be carried out (contributions are welcome!)
>
> Thanks,

it didn't receive much enthusiasm which is something I can understand. So I don't really think it makes sense to put engineering efforts into this.
