### ISSUE TITLE
Exception display after deployment using ceph-ansible

### ISSUE THREAD

**Issue by AbelTaylor** [ceph/ceph-ansible#6478]
**Bug Report**

What happened:

What you expected to happen:

How to reproduce it (minimal and precise):

I have successfully deployed the ceph cluster using ceph-ansible, and the cluster status is also normal, but the following abnormal display keeps appearing on my server screen.
![image](https://user-images.githubusercontent.com/71317399/114981348-6d530980-9ec0-11eb-974c-2740568186c2.png)
![image](https://user-images.githubusercontent.com/71317399/114981378-793ecb80-9ec0-11eb-8a28-849ada001de1.png)
![image](https://user-images.githubusercontent.com/71317399/114981566-c7ec6580-9ec0-11eb-9301-510ff5a484e5.png)

**Environment**: 3 ceph nodes
* OS (e.g. from /etc/os-release):  CentOS 8 Stream
* Kernel (e.g. `uname -a`): 4.18.0-269.el8.x86_64
* Docker version if applicable (e.g. `docker version`): Podman Version :  3.1.0-dev
* Ansible version (e.g. `ansible-playbook --version`): 2.9.18
* ceph-ansible version (e.g. `git head or tag or stable branch`): 5.0.5
* Ceph version (e.g. `ceph -v`): 15

**Comment by dsavineau** [comment]
That's not directly related to ceph-ansible but podman because that's the one that uses overlayfs.

Considering you're using a podman dev version, you should report this to podman.
