### ISSUE TITLE
image tags do not match between ceph-ansible and cephadm deployments

### ISSUE THREAD

**Issue by Ejdesgaard** [ceph/ceph-ansible#6479]
**Bug Report**

What happened:
I have deployed a cluster with cephadm and had a look at the image tags deployed, then compared them to ceph-ansible-6.0.3 all.yml and it does not match

What you expected to happen:
matching tags/versions

How to reproduce it (minimal and precise):

Share your group_vars files, inventory and **full** ceph-ansibe log
$ git status
HEAD detached at v6.0.3
...

$ grep -iR container_image all.yml
#node_exporter_container_image: "docker.io/prom/node-exporter:v0.17.0"
#grafana_container_image: "docker.io/grafana/grafana:6.7.4"
#prometheus_container_image: "docker.io/prom/prometheus:v2.7.2"
#alertmanager_container_image: "docker.io/prom/alertmanager:v0.16.2"

From # ceph orch ps
VERSION NAME
0.20.0 alertmanager.node05
6.7.4 grafana.node04
0.18.1 node-exporter.node01
0.18.1 node-exporter.node02
0.18.1 node-exporter.node03
0.18.1 node-exporter.node04
0.18.1 node-exporter.node05
2.18.1 prometheus.node01

**Environment**:
ceph version 
ceph version 16.2.0 (0c2054e95bcd9b30fdd908a79ac1d8bbc3394442) pacific (stable)

cat /etc/centos-release
CentOS Linux release 8.3.2011

cephadm version
Using recent ceph image docker.io/ceph/ceph@sha256:030e84addad8f3a7d26ea49b180660f1a9b33ef06d691759f320a58e892fb535
ceph version 15.2.10 (27917a557cca91e4da407489bbaa64ad4352cc02) octopus (stable)

**Comment by dsavineau** [comment]
That's expected.

ceph-ansible and cephadm aren't two different tools two with different default values.

If you want to use the same container image tag than cephadm then you can still override the ceph-ansible default values.
