### ISSUE TITLE
Is it possible to deploy ceph without grafana in version 6.0?

### ISSUE THREAD

**Issue by poul1x** [ceph/ceph-ansible#6505]
I've encountered an error:

```
TASK [ceph-validate : fail if monitoring group doesn't exist] **********************************************************
Monday 03 May 2021  22:20:03 +0300 (0:00:00.153)       0:00:43.037 ************
fatal: [n1.local]: FAILED! => changed=false
  msg: you must add a monitoring group and add at least one node.
...
```

It looks like `ceph-ansible` forces me to deploy grafana. But ceph dashboard  is enough for me.
Is it possible to deploy only `cephmgr` with dashboard?

**Comment by poul1x** [comment]
Oh, I didn't order entire monitoring stack...

**Comment by dsavineau** [comment]
Yes, the default setup is to deploy the dashboard and the monitoring stack (grafana, prometheus and node-exporter) when `dashboard_enabled: true` (which is the default value).

That said, what you're asking is probably possible (but untested) and you will have to configure the dashboard (TLS, port, user) by yourself.

in all.yml
```yaml
dashboard_enabled: false
```

in mgrs.yml
```yaml
ceph_mgr_modules:
  - dashboard
```

**Comment by poul1x** [comment]
Thanks for provided solution.

I've tried it, but dashboard module has not been deployed.
So, my solution is to deploy ceph without dashboard and monitoring stack:

```yaml
# all.yml
dashboard_enabled: false
```
Then manual installation of dashboard module ([link1](https://docs.ceph.com/en/latest/mgr/dashboard/), [link2](https://stackoverflow.com/questions/56696819/ceph-nautilus-how-to-enable-the-ceph-mgr-dashboard))

![image](https://user-images.githubusercontent.com/31695750/117011067-2190c480-acf6-11eb-9a43-db4784904099.png)

And it works :)
