### ISSUE TITLE
Do I need to override `mgr_secret`, `admin_secret` in group_vars?

### ISSUE THREAD

**Issue by poul1x** [ceph/ceph-ansible#6514]
What are these vars responsible for? Should I override them?
There's no checks for them. I was able to deploy ceph with default values

```
# mgrs.yml
mgr_secret: 'mgr_secret'

# mons.yml
# ACTIVATE BOTH FSID AND MONITOR_SECRET VARIABLES FOR NON-VAGRANT DEPLOYMENT
monitor_secret: "{{ monitor_keyring.stdout }}"
admin_secret: 'admin_secret'
```

**Comment by dsavineau** [comment]
Those variables are used if you want to set your own keyring value for monitor, mgr and admin keys.

If you keep those default values then you will have autogenerated value.

**Comment by poul1x** [comment]
Ok, thanks for info
