### ISSUE TITLE
ERROR! 'mon_containerized_deployment_with_kv' is undefined

### ISSUE THREAD

**Issue by ksingh7** [ceph/ceph-ansible#652]
Hi
I was trying out this repo and did the following
```
git clone https://github.com/ceph/ceph-ansible.git
cd ceph-ansible/
cp vagrant_variables.yml.sample vagrant_variables.yml
cp site.yml.sample site.yml
vagrant up --no-provision --provider=virtualbox
vagrant provision
```
But then it failed here
```
TASK [ceph.ceph-common : generate ceph configuration file] *********************
fatal: [osd0]: FAILED! => {"failed": true, "msg": "ERROR! 'mon_containerized_deployment_with_kv' is undefined"}
fatal: [osd1]: FAILED! => {"failed": true, "msg": "ERROR! 'mon_containerized_deployment_with_kv' is undefined"}
fatal: [osd2]: FAILED! => {"failed": true, "msg": "ERROR! 'mon_containerized_deployment_with_kv' is undefined"}

PLAY RECAP *********************************************************************
mon0                       : ok=47   changed=0    unreachable=0    failed=0
osd0                       : ok=30   changed=0    unreachable=0    failed=1
osd1                       : ok=29   changed=0    unreachable=0    failed=1
osd2                       : ok=29   changed=0    unreachable=0    failed=1

```
Do you think it has something to do with #630 ? 
Anyways I made it working after adding  ``mon_containerized_deployment_with_kv: false``  to  ``roles/ceph-common/defaults/main.yml``
But what's the right way to fix it ?

**Comment by leseb** [comment]
Hi @ksingh7, came across that one too and forgot to push a change.
I've been thinking about a "non-ugly" way to fix it however it seems that declaring `mon_containerized_deployment_with_kv`  to `false` in the ceph-common role is the only valid fix I can think about.
I'm saying 'ugly' because it is not ideal given that the containerized scenario doesn't have any dependency with the ceph-common so it's a bit weird to find a container variable...

Anyways, can I leet you submit a fix for this?
In the PR, please highlight this issue and explicitly write to not touch this variable :).

Thanks!

**Comment by ksingh7** [comment]
Thanks @leseb happy to submit my first PR for this project :) will do it as soon as i can.

**Comment by ksingh7** [comment]
Some permission issue while pushing the changes , do i need to do any additional step for this repo ?
```
teeri:ceph-ansible ksingh$ git branch
* fix_mon_containerized_deployment_with_kv
  master
teeri:ceph-ansible ksingh$
teeri:ceph-ansible ksingh$ git status
On branch fix_mon_containerized_deployment_with_kv
nothing to commit, working directory clean
teeri:ceph-ansible ksingh$
teeri:ceph-ansible ksingh$ git push origin fix_mon_containerized_deployment_with_kv
remote: Permission to ceph/ceph-ansible.git denied to ksingh7.
fatal: unable to access 'https://github.com/ceph/ceph-ansible.git/': The requested URL returned error: 403
teeri:ceph-ansible ksingh$
teeri:ceph-ansible ksingh$ telnet github.com 443
Trying 192.30.252.129...
Connected to github.com.
Escape character is '^]'.
```

**Comment by leseb** [comment]
@ksingh7 read the pull request section of this https://guides.github.com/activities/contributing-to-open-source/

**Comment by ksingh7** [comment]
Thanks @leseb that was a useful link :)
I have created PR for this issue #653 , please let me know if need to change something.

**Comment by ksingh7** [comment]
Issue fixed with #653

**Comment by civik** [comment]
Seeing this issue with a fresh clone.  

`TASK [ceph.ceph-common : generate ceph configuration file] *********************
fatal: [osd0]: FAILED! => {"failed": true, "msg": "'mon_containerized_deployment' is undefined"}
fatal: [osd1]: FAILED! => {"failed": true, "msg": "'mon_containerized_deployment' is undefined"}
fatal: [osd2]: FAILED! => {"failed": true, "msg": "'mon_containerized_deployment' is undefined"}`

**Comment by leseb** [comment]
@civik just fixed the issue, sorry about that.
