### ISSUE TITLE
playbook does not finish when setting inventory host group variables

### ISSUE THREAD

**Issue by dennisTGC** [ceph/ceph-ansible#6523]
**Bug Report**

What happened:
> While setting the host group variables in `group_vars/all.yml` to our own naming the ansible playbook didn't finish and hanged on the task creating ceph keys. Even after hours it didn't complete or threw errors. 

What you expected to happen:
> that using the inventory group variables could be used. 

How to reproduce it (minimal and precise):

I set the following in the all.yaml
```
mon_group_name: cmon
osd_group_name: cosd
rgw_group_name: cog
ntp_service_enabled: false
ceph_origin: repository
ceph_repository: community
ceph_stable_release: nautilus
monitor_interface: eth0
public_network: "10.4.10.0/24"
radosgw_interface: eth0
dashboard_enabled: false
dashboard_admin_password: secret
grafana_admin_password: secret
```
ansible file
```
[ceph:children]
cog
cmon
cosd
# Ceph OSD's
[cosd]
t-cosd[01:03]
[cog]
t-cog[01:02]
[cmon]
t-cmon[01:03]
[mgrs]
t-cmon[01:03]
```
Share your group_vars files, inventory and **full** ceph-ansibe log

**Environment**: 
* OS (e.g. from /etc/os-release): ubuntu 18.04.4
* Kernel (e.g. `uname -a`): 4.15.0-142-generic
* Docker version if applicable (e.g. `docker version`): 
* Ansible version (e.g. `ansible-playbook --version`): ansible 2.9.16
* ceph-ansible version (e.g. `git head or tag or stable branch`): stable-4.0
* Ceph version (e.g. `ceph -v`): 14.2.20

**Comment by guits** [comment]
@dennisTGC  Please, share a full ceph-ansible log

**Comment by dennisTGC** [comment]
sorry, here it is.
[Ansible.log](https://github.com/ceph/ceph-ansible/files/6503525/Ansible.log)

**Comment by guits** [comment]
@dennisTGC Am I missing something or the log you provided seems messed up ?

**Comment by dennisTGC** [comment]
yes, sorry, something went wrong with the copy/paste.
[Ansible.log](https://github.com/ceph/ceph-ansible/files/6515690/Ansible.log)

**Comment by guits** [comment]
> yes, sorry, something went wrong with the copy/paste.
> [Ansible.log](https://github.com/ceph/ceph-ansible/files/6515690/Ansible.log)

I don't see any difference with the first attachment

**Comment by dennisTGC** [comment]
aargh.. you should think I could copy/paste after 20 years ICT experience..
[Ansible.log](https://github.com/ceph/ceph-ansible/files/6515761/Ansible.log)

**Comment by guits** [comment]
if you ssh `t-cmon01.tgctest` and you run sudo `/usr/bin/apt-get -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold"      install 'apt-transport-https' 'gnupg' 'software-properties-common'` it should throw the same error i guess

**Comment by dennisTGC** [comment]
I will try it, it will take some time as I have to revert the VMs to a clean state. But it's curious as if I remove the group name mapping, it runs fine.
