### ISSUE TITLE
Failed ceph-osd: wait for all osd to be up

### ISSUE THREAD

**Issue by ekhawmu** [ceph/ceph-ansible#6527]
Hi,

I am trying to install CEPH on three nodes cluster as a baremetal deployment. It gets failed on osds, see below screenshot

![image](https://user-images.githubusercontent.com/11440656/117521241-a7399c00-afa4-11eb-9037-9c2cbc1c6e14.png)

Following are the IP addressess connected on interface **eno1np0**

> 192.168.10.201
> 192.168.10.202
> 192.168.10.203

**OS Ubuntu-20.04 LTS
kernel: 5.8.0-5-generic
Ansible version: 2.9.6
python version: 3.8.5**

In all above 3 nodes dedicated **8TB HD** is attached for CEPH on each node.

Following are the configurations of all.yml
```
ceph_origin: repository
ceph_repository: community
ceph_stable_release: octopus
public_network: "192.168.10.0/24"
cluster_network: "192.168.10.0/24"
monitor_interface: eno1np0
grafana_admin_user: admin
grafana_admin_password: T3ster!23
dashboard_admin_user: admin
dashboard_admin_password: T3ster!23
ceph_use_distro_backports: false
containerized_deployment_mode: false
journal_size: 10240
devices:
  - '/dev/sda'
```
cat /etc/ansible/hosts
```
[mons]
192.168.10.201
192.168.10.202
192.168.10.203

[osds]
192.168.10.201
192.168.10.202
192.168.10.203

[mgrs]
192.168.10.201
192.168.10.202
192.168.10.203

[grafana-server]
192.168.10.201
```

![image](https://user-images.githubusercontent.com/11440656/117520705-8d4a8a00-afa1-11eb-9f58-118d291808f1.png)

fdisk -l
![image](https://user-images.githubusercontent.com/11440656/117520730-a3f0e100-afa1-11eb-96cf-60964508dbfb.png)

[
[ceph-volume.log](https://github.com/ceph/ceph-ansible/files/6444925/ceph-volume.log)
[ceph.log](https://github.com/ceph/ceph-ansible/files/6444926/ceph.log)
](url)

Thanks in advance,
Let me know if you need more information

**Comment by jakoberpf** [comment]
could be the same [issue](https://github.com/ceph/ceph-ansible/issues/6522) as i have...
