### ISSUE TITLE
Backport RadosGW modules to stable-4.0

### ISSUE THREAD

**Issue by Dazul** [ceph/ceph-ansible#6535]
Currently we are using ceph-ansible to manage our ceph clusters. The only thing we keep managing by end are the radosgw users, buckets.

radosgw modules are really useful, but they have been back-ported only to stable-5.0. Is it any reason for that? Is it possible to backport them into stable-4.0?

Doing some cleaning and automation could help us a lot before upgrading our ceph clusters.

**Comment by guits** [comment]
> radosgw modules are really useful, but they have been back-ported only to stable-5.0. Is it any reason for that? 

Yes, usually we backport bug fixes only.

> Is it possible to backport them into stable-4.0?

I'm afraid not, that would be too many changes for a backport in stable-4.0
