### ISSUE TITLE
Failed to sync iscsi gateway config after cluster installation: there is no tcmu-runner data avaliable

### ISSUE THREAD

**Issue by HashFail** [ceph/ceph-ansible#6567]
**Bug Report**

After deploying a ceph cluster with an iscsi gateway, create a gateway vs gwcli fails:

```
create iqn.2021-05.com.privatemachines.iscsi-gw:iscsi-igw
ok
/iscsi-targets> cd iqn.2021-05.com.privatemachines.iscsi-gw:iscsi-igw/
create ceph-iscsigw0.novalocal 10.0.0.41
Adding gateway, sync'ing 0 disk(s) and 0 client(s)
REST API failure, code : 403
Unable to refresh local config over API - sync aborted, restart rbd-target-api on ceph-iscsigw0.novalocal to sync
```

`/var/log/rbd-target-api/rbd-target-api.log` contains the following messages

```
2021-06-03 21:59:42,091     INFO [_internal.py:87:_log()] - ::1 - - [03/Jun/2021 21:59:42] "PUT /api/gateway/iqn.2021-05.com.privatemachines.iscsi-gw:iscsi-igw/ceph-iscsigw0.novalocal HTTP/1.1" 200 -
2021-06-03 21:59:42,132     INFO [_internal.py:87:_log()] - fe80::f816:3eff:feec:d6db%eth0 - - [03/Jun/2021 21:59:42] "GET /api/config HTTP/1.1" 403 -
2021-06-03 21:59:42,502  WARNING [device_status.py:127:run()] - there is no tcmu-runner data avaliable
2021-06-03 21:59:52,514  WARNING [device_status.py:127:run()] - there is no tcmu-runner data avaliable
2021-06-03 22:00:02,526  WARNING [device_status.py:127:run()] - there is no tcmu-runner data avaliable
2021-06-03 22:00:12,538  WARNING [device_status.py:127:run()] - there is no tcmu-runner data avaliable
2021-06-03 22:00:22,549  WARNING [device_status.py:127:run()] - there is no tcmu-runner data avaliable
2021-06-03 22:00:32,552  WARNING [device_status.py:127:run()] - there is no tcmu-runner data avaliable
2021-06-03 22:00:42,562  WARNING [device_status.py:127:run()] - there is no tcmu-runner data avaliable
2021-06-03 22:00:52,574  WARNING [device_status.py:127:run()] - there is no tcmu-runner data avaliable
2021-06-03 22:01:02,586  WARNING [device_status.py:127:run()] - there is no tcmu-runner data avaliable
2021-06-03 22:01:12,592  WARNING [device_status.py:127:run()] - there is no tcmu-runner data avaliable
```

What you expected to happen:

How to reproduce it (minimal and precise):

Share your group_vars files, inventory and **full** ceph-ansibe log

group/vars.all
```
ceph_origin: repository
ceph_repository: community
ceph_stable_release: pacific
public_network: "10.0.0.0/24"
radosgw_interface: eth0
monitor_interface: eth0
dashboard_enabled: true
containerized_deployment: false
devices:
  - '/dev/vdb'
  - '/dev/vdc'
  - '/dev/vdd'
  - '/dev/vde'
monitoring_group_name: monitoring
dashboard_admin_password: xxx
grafana_admin_password: xxx
```

Full log: https://textbin.net/raw/1owjr4ovud

**Environment**:
* OS (e.g. from /etc/os-release):

NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8

* Kernel (e.g. `uname -a`): Linux ceph-iscsigw0.novalocal 4.18.0-240.1.1.el8_3.x86_64 #1 SMP Thu Nov 19 17:20:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Ansible version (e.g. `ansible-playbook --version`): ansible-playbook 2.9.6
* ceph-ansible version (e.g. `git head or tag or stable branch`): stable-6.0/e91e9d65021c5c51c5806ee0f9966961e8a1b131
* Ceph version (e.g. `ceph -v`): ceph version 16.2.4 (3cbe25cde3cfa028984618ad32de9edc4c1eaed0) pacific (stable)

**Comment by guits** [comment]
@HashFail is tcmu-runner well running ?

**Comment by HashFail** [comment]
Yes, tcmu-runner is up and running according to systemctl:

systemctl status tcmu-runner | cat
● tcmu-runner.service - LIO Userspace-passthrough daemon
   Loaded: loaded (/usr/lib/systemd/system/tcmu-runner.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2021-06-03 21:51:03 UTC; 1 weeks 6 days ago
     Docs: man:tcmu-runner(8)
 Main PID: 21144 (tcmu-runner)
    Tasks: 5 (limit: 60689)
   Memory: 22.0M
   CGroup: /system.slice/tcmu-runner.service
           └─21144 /usr/bin/tcmu-runner

Jun 03 21:51:03 ceph-iscsigw0.novalocal systemd[1]: Starting LIO Userspace-passthrough daemon...
Jun 03 21:51:03 ceph-iscsigw0.novalocal tcmu-runner[21144]: log file path now is '/var/log/tcmu-runner.log'
Jun 03 21:51:03 ceph-iscsigw0.novalocal tcmu-runner[21144]: main:1302: Starting...
Jun 03 21:51:03 ceph-iscsigw0.novalocal tcmu-runner[21144]: tcmur_register_handler:92: Handler fbo is registered
Jun 03 21:51:03 ceph-iscsigw0.novalocal tcmu-runner[21144]: tcmur_register_handler:92: Handler zbc is registered
Jun 03 21:51:03 ceph-iscsigw0.novalocal tcmu-runner[21144]: tcmur_register_handler:92: Handler glfs is registered
Jun 03 21:51:03 ceph-iscsigw0.novalocal tcmu-runner[21144]: tcmur_register_handler:92: Handler qcow is registered
Jun 03 21:51:03 ceph-iscsigw0.novalocal tcmu-runner[21144]: tcmur_register_handler:92: Handler rbd is registered
Jun 03 21:51:03 ceph-iscsigw0.novalocal systemd[1]: Started LIO Userspace-passthrough daemon.

```
journalctl -u tcmu-runner | cat
-- Logs begin at Thu 2021-06-03 20:11:02 UTC, end at Thu 2021-06-17 16:47:36 UTC. --
Jun 03 20:24:43 ceph-iscsigw0.novalocal systemd[1]: Starting LIO Userspace-passthrough daemon...
Jun 03 20:24:43 ceph-iscsigw0.novalocal tcmu-runner[15113]: log file path now is '/var/log/tcmu-runner.log'
Jun 03 20:24:43 ceph-iscsigw0.novalocal tcmu-runner[15113]: main:1302: Starting...
Jun 03 20:24:43 ceph-iscsigw0.novalocal tcmu-runner[15113]: load_our_module:576: Inserted module 'target_core_user'
Jun 03 20:24:43 ceph-iscsigw0.novalocal tcmu-runner[15113]: tcmur_register_handler:92: Handler fbo is registered
Jun 03 20:24:43 ceph-iscsigw0.novalocal tcmu-runner[15113]: tcmur_register_handler:92: Handler zbc is registered
Jun 03 20:24:43 ceph-iscsigw0.novalocal tcmu-runner[15113]: tcmur_register_handler:92: Handler glfs is registered
Jun 03 20:24:43 ceph-iscsigw0.novalocal tcmu-runner[15113]: tcmur_register_handler:92: Handler qcow is registered
Jun 03 20:24:43 ceph-iscsigw0.novalocal tcmu-runner[15113]: tcmur_register_handler:92: Handler rbd is registered
Jun 03 20:24:43 ceph-iscsigw0.novalocal systemd[1]: Started LIO Userspace-passthrough daemon.
Jun 03 21:46:41 ceph-iscsigw0.novalocal systemd[1]: Stopping LIO Userspace-passthrough daemon...
Jun 03 21:46:41 ceph-iscsigw0.novalocal tcmu-runner[15113]: main:1425: Exiting...
Jun 03 21:46:41 ceph-iscsigw0.novalocal tcmu-runner[15113]: tcmu_rbd_destroy:1662: destroying the rbd handler
Jun 03 21:46:41 ceph-iscsigw0.novalocal systemd[1]: tcmu-runner.service: Succeeded.
Jun 03 21:46:41 ceph-iscsigw0.novalocal systemd[1]: Stopped LIO Userspace-passthrough daemon.
Jun 03 21:51:03 ceph-iscsigw0.novalocal systemd[1]: Starting LIO Userspace-passthrough daemon...
Jun 03 21:51:03 ceph-iscsigw0.novalocal tcmu-runner[21144]: log file path now is '/var/log/tcmu-runner.log'
Jun 03 21:51:03 ceph-iscsigw0.novalocal tcmu-runner[21144]: main:1302: Starting...
Jun 03 21:51:03 ceph-iscsigw0.novalocal tcmu-runner[21144]: tcmur_register_handler:92: Handler fbo is registered
Jun 03 21:51:03 ceph-iscsigw0.novalocal tcmu-runner[21144]: tcmur_register_handler:92: Handler zbc is registered
Jun 03 21:51:03 ceph-iscsigw0.novalocal tcmu-runner[21144]: tcmur_register_handler:92: Handler glfs is registered
Jun 03 21:51:03 ceph-iscsigw0.novalocal tcmu-runner[21144]: tcmur_register_handler:92: Handler qcow is registered
Jun 03 21:51:03 ceph-iscsigw0.novalocal tcmu-runner[21144]: tcmur_register_handler:92: Handler rbd is registered
Jun 03 21:51:03 ceph-iscsigw0.novalocal systemd[1]: Started LIO Userspace-passthrough daemon.
```
