### ISSUE TITLE
rolling_update.yml fails at [ceph-rgw : update period for zone creation]

### ISSUE THREAD

**Issue by DavePiperMicrosoft** [ceph/ceph-ansible#6578]
**Bug Report**

What happened:

I ran the rolling_update.yml playbook on a containerized cluster to upgrade from v4.0.12-stable-4.0-nautilus-centos-7  to v5.0.10-stable-5.0-octopus-centos-8  using ceph-ansible stable-5.0. We have applied a number of local modifications to the ceph-ansible code but I don't see how they would be changing the here.

The playbook failed at TASK [ceph-rgw : update period for zone creation] which was run whilst upgrading the mon cluster. The task tried to run on the MON container that is not present as we're in the process of upgrading it.

2021-06-10 15:40:39,809 p=26731 u=qs-admin n=ansible | TASK [ceph-rgw : update period for zone creation] 
2021-06-10 15:40:39,809 p=26731 u=qs-admin n=ansible | Thursday 10 June 2021  15:40:39 +0000 (0:00:03.736)       0:01:54.759 *********
2021-06-10 15:40:40,393 p=26731 u=qs-admin n=ansible | failed: [10.225.39.92 -> 10.225.39.92] (item={u'is_master': True, u'zonegroup': u'geored_zg', u'endpoints': u'https://10.225.39.92:7480,https://10.
225.39.93:7480,https://10.225.39.94:7480', u'realm': u'geored_realm', u'zone': u'siteA'}) => changed=true
  ansible_loop_var: item
  cmd:
  - docker
  - exec
  - ceph-mon-prd16134_fv_sc0
  - radosgw-admin
  - --cluster=ceph
  - --rgw-realm=geored_realm
  - --rgw-zonegroup=geored_zg
  - --rgw-zone=siteA
  - period
  - update
  - --commit
  delta: '0:00:00.069922'
  end: '2021-06-10 15:40:40.349614'
  item:
    endpoints: https://10.225.39.92:7480,https://10.225.39.93:7480,https://10.225.39.94:7480
    is_master: true
    realm: geored_realm
    zone: siteA
    zonegroup: geored_zg
  msg: non-zero return code
  rc: 1
  start: '2021-06-10 15:40:40.279692'
  stderr: 'Error: No such container: ceph-mon-prd16134_fv_sc0'
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
2021-06-10 15:40:40,451 p=26731 u=qs-admin n=ansible | skipping: [10.225.39.92] => (item={u'realm': u'geored_realm', u'zone': u'siteApubsub', u'sync_zone': u'siteA', u'is_master': True, u'tier_type': u'pubsub', u'endpoints': u'https://10.225.39.92:7481,https://10.225.39.93:7481,https://10.225.39.94:7481', u'zonegroup': u'geored_zg'})

We're getting to this point via the following playbook/task invocations:

1) rolling-update.yml : import_role: name: ceph-handler 

[hosts.txt.txt](https://github.com/ceph/ceph-ansible/files/6633834/hosts.txt.txt)

[ansible_log.txt.log](https://github.com/ceph/ceph-ansible/files/6633835/ansible_log.txt.log)
[groupvars.txt](https://github.com/ceph/ceph-ansible/files/6633842/groupvars.txt)

2) ceph-handler/tasks/main.yml : import_role ceph-rgw
3) ceph-rgw/tasks/multisite.yml: include_tasks multisite
4) ceph-rgw/tasks/multisite/main.yml : include_tasks master.yml
5) ceph-rgw/tasks/multisite/master.yml : update period for zone creation

What you expected to happen:

Playbook completes successfully. Ansible scripts to upgrade cluster shouldn't need to update RGW period.

How to reproduce it (minimal and precise):

Run `ansible-playbook rolling_update.yml`

Share your group_vars files, inventory and **full** ceph-ansibe log

**Environment**:
[qs-admin@prd16134_fv_sc0 ~]$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

[qs-admin@prd16134_fv_sc0 ~]$ sudo uname -a
Linux prd16134_fv_sc0 5.4.108-1.el7.elrepo.x86_64 #1 SMP Mon Mar 22 18:37:08 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux

[qs-admin@prd16134_fv_sc0 ~]$ sudo docker version
Client: Docker Engine - Community
 Version:           19.03.15
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        99e3ed8919
 Built:             Sat Jan 30 03:17:57 2021
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.15
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       99e3ed8919
  Built:            Sat Jan 30 03:16:33 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

[qs-admin@prd16134_fv_sc0 ~]$ sudo ansible-playbook --version
[WARNING]: log file at /root/ansible/ansible.log is not writeable and we cannot create it, aborting

ansible-playbook 2.9.21
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/stretch-ansible/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Nov 16 2020, 22:23:17) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]

[qs-admin@prd16134_fv_sc0 ~]$ sudo docker exec d98a6738a3be ceph -v
ceph version 14.2.9 (581f22da52345dba46ee232b73b990f06029a2a0) nautilus (stable)
[qs-admin@prd16134_fv_sc0 ~]$

Ceph ansible branch: stable-5.0 with some of our own modifications

**Comment by guits** [comment]
that will be fixed by #6577

**Comment by DavePiperMicrosoft** [comment]
Ah, brilliant! Sorry for the duplicate, looks like #6577 might have been created just after I'd checked for existing issues.

Dave
