### ISSUE TITLE
site_container.yml fails when creating secondary zone in existing realm/zonegroup

### ISSUE THREAD

**Issue by DavePiperMicrosoft** [ceph/ceph-ansible#6613]
[ansible.log](https://github.com/ceph/ceph-ansible/files/6671063/ansible.log)
[all_yml.txt](https://github.com/ceph/ceph-ansible/files/6671070/all_yml.txt)
**Bug Report**

What happened:

Followed the instructions detailed under "Deployment Scenario #1: Single Realm & Zonegroup with Multiple Ceph Clusters" from https://github.com/ceph/ceph-ansible/blob/master/README-MULTISITE.md

During creation of the second zone, site_container.yml failed. Ansible has called into:

	- Multisite/main.yml
		○ [set_fact realms]
			§ skipped because rgw_zonemaster: false
		○ [create list zonegroups]
			§ Not skipped, because rgw_zonegroupmaster: true
			§ builds up a non-empty zonegroups list
		○ ...
		○ Multisite/master.yml always included
			§ [create the realm(s)]
				□ skipped because realms is empty
			§ [create zonegroup(s)]
				□ Attempted because zonegroups is non-empty

At this point we've failed because there's no realm (we need to pull it from the master zone which doesn't happen until multisite/secondary.yml)

What you expected to happen:

Playbook succeeds. 

How to reproduce it (minimal and precise):
Follow the steps under "Deployment Scenario #1: Single Realm & Zonegroup with Multiple Ceph Clusters" from https://github.com/ceph/ceph-ansible/blob/master/README-MULTISITE.md

The relevant bit of group_vars:

	rgw_multisite: true
	rgw_zonemaster: false
	rgw_zonesecondary: true
	rgw_zonegroupmaster: true
	rgw_zone: siteB
	rgw_zonegroup: geored_zg
        rgw_realm: geored_realm

**Environment**:

ceph-ansible version: stable-5.0 (with some local modifications that I don't think affect this issue)

**Comment by DavePiperMicrosoft** [comment]
I forgot to paste the ansible failure:

```
TASK [ceph-rgw : create zonegroup(s)] ***********************************************************************************
Thursday 17 June 2021 10:48:31 +0000 (0:00:00.053) 0:23:36.137 *********
failed: [10.225.38.254 -> 10.225.38.254] (item={u'is_master': True, u'zonegroup': u'geored_zg', u'realm': u'geored_realm'}) => changed=true
ansible_loop_var: item
cmd:
- docker
- run
- --rm
- --net=host
- -v
- /cephconfig/etc/ceph:/etc/ceph:z
- -v
- /cephconfig/var/lib/ceph/:/var/lib/ceph/:z
- -v
- /var/log/ceph/:/var/log/ceph/:z
- --entrypoint=radosgw-admin
- ceph-daemon:v5.0.10-stable-5.0-octopus-centos-8
- --cluster
- ceph
- zonegroup
- create
- --rgw-realm=geored_realm
- --rgw-zonegroup=geored_zg
- --default
- --master
delta: '0:00:00.754246'
end: '2021-06-17 10:48:32.740688'
item:
is_master: true
realm: geored_realm
zonegroup: geored_zg
rc: 2
start: '2021-06-17 10:48:31.986442'
stderr: 'failed to init realm: (2) No such file or directory'
stderr_lines: <omitted>
stdout: ''
stdout_lines: <omitted>
		  item:
		    is_master: true
		    realm: geored_realm
		    zonegroup: geored_zg
```

**Comment by DavePiperMicrosoft** [comment]
This issue still requires investigation. Could someone get back to me please?  I can provide additional diags if required.

**Comment by guits** [comment]
@DavePiperMicrosoft could you share the full ansible log ?

**Comment by DavePiperMicrosoft** [comment]
I'm not sure I understand your last update. We have #71a5e66 applied in the version of ceph-ansible we're running, which is why we're hitting this issue.

Are you saying our config in all.yml is wrong? Currently we have: 

```
rgw_multisite: true
rgw_zonemaster: false
rgw_zonesecondary: true
rgw_zonegroupmaster: true
rgw_zone: siteB
rgw_zonegroup: geored_zg
rgw_realm: geored_realm
```

on the secondary site. We have already created (master) RGW zone "siteA" inside (master) zonegroup "geored_zg" using a different all.yml file to deploy a previous ceph cluster, and now are trying to deploying a second cluster with a RGW zone "siteB" as a secondary zone in the same zonegroup.

**Comment by kutovoy** [comment]
this is still happening on branch 5.0ga installing ceph octopus
