### ISSUE TITLE
Fail to generate ceph.conf when fsid is set and not automatically generated

### ISSUE THREAD

**Issue by leseb** [ceph/ceph-ansible#672]
Reported by @analbeard in #667 

TASK [ceph.ceph-common : generate ceph configuration file] *********************
task path: /root/ceph-02/ceph-ansible-cloudnull/roles/ceph-common/tasks/main.yml:178
<mon01-c02-rd> ESTABLISH SSH CONNECTION FOR USER: None
<mon01-c02-rd> SSH: EXEC ssh -C -q -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r -tt mon01-c02-rd '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1459409006.79-142331915204165 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1459409006.79-142331915204165 `" )'"'"''
fatal: [mon01-c02-rd]: FAILED! => {"failed": true, "msg": "{{ cluster_uuid.stdout }}: 'dict object' has no attribute 'stdout'"}
I was able to work around this by removing the fsid I had manually specified and letting the play generate a UUID instead.

**Comment by stpierre** [comment]
We currently do exactly this without problems. We have:

  fsid: "{{ foo|magical_fsid_generating_filter }}"
  generate_fsid: false

If you override `fsid` for all of your nodes, then you shouldn't get the error you're showing.

**Comment by leseb** [comment]
You're right, let's close this for now.
