### ISSUE TITLE
low-priority: "ansible-playbook -l rgws site.yml" fails

### ISSUE THREAD

**Issue by bengland2** [ceph/ceph-ansible#674]
I wanted to reinstall just the RGWs, instead of having to reinstall the whole cluster (I was having a problem with authentication in Swift).    When I try to reinstall just the RGW hosts with command in subject line, it fails with 

  TASK: [ceph.ceph-common | generate ceph configuration file] ******************\* 
  fatal: [gprfc074] => One or more undefined variables: 'dict object' has no attribute 'ansible_eth1'

looking at the code for this task, it is expanding a jinja2 template for ceph.conf, and the problem occurs in the vicinity of 

  {% if monitor_interface != "interface" %}
  {% include 'mon_addr_interface.j2' %}
  {% else %}
  {% include 'mon_addr_address.j2' %}
  {% endif %}

and since the "if" condition would have failed (I set it to eth1), then it would have evaluated

  mon addr = {{ hostvars[host]['ansible_' + (hostvars[host]['monitor_interface'] if hostvars[host]['monitor_interface'] is defined else monitor_interface) ]['ipv4']['address'] }}

so I commented out monitor_interface var in my group_vars/all file and it gets farther now, but blows up on this:

  TASK: [ceph-rgw | create rados gateway keyring] ******************************\* 
  failed: [gprfc073] => {"changed": false, "cmd": ["ceph", "--cluster", "ceph", "--name", "client.bootstrap-rgw", "--keyring", "/var/lib/ceph/bootstrap-rgw/ceph.keyring", "auth", "get-or-create", "client.rgw.gprfc073", "osd", "allow rwx", "mon", "allow rw", "-o", "/var/lib/ceph/radosgw/ceph-rgw.gprfc073/keyring"], "delta": "0:00:00.141773", "end": "2016-04-01 08:23:40.865557", "rc": 1, "start": "2016-04-01 08:23:40.723784", "warnings": []}
  stderr: no monitors specified to connect to.
  Error connecting to cluster: ObjectNotFound

I think the jinja2 loop can't find a monitor as it loops through hosts in ceph.conf.j2, because I said to limit scope to RGWs.  

  {% for host in groups[mon_group_name] %}

Is there another way to access hosts that are in the inventory flie but out of scope for the current play?

**Comment by leseb** [comment]
Yes this is tricky since we have a dependancy on the monitors.
I recently discussed an alternative with @SamYaple, which will allow us to generates a complete `ceph.conf` with all the hosts.
It might solve this issue.

Not sure when I'll have time to address this.

**Comment by bengland2** [comment]
This brings up the whole subject of incremental installation.  Is there a way to incrementally install using ceph-ansible?  For example, can you add(/remove) hosts for any of the roles?  This would be important for any long-term use of ceph-ansible, since otherwise you can only use it at first install and never use it again.  I have some ideas if you are interested.

**Comment by SamYaple** [comment]
Generating the ceph-conf in one pass is doable, but i dont think that solves the issue youre having nor the question you are asking.

**Comment by ksingh7** [comment]
Hitting exact same issue

```
#  ansible-playbook site.yml -l ceph-rgw1

TASK: [ceph.ceph-common | generate ceph configuration file] ******************* 
fatal: [ceph-rgw1] => One or more undefined variables: 'dict object' has no attribute 'ansible_ens20f0'

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/root/site.retry

ceph-rgw1                  : ok=58   changed=2    unreachable=1    failed=0   
```
@leseb @SamYaple @bengland2 managed to get this working as of now but this needs fix

**Comment by ksingh7** [comment]
Hey, i managed to get this fixed by caching facts. Tested that and worked fine

```
# ansible-playbook site.yml -l ceph-rgw2
............
NOTIFIED: [ceph.ceph-common | restart ceph rgws with systemd] ***************** 
skipping: [ceph-rgw2]

PLAY [restapis] *************************************************************** 
skipping: no hosts matched

PLAY [rbdmirrors] ************************************************************* 
skipping: no hosts matched

PLAY [clients] **************************************************************** 
skipping: no hosts matched

PLAY RECAP ******************************************************************** 
ceph-rgw2                  : ok=79   changed=17   unreachable=0    failed=0   

```
@leseb i can send PR if you like

**Comment by bengland2** [comment]
This is great, I didn't see how to do it.   The problem with ceph-ansible is that people may not always realize that they need RGW or RBD or Cephfs at the time they install the cluster, and may not know which hosts or how many are needed.   The more independently the different components can be installed, the better right?  In theory, ansible playbooks are supposed to do things idempotently, which would make this possible, but in practice that's hard to do.

**Comment by leseb** [comment]
@bengland2 playbook are idempotent so replaying the entire book is fine, it's just takes a bit more time.
@ksingh7 if you have a fix, please send a PR :)

**Comment by ksingh7** [comment]
@leseb @bengland2 what are your thoughts on this https://github.com/ceph/ceph-ansible/pull/834/commits/01ea0dca76adfaa1bcf19c7eadc5a9fc74491109

This fix works , but not very sure how does the caching thing behaves in a long run.

**Comment by SamYaple** [comment]
@ksingh7 I am not a fan of caching because of the potential for stale caches. This can be fixed in a slightly different manner. The caching is a great workaround for this common issue though. Maybe it can be implemented with a note to remove when the playbooks are restructured?

**Comment by ksingh7** [comment]
@SamYaple 100% agree with you.
Caching is not the smartest way to fix this, but it can be our ducktape as of now.

**Comment by bengland2** [comment]
Sorry I've been gone for so long.  Let me recap what I heard people saying, see if I got it right.  The best way to solve this problem is not to use "-l rgws" at all.  Instead, just add the [rgws] section to the inventory file.  Since ceph-ansible is idempotent, it won't alter the mons or OSDs and will just add the gateways.    I'll try that, if it works then I consider the problem resolved.

**Comment by leseb** [comment]
You can now use the rgw playbook  `rgw-standalone.yml` as directly like this:

`ansible-playbook rgw-standalone.yml \
--extra-vars '{"radosgw_civetweb_bind_ip":"0.0.0.0","radosgw_civetweb_port":"7480","ansible_hostname":"node-test"}'`
