### ISSUE TITLE
Non-containerized node-exporter

### ISSUE THREAD

**Issue by rdavyd** [ceph/ceph-ansible#6741]
**Is your feature request related to a problem? Please describe.**
Non-containerized deployment still uses docker to install node-exporter if dashboard is enabled. Which in turn adds unwanted iptables rules and runs `dockerd` useless extra daemon. Some HCI hypervisors (with OSDs) should have zero rules in iptables.

**Describe the solution you'd like**
Modify `ceph-node-exporter` role to install node-exporter daemon non-container version if `containerized_deployment` is set to `false`

Should I submit a PR?

**Comment by dsavineau** [comment]
it has been decided to deploy the monitoring stack with containers only by design (even if containerized_deployment is set to false).

> Should I submit a PR?

I'm afraid this won't be accepted.
