### ISSUE TITLE
shrink-mgr playbook issue

### ISSUE THREAD

**Issue by jeevadotnet** [ceph/ceph-ansible#6796]
**Bug Report**

**What happened:**
playbook complaining that one of the controllers are not found and stops the playbook

**What you expected to happen:**
MGR to be successfully removed in line with shrink-mon & shrink-mds ansible playbooks
I have to manually remove it at the moment

**How to reproduce it (minimal and precise):**
` ansible-playbook -vvv -e 'ansible_python_interpreter=/usr/bin/python3' -i inventory infrastructure-playbooks/shrink-mgr.yml -e mgr_to_kill=B-01-34-cephctl.maas`

**Share your group_vars files, inventory and **full** ceph-ansibe log**
ansible log: http://pastefile.fr/4693fcd95540aff76a2817485ad4d4a8
vars: http://pastefile.fr/3100356e4d9e53d76216cf709cdf0d85
inventory: http://pastefile.fr/27ccf7c6ce24ae669b5028cfad4a3599

**Environment**:
* OS (e.g. from /etc/os-release): `Ubuntu 18.04.5 LTS"`
* Kernel (e.g. `uname -a`): `Linux ilifu-mgmt 5.4.0-74-generic #83~18.04.1-Ubuntu SMP Tue May 11 16:01:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
* Docker version if applicable (e.g. `docker version`): `20.10.2`
* Ansible version (e.g. `ansible-playbook --version`): `ansible-playbook 2.9.0`
* ceph-ansible version (e.g. `git head or tag or stable branch`): `stable 5.0`
* Ceph version (e.g. `ceph -v`): `15.2.12`

**Comment by dsavineau** [comment]
> ceph-ansible version (e.g. git head or tag or stable branch): stable 5.0

Could you give more detail on the commit/tag on that branch ?

Because I'm pretty sure this has been already fixed by [1] which included with the updated stable-5.0 branch and the v5.0.8 tag

[1] https://github.com/ceph/ceph-ansible/commit/fe2e057b51edec62f99d4c9f5b389b5dffe053ed

**Comment by jeevadotnet** [comment]
Hi @dsavineau 

```cat .git/HEAD
ref: refs/heads/stable-5.0
```

**Comment by dsavineau** [comment]
that doesn't tell me the commit sha1 you're using.

Being on your local stable-5.0 branch doesn't mean it has been updated.

**Comment by jeevadotnet** [comment]
```
git rev-parse HEAD
a1cefe886be52edaeb98935e525c28ccf11530c6
```

**Comment by dsavineau** [comment]
```console
# git log --oneline a1cefe886be52edaeb98935e525c28ccf11530c6..upstream/stable-5.0 |wc -l
147
```

You have 147 commits missing compared to the upstream stable-5.0 branch

```console
$ git log --oneline a1cefe886be52edaeb98935e525c28ccf11530c6..upstream/stable-5.0 |grep shrink-mgr
fe2e057b5 shrink-mgr: modify existing mgr check
```

Please update your stable-5.0 branch.

**Comment by jeevadotnet** [comment]
Ah ok, I didn't even know about this.

Now on:

```
git rev-parse HEAD
bcf9a2c25e76581ee750f9a1b6b1a6878e7c9cdf
```
