### ISSUE TITLE
"you must add a monitoring group and add at least one node" message also if monitoring group is declared

### ISSUE THREAD

**Issue by fpiraneo** [ceph/ceph-ansible#6809]
What happened:
While installing ceph pacific on CentOS Stream 8 got:

`TASK [ceph-validate : fail if monitoring group doesn't exist] ******************************************************************************************************************************************************************************
Monday 09 August 2021  17:03:38 +0200 (0:00:00.258)       0:01:08.263 ********* 
fatal: [mon1]: FAILED! => changed=false 
  msg: you must add a monitoring group and add at least one node.
fatal: [mon2]: FAILED! => changed=false 
  msg: you must add a monitoring group and add at least one node.
fatal: [mon3]: FAILED! => changed=false 
  msg: you must add a monitoring group and add at least one node.
fatal: [osd1]: FAILED! => changed=false 
  msg: you must add a monitoring group and add at least one node.
fatal: [osd2]: FAILED! => changed=false 
  msg: you must add a monitoring group and add at least one node.
fatal: [osd3]: FAILED! => changed=false 
  msg: you must add a monitoring group and add at least one node.`

However in `hosts` following has been declared:

`[mons]
mon1
mon2
mon3

[mgrs]
mon1

[osds]
osd1
osd2
osd3

[ceph:children]
mons
osds
mgrs`

What you expected to happen:

Ceph infrastructure installed correctly or more informations to debug like: What is expected to configure and a reference to the documentation.

How to reproduce it (minimal and precise):
Contact me for more.

Share your group_vars files, inventory and **full** ceph-ansibe log - Contact me with precise questions

**Environment**:
* CentOS Stream release 8
* Kernel (e.g. `uname -a`): Linux ansible 4.18.0-326.el8.x86_64 #1 SMP Wed Jul 28 21:21:05 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* Docker version if applicable (e.g. `docker version`): NA
* Ansible version (e.g. `ansible-playbook --version`): 

ansible-playbook 2.9.23
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/etc/ansible/library']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 3.6.8 (default, Jul 15 2021, 15:17:46) [GCC 8.5.0 20210514 (Red Hat 8.5.0-2)]

* ceph-ansible version (e.g. `git head or tag or stable branch`): stable
* Ceph version (e.g. `ceph -v`): pacific

**Comment by dsavineau** [comment]
> Ceph infrastructure installed correctly or more informations to debug like: What is expected to configure and a reference to the documentation.

I don't know what you want more.

The message seems pretty clear. You need to have a `monitoring` group declared in your ansible inventory due to the `dashboard_enabled` variable set to true by default.

If you want the Ceph dashboard+monitoring deployed then add something in your ansible inventory like

```yaml
[monitoring]
mon1
```

Or just disable the Ceph dashboard+monitoring installation in your group_vars.

```yaml
dashboard_enabled: false
```

**Comment by fpiraneo** [comment]
@dsavineau Is there any comments or documentation point that clearly underline this prerequisite?

**Comment by fpiraneo** [comment]
@dsavineau Another way to rise an error: "Please declare a [monitoring] group in your inventory file or set dashboard_enabled = false; checkout point 3.22 of documentation" ;-)

Ah documentation: If it was hard to write it must be hard to understand!

**Comment by dsavineau** [comment]
> @dsavineau Another way to rise an error: "Please declare a [monitoring] group in your inventory file or set dashboard_enabled = false; checkout point 3.22 of documentation" ;-)
> 
> Ah documentation: If it was hard to write it must be hard to understand!

Any PR are welcomed ;)

**Comment by cybercoder** [comment]
Add one grafana node to your groups.
```It is creating monitor node base on grafana!```
