### ISSUE TITLE
RBD client admin socket path created twice

### ISSUE THREAD

**Issue by stpierre** [ceph/ceph-ansible#687]
The RBD client admin socket path is created multiple different times in wildly divergent ways:

https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-common/tasks/installs/install_on_redhat.yml#L150-L160
https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-common/tasks/installs/install_on_debian.yml#L49-L59
https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-common/tasks/main.yml#L203-L209

The first two create it only if `rbd_client_directories` is true (it's false by default), with a configurable user/group (`qemu:libvirtd` by default), and with 0755 permissions. The third always creates it, uses an unconfigurable user/group (`ceph:ceph` on infernalis, `root:root` otherwise), and different permissions (`0770` on infernalis, `1777` otherwise). I'd be happy to fix this mess, but I have no idea which is correct (or if the actual correct option is some mish-mash of the two). The first two also create `rbd_client_log_path` with the same metadata, which also may or may not be correct.

**Comment by leseb** [comment]
Thanks for bringing this one up, depending on the usage it is a little bit complex though. Using it on OpenStack we want QEMU to have the right permissions for those directories. I think both socket and logs and vital for production. Level can be configured so it will ease debugging.

At the same time, we want regular users to be able to run `ceph`, `rbd`, `rados` commands too without having permissions errors. Those errors are harmless but they might just be confusing at some point.

I think the right approach would be to disable the creation of the directories by default. Permissions (owner, mode, group) should be configurable. Ideally we would provide some guidance as well regarding the right usage/permissions of those.
I think we should keep this in the main.yml and remove the debian and redhat ones.

Is it enough to start a PR?

**Comment by jdurgin** [comment]
relatedly, the admin socket and log path will fail with selinux enforcing since the rbd_client directory isn't labelled.

Is a subdir of /var/{log,run}/ceph necessary? why not use /var/{log,run}/ceph/$cluster-$name.$pid.$cctid.{log,asok}?

**Comment by leseb** [comment]
@jdurgin the subdir is not mandatory, I just thought a directory was cleaner since I was running some of my tests on devstack (thus mixing ceph daemon sockets and client sockets). I just realised that in a real life scenario `/var/{log,run}/ceph` is on the hypervisor so it will only contain guests sockets/logs.
Later we just need to set the proper permission on  `/var/{log,run}/ceph` for qemu to write.

**Comment by jdurgin** [comment]
@leseb yeah good point about qemu permissions - the subdir itself isn't an issue I don't think, we just need to set the proper perms and selinux settings to let qemu or other ceph-using processes write to it. e.g. nova or cinder or glance could ideally also access it
