### ISSUE TITLE
ceph --cluster cluster osd stat -f json parses wrong output

### ISSUE THREAD

**Issue by pertoft** [ceph/ceph-ansible#6870]
**Bug Report**
The task https://github.com/ceph/ceph-ansible/blob/f2bd8ae70f0ae5d0c7c7a36bd6ecdad6383feed9/roles/ceph-osd/tasks/main.yml#L87 parses output from "ceph --cluster cluster osd stat -f json" wrong.
It appears that the commit https://github.com/ceph/ceph-ansible/commit/b9cb0f12e9e79600f1a974dd88ba1ed1d833211f changed to ceph osd stats, and some of the checks were later removed.

I have tested in main branch, stable-4.0 and stable-5.0 branch and they all are affected by the same error.

What happened:
When upgrading form nautilus to octopus, with the stable-5.0 branch, the mons are running nautilus during the first check, and the playbook fails, as the output from osd stats on nautilus is different from octopus. 

````
TASK [ceph-osd : wait for all osd to be up] ***********************************************************************************************************************************************************************************
Monday 06 September 2021  15:46:15 +0200 (0:00:00.045)       0:06:47.097 ******
fatal: [ceph-osd03.test.netic.dk -> ceph-mon01.test.netic.dk]: FAILED! =>
  msg: 'The conditional check ''(wait_for_all_osds_up.stdout | from_json)["num_osds"] | int > 0'' failed. The error was: error while evaluating conditional ((wait_for_all_osds_up.stdout | from_json)["num_osds"] | int > 0): ''dict object'' has no attribute ''num_osds'''
````

What you expected to happen:
Upgrade of ceph to complete
How to reproduce it (minimal and precise):
Checkout master or stable-4.0 branch and run rolling upgrade play.

Share your group_vars files, inventory and **full** ceph-ansibe log

**Environment**:

* OS (e.g. from /etc/os-release): Ubuntu 20.04 LTS
* Kernel (e.g. `uname -a`): Linux ceph-master01 4.15.0-115-generic #116-Ubuntu SMP Wed Aug 26 14:04:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Docker version if applicable (e.g. `docker version`): N/A
* Ansible version (e.g. `ansible-playbook --version`):
root@ceph-master01:~# ansible-playbook --version
ansible-playbook 2.9.13
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.17 (default, Feb 27 2021, 15:10:58) [GCC 7.5.0]
root@ceph-master01:~# ceph-ansible version (e.g. `git head or tag or stable branch`):
* Ceph version (e.g. `ceph -v`):
ceph version 14.2.22 (ca74598065096e6fcbd8433c8779a2be0c889351) nautilus (stable)

**Comment by guits** [comment]
> When upgrading form nautilus to octopus, with the stable-5.0 branch, the mons are running nautilus during the first check

the mon should be running octopus at this point
