### ISSUE TITLE
fsid generation for docker deployment

### ISSUE THREAD

**Issue by leseb** [ceph/ceph-ansible#689]
We need to find a proper way to set a UUID, so we can avoid this error:

```
TASK [ceph-mon : generate ceph configuration file] *****************************

fatal: [mon0]: FAILED! => {"failed": true, "msg": "'dict object' has
no attribute 'stdout'"}
```

**Comment by ivotron** [comment]
@leseb We're currently experiencing this issue. If you have time, can you please suggest a workaround?

**Comment by leseb** [comment]
@ivotron simple workaround is to add `fsid: c41b5d3d-f508-4e3a-bf6c-aa0744c030d4` in your `group_vars/all`.

**Comment by ivotron** [comment]
cool, thanks!
