### ISSUE TITLE
Question: Is incremental addition of mons/osds supported?

### ISSUE THREAD

**Issue by vvb** [ceph/ceph-ansible#690]
scenario 1:
I start with the below inventory file, and things work great. I end up with one cluster with 2 mons in it.

```
[mons]
node1
node2
```

scenario2:
I do the same, but one node at a time. I end up with a split brain scenario (or so I think). `ceph -s` shows only 1 mon in each of the nodes. The cluster ids, fsid are same for both nodes.

run1: 
```
[mons]
node1
```
run2:
```
[mons]
node2
```
Questions:
1. Is scenario 2 supported by the present ansible workflow?
2. I see that we don’t set `mon_initial_members` - Would that be causing the split brain in scenario 2 above.
3. As per ceph documentation, monmap needs to be specified while adding a new mon node. I don’t see any logic in the existing workflow for monmaps (except some docker related tasks which have it)

note: everything stated above is in context of non-containerised scenarios.

**Comment by bdastur** [comment]
I have definitely validated incremental additions of osds. But I would think mons should work as well.

In your scenario two, run2 should have both the mon nodes  and not just the new node you are adding.

[mons]
node1
node2

**Comment by leseb** [comment]
Yes incremental monitors/osds addition is supported.
run 1 is correct but run2 should be:

```
[mons]
node1
node2
```

Then node2 will be added to the other monitor.

**Comment by vvb** [comment]
@bdastur @leseb I have verified that run2 having both nodes works. What I am not sure about is if we really need to specify both nodes there. 
As per the documentation at http://docs.ceph.com/docs/master/rados/operations/add-or-rm-mons/ , while adding second mon, there were no operations done to pre-existing mons. I might be missing something

**Comment by leseb** [comment]
When we add node2 to the mon section we just build a proper ceph.conf for node2 to refer to.
Basically when you say:

```
[mons]
node1
node2
```

Your ceph.conf will be populated with 2 monitors subsections. When the second monitor will be bootstrapped it will then be able to refer to the node1 to find all the necessary information to join the cluster. So we don't do anything on node1. We just need to it to build a correct ceph.conf.

Is this clearer now? If so feel free to close this :)

**Comment by vvb** [comment]
@leseb 
one last follow up question, updating ceph.conf on node1 during run2 - won't it then require a restart of ceph services and hence be disruptive?

**Comment by leseb** [comment]
@vvb yes changing the `ceph.conf` will trigger a restart of the ceph-mon services. However the restart will happen at the end of play, so yes it'll be disruptive but just for a couple of seconds.
Perhaps it is time, to switch and use `mon_initial_members` instead of creating sections...

**Comment by vvb** [comment]
@leseb @bdastur thanks for clarifying. I will go ahead and close this issue now.

**Comment by leseb** [comment]
Thanks!
