### ISSUE TITLE
Should be able to use ceph config instead of /etc/ceph/ceph.conf for some options

### ISSUE THREAD

**Issue by GillesMocellin** [ceph/ceph-ansible#6949]
**Is your feature request related to a problem? Please describe.**
Changing global configuration like osd deep scrub interval needs restarting all OSD.
Instead, we can use the Dashboard or `ceph config` to set it at once, without restarting the daemons.

**Describe the solution you'd like**
I'd like to be able to use ceph config in ceph-ansible, to have a unique central point of configuration.

**Describe alternatives you've considered**
One alternative is not to use ceph-ansible, but we will lose the central source of truth.

**My env**
I'm with Octopus an Ubuntu 18.04, ceph-ansible stable-5.0.

**Comment by guits** [comment]
@GillesMocellin ideally we should drop the `ceph.conf` usage and use `ceph config` instead but that would need significant changes.
PR are welcome... 🙂
