### ISSUE TITLE
ERROR! module is missing interpreter line

### ISSUE THREAD

**Issue by vvb** [ceph/ceph-ansible#695]
Seeing the following failure while running `vagrant provision`
```
TASK [ceph.ceph-common : generate ceph configuration file] *********************
fatal: [mon0]: FAILED! => {"failed": true, "msg": "ERROR! module is missing interpreter line"}
```

```
�  ceph-ansible git:(master) � cat ansible.cfg
[defaults]
ansible_managed = Please do not change this file directly since it is managed by Ansible and will be overwritten
action_plugins = plugins/actions
�  ceph-ansible git:(master) �
```

I have tried adding `#!/usr/bin/env python` to all the files in `plugins/actions` and `roles/ceph-common/plugins/actions`

also verified that the ansible.cfg has `plugins/actions` specified. tried changing it to `roles/ceph-common/plugins/actions`

But I still see the issue..

```
Python 2.7.8
ansible 2.0.0.2
```

Update:
I added `#!/usr/bin/python` to `library/config_template`. Now I get a different error in the same task,

```
fatal: [mon0]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "config_template"}, "module_stderr": "OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: auto-mux: Trying existing master
debug2: fd 3 setting O_NONBLOCK
debug2: mux_client_hello_exchange: master version 4
debug3: mux_client_forwards: request forwardings: 0 local, 0 remote
debug3: mux_client_request_session: entering
debug3: mux_client_request_alive: entering
debug3: mux_client_request_alive: done pid = 18664
debug3: mux_client_request_session: session request sent
debug1: mux_client_request_session: master session id: 2
debug3: mux_client_read_packet: read header failed: Broken pipe
debug2: Received exit status from master 0
Shared connection to 127.0.0.1 closed.
", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}
```

**Comment by vvb** [comment]
I have tried adding `#!/usr/bin/env python` to all the files in `plugins/actions` and `roles/ceph-common/plugins/actions`

also verified that the ansible.cfg has `plugins/actions` specified. tried changing it to `roles/ceph-common/plugins/actions`

But I still see the issue..

```
Python 2.7.8
ansible 2.0.0.2
```

**Comment by leseb** [comment]
You're setup looks good. I'm not sure what's happening, @cloudnull do you have any idea?

**Comment by cloudnull** [comment]
I've not specifically seen this issue. However I can look into it later today.

**Comment by cloudnull** [comment]
I have no idea what could've caused the error at this point. While code diving I found an issue with the action plugin that is 2.0.0.0 specific when using the multi-string-op type it wasn't (PR to fix in-bound) something that caused a stracktrace. @vvb might you be able to share the ``config_template`` options that your passing in? If it's something in the settings that's causing the problem and I can account for the issues I'm happy to fix it though right now I'm at a loss as to what could be the problem.

On another note, have you tried a different version of Ansible (1.9.5, 2.0.1.0)?

**Comment by cloudnull** [comment]
This is the PR to resolve the issue mentioned previously https://github.com/ceph/ceph-ansible/pull/707 -- @vvb you can try and pull in those changes to see if they resolve your issue though I'm not sure they will based on the provided information.

I tested using the following data as my overrides:

``` yaml
test_config_override_structure:
  DEFAULT:
    str_op: test
    int_op: 1234
    list_int_op:
      - 1
      - 2
      - 3
      - 4
    list_str_op:
      - a
      - b
      - c
      - d
    multi_str_op:
      ? a
      ? b
      ? c
      ? d
    multi_int_op:
      ? 1
      ? 2
      ? 3
      ? 4
```

Which produced as expected: 
``` ini
[DEFAULT]
multi_str_op = a
multi_str_op = c
multi_str_op = b
multi_str_op = d
int_op = 1234
list_str_op = a,b,c,d
multi_int_op = 1
multi_int_op = 2
multi_int_op = 3
multi_int_op = 4
list_int_op = 1,2,3,4
str_op = test
```

Tests were run w/ ansible 1.9.5, 2.0.0.2, 2.0.1.0, 2.1.0(devel)

**Comment by vvb** [comment]
@cloudnull will update, test and get back.

**Comment by alfredodeza** [comment]
we have seen the "missing interpreter line" issue when running from a directory other than the `ceph-ansible/`

**Comment by vvb** [comment]
@cloudnull I tested with the diff in #707 , I still hit the same issue.

As for the `ceph_conf_overrides` that I am using, I am using the same dummy values that were originally commented in the existing code
```
+ceph_conf_overrides:
+  global:
+    foo: 1234
+    bar: 5678
+
+#ceph_conf_overrides: {}
```

@alfredodeza I am running `vagrant provision` from `ceph-ansible` directory only.

**Comment by vvb** [comment]
ah! I found the issue. so, I had earlier followed http://www.sebastien-han.fr/blog/2014/03/03/Announcing-ceph-ansible-playbooks/ once. and as a result the ANSIBLE_CONFIG was set to something else. I set it back to the ansible.cfg in the ceph-ansible directory and it got past that stage. 

sorry, for wasting time :-(

**Comment by cloudnull** [comment]
@vvb no time waisted at all it in fact it was this conversation that lead me to find an issue with a module our projects share so IMHO it was quite productive. Regardless I'm glad the issue got sorted. Cheers.

**Comment by wallnerryan** [comment]
im actually still seeing this, trying to follow something like http://www.sebastien-han.fr/blog/2014/03/03/Announcing-ceph-ansible-playbooks/  form outside the ceph-ansible directory. I want to do this because I have other installation files I want to use. 

1. is that link outdated?
2. is it possible to run outside the ceph-ansible dir.

**Comment by leseb** [comment]
@wallnerryan yes it is possible, you can use the ansible galaxy if you want.
Just follow the instructions here: https://github.com/ceph/ceph-ansible/tree/master/roles/ceph-common#requirements

**Comment by hanynowsky** [comment]
same error here for module FILE.
Fixed if I CD to /etc/ansible.
