### ISSUE TITLE
fail on unsupported distribution Astra Linux

### ISSUE THREAD

**Issue by vldanch** [ceph/ceph-ansible#6989]
**Bug Report**

What happened:
```
TASK [ceph-validate : fail on unsupported distribution] **********************************************************************************************fatal: [192.168.1.50]: FAILED! => {"changed": false, "msg": "Distribution not supported Astra Linux (Smolensk)"}
```
**Environment**:
* OS: Astra Linux (Smolensk 1.6)
* Kernel: 4.15.3-1-generic
* Ansible version: ansible-playbook 2.6.20
* ceph-ansible version: stable-3.2
* Ceph version: ceph version 12.2.13, luminous (stable)

**Comment by guits** [comment]
What is the issue then? I think the error is pretty self-explanatory... ceph-ansible doesn't support Astra Linux :man_shrugging: 
(By the way, stable-3.2/luminous are EOL.)

**Comment by vldanch** [comment]
@guits and when will they add support?

**Comment by guits** [comment]
@vldanch unfortunately, this is very unlikely to happen.
ceph-ansible is going to be deprecated.
please, take a look at https://docs.ceph.com/en/pacific/install/#recommended-methods
