### ISSUE TITLE
Ansible script fails to complete on SUSE

### ISSUE THREAD

**Issue by james4765** [ceph/ceph-ansible#6996]
**Bug Report**

What happened:
On running the script to install on SLES 15.3, received an error from ceph-validate that 'obs' is not a valid ceph_repository.

What you expected to happen:
Script should complete.

How to reproduce it (minimal and precise):

Share your group_vars files, inventory and **full** ceph-ansibe log

**Environment**:
* OS (e.g. from /etc/os-release):
scvadmin:/opt/ansible # cat /etc/os-release
NAME="SLES"
VERSION="15-SP3"
VERSION_ID="15.3"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP3"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp3"
DOCUMENTATION_URL="https://documentation.suse.com/"

* Kernel (e.g. `uname -a`):
scvadmin:/opt/ansible # uname -a
Linux scvadmin 5.3.18-59.27-default #1 SMP Tue Oct 5 10:00:40 UTC 2021 (7df2404) s390x s390x s390x GNU/Linux

* Docker version if applicable (e.g. `docker version`):

* Ansible version (e.g. `ansible-playbook --version`):
scvadmin:/opt/ansible # ansible-playbook --version
ansible-playbook 2.9.27
  config file = /opt/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible/plugins/modules', '/opt/ansible/plugins/modules']
  ansible python module location = /opt/ansible2.9/lib64/python3.6/site-packages/ansible
  executable location = /opt/ansible2.9/bin/ansible-playbook
  python version = 3.6.13 (default, Mar 10 2021, 18:30:35) [GCC]

* ceph-ansible version (e.g. `git head or tag or stable branch`):
stable-6.0 (also happens in master)

* Ceph version (e.g. `ceph -v`):

**Comment by james4765** [comment]
[ceph-ansible.patch.txt](https://github.com/ceph/ceph-ansible/files/7540031/ceph-ansible.patch.txt)

This is the change I made to complete my test install. With this change, I was able to complete the installation.

**Comment by james4765** [comment]
Ansible log:

[ceph-ansible-failure-2021-11-15.txt](https://github.com/ceph/ceph-ansible/files/7540083/ceph-ansible-failure-2021-11-15.txt)

Inventory:
[hosts.yaml.txt](https://github.com/ceph/ceph-ansible/files/7540096/hosts.yaml.txt)

group_vars/:
[all.yaml.txt](https://github.com/ceph/ceph-ansible/files/7540104/all.yaml.txt)

**Comment by guits** [comment]
@james4765 do you mind sending a PR since you already have the patch? Thanks!
