### ISSUE TITLE
Ceph depolyment failing during ceph-common package installation due to selinux-policy-base package missing

### ISSUE THREAD

**Issue by Dannyb48** [ceph/ceph-ansible#7001]
**Bug Report**

What happened:

My team has been using ceph-ansible to provision a ceph cluster on RHEL-8.4 OpenStack Instances. This has been working fine for a couple months now and then some time mid last week it started failing with the following errors

```
2021-11-22 21:01:40,027 INFO - 'changed: [10.0.114.71]'
2021-11-22 21:01:40,027 INFO - 'fatal: [10.0.114.53]: FAILED! => changed=false '
2021-11-22 21:01:40,027 INFO - '  attempts: 3'
2021-11-22 21:01:40,027 INFO - '  failures: []'
2021-11-22 21:01:40,027 INFO - '  msg: |-'
2021-11-22 21:01:40,027 INFO - '    Depsolve Error occured:'
2021-11-22 21:01:40,028 INFO - '     Problem: package ceph-mon-2:14.2.11-208.el8cp.x86_64 requires ceph-base = 2:14.2.11-208.el8cp, but none of the providers can be installed'
2021-11-22 21:01:40,028 INFO - '      - package ceph-base-2:14.2.11-208.el8cp.x86_64 requires ceph-selinux = 2:14.2.11-208.el8cp, but none of the providers can be installed'
2021-11-22 21:01:40,028 INFO - '      - cannot install the best candidate for the job'
2021-11-22 21:01:40,028 INFO - '      - nothing provides selinux-policy-base >= 3.14.3-80.el8 needed by ceph-selinux-2:14.2.11-208.el8cp.x86_64'
2021-11-22 21:01:40,028 INFO - '  rc: 1'
``` 

This happens for all the cluster components. Here is the enabled repolist for the mon as an example
```
[cloud-user@psi-c0-osp16-test-decepticon-ceph-mon-1 ~]$ sudo dnf repolist
Updating Subscription Management repositories.
repo id                                                                                         repo name
rhceph-4-mon-for-rhel-8-x86_64-rpms                                                             Red Hat Ceph Storage MON 4 for RHEL 8 x86_64 (RPMs)
rhceph-4-tools-for-rhel-8-x86_64-rpms                                                           Red Hat Ceph Storage Tools 4 for RHEL 8 x86_64 (RPMs)
rhel-8-for-x86_64-appstream-rpms                                                                Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs)
rhel-8-for-x86_64-baseos-rpms                                                                   Red Hat Enterprise Linux 8 for x86_64 - BaseOS (RPMs)

```

There is no package called **selinux-policy-base** ONLY **selinux-policy**

What you expected to happen:

The cluster deployment to complete successfully

How to reproduce it (minimal and precise):

- Install RHEL-8.4
- Enabled the rh-ceph-4 repos
- Enable the AppStream and BaseOS repos
- Install ceph-ansible from the rhceph-4-tools repo on adm
- Use the default site.yml that comes with ceph-ansible
- 
[ansible.log](https://github.com/ceph/ceph-ansible/files/7589004/ansible.log)

Share your group_vars files, inventory and **full** ceph-ansibe log

**Environment**:
* OS (e.g. from /etc/os-release):
```
Red Hat Enterprise Linux release 8.4 (Ootpa)
```
* Kernel (e.g. `uname -a`):
```
Linux 4.18.0-305.7.1.el8_4.x86_64 #1 SMP Mon Jun 14 17:25:42 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux
```
* Docker version if applicable (e.g. `docker version`):
* Ansible version (e.g. `ansible-playbook --version`):
```
ansible 2.9.27
```

* ceph-ansible version (e.g. `git head or tag or stable branch`):
```
Installed Packages
ceph-ansible.noarch                                                                     4.0.62.8-1.el8cp                                                                     @rhceph-4-tools-for-rhel-8-x86_64-rpms
```
* Ceph version (e.g. `ceph -v`):

**Comment by guits** [comment]
I suspect this is only an issue with your environment.
In any case, this is not the right place, you should open a BZ instead of an upstream github issue for this.
Do you mind opening a BZ instead? thanks!
