### ISSUE TITLE
Add EuroLinux as supported Distro

### ISSUE THREAD

**Issue by EuroTesty** [ceph/ceph-ansible#7020]
**Is your feature request related to a problem? Please describe.**
The problem is that ansible is not working with EuroLinux distribution

**Describe the solution you'd like**
Add EuroLinux as supported distribution

**Describe alternatives you've considered**
I didn't found any alternative

**Additional context**
EuroLinux is a distribution which is 100% based on RedHat. ( https://en.euro-linux.com/ )
I've made some test and the ansbile and rpm used inside are 100% working with EuroLinux (as it is a RedHat family OS). EuroLinux is a CentOs equivalent for some part of the marked and it would be nice and handy to have a Ceph-Ansible supported installation on it.
As I've mentioned before to install ceph on ELL we need the same path as for RedHat. The only needed thing is to add EuroLinux as supported os_family / os_distribution to all Cephs services.

**Comment by guits** [comment]
@EuroTesty there's no plan at the moment for supporting this distro.

That being said, PR are welcome 🙂
