### ISSUE TITLE
NFS-ganesha Debian packages not available?

### ISSUE THREAD

**Issue by rjzak** [ceph/ceph-ansible#7031]
**Bug Report**

What happened: ceph-ansible cannot install nfs-ganesha on Ubuntu 20.04

```
Ign:6 https://download.ceph.com/nfs-ganesha/deb-V3.5-stable/pacific focal InRelease
Err:7 https://download.ceph.com/nfs-ganesha/deb-V3.5-stable/pacific focal Release
  404  Not Found [IP: 158.69.68.124 443]
Hit:8 http://ppa.launchpad.net/ansible/ansible/ubuntu focal InRelease
Reading package lists... Done
E: The repository 'https://download.ceph.com/nfs-ganesha/deb-V3.5-stable/pacific focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

Turns out, the URL for nfs-ganesha does not exist on the server. https://download.ceph.com/nfs-ganesha/deb-V3.5-stable/pacific

What you expected to happen: Install nfs-ganesha .deb files on supported distro Ubuntu 20.04

How to reproduce it (minimal and precise): In my ansible host file:

    [nfss]
    10.10.10.10 # whatever my IP is for this service

Ceph is installed and running on the cluster. Just can't find debian packages.

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 20.04.3 LTS
* Kernel (e.g. `uname -a`): Linux ceph1 5.4.0-91-generic # 102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* Docker version if applicable (e.g. `docker version`): 20.10.7
* Ansible version (e.g. `ansible-playbook --version`): 2.9.6
* ceph-ansible version (e.g. `git head or tag or stable branch`): pacific
* Ceph version (e.g. `ceph -v`): 16.2.7

**Comment by prathamaror** [comment]
I think i have a pretty good idea about this should I start working on this I have some questions prior

**Comment by rjzak** [comment]
What are your questions? I'm surprised that it has the RPM packages but not DEB for the latest version (but has old DEB for prior releases of Ceph).

**Comment by guits** [comment]
Actually, this has nothing to do with ceph-ansible.
Unfortunately, it looks like for some reason the Debian packages aren't built anymore after nautilus...

Have you tried to ask on the ML about that?

**Comment by rjzak** [comment]
I did ask the ML, no response. I'll try again. Thanks!

**Comment by guits** [comment]
I tried to get feedback internally (at redhat)... I've been unlucky as well... 🤷‍♂️

**Comment by rjzak** [comment]
Mailing list response: the components are to be containerised, so maybe Ceph-ansible needs to pull a Docker image for NFS-Ganesha instead of Debian packages.

**Comment by guits** [comment]
@rjzak on which mailing list have you asked?

**Comment by rjzak** [comment]
ceph-users. https://lists.ceph.io/hyperkitty/list/ceph-users@ceph.io/thread/HDI4GYRCPRC23NFVBID5XGO72UC5LPGD/
I received one response and it as directly to me. The response was: 

> The Ceph project now recommends containers and the orchestrator to not
have to build packages for all distributions.

**Comment by rjzak** [comment]
From victoria@redhat-dot-com on the [ceph-users mailing list](https://lists.ceph.io/hyperkitty/list/ceph-users@ceph.io/message/B22G3ZUZNOV5C45URGN2PUAOBF5EQVEF/):

> Hi all,
> 
> For OpenStack Manila CI we are using Ubuntu 20.04 LTS with the community
> PPAs [0].
> 
> For those users in RHEL based distros, we allow them to use the packages in
> download.ceph.com [1], but that is not being actively tested by our CI.
> 
> IIRC there are no builds for Ubuntu, CentOS or Fedora in [2] for the
> versions we are using (2.8 and 3.0), only instructions on where to get the
> packages.
> 
> Having said that, right now I don't think it wouldn't change too much for
> us if nfs-ganesha packages are no longer distributed on download.ceph.com.
> 
> That would impact our development environments tool, but we could fix it to
> point to the new repos.
> 
> Thanks,
> 
> V
> 
> [0]
> https://github.com/openstack/devstack-plugin-ceph/blob/stable/xena/devstack/lib/ceph#L1019-L1020
> [1]
> https://github.com/openstack/devstack-plugin-ceph/blob/stable/xena/devstack/lib/ceph#L928-L958
> [2] https://download.nfs-ganesha.org/

So it seems this issue should be re-opened, and either ceph-ansible uses different links for the nfs-ganesha packages, or removes nfs-ganesha functionality.

**Comment by guits** [comment]
@rjzak see #7053

**Comment by rjzak** [comment]
Thanks!!
