### ISSUE TITLE
The result is null when run the command "ceph orchestrator host ls".

### ISSUE THREAD

**Issue by xudehua** [ceph/ceph-ansible#7038]
**Bug Report**

What happened:
Deployed ceph 14.2.21cluster with ceph-ansible 6.0,and ceph-mgr-ssh-14.2.21-0.el8.noarch was installed.
set the ssh moudule by
  "ceph mgr module enable ssh"
  "ceph orchestrator set backend ssh"

add the ssh_config_file as the follows:
cat /root/.ssh/config
Host ceph01
  HostName 172.16.1.191
  User root
  Port 22
  UserKnownHostsFile /root/.ssh/known_hosts
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /root/.ssh/id_rsa
  IdentitiesOnly yes
  LogLevel FATAL
......  other nodes parameter in the cluster

ceph config set mgr mgr/ssh/ssh_config_file /root/.ssh/config

What you expected to happen:
Get the result is NULL ,when run the command "ceph orchestrator host ls".
and run the command "ceph orchestrator device ls {ceph01}"
error:
  File "/usr/share/ceph/mgr/orchestrator.py", line 946, in _oremote
    return mgr.remote(o, meth, *args, **kwargs)
  File "/usr/share/ceph/mgr/mgr_module.py", line 1381, in remote
    args, kwargs)
RuntimeError: Remote method threw exception: Traceback (most recent call last):
  File "/usr/share/ceph/mgr/ssh/module.py", line 450, in get_inventory
    self._require_hosts(hosts)
  File "/usr/share/ceph/mgr/ssh/module.py", line 211, in _require_hosts
    unregistered_hosts))))
RuntimeError: Host(s) '{ceph01}' not registered

How to reproduce it (minimal and precise):

ceph-ansible 6.0 created a ceph 14.2.21 cluster with 3*monitor, 3*manager, 3*osd in 3 nodes, and one client node .
 
Share your group_vars files, inventory and **full** ceph-ansibe log

**Environment**:
* OS (e.g. from /etc/os-release): centos 8
* Kernel (e.g. `uname -a`): 4.19.113-10
* Docker version if applicable (e.g. `docker version`):
* Ansible version (e.g. `ansible-playbook --version`):  2.9.21
* ceph-ansible version (e.g. `git head or tag or stable branch`): stable 6.0
* Ceph version (e.g. `ceph -v`): 14.2.21

**Comment by xudehua** [comment]
when run the "ceph orchestrator set backend test_orchestrator" command,then run 
"ceph orchestrator device ls" or "ceph orchestrator host ls"
it will display the localhost info and local devices.

**Comment by guits** [comment]
> **Bug Report**
> 
> What happened: Deployed ceph 14.2.21 cluster with ceph-ansible 6.0,and ceph-mgr-ssh-14.2.21-0.el8.noarch was installed. set the ssh moudule by "ceph mgr module enable ssh" "ceph orchestrator set backend ssh"

ceph-ansible stable-6.0 isn't intended for deploying ceph 14.2.21. I even wonder how you could do that actually.
you must use ceph-ansible stable-4.0 in order to deploy Ceph Nautilus (which is, by the way, EOL)

> What you expected to happen: Get the result is NULL ,when run the command "ceph orchestrator host ls". and run the command "ceph orchestrator device ls {ceph01}" error: File "/usr/share/ceph/mgr/orchestrator.py", line 946, in _oremote return mgr.remote(o, meth, *args, **kwargs) File "/usr/share/ceph/mgr/mgr_module.py", line 1381, in remote args, kwargs) RuntimeError: Remote method threw exception: Traceback (most recent call last): File "/usr/share/ceph/mgr/ssh/module.py", line 450, in get_inventory self._require_hosts(hosts) File "/usr/share/ceph/mgr/ssh/module.py", line 211, in _require_hosts unregistered_hosts)))) RuntimeError: Host(s) '{ceph01}' not registered

In any case, this has nothing to do with ceph-ansible.

Although I suspect you are facing an issue because of your setup/environment, you might want to open a tracker issue at https://tracker.ceph.com/ in the right component.

**Comment by xudehua** [comment]
@guits thanks for you reply. 
I changed some code for ceph-ansible stable-6.0 to deploy ceph 14.2.21

**Comment by guits** [comment]
> @guits thanks for you reply. I changed some code for ceph-ansible stable-6.0 to deploy ceph 14.2.21

🤮 

you are in an unsupported configuration, I don't see a good reason for doing that.
