### ISSUE TITLE
podman: deploy ceph cluster without pulling the container image(alertmanager,prometheus,grafana,node-exporter )

### ISSUE THREAD

**Issue by xudehua** [ceph/ceph-ansible#7056]
**Bug Report**
I deployed a ceph cluster with 'containerized_deployment: False',
but it will start docker when setting 'dashboard_enabled: True'.
it will pull container image from offical and start container(alertmanager,prometheus,grafana,node-exporter).

What happened:

What you expected to happen:

Is there a way to have four services running on the host instead of the docker.

How to reproduce it (minimal and precise):

Share your group_vars files, inventory and **full** ceph-ansibe log

**Environment**:
* OS (e.g. from /etc/os-release): centos8
* Kernel (e.g. `uname -a`): 4.19.113
* Docker version if applicable (e.g. `docker version`): podman version 1.6.4
* Ansible version (e.g. `ansible-playbook --version`): ansible 2.9.21
* ceph-ansible version (e.g. `git head or tag or stable branch`):  stable-4.0
* Ceph version (e.g. `ceph -v`): 14.2.22

**Comment by guits** [comment]
when using `containerized_deployment: False` it only applies to ceph cluster deployment, the dashboard is containerized anyway.
