### ISSUE TITLE
ERROR! couldn't resolve module/action 'openstack.config_template.config_template'.

### ISSUE THREAD

**Issue by captain120** [ceph/ceph-ansible#7060]
nonono

**Comment by duizhang996** [comment]
git clone https://github.com/ceph/ceph-ansible.git
cd ceph-ansible/
git checkout stable-5.0

--------------
$ ansible --version
ansible 2.10.16
  config file = /home/ansible/ceph-ansible/ansible.cfg
  configured module search path = ['/home/ansible/ceph-ansible/library']
  ansible python module location = /usr/local/python3.9.8/lib/python3.9/site-packages/ansible
  executable location = /bin/ansible
  python version = 3.9.8 (main, Jan 25 2022, 16:03:08) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]

----------------
$ python -V
Python 3.9.8
$ pip -V
pip 21.3.1 from /usr/local/python3.9.8/lib/python3.9/site-packages/pip (python 3.9)

**Comment by duizhang996** [comment]
How do I solve this problem with double quotes ?

**Comment by captain120** [comment]
nono

**Comment by moly7x** [comment]
Hello, I got this problem too. How did you solve it?

**Comment by Andre15711** [comment]
I also have the issue with this error message...... any solution in this?

**Comment by guits** [comment]
https://github.com/ceph/ceph-ansible/blob/master/docs/source/index.rst#ansible-collections
