### ISSUE TITLE
Support Rocky Linux

### ISSUE THREAD

**Issue by distributorofpain** [ceph/ceph-ansible#7100]
**Is your feature request related to a problem? Please describe.**
When gathering facts, it sees rocky as the OS family, then any tasks that depend on a family type, it just dies...

**Describe the solution you'd like**
add an os family identifier for "Rocky" in the tasks that specify suse and redhat 

**Describe alternatives you've considered**
Can override playbooks, but seems silly.

**Comment by RaminTorabi** [comment]
Beginning with Ansible 2.11 the `os_family` and `distibution` should be fixed within Ansible:
  https://forums.rockylinux.org/t/ansible-os-family-question/3320/8
but for ceph-ansible uses older versions of Ansible - even in the non-stable `master` branch.
Therefore I am also voting for adding Rocky to ceph-ansible.
Is there any way to overwrite or superseed some of the ansible_facts variables?

I changed 23 lines in my `stable-6.0` branch. Changes typically look like these
```
    - ansible_facts['os_family'] == 'RedHat'
    - ansible_facts['os_family'] in ['RedHat', 'Rocky']
```
or
```
  when: ansible_facts['distribution'] not in ['RedHat', 'CentOS', 'Fedora']
  when: ansible_facts['distribution'] not in ['RedHat', 'CentOS', 'Fedora', 'Rocky']
```
but a few Jinja2 templates are also affected and I created one softlink:
```
roles/ceph-container-engine/vars/Rocky.yml -> RedHat-8.yml
```

For restarting running ceph daemons I also had to change the conditionals. I am unsure if this is related to Rocky Linux.

**Comment by distributorofpain** [comment]
I used this to fix the top part:
`
sed -i "s/'RedHat',/'RedHat', 'Rocky',/g" /ceph-ansible/*.yml

find /ceph-ansible -type f -name '*.yml' -exec sed -i "s/'RedHat',/'RedHat', 'Rocky',/g" '{}' +
`

I did a search for the "when" statements and manually fixed those as well as create the linked file like they did that points to the redhat yml.    Havent had a chance to check my work though, the cluster i had for testing only had one monitor and apparently the new versions of ceph-ansible require 3.  Tried to hack my way around that but ran out of time.

**Comment by guits** [comment]
> Beginning with Ansible 2.11 the `os_family` and `distibution` should be fixed within Ansible: https://forums.rockylinux.org/t/ansible-os-family-question/3320/8 but ceph-ansible uses older versions of Ansible - even in the non-stable `master` branch. Therefore I am also voting for adding Rocky to ceph-ansible. Is there any way to overwrite or superseed some of the ansible_facts variables?
> 
> I changed 23 lines in my `stable-6.0` branch. Changes typically look like these
> 
> ```
>     - ansible_facts['os_family'] == 'RedHat'
>     - ansible_facts['os_family'] in ['RedHat', 'Rocky']
> ```
> 
> or
> 
> ```
>   when: ansible_facts['distribution'] not in ['RedHat', 'CentOS', 'Fedora']
>   when: ansible_facts['distribution'] not in ['RedHat', 'CentOS', 'Fedora', 'Rocky']
> ```
> 
> but a few Jinja2 templates are also affected and I created one softlink:
> 
> ```
> roles/ceph-container-engine/vars/Rocky.yml -> RedHat-8.yml
> ```
> 
> For restarting running ceph daemons I also had to change the conditionals. I am unsure if this is related to Rocky Linux.

PR are welcome 🙂

**Comment by distributorofpain** [comment]
I guess i would need to figure out how to do a PR, but Guits, can you list all the files, i can check stable 5.0
