### ISSUE TITLE
[ansible 1.9.x only] 'dict object' has no attribute 'monitor_interface'

### ISSUE THREAD

**Issue by vvb** [ceph/ceph-ansible#711]
with the existing top of the tree, `monitor_interface` is already defined in the Vagrantfile, but while doing a `vagrant provision` the following error is seen

```
TASK: [ceph.ceph-common | generate ceph configuration file] *******************
fatal: [mon0] => One or more undefined variables: 'dict object' has no attribute 'monitor_interface'

FATAL: all hosts have already failed -- aborting
```

fails at ` {% if hostvars[host]['monitor_interface'] != "interface" %}`

UPDATE:
Issue occurs when using ansible version is 1.9.4
When I use ansible version 2.0.1.0 I do not see this issue.

**Comment by leseb** [comment]
Duplicate of ##702 (which is closed sorry), it seems to be an issue with Ansible `1.9.4` indeed.
I haven't found the time to look into it yet...

**Comment by vichoward** [comment]
I am also seeing the same issue, running ansible version 1.9.3

TASK: [ceph.ceph-common | generate ceph configuration file] ******************* 
fatal: [mon1] => One or more undefined variables: 'dict object' has no attribute 'monitor_interface'
fatal: [mon0] => One or more undefined variables: 'dict object' has no attribute 'monitor_interface'
fatal: [mon2] => One or more undefined variables: 'dict object' has no attribute 'monitor_interface'

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/Users/vhoward/site.retry

mon0                       : ok=35   changed=5    unreachable=1    failed=0   
mon1                       : ok=35   changed=5    unreachable=1    failed=0   
mon2                       : ok=35   changed=5    unreachable=1    failed=0   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by like-inspur** [comment]
I also met this error with ansible version 2.4.0.0. Do I need to use latest version of ceph-ansible?

**Comment by guits** [comment]
@like-inspur which version of ceph-ansible are you using ?

**Comment by like-inspur** [comment]
@guits v2.2.11
