### ISSUE TITLE
Error with task: fetch ceph red hat development repository for ceph-iscsi

### ISSUE THREAD

**Issue by c-stewa20** [ceph/ceph-ansible#7136]
**Bug Report**

What happened:
On installation of iscsi gateway, an error is generated: 

The task includes an option with an undefined variable. The error was: list object has no element 0

I inserted:

        - name: latest_build_ceph_iscsi results
          debug:
            msg: latest_build_ceph_iscsi.results

before         - name: fetch ceph red hat development repository for ceph-iscsi

which returned nothing.

What you expected to happen:

iscsi gw to be installed by obtaining correct repos

How to reproduce it (minimal and precise):

when running site.yml playbook with iscsigw configured in hosts file

Share your group_vars files, inventory and **full** ceph-ansibe log

* Ansible version (e.g. `ansible-playbook --version`):
* ansible-playbook 2.9.27
  config file = /home/dsdadmin/dell-cluster/ceph-ansible-stable-6.0/ansible.cfg
  configured module search path = [u'/home/dsdadmin/dell-cluster/ceph-ansible-stable-6.0/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Nov 16 2020, 22:23:17) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]

**Comment by guits** [comment]
@c-stewa20 Are you trying to deploy Ceph Pacific on EL7 based OS hosts?

**Comment by c-stewa20** [comment]
EL8

**Comment by guits** [comment]
shaman API doesn't return any repo, hence your failure

```console
$ curl -s -D-  "https://shaman.ceph.com/api/search/?status=ready&project=ceph-iscsi&flavor=default&distros=centos/8/noarch&ref=pacific&sha1=latest"
HTTP/1.1 200 OK
Server: nginx
Date: Wed, 13 Apr 2022 08:51:35 GMT
Content-Type: application/json
Content-Length: 2
Connection: keep-alive
X-Pecan-path: /api/search/
X-Pecan-status: 200 OK
X-Pecan-method: GET
X-Pecan-controller: SearchController.index
X-Pecan-params: [('status', 'ready'), ('project', 'ceph-iscsi'), ('flavor', 'default'), ('distros', 'centos/8/noarch'), ('ref', 'pacific'), ('sha1', 'latest')]
X-Pecan-hooks: ['TransactionHook', 'RequestViewerHook']
Strict-Transport-Security: max-age=31536000
Strict-Transport-Security: max-age=31536000

[]
```

**Comment by c-stewa20** [comment]
[all.txt](https://github.com/ceph/ceph-ansible/files/8488700/all.txt)

Attached is the all.yml file that I have been using.  The rbd-target-api.service is running but the rbd-taget-gw.service is not.  I have looked in all the log places I know of and can't seem to find anything that would indicate why it would not be starting.

<pre>sudo systemctl status rbd-target-api.service
<font color="#8AE234"><b>●</b></font> rbd-target-api.service - Ceph iscsi target configuration API
   Loaded: loaded (/usr/lib/systemd/system/rbd-target-api.service; disabled; vendor preset: disabled)
   Active: <font color="#8AE234"><b>active (running)</b></font> since Thu 2022-04-14 11:02:01 UTC; 17min ago
 Main PID: 18372 (rbd-target-api)
    Tasks: 13 (limit: 1649080)
   Memory: 44.1M
   CGroup: /system.slice/rbd-target-api.service
           └─18372 /bin/python /usr/bin/rbd-target-api
</pre>

<pre>sudo systemctl status rbd-target-gw.service
<font color="#EF2929"><b>●</b></font> rbd-target-gw.service - Setup system to export rbd images through LIO
   Loaded: loaded (/usr/lib/systemd/system/rbd-target-gw.service; disabled; vendor preset: disabled)
   Active: <font color="#EF2929"><b>failed</b></font> (Result: exit-code) since Tue 2022-04-12 21:13:34 UTC; 1 day 14h ago
 Main PID: 4920 (code=exited, status=1/FAILURE)</pre>

...<pre><b>rbd-target-gw.service: Failed with result &apos;exit-code&apos;</b></pre>
...<pre><font color="#EF2929"><b>Failed to start Setup system to export rbd images through LIO.</b></font></pre>
