### ISSUE TITLE
TCMALLOC_MAX_TOTAL_THREAD_CACHE_BYTES=128mb as default in firefly

### ISSUE THREAD

**Issue by Chrislevi** [ceph/ceph-ansible#714]
Hi
I have installed ceph firefly cluster with the playbook and I got less iops than I expected.
I saw that changing this option (In your blog) will increase the 4k random iops.
Is the playbook change this option?

Thank you

**Comment by leseb** [comment]
Nop Ansible doesn't change anything.
Why are you deploying Firefly btw?

**Comment by Chrislevi** [comment]
I'm deploying Firefly cause this is the version I most familiar with.
Is there any way to apply this config on ceph cluster manually?How can I do it?
Which version supporting changing this parameter?

Thank you

**Comment by leseb** [comment]
You can add `TCMALLOC_MAX_TOTAL_THREAD_CACHE_BYTES` in `/etc/default/ceph` if you run on a Debian based system or in `/etc/sysconfig/ceph/` if you run a Red Hat based system.

**Comment by leseb** [comment]
Assuming this resolves your issue, I'm closing this. Feel free to re-open if necessary.

**Comment by Chrislevi** [comment]
Hi,
I upgraded to 0.94.6 with the upgrade yaml(without downtime!).
The file /etc/default/ceph doesn't exist(I'm using Ubuntu 14.04) so I created the file.
I added this line, How could I know if the ceph osd process using this parameter when TCMalloc is used?

**Comment by leseb** [comment]
@liewegas how can we verify that? Thanks!

**Comment by liewegas** [comment]
cat /proc/$pid/environ to see if the environment variable is set?
