### ISSUE TITLE
Failed to download ceph releases 

### ISSUE THREAD

**Issue by nadendlaprasad** [ceph/ceph-ansible#7154]
Environment - CentOS 8

Trying to add new osd server,

In the first instance, it throws ssl error. I had to manually fetch CA of https://download.ceph.com/keys/release.asc. once this issue was sorted out , it started throwing 403 error. 

Hope the following log will be helpful

![image](https://user-images.githubusercontent.com/33215264/163799417-0205f8c9-66ee-4f20-8187-40da0a2f8f9d.png)

**Comment by guits** [comment]
are you still having this error?

```console
➜  ~ curl -D- -o/dev/null -s https://download.ceph.com/keys/release.asc
HTTP/1.1 200 OK
Server: nginx
Date: Thu, 21 Apr 2022 12:00:28 GMT
Content-Type: application/octet-stream
Content-Length: 1645
Last-Modified: Thu, 15 Oct 2015 19:42:48 GMT
Connection: keep-alive
ETag: "562001b8-66d"
Strict-Transport-Security: max-age=31536000
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Content-Security-Policy: default-src 'self'; script-src 'self'
Accept-Ranges: bytes
```

**Comment by hlbomfim** [comment]
Hello. I
nstalling now and have the same error but inside the mgr0 this ok.
Environment: macos monterey

![Screen Shot 2022-04-21 at 16 44 37](https://user-images.githubusercontent.com/10262534/164541304-39caf359-118a-49db-b4c3-8e748e72cf2c.png)
![Screen Shot 2022-04-21 at 16 47 46](https://user-images.githubusercontent.com/10262534/164541341-f18c7531-a8b1-477b-903a-b1fd77a40fbc.png)
:

**Comment by guits** [comment]
is your package `ca-certificates` up to date on your VMs ?

**Comment by guits** [comment]
`ca-certificates-2020.2.41-80.0.el8_2.noarch` seems old

**Comment by hlbomfim** [comment]
But there is an update:
[vagrant@mgr0 ~]$ yum check-update ca-certificates
Last metadata expiration check: 0:08:28 ago on Tue 26 Apr 2022 12:52:32 PM UTC.
Module yaml error: Unexpected key in data: static_context [line 9 col 3]
Module yaml error: Unexpected key in data: static_context [line 9 col 3]

ca-certificates.noarch 2021.2.50-82.el8 baseos

I'll try update the playbook to upgrade too

**Comment by guits** [comment]
I think you should just get an OS up to date on all nodes before running the playbook.
basically, just running `dnf update -y` on all your VMs should address your issue

**Comment by hlbomfim** [comment]
> I think you should just get an OS up to date on all nodes before running the playbook. basically, just running `dnf update -y` on all your VMs should address your issue


roles/ceph-defaults/tasks/main.yml changed.

the problem:
ceph-defaults : Upgrade all packages --------------------------------- 3968.67s

rsrs

**Comment by guits** [comment]
> > I think you should just get an OS up to date on all nodes before running the playbook. basically, just running `dnf update -y` on all your VMs should address your issue
> 
> roles/ceph-defaults/tasks/main.yml changed.

are you saying you have modified this file ?

**Comment by hlbomfim** [comment]
> > > I think you should just get an OS up to date on all nodes before running the playbook. basically, just running `dnf update -y` on all your VMs should address your issue
> > 
> > 
> > roles/ceph-defaults/tasks/main.yml changed.
> 
> are you saying you have modified this file ?

In my environment, yes.

All of this: https://github.com/ceph/ceph-ansible/issues/7154#issuecomment-1109683340

**Comment by guits** [comment]
you shouldn't edit the playbook like that.

If you upgrade your OS correctly, it should fix your issue.
In any case, this has nothing to do with ceph-ansible, for that reason, I'm closing this one.
