### ISSUE TITLE
plugin folder in role

### ISSUE THREAD

**Issue by tdsparrow** [ceph/ceph-ansible#716]
ansible-playbook 2.0.1.0 didn't load config_template action plugin for role ceph-common, works after changing folder 'plugins/actions' -> 'action_plugins'

**Comment by rootfs** [comment]
thanks, is [this](http://docs.ansible.com/ansible/intro_configuration.html#action-plugins) helping?

**Comment by leseb** [comment]
Closing this, feel free to re-open.
