### ISSUE TITLE
docker deployment without KV store fails with /etc/ceph/ceph.mon.keyring must exist

### ISSUE THREAD

**Issue by ivotron** [ceph/ceph-ansible#717]
This is on v1.0.5 . The relevant vars in my configuration are:

`group_vars/all`:

```yaml
docker: true
mon_containerized_deployment_with_kv: false
```

`group_vars/all.docker`:

```yaml
rgw_containerized_deployment: false
```

`group_vars/mons`:

```yaml
mon_containerized_deployment: true
```

For a reason I can't yet still determine, the output of https://github.com/ceph/ceph-docker/blob/master/daemon/config.static.sh only generates `/etc/ceph/ceph.conf` but not the other files.

**Comment by rootfs** [comment]
this is addressed in https://github.com/ceph/ceph-docker/pull/250

**Comment by leseb** [comment]
@ivotron does https://github.com/ceph/ceph-docker/pull/250 fix your issue?

**Comment by ivotron** [comment]
I will try #250 later this week and report back

**Comment by ivotron** [comment]
that fixed it. Thanks :-)
