### ISSUE TITLE
 Ceph cluster authentication Error EACCES: access denied

### ISSUE THREAD

**Issue by topeawolwo** [ceph/ceph-ansible#7178]
I am running Ceph cluster in my production environment, with three Nodes (Node1, Node2, Node3)

The issue is this : I cant authenticated againist the ceph cluster

At the moment the Ceph dashboard is down and cant be accessed.

[root@node3 ceph]# sudo ceph auth import -i ceph.client.admin.keyring
Error EACCES: access denied

I had created a ceph.client.admin.keyring in the /etc/ceph where the ceph.conf is located.

Just wondering where I am getting it wrong and how to fix it,

**Comment by mohit-kanojia** [comment]
did you able to solve it?
