### ISSUE TITLE
Question on Ansible Versions

### ISSUE THREAD

**Issue by aza547** [ceph/ceph-ansible#7210]
Hello,

The version requirements of ansible for each branch is stated here:
https://github.com/ceph/ceph-ansible/blob/main/docs/source/index.rst#releases

What is the reasoning behind having this requirement?

Context is that I am looking to use `ceph-ansible` on a linux distro (Mariner) where I expect not to be able to use the required version of ansible. I am using Ceph Octopus for which doc above states:

> stable-5.0 Supports Ceph version octopus. This branch requires Ansible version 2.9.

...however I only have access to ansible 2.12. 

Is this just a case of testing or is there known issues that will cause problems here? If so, how difficult might it be to made changes to be compatible with ansible 2.12? 

Thanks in advance.
Alex

**Comment by alexanderkershaw** [comment]
Sorry I don't really understand your comment. How could I use a virtualenv to solve this problem?

I currently install ansible via an RPM. Are you proposing I install ansible into a python venv with pip?

Thanks

**Comment by guits** [comment]
> Are you proposing I install ansible into a python venv with pip?

yes

**Comment by aza547** [comment]
Thanks, I've tried with an upgraded ansible and with the collections specified [here](https://github.com/ceph/ceph-ansible/blob/main/requirements.yml) and a few code changes from the above links, I didn't get all the way through the install due to some other issues but looks promising. Reckon this can be closed.

**Comment by guits** [comment]
Keep in mind that you are going to fork which isn't something I would recommend.
Upgrading ceph-ansible may be painful and if you have any issues because of this, you will likely not get support.

By the way, afaik, Ceph Octopus should be EOL soon, along with ceph-ansible stable-5.0 (I believe ~1 month), you might want to consider using Ceph Pacific instead.
