### ISSUE TITLE
ansible posix module missing from requirements.yml in stable-6.0 branch

### ISSUE THREAD

**Issue by SvenMW** [ceph/ceph-ansible#7261]
**Bug Report**

What happened:
my CI Pipeline runs 
```
ansible-playbook -i ../inventories/common -i ../inventories/dev --syntax-check site.yml
```

on ceph-ansible as a syntax check

What you expected to happen:

the check should be green

How to reproduce it (minimal and precise):

Dockerfile to deploy the stable-6.0 branch, which has a hard requirements check on ansible 2.10

```
FROM ubuntu:latest
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && \
    apt -y install python3-pip policycoreutils-python-utils && \
    apt clean && \
    rm -rf /var/lib/apt/lists/* && \
    pip3 install ansible-base==2.10.17 
```
then run above ansible syntax check and get:

```
ERROR! couldn't resolve module/action 'selinux_permissive'. This often indicates a misspelling, missing collection, or incorrect module path.
The error appears to be in '/builds/m-cloud/config/mw-ceph/ceph-ansible/roles/ceph-nfs/tasks/main.yml': line 35, column 3, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
# NOTE (leseb): workaround for issues with ganesha and librgw
- name: add ganesha_t to permissive domain
  ^ here
```

I believe this can be fixed by altering the docker file like this:

```
ansible-galaxy collection install ansible.posix
```

as an alternative, this seems to be fixed in master branch in the requirements.yml file:

```
ansible-galaxy install -r requirements.yml
```

but the required posix module was only added in this commit, it seems:
https://github.com/ceph/ceph-ansible/commit/aa68b06c99f09111effbdf3b3ac5efe99b5e92f6

Share your group_vars files, inventory and **full** ceph-ansibe log

**Environment**:
* OS (e.g. from /etc/os-release): doesn't matter
* Kernel (e.g. `uname -a`): doesn't matter
* Docker version if applicable (e.g. `docker version`): doesn't matter
* Ansible version (e.g. `ansible-playbook --version`): 2.10.17
* ceph-ansible version (e.g. `git head or tag or stable branch`): stable-6.0
* Ceph version (e.g. `ceph -v`):  doesn't matter

I hope I didn't miss anything and this is a valid bug report, will make a Pull Request soon.

kind regards

Sven

**Comment by guits** [comment]
fixed by #7262
