### ISSUE TITLE
Unauthorized for url http://xxxx/api/dashboards/db, purge-dashboard not working

### ISSUE THREAD

**Issue by jeevadotnet** [ceph/ceph-ansible#7265]
**Bug Report**

**What happened:**
Upgraded from octopus to pacific 16.2.10 
And the dashboard no longer works, with ansible-playbook failing on:
`requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: http://10.102.73.89:3000/api/dashboards/db
`

I then try to purge the dashboard with the provided infrastructure playbook:
`ansible-playbook -i /opt/ceph-ansible/inventory -e 'ansible_python_interpreter=/usr/bin/python3' infrastructure-playbooks/purge-dashboard.yml --limit=grafana-server` 

However this run successfully but does not remove all the containers as prescribed in the playbook. It only removes node-exporter but not grafana, prometheus, alertmanager

**What you expected to happen:**
For the dashboard elements all to be deleted & purged. So that I can redeploy it from site-container.yml --limit=grafana-server

**How to reproduce it (minimal and precise):**
Deploy `site-container.yml` to existing setup with a dashboard 
or
upgrade from octopus to pacific
or
`purge-dashboard.yml`

Share your group_vars files, inventory and **full** ceph-ansibe log
[Anible-log for site-container --limit=grafana-server](https://zerobin.net/?99855fa9c0765e43#qowcDoypB1nJyw1ov7VeM1XPR9CdBpgPgElwfMTNIwQ=)
[ansible-log for purge-dashboard --limit=grafana-server](https://zerobin.net/?ae953629d8ad0a91#ESUdsDYlkJHXV/yox/5WNY5WuPw6cE5EaxsqWsor61Q=)

[Group_vars](https://zerobin.net/?9058b3e13a1d3022#siDBNbW5dyvs/bNNbmuN6YCNsZzHRWN8HUqcBy2Wji8=)

**Environment**:
* OS (e.g. from /etc/os-release): `Ubuntu 20.04.4 LTS`
* Kernel (e.g. `uname -a`): `Linux B-03-11-cephctl 5.4.0-122-generic`
* Docker version if applicable (e.g. `docker version`): `20.10.12`
* Ansible version (e.g. `ansible-playbook --version`): `2.9.27`
* ceph-ansible version (e.g. `git head or tag or stable branch`): `stable-6.0`
* Ceph version (e.g. `ceph -v`): `16.2.10`

**Comment by guits** [comment]
i see 
```
2022-07-29 11:20:42,003 p=2715436 u=ilifu-adm n=ansible | PLAY [purge ceph monitoring] **********************************************************************************************************************************************************************************
2022-07-29 11:20:42,003 p=2715436 u=ilifu-adm n=ansible | skipping: no hosts matched

```

could you please share your inventory host ?

**Comment by guits** [comment]
@jeevadotnet i think it's because you are using the 'legacy' group name `grafana-server`

**Comment by guits** [comment]
@jeevadotnet we probably need something like this https://github.com/ceph/ceph-ansible/blob/main/infrastructure-playbooks/cephadm-adopt.yml#L30-L34 in the purge-dashboard.yml playbook

**Comment by jeevadotnet** [comment]
> 

It only strips node-explorer. 

Alertmanager, grafana server and prometheus stays behind running. 

I'm using
```
[grafana-server]
B-03-11-cephctl.maas
```
