### ISSUE TITLE
Unable to deploy dashboard - template error while templating string: No filter named ''ansible.utils.ipwrap"

### ISSUE THREAD

**Issue by jeevadotnet** [ceph/ceph-ansible#7274]
**Bug Report**

**What happened:**
Manually removed the dashboard containers & images from the [grafana-server] host, since it changed between `stable.5` and `stable.6` and the `purge-dashboard.yml` component doesn't work even after updating the bits of [here](https://github.com/ceph/ceph-ansible/issues/7265). 

Host only reflects the current containers running:
```

ubuntu@B-03-11-cephctl:~$ sudo docker ps
CONTAINER ID   IMAGE                                                          COMMAND                  CREATED       STATUS       PORTS     NAMES
69c22ed0f6fd   quay.io/ceph/daemon:v6.0.8-stable-6.0-pacific-centos-stream8   "/opt/ceph-container…"   7 days ago    Up 6 days              ceph-rgw-B-03-11-cephctl-rgw0
d3dc10ec4da9   quay.io/ceph/daemon:v6.0.8-stable-6.0-pacific-centos-stream8   "/opt/ceph-container…"   7 days ago    Up 7 days              ceph-mds-B-03-11-cephctl
1a06985ecbbb   quay.io/ceph/daemon:v6.0.8-stable-6.0-pacific-centos-stream8   "/opt/ceph-container…"   7 days ago    Up 7 days              ceph-mgr-B-03-11-cephctl
b4f08b679bef   quay.io/ceph/daemon:v6.0.8-stable-6.0-pacific-centos-stream8   "/opt/ceph-container…"   7 days ago    Up 7 days              ceph-mon-B-03-11-cephctl
dfc0d582ce92   quay.io/ceph/daemon:v6.0.8-stable-6.0-pacific-centos-stream8   "/usr/bin/ceph-crash"    12 days ago   Up 12 days             ceph-crash-B-03-11-cephctl
```
Made sure my `inventory`, `site-container.yml` and `all.yml` reflects the new changes brought in by `stable.6`

Execute the runbook with `ansible-playbook -i /opt/ceph-ansible/inventory -e 'ansible_python_interpreter=/usr/bin/python3' site-container.yml --limit=monitoring` 

Runbook fails with:

```
TASK [ceph-facts : set_fact _monitor_addresses to monitor_interface - ipv4] *****************************************************************************************
Tuesday 02 August 2022  09:11:14 +0200 (0:00:00.077)       0:02:18.001 ********
fatal: [B-03-11-cephctl.maas]: FAILED! =>
  msg: 'template error while templating string: No filter named ''ansible.utils.ipwrap''.. String: {{ _monitor_addresses | default([]) + [{ ''name'': item, ''addr'': hostvars[item][''ansible_facts''][(hostvars[item][''monitor_interface'']|replace(''-'', ''_''))][ip_version][''address''] | ansible.utils.ipwrap }]  }}'

NO MORE HOSTS LEFT **************************************************************************************************************************************************

PLAY RECAP **********************************************************************************************************************************************************
B-03-11-cephctl.maas       : ok=21   changed=1    unreachable=0    failed=1    skipped=37   rescued=0    ignored=0
```

**What you expected to happen:**
That the runbook runs successfully and the `alertmanager`, `grafana-server`, `prometheus` and `node-exporter` runs on the `monitoring` host. 

**How to reproduce it (minimal and precise):**
`git reset --hard origin/stable-6.0`
Run `site-container.yml`, limited to the the `monitoring` host

Share your group_vars files, inventory and **full** ceph-ansibe log
- [Verbose Ansible Log](https://zerobin.net/?b9a836efa1e84dc1#u5yb7ZC7Apon1VZXVYrmRYrSTF+JmJ2cgq3aJ2VSoqI=)
- [Group Vars](https://zerobin.net/?a54505ed019a3be5#iTz7nML3j4cXhebFJBs8P1u3BZEIjxYfJBo15tOXxFg=)
- [Inventory](https://zerobin.net/?76e72089b507d42e#kyg2k9yseokvLv1t3/5e5brFrJu7n/fa2hqCiDM7GGE=)

**Environment**:
* OS (e.g. from /etc/os-release): `Ubuntu 20.04.4 LTS`
* Kernel (e.g. `uname -a`): `Linux 5.4.0-122-generic`
* Docker version if applicable (e.g. `docker version`): `20.10.12`
* Ansible version (e.g. `ansible-playbook --version`): `2.9.27`
* ceph-ansible version (e.g. `git head or tag or stable branch`): `stable-6.0`
* Ceph version (e.g. `ceph -v`): `16.2.10`

**Comment by jeevadotnet** [comment]
@guits  maybe any ideas please?

**Comment by guits** [comment]
hi @jeevadotnet ,

this is probably related to #7262

**Comment by guits** [comment]
can you try the following

```console
$ ansible-galaxy collection install ansible.utils
```

**Comment by guits** [comment]
fixed by #7262

**Comment by jeevadotnet** [comment]
Thanks that did it,

**Comment by jeevadotnet** [comment]
Thanks master @guits  it worked 💯
