### ISSUE TITLE
ceph-mon : check if monitor initial keyring already exists - stuck

### ISSUE THREAD

**Issue by allidoiswin10** [ceph/ceph-ansible#7287]
**Bug Report**

**What happened:**

Trying to run site-container.yml playbook to add an additional OSD (dc1-cephu02) node and MON (azure-cephu01) node. Playbook gets stuck on _TASK [ceph-mon : check if monitor initial keyring already exists]_ 

Increased verbosity shows it's specifically stuck on running AnsiballZ_ceph_key.py

Which I think is trying to query the mon keyring inside of the running mon containers:
`ceph -n mon. -k /var/lib/ceph/mon/ceph-azure-cephu01/keyring --cluster ceph auth get mon. -f json`

I've checked the mon keyring exists and is accessible inside of the container. If I run the above command on ceph-mon-azure-cephu01, I get timeouts:
```
2022-08-09T15:00:41.269+0000 7f4e80d12700  0 monclient(hunting): authenticate timed out after 300
2022-08-09T15:05:41.268+0000 7f4e80d12700  0 monclient(hunting): authenticate timed out after 300
2022-08-09T15:10:41.273+0000 7f4e80d12700  0 monclient(hunting): authenticate timed out after 300
2022-08-09T15:15:41.267+0000 7f4e80d12700  0 monclient(hunting): authenticate timed out after 300
2022-08-09T15:20:41.273+0000 7f4e80d12700  0 monclient(hunting): authenticate timed out after 300
```
If I run this on a ubuntu 18.04 vm with a mon container, I get the mon keyring returned. (see corresponding versions below)

**What you expected to happen:**

For the ansible playbook to run successfully.

**How to reproduce it (minimal and precise):**

Run the playbook on a ubuntu 20.04 which has mon container.

**Share your group_vars files, inventory and **full** ceph-ansibe log**
group_vars all.yml - https://zerobin.net/?25c50c32c4e10f7d#9nVx9C3wa0/Fseh29alq3WugVRiODjKz3NphrLwOjmI= 
All others are the same as default.

Inventory -  https://zerobin.net/?934b5b1026330ff0#5agcU6kF+2xsB6y3cI8jQqJDXl92/ZGhI/w2kcuIwrE= 
(the azure node has 20.04)

I can't not provide the full ceph-ansible logs as it's too revealing. Happy to answer more questions about our cluster.

**Environment**:
* OS (e.g. from /etc/os-release): 18.04 all dc1 and dc2 vms. 20.04 on azure vm.
* Kernel (e.g. `uname -a`): 5.4.0-91-generic dc1 and dc2 vms. 5.13.0-1023-azure on azure vm.
* Docker version if applicable (e.g. `docker version`): 20.10.17 on dc1 and dc2 vms. 20.10.12 on azure vm.
* Ansible version (e.g. `ansible-playbook --version`): 2.10.17
* ceph-ansible version (e.g. `git head or tag or stable branch`): stable-6.0
* Ceph version (e.g. `ceph -v`): ceph version 16.2.5

**Comment by guits** [comment]
> ```
> 2022-08-09T15:00:41.269+0000 7f4e80d12700  0 monclient(hunting): authenticate timed out after 300
> 2022-08-09T15:05:41.268+0000 7f4e80d12700  0 monclient(hunting): authenticate timed out after 300
> 2022-08-09T15:10:41.273+0000 7f4e80d12700  0 monclient(hunting): authenticate timed out after 300
> 2022-08-09T15:15:41.267+0000 7f4e80d12700  0 monclient(hunting): authenticate timed out after 300
> 2022-08-09T15:20:41.273+0000 7f4e80d12700  0 monclient(hunting): authenticate timed out after 300
> ```

It doesn't seem to be a ceph-ansible issue at first glance. It looks like a networking issue in your infra. 
Could you check what is described here [1] ?

[1] https://docs.ceph.com/en/pacific/rados/troubleshooting/troubleshooting-mon/#client-can-t-connect-or-mount
