### ISSUE TITLE
lsblk: unknown column: PARTLABEL while running docker osd playbook 

### ISSUE THREAD

**Issue by ivotron** [ceph/ceph-ansible#729]
While running a docker-based deployment (specifically, [this line](https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-osd/tasks/docker/start_docker_osd.yml#L13)), the task that checks for `PARTLABEL` fails with the message of the title. This is on ubuntu 14.04.2 , with `util-linux` version `2.20.1-5.1ubuntu20.4` . An alternative would be to use `ceph-disk list`

**Comment by leseb** [comment]
The `ceph-disk` alternative won't work for CoreOS or Atomic distros.
