### ISSUE TITLE
library/rados_user.py modify

### ISSUE THREAD

**Issue by karasjoh000** [ceph/ceph-ansible#7296]
https://github.com/ceph/ceph-ansible/blob/b40e4bfe60cb14a8eac225086f60d5b170636b6d/library/radosgw_user.py#L268-L269

If display_name != name and display_name is not provided as a param, then display_name is changed to name although the expectation will be that display_name should not change. 

Note: I did not test this, but it seems that L268 and L269 need to be removed.

**Comment by asm0deuz** [comment]
display_name is a mandatory parameter to radosgw-admin command. If you do not set the display_name, it fails creating the user with `could not create user: unable to create user, no display name specified`. This is probably why L268 and L269 are there for but indeed if the user already exists, its display_name will be overwritten with name.

Seems to be an easy fix, I will take a look at it. Thx

**Comment by karasjoh000** [comment]
Ill create a PR for this

**Comment by guits** [comment]
@karasjoh000 what is the status on this? should we take over?

**Comment by guits** [comment]
@asm0deuz @karasjoh000 🙂

**Comment by karasjoh000** [comment]
This should be a 2 line fix I think.
