### ISSUE TITLE
'Unsupported parameters for (ceph_ec_profile) module: crush_root.

### ISSUE THREAD

**Issue by quangln94** [ceph/ceph-ansible#7306]
when I use the "ceph_ec_profile" module with the "crush_root" parameter, I get the following msg:
'Unsupported parameters for (ceph_ec_profile) module: crush_root. Supported parameters include: cluster, stripe_unit, name, k, state, m, crush_device_class.'

this parameter is already described in this module "ceph-ansible/library/ceph_ec_profile.py", how can i use it ?

**Comment by guits** [comment]
Although `crush_root` is documented here [1] this module doesn't support this parameter, see [2].

Not sure why I've documented this parameter while the module doesn't actually support it, it seems to be an error.

[1] https://github.com/ceph/ceph-ansible/blob/main/library/ceph_ec_profile.py#L79-L83
[2] https://github.com/ceph/ceph-ansible/blob/main/library/ceph_ec_profile.py#L162-L169

**Comment by quangln94** [comment]
This parameters unsupported, so i close this issue.

**Comment by guits** [comment]
> This parameters unsupported, so i close this issue.

we could make it support this parameter though 🙂

**Comment by quangln94** [comment]
Thank you for this. I'm looking forward to it. 😄

**Comment by guits** [comment]
PR are welcome too 😅
