### ISSUE TITLE
deploy behind proxy : Ansible proxy

### ISSUE THREAD

**Issue by Xyic0re** [ceph/ceph-ansible#732]
I was unable to deploy behind my proxy server. It turns out that ansible requires its own proxy variable to be defined, it does not use the system variable.
I was able to hack ceph-ansible to make it work, but I'm sure there is a better way to do it.
group_vars/mons and group_vars/osds
I added the following lines
proxy_env:
  http_proxy: http://my.proxy.com:3128
  https_proxy: http:/my.proxy.com:3128

and then I needed to add the following to: roles/ceph-common/tasks/installs/redhat_ceph_repository.yml
  environment: "{{proxy_env}}"

I hope this makes sense.

**Comment by leseb** [comment]
@Xyic0re the easiest thing to do would be to edit `groups_vars/all`. This is a generic ansible variable.
Thanks for raising this point.

I'll see how we can integrate this in the playbook.

**Comment by davidebelloni** [comment]
Hi,
for CoreOS deployment, wher raw module is used, I think the best is to do the following changes:

```
diff --git a/roles/ceph-common-coreos/tasks/install_pip.yml b/roles/ceph-common-coreos/tasks/install_pip.yml
index 81d6d77..a7b759d 100644
--- a/roles/ceph-common-coreos/tasks/install_pip.yml
+++ b/roles/ceph-common-coreos/tasks/install_pip.yml
@@ -1,9 +1,9 @@
 ---
 - name: download get_pip.py
-  raw: cd $HOME && wget {{pip_url}}
+  raw: cd $HOME && https_proxy="{{ lookup('env', 'https_proxy') }}" wget {{pip_url}}
 
 - name: run get-pip.py
-  raw: "{{pypy_binary_directory}}/python $HOME/get-pip.py"
+  raw: "{{pypy_binary_directory}}/python $HOME/get-pip.py --proxy='{{ lookup('env', 'https_proxy') }}'"
 
 - name: create local temp directory
   local_action: raw mkdir -p {{local_temp_directory}}
diff --git a/roles/ceph-common-coreos/tasks/install_pypy.yml b/roles/ceph-common-coreos/tasks/install_pypy.yml
index 38ad207..c49c80d 100644
--- a/roles/ceph-common-coreos/tasks/install_pypy.yml
+++ b/roles/ceph-common-coreos/tasks/install_pypy.yml
@@ -1,6 +1,6 @@
 ---
 - name: download python
-  raw: cd $HOME &&  wget -O - {{coreos_pypy_url}} |tar -xjf -
+  raw: cd $HOME && https_proxy="{{ lookup('env', 'https_proxy') }}" wget -O - {{coreos_pypy_url}} |tar -xjf -
 
 - name: create pypy_directory
   raw: mkdir -p {{pypy_binary_directory}}
```

Thanks

**Comment by leseb** [comment]
@davidebelloni PR?

**Comment by davidebelloni** [comment]
https://github.com/ceph/ceph-ansible/pull/1192
