### ISSUE TITLE
Failing to setup cluster with ansible

### ISSUE THREAD

**Issue by ShadowOfStrelok** [ceph/ceph-ansible#7339]
fatal: [localhost]: FAILED! => changed=false 
  msg: cephadm is the new official installer. Please, consider migrating. See https://docs.ceph.com/en/latest/cephadm/install for new deployments or https://docs.ceph.com/en/latest/cephadm/adoption for migrating existing deployments.

**Comment by guits** [comment]
I'm not sure what you are reporting exactly. That message seems pretty self-explanatory.
By the way, it means you are using the development branch of ceph-ansible. If you know what you are doing you can still pass `-e yes_i_know=true` to discard this warning.
