### ISSUE TITLE
Ceph Quincy installation using ceph-ansible 

### ISSUE THREAD

**Issue by dbenduga** [ceph/ceph-ansible#7354]
Has anybody installed ceph quincy using ceph-ansible.

I tried to install cluster using multiple MON node and it failed to pass quorum task however if i configured with single mon node it pass quorum task but failed to create LVM 

Configuration files:= 

---
dummy:
cluster: quincy
mon_group_name: mons
osd_group_name: osds
rgw_group_name: rgws
mds_group_name: mdss
nfs_group_name: nfss
mgr_group_name: mgrs
configure_firewall: True
ceph_mon_firewall_zone: public
ceph_mgr_firewall_zone: public
ceph_osd_firewall_zone: public
ceph_mds_firewall_zone: public
ntp_daemon_type: chronyd
ceph_origin: repository
ceph_repository: community
ceph_stable_release: quincy
generate_fsid: true
monitor_interface: ens160
ip_version: ipv4
dashboard_enabled: True
dashboard_protocol: https
dashboard_port: 8443
dashboard_admin_user: admin
dashboard_admin_password: p@ssw0rd

=====================
osd.yml

---
dummy:
devices:
  - /dev/sdf
osd_auto_discovery: false
dmcrypt: False

====================

Please let me know if any changes is required in conf file.

**Comment by asm0deuz** [comment]
quincy installation works with ceph-ansible. It would nice to share at least the ansible logs to see what kind of error you get.

**Comment by mcodenie** [comment]
currently use the Quincy, based on your config mine got this added on the all.yml 
`osd_objectstore: bluestore`
 
and in the osd.yml, no dmcrypt enable.
```
---
dummy:
devices:
  - /dev/sdc
  - /dev/sdd
  - /dev/sde
  - /dev/sdf
osd_auto_discovery: false 
```

in the mons.yml
```
---
dummy:
mon_group_name: mons
monitor_secret: "{{ monitor_keyring.stdout }}"
admin_secret: 'admin_secret'
client_admin_ceph_authtool_cap:
  mon: allow *
  osd: allow *
```

and assume that your **hosts** for ansible define the hostname (ie. cephmon1..3) & monitor addresses with the actual IP:
```
[mons]
cephmon1 monitor_address=x.y.z.50
cephmon2 monitor_address=x.y.z.60
cephmon2 monitor_address=x.y.z.70
```

Agree with @asm0deuz if you can please provide logs the better if still encountered an issue.
