### ISSUE TITLE
"msg": "The task includes an option with an undefined variable. The error was: list object has no element 0\n\nThe error appears to be in

### ISSUE THREAD

**Issue by NitinKalburgii** [ceph/ceph-ansible#7361]
Here is my ansible yaml file
```
- name: Find the green asg with matching tags
  ec2_asg_info:
    tags:
      service_name: cps_wallet
      Environment: "{{ name_env }}"
      service_state: green
  register: asgs_payment

- name: Show the ASG Payment name
  debug: 
    msg: "{{ asgs_payment.results[0].auto_scaling_group_name}}"

- set_fact:
    asg_payment_name: "{{ asgs_payment.results[0].auto_scaling_group_name}}"
```

When running from jenkins i was getting
fatal: [127.0.0.1]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: list object has no element 0\n\nThe error appears to be in '/opt/software/jenkins/workspace/payment-react-ui/srv/payment-ui-110/payment-ui/roles/inspect/tasks/cps_green_deploy.yml': line 9, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Show the ASG Payment name\n  ^ here\n"}

If the update it as
```
- name: Show the ASG Payment name
  debug:
    msg: "{{ asgs_payment}}"

- set_fact:
    asg_payment_name: "{{ asgs_payment}}"
```
I don't get error but my result doesn't have an output
`    "msg": {
        "changed": false, 
        "failed": false, 
        "results": []
    }`
The result list in empty i want it to get ASG name from tags

**Comment by asm0deuz** [comment]
@NitinKalburgii Hi! Your problem seems related to aws, not to ceph-ansible. I will close this issue, feel free to reopen it necessary.
