### ISSUE TITLE
Stable-7.0. ERROR! couldn't resolve module/action 'openstack.config_template.config_template'.

### ISSUE THREAD

**Issue by alvarocurt** [ceph/ceph-ansible#7363]
What happened: I'm trying to deploy a ceph cluster (quincy version) following the steps on https://docs.ceph.com/projects/ceph-ansible/en/latest/index.html and I already did all the configuration and installed the requirements.

However, when entering "ansible-playbook site.yml"  this was my output
<img width="717" alt="image" src="https://user-images.githubusercontent.com/121892413/210414774-c0b0b64d-5426-46fd-97de-18214337a888.png">

I didn't touch that file so I doubt is a syntax nor an indexing error. 
I saw there was a previous post about this error but it got solved by making sure the requirements are up to date, but I already did that from the requirement files. Still, I post my current ansible version.
<img width="447" alt="image" src="https://user-images.githubusercontent.com/121892413/210415120-af1cbb09-82b3-4736-9e02-f07b14189b76.png">
<img width="351" alt="image" src="https://user-images.githubusercontent.com/121892413/210415173-915f032b-e830-47be-bfd0-583b11f6919b.png">
<img width="583" alt="image" src="https://user-images.githubusercontent.com/121892413/210415497-751e4c40-ee56-44d5-8c34-d4b1287f6b7d.png">

This is running on an Ubuntu 20.04.5 LTS. I'm sorry if this doubt is too basic or obvious. I'm relatively new with ansible.

**Comment by asm0deuz** [comment]
Hello,

It looks like you are missing the _openstack.config_template_ collection. Do you have a folder `/home/XXX/.ansible/collections/ansible_collections/openstack/config_template` on your system?

It should be installed by running `ansible-galaxy install -r requirements.yml`

Can you share the content of the _requirements.yml_?

Thx

**Comment by alvarocurt** [comment]
You are right, I'm working as root and I can't find any collections folder in /root/.ansible
<img width="392" alt="image" src="https://user-images.githubusercontent.com/121892413/210603412-94590a43-4ea2-4b24-9899-1b21107023ad.png">
I already ran ansible-galaxy install -r with the requirements.yml file from Stable-7.0
<img width="479" alt="image" src="https://user-images.githubusercontent.com/121892413/210602784-df2045bb-b63b-4988-9989-487881e8a458.png">
But I can see that I have 2 openstack folders:
<img width="511" alt="image" src="https://user-images.githubusercontent.com/121892413/210604735-2ed00746-2ac0-49d4-8798-814cc81239c2.png">

Am I missing something? How should I change where are the modules looked up?
Thanks

**Comment by asm0deuz** [comment]
@alvarocurt Hi,

Can you download, execute this script? https://raw.githubusercontent.com/bcoca/std/devel/list_collections.py and share the output?

It will list the collections installed on your setup. ansible 2.9 does not have _ansible-galaxy collection list_ command implemented.

Thx

**Comment by alvarocurt** [comment]
I get no output from the ecript. Still, exploring what the script did, the result of C.COLLECTIONS_PATHS is:
['/root/.ansible/collections', '/usr/share/ansible/collections']
But my host doesn't have any collections directory in those paths.
By using "find", I encountered these paths with some ansible collections directory
<img width="933" alt="image" src="https://user-images.githubusercontent.com/121892413/212064424-212d2219-32cd-45f1-8384-abff55a0125e.png">
Looks like there's some type of conflict between the pip managed ansible, and the one installed by apt-get.

**Comment by alvarocurt** [comment]
> @alvarocurt did you manage to fix your issue?

Not really, I gave up and deployed the cluster with cephadm, but came up with the idea of running containerized ansible to avoid the dependencies errors. I might try that in the future.
