### ISSUE TITLE
Add node add not in

### ISSUE THREAD

**Issue by misteruly** [ceph/ceph-ansible#7387]
![image](https://user-images.githubusercontent.com/31399968/220250319-c6ec1ce9-615a-41fc-8a1a-4fa17edd4626.png)

I have added a new host ceph-rgw, but I cannot skip this step. Is there any other way ？
**Environment**:
* centos 7.8
* Linux ceph-node1 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Client:
  Version:         1.13.1
  API version:     1.26
  Package version: docker-1.13.1-209.git7d71120.el7.centos.x86_64
  Go version:      go1.10.3
  Git commit:      7d71120/1.13.1
  Built:           Wed Mar  2 15:25:43 2022
  OS/Arch:         linux/amd64

    Server:
   Version:         1.13.1
   API version:     1.26 (minimum version 1.12)
   Package version: docker-1.13.1-209.git7d71120.el7.centos.x86_64
   Go version:      go1.10.3
   Git commit:      7d71120/1.13.1
   Built:           Wed Mar  2 15:25:43 2022
   OS/Arch:         linux/amd64
   Experimental:    false
* ansible-playbook 2.9.27
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Apr  2 2020, 13:16:51) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

* ceph version 14.2.20 (36274af6eb7f2a5055f2d53ad448f2694e9046a0) nautilus (stable)

**Comment by asm0deuz** [comment]
This seems related to the cockpit interface, I would have advised you to open a issue here: https://github.com/red-hat-storage/cockpit-ceph-installer/issues but I see you already did it.
