### ISSUE TITLE
ceph-osd/tasks/scenarios/osd_directory.yml using fact not availabe in ansible 1.9.x

### ISSUE THREAD

**Issue by mattt416** [ceph/ceph-ansible#741]
Hi All,

I get a failure when I try to use an OSD directory when using ansible 1.9.x.  I believe commit https://github.com/ceph/ceph-ansible/commit/210e4d4a015b0039c7ba1fd1427e3df846bdd430 introduced this and from what I can tell `ansible_service_mgr` is not available in ansible 1.9.x.  I'm not overly familiar w/ systemd -- what is the best way to check for this in the absence of `ansible_service_mgr` fact?

Thanks,
Matt

**Comment by leseb** [comment]
Hey @mattt416,

I didn't know that `ansible_service_mgr` was not available in `1.9.x`.
To check for systemd, we can use a fact and test `grep -sq systemd /proc/1/comm`.

**Comment by mattt416** [comment]
Thanks @leseb!  I'll set a fact called `init_system` in ceph-common which can be used in all roles.

On a side note, I see handlers such as this:

```
- name: restart ceph mons with systemd
  service:
      name: ceph-mon@{{ monitor_name }}
      state: restarted
  when:
    socket.rc == 0 and
    ansible_distribution != 'Ubuntu' and
    mon_group_name in group_names and
    is_after_hammer
```

Is that technically incorrect since Ubuntu does support systemd?  Would all those tasks need to be updated to use the new fact?

**Comment by leseb** [comment]
@mattt416 yes please do the fact :)

As for Ubuntu, we need to work on the support of 16.04 which has systemd. However 14.04 is still supported and uses upstart.
I guess we need to differentiate both for the time being.
