### ISSUE TITLE
stable-4.0: restart_nfs_daemon can't find ganesha.pid

### ISSUE THREAD

**Issue by canozyurt** [ceph/ceph-ansible#7417]
Branch stable-4.0 uses "latest" tag for nfs service. So this commit 45ddbedef2ffdee04f35ea90f01a6ea49181cdf5 should be applied to this branch as well. I haven't tested but all the stable branches up to 6.0 might be affected.

**Comment by guits** [comment]
`stable-4.0` is no longer supported. It is EOL for almost 2 years now.
