### ISSUE TITLE
Module `openstack.config_template.config_template`

### ISSUE THREAD

**Issue by ThomasBucaioni** [ceph/ceph-ansible#7422]
Some roles call the module `openstack.config_template.config_template`, but it looks like a typo?

**Comment by jeevadotnet** [comment]
I was just about to post about this, I'm getting the same issue when running `rolling_update.yml`

Trying to update from `pacific` to `quincy`

ansible: `2.12.10`
.git/HEAD: `refs/heads/stable-7.0`

Error:
```
ERROR! couldn't resolve module/action 'openstack.config_template.config_template'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/opt/ceph-ansible/roles/ceph-config/tasks/main.yml': line 110, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: "generate {{ cluster }}.conf configuration file"
  ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes. Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"
```

**Comment by ThomasBucaioni** [comment]
@jeevadotnet it was `cephadm-ansible`, my bad: https://access.redhat.com/documentation/en-us/red_hat_ceph_storage/5/html-single/installation_guide/index#registering-the-red-hat-ceph-storage-nodes-to-the-cdn-and-attaching-subscriptions_install
```
dnf install cephadm-ansible
```

**Comment by dsavineau** [comment]
> Some roles call the module `openstack.config_template.config_template`, but it looks like a typo?

it's not a typo and it's part of the collection requirements [1] so it's likely because you didn't install those [2]

[1] https://github.com/ceph/ceph-ansible/blob/main/requirements.yml#L4-L6
[2] https://docs.ceph.com/projects/ceph-ansible/en/latest/#ansible-collections
[3] https://opendev.org/openstack/ansible-config_template/src/tag/1.2.1/plugins/action/config_template.py

**Comment by ThomasBucaioni** [comment]
Cheers
