### ISSUE TITLE
Dashboard meters broken

### ISSUE THREAD

**Issue by badfiles** [ceph/ceph-ansible#7465]
**Bug Report**

What happened:

most monitoring meters on dashboard return
"parse error at line *, char *: missing unit character in duration"
while some work correctly

**Environment**:
* OS (e.g. from /etc/os-release): AlmaLinux 8.8 mgr/monitoring, AlmaLinux 9.2 osd/mon
* Kernel (e.g. `uname -a`):
* Docker version if applicable (e.g. `docker version`): distro podman
* Ansible version (e.g. `ansible-playbook --version`): 2.12
* ceph-ansible version (e.g. `git head or tag or stable branch`): master
* Ceph version (e.g. `ceph -v`): reef

![Screenshot from 2023-10-24 15-29-08](https://github.com/ceph/ceph-ansible/assets/1597304/4052bfea-4659-4b97-98d0-832aab4bfa29)

**Comment by asm0deuz** [comment]
How is this related to ceph-ansible?

**Comment by badfiles** [comment]
I have no idea how this could be related to ceph-ansible, but maybe 
 ceph-ansible provides grafana container, it could be broken/outdated,
 ceph-ansible provides dashboards, they could be buggy,
 this is how it is by design and not a bug.
 
That's why people invented bug reports. Maybe the solution will be found and other people with the same problem will find it here?
