### ISSUE TITLE
Can't update from quincy to reef from stable-8.0

### ISSUE THREAD

**Issue by mr1jingles** [ceph/ceph-ansible#7503]
Hello!
I can't upgrade ceph from quincy to reef from stable-8.0 branch

TASK [ceph-validate : Validate ceph_repository_community] *******************************************
fatal: [sc-mon1]: FAILED! => changed=false
  msg: ceph_stable_release must be 'squid'
...

I see it:

- name: Validate ceph_repository_community
  ansible.builtin.fail:
    msg: "ceph_stable_release must be 'squid'"
  when:
    - ceph_origin == 'repository'
    - ceph_repository == 'community'
    - ceph_stable_release not in ['squid']

Can you tell you which branch should I use for this?

P.S one week ago I upgraded from quincy to reef on test environment and it worked correctly

**Comment by guits** [comment]
@mr1jingles I'm sorry but `stable-8.0` isn't ready yet
