### ISSUE TITLE
Ceph-mon fails to bind on rocky 9

### ISSUE THREAD

**Issue by whinis** [ceph/ceph-ansible#7518]
**Bug Report**

What happened:
During the step Waiting for Monitors to form the quorum it times out. Upon investigation it seems that if you have more than one monitor they all attempt to bind to the same address regardless of settings. ansible.log didn't seem to generate for whatever reason. Also an oddity. if I attempt to install stable-7.0 first there is no issues.

How to reproduce it (minimal and precise):

Share your group_vars files, inventory and **full** ceph-ansibe log

**Environment**:
* OS (e.g. from /etc/os-release): Rocky Linux 9.3
* Kernel (e.g. uname -a): Linux localhost.localdomain 5.14.0-362.24.1.el9_3.x86_64  SMP PREEMPT_DYNAMIC Wed Mar 13 17:33:16 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
* Docker version if applicable (e.g. docker version):
* Ansible version (e.g. ansible-playbook --version): 2.15.9
* ceph-ansible version (e.g. git head or tag or stable branch): stable-8.0
* Ceph version (e.g. ceph -v): ceph version 18.2.2
* 
[all.yml.txt](https://github.com/ceph/ceph-ansible/files/14625939/all.yml.txt)

[ansible-hosts.txt](https://github.com/ceph/ceph-ansible/files/14625938/ansible-hosts.txt)

**Comment by whinis** [comment]
To try and get a working environment I attempted to have just one mon in the inventory and it later then fails as the mgr dashboard also attempts to bind to the first ip on the list. Even if you set it to only one it still fails in odd ways however as you can see in the log

```2024-03-16 22:39:47,536 p=375060 u=john n=ansible | changed: [192.168.30.8] => changed=true 
  cmd:
  - ceph
  - -n
  - client.admin
  - -k
  - /etc/ceph/ceph.client.admin.keyring
  - --cluster
  - ceph
  - mgr
  - module
  - enable
  - dashboard
  delta: '0:00:01.681765'
  end: '2024-03-16 22:39:47.513309'
  rc: 0
  start: '2024-03-16 22:39:45.831544'
  stderr: ''
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
2024-03-16 22:39:47,547 p=375060 u=john n=ansible | TASK [ceph-dashboard : Create dashboard admin user] **************************************************************************************************************************************************************
2024-03-16 22:39:57,801 p=375060 u=john n=ansible | fatal: [192.168.30.8]: FAILED! => changed=false 
  msg: |-
    Error EIO: Module 'dashboard' has experienced an error and cannot handle commands: OSError("No socket could be created -- (('192.168.30.8', 8443): [Errno 99] Cannot assign requested address)")```

If I attempt to run the command directly on the node outside of ansible it fails twice and then succeeds.

**Comment by guits** [comment]
hi @whinis 

to be very honest, although rocky linux support was added not so long ago, it isn't tested so I'm not quite surprised it's broken at the moment...

**Comment by whinis** [comment]
Thats fair, let me know how I can help debug the issue. I feel better running closer to metal with this stuff than everything being docker.

**Comment by guits** [comment]
@whinis I couldn't reproduce your issue. That being said, `stable-8.0` received some commits recently.
Which tag did you use?

**Comment by whinis** [comment]
Probably a few different ones as before each run I `git pull` and then `git reset --hard origin/stable-8.0` and finally `git checkout stable-8.0`. I think its likely related to #7517 because its the same kickstarted raw vm in both instances. I never set hostnames and left it as localhost.localdomain on all 3 instances. I am going to work on this tomorrow to have my setup assign proper hostnames

**Comment by whinis** [comment]
So, after setting hostnames it works without issue. Did not expect this but thank you
