### ISSUE TITLE
sgdisk fails to fully clear/wipe device

### ISSUE THREAD

**Issue by alfredodeza** [ceph/ceph-ansible#759]
The flags to sgdisk seem to need revising. This happens when a back MBR is present (disk wasn't correctly wiped):

    TASK: [ceph-osd | fix partitions gpt header or labels of the osd disks] *******
    failed: [dhcp-126-123.lab.eng.brq.redhat.com] => (item=[{'changed': False, 'end': '2016-05-05 09:44:20.721989', 'failed': False, 'stdout': u'', 'cmd': 'parted --script /dev/vdg print > /dev/null 2>&1', 'rc': 1, 'start': '2016-05-05 09:44:20.679120', 'item': u'/dev/vdg', 'warnings': [], 'delta': '0:00:00.042869', 'invocation': {'module_name': u'shell', 'module_complex_args': {}, 'module_args': u'parted --script /dev/vdg print > /dev/null 2>&1'}, 'stdout_lines': [], 'failed_when_result': False, 'stderr': u''}, u'/dev/vdg']) => {"changed": false, "cmd": "sgdisk --zap-all --clear --mbrtogpt -g -- /dev/vdg", "delta": "0:00:01.261285", "end": "2016-05-05 09:44:24.020624", "item": [{"changed": false, "cmd": "parted --script /dev/vdg print > /dev/null 2>&1", "delta": "0:00:00.042869", "end": "2016-05-05 09:44:20.721989", "failed": false, "failed_when_result": false, "invocation": {"module_args": "parted --script /dev/vdg print > /dev/null 2>&1", "module_complex_args": {}, "module_name": "shell"}, "item": "/dev/vdg", "rc": 1, "start": "2016-05-05 09:44:20.679120", "stderr": "", "stdout": "", "stdout_lines": [], "warnings": []}, "/dev/vdg"], "rc": 3, "start": "2016-05-05 09:44:22.759339", "warnings": []}
    stderr: Caution: invalid main GPT header, but valid backup; regenerating main header
    from backup!
    
    Warning! Main partition table CRC mismatch! Loaded backup partition table
    instead of main partition table!
    
    Warning! One or more CRCs don't match. You should repair the disk!
    
    Invalid partition data!
    stdout: Caution! After loading partitions, the CRC doesn't check out!
    GPT data structures destroyed! You may now partition the disk using fdisk or
    other utilities.
    Information: Creating fresh partition table; will override earlier problems!
    Non-GPT disk; not saving changes. Use -g to override.
    
    FATAL: all hosts have already failed -- aborting

Related issues:

https://bugs.launchpad.net/ubuntu/+source/gdisk/+bug/1303903
http://tracker.ceph.com/issues/6793

**Comment by leseb** [comment]
@alfredodeza stupid thing is, the already use `-g`, the only fix I've found so far without digging too much is to trigger the command a second time...

**Comment by alfredodeza** [comment]
Everything that I find tends to agree with you: a second try is the best (only?) way to ensure this works: https://github.com/coreos/ignition/pull/162

**Comment by leseb** [comment]
@alfredodeza yes, a second try is usually enough. I don't mind executing this twice.

**Comment by alfredodeza** [comment]
I am struggling here to have a nice way to retry these calls to sgdisk because of the `with_together` and the check of `item.0.rc != 0`

Since it is a loop over a list of devices already, the control of flow will get weird/unreadable if I go with ansible constructs. Will try an approach with using `||` since it is already a shell command

**Comment by leseb** [comment]
@alfredodeza sure. However I think this could be a command module. If so, we could simply create 2 tasks. Wdyt?

After discussing with last week @SamYaple, it seems that we are in the process of removing (at least trying) all the shell module calls. The reason mostly being security but also a better usage of Ansible and its Python (filters) capabilities.

**Comment by alfredodeza** [comment]
A module will require a bit more work. Would you be willing to merge this as-is while I improve this with a module on a next iteration? 

I promise to have a nice module soon-ish :)

**Comment by leseb** [comment]
@alfredodeza not really a module, just use the command module :).
But yeah we can go ahead with this one.

**Comment by SamYaple** [comment]
This would have been much better done with an "until" loop. Just loop on sgdisk for _n_ number of times until the rc of sgdisk is successful

But like @leseb says, it will get cleaned up as we remove shell

**Comment by alfredodeza** [comment]
@SamYaple thanks for the tip. I did struggle for a bit to get something going. Your approach would've been better.

**Comment by SamYaple** [comment]
@alfredodeza not a problem. this is all about learning and refining! What you have works and thats whats most important right now.
