### ISSUE TITLE
[Suggestion] Suggestions regarding dependencies in `stable-*` versions

### ISSUE THREAD

**Issue by bugwz** [ceph/ceph-ansible#7594]
**Regarding the issue of modifying the `ansible-core` version in historical `stable-*` versions within the community, I have the following suggestions:**

+ Try not to modify the `ansible-core` version and other dependent component versions in historical `stable-*` versions unless there are any bugs that prevent normal use. Modifications can lead to many chain reactions, such as:
  + Previously, everything worked fine, but after pulling the latest version of the code, local execution issues were discovered, ultimately traced back to community modifications of `ansible-core`, `python`, and other dependencies.
  + This can cause many discrepancies between `ceph-ansible` documentation and the actual code. For example, in https://github.com/ceph/ceph-ansible/pull/7492, the `ansible-core` version in `stable-7.0` was modified to be greater than `2.15`, and the `python` dependency was upgraded to `3.10`. However, the documentation at https://docs.ceph.com/projects/ceph-ansible/en/stable-7.0/ still indicates that the `ansible-core` dependency is `2.12`.
+ Since `ceph-ansible` will not receive significant support in the future, the primary focus should be on maintaining the stability of the existing versions rather than introducing new versions arbitrarily.

**I still recommend reverting the version dependency of stable-7.0 back to 2.12 unless the previous commit fixed a major issue.**

---

**针对于社区对历史 `stable-*` 版本修改 `ansible-core` 版本的问题，我有如下建议**：

+ 尽量不要修改历史 `stable-*` 版本中的 `ansible-core` 版本及其他依赖的组件版本，除非有任何无法正常使用的 bug 。因为修改后会导致很多连锁反应，比如：
  + 之前正常使用的没有问题，但是拉取最新版本代码后，发现本地执行异常，最终发现是因为社区修改了 `ansible-core` ，`python` 等的相关依赖；
  + 这会导致 `ceph-ansible` 的很多文档记录与实际的代码严重不符合。比如 https://github.com/ceph/ceph-ansible/pull/7492 中修改了 `stable-7.0` 中的 `ansible-core` 版本需要大于 `2.15` ，`python` 依赖需要升级为  `3.10` ，但是 https://docs.ceph.com/projects/ceph-ansible/en/stable-7.0/ 中的文档中标明的 `ansible-core` 依赖还是 `2.12` ；
+ 既然 `ceph-ansible` 后续不会投入大量的精力支撑，那么首先要保证的是存量的稳定，而不是为了随便引入新版本。

**我依旧建议将 `stable-7.0` 的版本依赖回退到 `2.12` ，除非之前的 commit 修复了很重大的问题**

@guits

**Comment by guits** [comment]
@bugwz let's just update the documentation in that case

**Comment by bugwz** [comment]
Thank you for your response. Modifying the document to maintain consistency is also a good approach.

@guits

**Comment by bugwz** [comment]
@guits  https://github.com/ceph/ceph-ansible/pull/7599 Please review the code. : )
