### ISSUE TITLE
[RFE] ceph client role

### ISSUE THREAD

**Issue by vasukulkarni** [ceph/ceph-ansible#769]
It would be useful to have ceph-client role, there can be 2 profiles for client but to start with

1) ceph client "admin" role that has rwx permission to all(mon, osd etc), existence of this role will ease admin work required after cluster setup,  admin keyring exists on mon servers.
2) "custom" client role based on user requirement via host vars?

**Comment by leseb** [comment]
@vasukulkarni ok you convinced me and you're not the only one that asked for this.
I'll try to come up with something soon.
