### ISSUE TITLE
Ability to shrink a cluster

### ISSUE THREAD

**Issue by leseb** [ceph/ceph-ansible#774]
Remove MONs, remove OSDs

**Comment by bengland2** [comment]
what happened to purge-cluster.yml?  Has this functionality moved somewhere?   it used to be in there as of RHSCON-2 stale branch, but it's gone.  I used to rely on this to strip out Ceph from a cluster so I could redeploy with different config.

**Comment by leseb** [comment]
It's now part of the `infrastructure-playbooks` directory structure.

**Comment by leseb** [comment]
https://github.com/ceph/ceph-ansible/pull/929
