### ISSUE TITLE
error when ceph-disk fails to prepare a device/partition

### ISSUE THREAD

**Issue by alfredodeza** [ceph/ceph-ansible#780]
This is similar to the work we did for activating an OSD, except we need to catch ceph-disk in a different way now:

    TASK: [ceph-osd | prepare osd disk(s)] ****************************************
    failed: [dhcp-126-125.lab.eng.brq.redhat.com] => (item=[{'changed': False, 'end': '2016-05-10 11:21:46.074846', 'failed': False, 'stdout': u'', 'cmd': "parted --script /dev/vdf print | egrep -sq '^ 1.*ceph'", 'rc': 1, 'start': '2016-05-10 11:21:46.058675', 'item': u'/dev/vdf', 'warnings': [], 'delta': '0:00:00.016171', 'invocation': {'module_name': u'shell', 'module_complex_args': {}, 'module_args': u"parted --script /dev/vdf print | egrep -sq '^ 1.*ceph'"}, 'stdout_lines': [], 'failed_when_result': False, 'stderr': u''}, {'changed': False, 'end': '2016-05-10 11:21:33.998193', 'failed': False, 'stdout': u'', 'cmd': "echo '/dev/vdf' | egrep '/dev/([hsv]d[a-z]{1,2}|cciss/c[0-9]d[0-9]p|nvme[0-9]n[0-9]p)[0-9]{1,2}$'", 'rc': 1, 'start': '2016-05-10 11:21:33.988921', 'item': u'/dev/vdf', 'warnings': [], 'delta': '0:00:00.009272', 'invocation': {'module_name': u'shell', 'module_complex_args': {}, 'module_args': u"echo '/dev/vdf' | egrep '/dev/([hsv]d[a-z]{1,2}|cciss/c[0-9]d[0-9]p|nvme[0-9]n[0-9]p)[0-9]{1,2}$'"}, 'stdout_lines': [], 'failed_when_result': False, 'stderr': u''}, u'/dev/vdf', u'/dev/vde']) => {"changed": false, "cmd": ["ceph-disk", "prepare", "--cluster", "ceph", "/dev/vdf", "/dev/vde"], "delta": "0:05:03.077442", "end": "2016-05-10 11:26:51.403133", "item": [{"changed": false, "cmd": "parted --script /dev/vdf print | egrep -sq '^ 1.*ceph'", "delta": "0:00:00.016171", "end": "2016-05-10 11:21:46.074846", "failed": false, "failed_when_result": false, "invocation": {"module_args": "parted --script /dev/vdf print | egrep -sq '^ 1.*ceph'", "module_complex_args": {}, "module_name": "shell"}, "item": "/dev/vdf", "rc": 1, "start": "2016-05-10 11:21:46.058675", "stderr": "", "stdout": "", "stdout_lines": [], "warnings": []}, {"changed": false, "cmd": "echo '/dev/vdf' | egrep '/dev/([hsv]d[a-z]{1,2}|cciss/c[0-9]d[0-9]p|nvme[0-9]n[0-9]p)[0-9]{1,2}$'", "delta": "0:00:00.009272", "end": "2016-05-10 11:21:33.998193", "failed": false, "failed_when_result": false, "invocation": {"module_args": "echo '/dev/vdf' | egrep '/dev/([hsv]d[a-z]{1,2}|cciss/c[0-9]d[0-9]p|nvme[0-9]n[0-9]p)[0-9]{1,2}$'", "module_complex_args": {}, "module_name": "shell"}, "item": "/dev/vdf", "rc": 1, "start": "2016-05-10 11:21:33.988921", "stderr": "", "stdout": "", "stdout_lines": [], "warnings": []}, "/dev/vdf", "/dev/vde"], "rc": 1, "start": "2016-05-10 11:21:48.325691", "warnings": []}
    stderr: prepare_device: OSD will not be hot-swappable if journal is not the same device as the osd data
    ceph-disk: Error: partprobe /dev/vde failed : Error: Error informing the kernel about modifications to partition /dev/vde1 -- Device or resource busy.  This means Linux won't know about any changes you made to /dev/vde1 until you reboot -- so you shouldn't mount it or use it in any way before rebooting.
    Error: Failed to add partition 1 (Device or resource busy)
    stdout: The operation has completed successfully.
    ...ignoring

**Comment by leseb** [comment]
@alfredodeza this is though, I'm not sure if we should fail completely. I think we should try to find a way to report what went wrong on which node and which device.
Stopping the play for a single drive is not ideal...

**Comment by alfredodeza** [comment]
@leseb the problem is that if there is no mechanism to alert at the end of the run (maybe with a warning). Imagine deploying to 100 OSDs, the sheer amount of output will obfuscate anything that might have not worked.

If the client is being specific about devices that should be created, not failing when the task is not accomplishing this seems unexpected.

**Comment by alfredodeza** [comment]
Another thing to keep in mind is that, in this case, one OSD failed to be prepared, and yes, it might be cumbersome to fail for 1 OSD if configuring 100. But if *all* the OSDs failed to be configured? Are we OK in not failing early?

**Comment by leseb** [comment]
@alfredodeza that's a good point, and we are not going to count for failing OSDs. In the end, I think it's fine to fail if the disk fails because we won't be getting the state we expect.
If this fails, we will investigate and the device and re-run the play.
If the play finishes, we expect an up and running cluster, not half :)
