### ISSUE TITLE
Not installing on CentOS hosts

### ISSUE THREAD

**Issue by rnowling** [ceph/ceph-ansible#783]
When I use CentOS, none of the installs triggered.  One solution was to change

```
use_server_package_split: true
```

to 

```
use_server_package_split: false
```

in `roles/ceph-common/defaults/main.yml` .

**Comment by leseb** [comment]
@rnowling which ceph version are you trying to install? This is only needed when your ceph version is before Jewel.
Basically from Argonaut to Infernalis.

**Comment by rnowling** [comment]
I was using Infernalis (from a checkout before the Jewel update). I'll re-run with the most recent commit (and Jewel) to verify that this is no longer a problem.

**Comment by leseb** [comment]
Well the behaviour is expected on Infernalis. Using Jewel won't require any changes.

**Comment by rnowling** [comment]
If the user was expected to change the variable but it wasn't in the README, then that documentation needs to be updated.  It should work out of the box following the directions.

**Comment by leseb** [comment]
True we should have documented the change.

**Comment by rnowling** [comment]
I can confirm that the change above isn't needed for Jewel, so I'm closing the issue.

**Comment by rnowling** [comment]
I was going to close the issue but a change to the docs is likely needed for users wanting to use earlier versions of Ceph.

**Comment by leseb** [comment]
Done.
