### ISSUE TITLE
Can't use ceph-ansible on Debian with Ceph versions not having the latest Jewel fix

### ISSUE THREAD

**Issue by smatzek** [ceph/ceph-ansible#788]
The commit https://github.com/ceph/ceph-ansible/commit/85fb03fc99e0b7cd14b27e369c8e952b79313d73 broke the ability to use ceph-ansible on Debian for all existing Ceph versions that do not have the bug Jewel fix in Jewel:
https://github.com/ceph/ceph/commit/791eba81a5467dd5de4f1680ed0deb647eb3fb8b

This includes breaking install:
Jewel from UCA
Jewel from latest Canonical 16.04 distro
All previous versions from Canonical
infernalis from Ceph.com??
hammer from ceph.com?

The ceph-ansible run fails with:
failed: [my-ceph-mon] => {"failed": true, "rc": 256}
msg: Destination /etc/default/ceph is a directory !

FATAL: all hosts have already failed -- aborting

One possibility for fixing this is to add a check near [1] to see if /etc/default/ceph is a directory and then register a variable for the destination accordingly.

[1] https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-common/tasks/main.yml#L234

**Comment by leseb** [comment]
Argh, I knew this would happen :(.
Ok let's make it compatible for everyone then.

Basically we need to check if `/etc/default/ceph`, if it exists and is a file we don't do anything, if nothing exist we create the `/etc/default/ceph` directory.

**Comment by leseb** [comment]
PR coming.

**Comment by ktdreyer** [comment]
@smatzek, Please file bugs with the appropriate distributors of Ceph so that they will fix their distributions. We can't persist these sort of hacks indefinitely in ceph-ansible, and these sort of things need to be filed with the distributors.

**Comment by ktdreyer** [comment]
CC'ing @javacruft since I think he maintains the ubuntu.com downstream packages...

**Comment by smatzek** [comment]
I agree that the fixes should be worked into the downstream packages.  However, I think this bug also breaks the install of previous versions of Ceph from ceph.com, unless the bug fix was backported Ceph Hammer, etc.  Ceph ansible contains support to install releases that aren't the most current so this fix is likely needed for those releases even if we had the ceph fix in the downstream packages.

**Comment by ktdreyer** [comment]
I need hyperlinks to specific bug reports (like in launchpad.net, and tracker.ceph.com), otherwise ceph-ansible becomes a pile of hacks, and we never know what hacks can be removed.
