### ISSUE TITLE
how to re-add a failed disk ??

### ISSUE THREAD

**Issue by acomisario** [ceph/ceph-ansible#798]
Hi, we've deployed a cluster using this set of roles, we use just one disk for ceph journal and 6 disks like this:

devices:
  - /dev/sdc
  - /dev/sdd
  - /dev/sde
  - /dev/sdf
  - /dev/sdg
  - /dev/sdh

raw_multi_journal: true
raw_journal_devices:
  - /dev/sdb
  - /dev/sdb
  - /dev/sdb
  - /dev/sdb
  - /dev/sdb
  - /dev/sdb

If a disks fails (eg. sdh), after we replaced it (asuming the device letter is the same) should we just re-run the osd role and that will take care of 

* formating the disk
* assign a new OSD id
* add it to the crush 

Or should we take into consideration any manual operation ?
PS: we took the device manually down and out of the crush map
Thanks!

**Comment by mattt416** [comment]
I'd love to see some of this stuff documented!  I know there would be overlap with ceph proper docs, but it's not always clear what the correct workflow is when you've deployed with openstack-ansible.  Anyone interested in helping me document a lot of these cases?

**Comment by acomisario** [comment]
@mattt416 after i know how to do it, i can help !

**Comment by acomisario** [comment]
@leseb any thoughts ?

**Comment by leseb** [comment]
@acomisario yes, if you add a new disk and run ansible, you will have another OSD being created.

**Comment by acomisario** [comment]
@leseb nice, and, can i limit (--limit) from command line to that host only ?

**Comment by leseb** [comment]
Limit should work. If it does not just temporary remove all the osd host from your inventory file and just let the one that has the new OSD. :)

**Comment by acomisario** [comment]
I can confirm that works **perfectly**

**Comment by rlljorge** [comment]
> @leseb Just make sure to remove the OSD from ceph (osd.id, key, and crush remove).

This is the correct procedure for remove OSD ?  

```
# ceph osd tree | grep -i down
ID WEIGHT   TYPE NAME      UP/DOWN REWEIGHT PRIMARY-AFFINITY 
 6  5.45609         osd.6     down        0          1.00000 

ceph osd out osd.6
service ceph stop osd.6
ceph osd crush remove osd.6
ceph auth del osd.6
ceph osd rm osd.6
```

After this I will go replace physical harddisk and re-execute ansible.

This is the correct way ?

**Comment by leseb** [comment]
@rlljorge this is the correct procedure.
