### ISSUE TITLE
use mon_initial_members instead of ceph.mon sections?

### ISSUE THREAD

**Issue by leseb** [ceph/ceph-ansible#803]
@alfredodeza any thoughts?
Looks like this will be helpful to integrate more closely with the OSP installer.

**Comment by alfredodeza** [comment]
initial members is what ceph-deploy uses, and it is nice/easier to consume. The issue is if the initial members change (or new mons get added). For a new deployment it certainly works.

**Comment by leseb** [comment]
What I personally like about the option is that we don't need to know all the monitors from the get-go.
I'll create a wip for this.

**Comment by mattt416** [comment]
We just implemented `mon initial members` in rpc-openstack using `ceph_conf_overrides` so we can always run our MON and OSD playbooks serially.  See https://github.com/rcbops/rpc-openstack/pull/1101/files.

**Comment by leseb** [comment]
@mattt416 thanks, will push a PR soon :)

**Comment by leseb** [comment]
PR is here: https://github.com/ceph/ceph-ansible/pull/815
