### ISSUE TITLE
rename ceph_stable_rh_storage to ceph_stable_rhcs

### ISSUE THREAD

**Issue by leseb** [ceph/ceph-ansible#811]
From filenames to variables :)
Thanks!

**Comment by leseb** [comment]
@alfredodeza still on your plate?

**Comment by alfredodeza** [comment]
I completely forgot about this one. I can work on it this week

**Comment by leseb** [comment]
Sure, thanks!

**Comment by alfredodeza** [comment]
Why do we need "stable" in the name? Are there unstable/dev/rc variants? If so, can we just define that: `ceph_rhcs` *is* the stable and everything else (if any) can be defined as such? For example: `ceph_rc_rhcs` ?

**Comment by leseb** [comment]
I was using "stable" because we have "dev" as well.
I think `ceph_rhcs` is fine.
