### ISSUE TITLE
ceph ansible on docker

### ISSUE THREAD

**Issue by thbeh** [ceph/ceph-ansible#813]
Hi, I am following very near to the video on the above but got this when it start to process ceph-osd, anything I missed?

TASK [ceph-osd : stat for ceph config and keys] ********************************
ok: [ceph3] => (item=/etc/ceph/ceph.client.admin.keyring)
ok: [ceph4] => (item=/etc/ceph/ceph.client.admin.keyring)
ok: [ceph2] => (item=/etc/ceph/ceph.client.admin.keyring)
ok: [ceph3] => (item=/etc/ceph/ceph.conf)
ok: [ceph4] => (item=/etc/ceph/ceph.conf)
ok: [ceph2] => (item=/etc/ceph/ceph.conf)
ok: [ceph3] => (item=/etc/ceph/monmap)
ok: [ceph4] => (item=/etc/ceph/monmap)
ok: [ceph3] => (item=/etc/ceph/ceph.mon.keyring)
ok: [ceph2] => (item=/etc/ceph/monmap)
ok: [ceph4] => (item=/etc/ceph/ceph.mon.keyring)
ok: [ceph3] => (item=/var/lib/ceph/bootstrap-osd/ceph.keyring)
ok: [ceph2] => (item=/etc/ceph/ceph.mon.keyring)
ok: [ceph4] => (item=/var/lib/ceph/bootstrap-osd/ceph.keyring)
ok: [ceph3] => (item=/var/lib/ceph/bootstrap-rgw/ceph.keyring)
ok: [ceph4] => (item=/var/lib/ceph/bootstrap-rgw/ceph.keyring)
ok: [ceph2] => (item=/var/lib/ceph/bootstrap-osd/ceph.keyring)
ok: [ceph3] => (item=/var/lib/ceph/bootstrap-mds/ceph.keyring)
ok: [ceph4] => (item=/var/lib/ceph/bootstrap-mds/ceph.keyring)
ok: [ceph2] => (item=/var/lib/ceph/bootstrap-rgw/ceph.keyring)
ok: [ceph2] => (item=/var/lib/ceph/bootstrap-mds/ceph.keyring)

TASK [ceph-osd : fail if we find existing cluster files] ***********************
[DEPRECATION WARNING]: Using bare variables is deprecated. Update your playbooks so that the environment value uses the full variable syntax ('{{statleftover.results}}').
This feature will be removed in 
a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: Using bare variables is deprecated. Update your playbooks so that the environment value uses the full variable syntax ('{{statleftover.results}}').
This feature will be removed in 
a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: Using bare variables is deprecated. Update your playbooks so that the environment value uses the full variable syntax ('{{statleftover.results}}').
This feature will be removed in 
a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
failed: [ceph2] (item=[u'/etc/ceph/ceph.client.admin.keyring', {u'stat': {u'uid': 0, u'exists': True, u'woth': False, u'mtime': 1464145298.1871, u'inode': 810562288, u'isgid': False, u'size': 137, u'roth

**Comment by leseb** [comment]
Is it a left over from a previous attemps?
