### ISSUE TITLE
/var/run/ceph is not boot persistent

### ISSUE THREAD

**Issue by OrFriedmann** [ceph/ceph-ansible#817]
Every reboot this folder wiped(cause /var/run is mounted to tmpfs) and return error each command I run in the cluster.
My solution is to add mkdir -p /var/run/ceph in the rc file.
What do you think about this?

Thank you

**Comment by leseb** [comment]
We discussed that in #278, this is a systemd thing that can be configured in systemd.
But the old good rc file is good too.

**Comment by OrFriedmann** [comment]
Thank you
