### ISSUE TITLE
Hangs on 'TASK [ceph-mon : collect admin and bootstrap keys' 

### ISSUE THREAD

**Issue by maxtortime** [ceph/ceph-ansible#818]
It doesn't have a problem when box is ubuntu/trusty64,
but I have a problem when box is ubuntu/wily64.

Also when first provision , it fails by 404 error (cannot find on download.ceph.com)

Thanks.

**Comment by leseb** [comment]
I suppose the monitor didn't start, can you confirm?

**Comment by maxtortime** [comment]
I think so too, But how can I start monitor manually?
Had I better to use command at [here](http://docs.ceph.com/docs/jewel/rados/operations/operating/)
Sorry for my short knowledge of Ceph.

Now, I resolved this problem by upgrading each node's kernel manually after provision.

**Comment by leseb** [comment]
So the issue went away after a kernel upgrade?

**Comment by maxtortime** [comment]
I'll explain my whole work here.

Firstly, I wanted to use ubuntu/wily64 box instead of default box(ubuntu/trusty64).
So I changed 'vagrant_variables.yml'' like below.
```yml
vagrant_box: ubuntu/wily64
```
And then I run 'vagrant up --no-provision' and 'vagrant provision'
But it hangs out at below
```
TASK [ceph-mon : collect admin and bootstrap keys]
```
Therefore, I returned 'vagrant_box' to 'ubuntu/trusty64' normally and run 'vagrant up' again.
I mean that I upgraded trusty64 box's kernel.

**Comment by leseb** [comment]
Ok now I understand, this is likely yet another problem with systemd.
Let me have a look.

**Comment by leseb** [comment]
Looks like `xenial64` has currently an issue to run.
Just use trusty if you use vagrant or centos 7 if you want a systemd based system

**Comment by masterdubs** [comment]
Check if the firewall is running !
