### ISSUE TITLE
Centos 7 install error

### ISSUE THREAD

**Issue by rlljorge** [ceph/ceph-ansible#820]
Hello !

This is my first deployment using ceph-ansible and is my first deployment using ansible too.

GATHERING FACTS ***************************************************************
ok: [osd02]
ok: [osd01]
ok: [osd03]

TASK: [ceph.ceph-common | fail on unsupported system] *************************
skipping: [osd01]
skipping: [osd02]
skipping: [osd03]

TASK: [ceph.ceph-common | fail on unsupported architecture] *******************
skipping: [osd01]
skipping: [osd02]
skipping: [osd03]

the full log are on http://pastebin.com/enErnEQT.

**Comment by bdastur** [comment]
@rlljorge from the error it looks like you are missing some config in the group_vars/osd file.
Have you set the following parameters.
journal_collocation:
devices:

regards,

**Comment by rlljorge** [comment]
@bdastur I had already set this on config files:

root@deploy:/opt/ceph-ansible# grep "^[^#;]" group_vars/osds
---
devices:
  - /dev/sdc
  - /dev/sdd
  - /dev/sde
 
raw_multi_journal: true
raw_journal_devices:
  - /dev/sda
  - /dev/sdb
  - /dev/sda
