### ISSUE TITLE
Mon and Osd same server

### ISSUE THREAD

**Issue by rlljorge** [ceph/ceph-ansible#829]
Can I put Monitor and Osd at same server ? 

root@deploy:/opt/ceph-ansible# cat /etc/ansible/hosts
[osds]
osd01
osd02
osd03

[mons]
osd01
osd02
osd03

I recive this error:

TASK: [ceph.ceph-common | make sure an osd scenario was chosen] *************** 
fatal: [osd01] => error while evaluating conditional: not journal_collocation
fatal: [osd02] => error while evaluating conditional: not journal_collocation
fatal: [osd03] => error while evaluating conditional: not journal_collocation

FATAL: all hosts have already failed -- aborting

but I configured the journal location :

```
root@deploy:/opt/ceph-ansible# grep "^[^#;]" group_vars/osds
---
devices:
  - /dev/sdc
  - /dev/sdd
  - /dev/sde
raw_multi_journal: true
raw_journal_devices:
  - /dev/sda
  - /dev/sda
  - /dev/sdb

```
What is my error ?

**Comment by leseb** [comment]
Yes you can put MONs and OSDs on the same servers.
You're currently seeing this issue https://github.com/ceph/ceph-ansible/pull/805
Pending fix, sorry for the pain.

**Comment by leseb** [comment]
Should be fixed now.
