### ISSUE TITLE
Serial note for OSDs

### ISSUE THREAD

**Issue by leseb** [ceph/ceph-ansible#830]
From JC:
This is an actual problem to run all hosts in // as the OSD IDs will get screwed up across nodes for an environment you want industrial and easily manageable. There should be an option to avoid that.

**Comment by civik** [comment]
👍 for this.  Just came here to post this issue.  

Not only for the sequential OSD numbering, I'm actually seeing some kind of race condition where the play creates init files for OSDs that are on other hosts - resulting in errors like this in subsequent playbook runs:

`=== osd.2 ===
2016-07-01 15:50:42.737929 7ff7243a6700  0 librados: osd.2 authentication error (1) Operation not permitted
Error connecting to cluster: PermissionError
failed: 'timeout 30 /usr/bin/ceph -c /etc/ceph/ceph.conf --name=osd.2 --keyring=/var/lib/ceph/osd/ceph-2/keyring osd crush create-or-move -- 2 0.44 host=g2-ceph-05 root=default'`

**Comment by civik** [comment]
Perhaps an option to set the `serial:` parameter in the site.yml for osd hosts?

**Comment by leseb** [comment]
@civik yup doing `serial: 1` should be sufficient.
