### ISSUE TITLE
consolidate docker/pre_requisites.yaml

### ISSUE THREAD

**Issue by rootfs** [ceph/ceph-ansible#842]
Each role has its own (yet mostly the same) pre_requisites.yaml, making it hard to update. It is ideal to consolidate them into one place.

**Comment by leseb** [comment]
Yeah i've been thinking about that too as it's really painful and dumb to copy/paste the content to each roles.
I think the logic should go in `ceph-common`, at some point we were discussing with @dang to do a lot of the container configuration upfront using ansible and then just let the container entrypoint start the process.
I think it makes a lot of sense and greatly simplifies the code, we have all the necessary bits in ceph-ansible to configure/populate ceph directories (daemons bootstraps in /var/lib/ceph/) so we don't need to replicate that logic in bash entrypoints :). Well we have been doing this actually but we should stop now :p 
The use case is valid for everything expect k8s where I don't think we can plug ansible.

**Comment by leseb** [comment]
Done.
