### ISSUE TITLE
Option to enable ntp

### ISSUE THREAD

**Issue by font** [ceph/ceph-ansible#845]
After the ansible playbook completed successfully a `ceph -s` indicated a `HEALTH_WARN` due to a clock skew being detected on the mon instances. This warning was valid as ceph detected a clock skew larger than the default threshold of 0.05 seconds:

`[root@ceph-mon0 ~]# ceph health detail`
`HEALTH_WARN clock skew detected on mon.ceph-mon1, mon.ceph-mon2; Monitor clock skew detected`
`mon.ceph-mon1 addr 192.168.121.156:6789/0 clock skew 0.318922s > max 0.05s (latency 0.000729135s)`
`mon.ceph-mon2 addr 192.168.121.157:6789/0 clock skew 0.240514s > max 0.05s (latency 0.000675196s)`

I noticed that the ntp package is installed as part of the playbook, but ntpd is not enabled nor started. Once I started ntpd all was well.

Can I add an option to the playbook to enable/start the ntp service?

**Comment by leseb** [comment]
Yes you can, please submit a PR :)
Thanks!

**Comment by maxtortime** [comment]
I think only one server syncs with ntp server and another servers follow synced server.
But I don't know fixing what code.

**Comment by leseb** [comment]
This is a bit too much for this repository, remember we only deploy Ceph and don't take over the world :).
In your infrastructure you should have a NTP playbook that configures a NTP server and followers.

The least we can do in our repo is making sure NTP is started on all the node.

**Comment by mattt416** [comment]
Agreed -- I'd prefer to see the enablement of ntp left out of this repo.
