### ISSUE TITLE
Define interface for RGW

### ISSUE THREAD

**Issue by ksingh7** [ceph/ceph-ansible#847]
My RGW nodes have multiple active interfaces, so is there a legitimate way in ceph-ansible to define interface which we want to use for RGW ?

group_vars/all `radosgw_civetweb_bind_ip: "{{ ansible_default_ipv4.address }}"` does not solve the purpose

Something similar to `monitor_interface: interface`would be useful

**Comment by leseb** [comment]
If you know the IP address of the specific interface you could (at least for now) populate your inventory file with something like:

```
[rgws]
ceph-rgw-01 radosgw_civetweb_bind_ip: x.x.x.x
ceph-rgw-02 radosgw_civetweb_bind_ip: x.x.x.x
ceph-rgw-03 radosgw_civetweb_bind_ip: x.x.x.x
```

Ultimately we will need something similar to `monitor_interface` I agree.

**Comment by hroogi** [comment]
Where we need to add these IP addresses? I mean which file?
We are facing similar issue.

**Comment by leseb** [comment]
@hroogi in your inventory file.
Default is `/etc/ansible/hosts`.

**Comment by hroogi** [comment]
@leseb Thank you. It worked.

**Comment by leseb** [comment]
I don't think we will ever have a dedicated feature like `monitor_interface`, using  `/etc/ansible/hosts` ansible inventory file is fine.
