### ISSUE TITLE
question 

### ISSUE THREAD

**Issue by thbeh** [ceph/ceph-ansible#863]
I notice that in group_vars/all the mon ip is set for eth1. is the the interface that mons communicate with the osds? if so what happen if some of my osds have only 1 interface namely eth0?

**Comment by rootfs** [comment]
The mon interface is important because osds need to know where mon is.  As long as osd can communicate to mon's ip and osd's ip is in the private network, single osd interface is ok.

**Comment by dang** [comment]
You can set it to whatever interface you want.  It's used to get the IP address that should be in the ceph.conf file.

**Comment by thbeh** [comment]
So does that mean it is ok for me to set mons listening at eth1 and osds listening at eth0?

**Comment by dang** [comment]
It should work fine, yes.

**Comment by leseb** [comment]
@thbeh if they share the same subnet then yes the interface name does not matter.
