### ISSUE TITLE
why use both `--mbrtogpt` and `-g` option for sgdisk?

### ISSUE THREAD

**Issue by chengweiv5** [ceph/ceph-ansible#896]
I found that both `--mbrtogpt` and `-g` option for sgdisk, but as I can tell from the sgdisk help info, they are just the same.

```
  -g, --mbrtogpt                                                       convert MBR to GPT
```

So should I submit a PR to remove `-g`?

**Comment by leseb** [comment]
Correct, yes please submit a PR.
