### ISSUE TITLE
One or more undefined variables: 'host' is undefined

### ISSUE THREAD

**Issue by chengweiv5** [ceph/ceph-ansible#897]
I am trying to setup a ceph cluster with ceph-ansible, however it always fail with below error:

```
TASK: [ceph.ceph-common | generate ceph configuration file] ******************* 
fatal: [xxxx] => One or more undefined variables: 'host' is undefined
```

I just copied site.yml.sample to site.yml without any change and my inventory file looks like below

```
[mons]
ceph-mon1

[osds]
ceph-osd1

[hosts:children]
mons
osds

[hosts:vars]
cluster=ceph-cluster
fsid=bf6fa9e4-56db-481e-8585-29f0c8317773
```

I found that if I manually define `host=` for every node, it will works fine, but I think this isn't the correct way to do that?

**Comment by leseb** [comment]
@chengweiv5 can you try to add:

```
- hosts: all
  tasks: []
```

to your `site.yml`?

**Comment by chengweiv5** [comment]
thanks @leseb , that does work! As previous I add `host={{ inventory_hostname }}` to my group_vars/all as a workaround, hope that didn't do any harm.
