### ISSUE TITLE
Hammer Install Fails Because Repo is no Longer Valid

### ISSUE THREAD

**Issue by jsaintrocc** [ceph/ceph-ansible#917]
When installing Hammer, the `ceph-release` package installed from http://download.ceph.com/rpm-hammer/el7/noarch/ceph-release-1-0.el7.noarch.rpm has an invalid baseurl "http://ceph.com/rpm-hammer/rhel7/$basearch".  The workaround is to change the baseurl to "http://download.ceph.com/rpm-hammer/el7/$basearch"

I've created a ticket with the ceph devops folks to resolve this on their side: http://tracker.ceph.com/issues/16916

**Comment by leseb** [comment]
Thanks @jsaintrocc, please close this one as soon as the issue is solved upstream :).

**Comment by jsaintrocc** [comment]
Hey leseb,

Confirmed that the repo issue is resolved.  Closing this ticket.

**Comment by leseb** [comment]
Thanks @jsaintrocc!
