### ISSUE TITLE
ceph.ceph-osd generates false positive result

### ISSUE THREAD

**Issue by Alfano93** [ceph/ceph-ansible#921]
If on the initial deployment of ceph an error causes the playbook to terminate in the role ceph.ceph-osd between tasks "prepare osd disk(s)" and "activate osd(s) when device is a disk" , a second run of the playbook without cleaning the drives will result in a false positive in where the osd cluster is not created. 

A check that the osd cluster is actually created before the recap portion, or a check for existing file systems on the osds would prevent issues farther along the deployment process.

**Comment by Alfano93** [comment]
specifically, the ceph.ceph-osd role between task "prepare osd disk(s) and task "activate osd(s) when device is a disk"

**Comment by leseb** [comment]
If there is an error the play will stop. What was the error?

So just to be clear, the first run failed, the second run completed successfully but OSD were not populated. Correct.

**Comment by Alfano93** [comment]
That is correct. The first run failed, and the second run completed successfully but OSD were not populated. As far as the error that made the play stop, it was caused by the ssh connection being lost while executing the playbooks. Possibly a hiccup with the VPN.

**Comment by leseb** [comment]
Any chance to give it another try?

**Comment by Alfano93** [comment]
The playbooks have been run a couple of times since. Each time the osd cluster is not created. However, the problem isn't so much that the cluster isn't getting created (that much is most likely user error to be honest), rather the problem is that the playbooks seem to pass whether or not an osd cluster is created or not.

**Comment by leseb** [comment]
I agree we are losing the idempotency here. We should probably include some post-install checks.
I had a first attempt here: https://github.com/ceph/ceph-ansible/tree/master/tests but then I was thinking we should use  teuthology for QA.

**Comment by Alfano93** [comment]
We are actually still trying to track down the error. After figuring out that the cluster wasn't created, we've zapped all of the disks and are attempting to set up an initial cluster with our normal (ssd's for the journals, sas for the data storage) nodes and then move onto the more unique nodes (ssd's for both journals and data storage).

**Comment by leseb** [comment]
Don't hesitate to pass your error here, usually if "prepare" fails it's due to disks problems.
Usually zapping the disks should fix the issues.

**Comment by Alfano93** [comment]
Just to close the loop, we were having problems with the ceph ports being closed so our cluster couldn't talk to our monitors.

**Comment by leseb** [comment]
We could have detected that earlier, while running the playbook for the first time it is usually recommended to set `check_firewall: true`. If nmap is installed this will test open ports.
I'm closing this, feel free to re-open.
