### ISSUE TITLE
playbook loop on osd

### ISSUE THREAD

**Issue by mistur** [ceph/ceph-ansible#940]
Hello,

I have a loop on ceph-osd task when I try to apply the playbook 

ansible-playbook -i cluster-cephprod site.yml

here the details of the configuration

[cluster-cephprod.tar.gz](https://github.com/ceph/ceph-ansible/files/422965/cluster-cephprod.tar.gz)

[ceph-ansible.log.gz](https://github.com/ceph/ceph-ansible/files/422968/ceph-ansible.log.gz)

is there something wrong in my configuration ?

here the list of the task :

$ grep "\[ceph-.*:" ceph-ansible.log
TASK [ceph-mon : generate monitor initial keyring] *****************************
TASK [ceph-mon : read monitor initial keyring if it already exists] ************
TASK [ceph-mon : set_fact] *****************************************************
TASK [ceph-mon : set_fact] *****************************************************
TASK [ceph-mon : create monitor initial keyring] *******************************
TASK [ceph-mon : set initial monitor key permissions] **************************
TASK [ceph-mon : create monitor directory] *************************************
TASK [ceph-mon : ceph monitor mkfs with keyring (for or after infernalis release)] ***
TASK [ceph-mon : ceph monitor mkfs without keyring (for or after infernalis release)] ***
TASK [ceph-mon : ceph monitor mkfs with keyring (before infernalis release)] ***
TASK [ceph-mon : ceph monitor mkfs without keyring (before infernalis release)] 
TASK [ceph-mon : activate monitor with upstart] ********************************
TASK [ceph-mon : start and add that the monitor service to the init sequence (ubuntu)] ***
TASK [ceph-mon : start and add that the monitor service to the init sequence] **
TASK [ceph-mon : start and add that the monitor service to the init sequence (for or after infernalis)] ***
TASK [ceph-mon : start the monitor service (for or after infernalis)] **********
TASK [ceph-mon : collect admin and bootstrap keys] *****************************
TASK [ceph-mon : wait for client.admin key exists] *****************************
TASK [ceph-mon : create ceph rest api keyring when mon is not containerized] ***
TASK [ceph-mon : create openstack pool] ****************************************
TASK [ceph-mon : create openstack keys] ****************************************
TASK [ceph-mon : find ceph keys] ***********************************************
TASK [ceph-mon : set keys permissions] *****************************************
TASK [ceph-mon : copy keys to the ansible server] ******************************
TASK [ceph-mon : drop in a motd script to report status when logging in] *******
TASK [ceph-mon : create filesystem pools] **************************************
TASK [ceph-mon : create ceph filesystem] ***************************************
TASK [ceph-mon : collect all the pools] ****************************************
TASK [ceph-mon : secure the cluster] *******************************************
TASK [ceph-mon : check if a cluster is already running] ************************
TASK [ceph-mon : check if it is Atomic host] ***********************************
TASK [ceph-mon : set fact for using Atomic host] *******************************
TASK [ceph-mon : set config and keys paths] ************************************
TASK [ceph-mon : stat for ceph config and keys] ********************************
TASK [ceph-mon : fail if we find existing cluster files] ***********************
TASK [ceph-mon : install pip and docker on ubuntu] *****************************
TASK [ceph-mon : install pip and docker on debian] *****************************
TASK [ceph-mon : install epel-release on redhat] *******************************
TASK [ceph-mon : install pip on redhat] ****************************************
TASK [ceph-mon : install docker-engine on redhat] ******************************
TASK [ceph-mon : install docker on redhat] *************************************
TASK [ceph-mon : install pip and docker on redhat (dnf)] ***********************
TASK [ceph-mon : install six] **************************************************
TASK [ceph-mon : pause after docker install before starting (on openstack vms)] 
TASK [ceph-mon : start docker service] *****************************************
TASK [ceph-mon : install docker-py] ********************************************
TASK [ceph-mon : install docker-py] ********************************************
TASK [ceph-mon : install ntp on redhat using yum] ******************************
TASK [ceph-mon : install ntp on redhat using dnf] ******************************
TASK [ceph-mon : install ntp on debian] ****************************************
TASK [ceph-mon : include] ******************************************************
TASK [ceph-mon : include] ******************************************************
TASK [ceph-mon : include] ******************************************************
TASK [ceph-mon : include] ******************************************************
TASK [ceph-mon : inspect ceph version] *****************************************
TASK [ceph-mon : set_fact] *****************************************************
TASK [ceph-mon : create bootstrap directories (for or before hammer)] **********
TASK [ceph-mon : create bootstrap directories (after hammer)] ******************
TASK [ceph-mon : create a local fetch directory if it does not exist] **********
TASK [ceph-mon : generate cluster uuid] ****************************************
TASK [ceph-mon : read cluster uuid if it already exists] ***********************
TASK [ceph-mon : generate ceph configuration file] *****************************
TASK [ceph-mon : set config and keys paths] ************************************
TASK [ceph-mon : stat for ceph config and keys] ********************************
TASK [ceph-mon : try to fetch ceph config and keys] ****************************
TASK [ceph-mon : check if selinux is enabled] **********************************
TASK [ceph-mon : set selinux permissions] **************************************
TASK [ceph-mon : populate kv_store with default ceph.conf] *********************
TASK [ceph-mon : populate kv_store with custom ceph.conf] **********************
TASK [ceph-mon : delete populate-kv-store docker] ******************************
TASK [ceph-mon : generate systemd unit file] ***********************************
TASK [ceph-mon : enable systemd unit file for mon instance] ********************
TASK [ceph-mon : reload systemd unit files] ************************************
TASK [ceph-mon : systemd start mon container] **********************************
TASK [ceph-mon : wait for ceph.conf exists] ************************************
TASK [ceph-mon : run the ceph monitor docker image] ****************************
TASK [ceph-mon : run the ceph monitor docker image with kv] ********************
TASK [ceph-mon : push ceph files to the ansible server] ************************
TASK [ceph-mon : create ceph rest api keyring when mon is containerized] *******
TASK [ceph-mon : install calamari server] **************************************
TASK [ceph-mon : install calamari server] **************************************
TASK [ceph-mon : initialize the calamari server api] ***************************
TASK [ceph-osd : install debian dependencies] **********************************
TASK [ceph-osd : install redhat dependencies via yum] **************************
TASK [ceph-osd : install redhat rependencies via dnf] **************************
TASK [ceph-osd : create bootstrap-osd directory] *******************************
TASK [ceph-osd : copy ceph admin key when using dmcrypt] ***********************
TASK [ceph-osd : copy osd bootstrap key] ***************************************
TASK [ceph-osd : check if the device is a partition] ***************************
TASK [ceph-osd : check if the device is a partition (autodiscover disks)] ******
TASK [ceph-osd : combine ispartition results] **********************************
TASK [ceph-osd : check the partition status of the osd disks] ******************
TASK [ceph-osd : check the partition status of the osd disks (autodiscover disks)] ***
TASK [ceph-osd : combine osd_partition_status results] *************************
TASK [ceph-osd : check the partition status of the journal devices] ************
TASK [ceph-osd : fix partitions gpt header or labels of the osd disks] *********
TASK [ceph-osd : fix partitions gpt header or labels of the osd disks (autodiscover disks)] ***
TASK [ceph-osd : fix partitions gpt header or labels of the journal devices] ***
TASK [ceph-osd : check if a partition named 'ceph' exists] *********************
TASK [ceph-osd : check if a partition named 'ceph' exists (autodiscover disks)] 
TASK [ceph-osd : combine parted results] ***************************************
TASK [ceph-osd : automatic prepare osd disk(s) without partitions] *************
TASK [ceph-osd : manually prepare osd disk(s)] *********************************
TASK [ceph-osd : automatically activate osd disk(s) without partitions] ********
TASK [ceph-osd : activate osd(s) when device is a disk] ************************
TASK [ceph-osd : automatically activate osd disk(s) without partitions (dmcrypt)] ***
TASK [ceph-osd : activate osd(s) when device is a disk (dmcrypt)] **************
TASK [ceph-osd : combine ispartition results] **********************************
TASK [ceph-osd : fail if ceph-disk cannot create an OSD] ***********************
TASK [ceph-osd : activate osd(s) when device is a partition] *******************
TASK [ceph-osd : get osd path] *************************************************
TASK [ceph-osd : get osd id] ***************************************************
TASK [ceph-osd : get osd id for directory scenario] ****************************
TASK [ceph-osd : combine osd_path results] *************************************
TASK [ceph-osd : create a ceph fragment and assemble directory] ****************
TASK [ceph-osd : create the osd fragment] **************************************
TASK [ceph-osd : copy cephprod.conf for assembling] ****************************
TASK [ceph-osd : assemble osd sections] ****************************************
TASK [ceph-osd : assemble cephprod.conf and osd fragments] *********************
TASK [ceph-osd : set selinux to permissive and make it persistent] *************
TASK [ceph-osd : start and add that the osd service(s) to the init sequence (before infernalis)] ***
TASK [ceph-osd : get osd id (for or after infernalis)] *************************
TASK [ceph-osd : enable the osd service (for or after infernalis)] *************
TASK [ceph-osd : start and add that the osd service(s) to the init sequence (for or after infernalis)] ***
TASK [ceph-osd : check if the device is a partition] ***************************
TASK [ceph-osd : check if the device is a partition (autodiscover disks)] ******
TASK [ceph-osd : combine ispartition results] **********************************
TASK [ceph-osd : check the partition status of the osd disks] ******************
TASK [ceph-osd : check the partition status of the osd disks (autodiscover disks)] ***
TASK [ceph-osd : combine osd_partition_status results] *************************
TASK [ceph-osd : check the partition status of the journal devices] ************
TASK [ceph-osd : fix partitions gpt header or labels of the osd disks] *********
TASK [ceph-osd : fix partitions gpt header or labels of the osd disks (autodiscover disks)] ***
TASK [ceph-osd : fix partitions gpt header or labels of the journal devices] ***
TASK [ceph-osd : check if a partition named 'ceph' exists] *********************
TASK [ceph-osd : check if a partition named 'ceph' exists (autodiscover disks)] 
TASK [ceph-osd : combine parted results] ***************************************
TASK [ceph-osd : prepare osd disk(s)] ******************************************
TASK [ceph-osd : automatically activate osd disk(s) without partitions] ********
TASK [ceph-osd : activate osd(s) when device is a disk] ************************
TASK [ceph-osd : automatically activate osd disk(s) without partitions (dmcrypt)] ***
TASK [ceph-osd : activate osd(s) when device is a disk (dmcrypt)] **************
TASK [ceph-osd : combine ispartition results] **********************************
TASK [ceph-osd : fail if ceph-disk cannot create an OSD] ***********************
TASK [ceph-osd : activate osd(s) when device is a partition] *******************

**Comment by mistur** [comment]
I forgot few element :

- ceph-ansible is uptodate
- running ansible on Ubuntu 14.04.4 LTS
- target is ceph jewel on Ubuntu 16.04 LTS
- ansible 2.1.1.0
- Python 2.7.6

**Comment by jsaintro** [comment]
Just skimmed your config.  I see that your combining multiple roles on the same nodes.  In the past I've seen the logic mess up when roles are combined on the same nodes (For me it was the client and osd role).  You may want test out putting the roles on different nodes.  I bet if you use nodes for exclusively for the OSD role it won't cause a loop.

Also I'd highly recommend you put the MONs on separate HW from the OSD's.  If you're OSD's get overloaded they will start killing the MONs which will definitely cause you to loose some sleep ;-).

**Comment by mistur** [comment]
moving MONs on other hardware is not an option right now, we have enouph CPU/RAM on the server. 

We have reinstalled the cluster from scratch and now, there in no loop anymore and we cannot reproduce the issue.

We can close.

Thanks.
