### ISSUE TITLE
Low priority: How to use the ceph_conf_overrides: in the group_Vars/all

### ISSUE THREAD

**Issue by OrFriedmann** [ceph/ceph-ansible#942]
Hi there,

I want to add a line in the ceph.conf 
under the mon section
`mon compact on start = true`

I did not understand how to use the variable below to do that.
ceph_conf_overrides:
#   global:
#     foo: 1234
#     bar: 5678

Thank you very much

**Comment by leseb** [comment]
Hi,

Here you go:

```
ceph_conf_overrides:
  mon:
    mon_compact_on_start: true
```
