### ISSUE TITLE
add more parameters to ceph.conf file using ceph-ansible

### ISSUE THREAD

**Issue by pujamud** [ceph/ceph-ansible#943]
I wanted to add more parameters to ceph.conf file using ceph-ansible.
There are some additional settings that do not existsin the current all,osds and mons files.
If I make entries of these parameters in all,osds or mons file it does not consider these additional settings after the run is completed. I need to know a way in ceph-ansible script where after adding these parameters it reflects in ceph.conf file post installation.

**Comment by leseb** [comment]
Use config override for that: https://github.com/ceph/ceph-ansible/blob/master/group_vars/all.sample#L312-L327
