### ISSUE TITLE
using multiple OSDs per SSD

### ISSUE THREAD

**Issue by pujamud** [ceph/ceph-ansible#944]
I need to know if it's possible to edit ceph-ansible to use multiple OSDs per SSD. 
If that is possible then what are the configuration changes that will be required.

**Comment by leseb** [comment]
Use this: https://github.com/ceph/ceph-ansible/blob/master/group_vars/osds.sample#L88-L103

And read this a bit: https://github.com/ceph/ceph-ansible/wiki

**Comment by pujamud** [comment]
So this allows you to create journal on a separate device. What I want is if we could have multiple partitions on the same device for more then on set of data and journal.
Right now if I select journal_collocation=true and set the devices, it partitions one device i.e /dev/sda as data and journal for one OSD, then for other OSD it uses 2nd device.

**Comment by leseb** [comment]
Hum setting `devices` like: /dev/sdb1, /dev/sdb2 *should* work, give it a try.

**Comment by pujamud** [comment]
I had tried this earlier but it does not work. Infact in groupvars/osds file under devices section it is mentioned that "Ceph-disk has a built in check which looks for empty devices.Thus devices with existing partition tables will not be used."

Hence wanted to know if ceph-ansible supports this feature.

**Comment by pujamud** [comment]
Something like this I had used:
devices:
- /dev/nvme0n1p1
-/dev/nvme0n1p2

After running ceph-ansible it did not use these existing partitions and hence OSDs were not created.

**Comment by leseb** [comment]
What you could try is to mount your partition and then use the directory scenario by specifying osd paths.
