### ISSUE TITLE
I need to set pool  name in ceph-ansible. I couldnt find any specific parameter to do so.

### ISSUE THREAD

**Issue by pujamud** [ceph/ceph-ansible#946]

**Comment by leseb** [comment]
Ansible does not create pools for you.
Use the: `ceph osd pool create` command for this.

**Comment by pujamud** [comment]
Thank you

**Comment by msalmanmasood** [comment]
how to define custom pools at the time of ceph cluster deployment?

**Comment by leseb** [comment]
@msalmanmasood it's marked as openstack but works with anything, please see: https://github.com/ceph/ceph-ansible/blob/master/group_vars/mons.yml.sample#L77-L121
