### ISSUE TITLE
RBD pool issue

### ISSUE THREAD

**Issue by pujamud** [ceph/ceph-ansible#949]
Hello Team,

I used config override option in ceph-ansible to add extra parameter but unfortunately it did not work.
When I check ceph osd dump it showed me a value as pgp_num 64 whereas I had set it to 4096.

Please can someone help me in this

**Comment by leseb** [comment]
The value only affects **new created** pools, it won't change existing pool PGs.

**Comment by pujamud** [comment]
Does this mean that ceph-ansible would not use any extra parameters specified to create default pools?
Which means do I need to manually assign these values to the existing rbd pool ?

**Comment by leseb** [comment]
Yes, this is a long standing issue with the rbd pool, usually during bootstrap the pool should a number of PG equal to number specified in `osd_pool_default_size`, for some reasons this is not the case. We can leave this open and investigate later. Please rename the title of the issue to point to the rbd pool.

**Comment by pujamud** [comment]
Thanks for this information. I have changed the title to "RBD pool issue"

**Comment by leseb** [comment]
@pujamud Thanks!

**Comment by leseb** [comment]
Implemented https://github.com/ceph/ceph-ansible/pull/1043
