### ISSUE TITLE
MAC address get concatenated in OSDs with vagrant-libvirt 0.0.35

### ISSUE THREAD

**Issue by rassie** [ceph/ceph-ansible#952]
I've tried setting up CEPH using `ceph-ansible` with `vagrant-libvirt`. However, I've got errors setting up OSDs about MAC address on the `eth2` interface being different from what was expected. I've debugged a bit and found out that those MAC addresses are two MACs each, concatenated (so the error message is correct). The problem is that `vagrant-libvirt` 0.0.35 uses an XPath expression to query the MAC from `libvirt`'s XML: `"/domain/devices/interface[source[@network='#{@network_name}']]/mac/@address"` (change came in in commit https://github.com/vagrant-libvirt/vagrant-libvirt/commit/ee7afab369dc7e80128ff35a2ff11f6eab23d368). However, this is how the XML for an OSD looks like:

```
    <interface type='network'>
      <mac address='52:54:00:c9:8b:13'/>
      <source network='ceph-ansible0' bridge='virbr2'/>
      <target dev='vnet3'/>
      <model type='virtio'/>
      <alias name='net1'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x08' function='0x0'/>
    </interface>
    <interface type='network'>
      <mac address='52:54:00:7a:9b:4c'/>
      <source network='ceph-ansible0' bridge='virbr2'/>
      <target dev='vnet4'/>
      <model type='virtio'/>
      <alias name='net2'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x09' function='0x0'/>
    </interface>
```

As you can see, both interfaces (`eth1` and `eth2`) have the same source network name, so that the XPath expression actually returns two addresses, which is not caught by `vagrant-libvirt` (so a bug report is due there as well).

So the question is basically (apart from `vagrant-libvirt`'s parsing): is this (probably default) network naming correct? If not, could this be changed?

**Comment by leseb** [comment]
I personally don't use `vagrant-libvirt` and I'm not sure why both interfaces have the same network name. If you can find the appropriate syntax to change the network name then I'm fine putting a change in the `Vagrantfile`.

**Comment by font** [comment]
Perfect timing as I had just filed https://github.com/vagrant-libvirt/vagrant-libvirt/issues/645 because I noticed the same error where `eth2` for OSDs end up with a DHCP address instead of the statically defined one `XXX.XXX.XXX.20X`. Defining a different network name for each private network interface on the OSDs could probably be a workaround. Otherwise they just fallback to DHCP.
