### ISSUE TITLE
Ubuntu 16.04 nfs-ganesha - Unable to locate package nfs-ganesha

### ISSUE THREAD

**Issue by OrFriedmann** [ceph/ceph-ansible#964]
Hi,
Could you consider to add `sudo add-apt-repository ppa:gluster/nfs-ganesha`
to solve this?

Thank you

**Comment by leseb** [comment]
Sure.

**Comment by OrFriedmann** [comment]
I have to reopen this issue there is a problem with the nfs-ganesha in ubuntu, the package of fsal rgw is not exist(of course we have the source but...).

Failed to load FSAL (RGW) because: Can not access a needed shared library
Failed to load module (/usr/lib/x86_64-linux-gnu/ganesha/libfsalrgw.so) because: Can not access a needed shared library

Ubuntu 16.04
Ceph 10.2.5
nfs-ganesha 2.4.1

**Comment by leseb** [comment]
This is not a problem with ceph-ansible. So let's keep it closed and track this on the Ubuntu package maintainer side.
