### ISSUE TITLE
multisite rgw: getting 403 error

### ISSUE THREAD

**Issue by OrFriedmann** [ceph/ceph-ansible#965]
Hi,
I am using Ubuntu 16.04 and Jewel 10.2.2
I have deployed 2 clusters using ansible and configure multisite.
While both clusters were working, replication was not.
After I looked at the /var/log of the secondary cluster I saw that I got the error 403.
My conclusion was that there is no system user on the remote site and after create it and restart the services, everything works fine.
I believe that we should add  system user creation in the secondary site.

Thank you

**Comment by leseb** [comment]
@OrFriedmann Thanks for reporting this, sounds like an easy fix, would mind sending a PR for this?

**Comment by symbatkarzhassov** [comment]
Hello, OrFriedmann. I have the same problem. But when I try to create system user on secondary zone it says me that a can do it on master. How you create user? Can you write command?
