### ISSUE TITLE
ImportError: librados.so.2: cannot map zero-fill pages: Cannot allocate memory

### ISSUE THREAD

**Issue by dixudx** [ceph/ceph-ansible#968]
I followed the README and tried to setup Ceph with Vagrant using virtualbox provider.

However below failures occurred when ansible run playbooks against mon[0-2] node.

> TASK [ceph.ceph-common : get ceph version] *************************************
fatal: [mon0]: FAILED! => {"changed": false, "cmd": ["ceph", "--version"], "delta": "0:00:00.042944", "end": "2016-08-31 15:19:19.375636", "failed": true, "rc": 1, "start": "2016-08-31 15:19:19.332692", "stderr": "Traceback (most recent call last):\n  File \"/usr/bin/ceph\", line 118, in <module>\n    import rados\nImportError: librados.so.2: cannot map zero-fill pages: Cannot allocate memory", "stdout": "", "stdout_lines": [], "warnings": []}
fatal: [mon1]: FAILED! => {"changed": false, "cmd": ["ceph", "--version"], "delta": "0:00:00.044416", "end": "2016-08-31 15:19:19.482945", "failed": true, "rc": 1, "start": "2016-08-31 15:19:19.438529", "stderr": "Traceback (most recent call last):\n  File \"/usr/bin/ceph\", line 118, in <module>\n    import rados\nImportError: librados.so.2: cannot map zero-fill pages: Cannot allocate memory", "stdout": "", "stdout_lines": [], "warnings": []}
fatal: [mon2]: FAILED! => {"changed": false, "cmd": ["ceph", "--version"], "delta": "0:00:00.052096", "end": "2016-08-31 15:19:19.523313", "failed": true, "rc": 1, "start": "2016-08-31 15:19:19.471217", "stderr": "Traceback (most recent call last):\n  File \"/usr/bin/ceph\", line 118, in <module>\n    import rados\nImportError: librados.so.2: cannot map zero-fill pages: Cannot allocate memory", "stdout": "", "stdout_lines": [], "warnings": []}

After ssh into mon0, still the same error.

```shell
vagrant@ceph-mon0:~$ ceph -h          
Traceback (most recent call last):
  File "/usr/bin/ceph", line 118, in <module>
    import rados
ImportError: librados.so.2: cannot map zero-fill pages: Cannot allocate memory
vagrant@ceph-mon0:~$ ceph -s
Traceback (most recent call last):
  File "/usr/bin/ceph", line 118, in <module>
    import rados
ImportError: librados.so.2: cannot map zero-fill pages: Cannot allocate memory
```

Anyone knows the reason ?

**Comment by leseb** [comment]
@dixudx I think you're running out of memory, try to use more memory for your virtual machines.

**Comment by dixudx** [comment]
@leseb Thanks for your help. Already allocated more memory. It works well.
