### ISSUE TITLE
One or more undefined variables: 'dict object' has no attribute u'ansible_bond0'

### ISSUE THREAD

**Issue by torkilt** [ceph/ceph-ansible#979]
I have 3 mons, one hardware and two virtual. They don't have the same name for their monitor_interface, so for the 2 beta we installed a month ago we did this in /etc/ansible/hosts:

[mons]
aramis monitor_interface=eno16780032
athos monitor_interface=bond0
porthos monitor_interface=eno16780032

Trying to install 2 release now gives me this error:
TASK: [ceph.ceph-common | check if monitor port is not filtered] *************\* 
fatal: [athos -> 127.0.0.1] => One or more undefined variables: 'dict object' has no attribute u'ansible_bond0'
ok: [aramis -> 127.0.0.1] => (item=aramis)
ok: [porthos -> 127.0.0.1] => (item=aramis)
fatal: [aramis -> 127.0.0.1] => One or more undefined variables: 'dict object' has no attribute u'ansible_eno16780032'
fatal: [porthos -> 127.0.0.1] => One or more undefined variables: 'dict object' has no attribute u'ansible_eno16780032'

FATAL: all hosts have already failed -- aborting

**Comment by torkilt** [comment]
I made the following change in /usr/share/ceph-ansible/roles/ceph-common/tasks/checks/check_firewall.yml to progress. 

#  local_action: shell set -o pipefail && nmap -p 6789 {{ item }} {{ hostvars[item]['ansible_' + monitor_interface]['ipv4']['address'] }} | grep -sqo filtered
  local_action: shell set -o pipefail && nmap -p 6789 {{ item }} {{ hostvars[item]['ansible_default_ipv4']['address'] }} | grep -sqo filtered

**Comment by leseb** [comment]
Well using `ansible_default_ipv4` is not the right solution to fix this.
Are you using ceph-ansible master or the red hat package?

**Comment by torkilt** [comment]
From repo   : rhel-7-server-rhscon-2-installer-rpms

**Comment by leseb** [comment]
You can also disable the fw check for now by setting: `check_firewall: false`.
I don't have a proper solution for now

**Comment by leseb** [comment]
fixed by https://github.com/ceph/ceph-ansible/pull/1045
