### ISSUE TITLE
ceph-fuse not installed for clients on non-debian machines

### ISSUE THREAD

**Issue by batrick** [ceph/ceph-ansible#985]
Specifically, I had this problem on CentOS 7.

Copied from: http://tracker.ceph.com/issues/17304

**Comment by leseb** [comment]
This is valid to me, let's add this to the `roles/ceph-common/tasks/installs/install_on_redhat.yml` and `roles/ceph-common/tasks/installs/install_rh_storage_on_debian.yml` and use `when: client_group_name in group_names`.
