### ISSUE TITLE
Add support for setting allow_multimds/max_mds

### ISSUE THREAD

**Issue by batrick** [ceph/ceph-ansible#986]
This would involve running these commands against the MDS after startup:

````
ceph fs set allow_multimds true --yes-i-really-mean-it
ceph fs set max_mds <n>
````

I think the tricky aspect of this is that it needs to happen after mds setup but requires the use of ceph admin keys (on the mons?). I'd be happy to implement this but I'm unsure how to do that.

Copied from: http://tracker.ceph.com/issues/17303

**Comment by leseb** [comment]
Put this on the mons please. Probably here: `roles/ceph-mon/tasks/create_mds_filesystems.yml`.
