### ISSUE TITLE
ceph_conf_overrides doesn't have effect on default pool after first setup

### ISSUE THREAD

**Issue by vasukulkarni** [ceph/ceph-ansible#992]
I had the overrides which set to pg values to 128 and size to 2, but the default rbd comes up with 64pgs and I believe the value has effect only for newly created pools

Expected results:
the default pools should come up with override value

**Comment by leseb** [comment]
This issue has been reported multiple times, I suspect this is an issue with ceph itself and not the playbook.
The ceph.conf is present way before the cluster is actually created.

@liewegas could this be a Ceph issue like the default pool creation doesn't honour  `osd_pool_default_pg_num` and `osd_pool_default_pgp_num`.
Thanks!

**Comment by OrFriedmann** [comment]
I can confirm that I have this issue too, only on the rbd pool.

**Comment by vasukulkarni** [comment]
@leseb can we delete default rbd pool and recreate if its a first time setup? that way ceph_conf values will be in effect, with ceph-deploy the monitor is bootstrapped only after ceph.conf is changed so we dont have the issue there.

**Comment by leseb** [comment]
@vasukulkarni yes you could potentially do this. It's the same with ceph-ansible, daemons are bootstrapped after the generation of the `ceph.conf`.
